### PR TITLE
Use new .AddAsync() in contentitem tag helper

### PR DESCRIPTION
**Pull request by giannik**
because now shapes are added async

### CODE REVIEW

**Comment by sebastienros** [comment]
Might also be better to remove the `dynamic` usage here

**Comment by jtkech** [comment]
@sebastienros 

Here we need the dynamic usage as we access dynamic props e.g. 

                    dynamic content = context.Shape;
                    string handle = content.Handle;

Then here we could just use the following where `context.Shape` is an `IShape`, and without having to add an `using`

                    await context.Shape.AddAsync(displayShape, "");

**Review by jtkech — APPROVED** [review]

**Comment by sebastienros** [comment]
I use Get property everywhere now instead of dynamic.

**Comment by jtkech** [comment]
Okay cool

Do we need to change it here? maybe better in a separate PR to also update other ones

**Comment by sebastienros** [comment]
Another is fine. I just do it when I see one. The GetProperty handles when there is no key, and can also take a default value. There is also a Try version.

**Pull request merged**
