### PR TITLE
Fix bootstrap confirm dialog with submit buttons

### LINKED ISSUE #3611: Not possible to delete content type
The new modal dialog breaks delete content type functionallity.

image

When pressing Ok the action is never performed and navigation to undefined page is taking place.

image

### PR DESCRIPTION
**Pull request by hishamco**
Fixes #3611

### CODE REVIEW

**Comment by hishamco** [comment]
Please don't make any action until I finish some other few tests

**Comment by hishamco** [comment]
Now I'm with the changes, I didn't thought that `FormValueRequired` has been used somewhere

This should work for both cases with and without using `FormValueRequired`

**Comment by hishamco** [comment]
Should I run it after or before running gulp task? coz what I understand from @sebastienros I should run the gulp after the rebase on dev and that's what I did before

**Comment by deanmarcussen** [comment]
what's happened is your node_modules is out of date - nothing in the pipeline forces an npm refresh when node modules are updated in the 'package.json' 

So with any luck 'npm -i' should refresh your node_modules. 

Do an  'npm list bootstrap' after and see if you've managed to upgrade to v4.3.1

If all else fails just delete your node_modules folders and start again

Once you've got the right node_modules version then you can run gulp

**Comment by hishamco** [comment]
@deanmarcussen when I run the `npm -i` I got this
npm1

npm2

**Comment by deanmarcussen** [comment]
My bad not near computer and command line memory failing. Try npm install

**Comment by Skrypt** [comment]
The appropriate command is the short version `npm i` or equivalent `npm install`

**Comment by hishamco** [comment]
I did `npm install`, I will update this PR soon

**Comment by hishamco** [comment]
It seems I have an odd issue with npm, hope it's fixed now ..

**Comment by deanmarcussen** [comment]
Bootstrap version looks much better.

Fyi I think I had weirdness with npm installing module dependencies (i.e. TheAdmin)
Resolved by updating npm `npm install npm@latest -g`

**Pull request merged**
