### PR TITLE
Use dropdown menu on admin top navbar for user menu

### LINKED ISSUE #3964: Logout and change password menu item in admin theme
1-in mobile view, the user name and logout menu are hidden. these are should be shown at the top of the page.

2-the seceond problem, i don't know why we don't have change password in the admin page. i think i we select service receipt, this menu and external login are shown in the layout. 

it's really useful to have change password in admin layout.

### PR DESCRIPTION
**Pull request by Skrypt**
orchard
orchard

Fixes #3964

### CODE REVIEW

**Comment by hishamco** [comment]
Screenshot please

**Comment by Skrypt** [comment]
Not finished yet

**Comment by hishamco** [comment]
Ok

**Comment by agriffard** [comment]
@Skrypt Are you working on it for RC2?

**Comment by hishamco** [comment]
@Skrypt let me know if you need some help on this and I can continue with this

**Comment by Skrypt** [comment]
I've been busy. I'll take a look tomorrow.

**Comment by hishamco** [comment]
Just notice a little tiny thing, can we make the icons align to the center, the text alignment is correct from UI/UX perspective but the icons is not

**Comment by hishamco** [comment]
Please screenshot before merge

**Comment by Skrypt** [comment]
Look at the first message of this issue I updated the gifs

**Comment by Skrypt** [comment]
I removed the hamburger menu because it was not necessary for displaying only a Log off option. That menu, is the UserMenu.cshtml so I believe that we only need to use a simply dropdown menu which will eventually include a link to the current user profile or system preferences ...

**Comment by hishamco** [comment]
Hope if there's ability to change or add items to it from other modules

**Pull request merged**
