### PR TITLE
#7518 background tasks, nextStartTime is assumed as local time

### LINKED ISSUE #7518: Background tasks, time zones should be converted
image
image

China UTC Plus 8, 8 a.m ： 0 8 * * *
now ： 0 0 * * *

### PR DESCRIPTION
**Pull request by lampersky**
fixes #7518

### CODE REVIEW

**Review by Skrypt — APPROVED** [review]

**Comment by sebastienros** [comment]
I don't think it's correct. `ILocalClock` does the job for you. In this PR the TimeZoneId setting is shortcutting the ITimeZoneSelector. I think you should just resolve `ILocalClock` instead of `IClock` and then access the `LocalNowAsync` value. It will resolve the correct timezone and convert the value for you, and based on any custom logic a module might have set.

**Comment by lampersky** [comment]
Thank you, will fix it.

I thought ILocalClock is the environment local time (where the app is
hosted and run), not site time (based on what user choose in site setting).

**Comment by Skrypt** [comment]
ILocalClock does the job for you. Forgot about this one.

**Comment by sebastienros** [comment]
@Skrypt I didn't remember either, but the code looked too complicated so I checked what the DateTimeShapes were doing.

**Comment by jtkech** [comment]
@Skrypt @sebastienros 

So, we would need to also update the `TimerEvent` that does

        private bool IsExpired()
        {
            if (StartedUtc == null)
            {
                StartedUtc = StartAtUtc ?? _clock.UtcNow;
            }

            var schedule = CrontabSchedule.Parse(CronExpression);
            var whenUtc = schedule.GetNextOccurrence(StartedUtc.Value);

            return _clock.UtcNow >= whenUtc;
        }

If so, at least open a new issue.

**Pull request merged**
