### PR TITLE
leaflet 1.9.3

### PR DESCRIPTION
**Pull request by agriffard**
https://www.npmjs.com/package/leaflet/v/1.9.3
https://github.com/Leaflet/Leaflet/releases/tag/v1.9.3

### CODE REVIEW

**Comment by agriffard** [comment]
An error occurs when creating/editing a content with a GeoPointField: 
It does not manage to get the icons, like`marker-icon-2x.png`.

I don't know how to set leaflet options with a correct `imagePath` property.

@Skrypt Can you please have a look?

**Comment by agriffard** [comment]
@Skrypt Any chance you can review this PR?

**Comment by Skrypt** [comment]
If it works then you can merge. But that's a 2 versions upgrade.

**Review by Skrypt — APPROVED** [review]
If it works then you can merge. But that's a 2 versions upgrade.

**Pull request merged**
