### PR TITLE
Updating dotnet SDK

### PR DESCRIPTION
**Pull request by sebastienros**
Note: Please wait for all builds to finish

### CODE REVIEW

**Comment by alexbocharov** [comment]
@sebastienros We no longer use Travis CI?

**Comment by sebastienros** [comment]
@alexbocharov I was trying to fix travis (which fails on linux because of the updated sdk version) but then I remembered appveyor does linux too, and I think it's better if we use the same scripts to handle both.

It doesn't look really nice right now, I'd prefer to have different scripts, or at least two main sections in the file, but it's progressing.

**Comment by sebastienros** [comment]
I am disabling Linux build in this PR for now until 2.1.300 is available in appveyor, hoping it will fix this issue:
```
/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.aspnetcore.mvc.razor.viewcompilation/2.0.3/build/netstandard2.0/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.targets(60,5): error MSB6003: The specified task executable "sh" could not be run. Cannot allocate memory [/home/appveyor/projects/orchard2/src/OrchardCore.Cms.Web/OrchardCore.Cms.Web.csproj]
Command exited with code 1
Build failed
```

The publish step takes a very long time, then hangs.

**Comment by alexbocharov** [comment]
> @alexbocharov I was trying to fix travis (which fails on linux because of the updated sdk version) but then I remembered appveyor does linux too, and I think it's better if we use the same scripts to handle both.
It doesn't look really nice right now, I'd prefer to have different scripts, or at least two main sections in the file, but it's progressing.

In travis has support a build for macOS

**Pull request closed without merging**
