### PR TITLE
Add Typed Content Items

### PR DESCRIPTION
**Pull request by deanmarcussen**
This PR adds the ability to make a model which inherits from `TypedContentItem` and contains properties for the `ContentFields` and `ContentParts` that exist on the content item, and it's definition, by creating a dynamic proxy between the `TypedContentItem` and the `ContentItem`

I was working (and still am) towards https://github.com/OrchardCMS/OrchardCore/issues/4125 which would allow definition of content types in code as well, but this actually works as a standalone PR for content types that are defined in the CMS, as there is need for a direct connection between a `TypedContentItem` and it's type definition.

The proxying is done on field type and field name, and properties must be virtual.

so for example
```
    public class TestTypedContentItem : TypedContentItem
    {
        public TestTypedContentItem(ContentItem contentItem) : base(contentItem) { }
        public virtual TextField TheTextField { get; set; }
        public virtual MarkdownBodyPart MarkdownBodyPart { get; set; }
        public virtual BagPart ANamedBagPart { get; set; }
    }
```

and it is used with
`var typedItem = contentItem.To<TestTypedContentItem>();`

If the contentType definition and the `TypedModel` differ (which can also happen with hard typing `ContentParts` which we can already do), properties will just return null.

By making use of the `CreateClassProxyWithTarget` leakiness that can occur with objects, it keeps a reference to the original content item in the proxy, which is what is used when updating the proxy values. 

So works for updating as well, and by using a proxy with a target, there shouldn't be any issues with the YesSql cache, as it is the original object being updated.

It's my first time using Castle DynamicProxy, so all feedback welcome.

There were a few other options, such as cloning via the json serializer, or deep memberwiseclone, but I think they would all cause problems with the session cache if updates were attempted and / or made creating the `TypedContentItem` harder - it could however have been similar to O1 and it's `ContentPartRecord` and `ContentPart`, but this makes the creation of the model simple for the user.

The rest of the idea from https://github.com/OrchardCMS/OrchardCore/issues/4125  still to follow, but as a separate PR.

### CODE REVIEW

**Comment by ns8482e** [comment]
Why need TypedContentItem that has ContentField?  ContentItem is composition of ContentPart and ContentField. Composition is power of Orchard, why restrict it using inheritance?

If restriction is required on composition then its better to use custom ContentPart.

**Comment by Skrypt** [comment]
I think the idea is to be able to have the choice to create Content Types in code or not. Still usefull in some scenarios where composition is not a requirement.

**Comment by ns8482e** [comment]
> some scenarios where composition is not a requirement.
Correct,  my point is creating Custom ContentPart for content item delivers the same result.

HtmlBodyPart is perfect example of Part that provides same UI functionality as HtmlField.

**Comment by deanmarcussen** [comment]
Closing this, will pick it up again when touching on https://github.com/OrchardCMS/OrchardCore/issues/4125

**Pull request closed without merging**
