### PR TITLE
Admin menus positions

### PR DESCRIPTION
**Pull request by agriffard**
Prefix all position parameters by `am-` in admin menus to differenciate them from the title.

### CODE REVIEW

**Comment by sebastienros** [comment]
Maybe we should use a special prefix for localized strings that should not be added to po files. That would mitigate the issues with this technique. Then for "Content Types" and "Content Parts" you can use `T["Content Types"] + ".1"` and `T["Content Types"] + ".2"` so it's still order relatively to the local language, but parts is always right after types.

**Comment by agriffard** [comment]
> This will duplicate the localization strings. Am I right?
Yes but people don't really need to translate them

**Comment by agriffard** [comment]
For `Content Types` and `Content Parts`, I called them `am1-Content Types` and `am2-Content Parts`.

**Comment by agriffard** [comment]
> Maybe we should use a special prefix for localized strings that should not be added to po files

I like the idea.

**Pull request merged**
