### PR TITLE
Introducing OrchardCore and OrchardCore.Abstractions

### PR DESCRIPTION
**Pull request by sebastienros**

### CODE REVIEW

**Comment by Jetski5822** [comment]
I need to look closer as I’m reading it on a phone, but right now it feels like Orchard.Framework :/

**Comment by sebastienros** [comment]
I can't disagree. At least there is an Abstractions package. And all the MVC stuff is outside, so it's really about modularity, tenants and services to make an orchard app.

**Comment by Jetski5822** [comment]
I’m going to sit down and look again, I know where you wanna head. Just not sure about what you have right now

**Comment by sebastienros** [comment]
Fixes #2195

**Comment by Jetski5822** [comment]
Some of the consolidation for clean up I can see if fine, however... I am not sure the shim or implementation for Modules has anything to do with Deferred Tasks, Scripting, Entities or Security.

I am really not keen of the Modules stuff having knowledge of the rest of the eco system, though I can see this has probably crept in some how.

Where I have see the modular stuff used, has been just that... only the modular stuff. I don't really think we should start bundling other stuff with it if we can avoid.

From a build perspective, did it really improve much time wise?

Going to have a think about it. I dont disagree there are more packages than we should have.. just not sure we chose the right ones to consolidate. N

**Comment by sebastienros** [comment]
I understand. Maybe create another one then, that would be more oriented to the application framework and contain the commands, entity, scripting, ...

**Comment by sebastienros** [comment]
@Jetski5822 Extracted the Entities, Security, Scripting, ... stuff into OrchardCore.Infrastructure. OrchardCore now only contains Extensions and Multi-tenancy. It need deferred tasks as it's part of the multi-tenant container logic.

In the end even a simple MVC application still has a transitive dependency on these two packages, because `DisplayManagement` (mvc views) requires it. I will try to make a sample that only uses modules and middlewares as it should not require that.

**Comment by sebastienros** [comment]
ping

**Comment by Jetski5822** [comment]
Ok ok I’ll take a look tomorrow :p

**Pull request merged**
