### PR TITLE
Update OpenIddict 4.8.0

### PR DESCRIPTION
**Pull request by hishamco**
https://www.nuget.org/packages/OpenIddict/4.8.0
https://github.com/openiddict/openiddict-core/releases/tag/4.8.0

### CODE REVIEW

**Review by kevinchalet — APPROVED** [review]
Thanks @hishamco! ❤️

**Comment by hishamco** [comment]
Thanks again @kevinchalet for all the efforts that you made in OpenIddict

**Comment by kevinchalet** [comment]
@hishamco thanks for your kind words! ❤️ 

Speaking of OpenIddict, we'll need to decide what we want to do with https://github.com/OrchardCMS/OrchardCore/pull/14021. Is this an experiment to want to finalize?

**Comment by hishamco** [comment]
Right, I suggest to demo it in the standup if you can

**Pull request merged**
