### PR TITLE
Features matrix

### LINKED ISSUE #2267: Document feature matrix with milestones

### PR DESCRIPTION
**Pull request by agriffard**
List of features currently available or in development with milestones.

Fixes #2267

### CODE REVIEW

**Comment by sebastienros** [comment]
Good start

But this should include CMS/Framework agnostic features.
Good examples:
- https redirection, google authentication, output caching, forms, user management, permissions, multi-tenancy
Bad example:
- Admin Menu, Flow, Recipes, Named parts

The idea is that someone without knowledge of Orchard would know if a common feature is already implemented oob, in a module, scheduled, or not at all.

**Comment by agriffard** [comment]
OK, I reviewed the list of features a little bit.

**Comment by hishamco** [comment]
@agriffard what's the remaining in this one?

**Comment by agriffard** [comment]
Conflicts resolved.
It is just waiting the will to merge it and we will update it once the RC is released.

**Pull request merged**
