### PR TITLE
make the solution pass the build

### LINKED ISSUE #5146: build fail after 3.1

### PR DESCRIPTION
**Pull request by infofromca**
fix #5146 , make the solution pass the build after changing to 3.1

### CODE REVIEW

**Comment by deanmarcussen** [comment]
Can you explain what is failing on the build? 

As it seems to be passing fine, and I don't understand how these changes will affect anything.

**Comment by ns8482e** [comment]
> fix #5146 , make the solution pass the build after changing to 3.1

Whats failing ? It works for me without this change

**Comment by infofromca** [comment]
image

**Comment by infofromca** [comment]
vs 2019 community

**Comment by hishamco** [comment]
AS it's shown above, the variable declared twice

**Pull request closed without merging**
