### PR TITLE
Replaced async send mail with task to schedule non-async send mail (#2306)

### PR DESCRIPTION
**Pull request by hswami**

### CODE REVIEW

**Comment by sebastienros** [comment]
It looks really wrong, there must be an obvious issue. Feel free to apply the patch locally if it unblocks you, but I want to spend more time on this to understand what is wrong. It might be because of a bigger issue with how tasks are executed.

@sfmskywalker can you repro this?

**Comment by sebastienros** [comment]
I would actually prefer a call to `SendMail` without the Task.Run call. IF it can unblock everyone.

**Comment by hswami** [comment]
OK. I'll submit a PR without the Task.Run call.

**Comment by hswami** [comment]
I will submit a new PR without the Task.Run call.

**Comment by hswami** [comment]
@sebastienros I just tried it and if I remove the Task.Run call, then I have to make something else in that method async ... like use Task.FromResult on one of the returns. Which *evil* do you prefer?

**Comment by sebastienros** [comment]
Remove the async keyword, return Task.FromResult(SmtpResult.Success)

**Comment by sfmskywalker** [comment]
I just tested the SendEmail activity in response to an HttpRequestEvent activity, but was unable to reproduce the issue. The SendAsync method successfully sent an email message. Sounds like something else is wrong.

@hswami perhaps you can try again from a clean installation (no custom code), and see if you can reproduce? If so, please share the exact repro steps. Maybe you're doing something different than me.

**Pull request closed without merging**
