### PR TITLE
Move card / tab shapes to Shape Attributes

### PR DESCRIPTION
**Pull request by deanmarcussen**
Fixes https://github.com/OrchardCMS/OrchardCore/issues/8619

/cc @jtkech 

I need to do a little more testing first :)

Need this for audit trail as well, as using it for Users, on the SaaS recipe creates the same issue.

### CODE REVIEW

**Comment by jtkech** [comment]
LGTM will take a deeper look this night

**Comment by jtkech** [comment]
Just tried the Tabs, i let you check Columns and  Cards

I committed some minors changes but feel free to revert them if you don't like them ;)

- Remove unused using.

- Add a null check, `shape.GetProperty<>` may return null if the type is not a value type e.g. a class / interface (and if we don't specify a default value).

- Here also i prefer to use a first lower case for method parameters.

- Set first to false once, only if it is true.

Note: I'm now used to not always add a line before an if block, e.g. after initializing a related variable, good compromise between a too compacted code and a too diluted one, but i still always add a new line after an if block. But open to any other rule, even if we say that here everybody can do as they want.

**Review by jtkech — COMMENTED** [review]
Waiting for testing cards / columns before approving

**Comment by deanmarcussen** [comment]
> Waiting for testing cards / columns before approving

All tested, works fine.

> use a first lower case for method parameters

Did not know we had gone case invariant on attribute method name injection. All good with me.

All changes appreciated :)

**Review by jtkech — APPROVED** [review]

**Pull request merged**
