### PR TITLE
Fix email validation when register a new user

### LINKED ISSUE #7456: Register Email Validate bug
[Feature("OrchardCore.Users.Registration")]
RegistrationController        

Register Action

 if (!string.IsNullOrEmpty(model.Email) && !_emailAddressValidator.Validate(model.Email))
            {
                ModelState.AddModelError("Email", S["Invalid email."]);

                // Check if user with same email already exists
                var userWithEmail = await _userManager.FindByEmailAsync(model.Email);

                if (userWithEmail != null)
                {
                    ModelState.AddModelError("Email", S["A user with the same email already exists."]);
                }
            }

Here, when mail rule validation fails, check whether a user with the same email already exists?
Duplicate emails can never be verified

### PR DESCRIPTION
**Pull request by hishamco**
Fixes #7456

### CODE REVIEW

**Comment by hishamco** [comment]
I may add a unit test for that as well if it's required

**Comment by agriffard** [comment]
Is it ready, now that you fixed the build?

**Comment by hishamco** [comment]
Please wait I will add a unit test then we can merge

**Comment by hishamco** [comment]
@agriffard you can merge after the build pass

**Pull request merged**
