### PR TITLE
Huge Code Cleanup

### PR DESCRIPTION
**Pull request by Skrypt**
By executing Visual Studio Cleanup Profile # 1
Warning : this might break a lot of PR's.

### CODE REVIEW

**Comment by hishamco** [comment]
🚀 🚀 🚀

**Comment by jtkech** [comment]
Wow LGTM so i will approve but as you said

> Warning : this might break a lot of PR's.

So i let others seeing it before merging

But if we want to merge it, maybe better to do it quickly as i'm starting new PRs ;)

**Review by jtkech — APPROVED** [review]

**Comment by hishamco** [comment]
@jtkech I told you many things to need to clean up ;)

**Comment by Skrypt** [comment]
Do I hit the 🚀  button?

**Review by hishamco — APPROVED** [review]
LGTM

**Comment by jtkech** [comment]
Other things that could be done later

- Using framework types e.g. `string` => `String`

- Using discard symbol e.g. `out var someVar` => `out _` when `someVar` is not used

- `using (var = ...) { code lines; }` => `using var = ...; code lines;`  if all the following lines belong to the block

I started such a PR but stopped it in the middle because of too many changes ;)

**Comment by hishamco** [comment]
I will handle the tedious work ;)

**Pull request merged**
