### PR TITLE
Script Liquid

### PR DESCRIPTION
**Pull request by agriffard**
Related to #9266

### CODE REVIEW

**Review by jtkech — APPROVED** [review]

**Comment by Skrypt** [comment]
I'm not sure why you need to push it at the footer because in this page example they set it in the header : 

https://fontawesome.com/how-to-use/javascript-api/setup/configuration

**Comment by agriffard** [comment]
I took example of TheAdmin but I can change.

**Comment by deanmarcussen** [comment]
Is this the same issue as https://github.com/OrchardCMS/OrchardCore/issues/9271

If you can confirm @agriffard , I will look into it

**Comment by agriffard** [comment]
> Is this the same issue as #9271
> 
> If you can confirm @agriffard , I will look into it

There is no `at`, so yes, I guess.

**Review by Skrypt — APPROVED** [review]

**Pull request merged**
