### PR TITLE
Make Themes always enabled

### LINKED ISSUE #12707: Exception due to missing `ThemeTogglerService` when disabling the Themes module
Hello, I was playing around with the features switches and by disabling one of them (not entirely sure which one but I think it was one around Themes), this error started popping up:

InvalidOperationException: No service for type 'OrchardCore.Themes.Services.DarkModeService' has been registered.

Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
Microsoft.AspNetCore.Mvc.Razor.RazorPagePropertyActivator+<>c__DisplayClass8_0.<CreateActivateInfo>b__1(ViewContext context)
Microsoft.Extensions.Internal.PropertyActivator<TContext>.Activate(object instance, TContext context)
Microsoft.AspNetCore.Mvc.Razor.RazorPagePropertyActivator.Activate(object page, ViewContext context)
Microsoft.AspNetCore.Mvc.Razor.RazorPageActivator.Activate(IRazorPage page, ViewContext context)
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)

I can't access any of the pages or login/logoff, so not entirely sure how to fix this. After searching for a resolution for some time, haven't been able to find this mentioned anywhere.

### PR DESCRIPTION
**Pull request by hishamco**
Fixes #12707

### CODE REVIEW

**Comment by hishamco** [comment]
The admin theme required `DarkModeService`, so if we disable `OC.Themes` module it will break everything

**Comment by jtkech** [comment]
Maybe just make `TheAdmin` dependent on `OC.Themes` in its manifest.

**Comment by ns8482e** [comment]
May be `DarkModeService` should be moved out of theme and defined in `Admin` module then

**Comment by jtkech** [comment]
And make `TheAdmin` dependent on `Admin`, yes looks better.

**Comment by Skrypt** [comment]
I don't agree 100%. The reason why the dark mode is tied to the frontend views is because of the Login views that can be overridden optionally in a theme. The Login Layout needs to register the dark mode service to take it into consideration. Also, the login is the admin login and the frontend login. So, we would need to make a distinction between both then.

**Comment by jtkech** [comment]
Okay didn't remember this ;)

**Comment by hishamco** [comment]
Agree with @Skrypt, dark mode is a theme specific

**Comment by hishamco** [comment]
At least we need a proper way to fix the related issue

**Pull request closed without merging**
