### PR TITLE
Fixes razor pages and autoroutes conflicts.

### PR DESCRIPTION
**Pull request by jtkech**
Related to an issue reported in #4261 

- The problem is with `DynamicRouteValueTransformer` that we recently used for our `HomeRouteTransformer` and `AutoRouteTransformer`. If the path is recognized as a valid pattern (`TransformAsync` is called) but there is no `HomeRoute` or no related `Autoroute`, a null endpoint is added to the candidate collection.

    This doesn't disturb the `MatcherPolicy` as `DynamicControllerEndpointMatcherPolicy`, `DynamicPageEndpointMatcherPolicy` and other ones, because there are doing e.g the following checking (or a null check on the related endpoint).

                if (!candidates.IsValidCandidate(i))
                {
                    continue;
                }

- But this is not the case of `PageLoaderMatcherPolicy` that fails when we also define `Razor Pages`.

    So here, i copy pasted the original source in which i added the above checking, and replaced the service registration with this custom implementation.

- Then all razor pages were working again. I re-tried the demo module pages and also all pages defined in our `OrchardCore.Application.Pages` testing project.

**Update**
**When using razor pages and without this workaround**, the problem with a `DynamicRouteValueTransformer` tied to a path pattern e.g `/` or `/{any}/{**slug}`, is that, when the pattern is matched, it would need to always return some valid route values related to a valid endpoint. Which is not the case if there is no home route or no related autoroute, then it fails if the path also matches a defined razor page.

### CODE REVIEW

**Comment by arkadiuszwojcik** [comment]
@jtkech should this be reported to AspNetCore team? Looks like this check should be there.

**Comment by jtkech** [comment]
You're right, i will report it this night.

**Comment by jtkech** [comment]
Done https://github.com/aspnet/AspNetCore/issues/13996

**Comment by jtkech** [comment]
I did it: https://github.com/aspnet/AspNetCore/issues/13996

**Pull request merged**
