### PR TITLE
Update libphonenumber-csharp  8.13.34

### PR DESCRIPTION
**Pull request by hishamco**
https://www.nuget.org/packages/libphonenumber-csharp/8.13.34

### CODE REVIEW

**Comment by MikeAlhayek** [comment]
@hishamco why do we need a test case to validate an external library here? Part of the adopted library has it's own testing and we should not need to add a testing on the top of their testing.

**Comment by Piedone** [comment]
I didn't mean that you should write a test. Rather, I'm asking whether you tested the phone number validation feature where it's used, like the user editor on the admin.

**Comment by hishamco** [comment]
> @hishamco why do we need a test case to validate an external library here? Part of the adopted library has it's own testing and we should not need to add a testing on the top of their testing.

Mike, I thought Zoltan wanted a unit test 

> I'm asking whether you tested the phone number validation feature where it's used, like the user editor on the admin.

I didn't because there's no major change in the library

**Comment by MikeAlhayek** [comment]
> Mike, I thought Zoltan wanted a unit test

I would remove it. Check out the last comment from Zoltan https://github.com/OrchardCMS/OrchardCore/pull/15669#issuecomment-2041657434

**Comment by hishamco** [comment]
> Check out the last comment from Zoltan https://github.com/OrchardCMS/OrchardCore/pull/15669#issuecomment-2041657434

I already replied :)

**Comment by Piedone** [comment]
I'm just stating the obvious, but you should always test your code changes by running them, even if the change seems trivial, and especially if it's somewhat opaque like a dependency update. The reviewer has to test the changes, too.

**Comment by hishamco** [comment]
> The reviewer has to test the changes, too.

Frankly I never saw this previously in the packages update, unless it's a major release coz it might have a breaking changes

**Comment by Piedone** [comment]
Every release can have breaking changes. We've seen breaking changes in .NET patch releases even. That it's not supposed to have them is no guarantee. So, naturally, you have to test the update. Flipping the version number in two files is not enough.

**Comment by hishamco** [comment]
> We've seen breaking changes in .NET patch releases even

You can blame them :) especially if they are using Semver

> Flipping the version number in two files is not enough.

This is too much, coz you don't know what you want to test

**Comment by Piedone** [comment]
That's part of the task: You need to check what's the impact of your change.

**Comment by hishamco** [comment]
So I will leave updating the packages, I don't think @agriffard did that for every update in the past. It would be tedious

**Pull request merged**
