### PR TITLE
fix validation error rendering on radio/checkbox

### PR DESCRIPTION
**Pull request by ns8482e**
fix validation error rendering on radio/checkbox
*Before*
image

*After*

image

### CODE REVIEW

**Review by hishamco — APPROVED** [review]

**Comment by ns8482e** [comment]
> Oops, there's an error in testing assets

updated assets

**Comment by MikeAlhayek** [comment]
@ns8482e you'll need to run `gulp rebuild-assets` on your machine and commit the generated files.

You can also try running `npm run cleanup all && npm install && gulp rebuild` and commit the files

**Comment by Piedone** [comment]
See https://docs.orchardcore.net/en/latest/guides/gulp-pipeline/#using-the-command-line and be sure to use Node.js 18. Before requesting review again, make sure to revert all the unnecessary file changes so only the SCSS one remains.

**Comment by ns8482e** [comment]
Yes! something is not right, I am using windows 😂

I build all this in fresh brach from main all cleaned and rebuild as @MikeAlhayek suggested 

I'll try with fresh clone too

**Pull request closed without merging**
