### PR TITLE
Reduce string allocations in MediaTokenService

### PR DESCRIPTION
**Pull request by lahma**
`MediaTokenService` used `String.Concat` which internally allocates string builder as there always seems to be more than one parameter to calculate for. Also a separate key was derived from using `TokenCacheKeyPrefix + commandValues`. Now using pooled string builder to build key with prefix and hashing the part of it that does not contain the prefix.

### CODE REVIEW

**Comment by sebastienros** [comment]
String.Concat uses a stack allocated char[256] by default and a pooled array if it overflows it (see ValueStringBuilder). I don't think it's necessary here to use the StringBuilderPool.

**Comment by lahma** [comment]
Might make sense to have `ValueStringBuilder` look-alike available and stack alloc, sizes usually should be lower than 256 in general case. Would `ZString` be acceptable dependency?

**Comment by sebastienros** [comment]
I think it's fine, though I wish they had a shared source variation of the package so we don't add extra dlls for single classes.

**Comment by sebastienros** [comment]
Do you want to reword this one once ZString is part of the dependencies?

**Comment by sebastienros** [comment]
I am merging it and other PRs using ZString can be created

**Pull request merged**
