### PR TITLE
Keyed Dictionary Support

### PR DESCRIPTION
**Pull request by hishamco**
This replaced PR #15100, it's a much simpler and more efficient way to support a keyed dictionary. Tested through unit tests as well as running OC web application everything is working as expected

@MikeAlhayek could you please try it on the SMS providers, and let me know if there're a missing corner cases

/cc @sebastienros

### CODE REVIEW

**Comment by MikeAlhayek** [comment]
@hishamco it feels wrong to me to override the service provider factory directly in OC. The approach I took in the other PR does not override anything but extend the feature. Either way, I don't think this problem is something we need to address in OC. It seems to be on the agenda for .Net 9. There is no pressing need to implement this so why not wait until it's part of the framework.

Maybe others will have other thoughts on this approach.

**Comment by hishamco** [comment]
> it feels wrong to me to override the service provider factory directly in OC.

Please check the `DefaultServiceProviderFactory` source

@sebastienros your thought if you have time

**Comment by hishamco** [comment]
FYI 
https://github.com/dotnet/runtime/blob/b8114f9c81897e9dbbda24f7e7a30ea0c04a8d35/src/libraries/Microsoft.Extensions.DependencyInjection/src/DefaultServiceProviderFactory.cs#L11-L45

**Comment by Piedone** [comment]
Can you point to some .NET 9 issues or something, @MikeAlhayek? I can't find anything.

**Comment by MikeAlhayek** [comment]
https://github.com/dotnet/runtime/issues/95476

**Comment by Piedone** [comment]
I see. So, to summarize:

- https://github.com/OrchardCMS/OrchardCore/issues/14799 is an issue asking to implement in OC what https://github.com/dotnet/runtime/issues/95476 asks to implement for .NET.
- This PR and https://github.com/OrchardCMS/OrchardCore/pull/14800 aim to address the OC issue.
- Neither of the two PRs, nor the OC issue is applicable since this will be part of .NET, and presumably following a different approach.
- Thus, the issue and both PRs should be closed.

Do I understand it correctly?

**Comment by MikeAlhayek** [comment]
Yes @Piedone the summary is correct. And Both PR's should be closed since we don't really have to this in OC

**Comment by Piedone** [comment]
OK then!

**Pull request closed without merging**
