### PR TITLE
Matiasmolleja/media stackoverflow

### LINKED ISSUE #2702: scrolling in media module
in select media if we have some files, the scroll doesn't appear.
mediascoll

### LINKED ISSUE #3022: Media Gallery : stackoverflow
When a media folder has too many documents ; the Media Gallery tries to render/download them all thus causing the stackoverflow exception.

To fix this issue ; the Media Gallery should paginate the folders instead of trying to render everything directly.

@matiasmolleja

### PR DESCRIPTION
**Pull request by matiasmolleja**
Fixes #2702

Fixes #3022
@Skrypt  Please try if this fixes the stackoverflow exception.

Be aware that everything is client-side. No changes in the media controller. So, If you browse a folder with hundred of files you get a json with all the files. You pay a penalty on first load, but after that then the navigation through pages is faster, without new requests to the server. 

Please let me know if you prefer the other way around, doing the pagination on the server.

### CODE REVIEW

**Comment by matiasmolleja** [comment]
pagination-assets

**Comment by matiasmolleja** [comment]
pagination-assets1

**Comment by matiasmolleja** [comment]
modal:

pagination-modal

**Comment by Skrypt** [comment]
Have you tried with for example with 1 gb of image files in a folder?

**Comment by matiasmolleja** [comment]
I just did it, on my dev machine.
Uploaded 4000 files. 2GB.
Set pagination to 100 items per page.
It does not throw errors. 
It took a while to upload, around 15 minutes. 
And after that the browsing was OK. A little bit of lag, but I think it's normal for such a large amount of data.
Anyway I think that if the issue is that rendering a lot of images causes an stackoverflow, this PR is only an incomplete solution. It just prevents loading a lot of images at the same time. Maybe we should look at other places.

**Comment by Skrypt** [comment]
The stackoverflow issue for me was happening on the browser itself ; I was reaching it's limit of ram usage. So like you said, depending on the size of the images it can get slower to render. And, I think that if, for example, your images all have sizes of 300 mb then it can also be an issue since now 100 images would be 3 gb. Are we using ImageSharp to render thumbnails only?

**Comment by sebastienros** [comment]
I think we should only load the content of one folder at a time, not the full hierarchy. And when trying to expand load the content of this folder. If it's empty them just remove the expand icon.

**Comment by matiasmolleja** [comment]
That is more or less what we do right now.  The question is more about where should be the logic to paginate, on the server or on the client . 

As it is now this PR does it on the client. It retrieves ALL the files in the folder, without pagination information.
And then, using VueJS it shows a list of pages and handles all the user navigation without asking again to the server.

The only issue I see is that for directories with a lot of files (I tried with 4000 in the same dir), the initial json payload is pretty large. And there is a little bit of lag while the user browses the pages.

And I'm not sure if it worth adapting this to do the pagination on the server: passing params to the server on each user interaction: page size, page number, sortColumn etc..

**Comment by sebastienros** [comment]
If we already load the content of a single directory then that's fine. We just have to tell people to organize things in folders, and not a single flat directory.

**Comment by Skrypt** [comment]
I will test this with my project. I'm already separating image folders per content type. Though I have a lot of them still in a single content type. I've also separated them per content field and I still have plenty of them in a single folder. I have to test it before saying anything else 😄

**Pull request merged**
