### PR TITLE
LiquidViewTemplate OnEnterScope Handler

### PR DESCRIPTION
**Pull request by jtkech**
Related to #5175 

Now `context.SetValue()` set a property for all renderings in a given request scope, and this is through `RenderAsync()` that we can pass a specific `Model` that will be **set in a `LiquidTemplateContext` child scope**. Before the `ContentItem` was sometimes a `Model` property, or a root property, or both. Now, when it exists it is always a `Model` property. **But for backwards compatibility**

- Here we can register handler callbacks that are executed when the liquid template context enters in a child scope, so that we can add `LiquidTemplateContext` child scope values.

- For backwards compatibility, i used one of these handlers to check if a model is marked as `IContent` and then add `IContent.ContentItem` as a root property of the current child scope. Then, for all the related models (e.g `AliasPartViewModel`) i just needed to make them derived from `IContent`.

- So for these models we can use both `Model.ContentItem` and `ContentItem`. But this is only for backwards compatibility, and only for the related models for which we were using `ContentItem` as a root property, and that i marked as `IContent`.

- @deanmarcussen here i included your changes plus the one i suggested.

- I hope it doesn't have a perf impact.

### CODE REVIEW

**Comment by deanmarcussen** [comment]
> @deanmarcussen here i included your changes plus the one i suggested.

Nice one @jtkech this looks like a good compromise. I'll close the other pr.

We'll have to update some docs as well I imagine :)

**Comment by sebastienros** [comment]
I thought we could just change `model.Markdown = await _liquidTemplateManager.RenderAsync(field.Markdown, _htmlEncoder, model);` to `model.Markdown = await _liquidTemplateManager.RenderAsync(field.Markdown, _htmlEncoder, model, (scope) => scope.SetValue("ContentItem", field.ContentItem));`

Or is there anywhere that the "ContentItem" value was set that doesn't involve a call to `RenderAsync` ?

**Comment by jtkech** [comment]
@sebastienros okay, at the beginning the idea was to prevent from having to change many things just for compatibility by providing a different way to set local scope values, but here i already did many changes and i don't know why but today using a lambda make more sense to me ;)

So i close this PR and will start a new one.

I suggest to only update the places where we were setting `ContenItem` as a root property, this only for backwards compatibility, not as a general rule.

**Comment by sebastienros** [comment]
Agreed

**Pull request closed without merging**
