### PR TITLE
Update match all template to include size

### PR DESCRIPTION
**Pull request by jbytes1027**
See #16779 for details. Specifically [this comment](https://github.com/OrchardCMS/OrchardCore/issues/16779#issuecomment-2402730875).

### CODE REVIEW

**Comment by jbytes1027** [comment]
@dotnet-policy-service agree

**Comment by MikeAlhayek** [comment]
@jbytes1027 thank you for contributing! Can you please also make the same change in the following docs?

https://github.com/OrchardCMS/OrchardCore/blob/9a1d68291c0f9b96520f6b2bf16cc4158454cb9d/src/docs/reference/modules/Elasticsearch/README.md?plain=1#L195

and also 

https://github.com/OrchardCMS/OrchardCore/blob/9a1d68291c0f9b96520f6b2bf16cc4158454cb9d/src/docs/reference/modules/Elasticsearch/README.md?plain=1#L207

**Comment by jbytes1027** [comment]
@MikeAlhayek the tables already include the mention of a size parameter.

```
| Parameter | Example | Description |
| --------- | ---- |------------ |
| `indexName` | `search` | The name of the index to query. |
| `query` | `{ "query": { "match_all": {} } }` | A JSON object representing the query. |
| `parameters` | `{ size: 3}` | A JSON object representing the parameters of the query. |
```

**Comment by MikeAlhayek** [comment]
@jbytes1027 

The match_all does not include the size.

```
| `query` | `{ "query": { "match_all": {} } }` | A JSON object representing the query. |
```

**Comment by jbytes1027** [comment]
Fixed. I take it this size has a different purpose:

    | `parameters` | `{ size: 3}` | A JSON object representing the parameters of the query. |

**Review by MikeAlhayek — APPROVED** [review]

**Review by gvkries — APPROVED** [review]

**Pull request merged**
