### PR TITLE
Add tenant description

### LINKED ISSUE #5638: Add a description to the tenant list
Add a description to the tenant list

截图录屏_选择区域_20200226201124

### PR DESCRIPTION
**Pull request by hishamco**
Fixes #5638

### CODE REVIEW

**Comment by jtkech** [comment]
@hishamco 

The `ShellSettings` uses 2 underlying `ShellConfiguration` => `_settings` and `_configuration`. The 1st one is for the minimum set of properties needed to run a tenant and that are saved in `tenants.json` (if not pre-configured from another config source), the 2nd is used for other configuration values.

And for a given `shellSettings` when you are using `shellSettings["SomeName"]` it uses the 2nd one.

So here it's better to not define a new `shellSettings.Description` and in your code just use `shellSettings["Description"]`, as an example see how it is already done for `shellSettings["Secret"]`.

**Comment by hishamco** [comment]
> So here it's better to not define a new shellSettings.Description and in your code just use shellSettings["Description"]

I just asked myself at the beginning why there's two options ;) I will update the PR now

**Comment by hishamco** [comment]
@jtkech your could merge if it looks good to you now ;)

**Comment by agriffard** [comment]
PR build failed:
`Controllers\AdminController.cs(94,41): error CS1001: Identifier expected [C:\projects\orchardcore\src\OrchardCore.Modules\OrchardCore.Tenants\OrchardCore.Tenants.csproj]`

**Comment by hishamco** [comment]
Oops, thanks Antoine

**Comment by sebastienros** [comment]
@jtkech can you approve (or not)

**Comment by jtkech** [comment]
As i can see LGTM so i will aprove it

But do we need to wait for someone to try it?
did somebody already try it?

If needed i'll try to take the time to try it this w-end

**Comment by hishamco** [comment]
I tried creating and editing a tenant with description, someone could try the workflow if it's necessary coz I didn't deal with it so far

**Pull request merged**
