### PR TITLE
Add Media background checkerboard pattern for transparent images.

### LINKED ISSUE #10441: Media gallery image background checkerboard pattern
As reported on Gitter by @Nic-84 : 

> I have a suggestion to slightly improve the UI on the admin side of Orchard. When you are dealing with media/images, the media picker has a white background (or black background in dark mode). Instead, could you make the background a checkered board, like other image software? I am using transparent pngs/svgs, and it would be nice to be able to see the image when it's either all white or all black. I have included a screen shot to explain what I mean. Should I post something like this on the GitHub site, Discussions > Ideas?

orchard-media-screen

### PR DESCRIPTION
**Pull request by Skrypt**
https://user-images.githubusercontent.com/3228637/136644651-93917b21-b4e1-4c84-adb5-e504f3298d33.mp4

Fixes #10441

### CODE REVIEW

**Comment by hishamco** [comment]
Ya it's too dark

**Comment by Skrypt** [comment]
You guys a lightweights 🙈

**Comment by Skrypt** [comment]
But you we're right 😄

**Comment by sebastienros** [comment]
Looks perfect now

**Pull request merged**
