### PR TITLE
Upgrade YesSQL 3.3.0

### PR DESCRIPTION
**Pull request by hishamco**
https://github.com/sebastienros/yessql/releases/tag/v3.3.0

### CODE REVIEW

**Comment by sebastienros** [comment]
Functional tests are failing on SQL Server
https://github.com/OrchardCMS/OrchardCore/actions/runs/3734315293/jobs/6336219068

**Comment by hishamco** [comment]
> Functional tests are failing on SQL Server

Why it doesn't show up on the checks here? I need to check if something related or not

**Comment by sebastienros** [comment]
We don't run the functional tests on all databases on standard checks.

**Comment by hishamco** [comment]
I see, I thought we run them ;) One more thing does SQL Server connection string is using trusted connection? I might need to run the tests on my laptop with all database providers

**Comment by sebastienros** [comment]
@hishamco good idea about the connection, that might be the reason.

**Review by sebastienros — APPROVED** [review]

**Comment by sebastienros** [comment]
It's passing now 👏

**Comment by hishamco** [comment]
I'm not sure if have a docs about Trusted connection for SQL Server /cc @agriffard

**Pull request merged**
