### PR TITLE
Obsolete SiteOwner claim and fix OpenId

### PR DESCRIPTION
**Pull request by MikeAlhayek**
Fix https://github.com/OrchardCMS/OrchardCore/issues/17083

### CODE REVIEW

**Review by kevinchalet — APPROVED** [review]
:shipit:

**Comment by Piedone** [comment]
This is supposed to be NOT breaking, no, @kevinchalet? This is meant for 2.1.2.

**Comment by MikeAlhayek** [comment]
@kevinchalet I made the change to reduce the DB call. But why did you tag this as a breaking change? The other PR is a breaking change, this one should not be.

**Comment by gvkries** [comment]
I would like to question this. Why did you obsolete the `SiteOwner` claim? As we don't have a fixed role for site owners, the information about which role is actually used for granting site owner permission is worth to be available in the claims.

This doesn't mean that authorization should dependent on the claim alone.

**Comment by kevinchalet** [comment]
> This is supposed to be NOT breaking, no, @kevinchalet? (Since you added the label.) This is meant for 2.1.2 and shouldn't be breaking. (Obsoletion warnings are OK.)

> @kevinchalet I made the change to reduce the DB call. But why did you tag this as a breaking change?

`RoleClaimsProvider` was updated in both PRs to no longer add the site owner claim in the claims collection (enough though this one preserves the static field), which is technically an observable/breaking change.

That said, it's not a huge deal, so if you think it's better not to flag it as breaking, that's fine 👍🏻

**Comment by MikeAlhayek** [comment]
@gvkries after we introduced the ISystemRoleNameProvider, it is easy to know if the user is an admin. When the user login, we assign them a claim for every role they belong to. With these claims, we can simply check to see if the user has the admin role and treat it as we did for the SiteOwner claim.  So having a SiteOwner claim is extra info that isn't needed to check if a user is a site owner or not

**Comment by gvkries** [comment]
@MikeAlhayek We don't need the claim ourselves, I never questioned that. But by only using the claims of a user, you don't have the same information about permissions as before. Because you may not know the administrator role name and the permission claims are gone. My concern is only in comparison to those permission claims and there unavailability for admin users. But if you're sure we don't need this I'm fine with that decision. But maybe we should not rush such a security related decision in the future.

**Comment by gvkries** [comment]
> But as Kevin mentioned, we don't want people to actually use it or even being to depend on it.

And I just disagree. I think you/we had a valid point of adding that claim. Our permission system is not only a role based one. 
Anyway, let's not waste time on this any longer 😇

**Pull request merged**
