### PR TITLE
Contained Content Item Routing

### PR DESCRIPTION
**Pull request by deanmarcussen**
Fixes https://github.com/OrchardCMS/OrchardCore/issues/2688

WIP

Introduces a Container Routing Part which provides routes for contained items, like taxonomies, and bag items.

Includes compromises to achieve this, however is achievable, and can provide clean routes, e.g. for a taxonomy `/categories/travel/some-place` 

Will demo and see what everyone thinks

Currently there's also a lot of code duplication between autoroute and container route, so would look to resolve some of that later

@jtkech For info I abstracted the transformer rather than using multiple transformers, as the catchall pattern could only be used by one transformer, or if a catchall, and a not quite catchall transformer used, a third not quite catchall transformer couldn't be used.

### CODE REVIEW

**Comment by mawendel** [comment]
Great Dean, this was exactly what i was looking for a little while back!

**Comment by jtkech** [comment]
@deanmarcussen

Okay makes sense, so a kind of composite transformer, let me know if you have any problem ;)

**Comment by deanmarcussen** [comment]
> Okay makes sense, so a kind of composite transformer, let me know if you have any problem ;)

Yes, kind of @jtkech - not totally, because a transformer would check better for ambiguous matches, where these providers rely on check for duplicates before adding entries.

I chose not to make it async, because our `IAutorouteEntries` pattern, doesn't need it, and performance... but let me know if you think it would be better to be async by default (as the transformer's do use `ValueTask`)

**Comment by deanmarcussen** [comment]
Replaced by https://github.com/OrchardCMS/OrchardCore/pull/5665 as was easier than dealing with the merge conflicts.

Leaving this branch intact, but pr closed

**Pull request closed without merging**
