### PR TITLE
Move LiquidPart models to abstractions

### PR DESCRIPTION
**Pull request by CrestApps**
Move LiquidPart models to abstractions and update find name to match the class name

### CODE REVIEW

**Comment by hishamco** [comment]
Just a quick comment not related to the PR, why I see many commits everytime when you push a PR, could you please rebase on `main` branch, then push your commits

**Comment by CrestApps** [comment]
@hishamco i’ll research how to rebase.

**Comment by hishamco** [comment]
If you have a Git client such as GitHub client or Fork you can easily select the branch, right click then rebase

**Comment by sebastienros** [comment]
We don't put parts in abstractions, and we don't want Liquid abstractions to reference Content Management.

Maybe you are looking for something like an Aspect to put in abstractions (c.f. IBodyAspect). Can you explain your use-case?

**Comment by CrestApps** [comment]
> If you have a Git client such as GitHub client or Fork you can easily select the branch, right click then rebase

@hishamco I don't think I can do rebase. maybe I am not following a specific workflow. but here is what I typically do.
1. I have a never changing main branch which is the original fork. This branch will always be 1:1 with OrchardCore:main. this should prevent any conflicts
2. Start a new feature branch from my main branch.
3. Make all my changed to the feature branch 
4. Create a PR

If I rebase my feature branch into my master, now my main/master branch will be different from OrchardCore:main.

Let me know if there is a better more recommended approach to follow

**Comment by hishamco** [comment]
Do you have a Git client or you are working from CMD? Please try "Fork" it's simple and easy Git client that can simplify the Git stuff from the UI

**Comment by CrestApps** [comment]
@hishamco I use Visual Studio 2022 to do git commands. I don't know what is the recommended workflow but the workflow I am using is stated [above](https://github.com/OrchardCMS/OrchardCore/pull/11722#issuecomment-1133656263)

**Pull request closed without merging**
