### PR TITLE
Update OrchardCore.Translations.All

### PR DESCRIPTION
**Pull request by hishamco**
Address part of #5841

### CODE REVIEW

**Comment by hishamco** [comment]
FYI this should work after merge [this](https://github.com/OrchardCMS/OrchardCore.Translations/pull/47)PR and push `OrchardCore.Translations` to NuGet

**Comment by hishamco** [comment]
@agriffard did we update the version?

**Comment by agriffard** [comment]
Yes, `1.0.0-rc2-108003` in rc2 branch.

@sebastienros still needs to merge master to dev.

**Comment by hishamco** [comment]
That's why I'm wondering why the PR is not merged ;)

**Pull request closed without merging**
