### PR TITLE
Cleanup unused things

### PR DESCRIPTION
**Pull request by jtkech**
To be continued

### CODE REVIEW

**Comment by sebastienros** [comment]
Good to see you are alive

**Comment by jtkech** [comment]
Good to see you are alive too ;)

**Comment by hishamco** [comment]
@jtkech please let me know if you need any help on this, seems the changed files are HUGE ;)

**Comment by jtkech** [comment]
@hishamco 

That's okay it's finished, only simple things but many of them

One thing is that we inject `ILogger<SomeType>` so that the factory returns the right implementation, but then we don't need an `ILogger<SomeType> _logger` field, we just need an `ILogger _logger` field

Idem with the string / html localizers.

**Comment by hishamco** [comment]
I can help you on this, there are many places where `IStringLocalizer <T>` and `IHtmlLocalizer <T>` are used

**Comment by jtkech** [comment]
Thanks but already done this w-end ;)

Also changed all the remaining logger / localizer that was still using property getter

**Pull request merged**
