### PR TITLE
Add IDE support to project templates

### PR DESCRIPTION
**Pull request by microposmp**
Update project templates to support Visual Studio New Project dialog. Should also work with other IDE.

Basic tests have been made to create projects (Agency Theme) with both .Net Core 3.1 and .Net 5.0 with the latest Orchard Core preview packages (1.0.0-rc2-15673).

### CODE REVIEW

**Comment by Skrypt** [comment]
Good initiative. I can't review this one. Anyone knows about this feature?

**Comment by agriffard** [comment]
Close/Reopen to rebuild.

**Comment by jtkech** [comment]
Looks good, i will try it asap

**Comment by agriffard** [comment]
Did you have time to test it @jtkech ?

**Comment by hishamco** [comment]
@agriffard I think it's great to demo this feature, I may test it after I finialize two PRs on y hands

**Review by jtkech — APPROVED** [review]

**Comment by hishamco** [comment]
Seems it has been merged ;)

Thanks @microposmp for your contribution

**Comment by microposmp** [comment]
Thanks, I can do a demo at the next meeting.

Fixes #8100

**Comment by hishamco** [comment]
@microposmp can you add some docs showing how to use the VS templates, I think it's useful for those who prefer VS instead of CLI

**Comment by microposmp** [comment]
@hishamco Yes, I can add docs that show how to use it. Will do it later this week.

**Comment by hishamco** [comment]
I created #8243

**Pull request merged**
