### PR TITLE
Adjust text of marker file hint (8270)

### LINKED ISSUE #8270: Is Azure Blob Storage directory marker really safe to delete?
### Describe the bug

`BlobFileStore` currently says for the OrchardCore.Media.txt files that "This is a directory marker file created by Orchard Core. It is safe to delete it." (see https://github.com/OrchardCMS/OrchardCore/blob/c72c6deb44a5e20c1040c26f12613a105aed33a8/src/OrchardCore/OrchardCore.FileStorage.AzureBlob/BlobFileStore.cs#L359). However, are these really safe to delete? I don't think so. You need them to list empty directories, and even if you can delete them from a non-empty directory without issues if you empty it later it'll cause a problem.

### Expected behavior

I'd just make this say "This is a directory marker file created by Orchard Core. Please don't delete it."

### PR DESCRIPTION
**Pull request by w-ko**
Addresses Azure Blob Storage marker hint stating it is safe to delete.

Fixes #8270

### CODE REVIEW

**Comment by w-ko** [comment]
@dotnet-policy-service agree

**Review by Skrypt — APPROVED** [review]

**Comment by Piedone** [comment]
@all-contributors please add @w-ko for code.

**Comment by Piedone** [comment]
Thank you for your contributions, and congrats on your first one!

**Comment by w-ko** [comment]
Awesome, feals great.
Thank you!

**Pull request merged**
