### PR TITLE
Avoid null exception when href is null.

### LINKED ISSUE #15752: Null reference exception in the Admin theme
While upgrading our website from 1.6 to 1.82, we ran into an issue with the Admin theme. Line 12 in NavigationItemLink-admin.cshtml is not checking for null, which prevents the theme from rendering.

Original:

 if (Model.Href.ToString() == "#")

Changed to:

 if ( ( Model.Href?.ToString() ?? "#" ) == "#")

Thanks

### PR DESCRIPTION
**Pull request by MikeAlhayek**
Fix #15752

### CODE REVIEW

**Comment by Piedone** [comment]
As I explained under the issue, that property shouldn't be null, to begin with. And if it is, we should throw a proper exception, because it's an invalid state for the menu, we shouldn't hide that.

**Comment by MikeAlhayek** [comment]
> As I explained under the issue, that property shouldn't be null, to begin with. And if it is, we should throw a proper exception, because it's an invalid state for the menu, we shouldn't hide that.

It won't be null if it was was added by the UI. But if you add it from other sources like migration, it could be null. The code should avoid throw an unexpected a null reference exception.

**Comment by Piedone** [comment]
Is it OK if it's null? I don't think a null `Href` makes sense. Why would we have such menu items?

**Comment by MikeAlhayek** [comment]
> Is it OK if it's null? I don't think a null Href makes sense. Why would we have such menu items?

It is not okay. But, we can incorrectly migrate a site with a null value outside the driver logic. Maybe line 12 should read this instead

```
Model.Href == null || Model.Href.ToString() == "#"
```

this way if there is an incorrect null value, we treat it as `#`

**Comment by Piedone** [comment]
That would explain how it can happen at all, but the corresponding issue is about `Href` being null for a menu item coming from code (that I can't reproduce and am baffled about how is possible, to begin with).

Having

```
Model.Href == null || Model.Href.ToString() == "#"
```

looks good, but this wouldn't yet fix the problem in the linked issue, just hide it. We can then merge this PR but I'd wait for the issue author to confirm what the root of the problem is.

**Comment by MikeAlhayek** [comment]
> looks good, but this wouldn't yet fix the problem in the linked issue, just hide it. We can then merge this PR but I'd wait for the issue author to confirm what the root of the problem is.

The root of the problem is storing incorrect value in the database. But, it is better if out code does not throw unexpected exception. So we can treat null as '#' so it does not break the app, but the menu item will not be useful.

**Comment by Piedone** [comment]
This isn't coming from the DB. Read from here: https://github.com/OrchardCMS/OrchardCore/issues/15752#issuecomment-2056993023

**Comment by MikeAlhayek** [comment]
@Piedone yes we should understand how that menu item is added. But, I also think we should also take this PR

**Comment by Piedone** [comment]
That's what I also said :).

**Review by Piedone — APPROVED** [review]
Looks good, but I'd like to give Italo more chance to reply under the issue. I'll merge this on Monday otherwise.

**Pull request merged**
