### PR TITLE
Fix namespace in OC.Autoroute.Core

### PR DESCRIPTION
**Pull request by hishamco**

### CODE REVIEW

**Comment by Skrypt** [comment]
I think we need to decide first if we should differentiate these namespaces or not because it is not consistent throughout the entire Core implementations. I prefer making a distinction for the Core modules because it is a Core implementation for us to use in the context of OC.

Else, Abstractions and main module can use the same namespace easily without an issue. But I tend to prefer making a distinction on namespaces. Of course, we can't start changing these without breaking people custom implementations. So, that's part of refactoring the entire code base as a framework and guideline around it.

**Comment by hishamco** [comment]
We already use the same namespace for both abstraction and implementations, have a look to `OC.Contents.Core`, `OC.Setup.Core`, `OC.Users.Core`

**Comment by hishamco** [comment]
FYI even ASP.NET team follows the same naming convensions

**Comment by jtkech** [comment]
Take care about changing the namespaces, for example if you change the namespace of a `Document` or a `DataMigration` whose full names are used on YesSql side, here you're in luck, the AutorouteState is a memory only Document, and the namespace of the Migrations was not changed ;)

I think there are many other places where the namespaces could be changed, I saw some including the `Abstractions` term, some are not in sync with the file locations, for example `OC.Environment.Shell` that I never dared to change ;)

So, if worth to do, maybe a more global PR but maybe only for a new major release.

**Comment by hishamco** [comment]
> here you're in luck, the AutorouteState is a memory only Document, and the namespace of the Migrations was not changed ;)

Ya I remembered your words on another PR, where the document name space has been changed

> So, if worth to do, maybe a more global PR but maybe only for a new major release.

I prefer multiple minor managable PRs instead of a BiG one

**Comment by hishamco** [comment]
> here you're in luck, the AutorouteState is a memory only Document, and the namespace of the Migrations was not changed ;)

Ya I remembered your words on another PR, where the document name space has been changed

> So, if worth to do, maybe a more global PR but maybe only for a new major release.

I prefer multiple minor managable PRs instead of a BiG one

**Comment by hishamco** [comment]
@sebastienros can we accept this for `1.6.0`

**Comment by sebastienros** [comment]
Too much of a breaking change.
AutorouteStateDocument and AutorouteMapIndex are potentially used in other places that will break.
If the document is stored in db, then the Type column is impacted.

I think it will require more thoughts, and definitely not be merged a few days before the release. And if it's not the only one like this there is no reason to patch that.

**Pull request closed without merging**
