### PR TITLE
Fix AzureAI Search issues

### PR DESCRIPTION
**Pull request by MikeAlhayek**
In this PR I fix the following issues that I encountered with Azure AI

 1. The Search Index content Part and Type settings was not saving the `Included` flag.
 2. Ensure we save IndexName and IndexFullName to the settings document.
 3. Fix `AzureAISearchIndexSettings` recipe step

### CODE REVIEW

**Comment by Piedone** [comment]
Why don't merge?

**Comment by MikeAlhayek** [comment]
@Piedone because I thought of something else and did not want someone to merge it yet. Anyway, it's ready not. If you like you can review it.

**Comment by Piedone** [comment]
In that case, you can convert it into a draft, that communicates the in-progress intent quite well.

I don't really know anything about AI search, so I'm probably not the best person to review this.

**Comment by MikeAlhayek** [comment]
Yeah I think I am the only one that is using it :)

**Pull request merged**
