### PR TITLE
Admin Urls

### LINKED ISSUE #4647: Remove OrchardCore. prefix from admin URLs
I don't see any value to have `OrchardCore.*` prefix in almost if not all the URLs in the admin, for instance https://localhost:5001/blog/**OrchardCore.Email**/Admin/Index `OrchardCore.Email` is reflect the module name, can we use alias name instead to become https://localhost:5001/blog/email/Admin/Index

/cc @agriffard @jtkech @sebastienros @Skrypt

### PR DESCRIPTION
**Pull request by agriffard**
Prettify some admin urls and provide a way to change the `admin` prefix.

It will have to be done on every admin controller if we want this to be consistent.

Fixes #4647, #4163, #2779, #1329

### CODE REVIEW

**Comment by agriffard** [comment]
@deanmarcussen I created an AdminOptions.

Is it supposed to work when I set it like this in `appsettings.json`?
```
  "Admin": {
    "AdminUrlPrefix": "Cms"
  },
```

**Comment by deanmarcussen** [comment]
Yes!

But for the admin options you need to configure it in a startup somewhere.

Hmm, which startup?

The code would be something like
```
services.Configure<AdminOptions>(_shellConfiguration.GetSettings<AdminOptions>());
```

Probably in here is ok
https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.Admin/Startup.cs

**Comment by jtkech** [comment]
See e.g in the `OC.Media.Azure` and `OC.Apis.GrahQL` startups how to inject and use an `IShellConfiguration` to configure your options.

Don't forget all the places where the hardcoded `Admin` string is used, e.g in some admin filters.

**Comment by hishamco** [comment]
I think I will remove my old PR, thanks again Antonie

**Comment by sebastienros** [comment]
Looks good. Conflicts.

**Comment by jtkech** [comment]
@agriffard i will test it and review it asap.

For the failing CI test, i think you need to update the page urls in `setup.test.js`.

**Comment by jtkech** [comment]
@agriffard for infos

- In `ContentTypeExtensions` to get the controller name i used [the same code as mvc](https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/Mvc.Core/src/ApplicationModels/DefaultApplicationModelProvider.cs#L170) where they use `EndsWith()`, by convention.

- For its usage, i tried to reduce some reflection stuff by using intermediate variables when we want to get the controller name of the same controller multiple times.

- But for perf not sure about checking if the controller type inherit from `Controller`, i would have only used a simple substring of the `nameof(TheController)`, but on another side it is only used on startup and it adds more checking, so for me that's okay.

For the last point i let you decide and then maybe not using intermediate variables, meanwhile i approved the PR.

**Comment by edwinyosorahardjo** [comment]
how do I disable admin routing completely, as in:
- cms hosted in cms.mysite/admin
- mysite (only site with no cms routing)

**Pull request merged**
