### PR TITLE
migration for BodyPart to HtmlBodyPart name changes.

### PR DESCRIPTION
**Pull request by awyl**
I haven't fully tested it.  The query runs fine with my Sqlite database.  However, I couldn't load the editor, which should be fix at #2022.

SQL query was provided by @Skrypt at https://github.com/OrchardCMS/OrchardCore/pull/1933#issuecomment-398578185

### CODE REVIEW

**Comment by awyl** [comment]
Just tested after #2022 merged.

MarkdownPart loads and saves fine.

**Comment by Skrypt** [comment]
Only thing I'm worried is that we don't use YesSQL SQL dialect to support different DB syntax. We normally should use the YesSQL Session to do this to avoid conflicts between different DB's.

**Comment by sebastienros** [comment]
1- Ensure REPLACE is valid in the 4 database types we use
2- Prefix the tables with the tenant prefix

**Comment by Skrypt** [comment]
https://www.w3resource.com/mysql/string-functions/mysql-replace-function.php
https://www.w3resource.com/sqlite/core-functions-replace.php
https://docs.microsoft.com/en-us/sql/t-sql/functions/replace-transact-sql?view=sql-server-2017
http://www.postgresqltutorial.com/postgresql-replace/

I'd say yes.

**Comment by sebastienros** [comment]
That sounds awesome!

Now a little more effort to support the prefixes for multi-tenancy

**Comment by Skrypt** [comment]
Maybe we could also use a UpdateFrom1.sql file instead of using that constant string.

**Comment by sebastienros** [comment]
LGTM, can someone test it on an existing site with Markdown and BodyPart, with a table prefix?
I will do it too.

**Pull request merged**
