### PR TITLE
Cypress 9.0

### PR DESCRIPTION
**Pull request by agriffard**
https://www.npmjs.com/package/cypress/v/9.0.0

### CODE REVIEW

**Comment by Skrypt** [comment]
Does it fix the npm install issues with `har-validator`?

**Comment by agriffard** [comment]
> Does it fix the npm install issues with `har-validator`?

I never encountered this `har-validator` issue by executing `npm i`.

**Comment by Skrypt** [comment]
You need to do `cd /test/Functional` and `npm install`
And `cd /cypress-commands` and `npm install`

This is not part of our main package.json file so it does not execute npm install for these.

**Comment by agriffard** [comment]
> You need to do `cd /test/Functional` and `npm install` And `cd /cypress-commands` and `npm install`
> 
> This is not part of our main package.json file so it does not execute npm install for these automatically.

No errors restoring packages in those folders.

**Review by Skrypt — APPROVED** [review]

**Pull request merged**
