### PR TITLE
Fix HtmlFieldSettings not showing up

### LINKED ISSUE #7112: Html field settings not editable
I am running version `1.0.0-rc2-14344`

image

### PR DESCRIPTION
**Pull request by jptissot**
Fixes #7112

### CODE REVIEW

**Comment by sebastienros** [comment]
This is not the only settings driver that was targeting "Editor" . The change was made by @deanmarcussen in this commit (sanitization):
https://github.com/OrchardCMS/OrchardCore/commit/99cfa8e6c5447dfb7b27c7320586983b11409999#diff-3b391a96d2e285da64e4642f4b98b088

I think we need to understand why the change was done, and also fix it everywhere it's wrong, as there are other places that have this.

**Comment by jptissot** [comment]
I think you need to target Editor for editor based options (TextFieldPredefinedList) but the common options for a field need to be rendered in the Content. I think this was just a typo.

**Comment by jptissot** [comment]
I looked at the other field option drivers and they all looked fine.

**Comment by deanmarcussen** [comment]
Yeah, I couldn't repro @jptissot issue but I think the fix is good.

As @jptissot general settings / common to all editors should be in `Content` and editor modes should be in `Editor`

Change originally made by @agriffard and I think just a typo.

**Pull request merged**
