### PR TITLE
Manage Content Search text

### PR DESCRIPTION
**Pull request by Loneve**
Sorry, the last change was not good enough, should keep the Search text

### CODE REVIEW

**Comment by alexbocharov** [comment]
@Loneve Related with #3054?

**Comment by Loneve** [comment]
@alexbocharov yes

**Comment by alexbocharov** [comment]
In the future, is it better to make one request :wink:

**Comment by Loneve** [comment]
Ok，I tried a request, but something wrong
qq 20190118175311

**Comment by alexbocharov** [comment]
dev in dev?

What is a branch contains changes?

**Pull request merged**
