### PR TITLE
Redirect the user to edit role when a new role is created

### LINKED ISSUE #11959: When a user create a new role, redirect the use to the edit page instead of index
### Is your feature request related to a problem? Please describe.
When a new role is created, currently we redirect the user to the [Index](https://github.com/OrchardCMS/OrchardCore/blob/main/src/OrchardCore.Modules/OrchardCore.Roles/Controllers/AdminController.cs#L116) view. After a user adds a new role, they would likely want to assign permissions to it. from a user experience, I think it would be more logical to redirect the user to the Edit screen of that role instead.

### Describe the solution you'd like
After a new role is successfully created, redirect the user to the edit view `return RedirectToAction(nameof(Edit), new { id = role.RoleName});`

### PR DESCRIPTION
**Pull request by CrestApps**
Fix #11959

### CODE REVIEW

**Comment by hishamco** [comment]
It's not compulsary to assign permissions after creation directly

**Comment by CrestApps** [comment]
@hishamco its not. But 9 time out of 10 you will add permission.

**Comment by ns8482e** [comment]
That not good UX

IMO on save of add or edit should return to list.

 If you have save and continue button then staying on edit is fine.

I guess you want to provide `save and continue` as an additional option

**Comment by hishamco** [comment]
@ns8482e reads my mind, I will push a PR to supports save and continue as we already did in many places. We could add nother option `Save and edit` because roles are little bit different because they have permissions

**Pull request closed without merging**
