### PR TITLE
Fixed string localiser

### PR DESCRIPTION
**Pull request by duncanhoggan**
Looks like the reference to the string localiser was never swapped for the UserTaskEvent.
There may be more of these, but this is a blocker on a project at the moment.
#5662

### CODE REVIEW

**Comment by duncanhoggan** [comment]
Want to rebase before this goes

**Comment by duncanhoggan** [comment]
Rebase done, nice and clean now

**Comment by jtkech** [comment]
Yes i agree, there is a remaining T that has not been replaced with S

Yes, open a new PR then i will approve it

**Comment by hishamco** [comment]
Strange!! I scan the entire source few months ago, seems we need a roslyn analyzer to do this in out behalf ;)

**Comment by jtkech** [comment]
Yes because the T property is still defined and used in one place, so ...

**Pull request closed without merging**
