### PR TITLE
VS Test SDK 16.9.1

### PR DESCRIPTION
**Pull request by agriffard**
https://github.com/microsoft/vstest/releases/tag/v16.9.1

### CODE REVIEW

**Comment by agriffard** [comment]
Was there a reason to not update it?

**Comment by hishamco** [comment]
Can we have a BOT to upgrade the packages automatically?

**Comment by sebastienros** [comment]
What is this package adding? If only support for .NET test types, then we don't use it

**Comment by agriffard** [comment]
Used to run the tests on VS.

**Pull request merged**
