### PR TITLE
 Fix "Context Type" filter font color

### LINKED ISSUE #12371: Fix Context Type filter font color
### Describe the bug
When viewing the Manage contents section, the "Content Type" filter has a different text color than the other filters. I think it would look better if it matches the other filters.

image

### PR DESCRIPTION
**Pull request by MikeAlhayek**
Fix #12371 

default theme
image

dark theme
image

### CODE REVIEW

**Comment by hishamco** [comment]
Please share a screenshot for both Light & Dark themes

**Review by Skrypt — APPROVED** [review]

**Comment by MikeAlhayek** [comment]
@hishamco I updated the PR with some screenshots

**Comment by hishamco** [comment]
Awesome

**Comment by hishamco** [comment]
BTW is this will reflect to all filters coz we might need to revise content items page too

**Pull request merged**
