### PR TITLE
Non awaited async calls.

### PR DESCRIPTION
**Pull request by jtkech**
Maybe related to an issue that @peterkeating talked on gitter.

So, here i used our `InvokeAsync()`, let me know if better to use a simple foreach loop.

Also, in 2 places i return the `Task` of `ToList().InvokeAsync()` in place of using `await`, that's ok but when doing this on a collection, i don't remember if it is the best for exception handling.

### CODE REVIEW

**Comment by sebastienros** [comment]
I think foreach are better otherwise we'll swallow exceptions, which was not the case in the code before

**Comment by peterkeating** [comment]
Happy to give this a try when ready with the rogue recipe that was consistently causing the issue explained in Gitter.

**Comment by sebastienros** [comment]
Can you share this recipe at least privately with JT and me?

**Comment by jtkech** [comment]
Okay, i will update the PR.

**Pull request merged**
