### PR TITLE
Dark admin theme setting

### PR DESCRIPTION
**Pull request by agriffard**
Try to see what is needed to have a fully supported dark admin theme.

Added a setting to specify a Light or a Dark background color (and reciprocally a Dark or a Light text color)

I don't see a way to do it full client side.
It would require to change many pages that have List, Modal, dropdown, card, ... to add the expected css class according to the current theme.

So the first question is: Do we want such a feature and everything that it implies?

### CODE REVIEW

**Comment by agriffard** [comment]
For example, the content items admin page would look like this:
image

**Comment by hishamco** [comment]
I like the idea, but it would be nice if it's extensible, of course docs may needed to add new theme like blue theme .. etc

I think this should go after 1.0.0 release, but I like to hear from other folks

BTW I have some thoughts and ideas about admin site design and extensibility point that I'd like to share

Thanks

**Comment by hishamco** [comment]
Why this is closed?

**Comment by hishamco** [comment]
Seems @Skrypt is using something similar, I always see his screen shoots with Dark theme. Again I like the idea with some extensibility enabled

Thanks

**Pull request closed without merging**
