### PR TITLE
Add ShortCodes Rich APIs

### PR DESCRIPTION
**Pull request by hishamco**
Address part of #6323

### CODE REVIEW

**Comment by hishamco** [comment]
FYI, the unit tests was passed before merge the change from `[media]` to `[image]` may be it is a good feature to target more than one shortcode with the same logic

This will allow us to write a single shortcode for both `[audio]` & `[video]` for instance

**Comment by sebastienros** [comment]
https://github.com/sebastienros/shortcodes

**Comment by hishamco** [comment]
I saw you are started shortcodes projects several days ago but I don't know what was the path for I

I think the APIs that you introduced is cool for parsing which is the thing that I need to use

If you don't mind I can do a few changes to built on top of the project that you already started, or if you have another plan please let me know

**Comment by hishamco** [comment]
Closing this while the Shortcode implemented based on Seb Shortcodes library, I may add few features on top of it in OCC repo

**Pull request closed without merging**
