### PR TITLE
Default value for BooleanField.

### PR DESCRIPTION
**Pull request by microposmp**
Added option to specify a default value to BooleanField.

### CODE REVIEW

**Comment by sebastienros** [comment]
Don't we have other editors to update for the boolean field?

**Comment by microposmp** [comment]
The editor is selectable when attaching the BooleanField to a content type. The option I suggested is on the field configuration screen. I used the same BooleanField layout that is used for Creatable, Listable on the edit content type screen.

image

In the image below:
1. The suggested option to configure the default value when creating content items of this type.
2. Option to select the editor to be used when working with the content item.

image

When adding a new content item of the type with default value set to true and "Switch" used as the selected editor for the BooleanField is looks like below.

image

I don't think we have to support the other editors on the field configuration screen.

**Comment by sebastienros** [comment]
What you are saying is that because you pre-assigned the default value to the view model it is applied automatically to all editors?

**Comment by microposmp** [comment]
When creating a new content item the default value will be preselected. Once the item is saved or published the value chosen when creating the item will be shown.

The idea is to give the designer of the content type the possibility to set the value that will be the most common as a default. It's only used when creating a new item to make it more efficient.

In our case we have some types with BooleanFields where the selected value almost always will be true. Only in a few exceptions it will be false. In those cases, it can be overridden or changed at a later time.

**Comment by sebastienros** [comment]
Good.

The UI is not very intuitive IMO. It says "Default value" so I would expect that it would let me set a default value if I check this box, not that the check means the default value is true. So maybe change this text to "Set the default value as true", or "Initialize the editor with 'true'". Or with better english if you find one.

**Comment by microposmp** [comment]
image

**Comment by sebastienros** [comment]
This is not a good "checkbox pattern", sorry. The main text should be what you sign for. Here you sign for "Default value" which doesn't make any sense. "Default value is true" would make more sense.

**Comment by microposmp** [comment]
image

Ok, thanks. This is great feedback. Kept the information that it only applies when creating a new item in the hint. Maybe that is not needed.

**Comment by sebastienros** [comment]
Good, add a comment to this thread when it's done so I get a notification.

**Comment by microposmp** [comment]
I made the change directly in the Github website. I'll make a new fork when my open pull requests are closed.

**Comment by sebastienros** [comment]
> I'll make a new fork when my open pull requests are closed

Why?

**Comment by microposmp** [comment]
I have made a pull request from my own dev branch that I get included everytime I greate a new branch from it and would like to start from a clean local dev branch.

**Comment by sebastienros** [comment]
When your branches are merged, you can delete them to keep your repos clean

**Comment by microposmp** [comment]
Yes, I'll delete them and not make any changes on the dev branch. Only make merges from the upstream dev branch into it.

**Pull request merged**
