### PR TITLE
Add permissions to localization & reverse proxy settings navigation

### LINKED ISSUE #3775: permission issu in admin panel
@matiasmolleja  these menus should not show, like https menu  #3628
Capture

### PR DESCRIPTION
**Pull request by hishamco**
Fixes #3775

### CODE REVIEW

**Comment by sebastienros** [comment]
Reopening the PR to trigger the CI again

**Comment by hishamco** [comment]
All checks have passed :)

**Comment by aghili371** [comment]
please merge this.

**Comment by hishamco** [comment]
Waiting for Seb 😊

**Pull request merged**
