### PR TITLE
Removes a reference to options in RequireSettings

### PR DESCRIPTION
**Pull request by gvkries**
Removes an unneeded reference to the ResourceManagementOptions in RequireSettings.

/cc @sebastienros

### CODE REVIEW

**Review by sebastienros — APPROVED** [review]
Even more right since the object can be mutated even if the options aren't.

**Comment by gvkries** [comment]
It's refactored only, it should not change behavior.

**Comment by Piedone** [comment]
Please do test, because this removes code added by the PR that fixes that issue.

**Comment by gvkries** [comment]
It just moves the code from the c'tor to the `New()` method to avoid keeping a reference around. And therefore it also considers changes done to the parent `RequireSettings` as well.

**Comment by gvkries** [comment]
So yes, #16401 is still of cause.

**Comment by Piedone** [comment]
OK then!

**Pull request merged**
