### PR TITLE
Forgot reset password

### PR DESCRIPTION
**Pull request by sipronunciaaigor**
This is the core code to allow a user to reset his password #1299 .

~~I still need to implement and test the token validation (the code still raises "Invalid token" when attempting to validate the reset token) - this is already under development - and Reset token is working. Sending email still needs to be implemented/injected (this refers to Issue #1138 )~~
Improvements to be done, but not in the TODO list for this card: integrate a templating system.

TODO list
- [x] forgot password pipeline
- [x] reset password pipeline

- [x] fix "invalid token" error
- [x] integrate email module #1138

### CODE REVIEW

**Comment by sebastienros** [comment]
I assume we'll need to focus on the email module before you can make any more progress ...

**Comment by sipronunciaaigor** [comment]
I already have the code to integrate the email as soon as the module is ready. It's a non compiling one, that's why I avoided to commit.

Anyway I'm still investigating the invalid token issue. I don't get why it's not working (it should have been straight forward). I'm using the built-in functionality from Identity Framework. I'm able to generate the token (I can read it with no problems), but it's not recognized when I send it back...

**Comment by OlegLario** [comment]
I`m new at this project, can you advise, if this branch merged at dev, why I do not see your changes?  Sorry for offtop.

**Comment by sipronunciaaigor** [comment]
@OlegLario It's still a pull request and it's not effectively merged into dev. It passes the tests so that it can potentially be merged, but it's not ready yet to be merged definitively.

**Comment by sipronunciaaigor** [comment]
@sebastienros I fixed the "invalid token" error: it was an encoding/decoding problem. Now it encodes/decodes the token using base64 instead of url encoding.
Let me know if I can help with #1138: its integration is the last thing which is missing with this module.

**Comment by sebastienros** [comment]
There has been some progress in both modules, that's great. I hope I can test it very soon to merge it.

**Comment by sebastienros** [comment]
Did you look at what the default MVC templates are doing? Maybe I already told you but we should do the same thing, at least for security best practice reasons.

**Comment by sipronunciaaigor** [comment]
I started from the dotnet core 2 boilerplate. What do you think I should improve from the security viewpoint?

**Comment by sebastienros** [comment]
Email module has been merged, we can use it now

**Comment by sipronunciaaigor** [comment]
@sebastienros Sorry for the delay, but I noticed the updates only few days ago (it sat there for a couple of months...).
Anyway: now the module is finished.
I don't know if there is a template module somewhere.
Ideally the email content management should be centralized into an admin area where the admin can set the text, the subject, the sender, the body etc.
For now it is handled with a simple string.

**Pull request closed without merging**
