### PR TITLE
Initialize the RequestLocalizationMiddleware asynchronously

### LINKED ISSUE #14798: Initialize the RequestLocalizationMiddleware asynchronously
The options used to add the `RequestLocalizationMiddleware` to the pipeline make a synchronous call. Not a good idea to block the thread on every request that use localization.

### PR DESCRIPTION
**Pull request by MikeAlhayek**
Fix #14798

### CODE REVIEW

**Comment by hishamco** [comment]
Please hold on, I have another PR related to localization from a week or so, I need to do a final test before I merge it, and then I can look into your

**Comment by MikeAlhayek** [comment]
@hishamco this PR fixes a one issue that is causing thread locking on every single request. I am not sure what does you PR do, but I am not sure we should block this PR meanwhile.

**Comment by jtkech** [comment]
Feel wrong to me, I think we can find a way to configure the options asynchronously without having to clone the whole middleware.

Hmm the "problem" with an initializer is that it runs early, here we configure later on, for info I already suggested to add `ConfigureAsync()` to our startup, would be useful here, maybe time to do it, or as said find another compromise.

**Comment by hishamco** [comment]
> for info I already suggested to add ConfigureAsync() to our startup, would be useful here, maybe time to do it, or as said find another compromise.

I remember Seb already talked about it previously, so @MikeAlhayek I think we need to hold this PR for the moment if you don't mind

@jtkech I'm with you to have it in our startup

**Comment by hishamco** [comment]
Regarding my first comment I thought you added `ConfigureAsync()` but after I review now, I might disagree with the PR, I prefer to have `ConfigureAsync()` in our startup as JT mentioned

**Comment by MikeAlhayek** [comment]
> Feel wrong to me, I think we can find a way to configure the options asynchronously without having to clone the whole middleware.

@jtkech I don't disagree with you here. I just don't think we have better option at this point. If you are going to add ConfigureAsync, then sure we don't need to merge this PR and we can use the ConfigureAsync.

**Comment by hishamco** [comment]
Please let us don't merge this for now

**Comment by MikeAlhayek** [comment]
Closing in favor of #14801

**Pull request closed without merging**
