### PR TITLE
Use Bootstrap-grid to extend instead of full Bootstrap SASS

### PR DESCRIPTION
**Pull request by Skrypt**
* adding bootstrap-bundle ressource that has popper.js as a dependency.
* removed popper.js dependency on bootstrap ressource.
* adding missing minified ressources.
* removing theme-orchard.css files and moving back to theme css files that doesn't embed Boostrap.
* Adding back Bootstrap style and script to layout.

### CODE REVIEW

**Comment by sebastienros** [comment]
@davidhayden  If you want to check what's done here before I merge, I would appreciate. At least clone this branch and test that it fixes your carousel.

**Comment by davidhayden** [comment]
@Skrypt @sebastienros I'm getting this error in Chrome:

Failed to find a valid digest in the 'integrity' attribute for resource 'https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.bundle.js' with computed SHA-256 integrity 'MpCtO4pXnvO8EcZ9qt3jS4xgU34zesYkmIXYXRNWY2M='. The resource has been blocked.

Here is the a snippet of the Layout template I see in The Blog Theme:

```html
{% script name:"bootstrap-bundle", use_cdn:"true", version:"4", at:"Foot" %}
{% script source:"/OrchardCore.Menu/Scripts/activate-links.min.js", debug_src:"/OrchardCore.Menu/Scripts/activate-links.js", at:"Foot" %}
{% script source:"/TheBlogTheme/js/clean-blog.min.js", debug_src:"/TheBlogTheme/js/clean-blog.js", at:"Foot" %}
```
Here is the resulting HTML in the browser:

```html
<script crossorigin="anonymous" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" src="https://code.jquery.com/jquery-3.3.1.js" type="text/javascript"></script>
<script crossorigin="anonymous" integrity="sha384-AsJUT69WgSCIrLgOnMRkNjLvBl0aoHtB3vBDnAEOKRfxKMm7gvmSTJUZCefoYWdA" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.js" type="text/javascript"></script>
<script crossorigin="anonymous" integrity="sha384-fyOlGC&#x2B;soQAvVFysE2KxkXaVKf75M1Zyo6RG7thLEEwD7p6/Cso7G/iV9tPM0C/a" src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.bundle.js" type="text/javascript"></script>
<script src="/OrchardCore.Menu/Scripts/activate-links.js" type="text/javascript"></script>
<script src="/TheBlogTheme/js/clean-blog.js" type="text/javascript"></script>    <script type="text/javascript">(function($) { $('#mainNav').activateLinks(); })(jQuery);</script>
```

**Comment by Skrypt** [comment]
I made some enhancements though I still don't like the fact that we need to have more than 1 JS and CSS link on a template. Normally, for performance reasons, it is best to bundle everything up in a single file. If you look at recommendation on tools like : https://developers.google.com/speed/pagespeed/insights/?hl=fr

**Comment by sebastienros** [comment]
I don't think we should target the best scores on these templates, they are just trying to apply the StartBootstrap themes. Maybe an issue to fix in their repos directly instead of here. And at the same time serving content from external CDN might relieve some pressure on Orchard itself.

**Comment by Skrypt** [comment]
Sure, if the goal is only to stay in sync with the main theme repo then let's not push too far on this. I opened up an issue once on these repo's and had no answers so ... I believe that if someones require these things at this point he could just work it by himself. These are mostly just examples.

**Pull request merged**
