### PR TITLE
MailKit, MimeKit 3.0

### PR DESCRIPTION
**Pull request by agriffard**
https://www.nuget.org/packages/MailKit/3.0.0
https://www.nuget.org/packages/MimeKit/3.0.0
https://github.com/jstedfast/MailKit/releases/tag/3.0.0
https://github.com/jstedfast/MimeKit/releases/tag/3.0.0

### CODE REVIEW

**Comment by hishamco** [comment]
Is there any features or / and breaking-changes list?

**Comment by agriffard** [comment]
https://github.com/jstedfast/MailKit/blob/master/ReleaseNotes.md
https://github.com/jstedfast/MimeKit/blob/master/ReleaseNotes.md

> Removed APIs marked as [Obsolete] in 2.x.

But we don't seem to use those obsolete methods.

**Comment by hishamco** [comment]
https://github.com/jstedfast/MailKit/issues/1161
https://github.com/jstedfast/MimeKit/issues/705

Please hold this I need to check them ..

**Comment by hishamco** [comment]
Regarding this change https://github.com/jstedfast/MailKit/commit/e32bb65b91e701246b999dbb33b760f0fb84d633#diff-7bc7f11950f4b02de31df29546c0196e918c447abf653e9550776fd21e32b75aR78 can we return the response result into `SmtpResult`

/cc @sebastienros

**Comment by sebastienros** [comment]
If it's not fixing anything critical in OC I'd prefer to wait for after 1.2 to limit the risk of breaking anything (so close to shipping).

**Comment by hishamco** [comment]
Nothing to break according to thier changes. BTW I create a PR #10892, to add a server response that added by `MailKit`, this is useful if someone want to know the actual server response

**Comment by hishamco** [comment]
I think it's a time to look into #10892 if the upcoming version will be `2.0.0` I will change the PR because I may introduce a breaking changes

**Comment by hishamco** [comment]
I think it's a time to look into #10892 if the upcoming version will be `2.0.0` I will change the PR because I may introduce a breaking changes

**Pull request merged**
