### PR TITLE
Update OpenIddict 5.5.0

### PR DESCRIPTION
**Pull request by hishamco**
https://www.nuget.org/packages/OpenIddict/5.5.0)](https://www.nuget.org/packages/OpenIddict/5.5.0

### CODE REVIEW

**Comment by MikeAlhayek** [comment]
@kevinchalet any breaking changes or are we good with the new version?

**Comment by kevinchalet** [comment]
@MikeAlhayek nope, no breaking change in 5.5.0 (introducing breaking changes in minor versions isn't really Semver-compliant so I try to avoid it as much as possible, but when there are behavior changes, I explicitly mention them in the release notes)

**Review by kevinchalet — APPROVED** [review]
Thanks!

**Comment by agriffard** [comment]
Why `OpenIddict.Core` has not been updated with the latest version?

**Comment by kevinchalet** [comment]
> Why `OpenIddict.Core` has not been updated with the latest version?

Ah crap, I missed it during the review. Feel free to fix it 👍🏻

**Pull request merged**
