### PR TITLE
Sitemap Extended Namespace fix

### PR DESCRIPTION
**Pull request by jagbarcelo**
According to:
  https://support.google.com/webmasters/answer/189077?hl=en
the xhtml namespace should be:
  xmlns:xhtml="http://www.w3.org/1999/xhtml"

https://github.com/OrchardCMS/OrchardCore/issues/7301

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/OrchardCMS/OrchardCore?pullRequest=7315) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/OrchardCMS/OrchardCore?pullRequest=7315) before we can accept your contribution.<br/><br/>:x: jagbarcelo [sign now](https://cla.dotnetfoundation.org/OrchardCMS/OrchardCore?pullRequest=7315)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/OrchardCMS/OrchardCore?pullRequest=7315) it.</sub>

**Review by hishamco — APPROVED** [review]
LGTM

**Comment by deanmarcussen** [comment]
Yeah that's annoying.

I remember it was super difficult to test this without having a site live, that was using localization, when I wrote it.

But you have one which is helpful.

I assume this means that the sitemap no longer passes validation at https://www.sitemaps.org/protocol.html ?

**Comment by hishamco** [comment]
> I remember it was super difficult to test this without having a site live

I forgot that, so @jagbarcelo may working on LIVE one, that's why the reported this

**Comment by jagbarcelo** [comment]
No it does not pass the validation since `xhtml:link` is not declared in `http://www.w3.org/1999/xhtml`.
I have tested my xml output against https://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd using https://www.freeformatter.com/xml-validator-xsd.html and here are the results:

image

The first two errors are expected. I do not understand why it complains about `lastmod` too. It seems it has the right format.

**Review by deanmarcussen — APPROVED** [review]
> The first two errors are expected. I do not understand why it complains about `lastmod` too. It seems it has the right format.

Yes, lastmod looks correct. But google has accepted the lastmod? so ok.

Will you be submitting it to bing as well? 

They don't support the lang extensions (I believe) but I would be interested to know if they will still accept it in with the exensions in?

**Comment by jagbarcelo** [comment]
Bing Webmaster Tools also accepts the sitemap with these changes:

image

**Comment by deanmarcussen** [comment]
Great thanks @jagbarcelo nice to have the feature validated and fixed

**Pull request merged**
