### PR TITLE
Content type badges

### PR DESCRIPTION
**Pull request by agriffard**
Use badges in Content Type: Display mode, Editor.
Collapsable Options (Creatable, ...), Indexing (Full-text).
Move Shortcuts at bottom.

image

### CODE REVIEW

**Comment by agriffard** [comment]
The goal was to have a more condensed UI, to focus on Fields and Parts which are the most common tasks.

@sebastienros was confused by this new UI.

Should we revert the changes?

**Comment by hishamco** [comment]
IMHO the new UI in general is better than the old

**Comment by agriffard** [comment]
The Creatable, Listable, ... badges may be confusing because they are not linked to checkbox state and they are a repetition of the checkboxes.

My goal was to display them as a summary so you don't have to open the Options.

**Comment by deanmarcussen** [comment]
Yes this one should be reverted.

Suggestion of tabs for a future rather than the drop downs sounded better

**Comment by agriffard** [comment]
ok, reverted.

**Pull request merged**
