### PR TITLE
Use IAsyncConfigureOptions

### PR DESCRIPTION
**Pull request by hishamco**

### CODE REVIEW

**Comment by MikeAlhayek** [comment]
@hishamco `IAsyncConfigureOptions` is not the same as `IConfigureOptions`  

With `IAsyncConfigureOptions` you cannot resolve options using `IOptions<>`. `IAsyncConfigureOptions` is to be used for casees where you need to call external services after the service provider is created.

**Comment by hishamco** [comment]
> IAsyncConfigureOptions is to be used for casees where you need to call external services after the service provider is created.

@MikeAlhayek I assume we should use the options itself

**Comment by MikeAlhayek** [comment]
no. you should not use `IAsyncConfigureOptions` for configuring options. This is only to be used to initialized services that depends on settings not to configure options.

**Comment by MikeAlhayek** [comment]
yes I expect it to fail because it is called after the SP is already created.

**Comment by hishamco** [comment]
Any idea how to fix it, because this is something we might want in the email services

**Comment by MikeAlhayek** [comment]
@hishamco 
 `IAsyncConfigureOptions` does not do the same job of `IConfigurationOptions` so you cannot replace them as you seems to be trying to do in this PR.

With `IConfigurationOptions<HishamOptions>` you can inject `IOptions<HishamOptions>` into your service to get access of the `HishamOptions` object.

However, with `IAsyncConfigureOptions<HishamOptions>` you would inject it using `HishamOptions`. This does not mean let's replace `IOptions<HishamOptions>` by `HishamOptions` and just start using  `IAsyncConfigureOptions`.

in the example of `BlobOptions` you mentioned, we use `IAsyncConfigureOptions` to asynchronously initialize the blog service. We check whether or not the Blob storage container exists and if not we create a new container "after the ServiceProvider is created". Meaning at that point, we can't inject any additional service.

In your Email service, why do you think you need to use it? Which service that required initialization "not configuration"?

**Comment by hishamco** [comment]
> In your Email service, why do you think you need to use it? Which service that required initialization "not configuration"?

Seems @Piedone wants to use the async version instead of `GetAwaiter().GetResult()`, correct me if I'm wrong Zoltan

**Comment by MikeAlhayek** [comment]
which code are you referring to? It is okay to use `GetAwaiter().GetResult()` to use in `IConfigurationOptions` since that is only called during startup. and the `GetAwaiter().GetResult()` only truly blocks once during the startup cycle. Ideally, Microsoft would provider us `IConfigurationAsyncOptions` where we don't need to block at all. But at this point, Microsoft are not willing to make Option configuration async so we just have to live with it.

**Comment by Piedone** [comment]
Wait, so `IAsyncConfigureOptions<TOptions>` is NOT the async equivalent of `IConfigureOptions<TOptions>`? Given the similar name and method signature, this is really confusing.

I then suggest either one of the following:

- Rename the service, to like `IAsyncConfigurationProvider` and in its interface docs emphasize the similarity but differences to `IConfigureOptions<TOptions>`.
- Make it more similar by adding an `IAsyncOptions<T>` type to inject, with `GetValueAsync()`. This would otherwise work the same as `IOptions<T>` and its `Value` property.

**Comment by hishamco** [comment]
Ya, it confused me too :)

**Comment by hishamco** [comment]
So, Let us do it after merging Azure Email because it will take long time :)

**Comment by MikeAlhayek** [comment]
Yes @Piedone it is confusing. I had the same argument with JT when he introduced it. It may not be a bad idea to rename it. It's for initializing services not configuring options using IOption pattern.

**Comment by hishamco** [comment]
Is this solve a real problem Mike?  just kidding :)

**Comment by MikeAlhayek** [comment]
Refactoring sometimes makes sense. And sometimes is a must. But, it's typically risky to take on specially if there is no testing to ensure that the end result is the same. 

Either way, PRs should be dealt with fast. Either we request changes, close it or merge it. As previously mention a PR that takes a long time in the queue will likely mean it adds to real value

**Comment by hishamco** [comment]
@MikeAlhayek could you please close this and handle Zoltan's comments https://github.com/OrchardCMS/OrchardCore/pull/15125#issuecomment-1902778411 if you have time, while you know the differences between both APIs

**Pull request closed without merging**
