### PR TITLE
Prefix resource manager definitions for sample themes

### PR DESCRIPTION
**Pull request by deanmarcussen**
Fixes https://github.com/OrchardCMS/OrchardCore/issues/5025

### CODE REVIEW

**Comment by Skrypt** [comment]
LGTM

**Comment by Skrypt** [comment]
I'm thinking of this and could we not prefix it from a module Manifest theme name or prefix instead? This would be easier to change when copy/pasting or generating a new theme from the dotnet templates command.

**Comment by hishamco** [comment]
It would be nice if we declare the prefix as variable, so no need to change in all the places

**Comment by jtkech** [comment]
See my last comment in #5025, here a copy paste of the last part.

This knowing that the theme `IResourceManifestProvider` are scoped services but their `BuildManifests()` are called once by the manager because it has a tenant singleton cache.

**Yes, maybe a good compromise**.

- In a theme `IResourceManifestProvider` (a scoped service) check if it is the current theme or a base theme of the current one, if so build the resources, otherwise do nothing.

- When we change the current theme, restart the tenant as we do when we enable / disable a theme, so that a theme `BuildManifests()` will be re-called and will do the same check.

- Change `ResourceDefinition.DefineResource()` to allow a resource to be overridden (easy to do), this to allow a theme to override the resources of its base theme.

**Comment by jtkech** [comment]
Okay i could get a version working but just remembered that we also have dynamic theme selectors e.g based on the user, so it would need to be more dynamic and then have a perf impact.

So, too complicated for, as you said, such a little issue and it makes sense that each theme use different resource names. But it was interesting ;)

**Comment by jtkech** [comment]
Just for infos, in fact when there are multiple resources with the same name, the resource manager takes the one with the highest version, if multiple with the same version, as said it takes the 1st registered.

    // Use the highest version of all matches
    if (resource == null
        || (resourceDefinition.Version != null && new Version(resource.Version) < version))
    {
        resource = resourceDefinition;
    }

Note: If we change `< version` with `<= version` it would take the last one.

But that's okay about allowing a theme to override a resource of its base theme, knowing the above it can do it, it just has to provide an higher version !

**Comment by jtkech** [comment]
@deanmarcussen 

Maybe okay but just saw that for the themes there is no `Assets` folder and just an `Assets.json` with only one input but coming from the theme wwwroot folder. All front end themes have this file but not  `TheComingSoonTheme`.

    {
      "generateSourceMaps": false,
      "inputs": [ "wwwroot/scss/bootstrap-oc.scss" ],
      "output": "wwwroot/css/bootstrap-oc.css"
    }

That said `wwwroot/scss/bootstrap-oc.scss` exists in `TheTheme` but not in other themes.

**Comment by deanmarcussen** [comment]
@hishamco the reason I haven't gone for a variable, is that there is no concept of a variable in liquid. It would have to be a filter or tag (to the best of my knowledge). 
For such a minor issue that seems even more complicated, and I suspect even harder to understand for someone new to OC, rather than just seeing in the layout file the name of something, that they can update - if you look at the changes, it's 4 lines in a layout file. 
Not worth having a liquid tag to do it, or they're going to have to understand how to rewrite a liquid tag as well.

**Comment by deanmarcussen** [comment]
@jtkech as you say, interesting, but too complicated!

Cool to know that the higher version is a good way to affect things though!

I might put a pr in to add a ResourceManifest to `TheAdmin`, it is minor as well, but a useful way to affect the admin css, and js, without major changes to the actual templates. Have been meaning to do that for a while.

Oh, also the scss files are there in each of the different themes (except `TheComingSoon`), they're just not included in the `.csproj` so you have to look for hidden folders.

**Comment by deanmarcussen** [comment]
@agriffard any particular reason `TheComingSoonTheme` never got the `bootstrap-oc` file ?

**Comment by hishamco** [comment]
@deanmarcussen I mean ResourceManifest :)

**Comment by agriffard** [comment]
@deanmarcussen I guess I didn't see a value to have the grid css classes with TheComingSoonTheme.

**Comment by deanmarcussen** [comment]
@jtkech just for infos.

I won't pr `TheAdmin` to have a `ResourceManifest` because after testing what you discovered about resource preference, i.e. highest version wins, it is easy to do this in a custom admin theme (or any other theme variation)

Add a `ResourceManifest` like this and register it in `Startup`
```
manifest
    .DefineStyle("admin")
    .SetUrl("~/ThisNetWorksAdminTheme/Styles/theme.min.css", "~/ThisNetWorksAdminTheme/Styles/theme.css")
    .SetDependencies("jQuery-ui")
    .SetVersion("0.0.1");
```

Give it a version higher than the no version supplied by `TheAdmin` `Layout.cshtml` in the tag helper (i.e. `0.0.1` works)

and it will override the default `admin` css registered by `Layout`

Then in the sass that builds the tweaked admin layout, import the existing `TheAdmin.scss` file, and any custom overrides after the import.

So it's not necessary to have a `ResourceManifest` in `TheAdmin` to achieve this, it also works perfectly against the tag helper registration that already exists.

**Pull request merged**
