### PR TITLE
Handle UnauthorizedResult (#3209)

### LINKED ISSUE #3209: Handle UnauthorizedResult
When trying to access an unauthorized ContentItem in front-end, `ItemController` returns an `UnauthorizedResult`.

Until there, it's correct. However, UnauthorizedResult is treated as any other error and an error message is returned : "An error occured while executing this request." leaving us thinking there is a bug.

What's the expected behavior ? Should we redirect to authentication page (if not already authenticated) or at least return a dedicated message (like "You are not authorized to view this content.")

### PR DESCRIPTION
**Pull request by TFleury**
Fixes #3209
- Add Unauthorized error page.
- In ItemController, return unauthorized requests to login if not authenticated.

### CODE REVIEW

**Comment by sebastienros** [comment]
@PinpointTownes Isn't there a middleware that will convert an `Unauthorized` call to a `Challenge`?

**Comment by PinpointTownes** [comment]
@sebastienros in 1.x, ASP.NET Core used to automatically convert 401 responses to challenges (handled by the authentication stack). This behavior - inherited from OWIN/Katana was inconvenient and in 2.0, we all agreed to remove it, so nope, there's no built-in conversion.

The proper fix here would be to replace `Unauthorized()` by `Forbid()` everywhere we return it after manually performing an authorization check as all the actions that use this pattern also use `[Authorize]` (in this case, unauthenticated requests are automatically rejected and a 401 response is returned by the authentication handler that handled the request).

**Comment by TFleury** [comment]
`Forbid()` redirects all requests (authenticated and unauthenticated) to login.

The proper fix depends on the behavior we expect. Do we want to redirect authenticated users back to login if they are already authenticated ?

**Comment by PinpointTownes** [comment]
When invoked via Forbid(), the cookie authentication handler redirects you to a special "access denied page", that doesn’t have to be the login page.

If you see a different behavior, then we have a bug somewhere.

**Comment by TFleury** [comment]
In our case, `AccessDeniedPath` is set to `LoginPath`.

https://github.com/OrchardCMS/OrchardCore/blob/b625ffad3f0a6ffb4ca4366ae22a276bd4c3b70c/src/OrchardCore.Modules/OrchardCore.Users/Startup.cs#L83-L98

The correct behavior should be to redirect  [403 Forbidden](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403) to an error page like with `Microsoft.AspNetCore.Identity.UI`.

To come back to the case of our `ItemController`, we can't use `[Authorize]` because we handle per content authorization and anonymous access is also acceptable. So we have to return `Challenge()` ourselves.

**Comment by TFleury** [comment]
@PinpointTownes thank you for your help. Could you review my last changes and let me know if it seems correct to you ?

**Comment by sebastienros** [comment]
After some time looking into it it seems that we have no choice but to do the check in the controller and return a Forbid/Challenge result based on the authentication status.

So this fix looks good to me.

@PinpointTownes can you confirm and I will merge it

**Comment by PinpointTownes** [comment]
Is there a particular reason why the content controller doesn't use `[Authorize]`? If it did, we could remove the helper and directly do `return Forbid()` from the action code (as the unauthenticated case would be covered by the attribute).

**Comment by sebastienros** [comment]
[Autorize] will always challenge if we are not anonymous, or should it work with also [AllowAnonymous]

Are you suggesting:
`[Authorize, Allowanonymous]` then return `Forbid()` ?

**Comment by PinpointTownes** [comment]
> [Autorize] will always challenge if we are not anonymous, or should it work with also [AllowAnonymous]

AFAICT, these actions are not supposed to be invoked by unauthenticated callers. Did I miss something?

**Comment by sebastienros** [comment]
They are called by anonymous users, it's to display a content item, like a blog post.

**Comment by PinpointTownes** [comment]
Then what's the point of performing an authorization check for authenticated users if not being authenticated bypasses the check? There's surely something I'm missing.

**Comment by sebastienros** [comment]
The action code is always executed because we need to load the resource to know if the current request has access to it. There is an option to "Allow anonymous" users to see this resource, so we need to run the code even for anonymous.

**Comment by PinpointTownes** [comment]
How does that work, concretely?

AFAICT, it will only work if the Roles module is enabled, because otherwise,
`Display` calls `_authorizationService.AuthorizeAsync(User, Permissions.ViewContent, contentItem)`, that will end up invoking `PermissionHandler`, that won't accept unauthenticated demands (due to the first `if`).

If Roles is enabled, the code logic will be different as it comes with a special `RolesPermissionsHandler`. Is it intended that the behavior will differ whether the Roles module is enabled or not?

**Comment by PinpointTownes** [comment]
The logic we have in this PR is fine, but I suspect there are other places where we blindly return `Challenge` instead of `Forbid`. You may want to do a global search to find and fix them too.

**Comment by sebastienros** [comment]
It's fine that without the roles module non-authenticated won't work, unless there is another handler that overrides that.

**Comment by jonvee** [comment]
Just wondering if this PR good to go? I could use it right now, so I'm happy to do some basic testing if needed.

**Comment by hishamco** [comment]
@PinpointTownes what's the status of this one?

**Comment by PinpointTownes** [comment]
@hishamco ideally, we should also fix all the calls to `Unauthorized()` (by replacing them by either `Challenge` or `Forbid`, depending on the case). That said, it looks like this PR was abandoned, so I guess it will have to be done in another one, by someone else 😄

**Pull request merged**
