### PR TITLE
bootstrap-select 1.14.0-beta3

### PR DESCRIPTION
**Pull request by agriffard**
https://www.npmjs.com/package/bootstrap-select/v/1.14.0-beta3

### CODE REVIEW

**Comment by Skrypt** [comment]
"gulp build" for TheAdmin theme.

**Comment by agriffard** [comment]
I did a `gulp rebuild`.
It is not in TheAdmin theme.

**Comment by agriffard** [comment]
[TheAdmin/package.json](https://github.com/OrchardCMS/OrchardCore/blob/5225c637e43abc27abe8a5eae425d31a02c84af0/src/OrchardCore.Themes/TheAdmin/package.json#L7) already has the correct version.

**Review by Skrypt — APPROVED** [review]

**Comment by Skrypt** [comment]
This update is causing a lot of issues when trying to refresh the components dynamically.
See https://github.com/snapappointments/bootstrap-select/issues/2724
We should consider reverting to beta2 in the meantime.

**Comment by Skrypt** [comment]
Also, the ResourceManager version has not been updated and the CDNs for the script has been commented out.

**Pull request merged**
