### PR TITLE
Add referer property on Liquid Request object

### LINKED ISSUE #8808: In workflows redirect task need  to redirect to the referer url
I am triggering a workflow (using a post incoming request event) from a page and when it completes 
I wish to return to the page it was originally called using the redirect task. 
So there should be a liquid helper on the Request object to return the referer inside the redirect task as : {{Request.Referer}}

### PR DESCRIPTION
**Pull request by giannik**
fixes #8808

### CODE REVIEW

**Comment by giannik** [comment]
I am having some issues using this new property from redirect task becuase of the urlencoder thats used in redirecttask.
It only works if i pass in null  as the encoder  when calling : 
```
  var location = await _expressionEvaluator.EvaluateAsync(Location, workflowContext, _urlEncoder);
```
 
On the other hand if i use in liquid event handler the following  : 

```
case "Referer": return  new  HtmlContentValue(new HtmlString(request.GetTypedHeaders().Referer.PathAndQuery)) ;
``` 

I get the exception : 

```
 System.InvalidCastException: Unable to cast object of type 'System.Text.Encodings.Web.DefaultUrlEncoder' to type 'System.Text.Encodings.Web.HtmlEncoder'.
```
so i am wondering where the fix should be ?


@sebastienros

**Comment by sebastienros** [comment]
The PR needs to be updated since we merged the Fluid2 branch

**Comment by sebastienros** [comment]
Better create a new PR. Question though, can't it already be accessed using the `Headers` property that is declared a few lines above? If that's the case there we shouldn't add it, otherwise it's opening the door to adding every single known ones.

**Comment by giannik** [comment]
Hey , I just tried with the new fluid 2.0 branch and this works :  {{Request.Headers.Referer}}
So I'll close this branch.

**Pull request closed without merging**
