### PR TITLE
Add version & target framework variables in .props

### PR DESCRIPTION
**Pull request by hishamco**
This will simplify the process when we need to update AspNetCore version

### CODE REVIEW

**Comment by hishamco** [comment]
@jtkech any idea why this failed?!!

**Comment by jtkech** [comment]
I will check it tomorrow.

Meanwhile, all projects under the `OrchardCore.ProjectTemplates\content` folder are not built with our solution. There are delivered contents when people install our custom dotnet templates. So, because people will not have the `Dependencies.AspNetCore.props` file, people won't be able to build a given template. So we can't use e.g `AspNetCoreTargetFramework` for these delivered project files.

**Comment by hishamco** [comment]
> There are delivered contents when people install our custom dotnet templates. So, because people will not have the Dependencies.AspNetCore.props file, people won't be able to build a given template.

You're right

**Comment by hishamco** [comment]
Thanks a lot, at least we reduce the number of the changes that we need everything

@agriffard if this looks fine you can merge and rebase your ASP.NET Core 3.1 updates pr

**Pull request merged**
