### PR TITLE
Wrapping lines in CodeMirror to avoid cutoff

### LINKED ISSUE #9165: TitlePart pattern is cutoff when using a long pattern
See the screenshot

image

### PR DESCRIPTION
**Pull request by hishamco**
Fixes #9165

### CODE REVIEW

**Comment by Skrypt** [comment]
Seems like this would fix it only in one place "TitlePart".

**Comment by hishamco** [comment]
Yep, but what I notice that the horizontal scroll will not appear anymore ;)

**Comment by Skrypt** [comment]
Feels like an issue that should be fixed on the editor itself unless this issue happens only in OC.

**Comment by Skrypt** [comment]
I'll take a look, but sometimes it's like looking for a needle in a hay stack.

**Comment by jptissot** [comment]
I think this should be closed @hishamco

**Comment by hishamco** [comment]
Please wait for @Skrypt I'm not sure if he did something on this or we may continue on this PR

**Comment by jptissot** [comment]
Not needed as we will change most code editors to Monaco.

**Pull request closed without merging**
