### PR TITLE
fix double click issue on workflow activity and content items

### LINKED ISSUE #4227: Workflow Activity Double click issue
I accidentally double clicked the add button when adding an activity to the workflow and it added the activity twice with the same ID, causing the UI to throw an exception, even after reloading the site. I had to go into the database document and remove the duplicate entry for the UI to unblock. Maybe we should disable the button on click.

### PR DESCRIPTION
**Pull request by tropcicstefan**
Fix 
#4227 
and partially #8900

### CODE REVIEW

**Comment by deanmarcussen** [comment]
I like it. 
I think it would need to be on the Edit Views as well (and later on most forms)

**Comment by jptissot** [comment]
We could also put the button in the [disabled state ](https://getbootstrap.com/docs/4.0/components/buttons/#disabled-state) by adding the `disabled` attribute. 
Another addition could be to add a [spinner ](https://getbootstrap.com/docs/4.3/components/spinners/#buttons) to the button while it's in the disabled state.

**Comment by tropcicstefan** [comment]
> We could also put the button in the [disabled state ](https://getbootstrap.com/docs/4.0/components/buttons/#disabled-state) by adding the `disabled` attribute.

controller won't get button value if button is disabled [link](https://stackoverflow.com/questions/7357256/disabled-form-inputs-do-not-appear-in-the-request/7357314#7357314)
> Another addition could be to add a [spinner ](https://getbootstrap.com/docs/4.3/components/spinners/#buttons) to the button while it's in the disabled state.

I am not sure how to catch which button actually submitted when multiple:
-maybe by document.activeElement
-maybe like [this](https://stackoverflow.com/questions/2066162/how-can-i-get-the-button-that-caused-the-submit-from-the-form-submit-event/61110260#61110260) eventually



> I like it.
> I think it would need to be on the Edit Views as well (and later on most forms)

Sure. will add to Create views at least.

**Comment by sebastienros** [comment]
Disable is fine, no need for a spinner, more issues than anything.

**Comment by sebastienros** [comment]
Needs to be added to Edit.cshtml too.
And probably "automatically" on the links that have the custom attribute that make them form posts.

**Comment by deanmarcussen** [comment]
Replaced by https://github.com/OrchardCMS/OrchardCore/pull/9716/files

Thank you @tropcicstefan it got done on all the other views as well.

**Pull request closed without merging**
