### PR TITLE
Initial azure setup

### PR DESCRIPTION
**Pull request by sloethen**

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/OrchardCMS/OrchardCore?pullRequest=8663) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/OrchardCMS/OrchardCore?pullRequest=8663) before we can accept your contribution.<br/><br/>:x: sloethen [sign now](https://cla.dotnetfoundation.org/OrchardCMS/OrchardCore?pullRequest=8663)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/OrchardCMS/OrchardCore?pullRequest=8663) it.</sub>

**Comment by Skrypt** [comment]
@sloethen Please PM me on Gitter.

**Comment by sloethen** [comment]
Need to kill that.  It was supposed to be against my fork, not the main repo.

Sent via the Samsung Galaxy S9+, an AT&T 5G Evolution capable smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jtkech** [comment]
Okay so i close it

**Comment by Skrypt** [comment]
I'm not sure but maybe you should delete also the branch on your side to avoid exposing these settings.

**Pull request closed without merging**
