### PR TITLE
appsettings.json configuration is not taken into account

### LINKED ISSUE #15310: configuration stored in appsettings.json is not taken into account
I've noticed that configuration stored in **appsettings.json** is not binded in many places:
- SmtpSettings,
- FacebookSettings,
- GitHubAuthenticationSettings,
- GoogleAuthenticationSettings,
- MicrosoftAccountSettings,
- AzureADSettings,
- ReverseProxySettings,
- TwitterSettings.

It looks like somebody created some extensions methods, but they were not used, other than that they were wrong in my opinion.

Steps to reproduces:
- go to **appsettings.json**,
- uncomment a few lines, and provide some values, even fake one:
```
    "OrchardCore_Facebook": {
      "AppId": "1111111",
      "AppSecret": "2222222",
      "FBInit": false,
      "FBInitParams": "status:true,xfbml:true,autoLogAppEvents:true",
      "SdkJs": "sdk.js",
      "Version": "v3.2"
    },
    "OrchardCore_GitHub": {
      "ClientID": "33333333",
      "ClientSecret": "4444444",
      "CallbackPath": "/signin-github",
      "SaveTokens": false
    },
    "OrchardCore_Google": {
      "ClientID": "555555555",
      "ClientSecret": "666666666",
      "CallbackPath": "/signin-google",
      "SaveTokens": false
    },
    "OrchardCore_Twitter": {
      "ConsumerKey": "777777",
      "ConsumerSecret": "8888888",
      "AccessToken": "9999999999",
      "AccessTokenSecret": "0000000000000"
    },
    "OrchardCore_Microsoft_Authentication_MicrosoftAccount": {
      "AppId": "111111111",
      "AppSecret": "222222222",
      "CallbackPath": "/signin-microsoft",
      "SaveTokens": false
    },
    "OrchardCore_Microsoft_Authentication_AzureAD": {
      "DisplayName": "33333333",
      "AppId": "4444444",
      "TenantId": "55555555555",
      "CallbackPath": "/signin-oidc",
      "SaveTokens": false
    }
```
- make sure you don't have any configuration saved to the database, you can check this with this sql query: `select Content from document where Type = 'OrchardCore.Settings.SiteSettings, OrchardCore.Settings'`,
- run the app and observe the issue.

### PR DESCRIPTION
**Pull request by lampersky**
fixes #15310 
and maybe https://github.com/OrchardCMS/OrchardCore/issues/14050 (it would be good to check @Piedone)

For now I've marked a few methods as obsolete, but IMO they can by removed, because they are useless.

/cc: @sebastienros

### CODE REVIEW

**Comment by lampersky** [comment]
please put the review on hold until the errors are fixed

**Comment by ns8482e** [comment]
OC allows some settings to be modified by Admin UI, it's by-design default behavior. 

To use some of the configuration from appsettings.json  you need to explicitly opt-in by calling the respective extension method on your `Program.cs`

**Comment by hishamco** [comment]
@lampersky when these configurations have been broken I remember they were working as expected, @Piedone correct me if I'm wrong. Unless something updated since then

**Comment by lampersky** [comment]
@hishamco I already answered in the main issue, but here is the copy, so you don't need to jump back and forth:

> I have to admit something to you guys, I've never ventured into that part of the documentation :-P
> 
> I mistakenly assumed that it should work like for other configurable modules: **OrchardCore_Apis_GraphQL**, **OrchardCore_Media_Azure** and many others. The configuration from the appsettings.json file is taken into account automatically, you do not need to activate it additionally by calling any dedicated extension methods.
> 
> So, thank you @ns8482e, @Piedone and sorry for getting you involved unnecessarily. Maybe I was too quick into preparing the fix.
> If you guys will decide to reject the PR, let me know and I will extract this part which solves #14050 into another PR.

**Comment by Piedone** [comment]
Let's keep the "why" under the issue (https://github.com/OrchardCMS/OrchardCore/issues/15310) please, so we can focus on the "how" here.

**Comment by Piedone** [comment]
Closing this since the linked https://github.com/OrchardCMS/OrchardCore/issues/15310 issue is closed now too.

**Pull request closed without merging**
