### PR TITLE
Fix various issues with the hybrid flow

### PR DESCRIPTION
**Pull request by kevinchalet**
Fixes https://github.com/OrchardCMS/OrchardCore/issues/11717.

### CODE REVIEW

**Comment by kevinchalet** [comment]
@MichaelPetrinolis when you have a moment, could you please give it a try? 😃

**Comment by MichaelPetrinolis** [comment]
@kevinchalet tested the scenarios I used and works as expected, thanx! 
I also verified that when we change the response type to codetoken or codeidtokentoken for a client on a confidential app, the idp does not allow it. I will open a a bug for the OpenId client, because when we change the application from confidential to public(to check the other two response types), we cannot clear the client secret in the client configuration and the idp rejects the request because client_secret is not expected.

**Comment by sebastienros** [comment]
Now it's conflicting ...

**Comment by kevinchalet** [comment]
> Now it's conflicting ...

That's what happens when you merge PRs in the wrong order... :trollface: 

I'll rebase it and update @MichaelPetrinolis' new extension to use the same fix.

**Review by sebastienros — APPROVED** [review]

**Pull request merged**
