### PR TITLE
Fixes previewing when using the trumbowyg editor.

### LINKED ISSUE #1889: Preview when using trumbowyg editor is out of sync
When I edit content in the trumbowyg editor and click preview, the preview window is missing the last character.

Tested on Orchard Core v1.0.0-beta2-5965

Steps to replicate issue:
- From the admin area click 'New' then 'Page'
- Give page a title
- add a paragraph widget 
- type abc in to the editor
- click 'Preview'

When the preview page loads the character c is missing

I can go back and edit but the last character edit is always missing on preview.

### PR DESCRIPTION
**Pull request by jtkech**
Fixes #1889

### CODE REVIEW

**Comment by sebastienros** [comment]
Please merge dev, @matiasmolleja already fixed it, but your change moves it to the correct module. So please remove his code if that still works after that.

**Comment by jtkech** [comment]
Okay, and on my side i forgot to remove the unecessary code in `contentpreview.edit.js`, i wiil check it.

**Comment by matiasmolleja** [comment]
@sebastienros This is the kind of thing that would not occur if I were added to the OrcharCMS team, just saying :grin:
I would like a lot to have that bag on my Github profile. :pray:

**Comment by jtkech** [comment]
I'm voting for 🤞

**Comment by agriffard** [comment]
OK @matiasmolleja , you have been added to the OrchardCore Devs team.
You must have received a pending member request to which you just need to answer.

**Comment by matiasmolleja** [comment]
Thank you so much!
Iit's an honor for me to be part of this awesome team. :smiley:

**Pull request merged**
