### PR TITLE
Add modal that displays the json format of a content item

### LINKED ISSUE #9205: Workflow task [Create Content]
### Is your feature request related to a problem? Please describe.
when declaring a task to create content
it is necessary to get the dryness of the content from the table,
is it possible to make it autocomplete?

### Describe the solution you'd like
I selected the content type and the content properties were filled with json of the given entity

### PR DESCRIPTION
**Pull request by jptissot**
fix #9205

Is blocked by #9414

### CODE REVIEW

**Comment by jptissot** [comment]
Looks like this for now. I will try to fix the underlying issue that does not properly initialize field values when using the contentManager https://github.com/OrchardCMS/OrchardCore/issues/9103

image

**Comment by Piedone** [comment]
Our Lombiq JSON Editor module has a [JSON Content Editor](https://github.com/Lombiq/Orchard-JSON-Editor?tab=readme-ov-file#json-content-editor) that does something similar. Does that address this need, shall we close @jptissot, or would you like to revisit this? @timeshift92, as the author of the original issue, would you please check?

**Comment by timeshift92** [comment]
thank you that's what I need

**Comment by Piedone** [comment]
@jptissot please reopen if you'd like to get back to this in the near future.

**Pull request closed without merging**
