### PR TITLE
Adding Bootstrap back to The Blog Theme Layout

### LINKED ISSUE #2618: The Blog Theme Layout Missing Bootstrap Script Tag
Layout Template in The Blog Theme is missing a script tag for Bootstrap. It was removed as part of 2c27f9c but this was probably accidental.

### PR DESCRIPTION
**Pull request by davidhayden**
Fixes #2618

### CODE REVIEW

**Comment by Skrypt** [comment]
Unescessary. The Bootstrap SASS files are compiled as part of the gulp pipeline as far as I remember. Now you will serve these assets twice.

**Comment by sebastienros** [comment]
I checked but couldn't find it

**Comment by Skrypt** [comment]
https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Themes/TheBlogTheme/wwwroot/scss/clean-blog-orchard.scss

**Comment by sebastienros** [comment]
I ensured bootstrap is correctly included in the main js file, then reverted the change

**Comment by davidhayden** [comment]
@Skrypt @sebastienros Can you guys help me understand this?  If I clone the repository, run OrchardCore.CMS.Web, create a tenant using the Blog Theme Setup, and add a Bootstrap component, such as a carousel for example, it doesn't work unless the Bootstrap script is in the Layout.

**Comment by Skrypt** [comment]
Yes you need to add these lines in the bottom of your Layout view.

```
    <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
```

**Comment by davidhayden** [comment]
@Skrypt Okay, but I'm not sure why I have to do this manually now. The Blog Theme is a *Start Bootstrap* Theme, and I would expect Bootstrap to be included automatically with the theme.

And, if later, I add a component that requires Bootstrap and uses the Bootstrap script tag in a view to make sure the dependency is loaded, does this mean Bootstrap will get added twice, once in my layout using the tags you mention above, and another time using the script tag?

**Comment by sebastienros** [comment]
@Skrypt is there a way we would not have to embed BS in the js file?

**Comment by Skrypt** [comment]
Let's not be confused between SASS and JS assets. The SASS file is part of the compiled clean-blog-orchard.css and clean-blog-orchard.min.css file. So, we embed BS as part of our theme CSS. It could be done differently if we would just build mixins(modules) that extend Bootstrap directly. 

For the JS assets ; the bootstrap JS is not embedded in the clean-blog.js file. So, we just forgot to add the bootstrap.bundle.js file to the Layout template since it adds only Bootstrap components functionnalities. I agree that we should add it by default since these themes are used as pre-compiled most of the time.

**Pull request merged**
