### PR TITLE
Update admin routes - batch 1

### LINKED ISSUE #2779: Some admin panel sections escape from the /Admin/ url
Related to : 
https://github.com/OrchardCMS/Orchard/issues/5905

Example : 
https://localhost:44300/OrchardCore.Features/Admin/Features
should be at least : 
https://localhost:44300/admin/OrchardCore.Features/Admin/Features

### PR DESCRIPTION
**Pull request by hishamco**
Fixes #2779

- AdminMenu
- Contents
- ContentTypes
- Deployment
- Deployment.Remote
- Features
- Layers
- Lucene
- Queries
- Recipes
- Roles
- Templates
- Themes
- Users

### CODE REVIEW

**Comment by Skrypt** [comment]
@hishamco I won't have time to test it but the changes seems fine. We just need to make sure it doesn't break any other feature that could call routes by name for example.

**Comment by hishamco** [comment]
Ok, we may need to test them after I finish the entire list

> We just need to make sure it doesn't break any other feature that could call routes by name for example

Is there an example we module call route by name?

**Comment by Skrypt** [comment]
Admin Menu feature maybe. Not sure.

**Comment by hishamco** [comment]
Ok, thanks ..

**Comment by agriffard** [comment]
@hishamco Can you please update it to use the new .Net Core 3.0 `MapAreaControllerRoute` syntax?

**Comment by hishamco** [comment]
Sure, but I think this need to revise coz I don't wanna break any link :)

**Pull request closed without merging**
