### PR TITLE
Remove unnecessary fields from content picker view model

### PR DESCRIPTION
**Pull request by jameshawkins**
This is to stop eagerly loading content items in the content picker display driver. Instead the content items can be lazily loaded in a template.

Fixes https://github.com/OrchardCMS/OrchardCore/issues/3267

### CODE REVIEW

**Comment by sebastienros** [comment]
I added the `ContentItemIds` property on the view model. The same way it's done on other fields.

**Comment by jameshawkins** [comment]
Looks good, I like it better. Looks like the other field view models aren’t very consistent though. Maybe we should update them all like this?

**Comment by sebastienros** [comment]
Sure, I thought I had done that all of them. Fell free to fix them.

**Comment by sebastienros** [comment]
O, so it seems I have been consistent in not doing that :/ But it would make it easier, I agree. BodyPart and MarkdownPart have it.

**Comment by sebastienros** [comment]
Probably better to implement it in the view model, like `Text => Field.Text`

**Comment by jameshawkins** [comment]
Yeah sounds good to me... want a new PR or just update this one?

**Comment by sebastienros** [comment]
update this one

**Pull request merged**
