### PR TITLE
Add missing Sender SMTP field

### LINKED ISSUE #5239: Missing Smtp fields
Based on the specs, we should be able to set a From and Sender fields. Today we only ask for From and actually copy it to the Sender.

```
 A.2.  ORIGINATOR ITEMS

     A.2.1.  Author-sent

             George Jones logs into his host  as  "Jones".   He  sends
        mail himself.

            From:  Jones@Group.Org

        or

            From:  George Jones <Jones@Group.Org>

     A.2.2.  Secretary-sent

             George Jones logs in as Jones on his  host.   His  secre-
        tary,  who logs in as Secy sends mail for him.  Replies to the
        mail should go to George.

            From:    George Jones <Jones@Group>
            Sender:  Secy@Other-Group

     A.2.3.  Secretary-sent, for user of shared directory

             George Jones' secretary sends mail  for  George.  Replies
        should go to George.

            From:     George Jones<Shared@Group.Org>
            Sender:   Secy@Other-Group

        Note that there need not be a space between  "Jones"  and  the
        "<",  but  adding a space enhances readability (as is the case
        in other examples.

     A.2.4.  Committee activity, with one author

             George is a member of a committee.  He wishes to have any
        replies to his message go to all committee members.

            From:     George Jones <Jones@Host.Net>
            Sender:   Jones@Host
            Reply-To: The Committee: Jones@Host.Net,
                                     Smith@Other.Org,
                                     Doe@Somewhere-Else;
```

Also our current parsing seeks a space before `<`, though it's not mandatory to have one

### PR DESCRIPTION
**Pull request by hishamco**
Fixes #5239

### CODE REVIEW

**Comment by Skrypt** [comment]
@hishamco merged latest dev please fix the PR if there's anything.

**Comment by hishamco** [comment]
Sure, that's what I'm doing, there's a little tiny bug I need to fix before rebase on the dev, please hold on I'm facing an Internet issue ;)

**Comment by hishamco** [comment]
@Skrypt it's ready

**Comment by sebastienros** [comment]
Can you update MimeKit as part of this PR ?
Even better if you can use MimeKitLite instead, I don't think we need MimeKit, and it will make less dependencies.

**Comment by sebastienros** [comment]
I updated the version of the package, and we can't use MimeKitLite as I hoped because we actually need MailKit.
I think that also fixed #5591

**Pull request merged**
