### PR TITLE
Move OrchardCore.Translations.All

### LINKED ISSUE #17035: OrchardCore.Translations.All is not referenced by OrchardCore.Application.Cms.Core.Targets
If someone wants to use a module it should be properly translated at all time.
I suggest we move the reference to OrchardCore.Application.Cms.Core instead.

Unless what we expected was translations would not be supported when using OrchardCore.Application.Cms.Core.Targets on a web project instead of the latter.

The goal for us is to not load all the themes that comes with Orchard while still being able to use DataAnnotations translations.

### PR DESCRIPTION
**Pull request by Skrypt**
To OrchardCore.Application.Cms.Core.Targets

Fixes #17035

### CODE REVIEW

**Review by Piedone — APPROVED** [review]
This looks like a good change to me but @hishamco please comment.

**Comment by sebastienros** [comment]
Should we split Translation.All in two such that Core can reference core module translations, and .All include Cms modules too?

**Comment by Skrypt** [comment]
@sebastienros That would be even better.

**Comment by hishamco** [comment]
I think the main issue here is that we include all the translations even if we didn't use them, what if we include them on demand? 

I saw some CMS load the translations on the fly, but while we don't have this capability we could install them using dotnet CLI

**Comment by sebastienros** [comment]
@Skrypt I could check ... but as I understand it the "All" is for "all languages", not "all modules" ? If so then the change is fine.

**Comment by Skrypt** [comment]
@sebastienros It is both all languages and all modules. We don't make a distinction yet between Core and Modules. I think that's maybe the enhancement we could have. This way we could just use Core translations when we want to use OC as a framework so that we can get the DataAnnotation translations as an example.

**Review by sebastienros — APPROVED** [review]

**Comment by MikeAlhayek** [comment]
@Skrypt this PR caused an issue. If you try to use using version `3.0.0-preview-18449` or newer, you'll get this error 

> error NU1100: Unable to resolve 'OrchardCore.Translations.All (>= 2.1.0)' for 'net9.0'.

I tried many ways to fix it but nothing seems to be working. The latest stable version in `3.0.0-preview-18448`. Can you please see why it is not working and fix it? Otherwise, we may have to revert this PR meanwhile.

**Comment by Skrypt** [comment]
Yes, the localization folder generated in the Web project should now be expected. That's a result of the change as we always want to have these localizations. We expect that Orchard Core should be localizable if we ship the Localization module as part of the solution.

Now, the issue here seems to be related with resolving OrchardCore.Translations.All. I will take a look but I'm surprised of the issue.

**Comment by MikeAlhayek** [comment]
@Skrypt I would not expect an issue here. But try using the previews. we may have to revert this meanwhile.

**Comment by MikeAlhayek** [comment]
This is the last package that was released before it was reverted just in case you want to test it out `3.0.0-preview-18467`

https://cloudsmith.io/~orchardcore/repos/preview/packages/detail/nuget/OrchardCore.Application.Cms.Targets/3.0.0-preview-18467/

**Pull request merged**
