### PR TITLE
Repair bug that is JsEngine about JObejct.Value

### PR DESCRIPTION
**Pull request by zl2fxy**
Repair bug that is JsEngine about JObejct.Value

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/OrchardCMS/OrchardCore?pullRequest=10617) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/OrchardCMS/OrchardCore?pullRequest=10617) before we can accept your contribution.<br/><br/>:x: zl2fxy [sign now](https://cla.dotnetfoundation.org/OrchardCMS/OrchardCore?pullRequest=10617)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/OrchardCMS/OrchardCore?pullRequest=10617) it.</sub>

**Comment by zl2fxy** [comment]
#10533 
#5208

**Comment by sebastienros** [comment]
This bug was fixed in both Fluid and Jint now. When these libraries are updated here this should be fixed.

**Comment by sebastienros** [comment]
Can you check now that FLuid has been updated?

**Comment by Piedone** [comment]
Closing due to lack of response form the PR author.

**Pull request closed without merging**
