### PR TITLE
Allow sending email with the display name

### LINKED ISSUE #4268: MimeKit error sending email with address containing full name
There is a MimeKit error when the default sender address is set to something like this:
`Your Name <youraddress@host.com>`

Previously, it was working when we were using System.Net to send the emails.

### PR DESCRIPTION
**Pull request by hishamco**
Fix #4268

### CODE REVIEW

**Comment by hishamco** [comment]
:shipit:

**Comment by hishamco** [comment]
:shipit:

**Comment by hishamco** [comment]
@sebastienros this one too

**Comment by sebastienros** [comment]
Are you sure there is nothing in the library to handle this case?

**Comment by hishamco** [comment]
I think if we wrap the `MimeMessage` with the `System.Net.Mail.Message`, but I think the current solution is fine to handle the case

**Pull request merged**
