### PR TITLE
fontawesome 6.4.0

### PR DESCRIPTION
**Pull request by agriffard**
https://www.npmjs.com/package/@fortawesome/fontawesome-free/v/6.4.0
https://github.com/FortAwesome/Font-Awesome/releases/tag/6.4.0

### CODE REVIEW

**Comment by agriffard** [comment]
https://fontawesome.com/docs/web/setup/upgrade/whats-changed#full-style-names

**Comment by agriffard** [comment]
> We need to also update the styles as I mentioned in the previous pull request.

Done.

The `Configuration` admin menu does not have the `fa-gear` icon as expected though.

**Comment by agriffard** [comment]
The `Regular` style is only available with Pro License @MikeAlhayek.

**Comment by MikeAlhayek** [comment]
@agriffard interesting. It worked locally when I changed it. can we use `fa-light fa-bell`?

**Comment by MikeAlhayek** [comment]
@agriffard I think that icon is free.

image

**Comment by agriffard** [comment]
Yes, it seems to be indicated thta it is available without the pro license:
https://fontawesome.com/icons/bell?s=regular&f=classic

**Comment by MikeAlhayek** [comment]
@agriffard I tested out this branch and everything seems to be working as expected. Are you aware of any issues or todo items here?

**Comment by MikeAlhayek** [comment]
@agriffard should we merge this branch?

**Pull request merged**
