### PR TITLE
Remove form tag from ComingSoon content template

### LINKED ISSUE #6305: Coming soon: Form issue
The form is generated two times causing this problem:

image

### PR DESCRIPTION
**Pull request by ns8482e**
Fixes #6305

### CODE REVIEW

**Comment by agriffard** [comment]
This does not solve the display problem.
The form needs to be in the `<div class="masthead-content ...` as it was before.

**Comment by ns8482e** [comment]
@agriffard - Fixed using 100% form height.  

Also added style for validation-errors

comingsoon

**Comment by agriffard** [comment]
Ok, thank you.

The workflow is not redirected to the succes page though.
There is an error: `Value cannot be null. (Parameter 'value')`

@sfmskywalker or @MichaelPetrinolis Can you please have a look?

**Comment by sebastienros** [comment]
Can we have the styles in the css file? There is one file already that can be used (bootstrap-oc)

**Comment by ns8482e** [comment]
I added style to ComingSoon as specific style for form is required on this content type Only.

Adding style to css file will make theme not usable by other content types

**Comment by sebastienros** [comment]
I am sure we can find a way in css to apply this style only to the form on this page, or move the form in this template if it shouldn't be used for all types.

**Comment by sebastienros** [comment]
@ns8482e thank you, dean fixed it on a different PR, now the wrapper has a custom css

**Comment by ns8482e** [comment]
Thank you  @deanmarcussen @sebastienros

**Pull request closed without merging**
