### PR TITLE
Fire the login failed event only once when a known user login fails.

### LINKED ISSUE #16551: Login Failed event fires twice if you attempt to sign in using invalid password for an existing user
### Describe the bug

If you enable the user audit trail events and then attempt to sign in but type the wrong password you'll notice that three events are recorded:

1. A user updated event (the AccessFailedCount was incremented)
2. A login failed event that includes the user ID
3. A duplicate login failed event that does not include the user ID

Within the AccountController.Login method you can see that the LoggingInFailedAsync handler fires twice if the user is found (or just once if the user was not found).

### Orchard Core version

1.8.3

### To Reproduce

See above. 

### Expected behavior

The LoggingInFailedAsync  handler should fire once and the audit trail event should be recorded once (with the user ID included).

### PR DESCRIPTION
**Pull request by mvarblow**
Fixes #16551

### CODE REVIEW

**Review by MikeAlhayek — APPROVED** [review]

**Comment by Piedone** [comment]
Any reason you didn't merge @MikeAlhayek?

**Comment by MikeAlhayek** [comment]
Because of comments like https://github.com/OrchardCMS/OrchardCore/pull/16533#pullrequestreview-2226013055 . Giving others chance to look at it.

**Comment by Piedone** [comment]
That was for a _larger PR_ with _multiple reviewers requested_.

**Comment by MikeAlhayek** [comment]
Let's merge #16539 first, as it will cause a conflict with this PR. I'll then resolve the conflict and test the necessary commands to handle PR conflicts resulting from the namespace change.

**Review by gvkries — APPROVED** [review]

**Comment by Piedone** [comment]
Alright!

**Comment by MikeAlhayek** [comment]
@mvarblow can you please re-sync your main branch with OC? You should be able to do that by going to https://github.com/mvarblow/OrchardCore and click Sync form

image

**Comment by mvarblow** [comment]
@MikeAlhayek it looks like you already forced the resync. I resolved the merge conflicts.

**Pull request merged**
