### PR TITLE
 Prevent VS from adding some None Remove

### LINKED ISSUE #1384: Prevent VS from adding some None Remove ItemGroup
I opened this issue just as a reminder.

We already fixed the same kind of issue before the embedded branch but now e.g when copy / pasting a file, VS adds a `None Remove="..." />`. Here this is not a problem but maybe better to prevent it, let me know.

I already found a solution by adding some lines directly in a given module `csproj`. But if i add the same lines in `OrchardCore.Module.Targets.props`, **technically this is the same but VS doesn't take it into account**.

**Update**: Maybe first there are some little VS issues we could wait on. E.g, even we explicitly do some none remove, VS still does its own none remove.

### PR DESCRIPTION
**Pull request by jtkech**
Fixes #1384 

So, the solution is to define the `None` items explicitly through our `.props` file, but first it was not working for razor files, we needed to add some `None` remove in the `csproj` file directly.

 There are some subtle differences between `.props` and `.targets` files, e.g in `props` files properties are evaluated before items, in `.targets` files there are evaluated in the order they are defined ... Anyway, items defined in our `.props` file should always be evaluated before the ones in the `csproj` file.

This is the case when building and also for VS when copy / pasting some files, but not if it is a razor file, so maybe a little bug here. But **fortunately it works** if we do some `None` updates in a new `.targets` file in place of doing it in our existing `.props` file.

### CODE REVIEW

**Comment by sebastienros** [comment]
Please merge it yourself when it's ready, as I know you will keep adding commits.

**Comment by jtkech** [comment]
Okay, no problem, just want to retry it after resolving the new above conflict.
First, just need to finish and push some changes i'm doing on another branch.

**Comment by jtkech** [comment]
@sebastienros just solved the conflict related to `OrchardCore.sln`, i will retry it.

In `OrchardCore.sln` there are about [10 new lines here](https://github.com/OrchardCMS/OrchardCore/blob/dev/OrchardCore.sln#L295), is it intended?

**Comment by jtkech** [comment]
So, in our modules, `Compile` items are as in a regular project, we define ourselves `None` items and just to make visible some files as assets used by the gulp pipeline, then normally we don't need any `Content` items because all other items are intended to be `Embedded`.

- So, i think i fixed most of the use cases when copying a file from the same module or another project.

- VS still adds some lines in the `csproj` file if the build action of the file being copied doesn't match the build action corresponding to the destination module folder. E.g a `None` or `Content` item copied to the `Content` folder which normally contains `Embedded` items.

- In this case, through the UI you can update the buid action to the regular one, then VS will automatically remove the extra lines in the `.csproj` file . Otherwise, it's normal that VS keeps these extra lines.

- Just for razor files, to prevent VS from still adding a `None` remove, i needed somewhere to remove all razor files from the `None` items. So there is a specific case when copying a razor file whose build action is `None`, it will not be visible under the module project, so you need to clean up the project file.

- But the above specific case concerns only razor files and whose build action is `None` which is not the default one. The default is `Content` in a regular project, and `Embedded` in our modules.

So, i think it's quite ready, but i will do some other tests tomorrow.

**Comment by jtkech** [comment]
I think it is ready, i will merge it but after the yessql fix to not mix issues.

Meanwhile, it's quite cool to see VS cleaning up itself the project file without re-adding other lines, this when we set through the UI the right build action according to the module folder which contains it.

- So first, if we copy / paste from another project a view which is marked as a `Content` item.

itemgroup1

- Then, because normally a module `Views` folder holds `Embedded` items, VS adds the following.

itemgroup2

- Then, if through the UI we update the build action to `Embedded`.

itemgroup3

- VS cleans the project file and now, because of our `.props / .targets` files, without adding other lines.

itemgroup4

**Pull request merged**
