### PR TITLE
Bootstrap 5.2

### PR DESCRIPTION
**Pull request by agriffard**
https://www.npmjs.com/package/bootstrap/v/5.2.3
https://www.npmjs.com/package/bootstrap-scss/v/5.2.3
https://github.com/twbs/bootstrap/releases/tag/v5.2.3

https://getbootstrap.com/docs/5.2/migration/

- [ ]  Check modals with cards.
- [ ]  Check package.json dependencies in OrchardCore.Workflows.
- [ ]  Replace div with class `dropdown-menu` by ul li everywhere needed.
- [ ]  Replace split buttons with class `dropdown-menu` by ul li where needed.

### CODE REVIEW

**Comment by Skrypt** [comment]
Updating the Workflow module Bootstrap components will break the popovers and modals. The module probably needs a refresh because these javascript components have been changed in BS 5.

**Comment by agriffard** [comment]
The searchable dropdown lists used int the filters of the content items admin page should also be adapted to this 5.2.2 changes.

They rely on [bootstrap-select](https://www.npmjs.com/package/bootstrap-select) and I'm afraid we will have to wait a long time before this BS version is supported.

**Comment by MikeAlhayek** [comment]
@agriffard @Skrypt

Just a thought on this upgrade. I think we can take advantage of the new `text-bg-dark` and `text-bg-dark` to make it easy to change between dark and light theme. Currently we use `bg-primary` class for card to change the background. I think we should `text-bg-light` and `text-bg-dark` instead.

**Comment by MikeAlhayek** [comment]
@Skrypt will this PR fix #11703 ?

**Pull request closed without merging**
