### PR TITLE
Badge "disabled" in PascalCase

### PR DESCRIPTION
**Pull request by monoludic**
Consistency with WorkflowStatus

### CODE REVIEW

**Comment by sebastienros** [comment]
Can you share a screenshot to show the issue, I assume it's to fix a discrepancy but I don't recall it

**Comment by monoludic** [comment]
Here are the screenshots. It's a minor issue, but we noticed the case when using localization.

Worklows (no upper case badges):
workflows

Workflows instances (with upper case badges):
instances

**Comment by sebastienros** [comment]
Is that a custom theme?

Also you might need to update your translation files, I checked and the ones that are not translated are correctly set on Crowdin.

**Comment by monoludic** [comment]
Yes, it is a custom theme.

From my understanding, the terms not translated are not available for translation (e.g. [here](https://github.com/OrchardCMS/OrchardCore/blob/bbc6be8f399370af1772d724732bf4e4b45d5af8/src/OrchardCore.Modules/OrchardCore.Workflows/Views/Workflow/Index.cshtml#L79)).

I will probably open another PR for this.

**Comment by sebastienros** [comment]
This was is not, but I was talking about "5 days ago". For the enums do a switch case with each vue to call T[]

**Pull request merged**
