### PR TITLE
Removed check on protected audience

### PR DESCRIPTION
**Pull request by MatthijsKrempel**
Fix for https://github.com/OrchardCMS/OrchardCore/issues/4287

### CODE REVIEW

**Comment by sebastienros** [comment]
> Since there is no way to configure the audience on the server

Should you just comment this code with a link to the issue. And also file an issue to implement this such that it can be re-enabled once you can configure it on the server?

**Comment by PinpointTownes** [comment]
I'm not sure this check should be removed, as it's there to prevent a tenant using the validation feature from "impersonating" other tenants, that may not belong to the same party/administrator.

Consider this scenario:

  - You have 3 tenants, A, B and C.
  - A and B are managed by Marcel and C is managed by Robert.
  - A has the OpenID server feature enabled and has scopes that grant access to APIs in B and C.
  - B has the OpenID validation server feature enabled and uses A as the token issuer. In this case, B is given the special `oct:B` audience (it can't chose it).
  - With this change, the tenant C - that also has OpenID validation enabled - can replace its own audiences (`oct:C`) by an arbitrary one, representing another tenant: `oct:B` in this case.

Concretely, this allows a tenant to accept and retrieve claims from a token it was not meant to use.

(I'm not saying it's a perfect security measure, but it's better than nothing, specially since we don't have a "standard" Orchard-global way to represent trust relationships across multiple tenants)

**Comment by MatthijsKrempel** [comment]
@PinpointTownes ok, but this does not solve our problem.
We don't have different tennants running an OpenId server, we have a different server running an OpenId server. This check prevents us from using the Validation feature.
And I think your scenario is still covered, since you cant set the audience when selecting a tennant as your OpenId server.

**Comment by PinpointTownes** [comment]
Sold. Looks like we already ignore the audience in `OpenIdValidationConfiguration` that may have been set: https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.OpenId/Configuration/OpenIdValidationConfiguration.cs#L210-L212

But please, let's just remove the code block instead of commenting it as Sébastien suggested :smile:

**Comment by PinpointTownes** [comment]
That said, I'm curious: why does your remote OpenID server issue tokens with an oct: audience if the API tenant is part of another OrchardCore deployment?

**Comment by MatthijsKrempel** [comment]
@PinpointTownes we have a kubernetes cluster running several OrchardCore pods. One pod hosts the OrchardCore OpenId server and several other pods are OrchardCore web applications and some java services. So the OrchardCore OpenId server is setting the audience to oct:default. I guess you should ask the guy who wrote that module why he does that. :P :P :P

**Comment by PinpointTownes** [comment]
> @PinpointTownes we have a kubernetes cluster running several OrchardCore pods. One pod hosts the OrchardCore OpenId server and several other pods are OrchardCore web applications and some java services.

So the pods all share the same database/Orchard configuration or are they separate?

> So the OrchardCore OpenId server is setting the audience to oct:default.

It does that only to allow you to use the token with APIs located in the same tenant, not in an external application. This really makes me think we should have introduced a GUID identifier in the tenant settings, instead of relying on a string that will collide across deployments /cc @sebastienros

Folks who want to use tokens with external APIs are encouraged to create a dedicated scope and assign it all the "resources" names (aka API audiences) they want.

**Comment by PinpointTownes** [comment]
Adding the "dontmerge" label as I'm interested in learning more about your scenario first 😄

**Comment by MatthijsKrempel** [comment]
> Adding the "dontmerge" label as I'm interested in learning more about your scenario first 😄

Holding my PR hostage ey? 😄

**Comment by PinpointTownes** [comment]
> Holding my PR hostage ey? 😄

Definitely :trollface:

**Comment by MatthijsKrempel** [comment]
> So the pods all share the same database/Orchard configuration or are they separate?
All the pods (installations) have seperate databases.

We are not yet implementing Scopes, we are still working on it. We just ran into this limitation of the validation feature. In the future we might also move to multiple OpenId tennants or pods (depending on customer wishes).

Is that enough to set my PR free?

**Comment by PinpointTownes** [comment]
> We just ran into this limitation of the validation feature.

It's a deliberate one, actually. You're not supposed to use the `oct:default` audience as a way to share access tokens across deployments. I guess it would be less confusing if we instead had something like `oct:01828a5e-c205-4de5-b30d-0eeafac89611`.

Can you give the scopes thing a try? I really want to make sure it can't suit your needs, since the change in this PR is likely going to encourage folks to do things they are not supposed to do.

**Comment by MatthijsKrempel** [comment]
> We just ran into this limitation of the validation feature.
> 
> It's a deliberate one, actually. You're not supposed to use the oct:default audience as a way to share access tokens across deployments. I guess it would be less confusing if we instead had something like oct:01828a5e-c205-4de5-b30d-0eeafac89611.
> Can you give the scopes thing a try? I really want to make sure it can't suit your needs, since the change in this PR is likely going to encourage folks to do things they are not supposed to do.

Will have a look! 👍

**Comment by PinpointTownes** [comment]
@MatthijsKrempel did that work for your scenario? 😄

**Comment by MatthijsKrempel** [comment]
> @MatthijsKrempel did that work for your scenario? 😄

We are still looking into it, it's been rather busy :)

**Pull request closed without merging**
