### PR TITLE
Fix DataLoader concurrent issues

### LINKED ISSUE #9651: intermittent error 'Error trying to resolve contentItems' when executing graphQL
It's a super rare issue, but I'm getting error like this occasionally.
I don't know how to reproduce this.
Same GQL query is returning proper data, but once in a time I was able to observe result like this:

image

### PR DESCRIPTION
**Pull request by sebastienros**
Fixes #9651

### CODE REVIEW

**Comment by sebastienros** [comment]
No it won't defer the call, was that the intent?

**Comment by carlwoodhouse** [comment]
How the loader works (or did for this version of graphqldotnet) is to defer
the calls till it has them all so it can make one call at the end of the
request to sql instead of many.

The lockasyncresolver we added is supposed to stop the concurrency issues;
though clearly some issue remains Maybe a resolver isn’t using it ?

**Comment by sebastienros** [comment]
> so it can make one call

where is this logic?

**Comment by carlwoodhouse** [comment]
If I remember right it’s In the graphqldotnet dataloader implementation. If
you look in our graphqlmiddleware you can see we register the listeners for
dataloaders; but it just uses their implementation.

The general idea is that you load the calls into the dataloaders  by key
then the listener executes them all as one for that key to reduce sql
queries and reduce graphqls n+1 issue.

If you profile a query which resolves lists of contentitems as fields on a
type you should see it just runs one query for that dataloader key vs 1
additional query for each result.

Gonna try and pick the graphql update branch/or back up tomorrow which does
handle dataloaders much better.

**Comment by Piedone** [comment]
We don't have this class anymore, nor anything else with `Task.WhenAll()` for GraphQL. Was removed in https://github.com/OrchardCMS/OrchardCore/pull/9087.

**Pull request closed without merging**
