### PR TITLE
Add a way to restart a workflow instance

### LINKED ISSUE #14469: Add a way to restart an instance of workflow
### Is your feature request related to a problem? Please describe.
Sometimes, workflow instance fails for some reason. Or if we have a workflow that sends an email and failed. it would be helpful if we can restart the instance.

### Describe the solution you'd like
Add a button next to the "Delete" button names "Restart" when the instance failed. This will take the current workflow state and restart it.

### PR DESCRIPTION
**Pull request by MikeAlhayek**
Fix #14469

Here is a demo the new "Restart" button in action.

restart-workflow

### CODE REVIEW

**Review by sebastienros — APPROVED** [review]

**Comment by jtkech** [comment]
After a quick look looks like that if the workflow is atomic a lock (potentially distributed) is not use on restarting a workflow, maybe would have been better to do a `TriggerEventAsync()` that uses a lock.

**Comment by MikeAlhayek** [comment]
@jtkech we are placing a lock in the controller https://github.com/OrchardCMS/OrchardCore/pull/14470/files#diff-c064005ef72f8cceaec94e03e0f7a0745bd8e71193df7daa73815e2b564b716dR272 as we do in the [HttpWorkflowController](https://github.com/OrchardCMS/OrchardCore/blob/e228e452311fe16e74eaddcee1376c8b9662df8f/src/OrchardCore.Modules/OrchardCore.Workflows/Http/Controllers/HttpWorkflowController.cs#L18)

**Comment by jtkech** [comment]
Okay cool then

**Comment by jtkech** [comment]
Hmm just a thought, maybe we could have used a background job in case it takes a long time, to redirect more quickly and being able to check the state of the WF in progress.

**Comment by MikeAlhayek** [comment]
@jtkech may not be a bad idea. But this is an Http Request.

**Comment by jtkech** [comment]
Normally not problem, in a controller action you can still fire and forget a background job, I"m using it a lot.

**Comment by MikeAlhayek** [comment]
I guess since we have a status, it should work. we'll just show that the WF is processing meanwhile.

**Comment by jtkech** [comment]
Yes that's the idea but not fully sure, as usual would need to be tried

**Pull request merged**
