### PR TITLE
Integrate pickup directory support into OrchardCore.Email

### PR DESCRIPTION
**Pull request by jeremycook**

### CODE REVIEW

**Comment by jeremycook** [comment]
I integrated support into the existing UI.

image

**Comment by jeremycook** [comment]
Here's what you end up with in the specified folder:

image

And that message:
image

**Comment by sebastienros** [comment]
Shouldn't the drop down drive which options to show up?

**Comment by jeremycook** [comment]
@sebastienros I wasn't sure how to implement that with a drop down the Bootstrap 4 way. So I decided to just get it done this way. If you prefer, I'll work out how the drop down drives visibility.

**Comment by jeremycook** [comment]
@sebastienros here you go. I'm only showing options for the selected delivery method. I also localized a couple strings I had overlooked.

image

**Comment by jeremycook** [comment]
Is the message of a ValidationResult localized automatically or do I need to translate the message before returning a ValidationResult? I'm doing some validation by having SmtpSettings implement `IValidatableObject` and am currently returning raw English message.

**Comment by sebastienros** [comment]
You need to return localized strings, by injecteing `IStringLocalizer<SmtpSettings>` in `SmtpSettings`.

**Comment by sebastienros** [comment]
If you are stuck you can also ask for help and I can gladly add a commit to your branch.

**Comment by jeremycook** [comment]
@sebastienros localized validation messages

**Pull request merged**
