### PR TITLE
Add pathbase.

### PR DESCRIPTION
**Pull request by awyl**
I have created a middleware that internally rewrite a url like this
`/zh-TW/audiobooks` to `/audiobooks` and put `/zh-TW` into `Request.PathBase`.

As far as I clicked around, everything seems fine.  Except, in the admin, the links generated by `AdminMenu` and the content type filter in `Content Items` are missing PathBase.

### CODE REVIEW

**Comment by jtkech** [comment]
**PathBase**

- It may contain a virtual folder and, before the execution of the tenant pipeline (e.g when executing a middleware configured at the app level), it doesn't contains the tenant prefix yet.

      PathBase = /{virtualFolder} - Path = /{tenantPrefix}/somePath

      // If no value => {}, converting the PathString to a string results in an empty string.

- Then, when we are in the tenant pipeline (e.g when executing a middleware configured at the tenant level e.g by a module), the tenant prefix (null for the default tenant) has been moved to the PathBase.

      PathBase = /{virtualFolder}/{tenantPrefix} - Path = /somePath

- In some contexts we don't have to care about this e.g when using the url helper for an action, but here, how we build urls, this is not the case.

- So, here it was not working under a virtual folder, the fix being to use `PathBase` but **without reusing the tenant prefix**.

      _contentItemlistUrl = httpContextAccessor.HttpContext.Request.PathBase + "/Admin/Contents/ContentItems1/";

      var formActionWithoutTypeName = Context.Request.PathBase + "/Admin/Contents/ContentItems";

- Try the above for your use case. Assuming that you created an app level middleware, i think you would have to not set the `PathBase` but just append `/zh-TW` to it (maybe this what you are already doing).

    You could also try it under a new tenant, and it's easy to try it under a virtual folder by just using this.

        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            app.Map("/orchard", builder =>
            {

                if (env.IsDevelopment())
                {
                    builder.UseDeveloperExceptionPage();
                }

                builder.UseStaticFiles();

                builder.UseOrchardCore();
            });
        }



**Formatting**

- Remove unused using directives and sort them, as we configure it under VStudio the related command (ctrl r g) sort them by names, but put all `System.*` at the top.

- Under VS you can format a file by using ctrl k d.

- For github it is better to have a line feed at the end of each file.

**Comment by awyl** [comment]
Thanks.  Clearly explained.  It works for my use case.

I just notice that vscode didn't sort usings...  so I loaded up visual studio to sort it. ;)

**Comment by jtkech** [comment]
To keep only one PR, i did a commit here with the usage of `PathBase` in 2 more places.

**Comment by sebastienros** [comment]
What issue is it fixing? Shouldn't the tenant be part of PathBase already?

**Comment by awyl** [comment]
Yes, @jtkech explained to me.  But the various places that we fixed did not use `PathBase` where they should.

**Comment by jtkech** [comment]
It was not working in some places when under a `virtual folder`. E.g, when listing the content items in the admin, if you want to filter them by content types.

> Shouldn't the tenant be part of PathBase already?

Yes, and it may also start by a virtual folder, so here, when we build some urls (without using an url helper as `Url.Action()`), we use `PathBase` in place of just using the tenant url prefix as it was done.

Note: in some places we could have used `Url.Content("~/...")`

**Pull request merged**
