### PR TITLE
Obsolete WithCulture method fix to run on .NET 5

### PR DESCRIPTION
**Pull request by Diman96**

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/OrchardCMS/OrchardCore?pullRequest=7330) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/OrchardCMS/OrchardCore?pullRequest=7330) before we can accept your contribution.<br/><br/>:x: Diman96 [sign now](https://cla.dotnetfoundation.org/OrchardCMS/OrchardCore?pullRequest=7330)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/OrchardCMS/OrchardCore?pullRequest=7330) it.</sub>

**Comment by hishamco** [comment]
I'm not sure what's the issue, regarding `WithCulture` it's already removed in @agriffard PR for .NET 5.0

**Comment by deanmarcussen** [comment]
The suggestion I made was that we can't merge @agriffard pr at this stage, but it seems the `WithCulture` is the only blocker for @Diman96 trying to use the .NET 5 prerelease SDK.

So a standalone pr to just remove the `WithCulture` should be ok.

Unfortunately @Diman96 this pr is just a replica of @agriffard entire pr, so not something we can merge.

Please can you do a seperate pr to just remove the `WithCulture`

**Comment by hishamco** [comment]
@deanmarcussen `WithCulture` can't be removed until `5.0` is merged

**Comment by deanmarcussen** [comment]
@hishamco In that case I am wrong, so we will close this, and it will have to wait until we are ready to merge 5.0

My bad advise I'm afraid @Diman96

**Pull request closed without merging**
