### PR TITLE
Sponsorship

### PR DESCRIPTION
**Pull request by agriffard**
Add indiviual contributors from the dev team that have a GitHub sponsor account.

### CODE REVIEW

**Comment by hishamco** [comment]
What about those how haven't GitHub sponsor account, I'm struggling from two months or so, but still I'm unable to have an account, is there any other way to achieve this through Orchard Core Organization instead of setup the individuals themselves

**Comment by agriffard** [comment]
We tried to contact the .NET Foundation to know if they could act as a proxy (in an administrative perspective) in order to have a dedicated Orchard Core, like an Open Collective, but we didn't manage to have an answer.

The idea, here, is to list the contributors that can receive a sponsorship, to have a little bit of visibility and let people choose who they want to sponsor.

This may not seem the best way to do it but I hope it is better than nothing, even if I might be biased because I appear in the list of contributors.

**Comment by hishamco** [comment]
Why it's closed?

**Comment by agriffard** [comment]
Decision during the meeting.

**Comment by hishamco** [comment]
I see ..

**Comment by Piedone** [comment]
Here is it BTW: https://www.youtube.com/watch?v=fE59SuTcL78&feature=youtu.be&t=2904 However, maybe we could just add a note here to encourage people to look at the top contributors list and sponsor the ones they want? So while not mentioning specific people still encourage sponsorship?

**Pull request closed without merging**
