### PR TITLE
Show remove Field and part button when it is not system defined field/part

### PR DESCRIPTION
**Pull request by MikeAlhayek**

### CODE REVIEW

**Review by Piedone — COMMENTED** [review]
While this is all good, shouldn't we have some indicator that something is a system part/field? Because I can have e.g. this:

{4B02CB77-4273-452C-808C-18AD87BF95D9}

A user may wonder, why is Dashboard not removable? Why is Html Dashboard Widget neither editable nor removable?

**Comment by hishamco** [comment]
LGTM, just little notes

1. Agree with @Piedone that we need an indicator somehow, probably a badge
2. We could disable the button instead of hide it, just to make the buttons aligned

**Comment by hishamco** [comment]
I still think the badge will be obvious to the users, also the tooltip is too long, if this could be modified I will approve now, or wait for others to approve

**Comment by MikeAlhayek** [comment]
I used tooltip to align with the same implementation as the features UI.

**Review by Piedone — APPROVED** [review]
Much easier to understand, thank you!

**Review by hishamco — APPROVED** [review]

**Pull request merged**
