### PR TITLE
Release 2.1

### LINKED ISSUE #16995: Release v2.1.0
### Prepare the project

Do some housekeeping on GitHub in the [main repo](https://github.com/OrchardCMS/OrchardCore).

- [x] Assign the milestone of the release's version to this issue.
- [x] Close remaining issues for the version (including merging corresponding pull requests if suitable) or assign them to the next one.
- [x] Assign all issues that were closed for an upcoming version (including a wildcard version like "1.0.x") to this version (milestone).

### Prepare the code and documentation

Update the source, so everything looks like on the new version.

- [x] Create a `release/<version name>` branch (e.g., `release/1.8.0`) from `main` or the previous release branch. This is necessary to target pull requests for the upcoming release.
- [x] Create an issue branch out of this branch as usual.
- [x] Check the [release_ci](https://github.com/OrchardCMS/OrchardCore/blob/main/.github/workflows/release_ci.yml) workflow is using the expected .NET version to build the Docker images.
- [x] Update the `OrchardCore.Commons.props` file with `<VersionSuffix></VersionSuffix>` such that preview build numbers are not injected in packages. Verify the `VersionPrefix` tag matches the released version.
- [x] Update module versions in `src/OrchardCore/OrchardCore.Abstractions/Modules/Manifest/ManifestConstants.cs`.
- [x] Create a new milestone.
- [x] Add final updates to the release notes in the documentation. It should include the following, at least:
  - Overview of the release's highlights and goals. What do you want people to remember this release for?
  - Prerequisites. What framework version do you need, anything else to work with Orchard?
  - Upgrade steps, any migration necessary from previous versions, and any breaking changes.
- [x] Add the release notes documentation page to the documentation site's navigation in `mkdocs.yml` and remove it from `not_in_nav`.
- [x] Update the documentation to mention the version in all places where the latest version is referenced, for example, but not limited to (do a search for the package version string): [Status in the root README](https://docs.orchardcore.net/en/latest/#status), CLI templates, commands, the [Creating a new decoupled CMS Website](https://docs.orchardcore.net/en/latest/guides/decoupled-cms/) guide.

### Test the release

Make sure everything works all right.

- [ ] Make sure that [`OrchardCore.Samples` works](https://github.com/OrchardCMS/OrchardCore.Samples).
- [ ] Test the [guides](https://docs.orchardcore.net/en/latest/guides/) with the NuGet packages from the Cloudsmith feed (branches under `release/` are automatically published too). Test at least the following guides:
  - [Creating a modular ASP.NET Core application](https://docs.orchardcore.net/en/latest/guides/create-modular-application-mvc/)
  - [Creating an Orchard Core CMS website](https://docs.orchardcore.net/en/latest/guides/create-cms-application/)
  - [Creating a new decoupled CMS Website](https://docs.orchardcore.net/en/latest/guides/decoupled-cms/)
- [x] Re-certify Orchard Core for the latest major version of Red Hat Enterprise Linux if a new version has been released (e.g., v10 after v9). Refer to Orchard's [Red Hat Ecosystem Catalog profile](https://catalog.redhat.com/software/applications/detail/223797) for the previously certified version, the [Red Hat Customer Portal](https://access.redhat.com/articles/3078) for the latest version, and [our certification guide](https://docs.orchardcore.net/en/latest/topics/red-hat-ecosystem-catalog-certification/) for the certification steps.

### Prepare and publish Orchard Core Translations

Update everything in the [Translations project](https://github.com/OrchardCMS/OrchardCore.Translations). Only do this once all the code changes are done since localized strings can change until then.

- [x] Update .po files with [PoExtractor](https://github.com/lukaskabrt/PoExtractor). This will also update [Crowdin](https://crowdin.com/project/orchard-core).
- [x] Publish the new version on NuGet.
- [x] Update the `OrchardCore.Translations.All` package reference in the main repo's _./Dependencies.Packages.props_ file to refer to the new NuGet package.

### Publish the release

Do the harder parts of making the release public. This should come after everything above is done.

- [x] Tag the head of `release/<version name>` with the version. Include `v` in the name, e.g. `v1.8.0`.
- [x] Merge `release/<version name>` to `main`.
  - You'll need to create a pull request.
  - Merge it as a merge commit, not squash merge.
  - If there are merge conflicts, then create a `release/<version name>-integration` branch and fix them there.
- [x] Create and publish a release [on GitHub](https://github.com/OrchardCMS/OrchardCore/releases/new).
  - Generate release notes.
  - Add a link to the release notes in the docs (something like `For details on this version see the [release notes in the documentation](link here).`). Note that the docs will only be built once the branch is merged to `main`.
- [ ] Test the [guides](https://docs.orchardcore.net/en/latest/guides/) with the packages now automatically published to NuGet. Test at least the following guides:
  - [Creating a modular ASP.NET Core application](https://docs.orchardcore.net/en/latest/guides/create-modular-application-mvc/)
  - [Creating an Orchard Core CMS website](https://docs.orchardcore.net/en/latest/guides/create-cms-application/)
  - [Creating a new decoupled CMS Website](https://docs.orchardcore.net/en/latest/guides/decoupled-cms/)
- [x] Update [Try Orchard Core](https://github.com/OrchardCMS/TryOrchardCore).

### Publicize the release

Let the whole world know about our shiny new release. Savor this part! These steps will make the release public so only do them once everything else is ready.

- [ ] Tweet
- [x] Post to the [Orchard Core LinkedIn group](https://www.linkedin.com/groups/13605669/)
- [ ] Post to the [Orchard Core Facebook page](https://www.facebook.com/OrchardCore/)

### After the release is done

- [x] Create a new milestone with the next release number and close the old milestone.
- [x] Create a new release notes documentation file for the next version in the `OrchardCore.Docs` project. (e.g., `/releases/1.8.0.md`). Don't add it to the docs navigation and exclude it from validation under `not_in_nav` with `mkdocs.yml`.
- [x] Update the `OrchardCore.Commons.props` file with the next release number, and `<VersionSuffix>preview</VersionSuffix>` such that preview builds use the new one.

### PR DESCRIPTION
**Pull request by MikeAlhayek**
Fix #16995

### CODE REVIEW

**Comment by hishamco** [comment]
Seems you didn't see my comment 5 days ago https://github.com/OrchardCMS/OrchardCore/issues/16995#issuecomment-2477156518

**Comment by MikeAlhayek** [comment]
> Seems you didn't see my comment 5 days ago https://github.com/OrchardCMS/OrchardCore/issues/16995#issuecomment-2477156518

I did not.

**Comment by MikeAlhayek** [comment]
@sebastienros I think next steps are as follow:

1. Release translation package on nuget.
2. Update the package from nuget instead of cloud-smith.
3. Merge main to release/2.1
4. Merge releasel/2.1 on main 
5. Ship 2.1. 
 
Do you see an issue with this?

**Comment by sebastienros** [comment]
I published the 2.1.0 translations packages.

**Comment by MikeAlhayek** [comment]
> I published the 2.1.0 translations packages.

@sebastienros I updated the PR to use the 2.1.0. Let me know if you agree with the following steps next:

 - Merge main to release/2.1
 - Merge releasel/2.1 on main
 - Ship 2.1.

**Comment by hishamco** [comment]
@MikeAlhayek please hold on to this, there's a reported issue in Po Extractor https://github.com/OrchardCoreContrib/OrchardCoreContrib.PoExtractor/issues/100

@agriffard did you see such an error before, I'm waiting for the issue to provide steps to reproduce. If nothing stopper, I will publish a patch release ASAP and we can ship OC `2.1`

**Comment by agriffard** [comment]
> @MikeAlhayek please hold on to this, there's a reported issue in Po Extractor [OrchardCoreContrib/OrchardCoreContrib.PoExtractor#100](https://github.com/OrchardCoreContrib/OrchardCoreContrib.PoExtractor/issues/100)
> 
> @agriffard did you see such an error before, if nothing stopper we can ship OC `2.1`, otherwise I will publish a patch release ASAP

I didn't have any error to update the .pot translation files.

**Comment by sebastienros** [comment]
Any PRs merged in translations looked good. Only issue could be that we missed some strings.

**Comment by hishamco** [comment]
I replied to you on WhatsApp, but there's no respond from the author, so I can't reproduce the issue. Feel free to go

**Pull request merged**
