### PR TITLE
fix for "wrong environment variable value can be saved"

### PR DESCRIPTION
**Pull request by lampersky**
@rjpowers10 could you check if this will fix the issue #15275 

I've aded a few variables:

image

Here it is my `Default\appsettings.json`, as you can see I have correct value.

image

### CODE REVIEW

**Comment by MikeAlhayek** [comment]
why do we need to write these variable to the settings file? 

What if you want to change the default later?

**Comment by rjpowers10** [comment]
> why do we need to write these variable to the settings file?
> 
> What if you want to change the default later?

Yes, that was part of my question in the original issue. Not only was the wrong value being saved, I'm not sure if it's correct for it to be saved at all. The value doesn't get saved unless the env var is present at the time of tenant creation, so it may just be an obscure bug. If I initialize the tenant first and then add the env var, the correct value is used (and it is not saved to the file).

**Comment by Skrypt** [comment]
Because you can use a section of your appsetting.json file to create env variables with it.

**Comment by Skrypt** [comment]
Need to see why it gets written into our tenants appsettings.json files. Maybe there was a use case or it is simply the default behavior.

**Comment by lampersky** [comment]
I did not analyze why the environment variables are being saved, I assumed it was intentional, instead I focused on analyzing why the wrong value is being saved.

**Comment by Piedone** [comment]
Is this something you'd like to revisit any time soon @lampersky or should we close?

**Pull request closed without merging**
