### PR TITLE
Docs Timeline

### PR DESCRIPTION
**Pull request by agriffard**
https://docs.orchardcore.net/en/ag-timeline/docs/samples/timeline/

### CODE REVIEW

**Comment by Piedone** [comment]
You can ask me for a review once you're ready.

**Comment by agriffard** [comment]
For now, I only gathered the big milestones with important releases and events:

2010: Orchard 0.5
2011: Orchard 1.0
2012: Orchard Harvest Los Angeles
2013: Orchard Harvest Amsterdam
2014: Orchard Harvest Seattle
2015: Orchard Harvest Alicante
2017: Orchard Harvest New York
2019: Orchard Core 1.0.0-rc1
2010: Orchard Core 1.0.0-rc2
2021: Orchard Core 1.0
2023: First Orchard Harvest Online

**Comment by Piedone** [comment]
I think all releases can be there too (or at least the ones corresponding to a new .NET version).

**Comment by Piedone** [comment]
This looks like a draft PR (i.e. not meant to collect reviews yet), so I switched it to that.

**Pull request closed without merging**
