### PR TITLE
Update Jint

### PR DESCRIPTION
**Pull request by MikeAlhayek**

### CODE REVIEW

**Comment by Piedone** [comment]
These simple updates are done by Dependabot: https://github.com/OrchardCMS/OrchardCore/pulls?q=is%3Apr+is%3Aclosed+label%3A.NET Oddly enough though, no updates for two weeks now ([should be weekly](https://github.com/OrchardCMS/OrchardCore/blob/main/.github/dependabot.yml#L6)).

**Comment by MikeAlhayek** [comment]
I did not know we have an action that does this.

The history shows 

>  Errored with the message "Dependabot timed out during its update" 

Maybe we can increase the frequency to every 3 day too

**Comment by Piedone** [comment]
That would explain it, but where do you see that history?

**Comment by Piedone** [comment]
Ah, thanks. Why on earth would one put it there and not under https://github.com/OrchardCMS/OrchardCore/security where all the other Dependabot configs are?!

**Review by Piedone — APPROVED** [review]

**Comment by MikeAlhayek** [comment]
I think because dependabot is not a standard action. But should be at least referenced in the actions list as a non-standard action

**Comment by Piedone** [comment]
I'm looking into this.

**Pull request merged**
