### PR TITLE
Fix recipe steps with polymorphic types

### LINKED ISSUE #15246: AdminMenuNavigationProvidersCoordinator issue in main branch
I'm getting a lot of these in logs.

``` 
2024-02-03 12:39:15.9619|Default|00-4bc7e8b97123fe0446aeb1b4d56c3eee-022055cef940b42d-00||OrchardCore.AdminMenu.Services.AdminMenuNavigationProvidersCoordinator|ERROR|No Builder registered for admin node of type 'AdminNode' 
```

### PR DESCRIPTION
**Pull request by sebastienros**
Fixes #15246

### CODE REVIEW

**Comment by MikeAlhayek** [comment]
@sebastienros I think this works. But I think we also need to do the same things with deployment. If you try to export the Admin menu using deployment, the JSON looks like this

```
{
  "steps": [
    {
      "name": "AdminMenu",
      "data": [
        {
          "Id": "baef6f85ad13481681cde70ada401333",
          "Name": "Admin menus",
          "Enabled": true,
          "MenuItems": [
            {
              "UniqueId": "7b293d57056a4eebb3713f07f12c65d8",
              "Enabled": true,
              "Priority": 0,
              "LinkToFirstChild": true,
              "LocalNav": false,
              "Items": [],
              "Classes": []
            },
            {
              "UniqueId": "5118cecfde834dacb26ac08980f1b5a7",
              "Enabled": true,
              "Priority": 0,
              "LinkToFirstChild": true,
              "LocalNav": false,
              "Items": [],
              "Classes": []
            },
            {
              "UniqueId": "3e590d44f8704e4588e272dd966ce291",
              "Enabled": true,
              "Priority": 0,
              "LinkToFirstChild": true,
              "LocalNav": false,
              "Items": [
                {
                  "Position": "0",
                  "Priority": 0,
                  "LinkToFirstChild": true,
                  "LocalNav": false,
                  "Items": [],
                  "Classes": []
                },
                {
                  "Position": "1",
                  "Priority": 50,
                  "LinkToFirstChild": true,
                  "LocalNav": false,
                  "Items": [
                    {
                      "Priority": 0,
                      "LinkToFirstChild": true,
                      "LocalNav": false,
                      "Items": [],
                      "Classes": []
                    }
                  ],
                  "Classes": []
                }
              ],
              "Classes": []
            }
          ]
        }
      ]
    }
  ]
}
```

**Comment by sebastienros** [comment]
@MikeAlhayek fixed

**Comment by MikeAlhayek** [comment]
I'll give it a try. 

Since you are in STJ mind set, have a look at this issue if you have time  https://github.com/OrchardCMS/OrchardCore/issues/15322

**Comment by MikeAlhayek** [comment]
Still not working.

**Review by MikeAlhayek — APPROVED** [review]
I actually did another test. The Admin Menu seems to be working.

**Pull request merged**
