### PR TITLE
Add UseCdn Picker to Setup Page 

### PR DESCRIPTION
**Pull request by hyzx86**
#5969

### CODE REVIEW

**Comment by Skrypt** [comment]
We have a discussion next week about this. Your PR doesn't cover all scenarios. For example, here it will maybe work in the setup page. But it should be set before getting to the setup page. And even if the setup works afterward if you go to /admin the CDN issue will still remain.

**Comment by hyzx86** [comment]
This problem has been going on for a year, 
let's fix it first.
There are 1.4 billion people who don't have access to these CDN resources. A large number of new entrants have struggled with this problem. If there are any other problems, let's submit a new PR to solve them.

Thanks!

**Comment by Skrypt** [comment]
Duplicate PR see : https://github.com/OrchardCMS/OrchardCore/pull/7599

**Comment by sebastienros** [comment]
Closing since there is another PR with the same goal. And my preference is to just have local assets by default.

**Comment by hyzx86** [comment]
Hi @sebastienros  , Has the problem not been solved yet?
I found that the latest version still requires manual code to avoid loading resources from the CDN.

**Pull request closed without merging**
