### PR TITLE
Update npm dependencies + run npm run rebuild

### PR DESCRIPTION
**Pull request by jptissot**
**Edit:** 
Updated to only updates the build dependencies. Some minified files changed as a result.

Updated npm dependencies, ran `gulp rebuild`. Lots of files changed.
Maybe we don't want this. Just putting it out there.

### CODE REVIEW

**Comment by agriffard** [comment]
Well, good initiative but it is not so easy.

Some scripts and styles libraries also have their versions, their cdn and their CdnIntegrity set in ResouceManifest.cs so you also need to update them accordingly. 
Ex: CodeMirror.
Here is a tool to generate the SRI Hash from a url: https://www.srihash.org/

Sometimes, it is not a good idea to use the latest version. May be it is fixed but I remember that there were some troubles when I chose to update popperjs to 1.15, while Bootstrap 4.3.1 is using 1.14.7 as dependency:
https://getbootstrap.com/docs/4.3/getting-started/introduction/

Some others libraries need some tweaks.
Ex: Trumbowyg in which we add the image media popup plugin. 
Please see #2882 where I wanted to update it and offer a way to init the configuration in the TextField Editor settings.

**Comment by jptissot** [comment]
Thanks for the feedback. I'll change the pr to only update dev dependencies. Then maybe attempt to update the other dependencies separately. Would this be useful?

**Comment by hishamco** [comment]
May be @deanmarcussen is interested on this one :)

**Comment by deanmarcussen** [comment]
Haha, yes not to be the cdn police, but what @agriffard says, it is never simple, suggest doing it slowly, project by project (see the npm projects listing in the root package.json) is good, and match up with the `ResourceManifest`

Also @hishamco I see TheAdmin.css rebuild here has lost your `jquery-ui-override`. You miss the `import` statement in `TheAdmin.sass` so it will always get lost on a rebuild. Can you fix that?

**Comment by jptissot** [comment]
Updated to only updates the build dependencies. Some minified files changed as a result.

**Pull request merged**
