### PR TITLE
Adding ContentItem property to the menu shape

### LINKED ISSUE #2540: Menu shape builder (OnProcessing) ignores dynamically added parts
Extending the Menu content type definition via the admin UI doesn't work properly in all cases. Additional fields and parts can be added to the Menu content type, and then filled in for a specific Menu content item, but they are never added to the Menu shape when it is being populated (during the OnProcessing event for caching purposes) for display in the main site (not the admin site).

Parts other than the ones welded by the MenuContentHandler are currently overlooked when building the Menu shape, and they are therefore not available to be displayed in the Menu template. A workaround would be to inject IContentItemDisplayManager and some other helpers into the template, and call buildDisplay to get the ContentItemDisplayCoordinator to build the whole shape properly. However it seems it would be more helpful for this to be handled during the OnProcessing event with the other Menu shape building logic.

### Reproducing the Problem
- Go to the admin dashboard and add a new field to the Menu content type.
- Go to the Menu content item and fill in the new field with some value, and publish
- Load the any page for your actual site, and you will notice that the field is not displayed anywhere on the menu
- Go to the Menu.cs / liquid template and attempt to access the field on the Model...
- ... it isn't there

### PR DESCRIPTION
**Pull request by sebastienros**
Fixes #2540

### CODE REVIEW

**Comment by aodl** [comment]
I see that this is certainly a lot simpler. My perspective is obviously that of a new comer to Orchard, but this approach seems to diverge from what a person using Orchard would expect i.e. when you add a part to a content item, Orchard takes care of turning it into a shape for you and making it available on the model passed into the template

**Comment by sebastienros** [comment]
The issue comes from the fact that we are already creating a shape when using `<menu>`, and here we are just trying to load a specific content item and pass it to this menu shape.

Maybe a better solution would be to have a generic tag helper that would render any content item, using the same trick to allow for aliases and cache metadata, and only provide alternate dynamically, though alias might already be able to provide an alternate.

In the end I suggest we merge this change to unblock everyone, and I am opening an issue to try this new approach. Because I am adding `ContentItem` here, implementing the new approach would only add a breaking change to the name of the tag helper which would be more generic.

**Comment by sebastienros** [comment]
https://github.com/OrchardCMS/OrchardCore/issues/2632

**Pull request merged**
