### PR TITLE
Add user to a role acquired from principal.

### PR DESCRIPTION
**Pull request by fmacedoo**
Hi,

I am integrating OrchardCms to some others services i have. So i got into a point i would like to automate the way the new users registering into my CMS, through external login, also get their role previously set up at Azure AD Portal.

Herewith i changed the way the ExternalLoginConfirmation method works to include that logic.

Does that make sense to you all?

### CODE REVIEW

**Comment by MichaelPetrinolis** [comment]
There are two pending PRs that cover that need (#3488 and #3722).
There are demos also on Lombiq channel

**Comment by fmacedoo** [comment]
Wow that's awesome. If i could help, just let me know.

**Comment by agriffard** [comment]
@fmacedoo I tried to fix a conflict. Please check it is ok.

**Comment by agriffard** [comment]
Error during build:
`Controllers\AccountController.cs(537,126): error CS0103: The name 'OpenIdConnectConstants' does not exist in the current context`

**Comment by agriffard** [comment]
Can you please fix the build?

**Comment by MichaelPetrinolis** [comment]
@agriffard We already handle the mapping for roles between external provider's claims and user roles, so this PR is not needed. 
@fmacedoo did you manage to achieve your goal with the OOB implementation in OrchardCore ?

**Pull request closed without merging**
