### PR TITLE
Media Anchor Picker and Media Text Editor

### PR DESCRIPTION
**Pull request by deanmarcussen**
Fixes https://github.com/OrchardCMS/OrchardCore/issues/4326

Allows extra meta data to be added to the media field(s) for alt text, and introduces a crop anchor picker where a crop center location / anchor can be selected and saved with the media field(s).

Is optional, and configurable through settings if alt-text is allowed, or crop picking.

Uses ImageSharp for the crop / pad anchoring, and stores data in the media field element (not hard typed, so optional).

TODO 
- [x] Merge https://github.com/OrchardCMS/OrchardCore/pull/7119
- [x] Add encryption option to prevent disc filling
- [x] ~~Add precision option~~ removed in favour of tokens
- [x] max-height the modal image
- [x] `MediaText` property hard type on the `MediaField`

@sebastienros I changed my mind ;)

### CODE REVIEW

**Comment by deanmarcussen** [comment]
Related to The media profiles feature https://github.com/OrchardCMS/OrchardCore/pull/7119

but not reliant on it.

Marking both not ready as we should see if we want to integrate more with profiles, i.e. crops per profile. 

I think probably not, it might be over complicated (for users) to do that, but opinions are welcome...

**Comment by agriffard** [comment]
Can it be related to #6180 ?

**Comment by deanmarcussen** [comment]
> Can it be related to #6180 ?

Kinda of, but it isn't an image editor, I think we will still want an image editor, but that would be more for the media app itself, rather than the media field.

**Comment by deanmarcussen** [comment]
What about calling it `MediaText` @Skrypt ?

Because `Metadata` people might think it had image size and other meta information in it?

**Comment by Skrypt** [comment]
I'd try to make a distinction between Title and Alt. Here it's a Media Title. MediaText can work but it's less descriptive. Though, no big difference in the end.

**Comment by agriffard** [comment]
What do you mean by 'Merge #7209' in the todos? This is the current one.

**Comment by deanmarcussen** [comment]
> What do you mean by 'Merge #7209' in the todos? This is the current one.

Oops, meant https://github.com/OrchardCMS/OrchardCore/pull/7119 (updated)

Blocked on doing anything further as I'm to lazy to deal with the merge conflicts

**Comment by deanmarcussen** [comment]
> I'd try to make a distinction between Title and Alt. Here it's a Media Title. MediaText can work but it's less descriptive. Though, no big difference in the end.

So for me, unless I'm misunderstanding something it could be used for Title / Alt / anything (you could even throw some json in it to give more data, alt, and title).

So it seems like `DisplayText` - which can mean `Title`, but doesn't always (Widgets for example).
Hence I'm thinking `MediaText`, as being generic enough that it could be used for anything.

I will make it a property on the field (`MediaTexts` - because it's an array), rather than an extension...

**Comment by scleaver** [comment]
@deanmarcussen could this be used to store other things? Is it extensible? So currently I am using the media picker to select an mp3 file that is stored on Azure. I need to store the file size and actually the duration too automatically... I don't want to store this on save of the content item rather than the more costly exercise of getting this info from the file when displaying the content on the frontend.

I had actually added two properties to my content type to store the size and but it would seem better to do something like what you are doing.

**Comment by deanmarcussen** [comment]
@scleaver this could be a little extensible, in that you could choose to store, for example, a comma delimited string with multiple values. 

But it would still be editable, and may not be the best user experience.

I suspect adding the two properties and managing it as a content type / part might be a better user experience.

Equally all the fields, including this one, support storing other values alongside them. 

Here there is also a `Centers` array which is not hardcoded on the `MediaField` but accessed and set through some extension methods.

So for what you are doing, if you want to do it automatically, you might implement a second mediafield driver (or a content type handler) which could check the size, and duration, if it is an mp3 file, during save, and update a hidden property on the `MediaField` which would be accessible in your templates, but not seen on the ui.

**Comment by deanmarcussen** [comment]
Done - I think :)

`AltText` renamed to `MediaText`
Crop Centers renamed to `Anchor` as calling them `Center` was not quite clear enough. (it's not a center, when you offset a different part of the image, at that point it's a crop center, or pad center.)

But Anchor seemed to make sense as being specifically an Anchor point, whichever resizing technique is applied.

Tokens remain `token=` because I think they are actually a token, because they do contain the actual values of the resizing commands in the encrypted string. So it's not just obscufation, they do contain a tokenized value.

Screenshot 2020-11-01 at 12 52 44

Screenshot 2020-11-01 at 12 52 55

**Pull request merged**
