### PR TITLE
Monaco 0.24.0

### PR DESCRIPTION
**Pull request by agriffard**
https://www.npmjs.com/package/monaco-editor/v/0.24.0
https://github.com/microsoft/monaco-editor/releases/tag/v0.24.0

/cc @MichaelPetrinolis

### CODE REVIEW

**Comment by MichaelPetrinolis** [comment]
Should we use Monaco in liquid template editor? 
Is included in basic languages now!

**Comment by agriffard** [comment]
> Should we use Monaco in liquid template editor?
> Is included in basic languages now!

Good question @MichaelPetrinolis .
Indeed, I saw ther was a new liquid.js included in the languages.

Could you make a PR once this one is merged?

**Comment by agriffard** [comment]
See also #5242

**Comment by MichaelPetrinolis** [comment]
@agriffard sure, i will check it out ;)

**Pull request merged**
