### PR TITLE
Prevent ConnectionResetException on SelectedContentType change.

### PR DESCRIPTION
**Pull request by jtkech**
Sometimes when changing the content type selection under the content items index page.

It doesn't stop the app but errors are logged.

    Microsoft.AspNetCore.Connections.ConnectionResetException: 'The client has disconnected'
    0x800704CD "An operation was attempted on a nonexistent network connection."

It was 1st failing in our `FormValueRequiredMatcherPolicy`, i could fix it by checking `httpContext.IsRequestAborted` but then it was failing elsewhere in aspnetcore.

So here i tried the following on client side that seems to fix the issue.

- I removed an event that seems to be never triggered. Note: i was not able to use breakpoints (and right now i didn't search to do so) in a script that is inside a razor view.

- Then, when changing the content type selection, i kept the update of the action attribute but i removed the form submission that seems to be done in the following event. So i think the form was submitted twice and we were processing the 2nd one while the page was refreshing on the client side.

@agriffard when you will have time

### CODE REVIEW

**Comment by jtkech** [comment]
@Skrypt @agriffard @deanmarcussen @jptissot @hishamco  ...

Am i the only one to get logged errors when playing with the content type filter under the content items index page? Which is why i made this PR to fix it ;)

**Comment by deanmarcussen** [comment]
LGTM

@jtkech I'm not seeing the log errors (for some reason )

But I can clearly see the ajax call being cancelled and aborted every time a content type is selected in the chrome debugger.

**Comment by Skrypt** [comment]
I'm not on latest since a month so no clue for that one. I'm going to merge latest soon.

**Comment by jtkech** [comment]
@Skrypt yes it is related to recent change

**Pull request merged**
