### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by hishamco**
- Add build history
- Separate packages feed from build status

### CODE REVIEW

**Comment by hishamco** [comment]
ReadMe

**Comment by deanmarcussen** [comment]
I wish people would open issues about these things so they can be triaged.

So the change is adding some build history?

**Comment by deanmarcussen** [comment]
My concern with this is understanding what happens when builds are cancelled because we merge a few things at once.

If it's listing these cancelled builds, as failed (which it does when looking through github), then it would be showing an inaccurate picture.

**Comment by hishamco** [comment]
Dean frankly I'm not sure if it tracks the cancelled builds, but let me check if the gray bars means the build is cancelled

**Comment by agriffard** [comment]
This is not the kind of information that should appear in the Readme.
Closing it.

**Comment by hishamco** [comment]
> This is not the kind of information that should appear in the Readme.

Why? It is something I see in some repos for more detailed history about the builds, something like build status that we already show in README.md

**Pull request closed without merging**
