### PR TITLE
Fix zh cn

### PR DESCRIPTION
**Pull request by hyzx86**
fix : https://github.com/OrchardCMS/OrchardCore/issues/11672

In the recent update of System.Runtime, the `CultureInfo.GetCultures(CultureTypes.AllCultures)` 
command does not directly list zh-CN

In order to keep the browser consistent, a patch is made here to get the option of zh-CN, as it is only used for setting up the page, which should not cause performance problems

After fix:

image

image

### CODE REVIEW

**Comment by hishamco** [comment]
I disagree with the change, we need to resolve it in better way, let me check the issue carefully

**Comment by hishamco** [comment]
@hyzx86 check my comment [here](https://github.com/OrchardCMS/OrchardCore/issues/11672#issuecomment-1369011238)

**Comment by hyzx86** [comment]
@hishamco 
You can check this file, it contains a lot of handling of `zh` ,
And the latest version is quite different, so I added  `.Distinct()`


image

[CultureInfo.cs.txt](https://github.com/OrchardCMS/OrchardCore/files/10332232/CultureInfo.cs.txt)

**Comment by hishamco** [comment]
As I mentioned in the original issue the issue is not in .NET, OC just provided two cultures by default I'm not sure if we rename `zh-CN` to `zh` is right or not?!! But I think it's wrong because it targets both Chinese and Taiwan

Still I'm wondering should we have to support `zh`? If yes what about `zh-CN` and `zh-TW`?

**Comment by hishamco** [comment]
Closing this, while this is not a proper fix

**Comment by hishamco** [comment]
Closing this, while this is not a proper fix

**Comment by hishamco** [comment]
Seems we need to modify your PR as temp & quick fix

**Comment by hishamco** [comment]
I wasn't able to commit, so I will close this in favour of #13047

**Pull request closed without merging**
