### PR TITLE
Update Fluid 2.6.0

### PR DESCRIPTION
**Pull request by hishamco**
https://github.com/sebastienros/fluid/releases/tag/v2.6.0

https://www.nuget.org/packages/Fluid.Core/2.6.0

### CODE REVIEW

**Comment by hishamco** [comment]
@sebastienros is `DelegateAccessor` becomes sealed class?

**Comment by sebastienros** [comment]
> Error: /home/runner/work/OrchardCore/OrchardCore/src/OrchardCore/OrchardCore.DisplayManagement.Liquid/LiquidViewTemplate.cs(102,36): error CS0509: 'ShapeAccessor': cannot derive from sealed type 'DelegateAccessor' 

ouch

**Comment by hishamco** [comment]
Related to https://github.com/sebastienros/fluid/pull/611

/cc @lahma

**Comment by sebastienros** [comment]
@hishamco can you just copy the code from the previous type? It's very minimal.

**Comment by hishamco** [comment]
This simple workaround to inherits from `DelegateAccessor<object, object>` instead

**Comment by hishamco** [comment]
I think we're ready to merge

**Comment by lahma** [comment]
Yep, `DelegateAccessor` as base class doesn't make much sense when there's nothing to override from that type.

**Comment by hishamco** [comment]
Are we fine with the current changes?

**Pull request merged**
