### PR TITLE
Renamed  SummaryAdmin shapes of ContentsDriver

### PR DESCRIPTION
**Pull request by ns8482e**
Following `ContentsDriver` creates four shapes with different shape types. 

https://github.com/OrchardCMS/OrchardCore/blob/85b4f99618ba263b55cb72e366d973e1967b2298/src/OrchardCore.Modules/OrchardCore.Contents/Drivers/ContentsDriver.cs#L51-L54

However the actual shape type is considered before `__`  i.e. all above shapes are resolved to the same shape type `Contents_SummaryAdmin` 

Renamed these shapes as following to apply unique placement record for each shape

`Contents_SummaryAdmin__Tags`  renamed to  `ContentsTags_SummaryAdmin`
`Contents_SummaryAdmin__Meta` renamed to `ContentsMeta_SummaryAdmin`
`Contents_SummaryAdmin__Button__Edit` renamed to `ContentsButtonEdit_SummaryAdmin`
`Contents_SummaryAdmin__Button__Actions` renamed to `ContentsButtonActions_SummaryAdmin`

so that placement will target single shape type.

```
{
    "ContentsButtonActions_SummaryAdmin": [
      {
        "shape":"ContentsButtonEditNoView_SummaryAdmin"
      }
    ]    
}
```

Fixes #7002

### CODE REVIEW

**Comment by deanmarcussen** [comment]
So the issue is that using a seperator in the shape name stops placement from hitting it?

My gut feel is that we might be better off renaming the shapes, than having a differentiator that noone will know about?

A differentiator would normally have something regarding a content item / part / field name, so it's a bit weird to be differentiating between zones.

Related https://github.com/OrchardCMS/OrchardCore/issues/5151 (feel free to add a comment about how placement is impacted by seperators @ns8482e

**Comment by ns8482e** [comment]
> So the issue is that using a seperator in the shape name stops placement from hitting it?

Yes,  It's because original shape type is identified before `__`  in shape templates. Here! The original shape type for Contents_SummaryAdmin__Tags , Contents_SummaryAdmin__Meta, Contents_SummaryAdmin__Button__Edit, and Contents_SummaryAdmin__Button__Actions is Contents_SummaryAdmin hence placement is applied to all shapes


> Related #5151 (feel free to add a comment about how placement is impacted by seperators @ns8482e

Yes, I can update the PR to change ShapeType to to not have `_` or `__` and change the template name without using  differentiator.

e.g.

Contents_SummaryAdmin__Tags ----> SummaryAdminTags ---->SummaryAdminTags.cshtml
Contents_SummaryAdmin__Meta ----> SummaryAdminMeta ----> SummaryAdminMeta.cshtml
Contents_SummaryAdmin__Button__Edit ----> SummaryAdminButtonEdit ----> SummaryAdminButtonEdit.cshtml
Contents_SummaryAdmin__Button__Actions ----> SummaryAdminButtonActions ----> SummaryAdminButtonActions.cshtml

**Comment by deanmarcussen** [comment]
> Contents_SummaryAdmin__Tags ----> SummaryAdminTags ---->SummaryAdminTags.cshtml

Wouldn't it be `Contents_SummaryAdmin__Tags` ----> `ContentsTagsSummaryAdmin` ?

**Comment by ns8482e** [comment]
> Wouldn't it be `Contents_SummaryAdmin__Tags` ----> `ContentsTagsSummaryAdmin` ?

Sure It will work just thought to remove prefix `Contents` to avoid confusion with other shapes as Here it's not representing stereo type. These shapes will be use for all content items regardless of their stereo type.

**Comment by deanmarcussen** [comment]
> > Wouldn't it be `Contents_SummaryAdmin__Tags` ----> `ContentsTagsSummaryAdmin` ?
> 
> Sure It will work just thought to remove prefix `Contents` to avoid confusion with other shapes as Here it's not representing stereo type. These shapes will be use for all content items regardless of their stereo type.

I think the `Contents` was more an indicator which driver it was produced by, not related to stereotype.

I would keep it, otherwise there is no indicator that the shape is even content related. 

It would be good to see the change, and I want to discuss this at triage 

- This could be achieved by a shape provider
- Should placement work for everything?
    - Placement has been historically focused on front end display, but there are now more requests / expectations that it will work with all the admin shapes
    - If so, we have a larger shape renaming job to come, and a better shape name convention that we need to follow, that would need to reduce seperators when they have no specific meaning (like in this case, the seperator has no meaning, it is just getting in they way)

**Comment by ns8482e** [comment]
> * we have a larger shape renaming job to come, and a better shape name convention that we need to follow

Yes It's related #5151 and #5126 

> I think the `Contents` was more an indicator which driver it was produced by, not related to stereotype.

Ok, I agree for `Contents` prefix, if it's indicator of the driver  - Then I feel `SummaryAdmin` suffix is redundant, and the shape type should be without `displayType` suffix i.e.. `ContentsTags` 

And it's also align with the other shape `ContentsMetadata` produce by same driver but for `Detail` display type. 

So following placement would more appropriate

```
"ContentsTags": [
      {
        "displayType" : "SummaryAdmin",
        "place":"-"
      }
    ]
```

compared to


```
"ContentsTagsSummaryAdmin": [
      {
        "displayType" : "SummaryAdmin",
        "place":"-"
      }
    ]
```

**Comment by deanmarcussen** [comment]
`ContentsTags_SummaryAdmin`

**Comment by ns8482e** [comment]
> `ContentsTags_SummaryAdmin`

Read display type from context or hardcode in shape type? e.g.

`Shape("ContentsTags_SummaryAdmin", new ContentItemViewModel(model)).Location("SummaryAdmin", "Tags:10"),`
or
`Shape($"ContentsTags_{context.DisplayType}", new ContentItemViewModel(model)).Location("SummaryAdmin", "Tags:10"),`

**Review by sebastienros — APPROVED** [review]

**Pull request merged**
