### PR TITLE
Admin UI: Header buttons

### LINKED ISSUE #8034: Admin UI : header buttons
Before #7851 :  

image

After #7851 : 

image

I found out that we are displaying these buttons inside a hamburger menu now.
I'm not a fan of it. They should be displayed all the time.
If we have other menu items then they should be added in the hamburger menu but only if they have a text.
This looks strange needing to open the hamburger menu to toggle the darkmode.

image

/cc @agriffard

### LINKED ISSUE #8084: Admin UI : Top navbar titles that are too long will break UI
And make top navbar buttons unclickable.

image

### PR DESCRIPTION
**Pull request by Skrypt**
Fixes #8034, Fixes #8084

Before :  

image

After :  

image

### CODE REVIEW

**Comment by agriffard** [comment]
Can we please have the navbar icon links with dark color on light mode and light color on dark mode instead of blue, and not underlined on hover (see space between User and toggle)?

**Comment by agriffard** [comment]
Suggestion on xs screen: 
```
max-width: 220px;
overflow: hidden;
height: 28px;
word-break: break-all;
```

**Comment by Skrypt** [comment]
It's a draft ... I felt asleep before finishing this one. 😉

**Comment by Skrypt** [comment]
@agriffard Done. Your request is in the latest commit. Please test before anything.

**Review by agriffard — APPROVED** [review]
LGTM

**Pull request merged**
