### PR TITLE
Update Microsoft.Extensions.Azure 1.7.6

### PR DESCRIPTION
**Pull request by hishamco**

### CODE REVIEW

**Comment by MikeAlhayek** [comment]
Why are we doing this manually again? leave it to the dependabot to do it. @Piedone is working on resolving the issue with it.

**Comment by hishamco** [comment]
I just updated a few of the packages while @Piedone fixed it

**Comment by MikeAlhayek** [comment]
Unless there is a security issue that requires an urgent update, we should not waste time with these PR and leave them for the bot. If we update everything then we won't have any to test the bot with.

**Comment by Piedone** [comment]
Yep, better to leave these.

**Comment by hishamco** [comment]
No problem, I just updated those because I saw you updated the package `libphonenumber-csharp` recently #16830

**Comment by Piedone** [comment]
Yes, and I did that because of what I elaborated in the comment linked from there: https://github.com/OrchardCMS/OrchardCore/issues/16729#issuecomment-2393456700

**Pull request closed without merging**
