### PR TITLE
Added dotnet format

### PR DESCRIPTION
**Pull request by ns8482e**
Added dotnet format verification (`--verify-no-changes`) in PR pipeline.

Developer can fix the the reported errors by running `dotnet format`

### CODE REVIEW

**Comment by agriffard** [comment]
Is there a way to apply the recommendations?

**Comment by MikeAlhayek** [comment]
Build failed

**Comment by Skrypt** [comment]
Probably because it is chasing its own tail. It adds a CI `dotnet format` check while there are issues needed to be fixed which this PR fixes. The issues will need to be fixed before adding `dotnet format`  check.

**Comment by ns8482e** [comment]
> Build failed

it’s failed because due to line ending in Linux.  Git config takes care of line ending based on OS. However editorconfig has defined it crlf 

May be just validate it in windows only

**Comment by Skrypt** [comment]
The EOL is for Git I believe. Could have worked with a warn-only message. Need to see if we could force squash and merge still.

**Review by Piedone — CHANGES_REQUESTED** [review]
We should rather guard against such changes as part of the .NET build, treating warnings as errors, not with a separate CI step. Also see https://github.com/OrchardCMS/OrchardCore/issues/7950.

**Pull request closed without merging**
