### PR TITLE
Duplicate local time zone item

### PR DESCRIPTION
**Pull request by hishamco**

### CODE REVIEW

**Comment by Skrypt** [comment]
I will review this one because we juggled already a lot with those values. Let's be prudent with changes on that.

**Comment by hishamco** [comment]
Ok, but I was surprised why the first item exist!! because the default behavior the item with the `selected` property on it will show up first

**Comment by sebastienros** [comment]
I also think the behavior it's what is expected and that it's just not understood or documented why... Will check when i come back.

**Comment by hishamco** [comment]
> I also think the behavior it's what is expected and that it's just not understood or documented why... Will check when i come back.

I double checked this scenario, but it's great to confirm it from your end ⌚️

**Comment by Skrypt** [comment]
Looks fine to me. I don't remember why we duplicated the option of the LocalTimeZone instead of just selecting it from the options.

**Comment by sebastienros** [comment]
@Skrypt you are suggesting to merge it?

**Comment by Skrypt** [comment]
I'm saying that I can't remember why we duplicated that option. There was a reason? Let's check commit history to make sure.

**Comment by Skrypt** [comment]
That option is duplicated since first merge of the NodaTime branch. This PR is safe to merge. The only thing that will happen is that it will pre-select the proper timezone instead of adding it as the first element. I probably forgot to remove it and though it was selecting the proper timezone.
I approve. It can't break the setup.

**Pull request merged**
