### PR TITLE
Use package.json in OrchardCore.Resources

### LINKED ISSUE #2820: npm packages and assets
Reference in package.json other sub dependencies in different modules that restore scripts and css to generate assets in order to consolidate their use and easily update their version when published on NPM.

Already done for Apis.GraphQl and Worflows.

Ex of Todos:
CodeMirror #1998
Trumbowg #2816

Integrate other libraries in Resources? Bootstrap, Popper.js, jQuery, ...

### PR DESCRIPTION
**Pull request by agriffard**
Fixes #2820 

Added dependencies to Bootstrap, Popper.js (1.14.6), CodeMirror (5.42.0) and replaced paths to point to corresponding node_modules folders.

Used `asp-name` instead of `asp-src` for codemirror scripts (tests todo in workflows tasks using them).

Also: added this in apis.grapql package.json because there was a warning: `"graphql": "0.12.0",`

Didn't touch to trumbowyg and jquery-ui in the Assets and Scripts for the moment.

### CODE REVIEW

**Comment by sebastienros** [comment]
Did you remove the files that were used from /Assets?

**Comment by agriffard** [comment]
Not yet. 

We can emove the Bootstrap folder in Asses but we will keep jQuery (with version 1,2 and 3 inside) and trumbowyg for the moment.

Do you want me to do it?

**Comment by sebastienros** [comment]
Yes please. Also not sure we need to ship jquery < 3.

Removing the unnecessary files should be part of the PR if it is to use npm.

**Comment by agriffard** [comment]
If I remove Bootstrap, I can't use the Hack I added to make the build work: 
Comment `@import "functions";` in bootstrap.scss and add it in _variables.scss.

and if I do not use it, there is an error with `gulp rebuild`:
```
[1] Message:
[1]     node_modules\bootstrap\scss\_variables.scss
[1] Error: argument `$color` of `darken($color, $amount)` must be a color
```

The cause can be that we use compile *.scss in gulpfile.js : See https://github.com/twbs/bootstrap/issues/25361#issuecomment-437306598

So, I can't really finalize it and remove Bootstrap from the Assets, right now.

Also, Bootstrap.scss and other .scss are still referenced directly in some .scss like TheAdmin.scss, setup.scss, bootstrap-switch.scss

**Comment by sebastienros** [comment]
Maybe we don't need bootstrap in resources then. Admin can reference it by itself, and other themes too, which I assume they already do.

**Comment by sebastienros** [comment]
I fixed all the things. I also tested the setup, admin, and workflows.

**Pull request merged**
