### PR TITLE
Fix alias and autoroute defaults

### PR DESCRIPTION
**Pull request by deanmarcussen**
Follow on from https://github.com/OrchardCMS/OrchardCore/pull/4933 

just updates the defaults to use the `Model` property

### CODE REVIEW

**Comment by sebastienros** [comment]
Did we break everyone with the Template changes? @jtkech

**Comment by deanmarcussen** [comment]
Yeah all the default patterns went to .Model maybe we should do a migration?

**Comment by jtkech** [comment]
I retrieved my related comment

> Note: There are many places where we add a ContentItem value to the liquid scope, maybe we could remove them because now most of the time it is already accessible through Model.ContentItem.

Yes i did it knowing that people will have to change some of their settings, the ones using `ContentItem` directly in a liquid expression. Do we need to revert this change ?

I updated the recipes but i missed to change these default values.

@deanmarcussen we would also need to update `OrchardCore.Taxonomies.Migrations` line 28

    .WithPart("AliasPart", part => part.WithPosition("2")
        .WithSettings(new AliasPartSettings {
            Pattern = "{{ ContentItem | display_text | slugify }}" }))

**Comment by sebastienros** [comment]
Or pass a lambda or a dictionary to initialize the local scope. This way we can get the previous behavior back.

**Pull request closed without merging**
