### PR TITLE
Prettify recipes page

### LINKED ISSUE #4178: Prettify Recipes page

### PR DESCRIPTION
**Pull request by hishamco**
Fixes #4178

### CODE REVIEW

**Comment by sebastienros** [comment]
Don't forget the screenshots please, that helps us a lot. Before/After is even better btw.

**Comment by hishamco** [comment]
Nah, it's in my desktop, I thought I attached

Recipes

**Comment by hishamco** [comment]
Just the same search bar, and minimize the font in the headers, nothing else

**Comment by sebastienros** [comment]
These are quite agressive changes in the final html, lots of code IMO. /cc @Skrypt

**Comment by Skrypt** [comment]
It's fine he needed to use a card. The other option would have been to use actual classes to create a box with borders ... Maybe the first fieldset element could have been avoided but I'll see later.

**Comment by hishamco** [comment]
If there's anything related to the UI part, please let me know, coz I'm working on the Admin theme, web & mobile views

**Pull request merged**
