### PR TITLE
Fix sizing of html/markdowneditor settings to be consistent 

### PR DESCRIPTION
**Pull request by deanmarcussen**
Fixes https://github.com/OrchardCMS/OrchardCore/issues/6615

Closes https://github.com/OrchardCMS/OrchardCore/pull/6618

Related also to https://github.com/OrchardCMS/OrchardCore/pull/7175 

Bringing them all together for some consistency.

They all look like this now, without uneven padding, and shapes are consistently ordered.

Screenshot 2020-10-02 at 19 03 49

### CODE REVIEW

**Comment by hishamco** [comment]
There's already PR opened for #6615 ;)

**Review by Skrypt — APPROVED** [review]
LGTM

**Comment by deanmarcussen** [comment]
Yes @hishamco your pr was just missing some, so it was easier to start again.

However I see you managed to get the text field settings which I have missed, so if you want to update your pr after to just include those, to match this, that would be good

**Comment by hishamco** [comment]
No problem @deanmarcussen the important thing is we 're fixing the issues, but what I have seen last time there are some duplicate PR that are solving the same issue, so instead of more efforts we can ask the author for the first one to make the suitable updates, but if there's no respond we can start a new

I will try to review this one if it's need, thanks as usual Dean

**Pull request merged**
