### PR TITLE
Add move cursor to field list and part list items on edit content type view

### PR DESCRIPTION
**Pull request by matiasmolleja**
Right now there is no indication to the user that the fields and parts can be dragged.

### CODE REVIEW

**Comment by Skrypt** [comment]
Shouldn't we try to avoid using inline styling? Or is that one an exception?

**Comment by matiasmolleja** [comment]
You are right. But the module does not have a css file yet, and the addition is so small I thought it did not deserve adding a new css.

**Comment by Skrypt** [comment]
We could add this directly into the admin theme as a global class.

**Comment by matiasmolleja** [comment]
It's only that for maintenance I don't like to add to theAdmin rules specific to id's and classes that are spread across other modules ?

**Comment by Skrypt** [comment]
Well if it's a class that can be reused inside different modules then it makes sense to have it in the admin theme.

From the admin sass file : 
// Sortable
// ------------------------------
.ui-sortable-handle {
    cursor: move;
}

**Comment by matiasmolleja** [comment]
OK, I will add something similar to TheAdmin for Rubaxa's sortable. The library provides a 'handle' option that you can assign to a css class. I will do this afternoon.
Maybe you should sleep a little? 🛌  😆

**Comment by Skrypt** [comment]
Don't worry I'm going soon 🤓

**Pull request merged**
