### PR TITLE
Fixes #5823 Call LoadAsync() in Admin List (Lombiq Technologies: OCORE-18)

### LINKED ISSUE #5823: ContentManager.LoadAsync is not called for the content items when listing them on admin
The List action in OrchardCore.Contents/Controllers/AdminController.cs doesn't initialize content items (i.e. `_contentManager.LoadAsync(pageOfContentItems)` is missing). Is this intentional? Because of this the content handlers are also not activated.

### PR DESCRIPTION
**Pull request by jtkech**
Fixes #5823

TODO: To be done also when listing items in a list as blog posts in a blog

### CODE REVIEW

**Comment by sebastienros** [comment]
Too much abstractions. Will need to check that it's really necessary.

**Comment by jtkech** [comment]
Okay, just did it quickly yesterday

Will try to simplify it this night ;)

**Comment by sebastienros** [comment]
What about calling LoadAsync, or Get on the restuling ids, just simpy using the content manager when the session query is done?

**Comment by jtkech** [comment]
I thought about it but first tried like this because of @Piedone comment in the related issue.

> I'd create something like IContentManger.Query() that starts a specially prepared YesSQL query ...

But okay, i will try your suggestion, maybe better as we would not have to change the `IContentManager`

**Comment by jtkech** [comment]
@sebastienros 

Just to be sure, what do you meant with `Too much abstractions`

I just moved the 2 new classes from `OC.ContentManagement.Abstractions` to `OC.ContentManagement` just to show that we don't need them to be there, i thought it could be useful if someone want to override `IContentManager`.

But i think this is not what you meant, if so i will close this PR and start a new one based on your suggestion.

**Comment by jtkech** [comment]
Replaced by #9161

**Pull request closed without merging**
