### PR TITLE
ResourceManager shouldn't depends on IHttpContextAccessor

### LINKED ISSUE #2894: ResourceManager should not depend on IHttpContextAccessor
Right now it requires to be executed from an ASP.NET request because of that.

- `RegisterUrl(string resourceType, string resourcePath, string resourceDebugPath, string relativeFromPath)` should use `relativeFromPath` instead of `Request.PathBase`. 
- The default value for `relativeFromPath` should be defined using an option

When configured from an ASP.NET we can then use the `PathBase` as the default value for the option

### PR DESCRIPTION
**Pull request by hishamco**
Fixes #2894

### CODE REVIEW

**Comment by hishamco** [comment]
Your thoughts @sebastienros

**Comment by hishamco** [comment]
@jtkech is changes fine for you, before I resolve the conflict

**Comment by jtkech** [comment]
Hmm i was just thinking about the fact that we can compose and then use a tenant in the context of another tenant, so maybe better to use our `ShellContextFeature` (see in the media module startup how it is used) with something like this.

    var feature = httpContextAccessor.HttpContext?.Features.Get<ShellContextFeature>();

    var pathBase = feature?.OriginalPathBase ?? null;
    PathString prefix = "/" + feature?.ShellContext.Settings.RequestUrlPrefix;
    var resourcePath = (pathBase + prefix).ToString().TrimEnd('/');

But it's just for info because here maybe not so useful, it would be for rendering something for a given tenant in the context of another one, and at least it will work as before.

So LGTM

Seems that you just have to **add the registration of this `IConfigureOptions<>` as a transient service** as we do for other ones.

**Comment by hishamco** [comment]
Why I need to register `IConfigureOptions<>`?

**Comment by jtkech** [comment]
Oh sorry, i'm stupid, this options class was already existing and registered in the `OC.Resources` startup.

**Comment by hishamco** [comment]
So, I resolve the conflict right now, make it ready to merge

**Comment by hishamco** [comment]
@sebastienros it is ready for merge

**Comment by sebastienros** [comment]
Replaced by https://github.com/OrchardCMS/OrchardCore/pull/4120

**Pull request closed without merging**
