### PR TITLE
Code format

### PR DESCRIPTION
**Pull request by hishamco**

### CODE REVIEW

**Comment by hishamco** [comment]
Seems the current code-base needs format, if this something we will accept I will try to fix the current issues

**Review by Piedone — CHANGES_REQUESTED** [review]
I don't think this is a good approach to ensure consistent formatting: https://github.com/OrchardCMS/OrchardCore/pull/12235#pullrequestreview-1934966254

**Comment by hishamco** [comment]
IMHO this is a good thing, I notice many PRs have format issues, at least this is sort of guard :) I remember seeing something similar in Garnet repo, which is useful to make the code consistent

**Comment by Piedone** [comment]
I stand by what I've written under the link.

**Comment by hishamco** [comment]
@Piedone if this would be a part of code analysis then I will close this, or let us accept this for now until the #7950 has been fixed

**Comment by Piedone** [comment]
This should be done together with code analysis, I think, yes. Without it, it'll only bring confusion. We also need to consciously specify the formatting rules in the .editorconfig first, and apply them throughout the whole codebase before the CI build can verify it.

**Comment by hishamco** [comment]
@Piedone is this something we want to accept, or it's addressed somewhere else?

**Comment by Piedone** [comment]
I still don't think this is a good approach, see my comments above, so it's a no from me.

**Pull request closed without merging**
