### PR TITLE
Content filters

### LINKED ISSUE #1189: Filter and Saved Filters needed to manage content
- At minimum people should be able to filter by content type
- Filter by author would be nice
- Filter by published/draft status would be grand
- Filter by date created/published in range would be amazing
- Sort by last updated asc/desc
- Search by title is needed
- Being able to saved filters and have it readily available would be awesome

filter-needed

### PR DESCRIPTION
**Pull request by agriffard**
Fixes #1189, #1862

Allow to filter the content items on content type, published version, order by date.
Display content type in Summary Admin

### CODE REVIEW

**Comment by agriffard** [comment]
Inspired by @siyamandayubi 's PR #1899

**Comment by siyamandayubi** [comment]
Much better!

**Comment by sebastienros** [comment]
@siyamandayubi when you say "much better" does it mean your PR becomes useless after that? Or are they complementary?

**Comment by agriffard** [comment]
@siyamandayubi 's PR only filters on content type. 
This one also filters on content version status, order by dates and displays content type in summary.

So yes, I guess his PR can be closed.

**Comment by siyamandayubi** [comment]
yep, my PR can be closed as it contains filter by ContentType as well as by version, status etc.

**Pull request merged**
