### PR TITLE
Change the Script Task use Monaco Editor

### PR DESCRIPTION
**Pull request by hyzx86**
image

### CODE REVIEW

**Comment by deanmarcussen** [comment]
I don't get it. On a previous pr you are introducing the codemirror editor, then here the monaco editor?

**Comment by hyzx86** [comment]
Previous PR was primarily about fixing bugs, and I'm not sure how many workflow activities require the JavaScript editor, which I personally think is necessary to update scripting tasks, which are more commonly used after all.

**Review by deanmarcussen — APPROVED** [review]

**Comment by deanmarcussen** [comment]
Anyone have any objections to this, or I will merge it?

**Comment by MichaelPetrinolis** [comment]
I think it's cool to have the monaco javascript editor here. In a next PR we could extend the editor's intellisense with the workflow context.

**Comment by giannik** [comment]
Please commit.

**Pull request merged**
