### PR TITLE
Change models namespace everywhere

### PR DESCRIPTION
**Pull request by hishamco**

### CODE REVIEW

**Comment by sebastienros** [comment]
If we do it we need to do it for all the modules. And before RC because this is a breaking change.

**Comment by hishamco** [comment]
> If we do it we need to do it for all the modules. And before RC because this is a breaking change.

No problem, I will scan `Models` everywhere ..

**Comment by hishamco** [comment]
> And before RC because this is a breaking change

Is breaking considered before 1.0.0?!!

**Comment by hishamco** [comment]
Done!!

**Comment by hishamco** [comment]
Done!!

**Comment by hishamco** [comment]
:shipit:

**Pull request merged**
