### PR TITLE
Simplify email body

### LINKED ISSUE #13425: Mail body needs to be simplified
### Is your feature request related to a problem? Please describe.

Nowadays, when you trying to create an email message you should set either `Body` or `BodyText`, not only that you also need to set another property `IsBodyHtml` or `IsBodyText` I think the reason at the time was to map these properties to MailKit APIs, but this need simplification to make the setup easier, not only that, if someone set `IsBodyText` to `true` while the he/she sets the `Body` property, the email will sent as plain text.

### Describe the solution you'd like

Deprecated `BodyText`, so `Body` should be the content for the mail message, also we can introduce `IsHtmlBody` to determine the type of the body message HTML / Plaintext

### PR DESCRIPTION
**Pull request by hishamco**
Fixes #13425

### CODE REVIEW

**Review by sebastienros — APPROVED** [review]

**Comment by MikeKry** [comment]
@hishamco / @sebastienros 

I just came across this change after updating OC. May I ask why did we change this logic? Right now we are unable to send both html version and plain text version in one email - that is imo step in wrong direction. It should be both supported, not exclusively html / plain text.

**Comment by hishamco** [comment]
@MikeKry can you clarify how a single email could be send in two different formats?!!

**Comment by Mike4tel** [comment]
@hishamco well, I believe that it was working all the time before like that :) look up multipart mime type for emails. It is common practice to send both variants of email. 1) it is more likely to pass through spam filters 2) there are still mail clients and users that prefer plain text.

**Comment by Mike4tel** [comment]
@hishamco for example here: https://help.emarsys.com/hc/en-us/articles/360016272317-Best-practices-Email-size-and-multipart-messages
look for multipart message

**Comment by hishamco** [comment]
@Mike it depends on the mail software, but while it was supported before I'm going to allow it again

**Comment by hishamco** [comment]
FYI #14715

**Pull request merged**
