### PR TITLE
Add extensions to register conditions in the Rules module

### PR DESCRIPTION
**Pull request by MikeAlhayek**
Here is a summary of the changes:
 - Added new `OrchardCore.Rules.Core` project.
 - Added the new `AddRule<>` extensions in the Core project
 - Cleaned up the  `OrchardCore.Rules` project by using the new extensions.

### CODE REVIEW

**Comment by hishamco** [comment]
> This is not breaking

It's a binary-breaking change

**Comment by MikeAlhayek** [comment]
@hishamco 
OC.Rules depends on OC.Rules.Core so if someone already depend on OC.Rules, they they'll have access to everything in OC.Rules.Core so it won't have any compile or run time errors. So it should not be breaking anyone

**Comment by hishamco** [comment]
> OC.Rules.Core so it won't have any compile or run time errors.

I know what you mean, but while you changed the assembly it considered a binary breaking change, anyhow while we accept the breaking changes in minor releases it's not a problem

Again can we prevent breaking changes in minor release coz sometimes accepts and sometimes not :)

**Comment by MikeAlhayek** [comment]
@hishamco the only thing that would break is moving the rules to a different project because YesSQL stores the assembly name in the database when it is stored. So I am moving the models back to make sure Yessql won't have serialization problem.

**Review by MikeAlhayek — COMMENTED** [review]
Cleanup

**Pull request merged**
