### PR TITLE
New Admin menu

### LINKED ISSUE #4582: Rename Assets
AFAIK "Assets" is a generic terminology used for scripts, styles, images .. etc, IMHO Media or Media Library is more clear than assets, and it has been used while for many CMSs

/cc @agriffard @Skrypt @sebastienros

### PR DESCRIPTION
**Pull request by agriffard**
Fixes #4582, #4288

Here are the new main sections ('Article' is a custom admin menu) :

image

### CODE REVIEW

**Comment by hishamco** [comment]
Display -> Design or Appearance

**Comment by agriffard** [comment]
Do not merge it, there is still many things to discuss. 
Will probably do a demo on Tuesday.

**Comment by Skrypt** [comment]
Ok

**Comment by agriffard** [comment]
Here is the current admin menu when all features are enabled:

image

**Comment by agriffard** [comment]
My arguments for the new admin menu are: 
- Let's have main admin menus that are related to the Key Topics of the new documentation structure #4514
- If a menu only has 1 or 2 sub items, they could appear in another section.
- If a menu has too much items, let's split them in other menus. 
- Let's have menu labels that are easily understandable (Assets => Media Library)

Number of 1st level menus:
- Current: 12
- New: 8-9 (depends if we put `New` in `Content`)

Number of sub menus per parent:
**Current:**
- Content: 2
- Content Definition: 2
- Configuration: 15
- Themes: 1
- Workflows: 1
- Each External Service: 1+

**New:**
- Content: 4
- Design: 5
- Configuration: 10
- Search: 3
- Security: 5
- Workflows: 1

Other possible menus:
`Social` Menu (or a name related to the External services) that would contain the features related to Facebook SDK, Google Analytics could be create.
`Tools` Menu with the Import/Export, Recipes, Background tasks and Settings like Reverse Proxy and Smtp
`Api` (or label related to 'Data exposition') with GraphQl and OpenId

**Comment by agriffard** [comment]
We even talked about allowing users to 'pin menu items' in this meeting: https://youtu.be/fOZGjZUcl00?list=PLuskKJW0FhJfOAN3dL0Y0KBMdG1pKESVn&t=2938

Ultimately, one of the conclusions was:

> Provide configuration driven menu items so that an app can reorganize the menu items that the modules provide

It was one of the goal of the customizable 'admin menu' feature but it is at the same time more powerful because you can add dynamic items (ListPart) but also, for the existing menus, it is just a way to clone them and put them elsewhere in the menu and specify an icon.

**Comment by agriffard** [comment]
We talked about the new menu structure during the last meeting: https://youtu.be/XJQsavmzKqo?t=1281

Nothing more to add to this PR.

**Pull request merged**
