### PR TITLE
Isolate Tenant data into multiple REDIS databases

### LINKED ISSUE #13211: Allowing creating multiple REDIS databases and support liquid in instance prefix
### Is your feature request related to a problem? Please describe.
Currently, we seems to be using a single REDIS database for all tenants. https://github.com/OrchardCMS/OrchardCore/blob/339d74b251b53393dd510f8ad3027aa17d78500d/src/OrchardCore.Modules/OrchardCore.Redis/Services/RedisService.cs#L46

I think we should do tenant level data isolation here. Instead of calling `Database = Connection.GetDatabase();` we should pass the serial number of each tenant to `Database = Connection.GetDatabase(NumericTenantId);` this way each tenant can use their own database for caching instead of using a shared database for the entire app. 

Additionally, it would be nice to add liquid support for the `InstancePrefix` so if a user want to use liquid to build the prefix like `prod-{{ ShellSettings.Name }}` or `testing-{{ ShellSettings.Name }}`

### PR DESCRIPTION
**Pull request by MikeAlhayek**
Fix #13211

### CODE REVIEW

**Comment by jtkech** [comment]
Yes good idea, we already thought about this

But the problem is that `StackExchangeRedis.RedisCache` doesn't expose this option https://github.com/dotnet/aspnetcore/blob/2cd5873673d6c9858625baf80730507e428a6bad/src/Caching/StackExchangeRedis/src/RedisCache.cs#L275, but we still decided to use this ootb implementation.

So all our shared Documents will be still cached in the same Redis database, we would need to implement our own Redis Cache. So only the RedisLock and RedisTagCache would use a different database.

Also using the `_shellDescriptor.SerialNumber` as a db number may not differentiate tenants that may have the same SerialNumber integer value.

And as I remember the max database instances is limited to 16.

**Comment by MikeAlhayek** [comment]
Hummmm,maybe we need to rename the SerialNumber property if that isn't a unique number each tenant. Maybe we can create an algorithm that would return a unique int from the tenant name. 

That Cache implementation would be a problem in this case. Not sure why it does not support multiple databases

**Comment by jtkech** [comment]
Yes, the serial number is an incremental "version" used by a given tenant but not accross tenants.

We planned to introduce an unique TenantId, see #12980 but still not an integer.

Anyway the number of Redis databases is limited to 16.

We could think about grouping tenants, each tenant of the same group sharing the same database.

But for now still the limitation of the RedisCache always using the same default database.

**Comment by MikeAlhayek** [comment]
Maybe our best bet for now to to user tenant name as the prefix. I know we manually prepend the tenant name when creating the cache key. But I think the tenant name should be part of the service settings

**Pull request closed without merging**
