### PR TITLE
Prevent showing all tenants in OpenID scopes if not default tenant

### LINKED ISSUE #12722: Remove tenants as scope from OrchardCore.OpenId.Management feature when it's not running in the default tenant
### Is your feature request related to a problem? Please describe.
The feature "OrchardCore.OpenId.Management" allows adding, editing and removing the registered applications. Also, this module is allowed for any tenant to be able to use as it should. However, when you go to Scopes ends point which is part of the feature, you get a list of all running tenants even when you are not the default tenant. I think this is wrong. Its okay for a default tenants to see a list of all running tenants and add scope to different tenants. But I don't think we should allow a subtenant to add scope to other tenants.

### Describe the solution you'd like
Maybe we should [change the line] (https://github.com/OrchardCMS/OrchardCore/blob/6e3203e084c8a7091228c58be8367a74b5bd88bc/src/OrchardCore.Modules/OrchardCore.OpenId/Controllers/ScopeController.cs#L183) to something like this instead

```C#
var model = new CreateOpenIdScopeViewModel();

if (_shellSettings.IsDefaultShell())
{
    foreach (var tenant in _shellHost.GetAllSettings().Where(s => s.State == TenantState.Running))
    {
        model.Tenants.Add(new CreateOpenIdScopeViewModel.TenantEntry
        {
            Current = String.Equals(tenant.Name, _shellSettings.Name),
            Name = tenant.Name
        });
    }
}
else
{
    model.Tenants.Add(new CreateOpenIdScopeViewModel.TenantEntry
    {
        Current = String.Equals(_shellSettings.Name, _shellSettings.Name),
        Name = _shellSettings.Name
    });
}
```

### PR DESCRIPTION
**Pull request by MikeAlhayek**
Fix #12722

### CODE REVIEW

**Review by kevinchalet — CHANGES_REQUESTED** [review]
4 remarks:

  - It's going to be an important breaking change. It will likely deserve an announcement to inform folks they'll no longer be able to create scopes for tenants when the server is not in the default tenant.

  - It's not clear what the migration path for existing applications is. AFAICT, existing tenants will remain listed as valid resources until a scope is updated, but there's no indication it will break things.

  - I don't see code that would prevent a malicious user from selecting a tenant that is not listed (e.g by modifying the HTML source or by sending a HTTP request manually). If security or privacy is your main motivation for changing this feature, proper checks will need to be implemented.

  - AFAICT, the validation part - that is linked to the feature you're updating - is not covered: https://github.com/OrchardCMS/OrchardCore/blob/009daa30af536801583ec423a9f7d4c9ab7c2c70/src/OrchardCore.Modules/OrchardCore.OpenId/Drivers/OpenIdValidationSettingsDisplayDriver.cs#L23-L51

**Comment by MikeAlhayek** [comment]
> 4 remarks:
> 
>     * It's going to be an important breaking change. It will likely deserve an announcement to inform folks they'll no longer be able to create scopes for tenants when the server is not in the default tenant.
> 
>     * It's not clear what the migration path for existing applications is. AFAICT, existing tenants will remain listed as valid resources until a scope is updated, but there's no indication it will break things.
> 
>     * I don't see code that would prevent a malicious user from selecting a tenant that is not listed (e.g by modifying the HTML source or by sending a HTTP request manually). If security or privacy is your main motivation for changing this feature, proper checks will need to be implemented.
> 
>     * AFAICT, the validation part - that is linked to the feature you're updating - is not covered: https://github.com/OrchardCMS/OrchardCore/blob/009daa30af536801583ec423a9f7d4c9ab7c2c70/src/OrchardCore.Modules/OrchardCore.OpenId/Drivers/OpenIdValidationSettingsDisplayDriver.cs#L23-L51

@kevinchalet thanks for your feedback. As per the discussion in the issue, we did not want to change the UI "which is one the tenant can see their own tenant".

The main idea here is to listing listing other tenants to the default tenant only. If someone is using other tenants, they should consider moving the server to the default tenant.

I will label this PR as a breaking change for awareness. and I'll document the change in the change logs as well.

**Comment by jtkech** [comment]
Copy paste of my comment in the related issue

When I said that there is no other component listing other tenants, I didn't say that it is good or not ;)

As said by @kevinchalet maybe we are missing cross tenants permissions, maybe harder at the beginning but would prevent to change the behavior of tenants depending on being the Default tenant or not.

Yes, for me basically there is neither host tenant nor parent/childs tenants. Maybe OC would need to be a standalone application to manage tenants without a Default tenant, and being able to define groups. Or as it is currently, allow some way to define tenants groups, e.g. based on their enabled features.

But yes maybe too late and I'm not against the direction we are taking, I think @kevinchalet is best placed to see with @sebastienros if we're on the right path.

That said as I remember there is one place where we list tenants but only those having the openId server feature enabled, maybe here we could use the same kind of filtering.

**Comment by Piedone** [comment]
Is this something you'd like to revisit any time soon @MikeAlhayek or should we close?

**Comment by MikeAlhayek** [comment]
@Piedone I fixed the conflict for now. I'll try to find time to revisit it.

**Comment by Piedone** [comment]
Great, thank you!

**Comment by hishamco** [comment]
There's another conflict :)

**Comment by MikeAlhayek** [comment]
@kevinchalet I still think this is an important change to take. I just don't think exposing a list of tenants to other tenants is a good ideas. Tenants should not be aware of each other at all. At the same time. I don't want to keep resolving merge conflicts :)

Can you please revisit this PR and provide an update thoughts if we should or not proceed with this PR?

**Comment by kevinchalet** [comment]
> Can you please revisit this PR and provide an update thoughts if we should or not proceed with this PR?

I have no strong objection: the lack of reactions in https://github.com/OrchardCMS/OrchardCore/issues/12722 tends to indicate that a limited set of users would be affected so I guess removing this feature wouldn't be a huge deal.

That said, I don't think any of the concerns listed in https://github.com/OrchardCMS/OrchardCore/pull/12974#pullrequestreview-1253965984 has been addressed in this PR (the first bullet can be of course done a posteriori, but the other ones should be covered in this PR, specially since it's motivated by security/privacy reasons).

**Comment by sebastienros** [comment]
If there is no way to select a tenant anymore, then the whole controller/views is useless for a tenant, it could just be totally hidden. What about tenants could be identified secretly, through a cryptographic identifier (that could be regenerated at will) and let users put a value in a textbox instead. This would mean they would have to be given the key to identity a tenant.

We could disable this feature right now and then implement the secret way later.

**Pull request closed without merging**
