### PR TITLE
Lucene query docs, fixing QueryStringQueryProvider (Lombiq Technologies: OCORE-93)

### LINKED ISSUE #11560: Parsed Lucene query provider
### Is your feature request related to a problem? Please describe.
You can write elaborate [Lucene Queries](https://docs.orchardcore.net/en/latest/docs/reference/modules/Lucene/#lucene-queries) with the ElasticSearch DSL. This includes the `match` query type (akin to using the `my search term` syntax in the search box) and `match_all` (like writing `"my search term"` for exact search). And you can optionally use the parsed Lucene search syntax in the search text box. However, you can't combine the two, you can't add the ability to use the search syntax with a Query.

### Describe the solution you'd like
Add an `ILuceneQueryProvider` to address this.

### Describe alternatives you've considered
You can use simple search but then you loose out on Queries.

### PR DESCRIPTION
**Pull request by Piedone**
Fixes #11560.

This contribution is sponsored by the [City of Santa Monica](https://santamonica.gov/).

### CODE REVIEW

**Comment by Skrypt** [comment]
Ok, I need to review both of these first : 

https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html
https://lucene.apache.org/core/2_9_4/queryparsersyntax.html

Need to see if the first one is equivalent or not. Else, we need to try to follow ElasticSearch documentation/implementation.

Else, good work. 😄

**Comment by Piedone** [comment]
While I didn't know about it up until now, this is pretty much a simplified Query string query indeed.

Thanks :).

**Comment by Piedone** [comment]
Updated according to what was discussed under the issue.

**Review by Skrypt — APPROVED** [review]
All good to me. We should take a second look at the MultiFieldParser later on if it is required but I believe that the SimpleQueryStringQuery should cover that use case.

**Pull request merged**
