### PR TITLE
Add missing Html and Title dependencies to Admin Dashboard (Lombiq Technologies: OCORE-59)

### PR DESCRIPTION
**Pull request by Piedone**
Otherwise you have to manually enable these features to see the Dashboard working.

### CODE REVIEW

**Comment by jtkech** [comment]
@Piedone 

Yes i agree, this migration adds implicit dependencies on `OC.Html` and `OC.Title`, so would be better to add them in the manifest instead. But i think it is not intended that `OC.AdminDashboard` depends on these features.

Note: Not so important but those that already have run this migration recipe will not have these deps enabled.

So, one solution would be to have a separate `OC.AdminDashboard.Widgets` feature that would depend on `OC.Html` and `OC.Title` and that would register this migration (and decorate it with the `[Feature()]` attribute). Hmm, I thought about only having a specific startup decorated with the `[RequireFeatures("OC.Html", "OC.Title")]` attribute and that would register this migration, but a migration need to be tied to a feature.

Hmm, still one problem for existing sites that already have run the old migration.

**Comment by Piedone** [comment]
While the problem will exist for existing sites I'd argue that those people figured out the issue already. If they're affected that is because the Html and Title features are widely used and most possibly already enabled in the majority of installations (I only noticed this because by chance I played around with the feature after setting up the site with the Blank recipe).

I'd have added these as dependencies to the Manifest but I thought the original intent with the recipe (instead of doing the same things from a migration directly) was to be get a default configuration but be able to deviate from it. E.g. you get HtmlDashboardWidget with the Title and Html Body Parts but if you want, you can delete it and disable the Title and Html features and have your own Dashboard Widgets.

**Comment by jtkech** [comment]
@Piedone 

> I thought the original intent with the recipe (instead of doing the same things from a migration directly) was to be get a default configuration but be able to deviate from it.

Yes, good idea to have a separate recipe and to be able to deviate from it. But currently this is a **migration** recipe that is already called by the main migrations of the module.

https://github.com/OrchardCMS/OrchardCore/blob/212980eefdd3698b3bd1a5e44ba2d0688278d08a/src/OrchardCore.Modules/OrchardCore.AdminDashboard/Migrations.cs#L39

- So, good idea to have a recipe that you could execute or not through the admin, but not called by the migrations.

- Or a separate feature depending on `.AdminDashboard`, `.Html` and `.Title`, and defining migrations that call it.

Anyway i'm fine with it, so if you think it is not worth to do, i will approve it anyway ;)

**Comment by Piedone** [comment]
Well yeah but the recipe was already there so I just went with it :). I'm also just speculating what the original intent of it was, being it a migration recipe so I'm unsure about making it into a manually executable recipe. @agriffard since you created it, can you shed some light on the reason behind using a migration recipe?

**Comment by deanmarcussen** [comment]
I think its fine @jtkech 

Potentially nice to have a feature with recipes at another point - re : https://github.com/OrchardCMS/OrchardCore/issues/9111

but for this existing migration, making sure the features are enabled (even if it's implicit), and they can delete the types / content at later point seems ok to me

**Comment by jtkech** [comment]
Okay cool then, so as said

> Anyway i'm fine with it, so if you think it is not worth to do, i will approve it anyway ;)

I will approve it

**Review by jtkech — APPROVED** [review]

**Pull request merged**
