### PR TITLE
Fix Trumbowyg: Missing Shortcodes icon

### LINKED ISSUE #9696: Trumbowyg: Missing Shortcodes icon
image

The Shortcodes button icon is not displayed with the latest changes in Trumbowyg.

@deanmarcussen : Do you remember where the css/icon is coming from?

### PR DESCRIPTION
**Pull request by Skrypt**
Fixes #9696

### CODE REVIEW

**Comment by agriffard** [comment]
It does not work for me in a tenant.

The code generates:
`$.trumbowyg.svgPath = '/mytenant/OrchardCore.Resources/Styles/ui/icons.svg';`

**Comment by agriffard** [comment]
I am using an HtmlBodyPart, btw.

**Comment by Skrypt** [comment]
Yeah we have also this line in HtmlBodyPart-Trumbowyg.Edit.cshtml

**Comment by Skrypt** [comment]
Strange because it works for me : 

image

**Comment by agriffard** [comment]
It is maybe caused by my Windows Update problem.

**Comment by Skrypt** [comment]
image

**Pull request merged**
