### PR TITLE
Cleanup GraphQL Localization

### PR DESCRIPTION
**Pull request by MikeAlhayek**

### CODE REVIEW

**Comment by gvkries** [comment]
I'm not sure if we should do this, after all the discussions about breaking changes lately. The `where types` can be used directly, even if it is not the case in OC itself. Also, I don't see anything that could be made abstract in the base classes. So I don't see enough advantage of introducing another breaking change.

Anyway, if we do it, the c'tors should be protected.

P.S.: The PR description is misleading, why is it related to localization?

**Review by gvkries — APPROVED** [review]
Oh, I added that parameter, I forgot about it. Than it's already a breaking change introduced by myself. We could either fix that or you can go ahead, I'm fine with whatever you want.

**Comment by MikeAlhayek** [comment]
> We could either fix that or you can go ahead

That is what this PR fixes. Do you see something else that I missed?

**Comment by gvkries** [comment]
> > We could either fix that or you can go ahead
> 
> That is what this PR fixes. Do you see something else that I missed?

My change is still a breaking one after this PR, because the parameter less c'tor is missing. I mean we can either make the string localizer optional with a default one so my change is not breaking anymore, or go ahead and formalize the actual intent of these classes being base classes. That's how I understand your change. Isn't that correct?

**Pull request merged**
