### PR TITLE
Rename "design" to "configuration"

### PR DESCRIPTION
**Pull request by sfmskywalker**
I think the term "Design" for the admin menu item from which you can control things like Settings, Security, Tenants and Modules isn't very intuitive. "Configuration" seems to be a better term in my opinion.

I created a PR ahead of approval/rejection so that it's easy to merge in case others agree.

image

### CODE REVIEW

**Comment by sebastienros** [comment]
We'll discuss it during next meeting. I am not opposed to changing it, but it had been decided otherwise in a previous meeting (that I can find, it's in my notes)

**Comment by agriffard** [comment]
As Sipke suggests, I also prefer 'Configuration'.

There are other changes I'd like to see: 
- Put the Themes in this menu, below Modules.
- Reorder some sub menus, like Tenants, putting it at the end.
- I never understood why the Lucene queries and indices was in a Site menu. I would call it 'Search'.

**Comment by sebastienros** [comment]
Meeting: 9/13/2016 https://www.youtube.com/watch?v=fOZGjZUcl00&index=50&list=PLuskKJW0FhJfOAN3dL0Y0KBMdG1pKESVn

**Comment by agriffard** [comment]
I watched the video and I found the culprit ;-) : Bertrand suggested 'Design' and Sebastien just said "Let's keep this for the moment".

I still prefer 'Configuration'.

**Comment by hishamco** [comment]
IMHO the `Design should be there, alongside we can add `Configuration` or `Settings` menu as the following:

- Design

     - Layers
    - Templates
    - Themes

- Settings

     - Basic Settings (General)
    - Advance Settings

if you look closely the layer, templates and themes are design related while the others may belong to configurations

Also I'm a fan to separate the `Security` as new menu item

**Comment by sebastienros** [comment]
Design doesn't mean UI in this case, more like Software Design.

**Comment by hishamco** [comment]
But in almost CMSs that I ever seen, design focus on the UI parts, so that's why I group them the UI together, and most of the things inside the actual `Design` menu item is belong to configuration or settings

**Comment by PinpointTownes** [comment]
@sebastienros what's the final call concerning this PR? I think most of us agree to say that `Design` is a very confusing name for what's actually a configuration menu.

**Comment by sfmskywalker** [comment]
On last week's call we voted to do the rename to **Configuration**. @sebastienros you asked me to redo this PR since it looked like it included more changes than necessary (probably due to merge). However, after closer inspection, all of the changes in this PR are relevant to changing from "Design" to "Configuration". I didn't rename just the label, but also relevant file names, CSS classes, etc.

**Comment by PinpointTownes** [comment]
@sfmskywalker shouldn't this PR be merged into `dev` rather than `master`?

**Comment by sfmskywalker** [comment]
Yes, thank you :)

**Pull request merged**
