### PR TITLE
Fix GraphQL dynamic field conflicts

### PR DESCRIPTION
**Pull request by deanmarcussen**
Fixes https://github.com/OrchardCMS/OrchardCore/issues/5536

Caught me again today, so time to have a crack at it.

@carlwoodhouse not especially my area, but best I can tell it fixes it.

Can now add dynamic fields, to anything that has been preregistered by another builder.

### CODE REVIEW

**Comment by carlwoodhouse** [comment]
LGTM - might be an idea to supplement with some tests though ?

**Review by carlwoodhouse — COMMENTED** [review]
LGTM - might be an idea to supplement with some tests though

**Comment by Skrypt** [comment]
I don't think unit tests are worth it if we move to Hot Chocolate later on.

**Comment by carlwoodhouse** [comment]
Maybe not ... but you’d still want to test that scenario; regardless of the implementation

**Comment by carlwoodhouse** [comment]
I’m happy for it to go as it is btw; as in the current state it’s broken anyway !

**Comment by Skrypt** [comment]
I agree that it needs unit test but let's merge it and create an issue to create a unit test.

**Review by Skrypt — APPROVED** [review]

**Review by carlwoodhouse — APPROVED** [review]

**Pull request merged**
