### PR TITLE
Upgrade Fluid to 2.0.0-beta-1001

### PR DESCRIPTION
**Pull request by hishamco**

### CODE REVIEW

**Comment by hishamco** [comment]
Seems it needs to remove Irony dependency

**Comment by sebastienros** [comment]
Please do not merge until it has been tested with most views, even though all fluid tests pass, there are many more cases in OC that might trigger issues. Found one just by picking the first liquid template I could find in OC.
And also run the functional tests manually, as it will hit multiple pages.

**Comment by hishamco** [comment]
That's why I told you yesterday I need to test few cases .. This may need to be tested by the team if it is done .. after we sure there's no bugs we can merge

**Comment by sebastienros** [comment]
Can you try to fix the build so I can see if something is missing in v2?

**Comment by hishamco** [comment]
Sure, I will try to continue on this PR after an hour, one more thing how we can pass `FilterArgument[]`, I didn't find overload to pass such type. I will struggle to make this pass

**Comment by sebastienros** [comment]
I am working on it. The migration is not easy, and requires some work in Fluid.

**Comment by hishamco** [comment]
> I am working on it. The migration is not easy, and requires some work in Fluid.

Ok, it's in your plate now .. I was busy with the SQL Parser, BTW I have some feedback to Parlot, I will share it ASAP on its repo

**Comment by hishamco** [comment]
Replaced by #8424

**Pull request closed without merging**
