### PR TITLE
Content Items List : fix form post confirmation issue

### LINKED ISSUE #3612: Content Items List : form post confirmation issue
This isssue appears when using history back and when you have filtered content items previouly in that list.

image

### PR DESCRIPTION
**Pull request by Skrypt**
orchard

I know I did some styling on the bulk actions controls too but they still don't work. I will comment it out for this PR.

Fixes #3612

### CODE REVIEW

**Comment by Skrypt** [comment]
After testing more I found out that this breaks the "Show" and "Sort by" filters. Need to fix it first.

**Comment by Skrypt** [comment]
This will never work that way. 

```C#
return RedirectToAction("List", new RouteValueDictionary(model.Options));
```

This is my latest version and seems like Complex model binding doesn't work with RedirectToAction.

**Comment by Skrypt** [comment]
It works now. Please review and let me know if I did something wrong.

**Comment by Skrypt** [comment]
I need to read about this : https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/custom-model-binding?view=aspnetcore-2.2

**Comment by Skrypt** [comment]
This works now if I'm using `TempData["request"] = Newtonsoft.Json.JsonConvert.SerializeObject(model)`. I'm passing the model as a jsonObject and I'm deserializing it as a ListContentsViewModel wich now will replace the model binding. I tried passing a ListContentsViewModel directly to the `RedirectToAction("List", viewModel);` but the model binding doesn't work with viewModel.Options.

**Comment by Skrypt** [comment]
To be honest the ViewModel is quite a mess here ; it has a lot of code that is not used anymore and there's a good cleanup required on both the View and the ViewModel. Though, even if the code is all messy it shows that using a TempData instead of the model binding it works.

**Comment by Skrypt** [comment]
Ok, I made a lot of cleanup in that code. Now it works with model binding only.

**Comment by sebastienros** [comment]
Should I add a double ready tag?

**Comment by Skrypt** [comment]
Yeah, that's a shame I found one after 😜

**Pull request merged**
