### PR TITLE
Fixes #9269 release view buffer at the end of scope

### LINKED ISSUE #9269: "Buffer has already been rendered" exception
I have a `Menu.liquid` where we render the Items in two different lists.
```
  {% for item in Model.Items %}
      {{ item | shape_render }}
  {% endfor %}

.....
  {% for item in Model.Items %}
      {{ item | shape_render }}
  {% endfor %}
```

This exception occurs. Removing the second for loop fixes the issue.

image

As requested, moved the issue from https://github.com/sebastienros/fluid/issues/318

### PR DESCRIPTION
**Pull request by jtkech**
Fixes #9269

### CODE REVIEW

**Comment by jtkech** [comment]
Marked as not ready as it is just a first draft for testing

It works well but I need to think about the case an exception is thrown

I have ideas, will work on it this night

**Comment by jtkech** [comment]
@jptissot 

If you have time, can you try it to see if it fixes your issue?

**Comment by jptissot** [comment]
@jtkech I tested with rendering the same menu items twice and no exception was thrown.

**Comment by jtkech** [comment]
Okay cool, thanks

**Review by sebastienros — APPROVED** [review]

**Pull request merged**
