### PR TITLE
Only show fields in Summary and Detail display types

### PR DESCRIPTION
**Pull request by deanmarcussen**
Fixes https://github.com/OrchardCMS/OrchardCore/issues/3838 

and helps with https://github.com/OrchardCMS/OrchardCore/pull/4154

So a proposal only, but I go with the easy option : Always hide fields in `DetailAdmin` display type.

This stops them showing in the List view which is currently the only view making use of `DetailAdmin`

If someone wants a field to show in `DetailAdmin` or the List, then `placement.json` in any custom module will participate in placement for TheAdmin theme and the fields can be shown. (for me sometime I want them, they're useful as a header in a list container, but more often than not I don't want them, and it just looks weird when they show up by default).

Example placement that a custom module could use to override the driver setting and place a field. 

```
"TextField": [
    {
      "displayType": "DetailAdmin",
      "place": "Content"
    }
]
```

### CODE REVIEW

**Comment by hishamco** [comment]
Yesterday I was chatting with @sebastienros on Gitter and he suggested two ways, probably we may discussed in the upcoming meeting, but if this PR is fine for Seb the PR #4154 is ready

**Comment by jptissot** [comment]
I saw the same issue when creating a reusable part. The part would render in the ContentItem list (SummaryAdmin).

**Comment by sebastienros** [comment]
About your comment in the content items coordinator that defines the default placement for part in `Content`. Would it be easier to do the same thing for fields, such that the field drivers would not have any `Location` by default, only if they need to change their default zones?

**Comment by jtkech** [comment]
> I saw the same issue when creating a reusable part. The part would render in the ContentItem list (SummaryAdmin).

Really, just retried, when going to the blog in `DetailAdmin` mode, a reusable part (here just composed of one text field) belonging to a blog post is not rendered. Here each blog post is rendered in `SummaryAdmin` mode.

Only a reusable part belonging to the blog is rendered.

So the "problem" is only related to `DetailAdmin`, not to `SummaryAdmin`.

see my [comment here](https://github.com/OrchardCMS/OrchardCore/pull/4192/files#r322436918)

**Comment by deanmarcussen** [comment]
> About your comment in the content items coordinator that defines the default placement for part in `Content`. Would it be easier to do the same thing for fields, such that the field drivers would not have any `Location` by default, only if they need to change their default zones?

The default placement for the dynamic part is in `Content` and the same technique is used for fields, e.g. `Content`. 

When `Content` is used as a placement strategy with no display type it means they always get placed the `Content` location for every display type.

So by default the fields are then excluded from `SummaryAdmin` by using `.Location("SummaryAdmin", "")`

This just proposes doing the same for `DetailAdmin` 

Potentially we could do this by default for anything placed in `Content` without a location (i.e. always exclude the two admin display types), it would be one change, but it is a lot less explicit, and I think it's probably more explicit to define this in the field drivers, but up to you?

Also noting that this only affects the `ListPart` as it is the only part that seems to use ` DetailAdmin` 

I think @jtkech you are right this is only about `DetailAdmin` and the `SummaryAdmin` comment might be a red herring. 

@jptissot maybe you could retry today with @jtkech merge on the reusable part and if you can still see it somewhere strange you could post an image?

**Comment by sebastienros** [comment]
This only affect DetailsAdmin probably because Summary doesn't render the Content zone. 

My comment was to show that we are doing things differently for parts and fields, and maybe the default zones should be defined the same way, in the coordinator. You disagree?

**Comment by deanmarcussen** [comment]
> This only affect DetailsAdmin probably because Summary doesn't render the Content zone.

> My comment was to show that we are doing things differently for parts and fields, and maybe the default zones should be defined the same way, in the coordinator. You disagree?

Coming back to this I have had a look and I can't see how to make setting the location in the coordinator work.

The default zones are available in the coordinator, but `Location` is not.

`Location` is a precursor to placement (i.e. default placement) and only the `DisplayDrivers` and `ShapeResult` are aware of the concept.

So I try a few things, this for example is possible in `ShapeResult.ApplyImplementationAsync`

```
            if (_otherLocations == null)
            {
                if (displayType == "SummaryAdmin" || displayType == "DetailAdmin")
                {
                    _defaultLocation = "";
                }
            }
            // Look for mapped display type locations
            else
            {
                string displayTypePlacement;
                if (_otherLocations.TryGetValue(displayType, out displayTypePlacement))
                {
                    _defaultLocation = displayTypePlacement;
                }
            }
```

Which will hide by default `SummaryAdmin`, and `DetailAdmin`, and works fine, noting that only the `Fields` use the `.Location("Content") option, which is only for a zone, in the display methods. (Other things, like deploymentsteps use `.Location("Content")`, but only in Edit, not Display.

But I didn't really like it, as it isn't so explicit in the drivers, so coming back to the comment that things are done differently for `Fields`, and `Parts` in their respective display drivers, I think maybe it is better to do things the same for both.

i.e. define a default location with a `DisplayType`, and a `Zone`, still knowing that placement can override these defaults.

So PR adapted to use this for all of the field drivers
```
            .Location("Detail", "Content")
            .Location("Summary", "Content");
```

One difference still remains, that no default position is set. Could also do that.

Easy to revert if the other option was preferred.

**Comment by agriffard** [comment]
Still needed to be merged.

**Comment by agriffard** [comment]
Can you please solve the conflict @deanmarcussen ?

**Comment by deanmarcussen** [comment]
Conflicts resolved @agriffard  **Note** @sebastienros probably needs to review if this is the right way of fixing the issue, as there were a few possibilities

**Pull request merged**
