### PR TITLE
Fix nuget restore issue for integration tests

### LINKED ISSUE #8465: All databases actions failing
https://github.com/OrchardCMS/OrchardCore/actions/runs/521424148

These fail to build because of an issue with nuget / debian based operating systems.
```
error NU3028: Package 'System.Collections.Immutable 1.5.0' from source 'https://api.nuget.org/v3/index.json': The repository countersignature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain 
```

I think this is due to the use of the  `image: cypress/included:6.0.0` https://github.com/OrchardCMS/OrchardCore/blob/4c71d093a728d726bea24e0024ad9b58a9749aa8/.github/workflows/functional_all_db.yml#L13

This image uses : the `node:12.18.3-buster` image as a base https://github.com/cypress-io/cypress-docker-images/blob/master/base/12.18.3/Dockerfile#L8 

Related to https://github.com/NuGet/Home/issues/10491

### PR DESCRIPTION
**Pull request by jptissot**
fix #8465

### CODE REVIEW

**Comment by jptissot** [comment]
Ok so this fixes the build issue, but a postgresql issue is there  for the ComingSoon theme. 

https://github.com/OrchardCMS/OrchardCore/actions/runs/548809043

**Comment by jptissot** [comment]
It seems like the Orchard logs still go to App_Data and not App_Data_Tests eventhough the app runs under App_Data_Tests.

**Comment by jptissot** [comment]
Ok, this fixes #8465 but it also shows that we have an issue with postgresql (#8545)
https://github.com/OrchardCMS/OrchardCore/actions/runs/548869771

**Review by Skrypt — APPROVED** [review]

**Pull request merged**
