### PR TITLE
Async Initializations on tenant container creation

### PR DESCRIPTION
**Pull request by jtkech**
Usage

    services.Initialize(async sp =>
    {
        var store = sp.GetService<IStore>();
        if (store == null)
        {
            return;
        }

        await store.InitializeAsync();
        ...
    });

### CODE REVIEW

**Comment by MikeAlhayek** [comment]
@jtkech could be in a separate PR but the Elasticsearch service configuration can use this too 
https://github.com/OrchardCMS/OrchardCore/blob/32ec37524757bac55a608741b9bdb8f5ead04b28/src/OrchardCore.Modules/OrchardCore.Search.Elasticsearch/Startup.cs#L122

**Comment by jtkech** [comment]
@MikeAlhayek 

Yes good idea, this is the goal to do such async init without having to define and register a service.

Hmm but in the above example, the `client.Ping()` in the startup is also used as a validation check before registering the related services, not saying it is good but for now if the ping throws these services are not registered, so I'm not against but here moving the ping to an init step would change the behavior.

**Comment by MikeAlhayek** [comment]
Yes I see that. I am not a fan of adding validation logic during registration. Maybe we should have another async method for validation? If validation fails, we don't call Initialize or ConfigureServices

**Comment by jtkech** [comment]
Yes I agree, hmm but we could not register async validations in the DI if intended to be executed before `ConfigureServices()`, or integrate them in `IStartup` that are resolved differently, as I first did in another PR for initializations. Hmm maybe in that case better to only use the async initialize pattern that we could use to initialize a given main service that would do the async checking and then put itself in a given state if it fails, other related services being able to check this state from this main service.

In fact what we can do with a `services.Initialize()` can be managed by a given service itself, e.g. with an `EnsureInitialisedAsync()` that does async things only if not yet initialized, but in that case most of the time we would also need to use some locking, which is not necessary if called once from a `services.Initialize()` knowing that building a tenant container is already done under an async lock.

But yes, maybe other scenarios to think about and support.

**Pull request merged**
