### PR TITLE
Add ~/Localization folder to ModularPoFileLocationProvider

### LINKED ISSUE #4014: [Question] about storage / Localization files
I am deploying an instance of OC on kubernetes. We currently do not plan on scaling across pods (low traffic site).
The `App_Data` folder is mounted to a persistent volume claim to persist the Tenants and Asset files created at runtime. 
Since the Localization folder is included in the docker image and is localed under `App_Data/Localization` it get's hidden when we mount the PV to App_Data.

Some options to consider: 
- have a script that will copy the Localization to the PV upon creation
- moving the `Localization` folder out of `App_Data`
- moving other `App_Data` files to another storage (blob) I think this is already possible ? This is overkill for our use case.

### PR DESCRIPTION
**Pull request by jptissot**
fixes #4014
Add additional search path that is outside of App_Data

### CODE REVIEW

**Comment by sebastienros** [comment]
1- In the issue we mention that we should probably only keep the localization in App_data for tenant specific files. Do you agree with removing all the other patterns from app_data then?
2- I like `App_Localization`, but how the PR is implemented is by reusing the same name under `App_Data`. So either we keep `Localization` or we special case is for under App_Data. At the same time it's not something that has to be backed up like App_Data, it's very static, like `wwwroot` so I am not sure we should do that. And also people would ask, why `App` before Localization ...

**Comment by jptissot** [comment]
> 1- In the issue we mention that we should probably only keep the localization in App_data for tenant specific files. Do you agree with removing all the other patterns from app_data then?

I agree if you are ok with it.

**Comment by sebastienros** [comment]
Do 1- then

**Comment by hishamco** [comment]
> And also people would ask, why App before Localization

Simply because it stores the localization for the current application, but if it's tenant specific `AppData/Localization` is a good choice

**Comment by sebastienros** [comment]
wwwroot store the static files for the current application, but the difference with App_data is that it's not part of the site's state.

I think we should keep `Localization`

**Pull request merged**
