### PR TITLE
Fix shortcode button with easy mde editor

### LINKED ISSUE #15738: Shortcode icon not aligned properly
image

image

@MikeAlhayek Here, found one.

### PR DESCRIPTION
**Pull request by Skrypt**
shortcode-button

Fixes #15738

### CODE REVIEW

**Review by MikeAlhayek — APPROVED** [review]
LGTM.

Suggestion: maybe it is better to put these 2 files in assets and add a task that would copy them over to the wwwroot file. I am not sure if it is a good idea to add the files directly to the wwwroot.

**Comment by Skrypt** [comment]
I will take a look but then we need to fix this in other places where we did the same too. I need to check if the wwwroot folder is added to the assembly or not else it's a none-issue.

**Comment by MikeAlhayek** [comment]
Yea it's not an issue which is why I approved it. But typically we leave the wwwroot folder to get populated by gulp. I think our gulpfile has a task to copy files like fonts and others from assets to wwwroot. This way we don't accidentally delete these file and expect them to be regenerated.

**Comment by Skrypt** [comment]
Here see the assembly and all that is in the wwwroot folder:

image

**Comment by Skrypt** [comment]
Here is the Workflows module as anothe example:

image

**Comment by Skrypt** [comment]
Yeah, we copy when we have a /Assets/vendor folder that needs to be used for building assets in that folder. Or we want to archive a specific version of that vendor lib.

Else, we also copy often directly from /node_modules/
So, here, we keep the Assets because we need to build a minified/unminified version of them. Also the Assets folder is never bundled. But is we explicitly want to bundle something as part of the assembly then it should go directly to the wwwroot folder. The Assets folder can still be used for archiving a file but in this case we have Git to keep history of these files so I'm not sure if that makes sense to have another build step just to copy 2 files in that wwwroot folder.

**Pull request merged**
