### PR TITLE
Use PostLogoutRedirectUri when cancelling logout from OpenID

### LINKED ISSUE #13089: Redirec to whrong home page on Are you sure you want to log out? in oepn id
Once you are trying to logout from SPA with template of Are you sure you want to log out?.
If you click no, you are redirected to server URL home page instead of spa.
In my case, server and UI running in different containers.

### Expected behavior
If using openid redirect to app redirect url.

### PR DESCRIPTION
**Pull request by gvkries**
When cancelling a logout request from the OpenID server by clicking the "No" button, the user was always redirected to the home page of the OIDC server. Instead the `PostLogoutRedirectUri` should be used. 

I added additional query parameters to the redirect URI to allow the client app to easily detect whether logout has been cancelled. 

Fixes #13089

### CODE REVIEW

**Comment by Piedone** [comment]
@kevinchalet could you please take a look?

**Comment by kevinchalet** [comment]
Thanks for your PR 😃 

> Instead the `PostLogoutRedirectUri` should be used.

No: the OIDC RP-initiated logout specification doesn't allow redirecting the user agent to the `post_logout_redirect_uri` when an error occurs (unlike the `redirect_uri`, to which standard error parameters can be attached):

```
If any of the validation procedures defined in this specification fail, any operations requiring the information that failed to correctly validate MUST be aborted and the information that failed to validate MUST NOT be used.
```

```
As described in [Section 3](https://openid.net/specs/openid-connect-rpinitiated-1_0.html#RedirectionAfterLogout), when the OP detects errors in the RP-Initiated Logout request, the OP MUST not perform post-logout redirection to an RP.
```

https://openid.net/specs/openid-connect-rpinitiated-1_0.html#RPLogout

Even if we decided to implement that as a non-standard extension, very few OIDC clients would be able to use it: for instance, the OpenIddict client would treat it as an error (see https://github.com/openiddict/openiddict-core/blob/606715819bf4d52c75da5ece61779d749cfa9a80/src/OpenIddict.Client/OpenIddictClientHandlers.cs#L1245-L1257), but not the ASP.NET Core OIDC middleware, that would treat is a normal, positive post-logout callback (which wouldn't be good at all).

Thanks for your PR, but it's not a change we can make without being non-standard.

**Comment by Piedone** [comment]
Thanks! Do you think the linked issue is valid?

**Comment by kevinchalet** [comment]
@Piedone it is, but if we decide to implement that, the URI will need to be stored as a server setting. We can't use `post_logout_redirect_uri` for that.

**Comment by Piedone** [comment]
I see, thanks. @gvkries would you like to give that approach a try?

**Comment by gvkries** [comment]
@kevinchalet  Thanks for having a look. 

I don't think this is against the specification. A user-cancellation cannot be counted as validation error of the **request** and afterwards the OP has no restrictions on the actions to take (this includes redirecting IMHO, the added parameters are of cause non-standard):

```
Beyond that, the OP has discretion on what information to display to the End-User in the resulting page at the OP and what actions to enable the End-User to perform next.
```

In case of a native app or SPA, using the logout functionality is otherwise cumbersome. 

Anyways, I didn't want to start arguing here - sorry. I'm of cause fine with your decision of not taking this change.

Your other proposal what mean a server-wide setting for redirection in this case, did I understand that correct? In that case I don't think this would actually solve the problem, because this would still be needed per application. We can leave it as-is in that case, because it adds no real value.

**Pull request closed without merging**
