### PR TITLE
Features Across Tenants

### PR DESCRIPTION
**Pull request by jtkech**
Almost done.

As suggested by @sebastienros, the goal is to define features that are only managed by the default tenant and whose states are shared across all other tenants.

**For infos**

- `IsAlwaysEnabled` is used through the DI for the application's module. It is also and already used, but through manifest files, to prevent some features, once enabled, from being disabled.

- The default tenant is always created (activation + pipeline on request), only other tenants are first pre-created. So, in a given tenant we can always create a scope on the default tenant and use its `GetShellDescriptorAsync()` to grab the enabled features marked as `AcrossTenants`.

    Note: E.g during graphQL tests we create tenants but we let the default tenant uninitialized, so we can't e.g resolve a session on it and so on. So we need to check the default tenant state.

- Normally, any feature depending on an `AcrossTenants` feature would need to be `AcrossTenants` too. Otherwise, a given tenant, by enabling this feature, would be able to also enable one of its dependency that is  `AcrossTenants`. But i let it as it is, the rule being that such a feature should be also defined as `AcrossTenants`. Note: The same rule should be applied to `DefaultTenantOnly`.

**Todo**

- **Unload the tenants** when the state of an `AcrossTenants` feature change.

### CODE REVIEW

**Comment by jtkech** [comment]
So i did some progress on this one but maybe not so simple.

- For an `AcrossTenants` feature we need to consider its dependencies, if a given tenant can't enable / disable an `AcrossTenants` feature, it should not be able to disable also its dependencies.

- When the feature state change we would need to update, on each tenant, the state of the related dependents / dependencies, run the `ShellStateCoordinator` to apply the changes ...

So just to say that all is doable but maybe there is a simpler strategy, i will think about it.

**Comment by jtkech** [comment]
I close this PR as i think it will become too complex to manage the dependency graph accross tenants.

I will re-work on it in a new PR when i will have time. The idea being that an `AcrossTenants` feature should not have any `dependencies` and any `dependents`.

The strategie would be e.g to have a set of features that are enabled for a set of tenants, but that require an `AcrossTenants` feature (with the `[RequireFeatures()]` attribute) to be operational.

**Comment by deanmarcussen** [comment]
@jtkech that's a shame, it could be a very useful feature (imagine a piece of middleware that needs to be tenant aware, and run for every tenant).

But I understand the difficulty in managing the dependancy graph.

Would another option (maybe simpler, but maybe not) to allow feature configuration by `appsettings.json` ?

Then you could have a section for all shells, and maybe also single shells?

As I suggest this, I also realise that somehow that would need to be reflected in the ui, so they couldn't be disabled.

So just an idea, needs more thought

**Comment by jtkech** [comment]
@deanmarcussen no problem i will open a new PR when needed, just because it was no more in sync with my other PRs so better to re-work on it from scratch, and i already used some part of this PR in one of my other PRs.

> Would another option (maybe simpler, but maybe not) to allow feature configuration by appsettings.json ?

We can already do that by defining a `Features` array, see in `ShellDescriptorManager` where there is

    var configuredFeatures = new ConfiguredFeatures();
    _shellConfiguration.Bind(configuredFeatures);

**Pull request closed without merging**
