### PR TITLE
Fix bag-part when content type is deleted

### LINKED ISSUE #12857: BagPart: Null reference exception removed widget
### Describe the bug

After update to version 1.5, bagpart throws exception when ContentItem contains widget, that has been removed from Content Types.

```
IContentPartDisplayDriver thrown from OrchardCore.Flows.Drivers.BagPartDisplayDriver by NullReferenceException
System.NullReferenceException: Object reference not set to an instance of an object.
   at OrchardCore.Flows.Drivers.BagPartDisplayDriver.GetAccessibleWidgetsAsync(IEnumerable`1 contentItems, IContentDefinitionManager contentDefinitionManager)
   at OrchardCore.Flows.Drivers.BagPartDisplayDriver.<>c__DisplayClass7_0.<<Edit>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at OrchardCore.DisplayManagement.ShapeFactoryExtensions.<CreateAsync>g__Awaited|6_0[TModel](ValueTask task, IShape shape)
   at OrchardCore.DisplayManagement.Implementation.DefaultShapeFactory.CreateAsync(String shapeType, Func`1 shapeFactory, Action`1 creating, Action`1 created)
   at OrchardCore.DisplayManagement.Views.ShapeResult.ApplyImplementationAsync(BuildShapeContext context, String displayType)
   at OrchardCore.ContentManagement.Display.ContentItemDisplayCoordinator.<>c.<<BuildEditorAsync>b__8_0>d.MoveNext()
--- End of stack trace from previous location ---
   at OrchardCore.Modules.InvokeExtensions.InvokeAsync[TEvents,T1,T2,T3](IEnumerable`1 events, Func`5 dispatch, T1 arg1, T2 arg2, T3 arg3, ILogger logger)``
```

Related also to graphql 
```
GraphQL.Execution.UnhandledError: Error trying to resolve field 'widgets'.\r\n ---> System.InvalidOperationException: Abstract type ContentItem must resolve to an Object type at runtime for field .widgets with value 'test', received 'null'.\r\n   at GraphQL.Execution.ExecutionStrategy.ValidateNodeResult(ExecutionContext context, ExecutionNode node) in /_/src/GraphQL/Execution/ExecutionStrategy.cs:line 580\r\n   at GraphQL.Execution.ExecutionStrategy.CompleteNode(ExecutionContext context, ExecutionNode node) in /_/src/GraphQL/Execution/ExecutionStrategy.cs:line 505\r\n   --- End of inner exception stack trace ---```

### To Reproduce
Steps to reproduce the behavior:
1. Go to Content Item, add bagpart with widget inside
2. Go to Content types and remove widget type
3. Return to Content Item
4. Check logs and see error

### Expected behavior
There is no error thrown.

### PR DESCRIPTION
**Pull request by MikeAlhayek**
Fix #12857

### CODE REVIEW

**Comment by Skrypt** [comment]
Could we log an exception too at least?

**Comment by MikeAlhayek** [comment]
@Skrypt you referenced the flowPart. This PR presents change to the BagPart. We can add the same warning in the BagPart to show the user something instead of ignoring. Is this something you want me to add?

**Comment by Skrypt** [comment]
Yes, I think that would be a good addition.

**Comment by MikeAlhayek** [comment]
@Skrypt I made the requested change.

**Review by Skrypt — APPROVED** [review]

**Pull request merged**
