### PR TITLE
Align taxonomy filter to the right

### PR DESCRIPTION
**Pull request by tropcicstefan**
#10289 

Similar to #8079

### CODE REVIEW

**Comment by sebastienros** [comment]
Can you share a screenshot of the issue and with your fix?
I trust the change but I want to see it to understand if that is the best end result.

**Review by Skrypt — APPROVED** [review]

**Comment by agriffard** [comment]
Do you approve because the code seems ok for you or because you actually tested it (LTR and RTL) ?
We asked for a screenshot so it would be easier to see the change.

**Comment by tropcicstefan** [comment]
> Do you approve because the code seems ok for you or because you actually tested it (LTR and RTL) ?
> We asked for a screenshot so it would be easier to see the change.
I put the screenshots in the issue, sry, should have put them here

**Comment by agriffard** [comment]
Thank you, sorry we didn't check in the issue.

Can you please confirm that it is working with a Right To Left culture?

**Comment by hishamco** [comment]
> Can you please confirm that it is working with a Right To Left culture?

I may check this one

**Comment by hishamco** [comment]
Please don't merge this, I need to check few cases, seems the filter picker looks ugly in RTL. I will check and fix it requires

**Comment by hishamco** [comment]
Filter

**Comment by Skrypt** [comment]
If it doesn't work with RTL then it might not work for the others too as the fix is exactly what I did before. So, yeah, test it, it will be safer in that case.

**Comment by Skrypt** [comment]
All good I'm merging.

image

**Pull request merged**
