### PR TITLE
Isolated tenant http clients

### LINKED ISSUE #11041: `AddHttpClient<MyService>()` fails within Modules.
new version of #6677 as it was asked that a new issue be created.

Typed calls to `AddHttpClient` are failing within a module in `.Net 5.0` and `.Net 6.0`. (I tried rolling back to .Net 5.0 in case OC 1.1 was incompatibile with 6.0).

```cs
// MainProject/Startup.cs
class MainStartup
{        
  public void ConfigureServices(IServiceCollection services)
  {
    services.AddHttpClient<MyService>(); // this is cool
  }
}

// Module/Startup.cs
class ModuleStartup : OrchardCore.Modules.StartupBase
{ 
  public void ConfigureServices(IServiceCollection services)
  {
    services.AddHttpClient<MyService>(); // NullReferenceException
  }
}
```

The issue is as follows. In AspNetCore, `AddHttpClient` registers a singleton of `HttpClientMappingRegistry`.

https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/Microsoft.Extensions.Http/src/DependencyInjection/HttpClientFactoryServiceCollectionExtensions.cs#L52-L54

When initializing a typed HTTP Client, `HttpClientBuilderExtensions.AddTypedClient` calls `HttpClientBuilderExtensions.ReserveClient`, which iterates through the Builder's Services and attempts to find an _instantiated_ instance of HttpClientMappingRegistry. 

https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/Microsoft.Extensions.Http/src/DependencyInjection/HttpClientBuilderExtensions.cs#L634-L636

Orchard Core's FeatureAwareServiceCollection doesn't automatically instantiate Singletons, for the reason that @marlon-tucker linked in the initial issue -- it doesn't implement `IDisposable`, so it isn't instantiated until `ServiceProvider.GetService<HttpClientMappingRegistry>()` is called:

https://github.com/OrchardCMS/OrchardCore/blob/ec2154ae099913ee81751f30c4f7660952fe63c9/src/OrchardCore/OrchardCore/Shell/Builders/Extensions/ServiceProviderExtensions.cs#L42-L59

As you can see in the `ReserveClient` method above, however, GetService is never called on the `HttpClientMappingRegistry` -- it is instead selected through LINQ, meaning it is never instantiated. `Single()` returns a registered service, but `Single().ImplementedInstance` is null.

image

I'll try and provide a repro when I have the chance.

### PR DESCRIPTION
**Pull request by jtkech**
Fixes #11041 

For example see https://github.com/OrchardCMS/OrchardCore/issues/11041#issuecomment-1569479334 and https://github.com/OrchardCMS/OrchardCore/issues/11041#issuecomment-1571397783, so that it works as before at the tenant level but it now allows http client configurations at both host and tenant levels.

### CODE REVIEW

**Comment by jtkech** [comment]
@johnrom @ShaneCourtrille ...

I'm closing this PR but let the branch available if you are interested to test it.

Open to re-work on it if any feedback ;)

**Comment by jtkech** [comment]
No worries, easy to re-open on demand ;)

**Comment by jtkech** [comment]
Re-opened for one or two more weeks ;)

**Comment by jtkech** [comment]
I'm merging this one because

- If you only register http clients at the host level, it works as before.

- If you only register http clients at the tenant level, it works as before.

- If you register typed http clients at both levels, anyway it was failing before ;)

**Comment by xperiandri** [comment]
I call this on the host level
``` F#
services
    .ConfigureValidatable<DocumentUploadOptions>()
    .AddHttpClient<IDocumentServiceClient, DocumentServiceClientWrapper>(
        fun (serviceProvider: IServiceProvider) (client: HttpClient) ->
            let options = serviceProvider.GetRequiredService<IOptions<DocumentUploadOptions>>().Value
            client.BaseAddress <- Uri(options.BaseUrl)
    )
    .AddHttpMessageHandler(
        Func<IServiceProvider, DelegatingHandler>(fun serviceProvider ->
            let options = serviceProvider.GetRequiredService<IOptions<DocumentUploadOptions>>().Value
            let accessTokenManagementService =
                GoogleCloudAccessTokenManagementService(
                    options.BaseUrl,
                    serviceProvider.GetRequiredService<IClientAccessTokenRequestSynchronization>(),
                    serviceProvider.GetRequiredService<IClientAccessTokenCache>(),
                    serviceProvider.GetRequiredService<IOptions<GoogleCloudOptions>>(),
                    serviceProvider.GetRequiredService<ILogger<GoogleCloudAccessTokenManagementService>>()
                )
            new ClientAccessTokenHandler(accessTokenManagementService, DocumentUploadClientName))
    )
    |> ignore
```
and this function is never called
```
        fun (serviceProvider: IServiceProvider) (client: HttpClient) ->
            let options = serviceProvider.GetRequiredService<IOptions<DocumentUploadOptions>>().Value
            client.BaseAddress <- Uri(options.BaseUrl)
```

**Comment by jtkech** [comment]
Is your `IDocumentServiceClient` registered and/or injected at the tenant level?

If that's the case you need to wrap your code in `services.ConfigureServices(...)` instead.

> If you only register http clients at the host level, it works as before.

Yes it's not totally true, I meant if all is done at the host level including the usage.

**Comment by jtkech** [comment]
Okay, so if the usage is at the tenant level, your have to register clients and handlers at the tenant level, `services.ConfigureServices(tenantSercices => tenantSercices.AddHttpClient(...).AddHttpMessageHandler(...)` instead.

Normally still registering your tied services at the host level (if they don't need to resolve tenant level services) will work as we clone services (we filter specific ones) from host to tenant containers.

**Pull request merged**
