### PR TITLE
Add OpenID config input hints for redirect URIs

### PR DESCRIPTION
**Pull request by petedavis**
Helps make it clearer that you can add more than one redirect URI

### CODE REVIEW

**Comment by petedavis** [comment]
cc @PinpointTownes

**Comment by PinpointTownes** [comment]
LGTM.

That said, in an ideal world, we may want to move to either a multi-line input or dynamic inputs that you can add and remove to register multiple addresses (e.g something like https://itsolutionstuff.com/post/simple-add-remove-input-fields-dynamically-using-jquery-with-bootstrapexample.html).

**Comment by Skrypt** [comment]
You can use the predefined list Vue.js control for that matter. You would just need to remove the value part of each line and editing JSON directly could still be relevant.

**Comment by PinpointTownes** [comment]
Looks like @sebastienros was eager to merge this PR so I'll open a new ticket to track future improvements 😄

**Comment by sebastienros** [comment]
well I didn't expect anyone to improve the editor, or I could have waited for months ...

**Comment by PinpointTownes** [comment]
Well, not sure how it would work with vue.js (as @Skrypt suggested), but it we went with a simple approach based on jQuery like https://itsolutionstuff.com/post/simple-add-remove-input-fields-dynamically-using-jquery-with-bootstrapexample.html, it would only require a few lines of JS.

**Pull request merged**
