### PR TITLE
Implemented GraphQL query for retrieving current user data and its custom settings

### LINKED ISSUE #15214: GraphQL - Query current user and custom user settings
### Is your feature request related to a problem? Please describe.
Getting information about the current user and additionally its custom user settings (aka user profile) is currently not possible out of the box with GraphQL. 

### Describe the solution you'd like
A query as described in the documentation (https://docs.orchardcore.net/en/latest/docs/reference/modules/Apis.GraphQL/#http-methods-headers-and-body) would be handy for using OC as headless CMS with frontend users. This can then also allow querying custom user settings (i.e. content types with `CustomUserSettings` stereo type).

A sample query could look like:
```
query MyQuery {
  me {
    email
    phoneNumber
    userName
    userId
    userProfile {
      name
      profilePicture {
        urls
      }
    }
  }
}
``` 

### Describe alternatives you've considered
None

### PR DESCRIPTION
**Pull request by gvkries**
Fixes #15214

### CODE REVIEW

**Comment by hyzx86** [comment]
Good PR !👍

Is there a plan to implement UserPickerField?

**Comment by gvkries** [comment]
> Is there a plan to implement `UserPickerField`? You can refer to `ContentPickerField`

I had no need for that at the moment, but it would be a good addition.

**Review by hyzx86 — APPROVED** [review]

**Comment by hyzx86** [comment]
> @hyzx86 can you review this PR?

I have seen, I also have plans to do this feature, but it seems that he is more perfect implementation, I have not considered the hidden type

**Comment by sebastienros** [comment]
Should this wait for the GraphQL package update to be merged? OR @hyzx86 do you want this one to be merged first and you to update your PR with that.

**Comment by hyzx86** [comment]
> Should this wait for the GraphQL package update to be merged? OR @hyzx86 do you want this one to be merged first and you to update your PR with that.

it's not a big change. It can be merged into the main branch first. 
Later I can add GraphQL support for UserPickerField

**Pull request merged**
