### PR TITLE
 Fix notifier log message formatting

### PR DESCRIPTION
**Pull request by argonselenium**

### CODE REVIEW

**Comment by sebastienros** [comment]
I think you don't understand how the logging formatting works.
What is the behavior you are trying to fix? because this code looks actually correct. It's called "structured logging", here is some documentation with examples: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.2

**Comment by sebastienros** [comment]
Not saying there is not a bug, but your fix is probably going in the wrong direction. That's why I want to understand the issue you are experiencing first.

**Comment by jtkech** [comment]
@argonselenium see in the doc you linked, they use format strings, not string interpolation.

**Comment by argonselenium** [comment]
Thanks for the update. I was unaware of structured logging, looks like I've got some reading to do!

**Pull request closed without merging**
