### PR TITLE
Add TenantPipelineInitializer

### LINKED ISSUE #14086: IUrlHelper does not seems to work when used in `IBackgroundTask`
### Describe the bug
I have a background task that runs every 1 hours a checks for new published content items and sends out notifications. 

I want to be able to send out the `display_url` of each content item so that the user can click on the link from their email to view the correct content item.

I used Liquid to create the email body. In the email I do something like this `{{ Model.ContentItem | display_url }}`. But, for some reason the value is always nil. So the url isn't being generated for some reason. The following line https://github.com/OrchardCMS/OrchardCore/blob/83ada8fbb11e208caab7d3111b33deb056009d1a/src/OrchardCore.Modules/OrchardCore.Contents/Liquid/DisplayUrlFilter.cs#L53 seems to always return null even when `routeValues` has the correct values.

I am assuming the issue is because the request is coming from the background task and there is not URL in the HttpRequest but not positive. 

Is there a workaround for this?

To reproduce this issue you can add this Background task
```
[BackgroundTask(
    Title = "Testing",
    Schedule = "* * * * *",
    Description = "Testing")]
public class TestingBackgroundTask : IBackgroundTask
{
    public async Task DoWorkAsync(IServiceProvider serviceProvider, CancellationToken cancellationToken)
    {
        var session = serviceProvider.GetRequiredService<ISession>();
        var liquidTemplateManager = serviceProvider.GetRequiredService<ILiquidTemplateManager>();
        var htmlEncoder = serviceProvider.GetRequiredService<HtmlEncoder>();

        var contentItem = await session.Query<ContentItem, ContentItemIndex>(x => x.Published).FirstOrDefaultAsync();

        var message = "{{ ContentItem | display_url }}";

        var result = await liquidTemplateManager.RenderHtmlContentAsync(message, htmlEncoder, null,
            new Dictionary<string, FluidValue>()
            {
                ["ContentItem"] = new ObjectValue(contentItem),
            });

        using var writer = new StringWriter();
        result.WriteTo(writer, htmlEncoder);

        var finalString = writer.ToString();
    }
}
```

Then register it like this
```
services.AddSingleton<IBackgroundTask, TestingBackgroundTask>();
```
Put a break point and step into `DisplayUrlFilter`

### PR DESCRIPTION
**Pull request by MikeAlhayek**
Fix #14086

@jtkech not sure if this is a better approach than that approach you took in #14105

I tested this approach out and it also works.

### CODE REVIEW

**Comment by jtkech** [comment]
You go too fast ;)

Here the problem is not how to do things but to first well define what we want, as we can discuss in #14094, then I could complete #14105 because I prefer to keep control on this.

For example here you forgot to use a little dedicated middleware to shortcut the pipeline while in the background, this to make it lighter and faster. Also I saw that you removed the `HttpContext.SetBaseUrl()` while in the background, which is different than checking the `RequestUrlPrefix`.

**Comment by MikeAlhayek** [comment]
@jtkech I rather for you to take over the PR or finish yours. When we discussed the issue, I thought to try out the solution in this PR. At the end of the day, it's just a alternative way to do solve the problem. Feel free to close this PR and proceed with yours.

About the Base URL, we can simplify things here by removing this code

https://github.com/OrchardCMS/OrchardCore/blob/69189005c98cbbeec64323fee756ee9869112ff2/src/OrchardCore/OrchardCore.Abstractions/BackgroundTasks/ShellContextExtensions.cs#L35-L38

and 

[context.Items["IsHttpPathConfigured"] = true;](https://github.com/OrchardCMS/OrchardCore/blob/69189005c98cbbeec64323fee756ee9869112ff2/src/OrchardCore/OrchardCore.Abstractions/BackgroundTasks/ShellContextExtensions.cs#L42C9-L42C54)

Then we can remove the `!httpContext.Items.ContainsKey("IsHttpPathConfigured")` check in `TenantPipelineInitializer` class. This would build the same URL logic. 

I just did not want to change the code `ShellContextExtensions` to prevent any possible breaking change even when I don't think any one use these extensions.

**Comment by jtkech** [comment]
Okay cool then, no problem.

About the base url (that may not contain any prefix) we still need to set it in the background, this to eventually set the `Scheme`, `Host` and a new `PathBase`, but I will take  look at what you are suggesting.

**Comment by MikeAlhayek** [comment]
@jtkech I brought back the call to `SetBaseUrl()` and did some small cleanup so we don't use the `IsHttpPathConfigured`. Feel free to make any changes to this PR or proceed with the other PR if you think it is a better approach.

**Comment by jtkech** [comment]
Okay, if you still want to try it in this branch, add the little middleware to shortcut the pipeline if executed in the background, you will see the difference from tens of ms to only one ms.

**Comment by MikeAlhayek** [comment]
@jtkech adding shortcut to the pipeline will not register routes. Maybe the router is registered via pipeline and with the shortcut it won't register it.

**Comment by jtkech** [comment]
I tried it, it works even if I use `order: Int32.MinValue` (the order we call module startup Configure()) to be sure it is our 1st middleware, this because the pipeline is built inside an `app.UseRouting().UseEndpoint()`, so anyway the needed aspnetcore routing middlewares will execute first and then before the shortcut.

**Comment by jtkech** [comment]
It may depend where and how you are registering this middleware.

Also you can't inject `IFeatureCollection` which is not in the DI, it is explicitly passed when we register `ModularTenantRouterMiddleware` while building the app level `IApplicationBuilder`.

https://github.com/OrchardCMS/OrchardCore/blob/639e72e704942b7172066b927e8ec4070d9fdbf5/src/OrchardCore/OrchardCore/Modules/Extensions/ApplicationBuilderExtensions.cs#L34-L38

**Comment by MikeAlhayek** [comment]
@jtkech you did lots of work on #14105. I am closing this PR in favor of yours. If you want this one, you can always reopen it.

**Comment by jtkech** [comment]
Okay no problem

**Pull request closed without merging**
