### PR TITLE
Hint tag helper

### PR DESCRIPTION
**Pull request by NogginBox**
Potential implementation of "Tag helper for hint" #5804

This seemed like an easy one if I understand the requirement.

This PR includes the Tag Helper and one usage. If the implementation is okay I can apply it to all views where there is hint text.

### CODE REVIEW

**Comment by hishamco** [comment]
From your PR I didn't see much hint in the source, so creating a TagHelper for one occurance doesn't make sense to me, but I like the principle to create a TagHelper for it.

**Comment by scleaver** [comment]
@NogginBox  Some hints require additional classes eg. `dashed` will the PR cover this senario

**Comment by jtkech** [comment]
Need to be tried but as i remember any html attribute, that is not bind to a tag helper property, is just kept as is in the rendered html, unless we update it as done in this PR but by **just adding** a class `output.AddClass("hint", ...)`

**Comment by NogginBox** [comment]
@hishamco <span class="hint">...</span> is used lots, but I only replaced it once to show it working. I didn't want to replace all of them, if the tag helper I'd made did not meet the needs of the PR. I will go through and do the rest if the tag helper is agreed to fix issue #5804.

@scleaver I'll find where dashed is used and add it to the tag helper.

@Piedone made the original issue: Is this still required and does my PR meet your original intent?

**Comment by deanmarcussen** [comment]
for info the two types of `Hint` that we have are
```
<span class="hint">@T["The site name."]</span>
<span class="hint dashed">@T["The site name."]</span>
```

So the tag helper would become
```
<hint>@T["The site name."]</hint>
<hint class="dashed">@T["The site name."]</hint> 


<span asp-hint asp-dashed>@T["The site name."]</span> <-- or a variant of as @jtkech said it might be

```

I'm not sure what we have really saved or improved by adding a taghelper, except making it slower, and perhaps easier to change, if later another feature is added.

I'll let @Piedone argue the case for why we should have it as he suggested it

**Comment by Piedone** [comment]
Well, writing `<hint>` instead of `<span class="hint">` is more expressive I think :). However, when I opened the issue there was no `dashed` yet and dashes were also copy-pasted around, and together with that it was more of an issue. Now I'm less concerned about this but perhaps `<hint>` and `<hint dashed>` would be nicer?

**Comment by Skrypt** [comment]
It's maybe more expressive but also more restrictive. What if I want to add this to a `<div>` instead of a `span` ?

**Comment by NogginBox** [comment]
@Skrypt could use format suggested by @deanmarcussen 
```
<span asp-hint asp-dashed>@T["The site name."]</span>
```
Or if the use case for this is gone as I think @Piedone was suggesting, then I'm happy to cancel this PR and we can close the original issue as it's not required anymore?

**Comment by Piedone** [comment]
Yeah, I think this is not needed anymore, sorry about that.

**Comment by hishamco** [comment]
Closed according to the above comments, thanks @NogginBox

**Pull request closed without merging**
