### PR TITLE
Shortcut Migrations

### PR DESCRIPTION
**Pull request by jtkech**
Shortcut `Create` migrations that don't need to run on new installations.

@Skrypt can you confirm that this is the case of the  `Create` migration of `OC.Search.Lucene`?

### CODE REVIEW

**Comment by Skrypt** [comment]
I would not bet on that.

**Comment by jtkech** [comment]
@Skrypt Okay thanks

Here the upgrade is not run on a fresh setup, idem on AutoSetup that uses the setup service that marks the shell as IsInitializing. If the recipe is run afterwards from the admin it will behave as before, idem when enabling the feature after the setup.

Note: I thought about checking if the feature was newly installed (first enabling), but here if it is done on an existing installation, maybe some parts / fields settings may still need to be updated.

---

Yes would need to be tested but first I'm thinking about some use cases.

Hmm maybe you mean that it is still good to update parts / fields settings even on a fresh setup in case some recipes don't use the new conventions. So if you think it is too risky I will just revert this change.

Hmm, maybe at least on a fresh setup we could skip the deferred task that update the `$type` in some documents from `OrchardCore.Lucene...` to `OrchardCore.Search.Lucene...`. But again if you think it is too risky I will just revert the change ;)

**Review by Skrypt — APPROVED** [review]
Approved 😴 🐵

**Comment by jtkech** [comment]
@Skrypt 

Yes all good but as we discussed if the feature is enabled after a new setup, the useless upgrade will run.

So I tried what I first did but was not sure, by checking if the feature has been newly installed (the very first enabling), which is the case on a new setup including the feature or through a recipe later on.

But not the case on an existing installation where the feature has been already enabled, even if the feature was disabled in the meantime.

**Pull request merged**
