### PR TITLE
New version Font Icon Picker, removed IconPicker in TextField option, added required setting to Youtube field

### PR DESCRIPTION
**Pull request by zimplerconsulting**
This PR includes a new version of the Font Icon Picker, but now as a new field, since I also wanted to have some sort of control over how the selected icon is rendered on the page itself. You will need e.g. a font and related css.

Also, this picker has some more functionality like categories and the ability to load icon sets from multiple fonts (FontAwesome, Icomoon, Fontello), which 'can be' implemented at a later stage.

The current Icon picker is removed from the source code, so that you cannot choose an Icon Picker inside the Text Field settings.

You can see how this works in the gif below:

### CODE REVIEW

**Comment by sebastienros** [comment]
I think it's not a good approach to create a new field just for a font picker. What you did for the text field is good enough. The only that we could discuss would be to have a field that represents a css class, but I don't see how it would be better than a text field as there aren't many choices we can provide for it.

If the goal is to expose the class picker more directly to users, then I think a better option would be to change how we add a new field and show all possible editors instead, which will ultimately pick-up a field type. So when people chose Icon Picker, it automatically use a Text Field.

Also if you want to provider multiple sets of icons based on the font, it needs to be a settings on the icon picker editor. Because only the dev who wrote the template knows what is the correct option. The template and the editor settings are coupled.

**Comment by zimplerconsulting** [comment]
OK, I understand. Not sure why this isn't done with e.g. the YoutubeField, which should also render just a link?

Is it also possible to create a module that adds this IconPickerField to a solution?

**Comment by Skrypt** [comment]
Because the Youtube field stores 2 different strings.
https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.ContentFields/Fields/YoutubeField.cs

**Comment by Skrypt** [comment]
Yes, I think what @sebastienros wanted first is something simple that works with the TextField editors. I'm guessing that as a contrib module, the other method would be good too. Just change @sebastienros mind about it is the other last option 😉

**Comment by sebastienros** [comment]
I think you are doing a field with Text/HTML properties because there are no Display Editors to let you decide how the entered text is rendered.

**Comment by sebastienros** [comment]
I added Display Modes which will allow you to define a custom way to render a text field that contains an icon. And it can have settings which means we can set the desired font for the editor, and how it's rendered on the front end.

https://github.com/OrchardCMS/OrchardCore/pull/2544

**Pull request closed without merging**
