### PR TITLE
Return 403 if tenant disabled

### LINKED ISSUE #11218: Disabling tenant should return Tenant disabled instead of 404 not found
**See https://github.com/OrchardCMS/OrchardCore/issues/11218#issuecomment-1248382965.**

### Describe the bug
Disabling Tenant should return appropriate message instead of 404.

### To Reproduce
1. Go to Tenants
2. Disable a Tenant
3. Go to tenant home page
4. See 404 reported on Default tenant .  

### Expected behavior
It should display Tenant disabled instead of 404 not found on default tenant

### PR DESCRIPTION
**Pull request by jtkech**
First step to Fix #11218

### CODE REVIEW

**Comment by Skrypt** [comment]
I don't think we decided yet which error we should throw. There are specific cases where it will need to be tested.

**Comment by jtkech** [comment]
Yes for sure, it's only a first step to locate things.

**Comment by Skrypt** [comment]
It would have helped if you would have joined this afternoon's meeting. But basically, when the tenant is disabled and if it uses a different domain name than the default tenant it should not fall back to the default tenant 404 page because it will generally have a different theme than the disabled tenant.

default tenant -> foo.com --> 404 not found
tenant1 -> foo.com/prefix --> 404 not found (default tenant page)
tenant2 -> bar.com --> needs to be tested to see the behavior but normally if the tenant is disabled then the server will not resolve the tenant domain and will not map it to the tenant host which should cause the server to not be able to resolve anything and then display probably a server error page. That is what happens generally in Azure when a domain cannot be mapped to a tenant.

**Comment by jtkech** [comment]
What I can say for now is that here we keep the disabled tenant in the `RunningShellTable` so that it is mapped exactly as before it was disabled.

Then in `ModularTenantContainerMiddleware`, in place of being filtered by the `RunningShellTable` we check the disabled state just after to do what we want, for now here for testing I just return 403.

**Comment by Skrypt** [comment]
Ok, if the domain is still resolving to a tenant it means that at least the host is instantiated but it probably doesn't have any tenant registered from the DI simply.

**Comment by jtkech** [comment]
Yes, in fact the tenant is still registered in ShellHost in a disabled state but yes no DI container can be build.

**Comment by jtkech** [comment]
But only for now ;

As we can do what we want, for example in the Tenant Removal branch we build a container related to a disabled tenant to replay migrations

**Pull request closed without merging**
