### PR TITLE
Avoid slash in role name

### LINKED ISSUE #4410: Role name with slash "/" character cannot be Edited nor Deleted
1. Create a new role named "role/withSlash"
2. Try to Edit or Delete it

=> Error 404 : the page cannot be found.

### PR DESCRIPTION
**Pull request by hishamco**
Fix #4410

InvalidRole

### CODE REVIEW

**Comment by hishamco** [comment]
@sebastienros ready to merge

**Comment by sebastienros** [comment]
So it doesn't work with slahes because it's reserved in a URL. What about all other chars?

Ideally this should be encoded when the URL is built, or this should contain many more chars. But then why limit to the chars of an URL because it prevents you from handling it correctly? And what about other places where it's chars could be reserved? I'd suggest to actually define what is allowed, maybe following EF provider rules, and then econding when necessary in every place.

**Comment by hishamco** [comment]
> So it doesn't work with slahes because it's reserved in a URL.

Actuall the slash will add another segement that prevent use from editing or deleting the role

> maybe following EF provider rules, and then econding when necessary in every place.

I will try to check them, but AFAIK spaces & slash that make the URL sad

**Comment by hishamco** [comment]
> EF provider rules

BTW which rules you mean here?

**Comment by sebastienros** [comment]
You can create roles with the EF identity providers. Is there any validation in the names? I would assume not, which would prove that the issue is not about validating chars, but encoding them based on where the role names are used. In the case of this specific issue about url encoding it.

**Pull request merged**
