### PR TITLE
fix role update

### LINKED ISSUE #13035: Role permission settings are overwritten if a tenant is started
### Describe the bug

Whenever a tenant is activated, the `RoleUpdater` reapplies any default permissions  to the roles. This overwrites any adjustments made from the admin dashboard. This breaks all permissions assigned to specific content types, because e.g. the anonymous role is always reset.

### To Reproduce
Example steps to reproduce the behavior:
1. Go to security -> roles and edit the 'Anonymous' role.
2. Remove 'View' the permission from 'Content' and save.
3. Restart the web app.
4. The removed permission is added back.

### Expected behavior
Permission settings on roles are persisted between site restarts.

This bug was introduced by PR #12510.
See also bug #13024.

### PR DESCRIPTION
**Pull request by hyzx86**
fix : https://github.com/OrchardCMS/OrchardCore/issues/13024

Planned to also fix #13035.

https://user-images.githubusercontent.com/15613121/210268280-d710778f-4781-4c83-be93-2f5a62845831.mp4

### CODE REVIEW

**Comment by jtkech** [comment]
@hyzx86 

Thanks for re-opening this PR but maybe I will open a new PR as I already started to work on it locally to check different things as per my comment https://github.com/OrchardCMS/OrchardCore/issues/13024#issuecomment-1369392407

@MikeAlhayek maybe a different approach for example to not execute the RoleUpdater on each shell activation if possible, I think I will ask you some questions to confirm what was intended to be done.

Hmm, one question on the fly, yes in the controller, dynamic permissions was not taken into account, hmm maybe we need to take them into account also in the RoleUpdater, will see.

**Comment by MikeAlhayek** [comment]
@jtkech I in the `RoleUpdater` I think we have to call `GetDefaultStereotypes()` to group the permissions role this way we know which permissions should belong to Stereotype/role. If the grouped role is known to the current site, we then assign it. Once we assign a permission, we save the reference into `RolesDocument.PermissionGroups` this way we can know which permissions were auto assigned vs the assignments that were manually made "a user checking/unchecking" permissions.

In the Admin I agree we should not be using `GetDefaultStereotypes()`

We should be using the following as per your suggestions.
```
var permissionNames = new List<string>();
foreach (var permissionProvider in _permissionProviders)
{
    var permissions = await permissionProvider.GetPermissionsAsync();
    permissionNames.AddRange(permissions.Select(permission => permission.Name));
}
```

or 

```
var allPermissions = await Task.WhenAll(_permissionProviders.Select(x => x.GetPermissionsAsync()));
```

**Comment by jtkech** [comment]
Even if here all `GetPermissionsAsync()` seem to be synchronous (using Task.FromResult), and in that case it would be useless, I never use `Task.WhenAll()` ;) Unless I'm sure all are thread safe, which is not the case e.g. with `ISession`.

So okay the other breaking change, as stated by @gvkries https://github.com/OrchardCMS/OrchardCore/issues/13035#issuecomment-1370286327, is that on an existing installation not having yet the permissions history, some permissions get back to some roles on startup.

**Comment by jtkech** [comment]
Okay I'm  closing this one as I started to work on it on another branch #13040.

@hyzx86 @gvkries I will let you know when it will be ready to be tested.

**Pull request closed without merging**
