### PR TITLE
Simplify Collection initialization (IDE0300)

### PR DESCRIPTION
**Pull request by MikeAlhayek**

### CODE REVIEW

**Comment by hishamco** [comment]
I'm with & without the change, all the reactors will break the current PRs. I'm not disagree if all agree with the changes

**Comment by MikeAlhayek** [comment]
It should not break other PR since the change is done on a single line.

**Review by Piedone — COMMENTED** [review]
Looks good, but just to make sure, since I have to admit I didn't check all 497 files line by line: you didn't change anything apart from collection initializers, right?

**Comment by MikeAlhayek** [comment]
@Piedone yes this PR is only to simplify the collection initialization. I submitting couple PR to keep them simpler or easier to digest.

**Review by Piedone — APPROVED** [review]

**Pull request merged**
