### PR TITLE
Register ReCaptchaService as singleton

### LINKED ISSUE #14580: Make RecaptchaService a singleton
c.f. https://github.com/OrchardCMS/OrchardCore/discussions/14576

`RecaptchaService` can be a singleton, and the settings should be kept in a private field for reuse.

### PR DESCRIPTION
**Pull request by hishamco**
Fixes #14580

### CODE REVIEW

**Review by sebastienros — APPROVED** [review]

**Comment by jtkech** [comment]
But then in `ReCaptchaService` the `HttpClient` should not be held as a singleton field.

https://github.com/OrchardCMS/OrchardCore/blob/44a465b5291bef41b297f2ceaeca21463a530098/src/OrchardCore/OrchardCore.ReCaptcha.Core/Services/ReCaptchaService.cs#L31

https://github.com/OrchardCMS/OrchardCore/blob/44a465b5291bef41b297f2ceaeca21463a530098/src/OrchardCore/OrchardCore.ReCaptcha.Core/Services/ReCaptchaService.cs#L127

Need to leave, will do a PR this night.

**Comment by sebastienros** [comment]
Right, with the `IHttpFactory` pattern we should get a client every time we need one and then release it.

**Comment by sebastienros** [comment]
Also @jtkech while we are at it, we can optimize this:

```csharp
var content = new FormUrlEncodedContent(new Dictionary<string, string>
{
    { "secret", _reCaptchaSettings.SecretKey },
    { "response", responseToken }
});

_httpClient ??= _httpClientFactory.CreateClient(nameof(ReCaptchaService));
var response = await _httpClient.PostAsync($"_reCaptchaSettings.ReCaptchaApiUri.TrimEnd('/')}/siteverify", content);
```

The content should be a readonly field in the class, and so should the url from the request

**Comment by sebastienros** [comment]
Oops, the response token might be an issue.

**Comment by jtkech** [comment]
Yes ;)

**Pull request merged**
