### PR TITLE
better email regex

### PR DESCRIPTION
**Pull request by infofromca**

### CODE REVIEW

**Comment by sebastienros** [comment]
Can you give an example of an email that would not be filtered and that this expression is handling better?

We have a "validated" expression in Orchard 1 that we should reuse IMO, based on the official definition. It might be the one you are suggesting, in which case it's perfect. Can someone check in O1, it should also reference the source.

**Comment by douwinga** [comment]
Orchard 1 uses

```@"^(?![\.@])(""([^""\r\\]|\\[""\r\\])*""|([-\p{L}0-9!#$%&'*+/=?^_`{|}~]|(?<!\.)\.)*)(?<!\.)@([a-z0-9][\w-]*\.)+[a-z]{2,}$"```

https://github.com/OrchardCMS/Orchard/blob/48685b3ed7f3ed4f40d1081f0bc937a4e3b2338f/src/Orchard.Web/Modules/Orchard.Users/Models/UserPart.cs#L8

**Comment by sebastienros** [comment]
@douwinga this one is also wrong, the "better" one is this: https://github.com/OrchardCMS/Orchard/blob/735a67d20a9a54e7cc404c21b2c0b2a88e24ff64/src/Orchard.Web/Modules/Orchard.DynamicForms/ValidationRules/EmailAddress.cs#L14

```
            @"^[a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$";

```
And you can also find a mention of the source

**Comment by sebastienros** [comment]
Also I think we should provide a service like `IEmailAddressValidator` defined in `OrchardCore.Abstractions` because we might use it in many places, and we don't want to repeat the expression. And maybe someone will want to change how it's done, for instance by not using a regular expression which can be security sensitive. So bonus point if the implementation doesn't use a Regex but follows the same logic that it defines. And also unit tests, we have them in O1 so we just need to copy-paste.

**Comment by infofromca** [comment]
1) avoid use ^ $ for email:
https://stackoverflow.com/questions/577653/difference-between-a-z-and-in-ruby-regular-expressions
2) it seems that a**.**@a.com is allowed in O1

**Comment by nfarrell** [comment]
Unfortunately, even validating [email addresses](https://haacked.com/archive/2007/08/21/i-knew-how-to-validate-an-email-address-until-i.aspx/) is tough, so I try to avoid doing it myself. When I need to implement Email validation logic, I use a variation of this [answer from a StackOverflow](https://stackoverflow.com/a/1374644/1860002) question as I've been burnt too many times with Regex be it performance and looping or just being plain wrong:
```` C#
private static bool ValidateEmail(string email)
{
    try {
        return (new System.Net.Mail.MailAddress(email).Address) == email;
    }
    catch {
        return false;
    }
}
````

**Comment by hishamco** [comment]
@infofromca while we change the old `SystemNet.Mail` to `MailKit`, please check if the `MailKit` is already did sort of email validation or not

**Comment by Skrypt** [comment]
https://github.com/jstedfast/EmailValidation to evaluate as an option

**Comment by sebastienros** [comment]
Following with https://github.com/OrchardCMS/OrchardCore/issues/4124

**Pull request closed without merging**
