### PR TITLE
New Liquid Objects

### PR DESCRIPTION
**Pull request by hswami**
Added a way to access IConfiguration and IHostingEnvironment from Liquid.

### CODE REVIEW

**Comment by sebastienros** [comment]
No sure allowing Configuration access is wise in terms of security. It could contain connection strings, environment variables, ...

**Comment by hswami** [comment]
I disagree with the security assessment. Yes, there is potential for abuse ... but then how is it different from Razor pages having access to these as well? I can add @inject director to Razor pages and just as easily access these same values. Our use-case was to allow access to config and environment values that are needed both client-side and server-side ... for example, we now have to store ApplicationInsights instrumentation key in two places - appsettings.json and in custom settings ... appsettings.json allows for server-side config and custom settings is used to render client-side config. We have a few others that have much shorter life spans. The alternative for us would be to switch all our views from Liquid to Razor.

**Comment by sebastienros** [comment]
That exactly why we support Liquid, to make it safe, and only allow safe code on the admin ;)

**Comment by hswami** [comment]
Ah yes ... when you put it that way :). I guess that argument should be enough to justify the conversion from Liquid to Razor for those views that need this capability. I'll close this PR. Thank you for educating me. :)

**Comment by sebastienros** [comment]
One way which would be fine is that if we could detect that we are loading a liquid view from a file, and in this case then we could allow for more things.

**Comment by hswami** [comment]
Hmmm ... that is an interesting idea. To me it feels like we might be "polluting" the Liquid authoring experience ... one set of capabilities if the Liquid is authored one way, another set of capabilities if authored another way. It could lead to confusion. For e.g., if a site author/creator embeds a Liquid template via a file:text reference in a recipe, should this capability be allowed or not? We could document this expected behavior ... and it would make sense if you have a vision of what other kinds of things we would allow in Liquid that is coming from files and not content.

**Comment by hswami** [comment]
Meanwhile let me take a whack at it and see if I can figure out what you are proposing.

**Comment by sebastienros** [comment]
Yet another solution is to expose it as part of a different feature, or altogether in your own private module. I files an issue a while ago to be able to mark features as "security sensitive" to show users that enabling a feature might let users elevate their privileges. In some trustful environment it might be fine.

**Comment by hswami** [comment]
I think we'll go with the private module approach for now. I like that a lot better.

**Pull request closed without merging**
