### PR TITLE
Update AWS

### PR DESCRIPTION
**Pull request by hishamco**

### CODE REVIEW

**Comment by agriffard** [comment]
As @sebastienros stated in the previous Tuesday meeting, there is no need to update these AWS packages because they are changing every week without significative improvements.

**Comment by hishamco** [comment]
Maybe I didn't watch the last meeting, nothing but there are many packages we upgraded without significant improvements :)

FYI I accumulated 3 updates then I merged them into a single commit, anyhow let us decide what strategy we should go for updating packages if the case of AWS, I might merge it once a month

**Review by Piedone — CHANGES_REQUESTED** [review]
Please update to the current latest and then we can merge. Did you also test the S3 Media feature?

**Comment by hishamco** [comment]
> Did you also test the S3 Media feature

Nope, unfortunately, I didn't use Azure & S3 regularly

**Comment by Piedone** [comment]
You should test it though. Simply updating the package references is not enough, since it can break things.

**Pull request closed without merging**
