### PR TITLE
Fixing ModularBackgroundService logging and improving IsFatal() checks (Lombiq Technologies: OCORE-17)

### PR DESCRIPTION
**Pull request by Piedone**
It finally annoyed me too much that when the app is shut down there is a log entry every time from ModularBackgroundService which is not an actual error. Related to that I've found a couple of small inconsistencies or code styling issues.

### CODE REVIEW

**Comment by jtkech** [comment]
> It finally annoyed me too much that when the app is shut down there is a log entry every time from ModularBackgroundService

Good idea thanks

I think that the null-coalescing operator was not existing when i did it ;)

I'm also doing some cleanup in a PR, hope it will not in conflicts with yours

**Comment by Piedone** [comment]
C# is moving so fast that I'm not surprised to be able to nitpick such small things :).

**Comment by deanmarcussen** [comment]
Can you fix the merge conflicts @Piedone

**Comment by Piedone** [comment]
Sure, fixed them.

**Pull request merged**
