### PR TITLE
fix: workflow module page list issue when using PostgreSQL #14334

### PR DESCRIPTION
**Pull request by emrahtokalak**
fixes: https://github.com/OrchardCMS/OrchardCore/issues/14334

Fixed the query causing problems with Postgresql.

/cc @sebastienros or @MikeAlhayek

### CODE REVIEW

**Comment by MikeAlhayek** [comment]
@emrahtokalak how do it work on other database RDBMS? Can you run the same thing on other services like SQLite and or others?

**Review by jtkech — APPROVED** [review]
LGTM

**Comment by emrahtokalak** [comment]
> @emrahtokalak how did it work on other database RDBMS? Can you run the same thing on other services like SQLite and or others?

I tried it with PostgreSQL, SQLite and SQLServer, without any problems.

**Review by MikeAlhayek — APPROVED** [review]

**Comment by MikeAlhayek** [comment]
@emrahtokalak thanks for contributing!

**Pull request merged**
