### PR TITLE
Fix remaining routes to AdminUrlPrefix

### PR DESCRIPTION
**Pull request by deanmarcussen**
Routed to `/Admin/Feature` and/or tested (and was already good) the following

- Media
- Media Cache
- Content Picker
- Localized Content Picked
- Email
- Flows
- Menus
- Queries
- Themes
- Taxonomies 
- Widgets
- Features
- Recipes
- Background Tasks
- Demo Controller
- Remote Instance
- Templates
- Workflows
- Content list publish /delete/clone/unpublish and bulk actions

### CODE REVIEW

**Comment by deanmarcussen** [comment]
Yes/Maybe started looking at that a few hours ago. Not there yet though

**Comment by jtkech** [comment]
Yes maybe we could do some default mapping / convention but i don't see how we could manage the different patterns we are using.

E.g we already have this for all controllers

    routes.MapControllerRoute("Default", "{area:exists}/{controller}/{action}/{id?}");

But what could we do with the following different patterns

    "/ContentParts/{id}/Fields/{name}/Edit"
    "/Contents/ContentItems/{contentItemId}/Edit"

**Comment by deanmarcussen** [comment]
Was thinking of trying to do an ApplicationModel convention for any admin controllers, but so far it’s overriding the RouteBuilder routes.
Hopefully just an ordering issue...

Would be ideal if it can work as it would then apply a default for user admin controllers which could then be overridden, but will have to see if it can work first

**Comment by jtkech** [comment]
> Hopefully just an ordering issue...

Yes we can't set an order when using map route extensions but as i remember can be done at the route endpoint level. I would need more time to see what we could do and / or check what you already tried with the same code to see what happens and how we can tweak it.

**Comment by deanmarcussen** [comment]
> Yes we can't set an order when using map route extensions but as i remember can be done at the route endpoint level. I would need more time to see what we could do and / or check what you already tried with the same code to see what happens and how we can tweak it.

So this is what I tried with @jtkech 
```
    public class AdminRoutingConvention : IApplicationModelConvention
    {
        public void Apply(ApplicationModel application)
        {
            foreach (var controller in application.Controllers)
            {
                if (controller.ControllerName.StartsWith("Admin", StringComparison.OrdinalIgnoreCase)) || controller.Attributes.OfType<AdminAttribute>().Any())

                {
                    controller.Selectors[0].AttributeRouteModel = new AttributeRouteModel()
                    {
                        Template = "Admin" + "/[area]/[controller]/[action]/{id?}"
                    };
                }
            }
        }
    }
```

which would work, but it seems the only way to add a route via convention, is by adding an `AttributeRouteModel`. 
But when adding an attribute route, all conventional routes i.e.
`builder.MapAreaControllerRoute(...)` are then ignored.
So while this would work, it then means we would have to use attribute routing to define the custom route templates, which could be possible, but would need a special `[Route]` attribute to inject the `IOptions<AdminOptions>` and it would mean moving away from using conventional routing, and into attribute routing.
So too much of a breaking change IMO.

But there maybe other ways of doing it, that I haven't figured out ;)

However as I said on the other PR to just log a warning, this isn't a feature that everyone needs by any stretch of the imagination, so I am thinking that the best idea is to move the whole `AdminActionConstraint` to a feature.

I will do this on another PR

**Comment by jtkech** [comment]
@deanmarcussen i tried your model convention then indeed conventional routes are ignored

Then without your convention i 1st tried the following where you can see all the admin actions and those that are not mapped. This in a module `.Configure()` running later but before the mvc one.

RouteMapping

But using `routes.DataSoures.Endpoints` triggers some code on mvc side and then you can't map other routes anymore. My 1st goal was to only map the unmapped admin routes.

So finally i added a default route for each admin action even if it is already mapped. In that case we don't override anything, both routes will work. This is just the order of the registration that defines an order property (mvc increment the order). Notice that this is what we already do in the `OC.Mvc` startup but for all controllers. E.g `/orchardcore.admin/admin/index` already works because of this.

    routes.MapControllerRoute("Default", "{area:exists}/{controller}/{action}/{id?}");


So, i tried the following that seems to work in the `OC.Admin` module with a `ConfigureOrder => 1000 - 100` to run later but before the `OC.Mvc` one.

        public override int ConfigureOrder => 1000 - 100;

        public override void Configure(IApplicationBuilder builder, IEndpointRouteBuilder routes, IServiceProvider serviceProvider)
        {
            routes.MapAreaControllerRoute(
                name: "Admin",
                areaName: "OrchardCore.Admin",
                pattern: _adminOptions.AdminUrlPrefix,
                defaults: new { controller = typeof(AdminController).ControllerName(), action = nameof(AdminController.Index) }
            );

            var descriptors = serviceProvider.GetRequiredService<IActionDescriptorCollectionProvider>()
                .ActionDescriptors.Items
                .OfType<ControllerActionDescriptor>()
                .Where(d => d.ControllerName == "Admin" || d.ControllerTypeInfo.GetCustomAttributes<AdminAttribute>().Any())
                .ToArray()
                ;

            foreach (var descriptor in descriptors)
            {
                routes.MapAreaControllerRoute(
                    name: descriptor.DisplayName,
                    areaName: descriptor.RouteValues["area"],
                    pattern: _adminOptions.AdminUrlPrefix + "/{area}/{controller}/{action}/{id?}",
                    defaults: new { controller = descriptor.ControllerName, action = descriptor.ActionName }
                );
            }
        }

In these tests **i used your route template**, maybe we could check if the **prefix = controller name** so that it doesn't appear twice, and use more **descriptor infos as action parameters** to built a more complete default pattern. So here if an admin route has been mapped, e.g the `/admin` one, we will have 3 working routes in the following order. (here with `AdminUrlPrefix = "Admin"`).

    /admin  <= see above, lowest order, 1st processed
    /admin/orchardcore.admin/admin/index  <= see above
    /orchardcore.admin/admin/index  <= see in OC.Mvc startup, highest order, last processed

Hmm, but maybe this is not what we want, maybe we don't want that the last one works for admin actions, if so we would have to do the same but in the `OC.Mvc` startup and for non admin actions.

**Comment by deanmarcussen** [comment]
@jtkech this is pretty cool.

I need to try it tonight, and to understand what happens with the route ordering, in terms of how the `UrlHelper` will pick the most favoured route for route generation.

i.e. what happens with for example the email module if
```
/admin/orchardcore.email/admin/index  <= create from above 1st
/admin/email/index <= mapped by the email module 
/orchardcore.email/admin/index  <= see in OC.Mvc startup, highest order, last processed

```
so I will try to see and understand as well

but if we could do the same thing, but only for the non admin routes in `OC.Mvc.Startup` then **we do not need the admin constraint** at all, as the routes will not exist, I think.

and then the whole process is much more automatic for third party modules.

We would still want to do the mapping as is done in this pr, as it creates the more friendly routes, i.e. `/admin/email/index`

I did wonder if we might have a friendly url prefix, perhaps in the `manifest`, but equally that might provide an issue of collision, for third part modules. At least with the manual mapping we have done it is explicit, and any third part modules would have to choose their own friendly prefix, or just use the area as it does already.

So rather than jumping into the admin constraint as feature, e.g. https://github.com/OrchardCMS/OrchardCore/issues/5211 , I will take some more time to understand this and the implications.

Also of note. 
- I think we should probably leave the default pattern as you have used, because some modules that are using javascript need just a default pattern, rather than a more structured `route/id/routemarker/anotherid` so the route supports query string parameters. But I'm not sure what will even be in the route values, as I have not looked yet
- Need to check against all actions rather than just controllers, as the demo module demo's using the `[Admin]` attribute on just a controller action.

**Comment by deanmarcussen** [comment]
So @jtkech just tried with your code (but the opposite of, i.e. not an `AdminController`) in the OC.Mvc module to create default routes, replacing the `routes.MapControllerRoute("Default", "{area:exists}/{controller}/{action}/{id?}");` 

and it seems to work, need to do more testing.

Route generation as I mentioned above, still seems to be picking the nicer mapped route.
```
/admin/orchardcore.email/admin/index  <= create from above 1st
/admin/email/index <= mapped by the email module **`UrlHelper` is selecting this.**
/orchardcore.email/admin/index  <= see in OC.Mvc startup, highest order, last processed
```
So I'm still trying to understand how the ordering effect is working here, or if it's selecting it as a better match.

But looking good.

**Comment by jtkech** [comment]
Okay i agree and i let you decide what is better ;)

About ordering, i would need to check it more in details, but [see here](https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/Mvc.Core/src/Routing/ControllerActionEndpointDataSource.cs#L62) where mvc does `_order++`, so here it only depends on the registration order.

So, if for testing you were still using the `OC.Admin` with a `ConfigureOrder => 1000 - 100` the startup `Configure()` execution ordering would be: `OC.Email`, then `OC.Admin` then `OC.Mvc`. If so it would be normal that the route mapped by the email module is processed first.

Then, as i understood what you did, normally `/orchardcore.email/admin/index` would not work, if in the `OC.Mvc` startup you mapped routes as before but just for non admin actions. I didn't try it but it would be okay if we don't want any admin route that doesn't start with the admin prefix.

Finally, for doing these tests you needed to inject the `_adminOptions` in the `OC.Mvc` startup, not sure we can do this, hmm but why not by moving these options e.g in `OrchardCore.Abstractions`, i don't know.

**Comment by jtkech** [comment]
@deanmarcussen here the last idea i had, but you can do it in another PR, so i'll merge this one ;)

- Define an `IRoutePrefixProvider` that provides a prefix to be used with a controller name and / or an attrubute type, the admin one grabbing the admin prefix from the config as already done.

- Then we would lookup the controller actions once in the `OC.Mvc` that runs last and apply the default pattern as before unless for the controllers that match a given provider by name or attribute.

- Hmm, and when the **prefix == controller name**, to not have 2 segments with the same name, maybe pertinent for its actions to just use this default pattern `{controller}/{area}/{action}/{id?}` in place of `{prefix}/{area}/{controller}/{action}/{id?}`.

**Comment by jtkech** [comment]
> The AdminConstraint currently is checking for .StartsWith("Admin") and it should be .Equals("Admin")

Yes

    if (action.Controller.ControllerName.Equals("Admin", StringComparison.OrdinalIgnoreCase) ||
        action.Controller.Attributes.OfType<AdminAttribute>().Any())

**Pull request merged**
