### PR TITLE
Content items: Reset button in search

### PR DESCRIPTION
**Pull request by PiemP**
Related #7013 

clearfilter_button

### CODE REVIEW

**Comment by agriffard** [comment]
Which browser are you using?

On a Chrome (or Microsoft Edge), an `input type="search"` has an X button to clear the content when you start typing:

image

**Comment by PiemP** [comment]
> Which browser are you using?
Firefox

**Review by hishamco — CHANGES_REQUESTED** [review]
I'm stopping this because we already have similar issue, as @agriffard said the clear button is show up in the modern browsers

**Comment by hishamco** [comment]
It's addressed while I made this PR #6846

**Comment by PiemP** [comment]
I respect your decision, indeed before do this PR I have asked about the possibility to rewrite `ContentsAdminList-Search.cshtml` in my custom admin theme. If you believe is not necessary is good for me. 

For my opinion the "X" approach is good for a search engine where a user do a search and then want to reset the first search and do a new search, like google, but is not same good for a search field like this one where a user could do a search and then  want to see this field empty to list all items. In google you can't do an empty search, here could be have sense to allow user to have a button that clear the filter and submit it in one action.

Thank you and sorry, I have lost to do a search over closed issue before do this PR.

**Comment by Skrypt** [comment]
I can definitely see an issue that could be fixed. Here, there is no issue with the X button. It should only clear the text in the textfield. But having a button to reset the search would be more intuitive.

**Comment by agriffard** [comment]
Please merge dev.

Maybe with an icon and a toggle tooltip?
Here are some suggestions (Guess what is my preference):

image
image
image

**Comment by PiemP** [comment]
I have opted for the **times** icon and I have changed the title of the button from "Clear" to "Reset". 

For my opinion the **trash** icon and the **paper** icon doesn't fit the element and could give some misunderstanding. If you don't like the **times** icon (because too similar to the browser one) I have another option: a **broom** icon.

**Comment by PiemP** [comment]
@Skrypt In dark mode the search form buttons border "shine". Only to be sure, is it a desired behavior?

SharedScreenshot

**Comment by agriffard** [comment]
Please merge dev and fix the conflict.

**Comment by PiemP** [comment]
> Please merge dev and fix the conflict.

done.

**Comment by Piedone** [comment]
I sincerely apologize for us taking so much time here. I checked out the PR, going over old ones, and this would be quite useful.

Is this something you'd like to revisit any time soon or should we close?

**Comment by PiemP** [comment]
@Piedone probably is better to close it... when I have time I try to check this thing and if is necessary I open a new issue and a new PR. 

Thank you.

**Comment by Piedone** [comment]
I see, thank you for your quick reply.

**Pull request closed without merging**
