### PR TITLE
Improving default content picker editor

### LINKED ISSUE #2712: Content Picker: Does Not Return Items in Order Selected
The Content Picker in O1 returns the items in the order selected, but this isn't the case in Orchard Core. I think it's reasonable to expect the items will be returned in the order selected.

I added 5 Pages to a Content Picker, called Related, in the order of Page 1 -> Page 5 to the Landing Page in The Agency Theme:

content-picker

and using both a liquid template and a GraphQL query the items are not returned in order.

```twig
{% assign items = Model.ContentItem.Content.LandingPage.Related.ContentItemIds | content_item_id %}
<ul>
{% for item in items %}
<li>{{ item | display_text }}
{% endfor %}
</ul>
```

liquid

```GraphQL
{
  landingPage {
    related {
      contentItems {
        displayText
      }
    }
  }
}
```

```JSON
{
  "data": {
    "landingPage": [
      {
        "related": {
          "contentItems": [
            {
              "displayText": "Page 1"
            },
            {
              "displayText": "Page 2"
            },
            {
              "displayText": "Page 4"
            },
            {
              "displayText": "Page 5"
            },
            {
              "displayText": "Page 3"
            }
          ]
        }
      }
    ]
  }
}
```

### LINKED ISSUE #2713: Content Picker: Cannot Re-Order Items
In O1 we had the ability to re-order the items in the Content Picker, this is not the case in Orchard Core. This is really only necessary if the order is important ( https://github.com/OrchardCMS/OrchardCore/issues/2712 ), which I think should be the case.

I added 5 Pages to a Content Picker in the order of Page 1 -> Page 5 to the Landing Page in The Agency Theme. My only option is to delete an existing item or add a new one to the end of the list. I don't have the ability to insert an item between existing items or drag and drop items to different locations in the list.

content-picker

### PR DESCRIPTION
**Pull request by sebastienros**
Fixes #2713
Fixes #2712 

contentpicker

### CODE REVIEW

**Comment by davidhayden** [comment]
I like it a lot. Much better 👍

Drag and drop reordering is smooth. Deleting is easy. I like the type filtering capabilities. The Liquid filter is returning the items in the correct order.

GraphQL doesn't return the items in the correct order, but that's less important to me and can be opened as a separate issue.

Awesome!

**Comment by sebastienros** [comment]
I fixed the order in graphql, and also ensure we returned the published versions only.
But you didn't mention that these changes also works with live preview ;)

**Comment by Skrypt** [comment]
all pretty and shiny ❤️

**Pull request merged**
