### PR TITLE
Code Mirror: Cloudflare cdn

### PR DESCRIPTION
**Pull request by agriffard**
https://cdnjs.com/libraries/codemirror

Related to #8125

@giannik Can you please test and tell me if you have less errors with this cdn?

### CODE REVIEW

**Comment by giannik** [comment]
getting 
File not found: https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.59.0/lib/codemirror.css

**Comment by agriffard** [comment]
> getting
> File not found: https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.59.0/lib/codemirror.css

Ok, css url fixed.

**Comment by giannik** [comment]
worked for me.

**Comment by Skrypt** [comment]
I can't asset that this work. It's a CDN network issue thing here. Are we changing for one that will be accessible for @giannik and not for other people? We're playing russian roulette 😉

**Review by Skrypt — COMMENTED** [review]
I can't asset that this work. It's a CDN network issue thing here. Are we changing for one that will be accessible for @giannik and not for other people? We're playing russian roulette 😉

**Comment by deanmarcussen** [comment]
Is this issue only occuring because of an upgrade to codemirror? i.e. if it was fine on 5.58, but isn't on 5.59 we would be better to revert the version change until it is sorted by the existing cdn.

**Comment by agriffard** [comment]
I had used jsdelivr because cloudflare took many days before providing the 5.59.0 version of Code Mirror.

**Comment by agriffard** [comment]
Cloudflare seems to be a standard cdn while jsdelivr only exposes the npm package content.

**Comment by Skrypt** [comment]
@deanmarcussen It's not about the issue with codemirror we had. It's just a CDN change. If it works. merge it. No big difference to me if nothing breaks.

**Pull request merged**
