### PR TITLE
Remove deprecated members

### PR DESCRIPTION
**Pull request by hishamco**
Address #6704, this remove all the `Obsolete` members except `WithCulture()` which I still have a doubt to mark it as `Obselete` because it's controlled by ASP.NET Core team

### CODE REVIEW

**Comment by deanmarcussen** [comment]
Placing a block on this. Here you have not read the suggestion or action @hishamco

**Comment by hishamco** [comment]
Nah, it is my bad ;) what about removing other obsolete methods?

**Comment by deanmarcussen** [comment]
No, don't remove the other obsolete methods. There will be a suitable time to do this (perhaps after v1 we will clean up much old code, not just obsolete members). The time to do this is not now.

You can close this pr

**Comment by hishamco** [comment]
If I'm not wrong `Obsolete` member should be removed before major releases, I can keep this open for the future or close it if you wish

**Comment by agriffard** [comment]
GetContentItemIdByHandleAsync managed in #6747

**Comment by petedavis** [comment]
I have just tried building an running an OC website using .net 5.0 preview-8 and getting a missing method exception for `Microsoft.AspNetCore.Mvc.Localization.IHtmlLocalizer.WithCulture(System.Globalization.CultureInfo)`

```
System.MissingMethodException: Method not found: 'Microsoft.AspNetCore.Mvc.Localization.IHtmlLocalizer Microsoft.AspNetCore.Mvc.Localization.IHtmlLocalizer.WithCulture(System.Globalization.CultureInfo)'.
   at OrchardCore.Localization.NullHtmlLocalizerFactory.Create(Type resourceSource)
   at Microsoft.AspNetCore.Mvc.Localization.HtmlLocalizer`1..ctor(IHtmlLocalizerFactory factory)
   // DependencyInjection stack here...
   at OrchardCore.Environment.Shell.Scope.ShellScopeServices.GetService(Type serviceType) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.Abstractions\Shell\Scope\ShellScopeServices.cs:line 16
```

**Comment by agriffard** [comment]
Please merge dev to solve conflicts and remove the code related to ContentRazorHelperExtensions.cs, fixed by #6747.

**Comment by agriffard** [comment]
@deanmarcussen Please review so we can see what is the status of obsolete methods.

**Review by deanmarcussen — COMMENTED** [review]
Impossible to review due to bad merges.

I would not want to remove any of the fields extension code as it is tightly tied with migration code which should be removed at the same time.

As I already said after 1.0 not before, when we are able to make an effort towards cleaning/resetting migrations

The serilog related bits could go on a new pr, and the comment re aspnetcore 5 and the culture seems relevant.

**Comment by hishamco** [comment]
> As I already said after 1.0 not before

Removing after major release is a breaking changes, I understand the risk you are talking about, but if there are totally not used we can remove them or wait until `2.0.0` ;)

**Comment by agriffard** [comment]
Closing the dontmerge labels.

**Pull request closed without merging**
