### PR TITLE
Added missing namespace `OrchardCore.Taxonomies.Helper` to `TaxonomyOrchardHelperExtensions.cs`

### PR DESCRIPTION
**Pull request by Diman96**
because it does not allow to reference global namespace in Razor views.

### CODE REVIEW

**Comment by deanmarcussen** [comment]
The intended usage of these extensions is
`@Orchard. GetTaxonomyTermAsync`

where Orchard is the `IOrchardHelper`

What problem are you having that is making you want to do this?

**Comment by xperiandri** [comment]
@deanmarcussen, looks like someone forgot to add namespace to the file and the extensions class appeared in `global` namespace.
Those `GetTaxonomyTermAsync` cannot be imported as extension method anyhow in Razor. And an explicit call also cannot be done.

**Comment by deanmarcussen** [comment]
This is all by design (all the `IOrchardHelper` extension methods are designed this way - and they all work fine in Razor)

can you share some code where it is not working?

**Comment by Diman96** [comment]
@deanmarcussen  
`GetTaxonomyTermAsync` not found.
`<PackageReference Include="OrchardCore.Taxonomies" Version="$(OrcahrdCoreVersion)" />`

image

**Comment by deanmarcussen** [comment]
It's because you're passing a `dynamic`

You can't pass dynamic to extension methods, you have to cast them first.

`@await Orchard.GetTaxonomyTermAsync((string)Model.ContentItem.Content.... )`

**Pull request closed without merging**
