### PR TITLE
Allows to add routes after the tenant default mvc routes

### LINKED ISSUE #3341: MapSpaFallbackRoute does not work
This is minor bug, but one that will pop as people try to use Orchard with spa frameworks.

If you set a MapSpaFallbackRoute when using MVC, it gets ignored.

So if you visit your home page, and your spa kicks in and adds say a round like /cart, this works fine on load up.

But if you do a manual browser refresh, it doesnt work. The fallback is ignored

tenantRouteBuilder.MapSpaFallbackRoute(
                          name: "spa-fallback",
                          defaults: new { controller = "Home", action = "Index" }
                );

And sends you to

image

### PR DESCRIPTION
**Pull request by jtkech**
Fixes #3341.

Need to be tried by @nigel-dewar

### CODE REVIEW

**Comment by sebastienros** [comment]
Why 200? Why not -1 so that any other one is forcibly after this one.

**Comment by jtkech** [comment]
Oh, i think that it still need to be done after the other ones so that modules can override routes as before by adding their routes before. And here it is to allow to register routes last to behave as fallbacks .

But not sure now ;)

**Comment by jtkech** [comment]
@sebastienros okay i did the change by reusing only one `Mvc.Core.Startup` whose `Order` was already negative -200.

**Comment by jtkech** [comment]
@sebastienros i will revert the last change because then the generated urls with an url helper are not the same. E.g with `TheTheme` the menu item for login will send you to

    https://localhost:44300/OrchardCore.Users/Account/Login

In place of `https://localhost:44300/Login`

**Comment by sebastienros** [comment]
My question is "where is this value 200" coming from? And why devs who add routes should have to care about this?

**Comment by jtkech** [comment]
It comes from nowhere ;) just to have a relatively high value to normally run `Configure()` after others. As the current order has a negative value of -200 to normally run `ConfigureServices()` before others.

Then, as before devs don't have to care about the `Order` to add routes that may override default ones. They need to pass an `Order` > 200 only when they want to add routes intended to be **used as fallbacks** e.g with an spa system. Otherwise we would need another extension point or a `postConfigure` parameter.

**Note:** As we use somewhere the regular `services.AddMvc()`, i would like to use somewhere the regular `app.UseMvc()` so that it would be easier to maintain. Do you think it's worth to work on it?

**Comment by jtkech** [comment]
@sebastienros 

So, for testing, i was able to use the regular `.UseMvc()` but i needed to use

    mvcOptions.EnableEndpointRouting = false // true by default

Because of the new Endpoint Routing system, and as said in the doc

> The endpoint routing system doesn't support IRouter-based extensibility, including inheriting from Route.

And this is what we are using e.g for our `AutorouteRoute` and `HomePageRoute`.

I think we will have to do the migration to this new system more based on endpoint middlewares passing endpoint infos to other middlewares, e.g the MVC middleware to select a controller action.

I will need to learn it more in depth to do this migration through another PR. At least here i began to use the regular `.UseMvc()`, and when we will be able to replace our custom `IRouter`, we will just have to let `mvcOptions.EnableEndpointRouting = true` as it is by default.

**Comment by sebastienros** [comment]
Yes, we need a way to use EndpoitRouting, even if it means to refactor Home and Autoroute.

**Comment by jtkech** [comment]
Okay, from now through this PR, or later through another one?

**Comment by jtkech** [comment]
@sebastienros in my last commit

- I introduced the startup `ConfigureOrder` property which defaults to the `Order` property if not set. It allowed me to revert back to only have one `OC.Mvc.Core.Startup` class.

    Because of my changes i also renamed `IModularTenantRouteBuilder` to `ITenantPipelineBuilder`.

- About routes ordering, the "problem" is that people are used to call `.UseMvc()` e.g to add some routes, then some default routes and then they have the ability to add at the end fallback routes. Here, default mvc routes are added through `OC.Mvc.Core.Startup` with a `ConfigureOrder` of 1000 so that we can add fallback routes by passing an higher value. Maybe better to have an helper for this? Let me know.

- Hmm, this let me think that we still can't add a middleware (not routes) after `app.UseRouter()` that is called here e.g through `app.UseMvc()` (in a future version we will add endpoint middleware(s)). But i think we can already do the same by using a tenant `IStartupFilter` and by doing something like this.

        public class SomeStartupFilter : IStartupFilter
        {
            public Action<IApplicationBuilder> Configure(Action<IApplicationBuilder> next)
            {
                return app =>
                {
                    next(app); // called 1st
                    app.UseSomeMiddleware();
                };
            }
        }

    But it would be less natural to just use `app.UseSomeMiddleware()`. Hmm, maybe an helper here also.

- Finally, about endpoint routing, it is not so obvious but i made some progress. That said i think that it is too soon, in 3.0 there will be more types and helpers and with the concept of dynamic endpoint routing.

So, i don't think i can do more in this pr, i think that i will create another branch (based on this PR if it is merged), even before 3.0, to continue to work on endpoint routing.

**Comment by jtkech** [comment]
@sebastienros for infos.

We will have no choice, we will need to use the regular `UseMvc()` as done here, even we still not use endpoint routing, because e.g `MvcRouteHandler` will be an internal class in 3.0.

I started working to migrate to 3.0 to see if there are more helpers to use endpoint routing. I will create a new PR for this migration, and with more comments because there are other breaking changes e.g related to runtime compilation.

**Comment by jtkech** [comment]
Anyway, all will change with the new endpoint routing sytem in 3.0.

**Pull request closed without merging**
