### PR TITLE
use the proper button #mediaBodySelectButton to unbind event handler

### PR DESCRIPTION
**Pull request by scil**
for `HtmlBodyPart`, not for `HtmlField`

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/OrchardCMS/OrchardCore?pullRequest=10657) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/OrchardCMS/OrchardCore?pullRequest=10657) before we can accept your contribution.<br/><br/>:x: scil [sign now](https://cla.dotnetfoundation.org/OrchardCMS/OrchardCore?pullRequest=10657)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/OrchardCMS/OrchardCore?pullRequest=10657) it.</sub>

**Comment by sebastienros** [comment]
Shouldn't you run the assets building pipeline to update the minimized versions?

**Comment by Skrypt** [comment]
The same issue needs to be also fixed in different modules. The PR is incomplete.

**Comment by hishamco** [comment]
@scil please update the PR and consider Seb and Jasmin feedback

Thanks

**Review by Skrypt — APPROVED** [review]

**Review by hishamco — APPROVED** [review]

**Pull request merged**
