### PR TITLE
jQuery UI 1.13.1

### PR DESCRIPTION
**Pull request by agriffard**
https://www.npmjs.com/package/jquery-ui/v/1.13.1
https://blog.jqueryui.com/2022/01/jquery-ui-1-13-1-released/

### CODE REVIEW

**Comment by Skrypt** [comment]
Was it not causing issues?

**Comment by agriffard** [comment]
Admin menu and menu sortable by drag and drop does not work anymore.

**Comment by Skrypt** [comment]
I'm surprised about the admin menu though. It's not supposed to be using JQuery. It's using Bootstrap 4 collapsible. Probably, the issue is that javascript stops executing because of JQueryUI.

**Comment by agriffard** [comment]
This admin menu:
image

**Comment by Skrypt** [comment]
Admin menu management feature.

**Comment by deanmarcussen** [comment]
Yeah I thought we reverted this back down to fix that issue. Did you try it with the new version?

**Comment by Skrypt** [comment]
I think that the issue is that the JQueryUI sortable is not working anymore. We said that we should refactor this by using sortable.js or something like that if I remember correctly. But don't take me to my words, make a double check, these days my brain needs a replacement 😉

**Pull request closed without merging**
