### PR TITLE
Implemented FavIcon module with Razor tag helper and Liquidtag.

### PR DESCRIPTION
**Pull request by Diman96**

### CODE REVIEW

**Comment by xperiandri** [comment]
@sebastienros, @jean we have discovered such an interesting implementation of settings
https://github.com/EtchUK/Etch.OrchardCore.Favicon/blob/master/Migrations/create.recipe.json
Where the author delegated setting UI creation to Orchard via subclassing from `ContentPart`
https://github.com/EtchUK/Etch.OrchardCore.Favicon/blob/0599044c4c81deaa06ee896cd966934bc712b429/Models/FaviconSettings.cs#L8

What do you think about that approach?
What is the right way to incorporate different Orchard Core pickers (like media library picker) into a module settings UI?

**Comment by sebastienros** [comment]
@xperiandri it's not uncommon to use content fields for settings. This way you can reuse existing editors. What is less common is to provide a POCO mapping to this content part, though this is not the first we have seen it. This can be even simpler by just defining properties with the same type and name of the fields on the content part class. Here @peterkeating decided to create nicer accessors to check if the values were present, and only provide read access, which is a nice touch IMO.

Honestly it took me a couple minutes to realize what was happening and remember this technique.

**Comment by peterkeating** [comment]
The primary reason for using content fields was I didn’t want to have to define front-end logic for selecting media from the media library within the edit template for the part. When OrchardCore updates the front-end for interacting with the media library often changes. Using a media field means I don’t have to worry about any front-end changes around interacting with the media library, the media field handles it all for me.

**Comment by xperiandri** [comment]
So that we just inherit ContentPart defining properties of type https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.Media/Fields/MediaField.cs?

**Comment by xperiandri** [comment]
What if we also want color pickers that can be rest to `null`. Is it possible with this approach?

**Comment by sebastienros** [comment]
@Xceno In this case you need your field to support having empty values. That's very common to have a field be required or not. Also with a default value. Then your `ColorField` (note I am not using the notion of Picker which is specific to the editor) will have a nullable property to represent the color.

And BTW we don't have a Color Field as of no, so this would be a nice contribution. The storage should probably be in a very standard form like R+G+B+A. And pickers could be with inputs, and also a color picker.

**Comment by xperiandri** [comment]
There is a standard browser UI for that.
So I also need a trash bin icon button to reset the value, right?

Which project to add color field?

**Comment by sebastienros** [comment]
Try to follow what is used elsewhere, so yes, the trash icon is best here. Look at the media field for the exact same one.
And ColorField can be placed in ContentFields module.

Note that @hishamco has created liquid filters to manipulate colors, converting to/from hsl, and changing alpha levels. This will be useful in templates with this field. I could see a demo template with the preview feature where you pick a color, and you see gradients displayed live as you change the value of the picker.

**Comment by xperiandri** [comment]
Is there a sample of?
> This can be even simpler by just defining properties with the same type and name of the fields on the content part class.

Becuse it is not clear how to set field settings

**Comment by xperiandri** [comment]
Also I copied this stuff
https://github.com/OrchardCMS/OrchardCore/blob/a1fd797821fc2cbe8ee002c7f359ab482accd9f9/src/OrchardCore.Modules/OrchardCore.FavIcon/ServiceCollectionExtensions.cs#L57

What is the purpose of this?
Can I write https://github.com/EtchUK/Etch.OrchardCore.Favicon/blob/master/Migrations/create.recipe.json there in code?

**Comment by xperiandri** [comment]
How can we render a native media picker from our settings view?

**Comment by Piedone** [comment]
Is this something you'd like to revisit any time soon @Diman96 (given that this is a draft PR) or should we close?

**Comment by Piedone** [comment]
Closing due to inactivity.

**Pull request closed without merging**
