### PR TITLE
Use DateOnly & TimeOnly for DateField & TimeField

### PR DESCRIPTION
**Pull request by hishamco**
@sebastienros are `DateOnly` & `TimeOnly` supported in YesSQL? Seems I need to refresh my mind

### CODE REVIEW

**Comment by sebastienros** [comment]
YesSql doesn't support it. And it's an unnecessary breaking change in OC.

**Comment by hishamco** [comment]
Is there any plan to support it in YesSQL? Because there are database types for that

Another thing related to why we have `DateField`, `TimeField` while we can use `DateTimeField`

**Comment by MikeAlhayek** [comment]
> And it's an unnecessary breaking change in OC.

@hishamco can we close this pr?

**Comment by MikeAlhayek** [comment]
sorry accidentally merged main

**Comment by sebastienros** [comment]
Closing it @hishamco but if you want to try implementing it in yessql feel free to do. Might not be easy though if the types are not supported in some dbs, might need to still use datetime internally.

**Comment by hishamco** [comment]
I will have a try :)

**Pull request closed without merging**
