### PR TITLE
Remove unnecessary WriteTo() in FludiValue subclasses

### PR DESCRIPTION
**Pull request by hishamco**

### CODE REVIEW

**Comment by MikeAlhayek** [comment]
@hishamco why was this merged without an approval? You were one of the biggest advocates to not merging PR without approvals. 

This is likely a breaking change and should not not be part of the 2.x release. You could mark these useless methods as obsolete meanwhile and remove them in v3.

**Comment by hishamco** [comment]
@MikeAlhayek I just added this recently, so there are no breaking changes, just removing unnecessary overload

Related to https://github.com/sebastienros/fluid/pull/711

**Comment by MikeAlhayek** [comment]
It is still a binary breaking change and should not be taking in 2.x

**Comment by hishamco** [comment]
Why it's a binary-breaking change. As I mentioned earlier it wasn't there in the previous releases

**Pull request merged**
