### PR TITLE
improved wysiwyg functionality to HtmlField editor

### PR DESCRIPTION
**Pull request by PiemP**
added an option for a new HtmlField editor that use the resize plugin of trumbowyg editor to add image from OrchardCore assets.

added an option for a new HtmlField editor that use tinymce to edit HTML content.

see [More Wysiwyg editor: insert image from assets, see the image and resize it](https://github.com/OrchardCMS/OrchardCore/issues/4468)

### CODE REVIEW

**Comment by agriffard** [comment]
I don't think that TinyMce have the kind of license model that we are expecting in Orchard Core.

**Comment by PiemP** [comment]
WIP: 

- [ ] remove TinyMce and relative files
- [ ] improve resize code on trumbowyg with canvas resizer like TinyMce do
- [ ] upgrade trumbowyg files to the last version on OrchardCore.Resources 
- [ ] add table plugin on trumbowyg
- [ ] clean and minify javascript code
- [ ] rename "More" from file names

**Comment by PiemP** [comment]
Last update:
demo_2 0

**Comment by stantoxt** [comment]
@PiemP HtmlBodyPart also need this.I try it ,but I cant see image in the editor.

**Comment by PiemP** [comment]
@stantoxt I try to add the my version of HTML editor in HtmlBodyPart, theres no problem about it: I'm waiting for have feedback from someone like you, because I'm not a javascript developer and I don't know if I have do something that is really useful.

**Comment by sebastienros** [comment]
Can you explain what are the issues you are fixing with this PR? I don't see what's new from the current state of the code. For instance how is that different from the default jquery-resize plugin?

And also how you decided to fix it.

**Comment by PiemP** [comment]
Hi @sebastienros, sorry I'm pretty new to the team work and probably I've made something in the wrong way. 

No issue is concerned to this PR, I have the need to see image inside the HTML editor of OrchardCore HtmlField and HtmlBodyPart, but actually this functionality is not enabled on the standard WYSIWYG editor. 

For this reason I tried to add an editor with TinyMCE support, but @agriffard say to me that is not compatible with OrchardCore licence. 

Then I saw the resize funciontality of trumbowyg and I seen that this lack a lot: 
* It doesn't allow to move image when it is enabled
* It doesn't show where you can do the resize operation over the image (jquery-resizable doesn't support the resize operation over every image "corner" but only over one corner: the bottom-right ones)
...

And I decide to try to improve this and to add it with the trumbowyg table plugin to the default WYSIWYG editor of OrchardCore HtmlField to create a new WYSIWYG editor more user friendly. I don't have modified jquery-resizable, I have changed the trumbowyg resize plugin "behavior". 

I'm waiting about some feedback about it because I'm not a javascript developer or a designer and I believe my work can have some improvements (like add the support to orchardcore resize filter, but actually I don't know if the Filter come before the Html render inside the page) or is made in wrong way or have use something that you are removing from OrchardCore.... I don't know...sometimes I believe that I have "reinvent the hot water" in a bad way :D .  

Hope what I wrote in this post is understandable :D .

**Comment by agriffard** [comment]
Thank you for your work @PiemP .

To summarize:
- You updated Trumbowyg to version 2.19.1: I created the PR #4651 to update the library and allow to specify Options you want to use (buttons and plugins). It will be merged soon.
If you look at it, it will allow you to understand how we handle npm packages, assets (+ gulp build), ResourceManifest, Script Tag helpers and Field/Part (HtmlBody) editors in Orchard Core.

- You want to be able to insert img with their url from the 'Insert image' modal, instead of the Liquid code: This is what I was asking here: #2822. 
@sebastienros suggested to allow this behaviour based on an editor setting.
This should be done in a separate PR.

- You made a custom Trumbowyg plugin to allow to Insert an Image from the library with its url and allow to resize it.
This should stay two different plugins.
Also, to make it work the way you wanted, you changed the way the modal Wrapper, which is not the best way to do it (it should be in the Editor view).

- You want to be able to resize images in Trumbowyg: I faced this resizing problem (https://github.com/Alex-D/Trumbowyg/issues/1045) because, in OC, jQueryUI confilcts with jQuery-resizer (see https://github.com/RickStrahl/jquery-resizable/issues/25).
It seems you tried to find a way to fix it. 
The **best way to handle this issue** would be to submit your fix to the Trumbowyg repo and if it is accepted, it will be integrated in a future version and we will update it in OC.

**Comment by PiemP** [comment]
Thank you too @agriffard for your answer, I appreciate it. 

I need more help about the way to do some stuffs: 
> * You want to be able to resize images in Trumbowyg: I faced this resizing problem ([Alex-D/Trumbowyg#1045](https://github.com/Alex-D/Trumbowyg/issues/1045)) because, in OC, jQueryUI confilcts with jQuery-resizer (see [RickStrahl/jquery-resizable#25](https://github.com/RickStrahl/jquery-resizable/issues/25)).

About this I think to submit my updates to trumbowyg (and it is my first step) but for the issue with JQueryUI resizable plugin I don't know how to proceed: the JQuery implementation is pretty distant to the Rick Strahl ones and the version of Mr. Strahl is more easy to understand for me... @agriffard do you think I can ask to Mr. Strahl to change his function name to avoid the issue? I do the PR to his project by myself to change it if is necessary ... or you believe that is better o use JQuery solution to resize images?

**Comment by agriffard** [comment]
I guess you are talking about this change you made:
```
    // rename to avoid conflict with jquery-resizable
    $.fn.uiresizable = $.fn.resizable;
```

The jquery-resizer issue is now 2 years old, @RickStrahl made it quite clear that it won't be fixed:
https://github.com/RickStrahl/jquery-resizable/issues/25#issuecomment-356285321
> if you're using jquery-ui you certainly don't need this plugin

I tried to make a PR #4728 to not use jQueryUI everywhere but after a discussion with @sebastienros yesterday, the suggested change will certainly not be accepted and the PR will be closed.

**Pull request closed without merging**
