### PR TITLE
Fix GetTokenFilterDescriptor() in ElasticIndexManager

### PR DESCRIPTION
**Pull request by hishamco**

### CODE REVIEW

**Comment by MikeAlhayek** [comment]
@hishamco in PR's like this, it would be very helpful to see what issue is being fixed (link it to an issue). 

From the look of it using `property.PropertyType` is better than using string. maybe PropertyType is an integer or any other type. Why string is better that the actual type?

**Comment by sebastienros** [comment]
@hishamco Any more info?

**Comment by hishamco** [comment]
The issue is not with property type, if you look closely before the change the statements are similar, I will look who did that before and ping him if he is active, otherwise we should decide about this

**Comment by sebastienros** [comment]
We reviewed it and the other related PR/issues and we found a better, simpler way to handle all cases for all filters. Mike will update his PR with that. It will use STJ serialization which is supported natively by these classes to read the configuration.

**Comment by MikeAlhayek** [comment]
Closing this PR as we have made lots of changes to ElasticIndexManager in current version and in v3.0

**Pull request closed without merging**
