### PR TITLE
Adding field editors

### PR DESCRIPTION
**Pull request by sebastienros**
Fixing #1064

### CODE REVIEW

**Comment by sebastienros** [comment]
🔥 🔥 🔥 🔥 🔥 🔥 
BOOM !!!! 💥 💥💥💥💥💥 
🔥 🔥 🔥 🔥 🔥 🔥 

Thanks @jtkech and @Skrypt for helping me

**Comment by agriffard** [comment]
When I add a BooleanField called Featured in a Client content type, there is an error:
...src\OrchardCore.Modules\OrchardCore.ContentTypes\Views\Admin\EditField.cshtml line 37

'EditFieldViewModel' does not contain a definition for 'Shape' and no extension method 'Shape' accepting a first argument of type 'EditFieldViewModel' could be found (are you missing a using directive or an assembly reference?)
` @if (Model.Shape.Content != null)`

**Comment by agriffard** [comment]
When I add a TextField with a Multineline Editor and I enter a Color (ex: red), the setting is not stored the first time. If I go back in Edit, it is blank and if I reenter it and save, it works this time. 
I tried multiple times and it never works just after that the field has been added.

**Comment by sebastienros** [comment]
@agriffard thanks, and I think I know why.

Also @Skrypt @jtkech we can actually completely remove the new interface and just use the existing settings drivers, because we target a specific zone in the same shape. I am doing it now.

**Comment by jtkech** [comment]
@sebastienros cool, i will take a look more in depth but first as @agriffard i also saw some little issues i'm working on, this around **decimal** number formats according to the culture.

@Skrypt when the current issues will be fixed, i will be open to do the same but for content parts.

### E.g with the html5 `type="number"` in the spinner editor

- We would need to always pass string values in invariant culture to get it first working.

- Then it displays the value according to the browser culture but which may not be the same as the server side `CurrentUICulture`.

- Then the values are always posted back in invariant culture and the driver which use the `CurrentUICulture` can also fail to parse...

As i remember that's why in O1 we always use `type="text"`. So maybe we would need to get rid of the spinner editor (`type="number"` is also used for the scale settings but here there is no decimal part).

Or implement it with a script which will render the value according to the server side `CurrentUICulture`. But the script would need to be culture aware, so not so easy. Note: [i did a PR in O1](https://github.com/OrchardCMS/Orchard/pull/5511) which was using `Globalize.js` to do this kind of things but i don't remember the details.

- So, right now i will first check all other number editors when using a decimal part.

**Comment by Skrypt** [comment]
orchard-screencast

Here is what I did last night. Let me know if you like or not. Comments always appreciated. I looked at @jtkech branch and he added a ViewModel, I'm going to see with him later today why he used that.

**Pull request merged**
