### PR TITLE
Update DataMigration.cs comments

### PR DESCRIPTION
**Pull request by deanmarcussen**

### CODE REVIEW

**Comment by agriffard** [comment]
It seems you cannot use `<` or `>` because it is in a `<code>` markup.

**Comment by deanmarcussen** [comment]
Meh, I'll have to read the docs ;)

**Comment by agriffard** [comment]
Isn't it supposed to be : `&lt;int&gt;` ?

**Comment by deanmarcussen** [comment]
Yes, ty @agriffard had no idea you could use that in comments, but of course it is just xml. Cheers

**Pull request merged**
