### PR TITLE
Recipes: Order by display name

### PR DESCRIPTION
**Pull request by agriffard**
In each group category, order the recipes by display name.

Also: Refactor the UI to display more condensed information.

### CODE REVIEW

**Comment by agriffard** [comment]
Before:

image

After:

image

**Comment by agriffard** [comment]
Currently with my sample recipes:

image

**Comment by Skrypt** [comment]
Looks good but what are these numbers?

**Comment by agriffard** [comment]
> Looks good but what are these numbers?

This is how I named my recipes, in order to display them in that order and the user that setup a site after a blank recipe install can execute them one after another.

**Comment by Skrypt** [comment]
I would have thought that they would have been ordered by number since it's their "DisplayName". Strange unless I don't understand. Else the PR looks good.

**Comment by agriffard** [comment]
> I would have thought that they would have been ordered by number since it's their "DisplayName". Strange unless I don't understand. Else the PR looks good.

Precisely. It is how it looks like with the latest dev package, not with the PR change.

**Pull request merged**
