### PR TITLE
Changed GetCenters() to GetAnchors() in media documentation

### PR DESCRIPTION
**Pull request by netwavebe**

### CODE REVIEW

**Comment by Skrypt** [comment]
There is a CI issue here. It did not trigger the CI build probably because you only modified documentation.
/cc @jptissot

**Comment by hishamco** [comment]
@Skrypt I noticed that in my previous two PRs

**Comment by jptissot** [comment]
That is wanted behavior, no? Docs modifications should not trigger the ci!

**Comment by Skrypt** [comment]
For pull request true. But the issue then is that we can't merge it if the CI doesn't confirm a sucessful build. I guess only @agriffard can.

**Comment by jptissot** [comment]
Ahh I see. Can you file an issue ?

**Pull request merged**
