### PR TITLE
Organize & fix namespaces for unit tests

### PR DESCRIPTION
**Pull request by hishamco**

### CODE REVIEW

**Comment by agriffard** [comment]
Do you mean Organize?

**Comment by hishamco** [comment]
> Do you mean Organize?

Fix thr typo ;)

**Comment by sebastienros** [comment]
Why? Maybe `Tests` seems nicer at the end, but then it's not matching the folder structure. Not sure the changes make the whole thing "better" ?

**Comment by hishamco** [comment]
Its a common thing I notice in ASP.NET Core repos, BTW it reduces the namespace uses for an APIs, say:

`X.Y.MyClass` is the class to be tested, so in the unit test when we use `X.Y.Tests`, `MyClass` is already resolved. IMHO ending with Tests is much nicer and make everything consistent

**Comment by Piedone** [comment]
I don't really see any benefit of these changes. Removing "OrchardCore." from the folder/namespace names is not a huge gain but using different namespaces than folder structure sets us up for needless busywork trying to maintain it (and it goes against the general .NET recommendations as well as what VS and other IDEs generate).

So, this is a close from me.

**Pull request closed without merging**
