### PR TITLE
Set up CodeRabbit for AI code reviews (Lombiq Technologies: OCORE-159)

### LINKED ISSUE #15439: CodeRabbit for AI code reviews
**Attention, contributors:** See https://github.com/OrchardCMS/OrchardCore/issues/15439#issuecomment-2073645591.

### Is your feature request related to a problem? Please describe.
PRs usually sit open for too long (related: https://github.com/OrchardCMS/OrchardCore/issues/15029), partially due to nobody coming to review earlier.

### Describe the solution you'd like
We could try [CodeRabbit](https://coderabbit.ai/), which is an AI code review bot: it uses ChatGPT and perhaps other similar LLM tools to provide code review comments. Additionally:

- You can have a discussion with it. 
- Tt's capable of learning the habits of a project.
- When there's an issue linked, it can verify whether the PR addresses the issue.
- It can summarize the changes of a PR.
- Reviews are done either automatically or on-demand (requested with a comment).
- It's free for open-source projects.

For a while now we at Lombiq tested it on a couple of repositories. It's a mixed bag, with perhaps 50-50 useful and useless comments, but the experience varies greatly PR by PR. Some examples:

- [Useful comment](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/pull/649#discussion_r1443087533).
- [Mixed bag for the whole PR](https://github.com/Lombiq/Helpful-Libraries/pull/231).
- [Mostly useful comments](https://github.com/Lombiq/UI-Testing-Toolbox/pull/216#pullrequestreview-1799255257)
- [No actionable comments despite enough code changes](https://github.com/Lombiq/GitHub-Actions/pull/302#pullrequestreview-1828069907)

So, I'm not entirely convinced, but we could try if it's useful for us and helps with reviews, or it's more like noise.

- [x] Set it up first just from the CodeRabbit UI so it can be tested immediately.
- [x] Once we figured out how to configure it, move the config to a file. See https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/pull/662/files for a good starting point.
- [x] Document it for contributors that you'll get AI reviews, and take them the same as human reviews. See https://github.com/OrchardCMS/OrchardCore/issues/15029 for contribution docs too.

This will throw off our [community metrics](https://github.com/OrchardCMS/OrchardCore/issues?q=is%3Aopen+is%3Aissue+label%3A%22community+metrics%22) a bit, since the time to first reply for PRs will be down to a few minutes, so we won't be able to track the time to human reviews (and the useful remaining metric will be time to close). Also, if as a reviewer you scan for PRs to review by looking at the number of comments (as an indicator that somebody else reviewed already) then that won't apply anymore. Using the ["No reviews" filter](https://github.com/OrchardCMS/OrchardCore/pulls?q=is%3Apr+is%3Aopen+review%3Anone) can be appropriate, but a "review" here is a changes requested/approved flag, what some people don't use during review (but they just comment).

### Describe alternatives you've considered
Perhaps there are other such tools that we can check.

### PR DESCRIPTION
**Pull request by Piedone**
Fixes #15439.

While I've set up CodeRabbit for the repository from the UI for now, so it'll work immediately, the long-term better option is to configure it from a file. So, here I'm adding that too (it'll take precedence over the UI config).

### CODE REVIEW

**Comment by MikeAlhayek** [comment]
Your rabbit is limited :)

image

**Comment by Piedone** [comment]
It's still young :( :D.

This can happen if you have two reviews close to each other, like if you open multiple PRs within a few minutes, or instruct it to review manually multiple times. Was this the case?

**Comment by MikeAlhayek** [comment]
probably opened multiple PR with in close time.

**Comment by MikeAlhayek** [comment]
Did you find this useful yet? So far it just extra unwelcome noise for me.

**Comment by lampersky** [comment]
> Did you find this useful yet? So far it just extra unwelcome noise for me. 

same here 😀

**Comment by Piedone** [comment]
It's a mixed bag. From where it actually added actionable comments (there were a few where it couldn't):

- https://github.com/OrchardCMS/OrchardCore/pull/15389 are sensible
- The one comment under https://github.com/OrchardCMS/OrchardCore/pull/15734 was wrong
- https://github.com/OrchardCMS/OrchardCore/pull/15512 are sensible
- https://github.com/OrchardCMS/OrchardCore/pull/15173#discussion_r1577041033 is debatable
- Under https://github.com/OrchardCMS/OrchardCore/pull/12968#issuecomment-2074393835 and https://github.com/OrchardCMS/OrchardCore/pull/15810#issuecomment-2073796964 it didn't finish the review or something, [I've asked](https://discord.com/channels/1134356397673414807/1134374140397236334/1232745236459950192) the CR team about this.
- https://github.com/OrchardCMS/OrchardCore/pull/11939 are half good, half not.

**Comment by Piedone** [comment]
Please vote: https://github.com/OrchardCMS/OrchardCore/discussions/15935.

**Review by hishamco — APPROVED** [review]

**Comment by hishamco** [comment]
Can we let some workflows trigger when files within specific folders change, such as this PR I don't think there's a need to execute Build, Functional Tests while your change in docs

**Comment by Piedone** [comment]
Yeah, some of the workflows already do that. A downside to not running the build is that we can't have a branch protection rule like currently to prevent merges if the build didn't complete.

**Comment by Piedone** [comment]
Actually, that's already the case for the fictional tests, just the CodeRabbit YAML file was an exception to the rule.

**Pull request merged**
