### PR TITLE
GeoPointField translations

### PR DESCRIPTION
**Pull request by agriffard**
Surround Latitude and Longitude with `@T[""]` in GeoPointField editors.

### CODE REVIEW

**Review by Skrypt — APPROVED** [review]

**Review by hishamco — APPROVED** [review]

**Comment by hishamco** [comment]
I'm suggesting to create a TagHelper that can easily localize labels, spans .. etc instead of using T[""] all the time

/cc @sebastienros

**Comment by agriffard** [comment]
As I see it, `@T[""]` is already kind of minimal and it is what is detected by PoExtractor to generate the translations.

**Comment by hishamco** [comment]
Agree, but I'm thinking about a way that localize views without PoExtractor, something framework specific. I remember Damian Edwards suggested that in ASP.NET Core long time ago, I think it will be useful to provide such thing especially for some HTML elements such as label, span, paragraph .. etc

**Comment by hishamco** [comment]
Agree, but I'm thinking about a way that localize views without PoExtractor, something framework specific. I remember Damian Edwards suggested that in ASP.NET Core long time ago, I think it will be useful to provide such thing especially for some HTML elements such as label, span, paragraph .. etc

**Pull request merged**
