### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by alexbocharov**
Dev as a default development branch

/cc @sebastienros @Jetski5822 What do you think?

### CODE REVIEW

**Comment by Jetski5822** [comment]
@alexbocharov could we have Master and Dev in there?

**Comment by alexbocharov** [comment]
Yes.
Sample: Stable - master Current -dev. 

I can even display the package version.

**Comment by alexbocharov** [comment]
@Jetski5822 a good idea

**Comment by alexbocharov** [comment]
@Jetski5822 Better?

**Comment by alexbocharov** [comment]
@agriffard you agree?

**Comment by agriffard** [comment]
Yes, but when you change the Readme.md, you should also change the src/index.md if you want that the homepage of the documentation site reflects the same change. 
See http://orchardcore.readthedocs.io/en/dev/

**Comment by alexbocharov** [comment]
Of course

**Pull request merged**
