### PR TITLE
Append --source https://api.nuget.org/v3/index.json when using develo…

### PR DESCRIPTION
**Pull request by jeremycook**
…pment branch

Without appending the standard v3 nuget source I was getting this error when restoring from the development branch:

> error NU1101: Unable to find package NodaTime. No packages exist with this id in source(s): https://www.myget.org/F/orchardcore-preview/api/v3/index.json

### CODE REVIEW

**Comment by sebastienros** [comment]
That's surprising, we would have had more reports of this, and the myget feed is handling the redirection for packages that are not on the feed. Or not a single package that is not from our solution wouldn't be found. Maybe it was a transient network issue?

**Comment by jeremycook** [comment]
I don't need to provide the standard source **now** but I wonder if that is because NodaTime is cached locally now....

...So I went and cleared my NuGet cache and ran the restore command with just the myget source and it failed even more impressively, not just NodaTime. So there is definitely an issue.

```pwsh
dotnet nuget locals all --clear
dotnet restore .\MySite\MySite.csproj --source https://www.myget.org/F/orchardcore-preview/api/v3/index.json
```

Restore output:

```pwsh
C:\Users\jcook\Documents\Repos\_Trash\TryOC\MyModule\MyModule.csproj : warning NU1603: Microsoft.Win32.Registry 4.5.0 depends on System.Buffers (>= 4.4.0) but System.Buffers 4.4.0 was not found. An approximate best match of System.Buffers 4.5.0 was resolved. [C:\Users\jcook\Documents\Repos\_Trash\TryOC\MySite\MySite.csproj]
C:\Users\jcook\Documents\Repos\_Trash\TryOC\MyModule\MyModule.csproj : warning NU1603: System.Memory 4.5.1 depends on System.Buffers (>= 4.4.0) but System.Buffers 4.4.0 was not found. An approximate best match of System.Buffers 4.5.0 was resolved. [C:\Users\jcook\Documents\Repos\_Trash\TryOC\MySite\MySite.csproj]
C:\Users\jcook\Documents\Repos\_Trash\TryOC\MyModule\MyModule.csproj : warning NU1603: System.Security.Cryptography.Pkcs 4.5.0 depends on System.Buffers (>= 4.4.0) but System.Buffers 4.4.0 was not found. An approximate best match of System.Buffers 4.5.0 was resolved. [C:\Users\jcook\Documents\Repos\_Trash\TryOC\MySite\MySite.csproj]
C:\Users\jcook\Documents\Repos\_Trash\TryOC\MyModule\MyModule.csproj : warning NU1603: Microsoft.Win32.Registry 4.5.0 depends on System.Memory (>= 4.5.0) but System.Memory 4.5.0 was not found. An approximate best match of System.Memory 4.5.1 was resolved. [C:\Users\jcook\Documents\Repos\_Trash\TryOC\MySite\MySite.csproj]
C:\Users\jcook\Documents\Repos\_Trash\TryOC\MyModule\MyModule.csproj : warning NU1603: System.Security.Cryptography.Pkcs 4.5.0 depends on System.Memory (>= 4.5.0) but System.Memory 4.5.0 was not found. An approximate best match of System.Memory 4.5.1 was resolved. [C:\Users\jcook\Documents\Repos\_Trash\TryOC\MySite\MySite.csproj]
C:\Users\jcook\Documents\Repos\_Trash\TryOC\MyModule\MyModule.csproj : warning NU1603: System.Memory 4.5.1 depends on System.Numerics.Vectors (>= 4.4.0) but System.Numerics.Vectors 4.4.0 was not found. An approximate best match of System.Numerics.Vectors 4.5.0 was resolved. [C:\Users\jcook\Documents\Repos\_Trash\TryOC\MySite\MySite.csproj]
C:\Users\jcook\Documents\Repos\_Trash\TryOC\MyModule\MyModule.csproj : warning NU1603: System.Security.Cryptography.Pkcs 4.5.0 depends on System.Security.Cryptography.Cng (>= 4.4.0) but System.Security.Cryptography.Cng 4.4.0 was not found. An approximate best match of System.Security.Cryptography.Cng 4.5.0 was resolved. [C:\Users\jcook\Documents\Repos\_Trash\TryOC\MySite\MySite.csproj]
C:\Users\jcook\Documents\Repos\_Trash\TryOC\MyModule\MyModule.csproj : error NU1101: Unable to find package Microsoft.AspNetCore.Routing. No packages exist with this id in source(s): https://www.myget.org/F/orchardcore-preview/api/v3/index.json [C:\Users\jcook\Documents\Repos\_Trash\TryOC\MySite\MySite.csproj]
C:\Users\jcook\Documents\Repos\_Trash\TryOC\MyModule\MyModule.csproj : error NU1101: Unable to find package Newtonsoft.Json. No packages exist with this id in source(s): https://www.myget.org/F/orchardcore-preview/api/v3/index.json [C:\Users\jcook\Documents\Repos\_Trash\TryOC\MySite\MySite.csproj]
C:\Users\jcook\Documents\Repos\_Trash\TryOC\MyModule\MyModule.csproj : error NU1101: Unable to find package Microsoft.AspNetCore.Http. No packages exist with this id in source(s): https://www.myget.org/F/orchardcore-preview/api/v3/index.json [C:\Users\jcook\Documents\Repos\_Trash\TryOC\MySite\MySite.csproj]
  Restore failed in 5.49 sec for C:\Users\jcook\Documents\Repos\_Trash\TryOC\MyModule\MyModule.csproj.
C:\Users\jcook\Documents\Repos\_Trash\TryOC\MySite\MySite.csproj : error NU1101: Unable to find package Microsoft.AspNetCore.Routing. No packages exist with this id in source(s): https://www.myget.org/F/orchardcore-preview/api/v3/index.json
C:\Users\jcook\Documents\Repos\_Trash\TryOC\MySite\MySite.csproj : error NU1101: Unable to find package Newtonsoft.Json. No packages exist with this id in source(s): https://www.myget.org/F/orchardcore-preview/api/v3/index.json
C:\Users\jcook\Documents\Repos\_Trash\TryOC\MySite\MySite.csproj : error NU1101: Unable to find package Microsoft.AspNetCore.Http. No packages exist with this id in source(s): https://www.myget.org/F/orchardcore-preview/api/v3/index.json
C:\Users\jcook\Documents\Repos\_Trash\TryOC\MySite\MySite.csproj : error NU1101: Unable to find package Microsoft.AspNetCore.Mvc.Core. No packages exist with this id in source(s): https://www.myget.org/F/orchardcore-preview/api/v3/index.json
C:\Users\jcook\Documents\Repos\_Trash\TryOC\MySite\MySite.csproj : error NU1101: Unable to find package Microsoft.Extensions.Configuration.EnvironmentVariables. No packages exist with this id in source(s): https://www.myget.org/F/orchardcore-preview/api/v3/index.json
C:\Users\jcook\Documents\Repos\_Trash\TryOC\MySite\MySite.csproj : error NU1101: Unable to find package NodaTime. No packages exist with this id in source(s): https://www.myget.org/F/orchardcore-preview/api/v3/index.json
C:\Users\jcook\Documents\Repos\_Trash\TryOC\MySite\MySite.csproj : error NU1101: Unable to find package ncrontab. No packages exist with this id in source(s): https://www.myget.org/F/orchardcore-preview/api/v3/index.json
```

**Comment by jeremycook** [comment]
👍 worked just fine. Nevermind the doc change.

**Comment by sebastienros** [comment]
I assume the setting just got lost at some point, thanks for reporting

**Pull request closed without merging**
