### PR TITLE
React to site settings supported cultures changes

### PR DESCRIPTION
**Pull request by hishamco**
Seems one of my comments in PR #3647 doesn't been applied

/cc @Skrypt @Sebastienros

### CODE REVIEW

**Comment by sebastienros** [comment]
There are merge issues. Are you on master?

**Comment by hishamco** [comment]
I don't think so, but let me check

**Comment by Skrypt** [comment]
Actually I'm not sure this is right. lol

**Comment by Skrypt** [comment]
If you merge that change then add the lookup for finding the system culture if siteSettings.culture == null

**Comment by Skrypt** [comment]
Change this : 

```C#
        public static string[] GetConfiguredCultures(this ISite site)
        {
            return new[] { CultureInfo.InstalledUICulture.Name }.Union(site.SupportedCultures).ToArray();
        }
```

**Comment by hishamco** [comment]
You made me confused 😂.. I will closed this for now and I will continue on data localizer

**Comment by hishamco** [comment]
Sorry I closed the PR  before I see your latest changes. We need to revise this properly

**Comment by jtkech** [comment]
@Skrypt our site default culture may be not null and different from the system one.

so e.g siteSettings.Culture ?? CultureInfo.CurrentCulture.Name

And maybe take care if it is an invariant culture ;) Maybe not if, as i remember, an empty string is ok for the middleware, and if you check it through the UI to display e.g the display name / native name, as in the admin settings.

**Comment by Skrypt** [comment]
SiteSettings.Culture is equal to null when we choose no default culture in the site settings. That means that we should use CultureInfo.InstalledUICulture.Name then. There is no use case where someone will assign a default culture and that it will not be already in the list of supported cultures because they are added manually in that default culture list.

**Comment by Skrypt** [comment]
Moving the topic to https://github.com/OrchardCMS/OrchardCore/pull/3655

**Comment by jtkech** [comment]
Okay, but if you explicitly set a default culture (not the system one) which then belongs to the supported ones. Our union as done before is useless but that's ok, because in this case maybe you don't want to add the system one when using GetConfiguredCultures(). Right?

**Comment by Skrypt** [comment]
Look at the draft PR 😉

**Pull request closed without merging**
