### PR TITLE
Fix issue with enabling features in the admin page

### PR DESCRIPTION
**Pull request by petedavis**
Fixes issue #3544

### CODE REVIEW

**Comment by jtkech** [comment]
Not only enable / disable modules link are broken, also those in the admin tenants page (maybe others).

I will try your branch to see if it fixes both.

**Comment by petedavis** [comment]
I almost want to raise an issue on checking in TheAdmin.js and TheAdmin.min.js.

These are compiled files, and I picked up changes from a merge error where bootstrap was updated, and another pull request had changes that both were merged at the same time, yet both needed to be compiled into the TheAdmin.js file.

Would be better if these files were build from source with the rest of the code base.

**Comment by jtkech** [comment]
And i'm surprised that nobody complaints and requests your PR because currently many links don't work in the admin ;)

**Comment by Skrypt** [comment]
Lots of those links are broken after merging the PR that converts alerts to Bootstrap modals. I think links needs to be updated to support the new Bootstrap modal.

**Comment by petedavis** [comment]
Browser cache saves the day. I was going to post a comment on gitter to ask everyone to clear their cache in admin to see if things are working for them. Should up the priority ;) 

Have to get onto my other computer to fix the merge and rebuild the js files.

**Comment by petedavis** [comment]
@Skrypt Bootstrap modal was working for me when disabling features in the admin with my change. It just wasnt causing a form submit when there was no need for a modal to be displayed, which is the case for enabling a feature.

**Pull request merged**
