### PR TITLE
Move security settings to configuration > settings menu

### LINKED ISSUE #11773: Move Security Settings into Configuration Section
I just watched the latest OC standup, @sebastienros pointed why there's a new top level menu for Security Settings? I already though about it two days ago, so indeed we need to move it to configuration like other modules

### PR DESCRIPTION
**Pull request by hishamco**
Fixes #11773

### CODE REVIEW

**Comment by Skrypt** [comment]
That's just for one module here while there is another PR for that matter already from @CrestApps ??

**Comment by CrestApps** [comment]
Yes. I guess this one is only to move that single item while the other one moves all settings

**Comment by Skrypt** [comment]
Partial change already in #11937
Please explain the PR @hishamco

**Comment by hishamco** [comment]
@Skrypt this PR is fixed the original issue, that discussed month and half ago, then @CrestApps created another issue that move all the settings

So, I never mind to close this PR if all agreed about all the changes in other PR. But still I see some feedback and discussion in going on. I don't think there's an issue to merge this while we already agreed about it in the OC standup, or we should wait until #11937 is ready

**Comment by Piedone** [comment]
I'll review this PR next week (including checking if we need it).

**Comment by Piedone** [comment]
I'd close this one and keep https://github.com/OrchardCMS/OrchardCore/pull/11937. While https://github.com/OrchardCMS/OrchardCore/issues/11773 was first, under the other PR there might be some further refactoring and reorganizing of menu items. So, I wouldn't add more variables to that.

**Pull request closed without merging**
