### PR TITLE
Publish symbol for v1.0

### LINKED ISSUE #9990: For version 1.0 - Symbols are not published to nuget.org
### Describe the bug
For version 1.0 - Symbols are not published to nuget.org

### Expected behavior
Symbol to be published to nuget.org for  V 1.0

### PR DESCRIPTION
**Pull request by ns8482e**
Publish symbol - removed -n switch to allow publish snupkg

Fixes #9990 

/cc @sebastienros  @agriffard  @deanmarcussen

### CODE REVIEW

**Comment by Skrypt** [comment]
I'm not sure if we should push the symbols to debug OC in a "release" version. Maybe we should provide a version with symbols and a version without because else the libraries are bigger and it could be a concern for certain people. Also, you generally don't need to debug a final release, you could equally use the preview feed at the next or previous commit after 1.0 to do so.

I need to check with @sebastienros if this was intended to be published without symbols.

**Comment by ns8482e** [comment]
@Skrypt 

> else the libraries are bigger and it could be a concern

See size comparison discussion in original PR for symbols https://github.com/OrchardCMS/OrchardCore/pull/7237#issuecomment-715665839

> I need to check with @sebastienros if this was intended to be published without symbols.

May be it's copied from preview feed, and  `-n` is there for preview feed as cloudsmith doesn't support symbol server yet.

**Comment by Skrypt** [comment]
Maybe I'm wrong here, I will let @sebastienros decide. The size is not that much bigger at least.

**Comment by sebastienros** [comment]
The -s might have been for cloudsmith because it doesn't support them, and when I created the release pipeline I just copy-pasted it. I am ok with publishing the symbols on nuget.

**Review by sebastienros — APPROVED** [review]

**Pull request merged**
