### PR TITLE
Fixes missing dependencies in the ShellBlueprint

### LINKED ISSUE #16375: Shell blueprint is missing dependencies
### Describe the bug

During startup, the `ShellContainerFactory` is relying on the `ShellBlueprint.Dependencies` property to get all startup classes that needs to be added to DI. But if an extension contains only features that do not match the extension ID, dependencies without any feature assignment are not added to the blueprint at all. 

That means that some startup classes not executed at all.

### Orchard Core version

Reproducible in `1.8.3` and later. I didn't check earlier versions. 

### To Reproduce

1. Enable the features `Microsoft Entra ID Authentication` and `Deployment`. 
2. Create a deployment plan and add steps to it. The `Microsoft Entra ID` step is missing there, because its startup class `OrchardCore.Microsoft.Authentication.DeploymentStartup` is not executed.

### Expected behavior
All startup classes which meet their dependencies should be executed.

### PR DESCRIPTION
**Pull request by gvkries**
If a module contains no feature that matches the extension ID, some dependencies like startup classes were not being added to the `ShellBlueprint` and therefore not executed at all. 

This PR fixes that by changing the `ExtensionManager` to always add every exported type to the features contained in the module. Any type that had no associated feature before, is now added to each feature as a dependency. By doing this, the `CompositionStrategy` will correctly find all dependencies and all startup classes are executed.

Note that while working on this fix, I found another issue. The order in which startup classes are executed depends on the `ExtensionManager.LoadFeaturesAsync()` method, which must already return the features in order of dependencies. However, it returns an unordered list that comes from the `Dictionary.Values` property. I've fixed that as well, which allows us to use another `FrozenDictionary` as a small tweak as well.

This PR is based on #16324 because this change is in the same area and there is no benefit to fixing before #16324.

Fixes #16375

### CODE REVIEW

**Review by MikeAlhayek — APPROVED** [review]

**Comment by Piedone** [comment]
Does this need triage @MikeAlhayek or can be merged?

**Comment by MikeAlhayek** [comment]
This LGTM. But another set of eye may be great. I trust @gvkries

**Comment by Piedone** [comment]
Let's check this on Thursday together.

**Review by sebastienros — APPROVED** [review]
Let's see if we can get an easy test for that.

**Comment by Piedone** [comment]
Let's merge it, then.

**Pull request merged**
