### PR TITLE
Add user_settings liquid filter

### LINKED ISSUE #7669: CustomUserSettings not accessible in liquid
According to the docs, accessing the UserProfile content type with a CustomUserSettings steretotype should be possible by using the following line : `{{ User.Properties.UserProfile.Content.UserProfile.FirstName.Text }}` But this does not work. 

I think the issue is that only the `HttpContext.User` is loaded and not the user entity.

/cc @deanmarcussen

### PR DESCRIPTION
**Pull request by jptissot**
Used to access CustomUserSettings

fix #7669

### CODE REVIEW

**Review by deanmarcussen — CHANGES_REQUESTED** [review]
I don't like it. Sorry going to be the code police :(

Should be through claims.

We shouldn't be retrieving the user from the database for this, it defeats the entire purpose of claims

**Comment by jptissot** [comment]
I agree, but what about the use case where you want a piece of the Properties that you don't want exposed as claims ? This would suport this use-case ? Maybe I misunderstand the use of claims

**Comment by sebastienros** [comment]
DEAN THE CODE POLICE !!!!! 👮 

What about renaming it to user_settings or user_profile to make it clear it's for profile information. And there is no option but to do a database query in this case. All example should just use things from custom profile settings.

**Comment by Skrypt** [comment]
One doesn't prevent having the other too.

**Comment by jptissot** [comment]
I think there is a use case for this filter. And another one for claims. That's why I create another issue.

**Comment by Skrypt** [comment]
Ok was just thinking out loud. 😉

**Comment by deanmarcussen** [comment]
We do need something but not sure this is it (yet).

Some feedback on the comments on this pr https://github.com/OrchardCMS/OrchardCore/pull/7570

As in how should we resolve users through liquid as a whole

**Comment by jptissot** [comment]
This will be handled by the #7570 PR

**Pull request closed without merging**
