### PR TITLE
Rename Change email admin menu

### LINKED ISSUE #7896: Why is Email settings listed under Security?
Seems to me it's a Configuration Setting, not a Security Setting

Screenshot 2020-12-08 at 09 28 06

/cc @agriffard

### PR DESCRIPTION
**Pull request by agriffard**
Fixes #7896

### CODE REVIEW

**Comment by agriffard** [comment]
image

**Comment by deanmarcussen** [comment]
But it's not security related. 

It's configuration for Email ?

**Comment by deanmarcussen** [comment]
Ah, I got it. It's the setting for allowing users to change their email.

We have too many settings in the users process :(

**Comment by agriffard** [comment]
Yes, as the registration and reset password settings.

Should we call them 'User Change email', 'User Registration' and 'User Reset password'?

**Comment by deanmarcussen** [comment]
> Should we call them 'User Change email', 'User Login', 'User Registration' and 'User Reset password'?

ok cool :)

**Comment by agriffard** [comment]
image

**Review by deanmarcussen — APPROVED** [review]

**Comment by jptissot** [comment]
Almost feels like this should be in a  single User Settings page with tabs ;)

**Pull request merged**
