### PR TITLE
Upgrade to ASP.NET 3.1.0

### PR DESCRIPTION
**Pull request by agriffard**
https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-core-3-1/

### CODE REVIEW

**Comment by sebastienros** [comment]
The functional tests are failing with `You intended to execute a .NET Core program, but dotnet-bin/release/netcoreapp3.0/OrchardCore.Cms`. I think the command line must be referencing `netcoreapp30`. Can you do a global search on this string?

**Comment by agriffard** [comment]
basePath = orchard.run('../../src/OrchardCore.Cms.Web', 'OrchardCore.Cms.Web.dll');

no more references of `netcoreapp30`

**Comment by agriffard** [comment]
All good now.

**Comment by jtkech** [comment]
I think we don't need anymore to override `PageLoaderMatcherPolicy` because they have fixed what we asked them. I will check it afterwards in a separate PR and will see if there are other things to consider.

**Comment by sebastienros** [comment]
Do we know if Azure App Service has it already? We might want to wait for it or it could be hard for people to upgrade.

**Comment by agriffard** [comment]
https://aspnetcoreon.azurewebsites.net/ only 3.0 for the moment.

**Comment by carlwoodhouse** [comment]
They should all use docker instead, problem solved :P

**Comment by carlwoodhouse** [comment]
speaking of which; we probably need to update the image version in the dockerfile @agriffard ?

**Comment by agriffard** [comment]
Ok @carlwoodhouse, version changed in dockerfile.

**Comment by agriffard** [comment]
aspnetcore 3.1 is now available in all azure App Service regions globally.
https://twitter.com/DamianEdwards/status/1204136259582492672

**Comment by sebastienros** [comment]
I merged this: https://github.com/OrchardCMS/OrchardCore/pull/4992
I think you can redo it using the new options. Also I see that appveyor has the correct SDK now, so no need to use the script to download the sdk.

**Comment by agriffard** [comment]
Dev branch merged and appveyor.yml commented.

**Comment by hishamco** [comment]
> Also I see that appveyor has the correct SDK now, so no need to use the script to download the sdk

How AzurePipeline solve the issue that you mentioned in the standup without checking the dotnet version each time?

**Comment by Jetski5822** [comment]
What needs to be done to get this merged?

**Comment by hishamco** [comment]
@agriffard I think there's a variable in prop file need to be change into 3.1.0

**Pull request merged**
