### PR TITLE
Update xUnit 2.7.1

### PR DESCRIPTION
**Pull request by hishamco**
https://www.nuget.org/packages/xunit/2.6.4

### CODE REVIEW

**Comment by hishamco** [comment]
@MikeAlhayek don't tell me test this :)

**Comment by Skrypt** [comment]
Test it :smile:

**Comment by hishamco** [comment]
No worry Jasim, please file an issue for all the functional test you need, I will demo Playwright ASAP, then I will take the responsibility for the testing as much as I can

**Comment by Skrypt** [comment]
That's everyone responsibility, me included. That said. I need to work on that unit test still. Oops.

**Comment by hishamco** [comment]
This #15748 need to be merged first

**Pull request merged**
