### PR TITLE
Bootstrap switch editor in css

### LINKED ISSUE #1884: Use bootstrap switch css only for boolean editor
Replace boolean-switch.js (that stayed in 4.0 alpha for a long time) by css only for the boolean switch editor:
https://codepen.io/claviska/pen/KyWmjY

### PR DESCRIPTION
**Pull request by agriffard**
Fixes #1884

### CODE REVIEW

**Comment by sebastienros** [comment]
Haven't checked what we have done so far for other specific libraries (like trombowyg, markdown editor,...) but I think we should just have the scripts and CSS in the same folder as the module that uses them if they are there just for them, and reference it only from the cute that uses it? The Resources module should only contain what is common to many modules and could conflict. Or mainstream libraries we use and think other modules will use.

If we think this piece of CSS would be used on more places on the admin theme then we can also merge it on the admin.css.

Do you think it should be in admin.CSS?

**Comment by agriffard** [comment]
Good question, I will think about it, resource by resource. Each case is specific. For bootstrap switch, it has a dependency on Bootstrap variables so I would let it in Resources for the moment with a separated css but, yes, it could be in TheAdmin.css if we want to replace some chekboxes with this switch everywhere in the admin.

**Comment by agriffard** [comment]
Ok, scss moved to TheAdmin.

You can now use the `switch` class to wrap a checkbox anywhere in the admin:
```
    <span class="switch switch-sm">
        <input type="checkbox" class="switch">
    </span>
```

**Comment by agriffard** [comment]
In fact, this switch editor could become the default one.

**Pull request merged**
