### PR TITLE
Provide client side validation of Setup page

### PR DESCRIPTION
**Pull request by jeremycook**
The Setup page provides little to no validation feedback when filling out the form, and no indication of which fields are required. This adds HTML5 required attributes and password pattern attributes that match the password rules.

### CODE REVIEW

**Comment by sebastienros** [comment]
Why did you remove the `tabindex` attributes? without them the order is mostly random.

**Comment by jeremycook** [comment]
Fair question. I knew that would be controversial (especially since it was a very recent change) and really didn't want to do it but also knew that if I didn't do it now then it would remain that way forever.

I removed them because I found that the order was random with them. Email was floated to the right of username on wide screens, causing display order to differ between mobile and desktop displays. Not wrong but has weird side-effects. On mobile Email appears before Username. On desktop Username before Email but the tab orders persists because of the attributes. This means that tab order gets out of order on mobile (probably doesn't matter since this is a setup screen). On mobile, after filling in the connection string you would jump over email to username and then after filling out username back up to email. So dropping the float, the tab order attributes, and just reordering the email and username would allow things to flow more naturally in my opinion (maybe I'm wrong).

In addition to that, apparently HTML5 form validation ignores tab order attributes because if both username and email were left empty and I submit the form then email would receive focus.

What would you identify as random, or would you like improved? With this change tab order will be: name of site, recipe, type of database, table prefix, conn string, user name, email, password, password confirmation--which matches exactly what you see on any sized screen.

**Comment by sebastienros** [comment]
Then I'd like to revert all this awkwardness, even if we are missing the autocomplete on the next screen. See these changes: https://github.com/OrchardCMS/OrchardCore/pull/1442/files

 /cc @jtkech

**Comment by jtkech** [comment]
Yes, if it causes troubles, no problem to remove it.

**Comment by sebastienros** [comment]
Mind providing a screenshot of before/after so we don't have to install this branch to see it?

**Pull request merged**
