### PR TITLE
Seal all controllers

### PR DESCRIPTION
**Pull request by MikeAlhayek**

### CODE REVIEW

**Review by Piedone — COMMENTED** [review]
image

Are there any controllers that you decided to deliberately not seal? If yes, why?

**Review by Piedone — CHANGES_REQUESTED** [review]
I remembered that this can be easily checked with a `public class .* : Controller` search, and the answer is "no". However, the samples in the docs contain unsealed controllers, which I guess should all be changed too.

**Comment by MikeAlhayek** [comment]
no. all controllers should be sealed. Did I miss any controllers?

**Comment by MikeAlhayek** [comment]
I just updated the controller docs.
I did not do a text search. I right clicked on `Controller` class and clicked on `Find All References`. The did the something with `ControllerBase`

**Review by Piedone — APPROVED** [review]

**Pull request merged**
