### PR TITLE
Add Bootstrap 5.3.0

### PR DESCRIPTION
**Pull request by MikeAlhayek**

### CODE REVIEW

**Comment by agriffard** [comment]
Thank you but upgrading Bootstrap is not as easy as other depencencies because we have to test all the admin views and apply the changes (css classes, ...).

We even didn't manage to upgrade to Bootstrap 5.2 for the moment. 
Please see: https://github.com/OrchardCMS/OrchardCore/pull/12046

**Comment by agriffard** [comment]
We also wait a few days so that the `bootstrap-scss` npm package is updated.

**Comment by agriffard** [comment]
@Skrypt Can you teel us if the new Dark mode feature could be used as is, in the admin?
https://getbootstrap.com/docs/5.3/customize/color-modes/#dark-mode

**Comment by agriffard** [comment]
Many other modules have a package.json with a dependency on `Bootstrap`.

**Comment by MikeAlhayek** [comment]
@agriffard i did not upgrade using bootstrap 5. I simply adding 5.3.0 as a version to the available resource. Like if you want to use it for your own theme like a front end theme. 

This release should simplify lots of things in admin when we are ready to upgrade the admin theme to use bs 5.3

**Comment by Skrypt** [comment]
Yes, probably it would work for the main Bootstrap components. But maybe not for the Bootstrap extensions we have. So, it will require some work.

**Comment by MikeAlhayek** [comment]
@agriffard I don't want to mix things here. This PR is just to make 5.3 available in the resources for use. Another PR could be submitted to upgrade TheAdmin theme to use bootstrap 5.3

**Comment by Skrypt** [comment]
I would say that if you need Bootstrap 5.3 then create a custom ResourceManagementOptionsConfiguration file in a custom module in the mean time. Else, it means that we support BS 5.3 which is not the case at all.

**Comment by MikeAlhayek** [comment]
Yeah I am creating custom class and including bootstrap 5.3. But I thought it would help uses if they want to use bs5 in their own frontend themes.

**Comment by MikeAlhayek** [comment]
There is another PR for updating TheAdmin theme to BS 5.3.1 which provides BS 5.3 as a resource.

**Pull request closed without merging**
