### PR TITLE
HtmlSanitizer 7.1.542

### PR DESCRIPTION
**Pull request by agriffard**
https://www.nuget.org/packages/HtmlSanitizer/7.1.542
https://github.com/mganss/HtmlSanitizer/releases/tag/v7.1.542

### CODE REVIEW

**Comment by hishamco** [comment]
The build is failed due type resolultion for `HtmlSanitizerOptions`

**Comment by agriffard** [comment]
'HtmlSanitizerOptions' is an ambiguous reference between 'OrchardCore.Infrastructure.Html.HtmlSanitizerOptions' and 'Ganss.XSS.HtmlSanitizerOptions'

**Comment by agriffard** [comment]
Should we rename the `HtmlSanitizerOptions` class in OC ?

**Comment by hishamco** [comment]
Can you use FQN for now to avoid breaking-changes

**Review by hishamco — APPROVED** [review]

**Pull request merged**
