### PR TITLE
Make `IContentHandler` async

### PR DESCRIPTION
**Pull request by sfmskywalker**
This PR turns all methods on `IContentHandler` into `async` ones, while allowing sub-classes of `ContentHandlerBase` to still use the non-async versions.

#759 #763

### CODE REVIEW

**Comment by Jetski5822** [comment]
This PR includes Workflow stuff?

**Comment by sfmskywalker** [comment]
That's a mistake. Will fix.

**Comment by sfmskywalker** [comment]
Man, I think I merged the wrong branch into this feature branch. I'll abandon this PR and submit a new one.

**Comment by sfmskywalker** [comment]
That was it - I branched off of workflows. Here's a new PR: #1328

**Pull request closed without merging**
