### PR TITLE
graphiql 1.8.5

### PR DESCRIPTION
**Pull request by agriffard**
https://www.npmjs.com/package/graphiql/v/1.8.5
https://github.com/graphql/graphiql/releases/tag/graphiql%401.8.5

### CODE REVIEW

**Comment by Skrypt** [comment]
Can you eventually try with GraphiQL 2.0 beta too?

**Comment by agriffard** [comment]
> Can you eventually try with GraphiQL 2.0 beta too?

Where would you find this GraphiQL 2.0 beta version?

**Comment by Skrypt** [comment]
It doesn't seem to be available yet. Forget what I said. 😉

**Comment by agriffard** [comment]
https://github.com/graphql/graphiql/milestone/1 graphiql@2.0.0-beta No due date

**Review by Skrypt — APPROVED** [review]

**Pull request merged**
