### PR TITLE
Add a .vsconfig file for easier provisioning when using VS 2019

### PR DESCRIPTION
**Pull request by bleroy**
The .vsconfig file gets picked up by VS when opening the solution, and offers to download missing workloads.

### CODE REVIEW

**Comment by lukaskabrt** [comment]
If I try to install recommended components I get this error message:
image

Aren't these component available only in the Enterprise edition? I think the .vsconfig file should contain only components that are required for the OC.

**Comment by sebastienros** [comment]
> missing workloads

But shouldn't we limit it to the required components? Just one example: F#, we don't require it, why should we install it. There are many others

**Comment by bleroy** [comment]
Yes, I'll remove a few. As for others that look like we don't need them, the problem is that the .NET Core workload declares them as required, so we can't remove them all.

**Comment by bleroy** [comment]
I removed a bunch.

**Comment by bleroy** [comment]
Any feedback on the changed feature set?

**Comment by sebastienros** [comment]
I will try it, and I assume that if it asks me to install anything, it means it's not really necessary, right? Because I can do all the things with OC with the components I have currently on my box.

**Comment by bleroy** [comment]
Yes. It should be minimal.

**Comment by bleroy** [comment]
Bump. What's blocking this, if anything?

**Pull request merged**
