### PR TITLE
Fixing vulnerability warnings in themes

### PR DESCRIPTION
**Pull request by sebastienros**
I updated blog and agency themes which include security fixes for npm.
I removed font-awesome and it's the only thing that comes from a cdn in these themes. It's just too many files to handle.

### CODE REVIEW

**Comment by sebastienros** [comment]
Fixes #2852

**Comment by sebastienros** [comment]
I need to test the flow part. I touched the grids so it might have an impact.

**Comment by Skrypt** [comment]
In TheAgencyTheme you removed the scss folder which I think will break the Flow part grid yes.

**Comment by sebastienros** [comment]
Couldn't find anything that was using these scss? Also it should just be a css to "add" to the layout. But I might miss something. It should be that simple though in order to make it easy to update.

**Comment by sebastienros** [comment]
At least there are no more warnings on github  🎉

**Pull request merged**
