### PR TITLE
Fixes FeatureStep when also features to disable.

### LINKED ISSUE #2523: Error when running recipe that enables AND disables features.
`InvalidOperationException("Invalid serial number for shell descriptor")` is thrown in `ShellDescriptorManager.UpdateShellDescriptorAsync()`.

### PR DESCRIPTION
**Pull request by jtkech**
Fixes #2523.

### CODE REVIEW

**Comment by sebastienros** [comment]
The only thing I like here is that it fixes the issue, and that you worked late on it. The code though ... I will change what I don't like on this branch.

**Comment by sebastienros** [comment]
I think the interface should only that the method that accepts the more arguments. If we need more options then we can create extension methods (thought I don't think we do)

**Comment by jtkech** [comment]
Do you mean only one method, e.g `UpdateFeaturesAsync(...)`? If so i can do it.

Also, maybe 2 methods, one with the `force` argument and one without, as done before. Or only one if in the interface definition we allow to use a default value `bool force = false`.

**Comment by jtkech** [comment]
Okay.

Regarding the usage of the `force` parameter (see below), not sure that it's actual usage is right. E.g when  enableing a feature it only logs & notifies a message if the feature has dependencies, but without checking if they are already enabled. Idem when disabling a feature by checking dependent features.

Note: `FeatureDependencyNotification` is never used in the code. We always use `force = true` unless in one place for themes but again without checking if a possible dependency is not already enabled.

The comment `...should enable it's dependencies if required or fail otherwise.` is wrong because it never fails. Maybe redefine what we would want. **But right now i think we could get rid of this**.


        /// <summary>
        /// Enables a feature.
        /// </summary>
        /// <param name="featureId">The ID of the feature to be enabled.</param>
        /// <param name="availableFeatures">A dictionary of the available feature descriptors and their current state (enabled / disabled).</param>
        /// <param name="force">Boolean parameter indicating if the feature should enable it's dependencies if required or fail otherwise.</param>
        /// <param name="force">If false, there is if the feature has any dependency.</param>
        private IEnumerable<IFeatureInfo> GetFeaturesToEnable(
            IFeatureInfo featureInfo,
            bool force)
        {
            var featuresToEnable = _extensionManager
                .GetFeatureDependencies(featureInfo.Id)
                .ToList();

            if (featuresToEnable.Count > 1 && !force)
            {
                if (_logger.IsEnabled(LogLevel.Warning))
                {
                    _logger.LogWarning("Additional features need to be enabled.");
                }
                if (FeatureDependencyNotification != null)
                {
                    FeatureDependencyNotification("If {0} is enabled, then you'll also need to enable {1}.", featureInfo, featuresToEnable.Where(f => f.Id != featureInfo.Id));
                }
            }

            return featuresToEnable;
        }

**Comment by jtkech** [comment]
@sebastienros 

> I think the interface should only that the method that accepts the more arguments.

Okay for not creating additional methods just because of the `force` argument. Hmm, but i also understood that you also want only one method e.g `UpdateFeatures`, in place of having `EnableFeatures`, `DisableFeatures` and `DisableEnableFeatures`, right?

Anyway, i committed my changes but will be easy to change.

**Comment by sebastienros** [comment]
Much better. Overall less code too.

**Pull request merged**
