### PR TITLE
Pager Shape

### PR DESCRIPTION
**Pull request by Skrypt**
* [x] Update documentation because we changed Tag, ItemTag to TagName and ItemTagName.
Also fixes some issue related to changing this. 

* [x] Adding an extra validation on Properties["Tag"] to make sure it is a TagBuilder that is passed on this property to make sure that if someone used the Pager with a Tag property as a string that it won't fail type casting and throw exception afterward.

* [x] Also adding an extra Property check on GetTagBuilder as we should now use TagName instead of Tag property to change it. I've not seen it fail but next step is trying to find occurences in the code where we used Tag instead of TagName when morphing a Shape.

* [x] We need to document that with Liquid a `IDictionary<string,string>` "Shape.ItemAttributes" for example needs to be passed as a JSON string. `{"key1": "value1","key2":"value2"}` and an `IList<string>`  "Shape.ItemClasses" for example can be a string splitted by a space char : "class1 class2" or a Liquid array.

### CODE REVIEW

**Comment by Skrypt** [comment]
For liquid the parameters won't work for now we have thought about something that will come later on.

**Comment by Skrypt** [comment]
Here are the tests that I made that works : 

``` liquid
{% assign previousText = "← Newer Posts" | t %}
{% assign nextText = "Older Posts →" | t %}
{% assign previousClass = "previous" | t %}
{% assign nextClass = "next" | t %}

{% shape_pager Model.Pager previous_text: previousText, next_text: nextText,
    previous_class: previousClass, next_class: nextClass, tag_name: "div", item_tag_name: "div", attributes: "{\"key1\": \"value1\",\"key2\":\"value2\"}", item_attributes: "{\"key1\": \"value1\",\"key2\":\"value2\"}", classes: "class1 class2", item_classes: "itemclass1 itemclass2" %}

```

```C#
            var pagerShape = (await New.Pager(pager)).TotalItemCount(maxPagedCount > 0 ? maxPagedCount : await query.CountAsync()).RouteData(routeData).TagName("div").ItemTagName("div").Classes("class1 class2").ItemClasses(new List<string>(){ "itemclass1", "itemclass2" }).Attributes(new Dictionary<string, string>() { { "attribute", "value" } }).ItemAttributes(new Dictionary<string, string>() { { "itemattribute", "value" } });

            // Alternatively by affecting directly on the real Shape property.
            pagerShape.ItemClasses.Add("itemclass1 itemclass2");
            pagerShape.ItemAttributes.Add("itemattribute", "value");
```

**Comment by Skrypt** [comment]
#5535 needs to be merged first and afterward I will lowercase my [Shape] function params.

**Comment by jtkech** [comment]
I merged #5535

**Pull request merged**
