### PR TITLE
Bootstrap 5 in admin

### LINKED ISSUE #10300: Extra tooltip script on user menu should move to admin.css
### Describe the bug

We have an extra script that was added to the `UserMenu` to provide tooltips.

```
<script at="Foot">
    $('[data-toggle-tooltip="tooltip"]').tooltip();
</script>
```

We should move that script to the admin javascript, because it's just an extra script being loaded on every page on the admin, when it could just be part of our normal admin javascript.

/cc @agriffard

### LINKED ISSUE #10796: Notifications are hard to read in dark mode due to low contrast
### Describe the bug
In dark mode, the notification text is quite hard to read on the green background - see below.

### To Reproduce
1. Turn on dark mode (I don't know where, maybe it's a browser setting?).
2. Go to the Admin dashboard.
2. Look at the Welcome message.

### Expected behavior
An easily readable message text.

### Screenshots

image

The contrast ratio is **2.76:1**, which does not sound too bad, but in combination with the font it actually appears worse than e.g. in [this online tool here](https://contrastchecker.online/155724/28a745):

image

### PR DESCRIPTION
**Pull request by agriffard**
https://github.com/twbs/bootstrap/releases/tag/v5.1.3
https://www.npmjs.com/package/bootstrap/v/5.1.3
https://www.npmjs.com/package/bootstrap-scss/v/5.1.3
https://www.npmjs.com/package/@popperjs/core/v/2.11.5
https://www.npmjs.com/package/bootstrap-select/v/1.14.0-beta3

https://getbootstrap.com/docs/5.0/migration/

- [X] alert, modal => class="btn-close" 
- [X] data- => data-bs-
- [X] Checkbox and Radio button: form-check , form-check form-switch
- [X] form-control => form-select for `select`
- [X] Dropped .form-group, .form-row, and .form-inline for the grid system: form-group => mb-3
- [X] Dropped .input-group-append and .input-group-prepend => input-group-text
- [X] Dropped .badge-pill => .rounded-pill
- [X] ml-, mr-, pl-, pr- => ms-, me-, ps-, pe-
- [X] float-left, right => float-start, end
- [X] sr-only => visibility-hidden
- [x] card-header => accordion (check everywhere)
- [x] Badge background color is now bg-something instead of badge-primary for example.

Features not working because of `Modal`:

- [x] Media button (Add from field).
- [x] Edit Options in Editor, Custom tags in SEO.
- [x] Confirm modal
- [x] Sort Filters documentation modals

## TODO :

- [x] Dropped .card-columns in favor of Masonry or use grid as in Deployment steps: Queries, Shortcodes, Sitemaps, Workflows
- [x] Media library : Replace badge-light
- [x] Remove form-inline => row row-cols-lg-auto
- [x] Setup recipes dropdown descriptions
- [x] Monaco editor
- [x] Vue Multi-Select --> User Picker Field, Multi-Textfield
- [x] Workflows and https://www.npmjs.com/package/@types/bootstrap @skrypt We should not migrate this component as it breaks everything. We may consider keeping it as is for now.
- [x] Tooltips with popper.js
- [x] Sizes
- [x] Use proper semantic with dropdown-menu (partially). 
- [x] FlowMetadata.Edit.cshtml remaining (needs to be replaced by dropdown-select or else).
- [x] Fix #10796
- [x] Admin menu: when collapsed requires double-click to open up. Should work with a single click.

Keep using btn-info ?

Remove BS 3.4.0 ?

Fixes #10300

### CODE REVIEW

**Comment by agriffard** [comment]
https://getbootstrap.com/docs/5.0/migration/

alert, modal => class="btn-close" 

data- => data-bs-

Checkbox and Radio button: form-check , form-check form-switch

form-control => form-select for `select`

Dropped .form-group, .form-row, and .form-inline for the grid system: form-group => mb-3

Dropped .input-group-append and .input-group-prepend => input-group-text

Dropped .badge-pill => .rounded-pill

ml-, mr-, pl-, pr- => ms-, me-, ps-, pe-
float-left, right => float-start, end

sr-only => visibility-hidden

card-header => accordion

Waiting for bootstrap-scss 5.0.0 version on npm
https://www.npmjs.com/package/bootstrap-scss

Features not working because of `Modal`:

- [ ] Media button (Add from field).
- [ ] Edit Options in Editor, Custom tags in SEO.

Todo:

- [ ] Dropped .card-columns in favor of Masonry: Queries, Shortcodes, Sitemaps, Workflows
- [ ] Media library : badge-light
- [ ] Remove form-inline => row row-cols-lg-auto
- [ ] Monaco editor
- [ ] User Picker Field

Keep using btn-info ?

Remove BS 3.4.0 ?

Sizes => grid-breakpoints ?

**Comment by agriffard** [comment]
Does anyone want to help fixing the scripts using Bootstrap modal?

**Comment by Skrypt** [comment]
Seems like a lot of work to do. I'm moving onto a different PR but I'll take a look at the progress.

**Comment by Skrypt** [comment]
@agriffard I think this PR is a good initiative but maybe will take a little more time to make sure everything still works. I've not tested it yet but I want to contribute. Not a top priority for now but good to know there is some progress made.

**Comment by agriffard** [comment]
Would it be find an alternative to bootstrap-select?

**Comment by Skrypt** [comment]
I was looking at this one last week: https://github.com/github/details-menu-element
But it's not bound to any CSS framework.

**Comment by hishamco** [comment]
> Would it be find an alternative to bootstrap-select?

I remember I implment my own for one of the projects. Is there a features list that we need please let me know may I help you on this

**Comment by Skrypt** [comment]
@agriffard what was the issue with the Monaco editor?

**Comment by Skrypt** [comment]
@agriffard I fixed the admin menu. Now, most of the things that don't work are regressions on Bootstrap components. Could you please make a second pass on this and report anything missing from the TODO list. I'm still not sure why the Monaco editor is listed in there.

**Comment by agriffard** [comment]
Merged main into this branch, updated `@popperjs` and a few missing `float-right` to `float-end`.

**Comment by agriffard** [comment]
A little hack for BS5 (close button) has been added in bootstrap-select.js and bootstrap-select.min.js (cdn not used anymore)

Before
image

After
image

**Comment by agriffard** [comment]
In /Admin/Settings/AuditTrail:
image

See third column bottom.
Problem disappears if `.form-check display: block` is commented.

**Comment by agriffard** [comment]
/Admin/DeploymentPlan/Import/Index
image

**Comment by Skrypt** [comment]
image

**Comment by Skrypt** [comment]
https://user-images.githubusercontent.com/3228637/165180540-710c87df-fb6e-4452-b6bb-6fab7d89b657.mp4

**Comment by Skrypt** [comment]
https://user-images.githubusercontent.com/3228637/165180942-0b0d92ae-407c-4e9b-8476-77c38393da51.mp4

**Review by Skrypt — APPROVED** [review]
I approve the pull request. It may be added to the main branch so that it gets tested for some time. We may find some issues still but they will be minor.

**Comment by Skrypt** [comment]
@agriffard Could you take a look at this : card-header => accordion (check everywhere)
I'm not sure what you meant at all.

**Comment by sebastienros** [comment]
@hishamco do you mind checking the RTL version?

**Comment by hishamco** [comment]
Sure, @agriffard is the PR ready or is there anything else to add

**Comment by Skrypt** [comment]
We need to check every pages of the admin UI with a RTL culture and make sure everything still works. I started doing a quick review by myself and found some small issues. The Pull Request is ready, except RTL which I did not review entirely because ... I don't speak RTL 😉

**Comment by hishamco** [comment]
If there specific modules that I should enable, let me know, coz I will have a look to all the UI in the default installation

**Comment by hishamco** [comment]
@Skrypt do I need to do a npm stuff again ;) because NPM made me crazy all the time with the updates ;)

**Comment by hishamco** [comment]
Themes

The alignment should be to the righ

**Comment by hishamco** [comment]
Users Display Filter

The arrow is rotated which wrong

Users Search Filter

There's a menu issue

**Comment by hishamco** [comment]
Audit Trail

There's no space in the user, also the arrow issue

**Comment by hishamco** [comment]
These are almost the issues, but I could keep enabling other modules and check. IMHO it's fine to fix those and merge this, then we can fix any issue that may facing

**Comment by Skrypt** [comment]
You are sure about the arrow orientation? This comes from "bootstrap-select" directly. Seems odd that we need to change this in Orchard Core if it has been coded intentionally that way in that component.

**Comment by hishamco** [comment]
> You are sure about the arrow orientation?

Ya, if it's not I will need study Arabic language again ;)

https://www.bing.com/images/search?q=%D8%A7%D8%B4%D8%A7%D8%B1%D8%A9+%D8%B5%D8%AD&go=Search&qs=ds&form=QBIR&first=1&tsc=ImageHoverTitle

**Comment by hishamco** [comment]
LGTM expect the arrow orientation issue, we may override this in OC, alongside we could file an issue in bootstrap-select repo

**Review by hishamco — APPROVED** [review]
LGTM expect the arrow orientation issue, we may override this in OC, alongside we could file an issue in bootstrap-select repo

**Comment by ns8482e** [comment]
has jquery been removed in this PR?

**Comment by Skrypt** [comment]
> has jquery been removed in this PR?

You mean JQuery UI ? No, it is not removed yet but once it will be merged I will start a PR to migrate some components to sortable.js. Dropping JQuery might take more work.

**Comment by Skrypt** [comment]
image

**Comment by Skrypt** [comment]
Tracking issue : https://github.com/snapappointments/bootstrap-select/issues/2737

**Comment by hishamco** [comment]
Awesome, let us merge this

**Comment by Skrypt** [comment]
Wait on Tuesday for merging. We are going to announce it first.

**Comment by Skrypt** [comment]
A little extra : 

screencapture-localhost-5001-Admin-Queries-Sql-Query-2022-04-29-15_55_33

Using Monaco to display a SQL Query JSON result

**Pull request merged**
