### PR TITLE
Update SixLabors.ImageSharp.Web 3.1.3

### PR DESCRIPTION
**Pull request by hishamco**

### CODE REVIEW

**Comment by Piedone** [comment]
Such updates are now done by Dependabot weekly (after being broken for a while: https://github.com/OrchardCMS/OrchardCore/issues/16473).

**Comment by hishamco** [comment]
I thought it was still broken, it is your choice to accept it or break it, I followed up with the latest updates by Mike

**Comment by MikeAlhayek** [comment]
> I followed up with the latest updates by Mike

@hishamco the bot was fixed after my last PRs. so this should be automated as @Piedone suggested.

**Comment by MikeAlhayek** [comment]
@hishamco I suggest we close this PR and see if the workflow will work as expected next week "on schedule".

**Comment by MikeAlhayek** [comment]
closing at the bot took care of this.

**Pull request closed without merging**
