### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by Skrypt**
WIP

### CODE REVIEW

**Comment by Skrypt** [comment]
That makes a big Pull Request. I feel concerned about code changes history since it changes almost everything in these files.

**Comment by jtkech** [comment]
Hmm, personally I would keep it as is and let people using it progressively in new PRs. And maybe when a PR update an old file, but not sure as it would pollute the git diff.

**Comment by hishamco** [comment]
Is this including the namespace file scope? coz I already done!!

**Comment by jtkech** [comment]
Oops my comment was more related to #12031 in the first place.

**Comment by Skrypt** [comment]
I don't know, to be honest, if we want to change it then it is necessary. At the same time, it will eventually break everyone's PR. Since @hishamco did it I will close this one.

**Pull request closed without merging**
