### PR TITLE
GetAllCulturesAndAliases() using DefaultCultureProvider

### PR DESCRIPTION
**Pull request by hishamco**
@jtkech  I just introduced `DefaultCultureProvider` to utilize the `ICultureAliasProvider` to provide the culture aliases that we talked about last time. Now the aliases come from DI, the default provider provides Chinese cultures that are utilize by OC

### CODE REVIEW

**Comment by hishamco** [comment]
@sebastienros I watched the latest Orchard Core stand up, I find myself I did a PR 2 weeks ago taking in my mind the extensibility point of the aliases as we as you comments except that name `
GetAllCulturesAndAliases()` which suggested by JT :)

**Comment by jtkech** [comment]
@hishamco I also saw this video today ;)

@sebastienros mainly talked about the fact that you used an `ILocalizationService` static method which is harder to override, then about caching and about the `GetAllCulturesAndAliases` name.

About extensibility, just to be able to override `ILocalizationService` easily, not about more providers as done here with a new `ICultureProvider` using the existing `ICultureAliasProvider` that here has another implementation, but I'm not against, that said we may have better to use the `IOptions` pattern to provide more cultures, maybe by using the existing `CultureOptions`.

About the name, currently this is because we are using `.GetCultures(CultureTypes.AllCultures)` with the `AllCultures` option on which we add aliases, but I'm open to any name ;)

> "zh-CN" is an alias for the "zh-Hans-CN" culture, and "zh-TW" is an alias for the "zh-Hant-TW" culture. Aliased cultures are not returned by calls to the .GetCultures()

About caching .GetCultures() uses some caching on which we add static aliases, but yes the whole could be cached, that said only used in Controller / Drivers for editing.

As said, at some point my goal was to return back to a stable version which is now the case I think, so I think I will merge #13298, then yes we will be able to suggest anything else, for example move the static method to the service implementation, maybe rename the method to `GetAllCultures()` and so on.

**Comment by hishamco** [comment]
> @sebastienros mainly talked about the fact that you used an ILocalizationService static method which is harder to override, then about caching and about the GetAllCulturesAndAliases name.

Right, he was talking mainly about the `ILocalizationServices` and the newly introduced `static` method, that's why I rid of that in this PR

> About extensibility, just to be able to override ILocalizationService easily, not about more providers as done here with a new ICultureProvider using the existing ICultureAliasProvider that here has another implementation, but I'm not against, that said we may have better to use the IOptions pattern to provide more cultures, maybe by using the existing CultureOptions, this in place of registering many services.

If you rememered our talk in Gitter we agreed about this to avoid overriding it in all the implementations. Again I'm open to use `CultureOptions` to provide the aliases, I might have a try

> About the name, currently this is because we are using .GetCultures(CultureTypes.AllCultures) with the AllCultures option on which we add aliases, but I'm open to any name ;)

I knew, but I'm with Seb in this point to rename it to `GetAllCultures` or `GetCultures`

**Comment by hishamco** [comment]
I could start a PR to react for this one, but let us agreed how to avoid overriding `GetCultures()` on every implementation. Can we add it as a help method on `CultureOptions` where it's easy to capture the aliases from options itself

your though

**Comment by jtkech** [comment]
Yes but would need to think about it a little more, will see.

**Comment by hishamco** [comment]
So let us think or propose something before we merge your related PR (if you don't mind)

**Comment by jtkech** [comment]
> So let us think or propose something before we merge your related PR (if you don't mind)

I understand but currently `ICultureAliasProvider` is not used and here for the same interface name you suggest a different definition and implementation, so just better to remove it before we ship the new 1.6.0 release.

**Pull request closed without merging**
