### PR TITLE
Fix layer rules import step

### PR DESCRIPTION
**Pull request by deanmarcussen**
Fixes an issue importing more complex types, than the defaults.

Discussion is here https://github.com/OrchardCMS/OrchardCore/discussions/9011#discussioncomment-573776

### CODE REVIEW

**Comment by Skrypt** [comment]
@intellimedhu Please confirm it fixes your issue.

**Comment by intellimedhu** [comment]
Using the JSON ([here](https://github.com/OrchardCMS/OrchardCore/discussions/9011#discussioncomment-573776)), I get an exception:

https://github.com/OrchardCMS/OrchardCore/blob/0fe03ee8892afcdac23c4dddba47fb1f6cacf564/src/OrchardCore.Modules/OrchardCore.Layers/Recipes/LayerStep.cs#L91


image

**Comment by intellimedhu** [comment]
Works fine when removing this object:

```
"Operation": {
    "CaseSensitive": false
}
```

Should ignore "Operation"?

**Comment by deanmarcussen** [comment]
ok, thanks for checking. (thought I'd tested that, but obviously not). Probably need to do a type lookup from the factories. Will look later

**Comment by deanmarcussen** [comment]
@intellimedhu have had to include type handling for the operations. 

You'll need to adapt your json to include the types for the operations (or recreate from the deployment plans, which is now including it automatically)

**Pull request merged**
