### PR TITLE
Fix setup user name validation

### PR DESCRIPTION
**Pull request by deanmarcussen**
Fixes https://github.com/OrchardCMS/OrchardCore/issues/8189

Fixes https://github.com/OrchardCMS/OrchardCore/issues/1665

Fixes the user name validation for setup/api/tenants

Tidies up some of the email validation, and now using the same localization strings as are in the view. So less work for translators.

### CODE REVIEW

**Comment by hishamco** [comment]
@deanmarcussen I think your PR will fix #1665 too

**Comment by jtkech** [comment]
@deanmarcussen 

I tried with a bad connection string, it works, you can correct it, it's not too late

For the last errors checking, it's too late as soon as some tables have been created through migrations, nothing that we can really do. But I still added the code to set the setup context with the current shell settings (registered in memory), so that at least it is reverted back to the `Uninitialized` state.

**Comment by jtkech** [comment]
@hishamco yes you're right

Fixes #1665

**Comment by deanmarcussen** [comment]
@jtkech 

Cool, makes sense. Yes too late on the last error checking, but good to set the `ShellSettings` back at least.

For infos JT & @hishamco I discovered the other day that PR's only close issues if Fixes (or Closes etc) are in the first comment, so you have to edit the comment, to add another issue that is fixed by the PR. Then github links it properly.

**Review by Skrypt — APPROVED** [review]

**Pull request merged**
