### PR TITLE
Fix NRE when clearing out all zones

### LINKED ISSUE #8360: Cannot clear zones in layer zone settings
1. Navigate to **Design** -> **Settings** -> **Zones**
2. Remove all zones from **Available zones for Layers**
3. Click **Save** button

The zones do not clear, but instead remain the same.

The cause is an NRE in the [LayerSiteSettingsDisplayDriver](https://github.com/OrchardCMS/OrchardCore/blob/e0eb00b352db8a4a271c160f37755d5f702b63ab/src/OrchardCore.Modules/OrchardCore.Layers/Drivers/LayerSiteSettingsDisplayDriver.cs#L58) when attempting to split `model.Zones` when null.

```csharp
settings.Zones = model.Zones.Split(new[] { ' ', ',' }, StringSplitOptions.RemoveEmptyEntries);
```

I'll create a pull request to fix this.

### PR DESCRIPTION
**Pull request by davidhayden**
Fixes #8360

### CODE REVIEW

**Comment by Skrypt** [comment]
Needs to be tested before merging because we need to make sure it won't create a NRE somewhere else.

**Comment by davidhayden** [comment]
The change doesn’t set anything to null to create an NRE elsewhere in the code. It fixes an NRE, and `Zones` becomes an empty string array, which is appropriate when there are no zones in the theme. AFAIK, there is no requirement to have zones in a theme, and it’s a bug I’d like to see earlier than later if some other code expects a zone.

**Comment by Skrypt** [comment]
Maybe, I've not checked yet. I'm pretty sure though that we left one zone definition there for a reason. Maybe it's not necessary anymore, but we definitely had issues with NRE's with those zones a while ago. I just want that we test it and make sure that this won't introduce back the issue that was there beforehand.

Here, your fix only allows to have a string empty when we are saving the zone definitions. So, this is why I feel concerned about the fact that this need testing.

**Review by sebastienros — APPROVED** [review]

**Comment by sebastienros** [comment]
@jtkech do you see any issue with that? Zones will be an empty array.

**Comment by jtkech** [comment]
@sebastienros 

One thing is that if we remove a zone, it is not shown in the widget layers page, normal, but it is still in the layer document with the widgets we defined for it, so it is still rendered on the front end, **but that's another "issue".**

Note :Same kind of issue when we remove a part whose data are still persisted.

When changing the zones, the related driver would need to use the layer service to update the layer document, this by removing the layers (and its widgets) that doesn't exist anymore. Quite easy to fix, **but i think in another PR.**

Otherwise, when a zone doesn't exist, on the dynamic layout we can do the following check that doesn't throw, it uses the `Composite` binder that always returns true to not fail, but outputs a null object that we can check.

    @if (ThemeLayout["Footer123"] != null)

And in razor / liquid, when rendering a zone that doesn't exist, it fails if we use `required: true`, but it doesn't fail if we use `required: false`

    @await RenderSectionAsync("Footer", required: false)
    {% render_section "Footer", required: false %}

So LGTM, i will approve it

**Review by jtkech — APPROVED** [review]

**Pull request merged**
