### PR TITLE
Webpack 5

### PR DESCRIPTION
**Pull request by jptissot**
/cc @agriffard 

I am testing to make sure GraphiQL still works.

### CODE REVIEW

**Comment by agriffard** [comment]
Did you try to run `npm run-script build` to execute webpack?

**Comment by agriffard** [comment]
https://www.npmjs.com/package/webpack/v/5.2.0 is the latest version.

**Comment by jptissot** [comment]
It runs and works, but graphiql does not display in the admin with the following error: 

```
ReferenceError: process is not defined
    9539 graphiql-orchard.js:45344
    n graphiql-orchard.js:45963
    5961 graphiql-orchard.js:508
    n graphiql-orchard.js:45963
    9282 graphiql-orchard.js:36
    n graphiql-orchard.js:45963
    2961 graphiql-orchard.js:20407
    n graphiql-orchard.js:45963
    6619 graphiql-orchard.js:1181
    n graphiql-orchard.js:45963
    componentDidMount graphiql-orchard.js:16307
    ss graphiql-orchard.js:42332
    gl graphiql-orchard.js:43266
    unstable_runWithPriority graphiql-orchard.js:44682
    Gi graphiql-orchard.js:40435
    vl graphiql-orchard.js:43117
    rl graphiql-orchard.js:42893
    $s graphiql-orchard.js:42735
    Ul graphiql-orchard.js:43762
    Ql graphiql-orchard.js:43822
    ol graphiql-orchard.js:42905
    Ql graphiql-orchard.js:43822
    render graphiql-orchard.js:44027
    6143 graphiql-orchard.js:44993
    n graphiql-orchard.js:45963
    <anonymous> graphiql-orchard.js:46004
    <anonymous> graphiql-orchard.js:46004
graphiql-orchard.js:42260
Uncaught ReferenceError: process is not defined
    9539 graphiql-orchard.js:45344
    n graphiql-orchard.js:45963
    5961 graphiql-orchard.js:508
    n graphiql-orchard.js:45963
    9282 graphiql-orchard.js:36
    n graphiql-orchard.js:45963
    2961 graphiql-orchard.js:20407
    n graphiql-orchard.js:45963
    6619 graphiql-orchard.js:1181
    n graphiql-orchard.js:45963
    componentDidMount graphiql-orchard.js:16307
    ss graphiql-orchard.js:42332
    gl graphiql-orchard.js:43266
    unstable_runWithPriority graphiql-orchard.js:44682
    Gi graphiql-orchard.js:40435
    vl graphiql-orchard.js:43117
    rl graphiql-orchard.js:42893
    $s graphiql-orchard.js:42735
    Ul graphiql-orchard.js:43762
    Ql graphiql-orchard.js:43822
    ol graphiql-orchard.js:42905
    Ql graphiql-orchard.js:43822
    render graphiql-orchard.js:44027
    6143 graphiql-orchard.js:44993
    n graphiql-orchard.js:45963
    <anonymous> graphiql-orchard.js:46004
    <anonymous> graphiql-orchard.js:46004
graphiql-orchard.js:45344


```

**Comment by jptissot** [comment]
@agriffard what are orchard's admin supported browsers ? Do we have a list somewhere ?

**Comment by jptissot** [comment]
I tried to fix the runtime errors without success. I think we should wait until graphiql itself updates their webpack version.

**Comment by agriffard** [comment]
Closing the dontmerge labels.

**Pull request closed without merging**
