### PR TITLE
Tenants new UI

### LINKED ISSUE #4306: Tenants: Select all
A 'Select all' check box would be useful in the tenants page.

/cc @hishamco

### PR DESCRIPTION
**Pull request by agriffard**
Bulk Actions, Filters

Fixes #4306

### CODE REVIEW

**Comment by hishamco** [comment]
I just assign myself to that issue and waiting for your UI PR

Thanks

**Comment by agriffard** [comment]
That's it, that is my PR, you can review it @hishamco

**Comment by hishamco** [comment]
No problem Antonie, I will start to list all the UI issues and we will work together on them to avoid the PR duplication

**Comment by hishamco** [comment]
Please screen shoot

**Comment by agriffard** [comment]
image

**Comment by hishamco** [comment]
Uninitialized is a rare state, but overall it's LGTM

:shipit:

**Comment by sebastienros** [comment]
Can we have the filters in the toolbar aligned in some way, either left, or right, or with something, but not randomly in the middle then with a big space before the next one?

**Comment by agriffard** [comment]
image

**Comment by sebastienros** [comment]
Better, now last step, when you align right, you need to set the margin on the right. Such that the space between the last item and the border is the same as the space between the items.

image

**Comment by agriffard** [comment]
It relies on Bootstrap grid columns so I can't really do that if we also want a correct display on small screens.

**Comment by sebastienros** [comment]
> It relies on Bootstrap grid columns

Does it have to?

**Comment by agriffard** [comment]
> Does it have to?

No, it does not. 
It is just the easiest way for me to display them and guarantee they are rendered not so badly on different screen sizes, due to my poor designer skills ;-)

Let's call @matiasmolleja to the rescue.

**Comment by jptissot** [comment]
I think d-flex is what you are looking for https://getbootstrap.com/docs/4.3/utilities/flex/#direction 
Along with pr-3

**Comment by agriffard** [comment]
Done: Filters aligned on the right with same right padding, as on github: 

image

**Pull request merged**
