### PR TITLE
Webpack 5

### PR DESCRIPTION
**Pull request by agriffard**
Upgrading Apis.GraphQl to webpack 5:
https://www.npmjs.com/package/webpack/v/5.0.0

### CODE REVIEW

**Comment by agriffard** [comment]
Error executing npm `run-script build` in src\OrchardCore.Modules\OrchardCore.Apis.GraphQL:

```
> orchardcore.apis.graphql@1.0.0 build D:\Orchard\OrchardCore\src\OrchardCore.Modules\OrchardCore.Apis.GraphQL
> webpack --mode production

assets by status 945 KiB [cached] 1 asset
orphan modules 419 KiB [orphan] 89 modules
runtime modules 1.13 KiB 5 modules
modules by path ./node_modules/ 2.01 MiB 235 modules
modules by path ./Assets/ 6.77 KiB
  ./Assets/js/App.tsx 5.56 KiB [built] [code generated]
  ./Assets/css/graphiql-orchard.css 343 bytes [built] [code generated]
  ./node_modules/css-loader/dist/cjs.js!./Assets/css/graphiql-orchard.css 898 bytes [built] [code generated]

ERROR in ./node_modules/graphql-language-service-interface/esm/getDefinition.js 11:0-28
Module not found: Error: Can't resolve 'assert' in 'D:\Orchard\OrchardCore\src\OrchardCore.Modules\OrchardCore.Apis.GraphQL\node_modules\graphql-language-service-interface\esm'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "assert": require.resolve("assert/") }'
        - install 'assert'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "assert": false }
 @ ./node_modules/graphql-language-service-interface/esm/index.js 3:0-32 3:0-32
 @ ./node_modules/codemirror-graphql/lint.js
 @ ./node_modules/graphiql/esm/components/QueryEditor.js 74:8-42
 @ ./node_modules/graphiql/esm/components/GraphiQL.js 33:0-44 605:44-55 876:27-38
 @ ./node_modules/graphiql/esm/index.js 1:0-49 2:0-20 3:15-23
 @ ./Assets/js/App.tsx

ERROR in ./node_modules/graphql-language-service-interface/esm/getDiagnostics.js 1:0-31
Module not found: Error: Can't resolve 'assert' in 'D:\Orchard\OrchardCore\src\OrchardCore.Modules\OrchardCore.Apis.GraphQL\node_modules\graphql-language-service-interface\esm'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "assert": require.resolve("assert/") }'
        - install 'assert'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "assert": false }
 @ ./node_modules/graphql-language-service-interface/esm/index.js 4:0-33 4:0-33
 @ ./node_modules/codemirror-graphql/lint.js
 @ ./node_modules/graphiql/esm/components/QueryEditor.js 74:8-42
 @ ./node_modules/graphiql/esm/components/GraphiQL.js 33:0-44 605:44-55 876:27-38
 @ ./node_modules/graphiql/esm/index.js 1:0-49 2:0-20 3:15-23
 @ ./Assets/js/App.tsx

webpack 5.0.0 compiled with 2 errors in 20549 ms

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! orchardcore.apis.graphql@1.0.0 build: `webpack --mode production`
npm ERR! Exit status 1
```

/cc @sfmskywalker @Jetski5822 @carlwoodhouse Can you please help me to fix the App.tsx and the dependencies?

**Comment by carlwoodhouse** [comment]
Honestly i know nothing about how we do the frontend GraphiQL and the webpack stuff :P

**Comment by jptissot** [comment]
I will have a look :)

**Comment by agriffard** [comment]
Thank you @jptissot 
You can merge the dev branch or close this PR and start a new one if you want.

**Pull request closed without merging**
