### PR TITLE
Disable UseCdn by default

### PR DESCRIPTION
**Pull request by agriffard**
Related to #8324
Fixes https://github.com/OrchardCMS/OrchardCore/issues/8324

### CODE REVIEW

**Comment by deanmarcussen** [comment]
I think it would be better just to set the `SiteSettings.UseCdn = false;` (and the same in `ResourceManagementOptions`)

**Comment by agriffard** [comment]
> I think it would be better just to set the SiteSettings.UseCdn = false; (and the same in ResourceManagementOptions)

Ok, done.

**Comment by deanmarcussen** [comment]
Cool, will you do the docs as well?

Just something simple like
```
CDNs are disabled by default by the Resource Manager.

This is to allow access to resources when an internet connection is not available, i.e. internal networks, or China.

It is recommended to enable the CDN setting after setup ... etc etc.
```

**Comment by agriffard** [comment]
Section added to Setup documentation.

**Review by deanmarcussen — APPROVED** [review]

**Pull request merged**
