### PR TITLE
graphiql 1.9.9

### PR DESCRIPTION
**Pull request by agriffard**
https://www.npmjs.com/package/graphiql/v/1.9.9
https://github.com/graphql/graphiql/releases/tag/graphiql%401.9.9

### CODE REVIEW

**Comment by hyzx86** [comment]
fixed 
https://github.com/OrchardCMS/OrchardCore/pull/11833

**Comment by Skrypt** [comment]
What are all these javascript files for?

**Comment by hyzx86** [comment]
> What are all these javascript files for?

It should be the result of repackaging after the version of react graphql UI component is updated

**Comment by hyzx86** [comment]
@agriffard this problem haven't merge into your PR 
https://github.com/OrchardCMS/OrchardCore/issues/11831

I think you have to merge the `main` branch and rebuild the js files

**Comment by agriffard** [comment]
I merged main and rebuilt but no change.

**Comment by hyzx86** [comment]
@agriffard 
I pulled your code, but did not find my changes here..
https://github.com/OrchardCMS/OrchardCore/pull/11833/files

**Comment by hyzx86** [comment]
> I merged main and rebuilt but no change.

Yes, this is a strange problem, and updating the local project refference to 1.5.0-preview-16895 has no effect,
@sebastienros Do you know what's going on
image




And I also tried to use your branch to pull the code from main, and there is no difference..

Maybe you can copy all the contents of this file manually?

https://github.com/OrchardCMS/OrchardCore/blob/main/src/OrchardCore.Modules/OrchardCore.Apis.GraphQL/Assets/js/App.tsx

**Pull request closed without merging**
