### PR TITLE
Update AngleSharp and HtmlSanitizer packages

### PR DESCRIPTION
**Pull request by agriffard**
https://github.com/AngleSharp/AngleSharp/releases/tag/v0.15.0
https://github.com/mganss/HtmlSanitizer/releases/tag/v5.0.404

### CODE REVIEW

**Comment by agriffard** [comment]
Should we wait for a stable `6.x` version before merging it?
https://www.nuget.org/packages/HtmlSanitizer/6.0.409-beta

**Comment by lahma** [comment]
I'm not sure how long that will take to be released, upside for waiting is if we get both libraries to version that have optimizations it would be easier to check perf before and after PR where area was HTML sanitization. I don't mind, do what you feel is the best option 🙂

**Comment by agriffard** [comment]
Ok, so @lahma is not just improving OC, he's also improving the libraries used by OC. 

Next step, it will be the .NET Framework itself.

**Comment by lahma** [comment]
OC started to be quite lean allocation-wise so I had to go hunting in the dependencies 😉

**Pull request merged**
