### PR TITLE
EditTemplate buttons stick to top while scrolling

### LINKED ISSUE #1087: Edit Template Editor Suggestions
- Support Ctrl+S to save the template and continue editing. The current workflow is limited.
- Use CodeMirror or Monaco to support syntax highlighting (At least HTML)

### PR DESCRIPTION
**Pull request by hishamco**
Fixes #1087

EditTemplate

### CODE REVIEW

**Comment by deanmarcussen** [comment]
This is a good start, and a nice idea, but it needs more thinking.

You can't have buttons that are sometimes in one place, and sometimes in another place.

Please can it either be **reverted** or **reworked** 

My suggestion is the idea of sticky buttons is good. Move them to the right and top permanently. Make them sticky there.

Don't show them in one place and then another.

Don't have them overhang the text. 

Example from devops that works quite well.

Screenshot 2020-12-18 at 09 27 49

/cc @hishamco @agriffard

**Comment by agriffard** [comment]
Reverted.

@hishamco Can you please make a PR with the buttons at the top?

**Comment by hishamco** [comment]
@deanmarcussen I was thinking to move them to the right, but seems @agriffard merged quickly, I will start a new PR

**Comment by hishamco** [comment]
The PR #8067 is created

**Pull request merged**
