### PR TITLE
Add more view locations for razor pages.

### LINKED ISSUE #2385: Layout not found from Razor Page with route
Repro:
Create this
```razor
@page "{name}"

@functions {
public string Name {get;set;}
}
Hello
```

And in `_ViewStart.cshtml`

```
@ { Layout = "_Layout"; }
```

`_Layout.cshtml` is created in `Views\Shared`

Without the custom route, the layout is used.

### PR DESCRIPTION
**Pull request by jtkech**
Related to #1921.

Razor pages also search partial views in `pageRootDirectory/Shared` but in our case we set `pageRootDirectory` to `/` to allows the razor engine to lookup for pages also under `.Modules`.

**Done**

- Any page of a module (including the application) also searches views in its `/Pages/Shared` folder, not in other modules to not mix things. But it also search in the application `/Pages/Shared`, see below.

- Any page of any module also searches the view under the application `/Pages/Shared`.

- Any page of any module also searches the view under the application `/Views/Shared`.

- If theming, it also searches in `TheTheme/Pages/Shared` and still in `TheTheme/Views/Shared`.

- Any mvc view of any module also searches a partial view under the application `/Views/Shared`.

 - Fixes `AddModularPageRoute()` and `AddModularFolderRoute()` that i broke when implementing `@page "{Name?}"` and `[FromRoute]`, they were not working if we re-use only `@page`.

**Todo**

- Think about searching in the application `Areas` folder related to the original issue.

- Fix #2385.

### CODE REVIEW

**Comment by sebastienros** [comment]
If only we had a test web app we could app sample pages to ;) and then create functional tests ...

**Comment by jtkech** [comment]
@sebastienros 

Just saw your comment, yes we need a test web app, i will do it asap. Maybe we will need to discuss it.

Hmm, but why not using our web app, because now, even in a published context, we can add an application razor page and layout view while the app is running. 

But maybe you also want to test razor pages in a module, so we would need a test web app which reference such a module. Note: To add a razor page in a module at runtime we need to be in a `Development` env.

**Comment by jtkech** [comment]
Fixes #1921.

- Finally, in our expanders, i just needed to add for each module the related `/Pages/Shared`, i was not aware of this standard subfolder. Then, for other standard fallbacks which are relative to the application root, we just need to serve them even they are not requested under the virtual application's module.

- This is the case under the root for `/Pages/Shared`, `/Views/Shared` and also what is under `/Areas/**/*.cshtml`.

- Adding the last one seems to also solved the original issue in #1921, as i have tried.

**Comment by sebastienros** [comment]
When do you expect to remove the notready label?

**Comment by jtkech** [comment]
Very soon !!! 

But i started doing tests by replacing the virtual modules folder from `.Modules` to `Areas`. I made good progress and it seems to open many possibilities.

- We use automatically some standard view locations e.g `Areas/{2}/Views/{1}/{0}.cshtml` and those added by some mvc expanders e.g `LangageViewLocationExpander` and `PageViewLocationExpander`. Then we still need our custom providers for theming and to share component views accross modules.

- We could re-use the default pages route directory to `/Pages`.

- We don't have default routes as `{Areas}/{Module}/Pages/Foo` but there are useless and we get automatically `{Module}/Foo`, and for an `Index` page `{Module}/Index` and `{Module}`.

- Now e.g the `{Module}/Foo` route has an area route value that we can check.

- I was able to use absolute and relative `asp-page="/Foo"` and `asp-page="Foo"` attributes.

- I was able to use standard helpers as `AddAreaFolderRouteModelConvention` and `AddAreaPageRoute`.

**Question**: If you have an application index page (so the home), you have to define it after the setup. Otherwise, because the app's module is always enabled, the home page is displayed in place of the setup form. I think it's quite easy to fix by checking the tenant state, but do you think it's a real problem?

**Note**: Did you see #2389 about the fact that we can trigger a controller of a disabled module.

**Comment by sebastienros** [comment]
I hit the Setup vs. Home issue during my demo on Friday, when I tried to create tenants with the app containing the Index.cshtml.

Controllers should not be accessible if they are disabled.

**Comment by jtkech** [comment]
Okay, i will fix it

> Controllers should not be accessible if they are disabled.

Yes, i will fix it in a separate PR, or maybe here, in O1 i think it is done through the overridden `DefaultControllerFactory` so that the contoller type needs to have been registered.

**Pull request closed without merging**
