### PR TITLE
Replace unnecesary calls to SaveChangesAsync by FlushAsync

### PR DESCRIPTION
**Pull request by sebastienros**
See https://github.com/sebastienros/yessql/pull/601

### CODE REVIEW

**Comment by sebastienros** [comment]
@kevinchalet just because we talked about these years ago and you might remember something that I don't.

**Comment by kevinchalet** [comment]
I'm not familiar enough with YesSql to know the differences between `SaveChangeAsync()` and `FlushAsync()`, but assuming concurrency checks and unique indexes checks are performed by `FlushAsync()`, that should work.

I guess one risk of making this change is that some exceptions might surface elsewhere, when the session is committed higher in the stack, rather than in the stores themselves?

**Comment by sebastienros** [comment]
Functional tests are still passing on this branch. https://github.com/OrchardCMS/OrchardCore/actions/runs/12042510905

Doesn't mean that everything was tested. How awesome would it be if we have functional tests for these operations, including concurrency checks.

**Review by MikeAlhayek — APPROVED** [review]
looks good to me

**Comment by kevinchalet** [comment]
@sebastienros makes sense, thanks the detailed explanation 👍🏻 

(but just in case, that might be worth testing a complete authorization code flow using Postman, to ensure nothing regressed).

**Pull request merged**
