### PR TITLE
Same height for deployment cards

### LINKED ISSUE #4281: Deployment steps cards should be height equal
Steps

### PR DESCRIPTION
**Pull request by agriffard**
Fixes #4281

Uses https://www.npmjs.com/package/jquery-match-height

Result:
image

### CODE REVIEW

**Comment by agriffard** [comment]
Also updates the package.json dependencies

**Comment by Skrypt** [comment]
Strange, normally bootstrap 4 has css class for cards for doing this. We did this for the themes cards.

**Comment by agriffard** [comment]
I tried with `col-sm-4` and `card-deck` but didn't manage.
You can try if you want and tell me if it works.

**Comment by hishamco** [comment]
It would be nice if we can accomplish this without introducing a new package

**Comment by hishamco** [comment]
Can I try this in your branch if you don't mind?

**Comment by agriffard** [comment]
@hishamco You can try.
After a first quick test, in Display.cshtml: 
```
<div class="modal-body">
                <div class="form-group">
                    <input class="form-control" id="search-box" type="search" placeholder="@T["Filter"]" aria-label="@T["Filter"]" autofocus>
                </div>
                <div class="container">
                    <div id="cards" class="row">
                        @foreach (var thumbnail in Model.Thumbnails)
                        {
                            thumbnail.Value.DeploymentPlan = Model.DeploymentPlan;
                            thumbnail.Value.Type = thumbnail.Key;
                            @await DisplayAsync(thumbnail.Value)
                        }
                    </div>
                </div>
            </div>
```

And in DeploymentStep.Thumbnail.cshtml: 
```
<div class="card col-sm-4">
    <div class="card-body">
        @await DisplayAsync(Model.Content)
    </div>
    <div class="card-footer text-muted text-xs-right">
        <a class="btn btn-primary btn-sm" asp-route-action="Create" asp-route-controller="Step" asp-route-id="@Model.DeploymentPlan.Id" asp-route-type="@Model.Type">@T["Add"]</a>
    </div>
</div>
```

I get this:
image

**Comment by Skrypt** [comment]
https://getbootstrap.com/docs/4.0/components/card/#card-groups

**Comment by agriffard** [comment]
@Skrypt : If we use `card-group`, we would have to display them 3 by 3 (wrap in a new group every modulo 3 == 0) and the search filter could display empty cards in some rows.

**Comment by Skrypt** [comment]
They are supposed to use breakpoints to display by X amount of them by row naturally.

**Comment by agriffard** [comment]
If I replace `card-columns` by`card-group`, it displays all fards in one row.

**Comment by hishamco** [comment]
@agriffard is it fixed by the link sent by @skrypt or shall I try my changes?

**Comment by agriffard** [comment]
@hishamco You can push your changes. I don't manage to make it work with `card-group`.

**Comment by hishamco** [comment]
This is how it looks like with m changes

Cards

I will try to use pure bootstrap classes if its possible and remove the  5 lines that I add to make this work

**Comment by hishamco** [comment]
Quote from bootstrap docs

> In addition to styling the content within cards, Bootstrap includes a few options for laying out series of cards. For the time being, **these layout options are not yet responsive.**

I think it's fine to stay with what I came up with

**Comment by hishamco** [comment]
@agriffard please check my changes, if it looks good, then remove unnecessary match-height dependencies

**Comment by agriffard** [comment]
@hishamco I retrieved your changes, refreshed my browser cache and it looks like this:
image

**Comment by agriffard** [comment]
Ok, fixed. I added an `!important` in the css.

**Comment by hishamco** [comment]
Noooo, could you please ensure that the gulp works fine? Or try to copy the two CSS rules that I add in the `Display.chtml`, frankly I didn't test it after moved to a separated file

**Comment by sebastienros** [comment]
Don't merge yet, until simplified

**Comment by hishamco** [comment]
@sebastienros there's another PR by @Skrypt we may merge. It is more simple than this one

**Comment by agriffard** [comment]
Replaced by #5695

**Pull request closed without merging**
