### PR TITLE
Fixing https://github.com/OrchardCMS/OrchardCore/issues/17054

### LINKED ISSUE #17054: ObjectDisposedException - Problem with Database shell settings and Configuration
image

Changing these lines was a mistake
https://github.com/OrchardCMS/OrchardCore/commit/8413ef1649cd0937ae8c567acc4d75cd17ed4506#diff-f5aa894cdbf1a3406e880002dc5e43d02d9b0132cbbf87eadce0af1db8a42f32

https://github.com/OrchardCMS/OrchardCore/commit/8413ef1649cd0937ae8c567acc4d75cd17ed4506#diff-34a9b52f82b5e3080b24526ef2bef6da78b60ec6b3e591149cfa70b443d4a50b

### Orchard Core version
2.1.0

### To Reproduce

```
 builder.Services.AddOrchardCms()
                 .AddMvc()
                 .AddDatabaseShellsConfiguration()
```

### PR DESCRIPTION
**Pull request by vengi83644**
Fix #17054

### CODE REVIEW

**Comment by vengi83644** [comment]
Fixing #17054

**Review by gvkries — APPROVED** [review]

**Comment by gvkries** [comment]
@MikeAlhayek FYI, this was broken by PR #16949.

**Comment by Piedone** [comment]
We'll need a 2.1.1 with this.

**Pull request merged**
