### PR TITLE
[WIP] Add data localizer

### LINKED ISSUE #3607: Translate a dynamic content
This is so hot!! I'm interested to make a prototype for it. The case here that there are many dynamic strings are not localization such as content definition display name, admin menu .. etc. We need to provide a way to localise them without breaking the current sites or database mechanism

# Design steps

- First PR

  - [x] Introduce Data Localization Abstractions & Implementations APIs
  - [x] `DataLocalizer` should read the data from the database as: Key, Context, Value(s) and Culture
  - [x] Add `OrchardCore.DataLocalization` Module as a separated feature that can be enabled or disabled
  - [x] Add `ContentTypeLocalizationDataProvider` & `ContentFieldLocalizationDataProvider` as implementation of `ILocalizationDataProvider` to provide a strings that needs translations from both content types and content fields
  - [ ] Add simple admin screen to localize both content types & content fields names

- Second PR

  - [ ] Support Pluralization
  - [ ] Add `MenuItemLocalizationDataProvider`

- Third PR

  - [ ] Import / Export From Recipes

### PR DESCRIPTION
**Pull request by hishamco**
Fixes #3607 

This is very early PR, so I will keep update this. @sebastienros just few questions without look to the code now :)

- May the data resources contain HTML - I thought yes, but I need the confirmation -

- Is pluralization need here? I didn't think about any scenario here so that's why I didn't include it, but probably you have some scenarios that I don't think about

- Is there anything except Content Type Definition that need to be used from `IDataLocalizer`?

### CODE REVIEW

**Comment by hishamco** [comment]
@sebastienros I'm accepting feedback now, @skrypt @jptissot your feedback is welcome if you have time

The code infrastruction is almost done, the remaining is the GUI part to allow the translation of the missing once .. 

What is working now?

- Creating Content Type
- Edit Content Type

An example for a localized object

```json
{
    ...
    "DisplayName": {
        "" : "Shirt",
        "fr" : "Chemise",
        "ar": "قميص"
    }
    ...
}
```

**Comment by hishamco** [comment]
@agriffard please have a try if you have a time

**Comment by agriffard** [comment]
First, I tested with an existing already configured OC sqlite instance and of curse an error occurred because the display name of all content types didn't have the expected format:
```
ArgumentException: Could not cast or convert from System.String to OrchardCore.Localization.LocalizedObject.
Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable(object value, Type initialType, Type targetType)

JsonSerializationException: Error converting value "Menu" to type 'OrchardCore.Localization.LocalizedObject'. Path 'ContentTypeDefinitionRecords[0].DisplayName', line 6, position 27.
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, object value, CultureInfo culture, JsonContract contract, Type targetType)
```

It is going to be a major breaking change.

Then, I removed the sites in App_Data and setup a new instance with the Agency recipe.

- I added the fr-FR culture and set it as default.
- I changed the `DisplayName `of a Paragraph in ContentDefinition.json:

```
"DisplayName": {
        "": "Paragraph",
        "fr": "Paragraphe"
      },
```

but it didn't appear with this French translation in the admin.

Also, I don't know why but there is no `New` menu, while a LandingPage is creatable.

**Comment by hishamco** [comment]
> of curse an error occurred because the display name of all content types didn't have the expected format

You are right the format should be applied for the existing sites before using this feature

> but it didn't appear with this French translation in the admin.

Did you enable localisation module?

> Also, I don't know why but there is no New menu, while a LandingPage is creatable.

I notice that too, I need to apply `IDataLocalizer` for the displayed content types

thanks

**Comment by hishamco** [comment]
One more thing you need to set the culture to `fr-FR` in the display name instead of `fr` or add `fr` as supported culture to use the fallback, that's why the translation showed up

**Comment by hishamco** [comment]
May we need a tool or little code for changing to the new localised format during import content types if the folks agree about this PR

**Comment by agriffard** [comment]
Ok, with `fr-FR`, it works.

**Comment by hishamco** [comment]
Of course it should 😊 or add `fr` as supported culture and it should work too, please list all your feedback.

The remaining is the GUI that allow the user to add and modify the translation

thanks

**Comment by hishamco** [comment]
Now the **New** admin menu should appears with the proper translations

**Comment by hishamco** [comment]
Oops, seems `IDataLocalizer` need to be registered before activate `OrchardCore.Contents.AdminMenu`, let me try to introduce `NullDataLocalizer` to resolve this issue

**Comment by lukaskabrt** [comment]
I might be late with this suggestion, but please have a look at https://github.com/OrchardCMS/OrchardCore/pull/3626#issuecomment-492764830.

Reasons, why I would prefer the PO files based approach:
- all static and "almost" static strings are localized the same way
- if localized strings are defined inside a content type definition I have two options how to translate them
  - manually extract all strings for translation, send them to a translator and copy&paste translated strings to the content type definition
  - let translators (might be some external agency) access content type definition and risk, they can accidentally break something

**Comment by hishamco** [comment]
@lukaskabrt I still believe there's a need for the dynamic data approach because there are some resources by its nature are dynamic data.

Regarding your options we simply solve this by providing a GUI that allow the user to translate the dynamic data, we could add a permission for instance `Translator` so translators or agencies can access only the data that need to be translated nothing else

Again no need for export data into PO files, send them to translators or agencies and send them back again and finally import the PO files .. just give them a use with limited permission and  🚀🚀🚀 BOOM. But we could export the data to PO if we do so by introducing something like `IExportable`

Last but not least we can do not only localise content types, we can have `ZoneDataStringLocalizer` ... etc. At the end all of these localizers are using `IStringLocalizer` which is fit nicely 😊

Finally hope to hear the feedback from @sebastienros and all the folks that are interested in globalization and localization

**Comment by hishamco** [comment]
@sebastienros I was waiting for a feedback - either positive or negative - for this one, or shall I continue on the UI part and after that I will get the feedback?

**Comment by hishamco** [comment]
@Skrypt your review please .. it's two months since I sent this PR with no comment from the team

**Comment by sebastienros** [comment]
Closing as it should instead follow the design described in https://github.com/OrchardCMS/OrchardCore/issues/3607

**Comment by hishamco** [comment]
I'm not sure why it's closed!! I created the PR based on the issue #3607 which I filled 4 months ago, which designed based on what I heard from during the OrcahrdCore Standup meeting

**Comment by sebastienros** [comment]
Maybe we changed the design, we talked about it 3 weeks ago I think, looking at your PR I understand which meeting you are referring to. But this new design will allow "translators" to be able to provide custom string in the admin, without needing the permissions for editing content types or menus for instance. And some of your code should be reused. 

Keep your custom localizer (`IDataLocalizer`) but its content will be stored in a database (you can abstract the storage as we might be able to provide different sources, like po files too).

THIS POINT IS IMPORTANT: Then in the views, in the views only, I repeat, only in the views, we'll use `D[...]` to localize dynamic texts like content types, field names, menu items, ... by calling `D[contentType.Name]`. You remember when I say "never localize a variable, only a static text" ? Well this is where we'll use `D`. 

Now we need to be able to provide localized texts for these dynamic elements. So we create an `IDynamicStringProvider` that can return terms to localize and their context (like in po files). One implementation is for content types, and returns all the content type names with a `ContentType.Name` context. Same for field names, and another one for dynamic admin menu items. Then we create a controller to list all these strings returned by all the `IDynamicStringProvider` implementations, and we can store all the translations for each of these entries. The UI could be a big list of entries grouped by the context, and for each, on the same line a text field to edit the translation. With a drop down to switch languages maybe.
The stored translations is what is provided to the `IDataLocalizer`.
We also need to be able to import/export the translation as part of deployment steps (so we can import them in recipes).

**Comment by hishamco** [comment]
Could you please refer to me which time you talked about it, video link will be useful, I will come back to look to your notes carefully, because I'm busy little bit with testing translations packaging ..

**Comment by hishamco** [comment]
@sebastienros could please send me the video link when you are free, so I can keep track this before 1.0.0 release

**Comment by hishamco** [comment]
> Maybe we changed the design, we talked about it 3 weeks ago

@jptissot can you refer to me the video URL for the meeting that you change the design of this?

**Pull request closed without merging**
