### PR TITLE
Fixes #9394 Resource dependency location

### LINKED ISSUE #9394: KendoUI script error after upgrade to latest dev branch
I developed some modules on Kendo UI framework and that works fine. after upgrade to the latest dev branch, this error occurred on my page:
`Uncaught TypeError: jQuery(...).kendoLoader is not a function`
I think this is because ResorceManagement class moved `<script src="/OrchardCore.Resources/Scripts/jquery.js"></script>` to the end of page.
how can I set `OrchardCore.Resources` scripts inserted in `<head>` tag??

### PR DESCRIPTION
**Pull request by jtkech**
If a resource A at Foot depends on a resource B at Head, B should stay at Head

Fixes #9394

### CODE REVIEW

**Comment by MichaelPetrinolis** [comment]
@jtkech this one liner fixes the issue :)
you can also copy the unit test from #9430 or I can send a PR after merging this one

PS
I thought that introducing Position broke it, but Location was always not included in Combine

**Comment by jtkech** [comment]
@MichaelPetrinolis 

Thanks for the feedback

> I thought that introducing Position broke it, but Location was always not included in Combine

Yes this is what i saw while debugging to see step b step where the position was 1st overwritten ;)

**Comment by deanmarcussen** [comment]
@jtkech looks good. can you grab the unit test and bring it along as well (otherwise we will forget) ?

**Comment by jtkech** [comment]
Okay will do

**Review by MichaelPetrinolis — APPROVED** [review]

**Pull request merged**
