### PR TITLE
Replace Gulp cssnano by Gulp minifier

### PR DESCRIPTION
**Pull request by agriffard**
In order to prevent the vulnerabilities detected by npm audit.

### CODE REVIEW

**Comment by sebastienros** [comment]
Pending all minified files to actually be changed.

**Comment by sebastienros** [comment]
It's weird that some .css files are also altered ... if the change is only for the minifier.

**Comment by jptissot** [comment]
We really need to implement that ci check

**Comment by sebastienros** [comment]
I will just assume that the versions here are correct, and not the ones in dev

**Pull request merged**
