### PR TITLE
Prettify & Simplify content localization

### PR DESCRIPTION
**Pull request by hishamco**
This PR includes:
- Show badge instead of a wide dropdown list, which is simple and clear from UI/UX perspective
- Display culture name on the badge, to make more clear what culture we are working on
- Localize dropdown should show/hide based on content translations

### CODE REVIEW

**Comment by hishamco** [comment]
localization1

localization2

**Comment by agriffard** [comment]
Conflicts to resolve.

**Comment by hishamco** [comment]
Sure if there's an intend to accept this change

**Comment by Skrypt** [comment]
@hisham Do you remember if clicking on a badge redirects you to the edit page of that content item in the culture clicked. Because here what @jptissot made is also a way to toggle quickly editing the different versions of that content item cultures by allowing visiting these edit pages with it's UI component. I think we should close this one as I think the badges don't add anything but removes something we have. For the button on the content list I think it already has been fixed to show only other cultures than the current content item. It also allows to add a new culture directly or see the edit page of a content item with that culture.

**Comment by hishamco** [comment]
What I did is to simplify the content localization in the edit page instead of the ugly long dropdown on the bottom, regarding content items what we have currently is much better, I will look into this PR again

Thanks

**Comment by Skrypt** [comment]
I agree it needs to be rethinked. I don't like the current culture picker component in the edit page but it does more than just allowing to select a culture so we need to keep this in mind if we create a better component. Not create a regression basically.

**Pull request closed without merging**
