### PR TITLE
Update the action bar on manage roles page

### PR DESCRIPTION
**Pull request by MikeAlhayek**
This PR depends on #12368. PR #12368 should be merged first as it provides some key css changes.

### CODE REVIEW

**Comment by hishamco** [comment]
Please share a screenshot on such PR to make it clear and easy to merge

**Comment by MikeAlhayek** [comment]
All these PR are the same look.

**Comment by hishamco** [comment]
I know but we are trying to avoid unexpected behavior during copy paste nothing else. You can check my old UI PRs

**Comment by MikeAlhayek** [comment]
Combined into #12421

**Pull request closed without merging**
