### PR TITLE
Update Bootstrap 4 to Beta

### PR DESCRIPTION
**Pull request by agriffard**
Update Bootstrap 4 css and js to Beta.

Updated ResourceManifest with latest version of Bootstrap and jQuery.

Migrate css classes in views.

Upgraded npm modules in package.json

Made a few fixes in TheBlogTheme metas.

Added myself in Contributors.md

### CODE REVIEW

**Comment by sebastienros** [comment]
https://blog.getbootstrap.com/2017/10/19/bootstrap-4-beta-2/

**Comment by agriffard** [comment]
OK, I updated the PR with Bootstrap Beta 2 scripts and css files.

**Comment by sebastienros** [comment]
Please check everything again. There has been lots of changes in the templates.

**Comment by agriffard** [comment]
Do you mean StartBootstrap templates or Liquid Templates in admin?

I resolved two conflicts and fixed two views so all admin pages I tested seem OK.

Once this PR is merged, we could try to update the CleanBlog and Agency theme with the latest Beta2 changes in another PR.

**Comment by sebastienros** [comment]
We don't want to just update the themes to Beta 2, we need to update them completely as they have themselves been updated on the site. We should use this opportunity to fix the issues we found.

**Pull request merged**
