### PR TITLE
content types filter by stereotype

### PR DESCRIPTION
**Pull request by giannik**
image

### CODE REVIEW

**Comment by MikeAlhayek** [comment]
@giannik I like the idea of providing filters for the content-types UI where a user can filter that content types. However, filters will need to be added under in drop-down menus next to the bulk actions (between the content type list and the search bar in the header). You can check out how it's done in the content-items UI and follow the same footsteps.

Also, do not use "Content" as a stereotype as you are doing in this PR already. To list everything, just check if the filter is null or empty.

**Comment by giannik** [comment]
@MikeAlhayek why take up an entire row just to show a single filter control ? the contents ui supports many filter controls. 
there is no bulk actions here.
 we need a settings in drop  down for stereotype= null , hence the Content item.
null or empty means show everything regardless of stereotype.

**Comment by MikeAlhayek** [comment]
Because later others may want to add more filters to the same UI. Also, our UIs should stay consistent across the entire app. Like filter content types by their character (publishable, listable, ...).

So yes I would create the row for consistency and the ability to expand the filters.

**Comment by giannik** [comment]
@MikeAlhayek i think you are over-engineering it.
here is the ui . 

image

the contents ui has the same approach for the basic filters

image



 




 if someone wants more filters then that could be part of a new pr .

**Comment by MikeAlhayek** [comment]
Filters next to the search bar, are for filters with predefined value. If you want a filter with more than one value, you should use a drop-down menu as per my last recommendation.

If you still disagree, keep the PR as is for a review by others. If others are okay with it and willing to approve it, sure why not. I personally still think this should be a drop down menu

**Pull request closed without merging**
