### PR TITLE
Remove items from media cache when events fired

### PR DESCRIPTION
**Pull request by deanmarcussen**
Relates to https://github.com/OrchardCMS/OrchardCore/issues/4950

Deletes files from cache when deleted / moved

Also removes unused interfaces from the unused `Media.Services` project I removed last week.

//cc @Skrypt This should resolve the items left in cache from the media attached temp directory that you showed me last week.

### CODE REVIEW

**Comment by jtkech** [comment]
Then we will need to adpat it to a distributed environment, knowing that we prefer to not use a distributed signal using a message bus. I have different ideas that we will need to discuss. Maybe a distributed implementation through #5249 or in a separate PR.

Is it so expensive to get from the blob the Tree of media files? If not maybe just a bg Task that grabs these infos periodically and delete the cached files that don't exist anymore. Note: Or just a bg Task that just check the files that has not been accessed for a while.

Otherwise grab these infos once (by the 1st running instance) from the blob to built a shared Document (not persisted i think but shared through the multi level cache) that the handler will update.

We would have to check that a blob action doesn't fail before updating the cached Document, as i did with the file content definition store in #5249 by using an `IFileDocumentStore`.

**Comment by Skrypt** [comment]
Yes, we would require a cache of fileInfos to make sure these files gets removed from the cache on each instance.

**Comment by Skrypt** [comment]
I don't think this PR should cover this scenario so it is fine to merge it as it at least fix the issue on a single instance tenant website.

**Comment by jtkech** [comment]
I agree, i only suggested to do it later, in my other pr or a separate one, but yes not in this one

Also we try to not use a message bus => no distributed events => rather use distributed states

**Comment by deanmarcussen** [comment]
Yes @jtkech I agree this will need another implementation, of a handler, for distributed.

My thoughts were to have a second `MediaEventHandler` as a feature that depends on `Distributed` to manage that.

Options include
- Background task for period checking of accessed dates (that is already suggested on the issue anyway, to limit the cache size) and I think it is a good idea, regardless of distributed, but I intended it for another pr (don't want to make them too big!), and as an opt-in feature

- For distributed, I was thinking maybe of a volatile state document, which maintained the last 24 hours (configurable, maybe 1 week), of updated media files, knowing that if a server is out of the instance for longer than the period, there would be a few instant state related things to clear, lucene rebuild possibly, as well, so it would potentially always be something of a process, to bring a server back online, after an extended period of outage.

- They could also be persisted permanently, but overtime could grow.

- Also there is the ImageSharp cache to resolve at some point

- For sitemaps cache too.

- Also the cache clearing (from the admin) would need to raise an event / volatile state across servers.

**Comment by jtkech** [comment]
Okay will see, maybe we would have to do separate PRs for Lucene, Azure Media and SiteMaps.

> For distributed, I was thinking maybe of a volatile state document, which maintained the last 24 hours (configurable, maybe 1 week), of updated media files

Document cache options are configurable per document type. That said here i was thinking about a document representing the list / tree of the existing blob media files, not the list of the updated media files which is more like a kind of event, will see ;)

**Pull request merged**
