### PR TITLE
Theblogtheme bs4

### PR DESCRIPTION
**Pull request by Skrypt**
Updating TheBlogTheme to BS4.

### CODE REVIEW

**Comment by BennieCopeland** [comment]
While reviewing this in regards to #1563, I noticed a few things:

1. The src/build files (SASS, gulpfile.js, package.json, etc) are intermixed with the output files in `wwwroot`. This exposes them to be accessible via the browser. For example: `http://localhost:2918/TheBlogTheme/package.json`
2. The OSX file `.DS_Store` is added under the repo
3. When viewing the site, the three social media icons in the footer are now vertical instead of horizontal
4. When using the collapsed navigation on small screens, the menu item `onhover` visual change is so minimal, I almost didn't think there was any indication at all. It's just a very slight darkening of the menu item text.

**Comment by Skrypt** [comment]
1. Yes, we made this by purpose to let people bundle the theme by themselves. We can exclude files when publishing the theme. That's something that could be added. I don't think there's an issue having those files on dev though.

2. Removed it, good catch.

3. I changed the recipe data to have it display horizontally. To have the real result you need to create a new tenants that will execute the recipe.

4. If the theme on startbootstrap.com website is having the same responsive behavior then it's fine. We don't want to necessarly enhance those themes for now. We are just providing the themes as is.

**Comment by sebastienros** [comment]
Have you added back the Sub Title property to the post and pages as it's used in the theme? I think we should have it.

Also take a look at my PR for TheAgencyTheme, I added a way to embed external files in the recipe, this way we don't have to base64 encode or js encode the html snippets. Once I have merged mine we can update this recipe.

**Comment by Skrypt** [comment]
Done

**Comment by sebastienros** [comment]
I merged my theme, do you want to update the recipe to use external files instead of embedding the code directly?

**Comment by Skrypt** [comment]
The recipe is already updated.
https://github.com/OrchardCMS/OrchardCore/pull/1558/files#diff-ea6ab0f782b65d8665a6902539a9e05eR834

**Pull request merged**
