### PR TITLE
[OrchardCore.Modules.Cms.Alias] Add thread-safety for YesSql session queries. Fixes #16069

### LINKED ISSUE #16069: fix: `InvalidOperationException` thrown in `QueryAliasIndex` when `ISession` is still in "connecting" state
### Describe the bug

When loading multiple pages of a site quickly in multiple tabs, a `InvalidOperationException` exception is thrown, due to calling the `IOrchardHelper.GetContentItemByAliasAsync()` method.

```
InvalidOperationException: BeginExecuteReader requires an open and available Connection. The connection's current state is connecting.

    System.Threading.Tasks.ContinuationResultTaskFromResultTask<TAntecedentResult, TResult>.InnerInvoke()
    System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, object state)
    System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, object state)
    System.Threading.Tasks.Task.ExecuteWithThreadLocal(ref Task currentTaskSlot, Thread threadPoolThread)
    Dapper.SqlMapper.QueryAsync<T>(IDbConnection cnn, Type effectiveType, CommandDefinition command) in SqlMapper.Async.cs
    YesSql.Store.ProduceAsync<T, TState>(WorkerQueryKey key, Func<TState, Task<T>> work, TState state)
    YesSql.Services.DefaultQuery+Query<T>.FirstOrDefaultImpl()
    YesSql.Services.DefaultQuery+Query<T>.FirstOrDefaultImpl()
    AliasPartRazorHelperExtensions.GetContentItemIdByAliasAsync(IOrchardHelper orchardHelper, string alias)
    AliasPartRazorHelperExtensions.GetContentItemByAliasAsync(IOrchardHelper orchardHelper, string alias, bool latest)
    Data8.Website.ApiDocs.Components.Abstractions.MenuContentItemComponentBase.OnInitializedAsync() in MenuContentItemComponentBase.cs
    30. ContentItem = await OrchardHelper.GetContentItemByAliasAsync(Alias);
```
### To Reproduce

My specific case uses a Blazor8 de-coupled site, global `InteractiveServer`, and uses `GetContentItemByAliasAsync` for menus, and routing.

Steps to reproduce the behaviour:
1. Within a site that uses `GetContentItemByAliasAsync` for anything such as routing, menus, etc.
2. Create a page with a link to a page that uses `GetContentItemByAliasAsync`.
3. Within your browser, use "middle-click" to open several tabs using that link. My specific case uses a menu, and opening multiple tabs with middle-click, one for each item of the menu.
4. On some tabs, you will see an `Internal Server Error`, with a stack-trace similar to above.

### Expected behaviour

Each tab should load correctly, waiting for the YesSql session to be open and available, before executing the query.

### Screenshots

image

image

### Possible Solution

This method would likely need to be fleshed out to use a retry policy, or wait for the session to be open and available, before querying the database:

https://github.com/OrchardCMS/OrchardCore/blob/main/src/OrchardCore.Modules/OrchardCore.Alias/Services/AliasPartContentHandleProvider.cs#L37

### PR DESCRIPTION
**Pull request by ApacheTech**
Fixes #16069 

Added a `SemaphoreSlim` to synchronise requests, using the `AliasPartContentHandleHelper.QueryAliasIndexAsync` method

### Original Bug:

When loading multiple pages of a site quickly in multiple tabs, a `InvalidOperationException` exception is thrown, due to calling the `IOrchardHelper.GetContentItemByAliasAsync()` method.

```
InvalidOperationException: BeginExecuteReader requires an open and available Connection. The connection's current state is connecting.

    System.Threading.Tasks.ContinuationResultTaskFromResultTask<TAntecedentResult, TResult>.InnerInvoke()
    System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, object state)
    System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, object state)
    System.Threading.Tasks.Task.ExecuteWithThreadLocal(ref Task currentTaskSlot, Thread threadPoolThread)
    Dapper.SqlMapper.QueryAsync<T>(IDbConnection cnn, Type effectiveType, CommandDefinition command) in SqlMapper.Async.cs
    YesSql.Store.ProduceAsync<T, TState>(WorkerQueryKey key, Func<TState, Task<T>> work, TState state)
    YesSql.Services.DefaultQuery+Query<T>.FirstOrDefaultImpl()
    YesSql.Services.DefaultQuery+Query<T>.FirstOrDefaultImpl()
    AliasPartRazorHelperExtensions.GetContentItemIdByAliasAsync(IOrchardHelper orchardHelper, string alias)
    AliasPartRazorHelperExtensions.GetContentItemByAliasAsync(IOrchardHelper orchardHelper, string alias, bool latest)
```

### CODE REVIEW

**Comment by ApacheTech** [comment]
@dotnet-policy-service agree

**Review by Piedone — CHANGES_REQUESTED** [review]
Synchronization is only a fix for the symptom, not the cause. These services shouldn't be called concurrently with the same `ISession` (~same scope). This is also true for all services in Orchard Core, so we'd need synchronization for all data access, which is not the feasible solution either.

If you can't prevent your application code from calling these services concurrently (which would be the first thing to try to address, see https://github.com/OrchardCMS/OrchardCore/issues/16069#issuecomment-2115899011), then you need to add locking there, but not in Orchard Core.

**Comment by ApacheTech** [comment]
> Synchronization is only a fix for the symptom, not the cause. These services shouldn't be called concurrently with the same `ISession` (~same scope). This is also true for all services in Orchard Core, so we'd need synchronization for all data access, which is not the feasible solution either.
> 
> If you can't prevent your application code from calling these services concurrently (which would be the first thing to try to address, see [#16069 (comment)](https://github.com/OrchardCMS/OrchardCore/issues/16069#issuecomment-2115899011)), then you need to add locking there, but not in Orchard Core.

That's what I asked in the first place, and was told to make a PR with a fix. I didn't know if it was an application level thing, an OrchardCore thing, or a YesSql thing.

**Comment by Piedone** [comment]
It's probably unclear at first, but under the issue, Sebastien asked you to try if locking fixes your problem, because then the problem is concurrent invocation. But locking is not a proper fix, just a way to uncover the cause of the problem.

**Comment by Piedone** [comment]
What calls YesSql in parallel is your code. The fix needs to be done there.

After https://github.com/OrchardCMS/OrchardCore/pull/16079, in 2.0 we'll have an explicit exception for unsupported calls like this.

If, as Mike said, you have suggestions that would improve Blazor support, then that's always welcome. This PR was welcome as well, since we could continue the discussion toward a proper solution, it's just not the solution yet itself. E.g. if a change in OC would help you prevent that concurrent call, then that's a solution we can accept.

**Pull request closed without merging**
