### PR TITLE
Fixing templates

### PR DESCRIPTION
**Pull request by sebastienros**

### CODE REVIEW

**Comment by jtkech** [comment]
I will try it very soon.

**Comment by jtkech** [comment]
Just tried the listening to https but with our web app (using the web command).

So, when using 5001, for infos the browser always shows that it is an unsecured site.
Otherwise it works, i can login even if i have https cookies.
Hmm, maybe good to do the same update in our web app.

Indeed, we need a place holder for wwwroot.

I will try locally the template itself.

**Comment by jtkech** [comment]
- So, i did a dotnet new occms locally. Then, because i try things locally, i created a `Nuget.config` with the myget feed, and i manually replaced `Version="1.0.0-beta2"` to `Version="1.0.0-beta2-6752"` in the .csproj file. Then i opened the project under VS.

- Then i could run a blog setup without log errors, go to the admin.

- But when i created a new article i got

      OrchardCore.FileStorage.FileStoreException: Cannot get content of directory 'Test' because it does not exist.

- I will check it, first if we have the same with our cms web app in the solution.

- Then i tried the VS command which listen to `https://localhost:5001`. Here it launched the browser directly to `https://localhost:5001` and it didn't show that it is an unsecured site, and i could login.

**Comment by jtkech** [comment]
So, for me all seems to be ok unless the above issue that i can't repro.
I will retry it from a fresh blog setup.

**Comment by jtkech** [comment]
So, for me here all is ok.

- I only suggest to also listening `https://localhost:5001` in the `launchSettings.json` of our cms web app (in the solution), as you did for the template.

      "web": {
        "commandName": "Project",
        "launchBrowser": true,
        "applicationUrl": "https://localhost:5001;http://localhost:5000",
        "environmentVariables": {
          "ASPNETCORE_ENVIRONMENT": "Development"
        }

- For the above issue, i could also repro with our cms web app (in the solution). It is related to `OC.Media` when, i think, there is no files in the media folder. I will check it separately.

**Comment by jtkech** [comment]
Found the issue about `OC.Media`.

- Let say that you create a `Test` folder under `Media` through the admin, then display its content.

- Then close the browser, delete `App_Data` and redo a fresh setup.

- Then, go back to the admin and display the assets. Because it has memorised the last displayed media path, i think on the client side, it tries again to display the `Test` folder which doesn't exist anymore. Then it fails with the exception mentioned above.

- Let me know if it is the intended behavior or if we need to open an issue because some things need to be cleaned up, e.g when we close the browser, i don't know.

**Comment by Skrypt** [comment]
Well I see a more common scenario where 2 peoples are in the media folder. One deletes the Test folder while the other person is trying to upload stuff in it. Maybe we just need to handle that error scenario better simply.

**Comment by jtkech** [comment]
I updated .gitignore to not ignore the wwwroot folders of templates (right now only for the occms).

Maybe we will revert this change when `wwwroot/.placeholder` will have been merged in the main branches, i don't know.

**Comment by sebastienros** [comment]
I force added it. We could just include everything from the content folder.

**Comment by jtkech** [comment]
But the `wwwroot` of occms was not in the dev branch.
So i added it to make the template fully working.

So here, i think you mean to just use.

    !src/Templates/**/content/**

I will update it here. Do you want that i also update the dev branch?

**Pull request merged**
