### PR TITLE
Sticky Action buttons on Create/Edit content

### LINKED ISSUE #2255: Fix the location of "Publish" "Save Draft"
In template editing, content editing, etc.
Fix the position of buttons such as "Publish" "Save Draft",
Will it be better?

### PR DESCRIPTION
**Pull request by agriffard**
On Create/Edit content, put the actions buttons at the top in a sticky toolbar.

media

Fixes #2255

Related to #8093

### CODE REVIEW

**Comment by Skrypt** [comment]
Have you tested in the Menu and in the Widgets to make sure it works fine?

**Comment by Skrypt** [comment]
orchard

Here is a reminder for myself on what Github does with their buttons.
Might add more screens for getting ideas.

**Comment by deanmarcussen** [comment]
And for more views here is an example from devops...

Where the TopBar is a breadcrumb, rather than a title, and the title is the title.

Now I know we don't have a breadcrumb (yet), but that makes sense to me that the top bar is reserved for navigational purposes (one short term solution could be to render the title in both (as a psuedo breadcrumb in the lighter / smaller font), and later implement an actual breadcrumb. A crumb would be useful)

Screenshot 2021-03-10 at 08 27 28

**Comment by agriffard** [comment]
Title and Actions buttons in the same toolbar:

image

/cc @deanmarcussen

**Comment by agriffard** [comment]
Templates: Title and Actions buttons in the same toolbar:

image

**Comment by hishamco** [comment]
What's the status of this?

**Comment by agriffard** [comment]
> What's the status of this?

I implemented this sticky toolbar (with title on the left and actions on the right) in the Create/Edit Content and Create/Edit Template pages.

Are there any other admin pages where it could be useful?

**Comment by hishamco** [comment]
AFAIK the templates pages, but this could be helpful in queries, where a lot of code can scroll the page

**Pull request closed without merging**
