### PR TITLE
Fixed ContainedPartIndex behavior for DisplayText over 255 chars long

### PR DESCRIPTION
**Pull request by XopcT**
Hi! Currently there is an issue when adding content items with long DisplayText (over 255 chars) as a child list item. Postgres database allowes only 255 chars for ContainedPartIndex.DisplayText column. So this fix truncates long DisplayText to 255 chars, similart to ContentItemIndex behavior

### CODE REVIEW

**Comment by XopcT** [comment]
@dotnet-policy-service agree

**Comment by MikeAlhayek** [comment]
@XopcT thanks for this PR. You'll need to agree to the dotnet policy. But also, you'll need to set the same length of the column here https://github.com/OrchardCMS/OrchardCore/blob/b3c4b4689135498b0afcf687b801b9d149e6f5b3/src/OrchardCore.Modules/OrchardCore.Lists/Migrations.cs#L87

**Review by MikeAlhayek — APPROVED** [review]

**Comment by MikeAlhayek** [comment]
adding do not merge label until after dotnet-policy is agreed, then we can merge.

**Comment by MikeAlhayek** [comment]
I did not realize that you already have.

**Pull request merged**
