### PR TITLE
Trumbowyg: Media modal and Insert Media Url

### LINKED ISSUE #2822: Wysywig Editor: Insert Image in Html instead of Liquid
Currently, when you Insert an image from the Html editor, it adds Liquid code.

It can be a bit weird for some users that would expect to be able to see the image in the Wysiwyg editor.

The only advantage seems to be that it will resize the image to the expected size but, from my point of view, we are losing something important for 'standard' users.

### PR DESCRIPTION
**Pull request by agriffard**
Load Media wrapper (and modal) with Trumbowyg editor from MediaShapes.

Fixes #2822, #4797

### CODE REVIEW

**Comment by PiemP** [comment]
Hi @agriffard,  I have found an issue with trumbowyg dependencies. Need to set jQuery as a dependencies in ResourceManifest.cs in the module OrchardCore.Resources ... Maybe need to set jQuery-ui as an another dependencies of trumbowyg to prevent problem with resizimg plugin of trumbowyg, if they approve my PR.

```
            manifest
                .DefineStyle("trumbowyg")
                .SetDependencies("jQuery", "jQuery-ui", "jQuery-ui-i18n")
                .SetUrl("~/OrchardCore.Resources/Styles/trumbowyg.min.css", "~/OrchardCore.Resources/Styles/trumbowyg.css")
                .SetCdn("https://cdnjs.cloudflare.com/ajax/libs/Trumbowyg/2.19.1/ui/trumbowyg.min.css", "https://cdnjs.cloudflare.com/ajax/libs/Trumbowyg/2.19.1/ui/trumbowyg.css")
                .SetCdnIntegrity("sha384-Q67l3qyObuJLbT8KMRs6D2ZBPTg9qWCweoXYg5MMfKV17QLJeMY14Jr6XLh/wANO", "sha384-P8sKWJD2T0Qo4sz+kDpxBFoPO6BxaR7/sQFWKA/5HM8Oxxkmo14uZVGEcm5/4Npv")
                .SetVersion("2.19.1");

            manifest
                .DefineScript("trumbowyg")
                .SetDependencies("jQuery", "jQuery-ui", "jQuery-ui-i18n")
                .SetUrl("~/OrchardCore.Resources/Scripts/trumbowyg.js", "~/OrchardCore.Resources/Scripts/trumbowyg.js")
                .SetCdn("https://cdnjs.cloudflare.com/ajax/libs/Trumbowyg/2.19.1/trumbowyg.min.js", "https://cdnjs.cloudflare.com/ajax/libs/Trumbowyg/2.19.1/trumbowyg.js")
                .SetCdnIntegrity("sha384-6T5zd/UY6O+/GBXh9vN5ePib6hyqnP59uZzmwjpVDxoNc08ia4etj/IDPyrJS7R1", "sha384-2Mr/QWbCuYpU62KR2U8ObtDO47hBIlbpqZlH2V6+i2e/KTfV3yCc2/7UdOvkxAf4")
                .SetVersion("2.19.1");
```

Hope to be in the right place to do this reporting.

**Comment by agriffard** [comment]
@PiemP I already fixed the jQuery dependency issue here: #4788

**Comment by agriffard** [comment]
Added InsertMediaWithUrl setting in Trumbowyg Editor to allow to insert media with url instead of Liquid tag.
I moved the script import from the Modal to the Edit view.

Please help me to find the good way to explain the setting's use:
`Insert Media with url — Whether the url is used when selected from Insert Media (By default, the Liquid Tag is inserted).`
image

**Comment by stantoxt** [comment]
@agriffard I am exited with this feature.When you merge this?

**Pull request merged**
