### PR TITLE
Rename general setting views

### PR DESCRIPTION
**Pull request by MikeAlhayek**
Follow up PR on the comment https://github.com/OrchardCMS/OrchardCore/pull/14106#discussion_r1295110594

@jtkech

### CODE REVIEW

**Review by jtkech — APPROVED** [review]
LGTM if you re-tried it

**Comment by MikeAlhayek** [comment]
Yes of course. I also tested it after renaming the wrapper too.

**Comment by jtkech** [comment]
Okay, are there other shape names that you did recently and that may be worth to update?

**Comment by MikeAlhayek** [comment]
I don't think so. These were shapes that I was not sure of. I'll review the new SMS module and see if there is something these that require updates. Probably not.

**Pull request merged**
