### PR TITLE
Display username & logout in mobile view

### LINKED ISSUE #3964: Logout and change password menu item in admin theme
1-in mobile view, the user name and logout menu are hidden. these are should be shown at the top of the page.

2-the seceond problem, i don't know why we don't have change password in the admin page. i think i we select service receipt, this menu and external login are shown in the layout. 

it's really useful to have change password in admin layout.

### PR DESCRIPTION
**Pull request by hishamco**
Fixes #3964

This include:

- Polish the header in both PC & mobile view
- Style logout link
- Display username & logout button in mobile view
- Style the brand name

### CODE REVIEW

**Comment by hishamco** [comment]
The mobile view will look like:

mobile

**Comment by hishamco** [comment]
@aghili371 hope it fixes what is intended for

**Comment by sebastienros** [comment]
Why is the header so big? Should I try it locally?

Maybe a new icon in the menu on mobile to show the user profile with these actions

**Comment by hishamco** [comment]
> Why is the header so big? 

Yep, but I change the header little bit to look like https://getbootstrap.com/docs/4.3/examples/pricing/

**Comment by hishamco** [comment]
I think I need to set `text-decoration:none` for the brand name

**Comment by jptissot** [comment]
I personally prefer using the hamburger menu. It would take less space to leave the title but hide the menu items under a button.

**Comment by hishamco** [comment]
> I personally prefer using the hamburger menu. It would take less space to leave the title but hide the menu items under a button.

If you look to the sample above it uses bootstrap 4, I didn't see hamburger menu, nothing but what I saw from the screenshot above is not bad at all from UI/UX perspective

**Comment by aghili371** [comment]
> @aghili371 hope it fixes what is intended for

thank's

**Comment by jptissot** [comment]
@hishamco  Try this in mobile view: https://getbootstrap.com/docs/4.3/examples/navbars/ to see how the menu items are responsive and hide under the hamburger menu

**Comment by hishamco** [comment]
It looks like the previous version hamburger menu, just waiting for @sebastienros for final approval or change this one

**Comment by hishamco** [comment]
@sebastienros did you look to this one locally? Because I need to check this one #2885 too

**Comment by hishamco** [comment]
Seb any update on this one?

**Comment by sebastienros** [comment]
Haven't tried yet

**Comment by hishamco** [comment]
@sebastienros can you delegate this, because I'm trying to close all the issues & PRs that related to me :)

**Comment by hishamco** [comment]
Ok Jasmin, I need to revise the PR I'm sure there 're many change may happened since then

**Pull request closed without merging**
