### PR TITLE
Add top level Multi Tenancy menu

### LINKED ISSUE #12670: Move Tenants menu under Multi Tenancy menu
Move "Tenants" and "Tenant Feature Profile" under new menu "Multi Tenancy"

image

### PR DESCRIPTION
**Pull request by ns8482e**
Add top level Multi Tenancy menu and Move tenants and Tenant feature profile under Multi Tenancy menu

Fixes #12670 

image

### CODE REVIEW

**Review by hishamco — APPROVED** [review]

**Comment by MikeAlhayek** [comment]
@ns8482e 
If you want to name it "Multi Tenancy", maybe it should be written "Multi-Tenancy". By what if you change the main menu to "Tenants" and then replace current "Tenants" with "Management" or "Manage Tenants"? So it would look like this

```
builder
    .Add(S["Tenants"], "after", tenants => tenants 
        .AddClass("tenants").Id("tenants")
        .Add(S["Manage"], S["Manage"].PrefixPosition(), manage => manage 
            .Action("Index", "Admin", new { area = "OrchardCore.Tenants" })
            .Permission(Permissions.ManageTenants)
            .LocalNav()
        )
    );
```

**Comment by Skrypt** [comment]
Moving the menu items makes sense to me. That's a top-level feature.

**Comment by ns8482e** [comment]
@MikeAlhayek  I feel "Multi Tenancy" as top level menu as it represents a grouping of features related to multi-tenant, where as  "Tenants" / "Tenant Features Profile" individual features, menu name kept it as is as we used to with those names

**Comment by MikeAlhayek** [comment]
I understand. IMO, "Tenants" delivers the same meaning in a shorter manner.  But either way, its up to you

**Comment by ns8482e** [comment]
Some other CMS refer that top level menu as "Sites"

**Comment by ns8482e** [comment]
I am fine to use  any top level menu name all agrees to

**Comment by MikeAlhayek** [comment]
@ns8482e 
Personally I think "Tenants" is better than "Sites" or "Multi-Tenancy". I'll leave to you and others.

**Comment by hishamco** [comment]
I also see the term Sites in some CMSs, it's more clear for non technical users

**Comment by sebastienros** [comment]
My suggestion
- Multi-Tenancy
  - Feature Profiles
  - Tenants (because we already call it this way everywhere)

**Comment by MikeAlhayek** [comment]
@ns8482e I fixed the conflict. If you can just rename the menu item `Tenant Feature Profiles` to `Feature Profiles` and merge this PR.

**Comment by MikeAlhayek** [comment]
@ns8482e I make the changes @sebastienros mentioned. Feel free to merge this PR.

**Review by MikeAlhayek — APPROVED** [review]

**Pull request merged**
