### PR TITLE
Some CSS fixes for the content list

### LINKED ISSUE #4947: Content list filters: action button
The action button should display aligned to the right of the top bar.
Also the "New" button won't allow to scroll if there is a lot of menu items.

### PR DESCRIPTION
**Pull request by Skrypt**
image

image

Fixes #4947

### CODE REVIEW

**Comment by hishamco** [comment]
@Skrypt be sure it's working fine on RTL languages, coz there's a logged issue about the new button

**Comment by Skrypt** [comment]
I'm looking and it seems to be for all dropdown menus which doesn't open on the proper side.

**Comment by agriffard** [comment]
Can you please check on small screen?

**Comment by Skrypt** [comment]
Try it but from what I've seen small screens worked fine.

**Comment by Skrypt** [comment]
orchard

**Pull request merged**
