### PR TITLE
Add @JoshLefebvre as a contributor

### PR DESCRIPTION
**Pull request by hishamco**

### CODE REVIEW

**Comment by hishamco** [comment]
@agriffard is there a way to check the contributors live before merge?

**Comment by agriffard** [comment]
@JoshLefebvre is already in the contributors:
https://github.com/OrchardCMS/OrchardCore/blob/6e30583eeff4fb8d5aeba9574f5d44bf9f523019/.all-contributorsrc#L1108

Do not do this manually, all-contributors has a command to add a contribution.

**Comment by hishamco** [comment]
> @JoshLefebvre is already in the contributors:

Oops really?!!

**Comment by JoshLefebvre** [comment]
Thanks guys !

**Pull request closed without merging**
