### PR TITLE
Account views validation messages

### LINKED ISSUE #5086: User module forms error messages are not translated
When logging in / registering and an error occurs, the messages displayed are not translated.

image

### PR DESCRIPTION
**Pull request by agriffard**
Implement `IValidatableObject` on ViewModels in the User modules in order to localize the error messages.

Fixes #5086

### CODE REVIEW

**Comment by Skrypt** [comment]
Well that's a nice workaround. What we do with data annotation attributes error messages localization?

**Comment by hishamco** [comment]
I need to revise this as well as my data annotations PR, please give me some time to list my notes if there is

**Comment by agriffard** [comment]
With this solution, we also provide custom error messages that will be added to the Crowdin translations.

**Comment by hishamco** [comment]
>  we also provide custom error messages that will be added to the Crowdin translations.

Do you mean a translations on data annotations using `PoExtractor`? If Yes this is almost done, I can let someone demo this if it's interested

Thanks for your efforts, we can use it as workaround, please give me sometime to revise my PR again, I'm sure it was working at that time ;)

**Comment by hishamco** [comment]
Thanks @agriffard for your efforts, but no long need for this workaround while the actual fix is working, have a look to my comment [here](https://github.com/OrchardCMS/OrchardCore/pull/4675#issuecomment-597786219)

**Pull request merged**
