### PR TITLE
Release 1.7.1

### PR DESCRIPTION
**Pull request by MikeAlhayek**
This PR updates branch `release/1.7` with the patch. 

Release 1.7.1 will then target `release/1.7`  not `main`

@sebastienros

### CODE REVIEW

**Comment by hishamco** [comment]
What are the bugs that are critical to fix in this release?

**Comment by MikeAlhayek** [comment]
Look at the commits #14371 is needed. I also added #142991

**Review by sebastienros — APPROVED** [review]

**Comment by sebastienros** [comment]
@MikeAlhayek we triaged two other issues that should be patch 1.7. I assigned them to the 1.7 milestone (which I re-opened, hope you'll like it)

**Comment by hishamco** [comment]
Please hold on this, seems there're many issues in RTL after updating the bootstrap

**Comment by sebastienros** [comment]
> there're many issues in RTL after updating the bootstrap

In 1.7.0 ?

**Comment by MikeAlhayek** [comment]
@sebastienros i'll work on this next week. Currently out of town.

@hishamco we are not rolling out the bootstrap in 1.7.1. That is part of 1.8 release. Please report any issue in RTL along with a PR if you can.

**Comment by hishamco** [comment]
Ya I forgot ;) hope to start some PRs

**Review by sebastienros — APPROVED** [review]

**Pull request merged**
