### PR TITLE
Supporting "not in (select)" in SQL Query

### PR DESCRIPTION
**Pull request by siyamandayubi**

### CODE REVIEW

**Comment by sebastienros** [comment]
Why not just add the `in` operator and let the current NOT handle it?

**Comment by siyamandayubi** [comment]
'In' is a little tricky, as it currently supports "in (val1,... valn)", so it needs changing that. In this way, we need a more sophisticated parser that can diffrentiate between list of values and a select statement.

On the other hand, In(select ... ) can be done using joins easily, but not in (select..) is tricky using joins

**Comment by sebastienros** [comment]
I think this should be handled with another rule that will be able to dsitinguishd between 'SELECT' or a list of literals. i can try to give it a shot. We can still use your PR if I don't manage.

**Comment by siyamandayubi** [comment]
Would be great to have that, I didn't try, as I tried to avoid having side effects.

**Comment by sebastienros** [comment]
This PR handles the extra cases
https://github.com/OrchardCMS/OrchardCore/pull/5952

**Pull request closed without merging**
