### PR TITLE
Abstract AccountContorller

### PR DESCRIPTION
**Pull request by hyzx86**
Abstracts all actions in the `AccountController`
Enable logic code to be rewritten

link to https://github.com/OrchardCMS/OrchardCore/issues/12846

### CODE REVIEW

**Comment by hyzx86** [comment]
@sebastienros  @Skrypt  Is there any problem with this?  
At present, they can work, but code naming may not be so standardized
When SPA is upgraded in the future, it may need to be further abstracted to separate the logic code from MVC

**Comment by hyzx86** [comment]
This change allows developers to freely specify views, and is not limited to a certain theme module

**Comment by hishamco** [comment]
This is weird little bit, could you please let us know what functionality need to be customizable? We could use service instead

**Comment by hyzx86** [comment]
> This is weird little bit, could you please let us know what functionality need to be customizable? We could use service instead

1.  I wan't to change login process ，Limit the authorization methods of openid client applications , some openid applications can only use external login (such as Github), and direct access to the login address is unrestricted
2.  Use script to  process  login event 

The login module is too deeply coupled with the MVC. 
Because the Controller cannot be rewritten, I have to load the OC UserModule into my project, if I want to modify these codes
but this will make it difficult to merge with the latest OC code

**Comment by hishamco** [comment]
I think introduce a service for some account functionality will make it easier to extend and customize

**Comment by hyzx86** [comment]
Yes, I admit that these codes are extreme. But it completely solves the problem of controller rewriting.
For example, if I want to debug a piece of code, I can rewrite some OC code to my project for debugging
Instead of copying the entire module to my solution

**Comment by hyzx86** [comment]
> I think introduce a service for some account functionality will make it easier to extend and customize

If services are introduced, they should be decoupled from the controller
But if I want to render some other information on the view, I will not be able to use ViewData

Perhaps developers with such requirements should copy the UserModule into their own solutions separately..

**Comment by hyzx86** [comment]
@hishamco I have entered a misunderstanding. 
Cms modules as a sample of  ocframework.
The functionality I need is no longer limited to this. 
So I should reconstruct some of the key modules.

**Pull request closed without merging**
