### PR TITLE
Fix OrchardCore.Media.Core project path

### LINKED ISSUE #7097: Move OrchardCore.Media.Core module folder up
`OrchardCore.Media.Core` module is in
src\OrchardCore\OrchardCore.Media.Core\OrchardCore.Media.Core

Move it up and change the references where it is used.

### PR DESCRIPTION
**Pull request by hishamco**
Fixed #7097

### CODE REVIEW

**Comment by agriffard** [comment]
Many errors during the build.

**Comment by agriffard** [comment]
Can you please fix the errors @hishamco ?

**Comment by hishamco** [comment]
Sorry @agriffard I was on a travel and left my laptop, I will have a look now ...

**Comment by agriffard** [comment]
If you encounter this error using the source code:
`CS0579 Duplicate 'global::System.Runtime.Versioning.TargetFrameworkAttribute' attribute - OrchardCore.Media.Core`

Remove the folder 'src\OrchardCore\OrchardCore.Media.Core\OrchardCore.Media.Core'.

**Pull request merged**
