### PR TITLE
Upgrade to .NET 5

### PR DESCRIPTION
**Pull request by agriffard**
Todos:
- [ ] Rename .NET Core to .NET in the ReadMe, GitHub baseline, docs, ....
- [ ] Release notes and breaking changes.
- [ ] Specify the minimum version of Visual Studio to use when we are sure. 
- [ ] Pre-list package dependencies that have planned to move to .NET 5 quickly after the release is available.
- [ ] Determine when exactly Azure App Service is able to host .NET 5 applications: https://aspnetcoreon.azurewebsites.net/
- [ ] Tag and branch a version of the code that will be kept on 3.1 for future potential patches. 
- [X] Use Docker mcr.microsoft.com/dotnet/sdk:5.0 and mcr.microsoft.com/dotnet/aspnet:5.0

Use Framework version `5.0.2`.

Replace TargetFramework `netcoreapp3.1` by `net5.0`.

In Dependencies.AspNetCore.props:

`Microsoft.Extensions.Caching.StackExchangeRedis` and `Microsoft.Extensions.Http.Polly` has another version than the other ones.

In PortableObjectStringLocalizer.cs, remove:

```
        [Obsolete("This method will be removed in the upcoming ASP.NET Core major release.")]
        public IStringLocalizer WithCulture(CultureInfo culture) => this;
```

In NullHtmlLocalizerFactory.cs, remove:

`            IHtmlLocalizer IHtmlLocalizer.WithCulture(CultureInfo culture) => Instance;`

### CODE REVIEW

**Comment by Skrypt** [comment]
Are we moving ahead of time to .NET 5.0?
Should we target something else than dev branch for this?

**Comment by agriffard** [comment]
Build error on `AzureADOptions`:
`AzureADOptionsConfiguration.cs(18,32): warning CS0618: 'AzureADOptions' is obsolete: 'This is obsolete and will be removed in a future version. Use Microsoft.Identity.Web instead. See https://aka.ms/ms-identity-web.'`

**Comment by Skrypt** [comment]
That's probably part of the migration from the old Azure SDK to the new one.

**Comment by Skrypt** [comment]
OrchardCore.Common.Props file `<LangVersion>9.0</LangVersion>`

**Comment by agriffard** [comment]
New build error:
`CSC : error AD0001: Analyzer 'Lucene.Net.CodeAnalysis.Lucene1000_TokenStreamOrItsIncrementTokenMethodMustBeSealedAnalyzer' threw an exception of type 'System.IO.FileNotFoundException' with message 'Could not load file or assembly 'Microsoft.CodeAnalysis.VisualBasic, Version=3.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.'. [C:\projects\orchardcore\test\OrchardCore.Tests\OrchardCore.Tests.csproj]`

**Comment by agriffard** [comment]
Here is maybe a related issue https://github.com/apache/lucenenet/issues/286 and potential fixing PR https://github.com/apache/lucenenet/pull/330

**Comment by sebastienros** [comment]
Can it be updated with rc2, and also do a small test, targeting both netcoreapp3.1 AND net5.0

**Comment by sebastienros** [comment]
Sorry, didn't see it was already on rc2, thanks.
And multi targetting might be hard due to package references.

**Comment by xperiandri** [comment]
So what how are we going to solve this issue?

**Comment by xperiandri** [comment]
We can perfectly stay at .NET Core 3.1
Just remove obsolete `WithCulture` method and release the fix ASAP.
At it is the only blocker for us.

**Comment by Diman96** [comment]
@sebastienros

**Comment by deanmarcussen** [comment]
For the guys commenting on this pr.

We can't merge this pr currently.

But if you are blocked due to the obsolete method, I think we could take a pr, just removing the obsolete method.

**Comment by agriffard** [comment]
As .NET Core will become .NET 5 in November, do we rename Orchard Core back into Orchard?
Just kidding ;-)

One question though: Will the namespaces will be renamed from `Microsoft.AspNetCore.` to `Microsoft.AspNet.` on nuget?

We will also have to replace the textual references to .NET Core in the ReadMe, GitHub baseline, website, docs, ...

**Comment by agriffard** [comment]
Cypress tests are in error:

```
Cypress could not verify that this server is running:
  > http://localhost:5000
```

@jptissot Can you please have a look?

**Comment by agriffard** [comment]
@deanmarcussen Any idea why https://www.nuget.org/packages/Microsoft.AspNetCore.DataProtection.AzureStorage does not have a 5.0 nuget package?

**Comment by deanmarcussen** [comment]
I suspect they maybe deprecating it and moving to the storage library as they did for general blob storage. https://www.nuget.org/packages/Azure.Extensions.AspNetCore.DataProtection.Blobs
https://github.com/Azure/azure-sdk-for-net/tree/master

I haven't actually found any hard evidence for that, but it makes sense.

Last time I looked this package https://www.nuget.org/packages/Azure.Extensions.AspNetCore.DataProtection.Blobs did not exist.

But now it does, so it maybe that we need to look at moving to that.

If so, can be done independently of this pr I suspect. 

Will look in more detail when I have some time - but if anyone else can find any confirmation of that, it would be helpful to understand.

**Comment by lahma** [comment]
Here's the [breaking changes document and relevant section](https://docs.microsoft.com/en-us/dotnet/core/compatibility/3.1-5.0#azure-microsoft-prefixed-azure-integration-packages-removed).

**Comment by deanmarcussen** [comment]
> breaking changes document and relevant section

Thanks @lahma there's non as blind as those who can't see :)

**Comment by jptissot** [comment]
Don't forget the docker images versions. `mcr.microsoft.com/dotnet/aspnet:5.0`

**Comment by xperiandri** [comment]
Are there any issues left to upgrade to .NET 5?

**Comment by cyptus** [comment]
@sebastienros  is there any process on this issue? `PortableObjectStringLocalizer` is still an issue for `.net 5`

**Comment by hishamco** [comment]
@cyptus what's the issue with `PortableObjectStringLocalizer`?

**Comment by cyptus** [comment]
@hishamco as `IStringLocalizer.WithCulture` does not exist in `.net 5` any more (see https://docs.microsoft.com/de-de/dotnet/api/microsoft.extensions.localization.istringlocalizer.withculture?view=dotnet-plat-ext-3.1), this leads into a `MissingMethodException` (`Method not found: 'Microsoft.Extensions.Localization.IStringLocalizer Microsoft.Extensions.Localization.IStringLocalizer.WithCulture(System.Globalization.CultureInfo)`) because of: https://github.com/OrchardCMS/OrchardCore/blob/1879619df4418ff175a59ba70dcb36bab89fcbb5/src/OrchardCore/OrchardCore.Localization.Core/PortableObject/PortableObjectStringLocalizer.cs#L78

**Comment by hishamco** [comment]
Ya, I thought that's why you complain about, but I think @deanmarcussen commented about this somewhere else

**Comment by cyptus** [comment]
so i got it right, this is still an open issue for `net 5` upgrade?
i could not find comments about this in other issues.

**Comment by deanmarcussen** [comment]
No the issue with the htmllocalizer was resolved in the dev branch some months ago. You can use the current preview feed in a core 5 app

**Comment by agriffard** [comment]
@jptissot I changed the targets in the js files of the cypress-commands folder to make it work.

**Comment by agriffard** [comment]
Closing, now that multi targets build PR has been merged.

**Comment by xperiandri** [comment]
@agriffard is it already available as packages on Cloudsmith?

**Comment by agriffard** [comment]
> @agriffard is it already available as packages on Cloudsmith?

We migrated the Multi target framework PR #8550 during last triage.

It should be available for package version >= 15884

**Pull request closed without merging**
