### PR TITLE
Lucene spatial

### LINKED ISSUE #2658: Lucene and API (REST & GraphQL) Geo distance search
Hi,

Is it possible at the moment to do a geolocation search with Lucene/Elastic Search (https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-geo-distance-query.html)  against some content items that would have a long/lat properties and access either via the REST or GraphQL endpoints.

Thanks

Steve

### LINKED ISSUE #4568: "filter" is not implemented in the Lucene module
In Lucene you can do a "filter", which is like "must", but does not affect the score and can also be cached which isn't the case for a "must".

https://lucene.apache.org/solr/guide/8_1/json-query-dsl.html#filter-queries

https://github.com/apache/lucenenet/blob/master/src/Lucene.Net.Queries/BooleanFilter.cs

### PR DESCRIPTION
**Pull request by Skrypt**
See #2725

Fixes #2658, Fixes #4568

image

image

image

### CODE REVIEW

**Comment by Skrypt** [comment]
@petedavis please merge this branch on top of your PR to get the credits of the PR.

**Comment by petedavis** [comment]
Thanks @Skrypt. Sorry I have not been looking at OC much lately. I'll get this done soon.

**Comment by petedavis** [comment]
All done @Skrypt

**Comment by sebastienros** [comment]
Should we get a demo of that branch?

**Comment by sebastienros** [comment]
Also are we missing anything from yessql to be able to index spatial fields?

**Comment by petedavis** [comment]
@sebastienros It would be good to be able to create spatial index in the data store and then use spatial queries to find the documents, but I'm not too sure if all databases will have support (eg Sqlite).

**Comment by sebastienros** [comment]
We can implement it as extension methods in the query methods (like `IsIn`), and use custom dialect implementations based on the database. I am just wondering if there is something that should/could be done.

**Comment by petedavis** [comment]
I think it should be done. If spatial content items were able to be searched from the database, I think you would be able to almost build a web page like: https://www.realestate.com.au/buy/in-adelaide,+sa+5000/map-1?includeSurrounding=false

And use more specific query where Lucene might not be the best solution.

**Comment by sebastienros** [comment]
At least right now we can do it from lucene? Do we have the specific queries handled in the json elasticsearch language (in this PR)

**Pull request closed without merging**
