### PR TITLE
Setup screen improvements

### LINKED ISSUE #2019: Setup screen should fit without scrolling
It happens on a Surface 4 Pro screen.

image

### PR DESCRIPTION
**Pull request by agriffard**
- Remove jumbotron.
- Move function setLocalizationUrl() to setup.js.
- Move the code and html about cultureList from _Layout.cshtml to index.cshtml
- Use fieldset instead of h6 .
- Separate hints between database and table prefix.

Fixes #2019

The screen with recipe and database with connection string now look like this and should fit on a 2736x1824 resolution like a Surface.

/cc @urbanit 

image

### CODE REVIEW

**Comment by sebastienros** [comment]
The Finish button looks not aligned on the left in the screenshot

**Comment by agriffard** [comment]
Updated the screenshot.

**Comment by agriffard** [comment]
@urbanit Did you have time to try this version of the setup screen?

**Comment by sebastienros** [comment]
Let the people complain about it now.

**Pull request merged**
