### PR TITLE
Mwpowellhtx/module attrib

### PR DESCRIPTION
**Pull request by mwpowellhtx**
I think I've got the bases covered here. There may need to be _Themes packaging dependencies_ added acccounting for the targets, however, I think that is probably _'there'_ for the theme build properties and such; happy to append, etc, as necessary.

Did not see any specific instructions re: destination branches, so assuming `main` for the time being. Happy to amend, append, whatever, as necessary.

Additionally, happy to also contribute to docs to help illustrate the capability; separate repo, separate PR, I assume.

Thank you!

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/OrchardCMS/OrchardCore?pullRequest=11504) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/OrchardCMS/OrchardCore?pullRequest=11504) before we can accept your contribution.<br/><br/>:x: mwpowellhtx [sign now](https://cla.dotnetfoundation.org/OrchardCMS/OrchardCore?pullRequest=11504)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/OrchardCMS/OrchardCore?pullRequest=11504) it.</sub>

**Comment by mwpowellhtx** [comment]
Perhaps the _contributors_ is maintained automatically, I do not know.

**Comment by mwpowellhtx** [comment]
There are probably hooks that need updating to pick up the unit tests that I added as well, not sure.

**Comment by mwpowellhtx** [comment]
Closing this one. I thought there must be a better way to present CSPROJ item lists for batch, and I think I have that approach in mind now. Plus, probably was unnecessary to touch the contributors, per se, so will also revert that. Should be able to turn that around today for PR. Sorry for any confusion. Thanks!

**Pull request closed without merging**
