### PR TITLE
Added Source Link Package to Dependencies.props 

### LINKED ISSUE #7890: Sourcelink is an unmanaged package reference
From the recent nuget pr `SourceLink` is now giving a warning that is an unmanaged package reference.

Probably just needs to be added to the dependencies

### PR DESCRIPTION
**Pull request by ns8482e**
Fixes #7890

### CODE REVIEW

**Comment by deanmarcussen** [comment]
I think the projecttemplates project is still throwing a warning.

@jtkech might have some thoughts on that. 
Is it weird that we’re publishing that to nuget?

Because it doesn’t have the .targets file in it so doesn’t understand what PackageManagement is

**Comment by ns8482e** [comment]
@deanmarcussen  Removed `SourceLink` nuget package from `OrchardCore.ProjectTemplates`

**Comment by jtkech** [comment]
@deanmarcussen @ns8482e 

> Because it doesn’t have the .targets file in it so doesn’t understand what PackageManagement is

Yes, it only import `OrchardCore.Commons.props`

But that's okay to just remove the `SourceLink` reference from `OrchardCore.ProjectTemplates` as we don't need it for this project, we don't need it too in the project files of the templates that are produced for a given user.

**Review by jtkech — APPROVED** [review]

**Comment by deanmarcussen** [comment]
> @deanmarcussen Removed `SourceLink` nuget package from `OrchardCore.ProjectTemplates`

Cool, good choice

**Review by deanmarcussen — APPROVED** [review]

**Pull request merged**
