### PR TITLE
Tenants States

### PR DESCRIPTION
**Pull request by agriffard**
Display the State on the title line.

Purpose: Display 10 tenants and show the pager without having to scroll.

image

### CODE REVIEW

**Comment by hishamco** [comment]
Show the badge underneath will looks better

**Comment by agriffard** [comment]
> Show the badge underneath will looks better

By underneath, do you mean below?

My goal is to condense the display.

**Comment by hishamco** [comment]
> By underneath, do you mean below?

Yes, coz the status in the badge are not equal in terms of characters length, that's why I see the UI is need to be organized little bit

**Comment by Skrypt** [comment]
Put them between the name of the tenant and the url

**Comment by agriffard** [comment]
Between title and url:

image

**Comment by Skrypt** [comment]
How about using a grid here with a col-4 which would collapse on md breakpoint to col-md-12?

**Comment by Skrypt** [comment]
Again here let's just see what Github does : 

image

**Comment by hishamco** [comment]
We can move them below as we already did in content items or use circle icons as @Skrypt suggested

**Comment by agriffard** [comment]
image

**Comment by hishamco** [comment]
@agriffard this could be simplfied by #7987

**Comment by agriffard** [comment]
Replaced by #7987

**Pull request closed without merging**
