### PR TITLE
Language Types in Razor files

### PR DESCRIPTION
**Pull request by jtkech**

### CODE REVIEW

**Comment by MikeAlhayek** [comment]
Does dotnet format not catch Razor files? Seems like all the razor files were missed.

**Comment by jtkech** [comment]
No as I saw analyzers only parse .cs files

**Comment by MikeAlhayek** [comment]
Did you use another tool to do this? Or good old find and replace all?

**Review by MikeAlhayek — APPROVED** [review]

**Comment by jtkech** [comment]
Here old find and replace ;)

**Comment by MikeAlhayek** [comment]
You may need to check for other type like Int64,Int32,Char,... just in case you find some

**Comment by jtkech** [comment]
I did it for all framework types as Byte, Single and so on, but I may have missed some

**Pull request merged**
