### PR TITLE
Module and feature constructors

### PR DESCRIPTION
**Pull request by mwpowellhtx**
Cleaned up the branch and closed a few gaps which I considered possible and after the approach became readily apparent. Supports user provided `CSPROJ` _properties_, verified in unit tests. Would be happy to contribute some docs illustrating usage as well.

### CODE REVIEW

**Comment by mwpowellhtx** [comment]
Not sure what the hooks are informing _Build & Test_, _windows_ or _ubuntu_. The unit tests are in there, may need to be shuffled a bit alongside other test projects, perhaps. But otherwise the tests themselves are _'there'_ and passing.

**Comment by mwpowellhtx** [comment]
Looking into the checks.

**Comment by mwpowellhtx** [comment]
Reopened with refreshed source branch. AFAIK should be re-running _Build & Test_ checks.

**Comment by Skrypt** [comment]
First-time contributors need a maintainer to approve running workflows.

**Comment by mwpowellhtx** [comment]
> First-time contributors need a maintainer to approve running workflows.

Thanks.

**Comment by mwpowellhtx** [comment]
> Thanks. Looks like so far so good. Will stay tuned.

And now all checks have passed. Nice.

**Comment by mwpowellhtx** [comment]
I have the docs page ready, `mkdocs.yml` hooks poised and ready to go as well.

@Skrypt Shall I just include that in the PR then?

Thank you...

**Comment by mwpowellhtx** [comment]
Added [guides](https://github.com/OrchardCMS/OrchardCore/pull/11514/commits/44995a190611a96ae202ea6c067d88db80618fca) supporting the effort. Pending checks.

**Pull request merged**
