### PR TITLE
Use Array.Empty<> over Enumerable.Empty<>

### PR DESCRIPTION
**Pull request by MikeAlhayek**

### CODE REVIEW

**Comment by kevinchalet** [comment]
Don't expect any noticeable perf' improvement (because well, `Enumerable.Empty<TResult>()` calls `Array.Empty<T>` internally 🤣), but it's a good opportunity to simplify the syntax by using `[]` instead of `Enumerable.Empty<TResult>()`/Array.Empty<T>`.

**Comment by MikeAlhayek** [comment]
@kevinchalet yes there is no advantage. just once less call :)

Also, I think `[]` is different than `Array.Empty<>`. `Array.Empty<>` returns the same instance every time whereas `[]` creates a new instances every time.

**Comment by kevinchalet** [comment]
> Also, I think `[]` is different than `Array.Empty<>`. `Array.Empty<>` returns the same instance every time whereas `[]` creates a new instances every time.

Nope: https://sharplab.io/#v2:CYLg1APgAgTAjAWAFBQMwAJboMLoN7LpGYZQAs6AsgBQCU+hxTUcADANoC66AhgE58eAT3QBedFwDcjIgF9ksoA= 😄

**Comment by MikeAlhayek** [comment]
@kevinchalet that's awesome! and change it to a mutable object like a list autmatically create new List<T>! thanks for the tip!

**Comment by kevinchalet** [comment]
> @kevinchalet that's awesome! and change it to a mutable object like a list autmatically create new List! thanks for the tip!

Yeah! And it uses `CollectionsMarshal.AsSpan()` to populate the list so it's very efficient 😄 

Note: you can even use the range operator to build collections! E.g: https://github.com/openiddict/openiddict-core/blob/fb2565e298223940de7cf5e1c2fb3dd8de5bc516/src/OpenIddict.Client/OpenIddictClientHandlers.cs#L25-L162

**Comment by MikeAlhayek** [comment]
Making this change part of #15187. closing this one.

**Pull request closed without merging**
