### PR TITLE
Dispose ZStringWriter

### PR DESCRIPTION
**Pull request by sebastienros**

### CODE REVIEW

**Comment by sebastienros** [comment]
@lahma

**Review by lahma — APPROVED** [review]
Looks legit, `Dispose()` happens after `ToString()`

**Comment by sebastienros** [comment]
OrchardCore will fly after this PR is merged

**Comment by lahma** [comment]
There's also switches for getting the writer like not being nested (single call site like this) and whether UTF-8 is enough. But this should be good enough.

**Pull request merged**
