### PR TITLE
POStringLocalizer should respect FallBackToParentUICultures

### LINKED ISSUE #3573: PortableObjectStringLocalizer doesn't respect FallBackToParentUICultures
Last few days I was revisit the localization APIs, I have a plan to redesign the APIs and reduce many of the types and improve perf if it's possible and fix some issues

One of the issues that I expect two days ago is that `PortableObjectStringLocalizer` doesn't respect `FallBackToParentUICultures` so the localizer fallback to the parent culture all the time which is totally wrong. For that I tried today to reproduce the bug and fix it

### PR DESCRIPTION
**Pull request by hishamco**
Fixes #3573

/cc @Skrypt

### CODE REVIEW

**Comment by Skrypt** [comment]
I requested a review from @sebastienros since he's the one that did the .po file provider.

**Comment by hishamco** [comment]
I was facing an issues with restoring packages on test project that's why there is few commits, now they are restore and fix the tests permanently

**Comment by hishamco** [comment]
@sebastienros few days ago I started to redesign the entire localization system, I didn't say that all APIs are not fine, but I'm trying reduce the amount of types, gain some performance and fix some issues .. one of the issues that come in my mind after digging into the code is this one

If you don't mind I can share my initial design or leave it if there's no need

**Comment by sebastienros** [comment]
Will do

**Pull request merged**
