### PR TITLE
Update Azure.Identity 1.11.4

### PR DESCRIPTION
**Pull request by hishamco**
https://www.nuget.org/packages/Azure.Identity/1.11.4
https://github.com/Azure/azure-sdk-for-net/releases/tag/Azure.Identity_1.11.4

### CODE REVIEW

**Comment by Piedone** [comment]
I have no idea how to test this. How did you test?

**Comment by hishamco** [comment]
@Piedone some packages might be hard to test, while introducing #16284 the packages will be updated automatically without testing. I might suggest adding several unit testing for corner cases that uses almost if not all the dependencies 

FYI sometimes checking the release notes for the updated package might be enough especially if it's a patch release

**Comment by Piedone** [comment]
We still need to test them, even if they're hard to test. I don't understand why this is something that we keep getting back to, or why is it controversial, to begin with, that if you change the code, you should also run it and test it. How can you otherwise ensure that you don't break something?

https://github.com/OrchardCMS/OrchardCore/pull/16284 will only run the package reference updates and open PRs, but we'll still need to test the changes before merging.

**Comment by microposmp** [comment]
Currently all builds are failing because of this package. Warnings are treated as errors.

image

**Review by Piedone — APPROVED** [review]
I checked out [the diff with the previous version](https://github.com/Azure/azure-sdk-for-net/compare/Azure.Identity_1.11.3...Azure.Identity_1.11.4) (did you also do this, Hisham?) and I _think_ there's nothing risky there. So, I'm reluctantly merging this, but going forward, we have to find a way to test every change (and I feel that I'm overstating something really obvious). See:  https://github.com/OrchardCMS/OrchardCore/discussions/15800.

I'll also look into keeping these warnings as warnings for future such cases.

**Pull request merged**
