### PR TITLE
Setting the default culture as supported

### PR DESCRIPTION
**Pull request by sebastienros**
When enabling localization, the default culture is not added to the supported list, if it's the system one.

### CODE REVIEW

**Comment by Skrypt** [comment]
I will check back but I think the Localization middleware always sets the default system culture as supported.

**Comment by jtkech** [comment]
@Skrypt as i remember the default is only a fallback when none of the cultures returned by the providers are supported.

**Comment by sebastienros** [comment]
I could see in the logs, if I set a Supported culture, then the system one would not be added. So should I instead set it only if we have custom supported cultures?

**Comment by Skrypt** [comment]
But why would the system culture would need to always be supported?

**Comment by jtkech** [comment]
Just for infos, at some point we were using a [`DefaultRequestCultureProvider`](https://github.com/OrchardCMS/OrchardCore/blob/4ad465fbf9efecc97c0c01a96423df9988e41866/src/OrchardCore/OrchardCore.Localization.Core/DefaultRequestCultureProvider.cs) added to the `RequestLocalizationOptions.RequestCultureProviders`, but i don't remember in which position.

**Comment by sebastienros** [comment]
We have a drop down, english is selected by default on my machine. If we add French, then English still appears as the default culture. Which means I can assume that English is also supported. But right now it will log that it's not if your browser sends en-US. IF I had select French as the default culture, and not added any other one, then French would be added as supported.

**Comment by sebastienros** [comment]
So when we set an additional culture, OR if we set a custom default one (not the system) then we need to add the Default one to the supported cultures.

**Comment by Skrypt** [comment]
Is it because of the AcceptLanguageHeaderRequestCultureProvider? Yes, we had a DefaultRequestCultureProvider that was fixing this issue but we dropped it.

**Comment by jtkech** [comment]
@Skrypt just saw that in fact @sebastienros set the system one as the default culture, not really a supported culture, but as a "supported" culture that can be selected as the default one (if not yet selected from another real supported culture) ;)

Then he added the condition that at least one supported culture has been added.

hmm, but why not always set the system culture to the default culture (**not in the supported list**) if not yet selected, as it appears when we 1st go to the admin settings.

**Comment by sebastienros** [comment]
If the system culture appears, it's because the setting in null. And in this case the default providers will add the system one by themselves. If another culture is set as the default, then we have to set it. If any other supported culture is added, then the dropdown still has a value with the system one and its settin is null. In this case it wouldn't be added because we have more supported cultures.

**Comment by Skrypt** [comment]
Anything that works is fine guys ; I trust you both 😉 
What you did looks like logic to me. I approve !

**Comment by jtkech** [comment]
For infos, if the culture setting is null and we don't do `options.SetDefaultCulture()`, Then by default the `options.DefaultRequestCulture` is equals to the `CultureInfo.InstalledUICulture. So maybe we don't need to set it in this case.

culture
`.

**Comment by Skrypt** [comment]
What was in the SupportCultures there @jtkech ?

**Comment by sebastienros** [comment]
I closed because the Default provider was correctly taken into account, the issue is really in MVC that emits unnecessary log

**Comment by jtkech** [comment]
@Skrypt good question

culture

So, it also adds by default the system culture to the supported culture. But we saw with @sebastienros that `.AddSupportedCultures()` is more like a `Set` because it create a new collection.

So, i sugest to do something like this to keep the already set supported cultures.

    foreach (var culture in siteSettings.SupportedCultures)
    {
        options.SupportedCultures.Add(new CultureInfo(culture));
    }

**Comment by Skrypt** [comment]
You mean .SetDefaultCulture(someCultureList) will replace instead of adding.

**Comment by jtkech** [comment]
`AddSupportedCultures` starts from a new collection, [see here](https://github.com/aspnet/AspNetCore/blob/master/src/Middleware/Localization/src/RequestLocalizationOptions.cs#L120)

**Pull request closed without merging**
