### PR TITLE
Decouple the OpenID module from the Users/Roles modules

### PR DESCRIPTION
**Pull request by PinpointTownes**
Related topic: https://github.com/OrchardCMS/OrchardCore/issues/1023

### CODE REVIEW

**Comment by PinpointTownes** [comment]
Rebased.

**Comment by sebastienros** [comment]
Is the "notready" tag still appropriate?

**Comment by PinpointTownes** [comment]
@sebastienros thanks for the review!

**Comment by sebastienros** [comment]
yolo

**Pull request merged**
