### PR TITLE
Update SlugService benchmarks

### PR DESCRIPTION
**Pull request by hishamco**

### CODE REVIEW

**Comment by sebastienros** [comment]
The comment can be removed because it depends on the machine it runs on. I don't see any value there.
What can be done with the benchmark is run it before and after a change.

**Comment by hishamco** [comment]
> The comment can be removed because it depends on the machine it runs on

Agree, but that's the pattern I saw for other benchmarks

**Comment by hishamco** [comment]
Let us close if there's no value

**Comment by hishamco** [comment]
Closed in favor of #15393

**Pull request closed without merging**
