### PR TITLE
Fix CorrelateTask

### PR DESCRIPTION
**Pull request by hyzx86**
Fix :https://github.com/OrchardCMS/OrchardCore/issues/9634

The prompt states that it is using Liquid syntax, but the code incorrectly uses the Javascript parser

image

image

### CODE REVIEW

**Comment by deanmarcussen** [comment]
This is quite breaking, because every user will be using the script evaluator.

Would it make more sense to just update the view so it says it uses a script, and remove the note about liquid?

**Comment by hyzx86** [comment]
> This is quite breaking, because every user will be using the script evaluator.
> Would it make more sense to just update the view so it says it uses a script, and remove the note about liquid?

You're right, I've fixed the prompt message and changed the editor to codemirror

image

**Review by deanmarcussen — APPROVED** [review]

**Comment by sebastienros** [comment]
Better to add an option here not to break. That's what Elsa does too.

**Review by sfmskywalker — APPROVED** [review]

**Comment by sfmskywalker** [comment]
Could be done similar to this:
syntax-switching

**Comment by Skrypt** [comment]
@sfmskywalker What happens when you have values in both these editors? Should we also save then the editor choice on the task?

**Comment by hyzx86** [comment]
> @sfmskywalker What happens when you have values in both these editors? Should we also save then the editor choice on the task?

That will imporve more code changes

https://github.com/elsa-workflows/elsa-core/blob/cc7acb1790dcb2690b786d45ce56b47bf00928f4/src/core/Elsa.Abstractions/Attributes/ActivityInputAttribute.cs#L51

**Comment by sfmskywalker** [comment]
> @sfmskywalker What happens when you have values in both these editors? Should we also save then the editor choice on the task?

@Skrypt Exactly, you would save the selected syntax.

**Review by sebastienros — APPROVED** [review]

**Comment by Skrypt** [comment]
@sebastienros Are you sure? Because seems to me like it is missing something here that would define if the editor should parse javascript or Liquid based on the editor used.

**Comment by Skrypt** [comment]
Ok, merge but open another issue to support Liquid and Javascript then.

**Pull request merged**
