### PR TITLE
Remove appveyor badge

### PR DESCRIPTION
**Pull request by alexbocharov**
Is no longer needed

### CODE REVIEW

**Comment by alexbocharov** [comment]
@sebastienros, Travis badge also remove?

**Comment by sebastienros** [comment]
Yes, we just use GH actions now

**Comment by alexbocharov** [comment]
> Yes, we just use GH actions now

Add for master :
```
[![Build status](https://github.com/OrchardCMS/OrchardCore/workflows/Release%20-%20CI/badge.svg?branch=master)](https://github.com/OrchardCMS/OrchardCore/actions?query=workflow%3A%22Release+-+CI%22)
```

**Comment by sebastienros** [comment]
We need to add [ci skip] when the PR is merged

**Review by sebastienros — APPROVED** [review]

**Pull request merged**
