### PR TITLE
Added Azure Deploy Button

### PR DESCRIPTION
**Pull request by salem84**
In regard to #7068, I have create an ARM template with following fields:

image

In details
* Web app name: name of Azure App Service
* SKU: pricing tiers of App Service Plan
* Location: the same as location of ResourceGroup
* Database type: it's a select box, now choices ar Sqlite or Sql Server
* Sql Server section: unfortunately, at least I know, it's not possible to hide this section based on Database type condition; there are all details to create a Sql Server instance and database to use during setup. Sql Server is deployed only if Database Type = SqlServer (condition in ARM template)

Behind the scenes Azure App service use a Linux container instance with orchardproject/orchardcore-cms-linux image

In Readme I have added Deploy To Azure and Visualize button.

_As described on Microsoft Docs the absolute path to azuredeploy.json file must be linked to buttons, so they must be changed before merge!_

### CODE REVIEW

**Comment by sebastienros** [comment]
SQlite is a concern here, since it won't work with multiple instances for two reasons:
- you haven't configured (didn't find it) the storage to be outside of the container, so I assume it will be lost on a reboot, and also multiple instances won't share it
- if you had done that though, then you would see a problem since Azure App Service's filesystem locks are not compatible with sqlite

For these reasons it might be better to only support service based databases (sql server, postgres, mysql)

**Comment by salem84** [comment]
> SQlite is a concern here, since it won't work with multiple instances for two reasons:
> 
> * you haven't configured (didn't find it) the storage to be outside of the container, so I assume it will be lost on a reboot, and also multiple instances won't share it
> * if you had done that though, then you would see a problem since Azure App Service's filesystem locks are not compatible with sqlite
I have configured 

> 
> For these reasons it might be better to only support service based databases (sql server, postgres, mysql)

You are right!
A solution may be use WEBSITES_ENABLE_APP_SERVICE_STORAGE and ORCHARD_APP_DATA as you described in this issue https://github.com/OrchardCMS/OrchardCore/issues/3381 ? Or you think it's better remove Sqlite option?

**Comment by Piedone** [comment]
I sincerely apologize for us taking so much time here. I checked out the PR, going over old ones, and this would be quite useful.

Is this something you'd like to revisit any time soon or should we close?

Also, since then we have https://try.orchardcore.net/ and https://dotnest.com/ if you want to quickly try out Orchard Core. Perhaps an Azure deployment like this is not the best starter experience, since you have to understand the system enough to know how to best host it for your use case. An automated deployment from your repository is recommended too.

**Comment by Piedone** [comment]
Closing due to inactivity.

**Pull request closed without merging**
