### PR TITLE
clean code of email module

### PR DESCRIPTION
**Pull request by infofromca**

### CODE REVIEW

**Comment by infofromca** [comment]
do not agree with you.
if this method is useful currently, it just means that there is bug in  the current code .
if we want to use this method in future, we can consider it in future. and I had a PR to replace this method long time ago which was not accepted, but I think it is better than this current method.

**Comment by hishamco** [comment]
If you disagree why you remove it ;)

**Comment by sebastienros** [comment]
If this method is not used we can remove it.
If we want to use a different rule than what `[Email]` is doing then we need to use the expression that was suggested in the issue where we talked about it.

**Comment by infofromca** [comment]
ok, Agree with you both

**Comment by sebastienros** [comment]
More complete fix: https://github.com/OrchardCMS/OrchardCore/pull/5238

I found that MimeKit is much better than anything for confirming to the spec without using regular expressions. It also handles comments in email addresses as showed in the unit test I added.

**Pull request closed without merging**
