### PR TITLE
fixed jObject bind for properties

### PR DESCRIPTION
**Pull request by jwu-au**

### CODE REVIEW

**Comment by jwu-au** [comment]
@ns8482e You're right that we cannot tell what user passed in. From my understanding that the responsibility in LiquidTagHelperActivator is to convert what user passed in to target type (PropertyType), if any error happens in this point, it is good time for user to get the error, and correct input object.

And I firstly looked at if I can fix this in the ContentLinkTagHelper, I found that I need to actually change the PropertyType for `DisplayFor` to (maybe) `object` type, as you said, do the checking there, convert it if it is a JObject. And also need to do it the same for other properties in the same tag helper such as "EditFor" etc. But eventually may ended up with the same line `jObject.ToObject(property.PropertyType)` . I'm happy to see an example to do the conversion in a tag helper.

Thank you.

**Comment by ns8482e** [comment]
> From my understanding that the responsibility in LiquidTagHelperActivator is to convert what user passed in to target type (PropertyType),

IMO  `LiquidTagHelperActivator` should not do any conversion as it just a helper between View and `TagHelper` has no knowledge of underlying functionality of requested `TagHelper`

Unless you find a way to be `100%` sure that input JObject is convertible to `PropertyType` without any dataloss.

**Comment by jtkech** [comment]
As commented in #6234, here a copy

Hmm, when working from `ContentItem.Content` we get a `JObject` from which we can get parts that are also `JObject` and so on. So the problem is that we can't get e.g. a real `BagPart` whose `ContentItems` property is really a `ContentItem` collection.

i think the problem is only for liquid because in razor we can use `ContentItemExtensions` as this one `As<TPart>(this ContentItem contentItem)`

So maybe one solution would be to create a liquid filter that allows to retrieve real parts / fields from a `ContentElement` (so a `ContentItem`, or a `ContentPart`, or a `ContentField`), not its json representation, e.g `contentItem | get_element "Services"`.

**Comment by agriffard** [comment]
Can you provide a PR with the changes you suggested @jtkech?

**Comment by jtkech** [comment]
@agriffard need to focus on it again when i will have time, but added on my list ;)

**Comment by jtkech** [comment]
So, as said by @sebastienros in the related issue #6234, the right fix would be

> I would either create filter that convert a JObject to a ContentItem, or have an implicit conversion from JObject to ContentItem.

But, in place of using `Model.ContentItem.Content` that is a `JObject`, just tried the following by using `Model.Content` that is a `Shape` and then `Model.Content.Services` that is a `BagPart` holding a real `List<ContentItem>`.

    {% for service in Model.Content.Services.ContentItems %}
          {% a display_for: service, class: "btn btn-primary" %}
                {{ service.DisplayText }}
          {% enda %}
    {% endfor %}

So i close this PR, feel free to re-open it if it doesn't work for you

**Pull request closed without merging**
