### PR TITLE
Tenants buttons

### PR DESCRIPTION
**Pull request by agriffard**
image

### CODE REVIEW

**Comment by hishamco** [comment]
@agriffard did the team agreed to use the buttons again? Because using many colors is confusing and doesn't make sense, there should be a set of colors according the color scheme of the theme

**Comment by agriffard** [comment]
People seem to be used to Bootstrap buttons and colors.

**Comment by hishamco** [comment]
I don't have issue with the buttons, but introducing more colors without meaning doesn't make sense, that's my point

**Comment by deanmarcussen** [comment]
I'm not a fan of the slider icon for the disable / enable.

It suggests you can swipe it, as if it was a checkbox selector.

What about tick and cross?

**Comment by agriffard** [comment]
image

**Comment by agriffard** [comment]
Ok, no more icons. 
Screenshot updated in first comment.

**Pull request merged**
