### PR TITLE
Delete role should warn the user if the role has associated users

### PR DESCRIPTION
**Pull request by hishamco**
Address the comment https://github.com/OrchardCMS/OrchardCore/issues/4319#issuecomment-533764204

Delete Role

### CODE REVIEW

**Comment by sebastienros** [comment]
I have no idea what this message mean.

I could understand that the role is removed from the users that had it. But this message is just adding confusion IMO.

**Comment by hishamco** [comment]
What about this "This role has associated users, do you really want to delete it?"

**Comment by hishamco** [comment]
@agriffard do you can suggest a better message?

**Comment by agriffard** [comment]
```
The {0} role is associated to existing users.
Are you sure you want to remove it?
```

**Comment by hishamco** [comment]
Can we :shipit:?

**Comment by hishamco** [comment]
⌚️ 📆

**Comment by hishamco** [comment]
@agriffard could you please merge this?

**Pull request merged**
