### PR TITLE
Failsafe for absent or duplicated 'database' tag

### PR DESCRIPTION
**Pull request by Leonardo-Ferreira**
If the database tag is not specified, the default database (master for Sql Server) is used. This prevents it.

### CODE REVIEW

**Comment by deanmarcussen** [comment]
The problem with doing this is it only applies to SQL server, or MySql (which is why the build failed, because on the CI we use SQLite, which has no database listed in its connection string.)

If we did want to do connection string validation, we would need to have a provider for each of the possible databases, mysql, postgresql, sql server etc.

**Comment by Leonardo-Ferreira** [comment]
@hishamco yes, the ideal place would be there, but the lack of the `database` entry is not an error, but it leads to a undesired behaviour where in the case of SQL Server, a "bad-practise" (user data in the master database)
@deanmarcussen correct, I'll patch it up

**Comment by agriffard** [comment]
Still to be reviewed.

**Comment by Piedone** [comment]
Is this something you'd like to revisit any time @Leonardo-Ferreira soon or should we close?

**Comment by Piedone** [comment]
Closing due to inactivity.

**Pull request closed without merging**
