### PR TITLE
Fix arrows for collapsible panels in RTL languages

### PR DESCRIPTION
**Pull request by hishamco**
Extend #8831 to make the arrows show properly in RTL languages

RTL Arrows

### CODE REVIEW

**Comment by hishamco** [comment]
BTW @agriffard , seems there's no need to use DOM as I said in your PR

**Comment by agriffard** [comment]
Do it everywhere it is needed, ex: FlowPart.Edit (search for `angle-right`).

The problem I encounter is when you add a new bag or form element, this is always LTR.

**Comment by hishamco** [comment]
There's no `angle-right` anymore ;)

> The problem I encounter is when you add a new bag or form element, this is always LTR.

I didn't deal with bag, if the case is to add a new item in the list, I will try to check it now

**Comment by hishamco** [comment]
When I'm trying to add a new item the arrow goes down, after publishing it shows the left arrow which is correct in case of RTL languages

**Comment by agriffard** [comment]
> When I'm trying to add a new item the arrow goes down

But when you collapse it, it will be a left arrow.

**Comment by hishamco** [comment]
> But when you collapse it, it will be a left arrow.

That's right for RTL but not for LTR. Are you talking about LTR?

**Comment by agriffard** [comment]
> There's no angle-right anymore

Do you the change also here:

https://github.com/OrchardCMS/OrchardCore/blob/fdec2c6a9a985cd6ceee7dce2e60a3347872aacd/src/OrchardCore.Modules/OrchardCore.Flows/Views/ContentCard-FlowPart.Edit.cshtml#L21

**Comment by hishamco** [comment]
Seems there 3 places, I think I made a typo while searching, I will update the PR

**Comment by agriffard** [comment]
In RTL, the dot `.` moved at the begining (ex: `.Services - Provides a collection behavior for your content item`) is a bit weird.

**Comment by hishamco** [comment]
This is because the text is English, I will try to attach a new screenshot

**Comment by hishamco** [comment]
Services

**Pull request merged**
