### PR TITLE
Enable username or email as login credentials

### PR DESCRIPTION
**Pull request by petedavis**
Update to the account controller to enable logging in with either username or email.

I haven't indicated this on the template, but it also enables sites to use a login form that shows just email/password form, which is reasonably common practice these days.

### CODE REVIEW

**Comment by sebastienros** [comment]
I disagree with the validation. I'd prefer to remove all the validation. Even the `'@'` check. Just test in the username, then the email if nothing was found. Otherwise one day we'll have to fix the fact that a username has a `@` in its username, or that an email is valid though it failed validation.

**Comment by sebastienros** [comment]
Fixes #927

**Comment by PinpointTownes** [comment]
Be extremely careful before implementing this feature: **by default**, Identity doesn't require that email addresses be unique - which is crazy IMO, as all its email-related APIs/UI pages assume that only one user can be retrieved based on an email address (when multiple users can be found in the DB, only the first one is returned: the other ones are completely ignored).

This fact could be used as a potential attack vector in apps that don't use the email address as the username and don't enforce email validation: a malicious guy could register an account with the same email address as the victim's account but with a different password, which would cause the victim to not be able to log in using his/her email address. Probably not critical, but something to keep in mind.

**Comment by PinpointTownes** [comment]
> I disagree with the validation. I'd prefer to remove all the validation.

It's also worth mentioning that using unconstrained Regex (i.e with no maximum timeout) for that could have made the users module prone to DOS attacks: https://www.owasp.org/index.php/Regular_expression_Denial_of_Service_-_ReDoS

**Comment by petedavis** [comment]
@PinpointTownes  Is there is no way we can force unique email addresses? Or given that OC is so modular, could that then be turned off by another module?

I would never want to allow the same email address to be reused. I have seen some sites even stop the username+something@gmail.com from being different to username@gmail.com.

**Comment by petedavis** [comment]
@sebastienros I originally looked at email address only. but the username can be useful on sites that show user based information (eg comments) and doesnt have privacy issues like using an email address.

Github has a login page with "Username or email address" and asks for both when registering. I think that can be a suitable default if all security issues are sorted?

Perhaps login via email address requires unique email addresses and confirmed email address, otherwise show invalid login attempt?

**Comment by PinpointTownes** [comment]
> @PinpointTownes Is there a way we can force unique email addresses? Or given that OC is so modular, could that then be turned off by another module?

We could configure Identity to force email uniqueness, but indeed, it could be reverted by another module or via the new tenant services configuration APIs, without the developer necessarily realizing it's not a good thing to do.

It's interesting to note that other places in OC also rely on the fact the developer won't turn security features off, [like antiforgery, which is enabled globally and not per-controller](https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore/OrchardCore.Mvc.Core/Startup.cs#L34). In theory, one could easily disable that (e.g for API-oriented OC projects) by removing the antiforgery validation filter, which would make non-API controllers vulnerable.

**Comment by stevetayloruk** [comment]
Personally I think keeping the email as the ‘username’ is the best approach. This could be combined with a ‘Display Name’ that can be used publicly in comments etc.  

Don’t forget MFA in this too, which comes in multiple forms and is becoming more and more standard in SaaS products.

**Comment by Skrypt** [comment]
Any updates on this? I need this feature. Is there anything left to do?

**Comment by Skrypt** [comment]
https://github.com/aspnet/AspNetCore/issues/8356

**Comment by petedavis** [comment]
Sorry @Skrypt I havent managed to get back to this. Did you implement this feature?

**Comment by Skrypt** [comment]
Nothing yet. I'm using the username with emails in them simply.

**Comment by sebastienros** [comment]
I'd like to revive this one:
1. Right now, is it possible to create a new account with an email that already exists in the database?
2. I think we should support being able to log with a username or an email, and it might just be the only option
3. I don't think we should support being able to log with only the email or only the username (i.e. prevent the other one) as long as we don't expose if the entry exists in the db when the login fails, to prevent lookups
4. Unicity:
  - usernames should be unique (and case insensitive to prevent case spoofing)
  - emails should be unique (and case insensitive to prevent case spoofing)
  - Usernames and Emails should be unique, as a whole, such that an existing email can't be used as a new username
5- Like this PR we should be able to enforce the email to be valid before enabling an account, as a setting (in the admin)
6- Usernames should not be changed if they are used to represent a user reference (they are). Or we should introduce a new identity for users and use it, and also store usernames for historical data, not reference integrity (like we need to for tenants)
7- Emails can be changed as they are not used as user identity (and they shouldn't, because they can be changed)
8- I don't see why the username and the email should not have the same value, even if they can be changed individually, as long as the value doesn't collide with another existing user. There should then be no validation on the username, but validate the email.

**Comment by sebastienros** [comment]
To make emails unique:

```
            services.Configure<IdentityOptions>(options =>
            {
               options.User.RequireUniqueEmail = true;
            });
```

**Comment by petedavis** [comment]
@sebastienros I think email and username spoofing is already protected by asp.net identiy. There is a normalized email and normalized username column that is used to search for existing accounts etc. I believe the default normalization converts to upper case. What the user enters becomes display only.

**Comment by agriffard** [comment]
Please fix the conflicts.

**Comment by agriffard** [comment]
@petedavis Please solve the conflicts.

**Comment by kevinchalet** [comment]
> Usernames and Emails should be unique, as a whole, such that an existing email can't be used as a new username

It's worth noting that it would allow a bad guy to register a fake account with a username matching a legit email address that is not yet registered. Basically, the real email owner couldn't register with his email account, which is bad.

**Comment by deanmarcussen** [comment]
> I'm still convinced this double lookup is a bad idea.

@kevinchalet how do you feel about a single lookup on either UserName or Email address. Where the UI then must have two fields.

**Comment by kevinchalet** [comment]
@kevinchalet sounds like a much better option (even from a UX perspective, as you can set the email input as `type=email`).

**Comment by agriffard** [comment]
@petedavis Can you please merge dev and fix the conflicts?

**Comment by agriffard** [comment]
Can this be closed since #7645 has been closed? @deanmarcussen

**Pull request closed without merging**
