### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by hishamco**
Continuing with @Skrypt PR #7324 and according to @jtkech comment [here](https://github.com/OrchardCMS/OrchardCore/pull/7324#issuecomment-712517789)

- [x] Use Framework Types

- [ ] Using discard symbol in `out` when it's suited

- [ ] Using inline `using`

### CODE REVIEW

**Comment by MichaelPetrinolis** [comment]
@jktech @hishamco Is there any reason to use Framework Types instead of language aliases?

**Comment by hishamco** [comment]
@MichaelPetrinolis for instance `int` is an alias for `System.Int32`, AFAIK Microsoft preferred to use the framework types instead, which is a part of their static analyzer, but I don't think there's a performance impact

**Comment by hishamco** [comment]
Also using framework type is better for readability and make it easier for those how want to change the code to the native .NET languages

Again most of the @jtkech suggestions and more are a part of the static analyzer recommended suggestions

**Comment by jtkech** [comment]
@MichaelPetrinolis @hishamco 

> Is there any reason to use Framework Types instead of language aliases?

Not really ;) I just suggested it when @Skrypt did its cleanup PR

I have a little preference on framework types just because, otherwise, Visual Studio asks me to do it ;)

**Comment by hishamco** [comment]
> I have a little preference on framework types just because, otherwise, Visual Studio asks me to do it ;)

That's what I pointed in my last comment VS is always asking, so let us make VS happy and stop asking us ;)

**Comment by Piedone** [comment]
This in VS can be configured with an editorconfig, it can equally prompt for the aliases instead. It's already configured but inconsistent since ln 37 and 37 should be the same: https://github.com/OrchardCMS/OrchardCore/blob/dev/.editorconfig#L36

I think aliases are actually much better since they're a bit easier to write (no capitalization) and in some cases shorter (e.g. `int` vs `Int32`) and all snippets, and I have a hunch the majority of code written and available on the internet, use it. It's extremely rare to see C# code use e.g. `String`, `Int32`... Also, while this should be extremely rare, but you can also have a custom class or struct named as the framework types in your own namespace, so `String myString` doesn't necessarily mean the same as `string myString` while the latter will always refer to `System.String`. There are further arguments for aliases here: https://stackoverflow.com/questions/3730756/why-should-you-use-the-c-sharp-predefined-types-rather-than-the-aliases-in-the-s

**Comment by Skrypt** [comment]
Closing as we will do it right before releasing 1.0.
Keep your ideas for then. Or the action here should be about provinding proper .editorconfig settings for this to work properly by then.

**Pull request closed without merging**
