### PR TITLE
IUpdater null check

### PR DESCRIPTION
**Pull request by jtkech**
Allows to build a content item with a list part when there is no `IUpdater`, e. in the context of a razor page. But maybe not intended to be used in this context.

### CODE REVIEW

**Comment by sebastienros** [comment]
How do you reproduce the bug?

**Comment by jtkech** [comment]
i deleted the testing code.

But for a demo i injected in a razor page the content manager and display manager services, then after getting the blog content item i did a buildDisplay and then a display and it was failing when trying to update the pager.

**Comment by jtkech** [comment]
for a list part, even we are displaying (not editing) the controller `IUpdater` is used to grab the pager parameters from the query string as i remember.

**Comment by jtkech** [comment]
Maybe we can merge this one, it is just a null check.

- I had the issue when trying to render a list in a decoupled way from a razor page.

- When displaying a list part, even we are not editing, `IUpdater` is still used to bind to the pager shape the parameters from the query string.

Another fix would be to not use `IUpdater` when displaying but another way to update the pager shape.

**Comment by jtkech** [comment]
@sebastienros 

I saw that a razor page has some methods as `TryUpdateModelAsync()` so maybe we just need a `PageModelUpdater` and maybe also find a way to hold it through the `IUpdateModelAccessor`.

**Comment by jtkech** [comment]
I created a `RazorPageModelUpdater : IUpdateModel` instead, i will create a new PR.

**Pull request closed without merging**
