### PR TITLE
Add headless recipe

### PR DESCRIPTION
**Pull request by deanmarcussen**
Fixes https://github.com/OrchardCMS/OrchardCore/issues/4793

I've made a headless recipe, based on the blank recipe, with these extra features enabled
- OrchardCore.Apis.GraphQL
- OrchardCore.OpenId
- OrchardCore.OpenId.Management
- OrchardCore.OpenId.Server
- OrchardCore.OpenId.Validation

and removing the following features based on this logic
- OrchardCore.HomeRoute (not required, home just gives 404)
- OrchardCore.DynamicCache (unused by graphql)
- OrchardCore.ContentPreview (can't preview an api call)
- OrchardCore.Feeds (no html, so no feed?)
- OrchardCore.Queries (not supported by graphql?)
- OrchardCore.Templates (not adding templates)

I didn't enable OpenId.Client as that feels like something you'd turn on if you need it.

Most content management features are still enabled, just removed ones that aren't supported by GraphQL

And the ones I disabled are up for debate

### CODE REVIEW

**Comment by Skrypt** [comment]
I think that GraphQL has a method to return a content item rendered HTML so templates are still relevant for that matter. Queries are also as we can access them with a direct API call and could be required for things like a full text search or a custom Query. Also, not sure, but I think @sebastienros recently fixed something with the content preview so that it works on decoupled or headless (not sure which one).

**Comment by deanmarcussen** [comment]
@Skrypt yes, you're right.
Have included templates, queries, and preview (as if you have templates, then you want preview)

**Comment by sebastienros** [comment]
I agree that Queries needs to be kept, it has default rest endpoints and should probably have GraphQL ones if not already the case (what a shame, so important).

As for Templates/Preview, it's tangential as even if graphql has a way to render the html, it doesn't mean that it should by default. I would not encourage that as it means users would have to learn about shapes and template alternates ... which is the opposite of a lean headless stack. And we would not prevent them from doing it if they want, as the feature is available, but I wouldn't enable it by default.

**Comment by jrestall** [comment]
Cool!

Will this automatically redirect to the Admin site given that there's no front-end or do we need to set the HomeRoute like below?

```
    {
      "name": "settings",
      "HomeRoute": {
        "Action": "Index",
        "Controller": "Admin",
        "Area": "OrchardCore.Admin"
      }
    },
```

I also wonder if we should enable anonymous graphql execution with read only permission to make it easy to get started or if we want it secure by default.

**Comment by sebastienros** [comment]
I think we should keep it secure by default. If we don't do it, then we are just waiting for a big website to get its data expose, just to see people laugh at us for disabling auth by default before we change it.

**Comment by sebastienros** [comment]
A tutorial like the decoupled cms one would explain how to configure different auths, and maybe first disable it for test purposes.

**Comment by deanmarcussen** [comment]
Good feedback guys, cheers.

Have adapted to the following
- `HomeRoute` enabled, and set in site settings to `admin`
- Removed `Templates` and `ContentPreview`
- Removed `Autoroute` - yes querably by graphql but to me makes no sense for headless by default? could reenable if others disagree
- Included roles permissions (meant to do this yesterday but ran out of time)
    - anonymous view content permission removed
    - authenticated permission given to 
        - ExecuteGraphQL
        - ExecuteQueries
        - View Content
    - This is pretty much how I've setup Orchard Core api's previously, but noting that the default permissions for `ExecuteGraphQL` are administrator only, but open to feedback. I think this should be ok for the GraphQL Permissions PR as that adds a new permission for mutations, and relies on ViewContent and ExecuteGraphQL for others. /cc @carlwoodhouse  am I correct in those assumptions?

Still to follow, probably a seperate PR, based on this headless may still need some tweaks, is a readme (for the getting started tab) explaining roughly what is in each theme / package and the difference between the Core and Cms meta packages

3/4 written, but can't complete, until it's confirmed what's going in this headless recipe.

Side Note: I notice that we've got role descriptions now, but no descriptions for the default roles. Or in fact a way to edit role descriptions after creation.

**Comment by carlwoodhouse** [comment]
Mostly correct ya!

We might need to check some of the queries for layers / media etc, not exactly sure how those permissions work currently; we might just need to wire up the graphql queries to use the appropriate permissions for those. /cc @jrestall

**Comment by jrestall** [comment]
@carlwoodhouse Yea those queries don't have any explicit permissions set. Once your permissions PR is merged, we could wire them up to specifically check for 'View Media' and a new 'View layers' permission.

**Comment by sebastienros** [comment]
LGTM but I'd like to see a demo

**Comment by deanmarcussen** [comment]
Should be mentioned @carlwoodhouse suggests the permissions pr for graphql https://github.com/OrchardCMS/OrchardCore/pull/3951 is merged first, and I agree, as we could setup the recipe to support those permissions.

Demo next week :)

**Pull request merged**
