### PR TITLE
Generic handler for distributed cache exceptions

### PR DESCRIPTION
**Pull request by ShaneCourtrille**
Alternative implementation of existing PR [Support Distributed Caching bypass capability](https://github.com/OrchardCMS/OrchardCore/pull/10297)

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/OrchardCMS/OrchardCore?pullRequest=10313) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/OrchardCMS/OrchardCore?pullRequest=10313) before we can accept your contribution.<br/><br/>:x: ShaneCourtrille [sign now](https://cla.dotnetfoundation.org/OrchardCMS/OrchardCore?pullRequest=10313)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/OrchardCMS/OrchardCore?pullRequest=10313) it.</sub>

**Comment by jtkech** [comment]
@ShaneCourtrille 

I like the idea, will review it soon

Will see about injecting the breaker or using it as a component

**Comment by ShaneCourtrille** [comment]
> I sincerely apologize for us taking so much time here. Sadly, JT will not reply to you anymore (#14954). Can you @ShaneCourtrille please confirm that due to #10197 being closed by #10338 this PR and #10297 is not applicable anymore and can be closed?

Yes, this PR is no longer required.

**Comment by Piedone** [comment]
Thanks for your quick reply!

**Pull request closed without merging**
