### PR TITLE
Fixing GraphiQL on tenants

### LINKED ISSUE #2669: GraphQL not tenant aware
I am trying to use GraphQL in a tenant and it would not work. Testing in the default tenant is fine, so I am assuming that there is a tenant awareness issue here.

### PR DESCRIPTION
**Pull request by sebastienros**
Fixes #2669

### CODE REVIEW

**Comment by jrestall** [comment]
I don't think the average user would even understand what GraphiQL is. 'API Explorer' or the current 'GraphQL Explorer' seem more approachable.

**Comment by sebastienros** [comment]
> the average user would even understand what GraphiQL is

Ask an average user what GraphQL is 😄

**Comment by jrestall** [comment]
Fair enough, my vote is still for 'API Explorer' over 'GraphiQL' though since more people would understand what that is.

**Comment by sebastienros** [comment]
Got it, file an issue so we can track this.

**Comment by jrestall** [comment]
Okay it was just a suggestion, we can leave it as is rather than clutter up the issues.

**Pull request merged**
