### PR TITLE
Memory Leaks

### LINKED ISSUE #14117: Struggling with high memory usage
### Describe the bug
My scenario: We have a site built on Orchard Core 1.6. We have a pipeline that periodically deploys an instance to a test server and runs a suite of UI tests against it (the tests are using MSTest and Playwright, if it makes any difference). The site is running in IIS. The test suite runs for about 1 hour, and by the end of that run the w3wp process is consuming over 8.5 GB. `ASPNETCORE_ENVIRONMENT` is set to "Development".

Here's a quick look at the memory usage over time. This is the memory of the entire machine, not just OC, but looking in Task Manager, I see w3wp using over 8.5 GB.

image

### To Reproduce
I've been struggling for quite a while on pinpointing the root issue, with no success thus far. I've tried using the Visual Studio memory profiler but I've been struggling to make any sense of it.

I next tried a much simpler example. This next example is a plain old OC site (latest from the main branch) using the blog recipe. That's it. `ASPNETCORE_ENVIRONMENT` is set to "Development". I then wrote a small PowerShell script to ping the site over and over.

```
function Invoke-Path($path) {
    Invoke-WebRequest -Uri "https://localhost:8001/${path}"
}

$Paths = @(
    '', 
    'categories', 
    'tags', 
    'Contents/ContentItems/40rg5j34w43er1a5dwg0j14cnr', 
    'login'
)

while (1) {
    $Paths | ForEach-Object -Process {
        Invoke-Path $_
    }
}
``` 

I ran this script for a little while. Looking at the diagnostic tools in Visual Studio, I can see multiple garbage collector invocations (the yellow arrows), but the memory never seems to decrease. I was hoping to see a more jagged pattern in the memory usage.

image

image

At this point I'm looking for any ideas or advice. Thanks.

### PR DESCRIPTION
**Pull request by jtkech**
Fixes #14117 

- Here we override the `IHttpClientFactory`, mainly to make it `IDisposable` so that when releasing / reloading a Tenant we dispose clients Handlers and their Scope and cleanup Timers.

    So we may not need #14335 but stiil worth to only create a `RecaptchaClient` on demand.

- On Tenant Reloading, we now also Release the 2 inner `IConfiguration` of `ShellSettings`.

- About razor view compiled items, we already have a static shared compiler provider but that we only use if razor runtime compilation is enabled, here we always register it.

        // Shares across tenants a static compiler even if there is no runtime compilation
        // because the compiler still uses its internal cache to retrieve compiled items.
        services.AddSingleton<IViewCompilerProvider, SharedViewCompilerProvider>();

    Here we also reduce the number of times the compiled items are loaded, before 3 times per tenant building, now only once by caching the descriptors built in a given shell scope.

    We can still have duplicate strings but they are no longer rooted, the only one holding them being our static compiler that we now always use, and now it only references one instance of `"mvc.1.0.view"`.

- Also here we now call `CreateChildContainer()` once while building a shell.

- Finally also include the building of `RecaptchaClient` only on demand.

### CODE REVIEW

**Comment by jtkech** [comment]
Need some last tweaks and I may have some last ideas, for example not holding a released shell in the background for one minute, I'm working on this.

For now I rely on https://github.com/OrchardCMS/OrchardCore/issues/14117#issuecomment-1731500607 and https://github.com/OrchardCMS/OrchardCore/issues/14117#issuecomment-1731718238

Also @rjpowers10 and @wAsnk may do further testing soon.

> I tested it in our own solution with local NuGet files and it looks really good. I will do further testing in the upcoming days.

**Comment by jtkech** [comment]
Also here we now call `CreateChildContainer()` once while building a shell.

**Comment by MikeAlhayek** [comment]
Thanks for merging this one! Lots of work done! Great job!

**Comment by jtkech** [comment]
No problem, hope I didn't break anything 🤞

**Comment by rjpowers10** [comment]
Thank you @jtkech! Looking forward to the improvements in the next release.

**Pull request merged**
