### PR TITLE
GraphQL and JsonAPI

### PR DESCRIPTION
**Pull request by Jetski5822**
This is the PR for both GraphQL and JsonAPI endpoints. This is for initial review until we are all happy. I will update PR with more details later.

### CODE REVIEW

**Comment by sebastienros** [comment]
Haven't looked at the PR closely, small question first, is there a Permission to execute it? I think this is a minimum to have, at least to secure it, and also as it would work with token auth. Then a set of more granular permissions would be good, for specific kinds of queries, unless it's relying on other component's permissions, like content management, queries, tenant creation, data creation.

**Comment by sebastienros** [comment]
I was mentioning a proper Permission object for GraphQL endpoint, like "AccessGraphQL" and others sto access specific parts of GraphQL. Even before checking if the result can be displayed or not. That will prevent DOS attacks at least. Look at what the Queries api has.

**Comment by Jetski5822** [comment]
@sebastienros I know what you meant :) just haven’t added it just yet!! But will over the next day or two.

**Comment by jtkech** [comment]
Oh, so many things, i will review it as soon as i have time.
But first i will need to learn a little GraphQL and JsonAPI.
Just saw a typo: `ApiValueProivder` => `ApiValueProvider` ;)

**Comment by Jetski5822** [comment]
Im not happy with the JsonApi implementation, so am pulling the PR for now.

**Pull request closed without merging**
