### PR TITLE
Update the sort logic in the assets grouping

### PR DESCRIPTION
**Pull request by MikeAlhayek**

### CODE REVIEW

**Comment by MikeAlhayek** [comment]
@Piedone why would the validation the building fails? I rebuild the assets.

**Comment by Piedone** [comment]
What's exactly the goal here?

Check out the workflow output with the diff, and/or download the files the workflow built under https://github.com/OrchardCMS/OrchardCore/actions/runs/8808647832?pr=15815 and compare them locally.

**Comment by MikeAlhayek** [comment]
@Piedone the goal is as follow

```
// The inputPaths can contain either a physical path to a file or a path with a wildcard.
// It's crucial to maintain the order of each file based on its position in the assets.json file.
// When a path contains a wildcard, we need to convert the wildcard to physical paths
// and sort them independently of the previous paths to ensure consistent concatenation.
```

so if we have 
[
  {
    "inputs": [
      "./physical-path1.js",
      "./Assets/js/*.js",
      "./physical-path2.js",
    ]
  }
]

we should append 
 1. physical-path1.js
 2. all the files sorted from the js folder.
 3. physical-path2.js

**Comment by MikeAlhayek** [comment]
> Check out the workflow output with the diff, and/or download the files the workflow built under https://github.com/OrchardCMS/OrchardCore/actions/runs/8808647832?pr=15815 and compare them locally.

yes but it should not fail here since I rebuild the assets.

**Comment by Piedone** [comment]
Do we have a use case for this among our assets?

What I'd do is download the files and check out the diffs locally. That'll hint at what may go differently.

**Comment by hishamco** [comment]
> @MikeAlhayek has exceeded the limit for the number of commits or files that can be reviewed per hour. Please wait 27 minutes and 8 seconds before requesting another review.

Seems a lot of us will wait if there's a rate limiting :)

**Comment by MikeAlhayek** [comment]
@Piedone I still don't understand why the WF is failing. The order of the concatenated files could have been changed. but the fact that I build the assets should be enough for the WF to work. Are you able to look into it little more please? I think the order of files in this PR is correct and should work.

**Comment by Piedone** [comment]
Did you download the workflow artifact and check for the changes locally, compared to your files?

**Comment by MikeAlhayek** [comment]
@Piedone you should be able to see what changed using the diff view here. Looks like spacing changed and order of there the code is added. But, since I recreated all of the resources, it should not detect anything that isn't generated.

This looks strange, it is changing the order of the concatenated files, but it seems that the method definition is changing. I am working if `npm install` is using a different package version for example **"gulp-postcss": "^9.0.1"** is in the dependency, when we run npm install its going to install `gulp-postcss 9.0.latest` and use that. 

image

**Comment by MikeAlhayek** [comment]
Here is another strange one. the new files are generated with a different parameter name for the function than the one in production.

image

**Comment by Piedone** [comment]
Running `npm install`, then `npm run rebuild` for me yields a bunch of changes in this branch too, e.g.:

image

Downloading the artifact from https://github.com/OrchardCMS/OrchardCore/actions/runs/8930280187?pr=15815 yields slightly different changes.

So, it seems that the Gulpfile changes cause the merged files to be flaky/dependent on the platform. I don't know why.

However, I don't think it's worth putting any more time in this. I've spent about a workday sorting this out previously, with the goal of getting it to a stable state, so we can keep updating assets and get a reliable feedback if we've forgotten that. The changes in this PR address a use case that we don't actually have. It'd be nice to have (but still only "nice to have" and low on the list of priorities in my book due to the lack of use cases) if we were to want to maintain this assets pipeline for the foreseeable future, but we want to get rid of it.

**Comment by MikeAlhayek** [comment]
@Piedone We actually use it and should fix it.

Here is one example
https://github.com/OrchardCMS/OrchardCore/blob/main/src/OrchardCore.Modules/OrchardCore.Media/Assets.json#L11-L14

**Comment by Piedone** [comment]
I see. I searched and that's the only file where globbing and static paths are mixed. Only globbing is supported, even if multiple wildcard paths are listed (what also happens a few times). So, I suggest expanding that config manually by listing all the files, or converting it to an all-wildcard one.

And if you want to really diligent, then also add a validation [here](https://github.com/OrchardCMS/OrchardCore/blob/b56ea9675c7c0ae03575681c89983ab899261625/gulpfile.js#L122) that will fail the pipeline if the two are mixed.

**Comment by MikeAlhayek** [comment]
Here is the output of that media. The results are what I am expecting.

The logic in main is wrong and the use of `.sort()` is incorrect in main
```
[
  'C:/Code/OrchardCMS/OrchardCore/src/OrchardCore.Modules/OrchardCore.Media/node_modules/blueimp-file-upload/js/jquery.fileupload.js',
  'C:/Code/OrchardCMS/OrchardCore/src/OrchardCore.Modules/OrchardCore.Media/node_modules/blueimp-file-upload/js/jquery.iframe-transport.js',
  'C:/Code/OrchardCMS/OrchardCore/src/OrchardCore.Modules/OrchardCore.Media/Assets/js/helpers.js',
  'C:/Code/OrchardCMS/OrchardCore/src/OrchardCore.Modules/OrchardCore.Media/Assets/js/app/MediaApp/app.js',
  'C:/Code/OrchardCMS/OrchardCore/src/OrchardCore.Modules/OrchardCore.Media/Assets/js/app/MediaApp/fileupload.js',
  'C:/Code/OrchardCMS/OrchardCore/src/OrchardCore.Modules/OrchardCore.Media/Assets/js/app/MediaApp/folderComponent.js',
  'C:/Code/OrchardCMS/OrchardCore/src/OrchardCore.Modules/OrchardCore.Media/Assets/js/app/MediaApp/font-awesome-thumbnails.js',
  'C:/Code/OrchardCMS/OrchardCore/src/OrchardCore.Modules/OrchardCore.Media/Assets/js/app/MediaApp/mediaItemsGridComponent.js',
  'C:/Code/OrchardCMS/OrchardCore/src/OrchardCore.Modules/OrchardCore.Media/Assets/js/app/MediaApp/mediaItemsTableComponent.js',
  'C:/Code/OrchardCMS/OrchardCore/src/OrchardCore.Modules/OrchardCore.Media/Assets/js/app/MediaApp/pagerComponent.js',
  'C:/Code/OrchardCMS/OrchardCore/src/OrchardCore.Modules/OrchardCore.Media/Assets/js/app/MediaApp/sortIndicatorComponent.js',
  'C:/Code/OrchardCMS/OrchardCore/src/OrchardCore.Modules/OrchardCore.Media/Assets/js/app/MediaField/attachedMediaField.js',
  'C:/Code/OrchardCMS/OrchardCore/src/OrchardCore.Modules/OrchardCore.Media/Assets/js/app/MediaField/mediaFieldThumbsContainer.js',
  'C:/Code/OrchardCMS/OrchardCore/src/OrchardCore.Modules/OrchardCore.Media/Assets/js/app/MediaField/mediafield.js',
  'C:/Code/OrchardCMS/OrchardCore/src/OrchardCore.Modules/OrchardCore.Media/Assets/js/app/MediaField/mediafieldsAppsArray.js',
  'C:/Code/OrchardCMS/OrchardCore/src/OrchardCore.Modules/OrchardCore.Media/Assets/js/app/Shared/uploadComponent.js',
  'C:/Code/OrchardCMS/OrchardCore/src/OrchardCore.Modules/OrchardCore.Media/Assets/js/app/Shared/uploadListComponent.js'
]

```

**Comment by MikeAlhayek** [comment]
@Piedone your soon to be favor PR is passing. I am wondering if there was something wrong with my environment. But what I did was to run `npm remove gulp-print gulp-debug` which generated the updated packages-lock.json file. New files were generated locally and it passed. I am not sure if all I needed was `npm cache clean --force`

I am just happy that it finally worked and the files sorting is correct.

**Comment by MikeAlhayek** [comment]
@Piedone you good with this?

**Review by Piedone — COMMENTED** [review]
I wasn't aware that you're requesting my review here, sorry.

Does `gulp watch` work for you? For me, it gets stuck on this, never completing and thus never changing the output files:

image

**Comment by Piedone** [comment]
That seems like an in-progress build still. Does the output file change in the end?

**Comment by MikeAlhayek** [comment]
It does change for me.

image

**Review by Piedone — APPROVED** [review]
OK then!

**Pull request merged**
