### PR TITLE
Fixes #3212 : Allow theming for Login/Registration/ResetPassword

### LINKED ISSUE #3212: Allow theming for Login/Registration/ResetPassword
Since #2371 Login/Registration/ResetPassword Controllers use Admin theme for headless/themeless usages.
This implies creating an admin theme if you need to customize those pages.

Proposal :
- Move `[Login|Registration|ResetPassword]Controller` to `Base[Login|Registration|ResetPassword]Controller` as abstract controllers.
- Inherit those controllers for site usages as `[Login|Registration|ResetPassword]Controller` without `AdminAttribute` => uses site theme and view overrides.
- Inherit those controllers for admin usages as `Admin[Login|Registration|ResetPassword]Controller` with `AdminAttribute` => uses admin theme.

We also have to find a way to redirect `/login` route to the right controller depending if there is an active site theme or not.

### PR DESCRIPTION
**Pull request by TFleury**
Use admin theme as fallback only

### CODE REVIEW

**Comment by sebastienros** [comment]
I would prefer to keep the default behavior on the admin side of the things, and only opt-in for it to be served on the front-end, using a custom feature, or a setting. We need to check that it still works fine if no customization is provided in the front-end theme when this feature is enabled.

**Comment by TFleury** [comment]
It also fixes #2612 partially.

Having AdminAttribute on those controllers, that are not intended to run in the admin UI has undesired side effects (401 response code).

IMO, serving those page from font-end is the default usage. Serving from admin could be opt-in setting.
Until #2371, serving from front-end was the accepted/normal behavior (like in O1). This behavior was changed because of a malfunction with themeless scenario.

I tested it by my side without any front-end theme and works fine, but I could miss some scenarios.

**Comment by Skrypt** [comment]
It's been changed for supporting SaaS scenario usage and Headless scenario usage.

**Comment by sebastienros** [comment]
I don't think most sites care about customizing the login experience. So if we can prevent users from __having to__ customize it, it's better IMO. Otherwise if you have a custom theme and you go to the login screen and the form is completely off because it was not customized. Also, even you the front-end theme was the default one, you would still need custom views. Which means there is no advantage at all in using the FE theme by default. It _might _ just look ok, if you are lucky. But with admin controllers you are sure it will look ok in all cases.

#2612 is a different problem that can be resolved independently by changing the registration feature.

**Comment by TFleury** [comment]
> I don't think most sites care about customizing the login experience. So if we can prevent users from having to customize it, it's better IMO. Otherwise if you have a custom theme and you go to the login screen and the form is completely off because it was not customized. Also, even you the front-end theme was the default one, you would still need custom views. Which means there is no advantage at all in using the FE theme by default. It _might _ just look ok, if you are lucky. But with admin controllers you are sure it will look ok in all cases.

I agree with that. So, let's go for a opt-in setting to use front-end theme.
Maybe we can have a setting per controller/feature :
```
public class LoginSettings
{
    public bool UseSiteTheme { get; set; }
}
```
```
public class RegistrationSettings {
    public bool UsersCanRegister { get; set; }
    public bool UsersMustValidateEmail { get; set; }
    public bool UseSiteTheme { get; set; }
}
```
```
public class ResetPasswordSettings {
    public bool AllowResetPassword { get; set; }
    public bool UseSiteTheme { get; set; }
}
```
Or do you think one setting would be enough ?

> #2612 is a different problem that can be resolved independently by changing the registration feature.

I still think it's mostly due to `AdminFilter`. We want admin theme, but we don't want to check `AccessAdminPanel` permission.

**Comment by sebastienros** [comment]
Not sure about #2612. Try without it first.

**Comment by TFleury** [comment]
I added opt-in settings.
If "Use site theme" is opted in, it lets `SiteThemeSelector` do its job, but always provides admin theme as fallback (in case there is no site theme).
Othewise, it selects admin theme with same priority as `AdminThemeSelector`, avoiding `AdminAttribute` security checks.

**Pull request merged**
