### PR TITLE
Fix to DbConnectionAccessor with Documentation Added

### PR DESCRIPTION
**Pull request by mdockal**
I ran into some weird issues with Orchard Core this weekend.  I tried saving updates to pages and I couldn't do that.  I tried adding new users and that also failed.  It seemed like every time I tried to save something to the database it failed.   I was also using `DbConnectionAccessor.GetConnectionAsync()' to write data to the database.  I wondered if this new class was causing some issues so I commented it out where it was registered in debug and everything started working again like it was supposed to.    So I uncommented it and injected it into OrchardCore.Users module to see what was happening.   I eventually got and exception that the connection was null when it was trying to dispose.  I think maybe this was what was causing problems because I wasn't getting an exception when I was doing it via the nuget packages.   I also wanted to see where else the DbConnectionAccessor was being used and I found where it wasn't being disposed in ShellDescriptorManager.   The connection wasn't being closed either.

I think the following changes will remedy the situation:

- Fixed issue with DbConnectionAccessor throwing exception when disposed because the connection was null.  
- Wrapped DbConnectionAccessor in using block in ShellDescriptorManager so it is disposed.
- Created Readme.md for DbConnectionAccessor in OrchardCore.Data

### CODE REVIEW

**Comment by mdockal** [comment]
Added TablePrefix property to IDbConnectionAccessor since it wraps Store and you probably need it.  Modified IndexingTaskManager to use DbConnectionAccessor for the sake of consistency.   Removed redundant call to IStore since DBConnectionAccessor has TablePrefix property.   Updated the Readme.md to reflect these changes.

**Comment by mdockal** [comment]
Well maybe I shouldn't have changed the IndexingTaskManager but then again maybe this is why I am having weird issues.  

The reason the builds failed was 6 of the tests failed on Appveyor:
`System.AggregateException : One or more errors occurred. (SQLite Error 6: 'database table is locked'.)
---- Microsoft.Data.Sqlite.SqliteException : SQLite Error 6: 'database table is locked'.`

Ditto on Travis CI...

**Comment by mdockal** [comment]
Hopefully this will fix the database locking:
- Added `DbConnectionAccessor.Dispose()` to `IndexingTaskManager.Dispose()`.

**Comment by sebastienros** [comment]
This is typical of a soon to come maintenance nightmare ... Conflicting services with different Dispose scopes, surfacing unrelated components (table prefix in connections) ...

I won't ask to remove it if you can state how to reproduce the issue, what is actually causing the issue, and limit it to a fix that doesn't rely on disposing the `IDbConnectionAccessor` as it's a DI injected service and the DI should be responsible to do it. If this service causes more concern than help then we'll need to remove it. It might not be as simple as I initially thought.

**Comment by mdockal** [comment]
Working on response…. Had to work on other things yesterday.

**Comment by mdockal** [comment]
> This is typical of a soon to come maintenance nightmare ... Conflicting services with different Dispose scopes, surfacing unrelated components (table prefix in connections) ...
> 
> I won't ask to remove it if you can state how to reproduce the issue, what is actually causing the issue, and limit it to a fix that doesn't rely on disposing the `IDbConnectionAccessor` as it's a DI injected service and the DI should be responsible to do it. If this service causes more concern than help then we'll need to remove it. It might not be as simple as I initially thought.

I tried to make too many changes instead of just focusing on the issue at hand.  However, It would be nice to know the table prefix if you are creating custom tables.   Since DbConnectionAccessor wraps the Store object I thought it would be appropriate.   In order to get the  TablePrefix I would also have to inject the IStore which seems redundant.  The class could be renamed to DbAccessor since it would be doing more than just providing a connection.  

I was having some weird errors the other day.  I would try to do simple things like add a user or change there password and was getting an error like "The operation could not be completed"  in dev and in production using the nuget packages.   At the same time, I was using the DbConnnectionAccessor in a custom module and I thought it was somehow locking the database.    So I tried to reproduce the error in debug mode by adding it to the OrchardCore.Menus module.    I tried adding a menu and bam I got a null reference exception basically saying the connection was null when DI was trying to dispose of it.   I uncommented where the DbConnection Accessor was injected and everything started working normally.    I tried to reproduce the error in debug mode again today to no avail.   Turns out I think my dev environment was hosed because I had added docker support to the website project but was running on IIS Express and was causing some weird issues.

I think there could be a problem with Dispose if the connection is null that is why I changed it to _connection?.Dispose().   It would also be nice to have documentation of this feature but I am not sure weather to put it in OrchardCore.Data or OrchardCore.Data.Abstractions.

**Comment by sebastienros** [comment]
If we intend to dispose connections then we should register the connection as Transient, so that each call gets a new connection.

Also with my latest change it should be work better, the way sqlite and other services where handling connections were different, hence some potential scoping issues. I will commit on this PR all the changes I think are necessary.

**Comment by sebastienros** [comment]
Replaced by https://github.com/OrchardCMS/OrchardCore/pull/3131

I used a simpler approach to prevent any unwanted side effects.

**Pull request closed without merging**
