### PR TITLE
Fix edit template dropdown style in RTL

### LINKED ISSUE #3708: Edit templates dropdown style issue in RTL
This is moved from #3705, after little investigation the reason behind is `bootstrap.js` while doing a calculation to display the dropdown list

It is tricky little bit because we can't change the original bootstrap file, but hopefully I will find way to make this work

### PR DESCRIPTION
**Pull request by hishamco**
Fixes #3708

### CODE REVIEW

**Comment by sebastienros** [comment]
Please regenerate the css files

**Comment by hishamco** [comment]
Soon

**Comment by hishamco** [comment]
Seems I should do it again after you accepted one of my PR 😄

**Comment by hishamco** [comment]
@sebastienros please merge before someone else did a change in one of those files 😄

**Pull request merged**
