### PR TITLE
Prevent too many liquid shape recursion

### LINKED ISSUE #4368: Liquid Template: Exception of type 'System.StackOverflowException' was thrown.
Liquid Templates  throws  'System.StackOverflowException' and application crashes.

`
{{ Model | shape_render }}
`
should not be allowed within liquid template and should not be saved.

As OC shape that defines above syntax tries to call itself.

### PR DESCRIPTION
**Pull request by jtkech**
Fixes #4368 

- A counter is incremented on a liquid `shape_render` execution but only when the shape renders itself, so this doesn't limit the number of execution of a given shape while in the context of another shape.

- Then we check if this counter is greater than a maximum. Using a maximum of 1 doesn't break the menu because each item renders itself but once. Here i use a value of 10.

- If the counter > max => we return an empty htmlString to break the loop.

### CODE REVIEW

**Comment by hishamco** [comment]
Why we didn't implement it in Fluid itself?!!

**Comment by jtkech** [comment]
I will re-take a look on it this night. Maybe because here we can detect that an "OrchardCore" shape is rendering itself, that would not be possible through Fluid.

**Comment by jtkech** [comment]
To check it, in the blog recipe try to replace the last line of `Content-Article.liquid` with

    {{ Model | shape_render }}

The shape is rendered 10 times but without crashing the application.

**Comment by jtkech** [comment]
I could have done this check in `displayHelper.ShapeExecuteAsync` so that it would also work for razor shapes, but here less simple to retrieve the calling shape, maybe through our `ViewContextAccessor`, then its RazorView then its RazorPage then its Model.

But i'm fine to only have this security for liquid

@hishamco still not sure but each time we render a liquid view a new template context is created, so fuild could retrieve the current shape / model from the `context.LocalScope` (Note: it is not aware of this), but i don't think it would be able to retrieve the calling shape.

**Comment by jtkech** [comment]
@sebastienros let me know if we can merge it or just close it if it is not an important issue and that is not worth to be solved, and / or that i didn't fix in the right way.

**Comment by jtkech** [comment]
Easy to redo if it will be requested.

**Comment by jtkech** [comment]
I added some max recursions 

Recursion
messages

**Comment by jtkech** [comment]
Okay found another way to check shape recursions

It throws an exception, not a message as in the previous solution.

**Comment by sebastienros** [comment]
My concern is with adding a public counter property to LiquidTemplateContext. Moving it in the template manager as a private field would be better,

**Comment by jtkech** [comment]
> Moving it in the template manager as a private field would be better

When we render a liquid template **coming from a file**, we don't pass through the template manager

> My concern is with adding a public counter property

If the only concern is that it is a **public** property, i will change it

**Comment by agriffard** [comment]
@jtkech Please tell us when you think it is ready to be merged.

**Pull request merged**
