### PR TITLE
Use language keywords instead of framework type names for type references (IDE0049)

### PR DESCRIPTION
**Pull request by MikeAlhayek**
@sebastienros suggested to use language keywords instead of framework type. Applying Rule [IDE0049 ](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0049)

Here is an article explaining the reason why language keywords are preferred at Microsoft https://medium.com/@trapdoorlabs/c-string-vs-string-more-than-just-style-6dd967daef14

### CODE REVIEW

**Comment by MikeAlhayek** [comment]
@jtkech thoughts on this PR? The longer this one stays open will encounter conflicts. @sebastienros maybe we can talk about this during steering meeting?

**Comment by sebastienros** [comment]
We need someone else to agree or disagree, I don't want it to be unilateral.
@Piedone what do you think?

**Comment by Piedone** [comment]
I agree with the change. We follow this at Lombiq for much the same reasons elaborated in the linked blog post too.

**Comment by sfmskywalker** [comment]
I also agree.

**Review by jtkech — APPROVED** [review]

**Pull request merged**
