### PR TITLE
Adding GitHub Actions workflow to close stale PRs (Lombiq Technologies: OCORE-154)

### PR DESCRIPTION
**Pull request by Piedone**
Part of #15029.

### CODE REVIEW

**Review by MikeAlhayek — APPROVED** [review]

**Comment by MikeAlhayek** [comment]
Hopefully a stale PR is one with 0 approval. Maybe we should exclude those with "need-triage" label as well.

**Comment by Piedone** [comment]
We can exclude those (this action is super configurable) but do we want to? A PR will be marked as stale (label and comment added) after 60 days of inactivity (even a comment, or adding a label counts as activity), and closed 15 days after that. If nobody cared about a PR for 75 days then there's not much else to talk about.

**Comment by MikeAlhayek** [comment]
Well if a PR has at least one approval, then it should not be subject to be stale. If someone marked it with need-triage, then they think it is worth looking into. So we should not mark it stale. If we do the triage correctly, then these would be reviews with in a week. At that time, either we merge or provide feedback and remove the need-triage label. If we provide feedback, and don't get a response after 60 days then sure stale and close it. But as long as it is awaiting triage, we should not stale it.

**Comment by Piedone** [comment]
The 75 days starts at the last activity, and any activity resets it (if it's after the PR is marked stale, then you also need to remove the  label).

If a PR awaiting triage wasn't touched for 60 days, then upon the stale comment being added the reviewer adding "needs triage" has the chance to do something. Bring it up at the meeting, merge from `main`, or just comment "I'll bring this up in the next few weeks, pinky promise.". Then the 60 days start anew. However, something really should happen. I don't think we can hope for a PR to be ever picked up if nobody cared about it for 2,5 months.

When going through all the PRs, I found that a PR being dropped by a reviewer (or not reviewed by anyone), or dropped by the author after a review, were soft "no"s. This isn't how we should operate, because this results in almost 200 PRs piling up, at least a quarter of which were silent quit like this. Instead, we should provide clear feedback on each PR, including if we won't take it (which sucks, but is inevitable). If nobody from the team gives this clear feedback (which also is an issue), then auto-closing it can at least prevent the PR from just sitting in limbo forever.

(A PR receiving approval that the reviewer doesn't deem requiring a second opinion should just be merged right away.)

**Review by MikeAlhayek — APPROVED** [review]
I am good with this. If we find that this is causing issue we can then modify as needed.

**Comment by hishamco** [comment]
I'm afraid that another GC collector is coming on the way :)

**Pull request merged**
