### PR TITLE
Fix typo on GitHub menus

### LINKED ISSUE #4065: Use GitHub instead of Github
Typo reported on Crowdin.

### PR DESCRIPTION
**Pull request by agriffard**
Fixes #4065

Github => GitHub

I only changed the names in the localizations, not in the namespaces and classes.

### CODE REVIEW

**Comment by hishamco** [comment]
What's avoid us to change it everywhere?

**Comment by agriffard** [comment]
My laziness.

**Comment by hishamco** [comment]
If it's fine to push some commits to your, I will do it in your behalf

**Comment by agriffard** [comment]
You sure can.

**Comment by hishamco** [comment]
@agriffard if looks good squash & merge

**Comment by PinpointTownes** [comment]
@hishamco you'll have also have to update the casing of the actual file names, otherwise build will fail on case-sensitive filesystems (which is why it failed on Travis)

**Comment by hishamco** [comment]
I already but I don't know why some aren't pushed

**Comment by hishamco** [comment]
Still fails :(

**Comment by hishamco** [comment]
I will try to test it in Ubuntu bash on my Windows, to see why it keeps failing

**Comment by hishamco** [comment]
@PinpointTownes change the file casing doesn't preserve during commit!! Any idea?

**Comment by PinpointTownes** [comment]
@hishamco that's likely because you made the changes on Windows. It's certainly possible to change the casing on case-insensitive systems, but it's a bit more complicated.

https://stackoverflow.com/questions/1793735/change-case-of-a-file-on-windows should put you on the right track 😄

**Comment by hishamco** [comment]
I see, thanks to know that Kévin

**Comment by hishamco** [comment]
Finally I fix it after setting `ignore-case: false`

**Comment by PinpointTownes** [comment]
You're welcome! You may also want to update the file names, for consistency (e.g `GithubDefaults.cs` -> `GitHubDefaults.cs`).

**Comment by hishamco** [comment]
`GitHubDefaults.cs` isn't updated?!!

**Comment by PinpointTownes** [comment]
AFAICT, the folder name was successfully updated, but not the file name:

image

(it's true for the other files, too)

**Comment by hishamco** [comment]
Strange!! how the CI/CD is passed?!!

**Pull request merged**
