### PR TITLE
Code Mirror assets

### PR DESCRIPTION
**Pull request by agriffard**
Text field with Code Mirror and Markdown field look ok:

image

image

/cc @Skrypt

### CODE REVIEW

**Comment by Skrypt** [comment]
I'm testing and here what I get : 

image

image

image

image

**Comment by agriffard** [comment]
I tested on a blog and after a cache refresh, I see this:

image

**Comment by Skrypt** [comment]
I did a `git clean -xdf` and also a browser cache refresh (except cookies). So are you telling me that this is stored in cookies or localstorage?

**Comment by Skrypt** [comment]
orchard

**Review by Skrypt — APPROVED** [review]

**Pull request merged**
