### PR TITLE
Hishamco/upgrade graph ql

### PR DESCRIPTION
**Pull request by hyzx86**

### CODE REVIEW

**Comment by MikeAlhayek** [comment]
image

**Comment by hyzx86** [comment]
@hishamco  There are too many change differences here, it is recommended to merge the latest code in your branch and then we will make adjustments on it

**Comment by hyzx86** [comment]
> image

Yes I noticed that, but this PR is for merging into a branch in August and not into the main branch

**Comment by hishamco** [comment]
Can you rebase on `main` branch

**Comment by hyzx86** [comment]
> Can you rebase on `main` branch 

Ok, I'll try it sometime. I have some work to do today

**Pull request closed without merging**
