### PR TITLE
TheAgency: Resize images with existing sizes

### PR DESCRIPTION
**Pull request by agriffard**

### CODE REVIEW

**Comment by sebastienros** [comment]
How did you choose the modes? c.f. https://docs.sixlabors.com/api/ImageSharp/SixLabors.ImageSharp.Processing.ResizeMode.html

Screenshot to ensure it looks good?
I assume also that we are not using the filters in the other themes?
Can you check the media views work fine too?

**Comment by agriffard** [comment]
I tested mulitple modes.
I only changed the mode to `min` for the images in modal popup and kept `stretch` on purpose for the other.
I haven't found other resize_url filter.

What are the media views?

**Comment by sebastienros** [comment]
In the admin, the media management. They must be using razor.

**Comment by agriffard** [comment]
ok. the small thumbnails were resized to 120 in admin. I set them 160px.

**Comment by sebastienros** [comment]
I think we forgot about the .min js files :/

**Pull request merged**
