### PR TITLE
Improved `gulp watch` command

### PR DESCRIPTION
**Pull request by jptissot**
Gulp watch had a couple issues:
- Did not build assets initially
- Did not properly reload Assets.json changes. For example,
if you modified a Group, it would not pick up the changes.

This fixes those two issues.
- watch will initially build every asset group
- A modification to Assets.json will force a rewatch of all groups
within this modified Assets.json file

I also ran vscode code formatter. 
/cc @agriffard

### CODE REVIEW

**Comment by agriffard** [comment]
When I did a `gulp watch` and updated a scss file, it also regenerated some .js files, which is a bit annoying.

**Comment by jptissot** [comment]
It should only build what is modified. Except on load, it will build first, then watch.

**Comment by jptissot** [comment]
@agriffard technically, nothing should be modified other than what you are trying to edit. If it is modified, it either means you have an outdated version of the dependencies (need to npm install) or the code on the main repo were not properly built

One thing I have noticed is that sometimes the build will change line endings without changing anything in the file, which makes it appear in your git working directory changes.

**Comment by deanmarcussen** [comment]
@jptissot and it's the line endings that are the problem.

I like the improvements to watch, but not so much building every group when watch starts.

For example if someone is doing a change to the media app, but it also rebuilds the admin.js because they're on a different os, then they're going to need to discard those changes before creating a PR, or we're all going to be confused about what's in the PR

**Comment by jptissot** [comment]
@deanmarcussen Isn't there a way to fix the line ending issue instead ? 
https://github.com/iShafayet/gulp-line-ending-corrector

What made me trigger the build on watch start is that I often forgot to start watch before starting to work on a scss file, then I would watch but my change would not show up before I re-trigger the change.

I also found another issue with the pipeline and merge conflicts. 
**Example:**
Branch A and B both modified the `Admin.css` file (via a modification to the scss files). When I merge B into A (merge commit) and choose to keep the `Admin.css` from B or A because I will build the assets to get the latest version. But when running the `gulp build` command, `Admin.css` is not rebuilt  because the build thinks the timestamps are correct.

As action items, I think we need to remove the difference between rebuild and build and always "rebuild". As for watch, I really think it should rebuild on start. Let's take CreateReactApp as an example. When you start the dev server, it will rebuild everything and then start rebuilding on changes. 

In the end, my goal is to have consistent builds. How we do that, I don't really mind but right now it's still a bit broken ;)

**Comment by deanmarcussen** [comment]
@jptissot That looks like a good plugin to sort the line ending issue.

And yes, I agree regards build and rebuild.
If the line ending issue was sorted, and we could consistently rebuild across the different o/s, without getting changed files, then build and rebuild could become one, and we could have good consistent builds :)

**Comment by jptissot** [comment]
Should I revive this PR @agriffard  ?

**Comment by jptissot** [comment]
Should we exclude built assets from git and build them in the pipeline ?

**Comment by Skrypt** [comment]
That somehow would be better for reproducible builds. This way, if the CI doesn't build these assets properly we could throw an error on the CI and this would not let the responsibility of building these assets to everyone who can have a different version of Node.js / npm installed.

**Pull request closed without merging**
