### PR TITLE
Try to fix graphql test on AppVeyor.

### PR DESCRIPTION
**Pull request by jtkech**
Seems that `ShouldListBlogPostWhenCallingAQuery` graphql test still fails intermitently.

I already fixed one issue based on what i saw when testing them concurrently, but i remember there were 1 or 2 other ones. Here, step by step, i added another check based on what i remember.

### CODE REVIEW

**Comment by Jetski5822** [comment]
Lgtm

**Comment by sebastienros** [comment]
The error message looks like the content might not be indexed already when the query is sent.
I would just suggest to change the test to something that doesn't depend on something like indexing, it's too "flaky".

I also want to prevent any change that is like "let's try to do the same thing in a loop, we don't know why, but it might solve the issue" ;)

**Comment by sebastienros** [comment]
However I understand that some API calls might fail because of networking (which is not what you are testing here) and we might need to do retries. In this case the best practice is to do what @MatthijsKrempel did in the ReCaptcha PR by injecting a named HttpClient and assigning a retry policy using Polly.

**Comment by jtkech** [comment]
Yes, it is just for testing trying to retrieve what i did when doing tests concurently.

As i remember `EnsureSuccessStatusCode()` was not throwing that's why i didn't use a retry policy, but the content was empty.

i will dig into it, the problem is that currently i can't repro any issue on my machine. Even if i do the tests concurrently as i did before when i saw these issues.

**Comment by jtkech** [comment]
Oh, just remembered what i did to repro issues more frequently, duplicate the test e.g 10 times then run them in parallel, i will redo it soon.

**Comment by sebastienros** [comment]
As I said, it might be a timing issue. We need to get rid of these flaky tests, by making them not flaky. If we can test the same scenario without using the lucene index, then let's change that. If not and it's a timing issue, we need to wait, or ensure the index is up to date before.

**Comment by jtkech** [comment]
I could repro by using more tests in //. See the image, the response is OK but the content is empty.
Note: i remember that i was checking `.Length` in place of `IsNullOrWhiteSpace`, i will update the pr.
Now i will not throw an exception and try to repro the issue we have on AppVeyor and see if related.

graphqltests

**Comment by jtkech** [comment]
@sebastienros 

Okay, you are certainly **right about the timing issue** because of lucene indexing.

But it was worth to still search because **i found an issue**. I continued to search because i had the same symptom but in another context when executing tests concurrently.

- So, in `ShellHost.InitializeAsync()` we do a double check of `_shellContexts == null` but we set it to a new dictionary just after, before we end to create and register shells.

- So, i used an `_initialized` bool. Then, i was able to run `ShouldListBlogPostWhenCallingAQuery()` 10 times concurently. This without semaphore, without extra checking, and by reusing the static constructor to create the `DefaultTenantClient` as it was done at the beginning.

**Comment by sebastienros** [comment]
Good job!

**Pull request merged**
