### PR TITLE
add line break to make the section easy to see

### PR DESCRIPTION
**Pull request by infofromca**

### CODE REVIEW

**Comment by hishamco** [comment]
Could please provide a screen shoot?

**Comment by deanmarcussen** [comment]
Can you provide a before and after screenshot please?

I am fine with the idea, but we use this style in many places, so it would be good to see the difference, so we can decide if it should be everywhere or not.

**Comment by infofromca** [comment]
no br
no_br

**Comment by infofromca** [comment]
with br
with_br

**Comment by infofromca** [comment]
no br
image

**Comment by infofromca** [comment]
with br
image

**Comment by deanmarcussen** [comment]
Thanks for the screenshots @infofromca 

What does everyone else think?

I am all good with it, but if we did it here, we would have to do it everywhere we use the alert

i.e. on Site Settings, and the other places that have an alert notification in the top of the view

This one is common throughout, and also placed in the same location
`<p class="alert alert-warning">@T["The current tenant will be reloaded when the settings are saved."]</p>`

**Comment by ns8482e** [comment]
No <hr /> please.

**Comment by agriffard** [comment]
Closing it. Many people don't seem to agree on this addition, including me.

**Pull request closed without merging**
