### PR TITLE
Docs Dark mode

### PR DESCRIPTION
**Pull request by agriffard**
https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/?h=slate#system-preference

### CODE REVIEW

**Comment by hishamco** [comment]
Is there a preview link to see the dark mode on action?

**Comment by agriffard** [comment]
https://docs.orchardcore.net/en/ag-docsdark/

**Comment by hishamco** [comment]
Looks good but the dark blue links make it hard to read

**Comment by MichaelPetrinolis** [comment]
maybe instead of blue use the colors in the new branding ?

**Comment by MichaelPetrinolis** [comment]
it's nice, maybe we should change the link hover color ?

**Comment by hishamco** [comment]
Link hover still blue

**Comment by hishamco** [comment]
The icon too ;)

**Comment by agriffard** [comment]
image

**Comment by hishamco** [comment]
Looks much better now, but still there's an issue on link hover

**Comment by agriffard** [comment]
accent: green => hover links in green

**Review by hishamco — APPROVED** [review]
LGTM

**Comment by MichaelPetrinolis** [comment]
it's much better but for an inclusive design the hovered links should not differ only by color. 
Nevertheless it looks good!

**Pull request merged**
