### PR TITLE
Fix executeQuery function

### LINKED ISSUE #10648: executeQuery  function in workflow returns the dictionary incorrectly
This is my query:
image

and this is my code :
``` Javascript
var orderList = property("zsdgData");
log("Error","过滤前的数据总数："+ orderList.length)
var orderIds= orderList.map(x=>"'"+x['Delivery_Number']+'-'+x['Delivery_Item']+"'");

var queryParams= { ids: orderIds.join(',')};
log("Error","queryParams："+ JSON.stringify(queryParams))
//查询数据库中已存在的项 
var result = executeQuery("SCMQueryExistsedOrderIds",queryParams) //output:{"Count":36,"Capacity":64}

log("Error","qurey result："+ JSON.stringify(result))
var filterdData=orderList;
//排除数据库中已存在的条目
if(result!=null){
  	log("Error","qurey result is not null"+JSON.stringify(result)) // 
	var idResult= result.map(x=>x.DisplayText )
    filterdData=orderList.filter(x=> idResult.indexOf(x['Delivery_Number']+'-'+x['Delivery_Item'])==-1)
}

log("Error","过滤后的数据总数："+ filterdData.length)

setProperty("zsdgData",filterdData)
setOutcome('Done');
```
 

log out put:
```
input counts ：12 
queryParams：{"ids":"'145163194-10','145163285-10','145163288-10','145163304-10','145163307-10','145163315-10','145163318-10','145163323-10','145163325-10','145163327-10','145163329-10','145163331-10'"} 
result ：{"Count":36,"Capacity":64} 
result is not null :{"Count":36,"Capacity":64} 
An unhandled error occurred while executing an activity. Workflow ID: '143'. Activity: '4495mt0yfpjm2vn0pc32yd5ex1', 'ScriptTask'. Putting the workflow in the faulted state. Jint.Runtime.JavaScriptException: Property 'map' of object is not a function
   at :15:2    at :15:2
```

### PR DESCRIPTION
**Pull request by hyzx86**
Fixes #10648

### CODE REVIEW

**Comment by hyzx86** [comment]
@Skrypt 
Can we merge this PR into the main branch? It seems that this problem of Jint will not be dealt with in a short time

**Comment by Skrypt** [comment]
We can't really merge this change as it is a breaking change. It will need to be discussed. At the same time, @sebastienros was working on a fix inside Jint.

**Comment by hyzx86** [comment]
@Skrypt You are right , so  I've move the patch  position.  This should avoid as much impact as possible.

**Comment by hyzx86** [comment]
oh， don't merge , there is have some problem ..

```
Jint.Runtime.JavaScriptException: Cyclic reference detected.
   at stringify :9:1
   at :9:21    at stringify :9:1
   at :9:21
```

**Pull request closed without merging**
