### PR TITLE
Improve the scrolling in BagPart Sorting

### PR DESCRIPTION
**Pull request by MikeAlhayek**
When BagPart has lots of items, dragging/dropping while scrolling is too slow. In the process I also updated the ScrollableJs version from 1.5.0 to 1.5.3.

### Before Behavior
As you can see in the following screen cast, scrolling is super slow:

slower-scroll

### After Behavior
As you can see in the following screen case, scrolling is much faster now:

faster-scroll

### CODE REVIEW

**Comment by Piedone** [comment]
Can you please attach an export of the item in the gif, so I can test this with it?

**Comment by MikeAlhayek** [comment]
@Piedone 
[test.zip](https://github.com/user-attachments/files/17383716/test.zip)

**Comment by Piedone** [comment]
Don't you also experience this periodic getting stuck under Chrome?

https://github.com/user-attachments/assets/dca5e02f-c849-4108-a1c9-bec74fcd8c7a

**Comment by MikeAlhayek** [comment]
Yes. I think this is just how the script work which is strange. I wish it was a smoother scrolling. Maybe we can file an issue with the script owner to see if this is something they can improve.

**Pull request merged**
