### PR TITLE
do not need to get ContentTypeDefinition from DB again

### PR DESCRIPTION
**Pull request by infofromca**

### CODE REVIEW

**Comment by MikeAlhayek** [comment]
What problem does this PR solves? Changing interface is a breaking change. The document store cache the document so calling `GetContentType` should not cause another round trip to the server.

**Comment by infofromca** [comment]
before the cache , there is another hit to the db server

**Comment by Piedone** [comment]
Is this something you'd like to revisit any time soon @infofromca or should we close?

**Comment by Piedone** [comment]
Closing due to inactivity.

**Pull request closed without merging**
