### PR TITLE
Add select all checkbox on tenants page

### LINKED ISSUE #4306: Tenants: Select all
A 'Select all' check box would be useful in the tenants page.

/cc @hishamco

### PR DESCRIPTION
**Pull request by hishamco**
Fix #4306

### CODE REVIEW

**Comment by hishamco** [comment]
@agriffard this is almost done, the function part is 100% done, the remaining is polish the design, hopefully, I will finalize this ASAP

**Comment by agriffard** [comment]
You did it on the Features page.
Can you do please it on the Tenants page also?

**Comment by hishamco** [comment]
Thanks seems I do it on a wrong page

**Comment by hishamco** [comment]
With small buttons
Tenants-Small

With big buttons
Tenants-Big

@sebastienros @Skrypt  which one is make sense from user point of you

**Comment by sebastienros** [comment]
The small ones seem more consistent with the rest of the page. My opinion only. I don't know if there are other implications (accessibility for instance).

But please keep these tweaks for after rc, I really need to focus on what matters for rc.

**Comment by Skrypt** [comment]
See here I would have kept the big buttons but making them small is a compromise because the select all checkbox component is ugly when he's too tall. So, like I said previously in an other PR, we need to include this select all button on the list like it's done on Github and keep the button as normal size. Though, that's my opinion. For the sake of having the feature in the PR looks fine.

**Comment by agriffard** [comment]
Closing it as the new tenant UI as been implemented.

**Pull request closed without merging**
