### PR TITLE
fix: Update SimpleMDE repo link

### PR DESCRIPTION
**Pull request by nschonni**
Current repo link is just a defaced git repo

### CODE REVIEW

**Comment by Skrypt** [comment]
LGTM

**Comment by sebastienros** [comment]
I have no idea how you found this. Good catch!

**Comment by nschonni** [comment]
@Skrypt nope not for anything public facing, just some internal docs stuff

> I have no idea how you found this. Good catch!

:laughing: was reading through the docs about Markdown support, an found some issues about the old repo being dead/defaced

**Comment by Skrypt** [comment]
Good enough 😄

**Pull request merged**
