### PR TITLE
Merging release/1.7 into main

### PR DESCRIPTION
**Pull request by MikeAlhayek**

### CODE REVIEW

**Comment by hishamco** [comment]
How is this related to #14474?

**Comment by sebastienros** [comment]
I don't know if we should do this from GH, I will try to merge it and do manual things if necessary.

**Comment by MikeAlhayek** [comment]
Sounds good. If you end up no using this Branch, you can close it.

**Comment by sebastienros** [comment]
That doesn't work as expected. Closing it and doing it manually

**Comment by sebastienros** [comment]
> If you end up no using this Branch, you can close it.

It's release/1.7, so no I won't close it ;)

**Comment by sebastienros** [comment]
main is now up to date. We need a new PR that contains the version updates, and "this one" should be called Release 1.7.1, not the other ones that were called "Release 1.7.1" which actually contained bug fixes.

**Comment by MikeAlhayek** [comment]
> main is now up to date. We need a new PR that contains the version updates, and "this one" should be called Release 1.7.1, not the other ones that were called "Release 1.7.1" which actually contained bug fixes.

@sebastienros I am not following you. Why do we need another PR?

When we released v1.7.0, we created a branch called `release/1.7` based on main. Then we released v1.7.0. Now we are trying to ship v1.7.1 so we cherry picked few PR from main and added them to `release/1.7`. So now `release/1.7` should have what is needed to be ship into v1.7.1.

Now you merged `release/1.7` back into main. So I think all we need to do is ship 1.7.1 based on `release/1.7` which contains only the patches.

**Comment by sebastienros** [comment]
We need to change release/1.7 content with a release notes, update the 1.7.0 versions to 1.7.1. 

> So now release/1.7 should have what is needed to be ship into v1.7.1.

The fixes, yes, not the docs, versions and release notes

What we did in this PR: https://github.com/OrchardCMS/OrchardCore/pull/14111

**Comment by sebastienros** [comment]
Then we create the tag v1.7.1 from this release/1.7 branch

**Comment by MikeAlhayek** [comment]
We are on the same page now! We'll get a PR going soon

**Pull request closed without merging**
