### PR TITLE
Add babel to package.json and gulp js pipeline

### LINKED ISSUE #4427: A Js issue
https://github.com/OrchardCMS/OrchardCore/blob/55d1e89a1b9d60815ece4a38130e834e0a2fdb43/src/OrchardCore.Themes/TheAdmin/Assets/js/admin.js#L1

IE does not support this syntax。

### PR DESCRIPTION
**Pull request by agriffard**
Fix #4427

Then, `gulp rebuild` detect this kind of error:
```
 SyntaxError in plugin "gulp-babel"
Message:
    D:\Orchard\OrchardCore\src\OrchardCore.Modules\OrchardCore.Workflows\Assets\Scripts\workflow-canvas.ts: Unexpected token, expected ";" (5:9)

  3 | ///<reference path='./workflow-models.ts' />
  4 |
> 5 | abstract class WorkflowCanvas {
    |          ^
```

/cc @deanmarcussen @sfmskywalker Can you please give it a look?

### CODE REVIEW

**Comment by deanmarcussen** [comment]
Nice one @agriffard 

We might just have to try running it after the typescript compilation, (and excluding any *.ts files)

I can have a look later this afternoon.

You mind if I push something to this branch, if I can figure it out?

**Comment by deanmarcussen** [comment]
Working now Antoine, it just needed to be run after the typescript compilation.

so w/ gulp-babel this javascript 
```
var l = () => {
    return 'l';
}
```

compiles to
```
var l = function l() {
  return 'l';
};
```

the offending confirm dialogue was
```
function confirmDialog({ title, message, okText, cancelText, okCssClass, cancelCssClass, callback }) {
...
}
```

and compiles to 
```
function confirmDialog(_ref) {
  var title = _ref.title,
      message = _ref.message,
      okText = _ref.okText,
      cancelText = _ref.cancelText,
      okCssClass = _ref.okCssClass,
      cancelCssClass = _ref.cancelCssClass,
      callback = _ref.callback;
```

so in theory that should all work with ie (if in a compiled script, not in inline razor!)

@jrestall is clearly ahead of us all as the GraphQL webpack was already using babel, so I've updated the versions to match.

@agriffard I can't get a working install of npm on my machine due to this problem https://github.com/OrchardCMS/OrchardCore/issues/4338
so can you pull and rebuild again against yours? 

Other than making the graphql babel packages match I didn't install anything else.

Also had to remove strict type checking from the transpilation, due to all the different types of ways popper and other plugins are bundled. 

/cc @Skrypt @jptissot

**Comment by jptissot** [comment]
Looks good. I will try it with yarn to see if I get a different output.

**Comment by agriffard** [comment]
Ok, rebuilt. Thank you for the changes.

**Comment by jptissot** [comment]
I installed  using yarn and rebuilt. Nearly all minified files changed.

**Comment by jptissot** [comment]
I tried a npm install from, then gulp rebuild. package-lock.json changed and got build errors 

``` 
[14:50:10] 'rebuild' errored after 341 ms                                                        
[14:50:10] Error: File not found with singular glob: C:/Users/jeanp/repos/OrchardCore/node_module
s/bootstrap-slider/dist/css/bootstrap-slider.css (if this was purposeful, use `allowEmpty` option
)                                                                                                
    at Glob.<anonymous> (C:\Users\jeanp\repos\OrchardCore\node_modules\glob-stream\readable.js:84
:17)                                                                                             
    at Object.onceWrapper (events.js:299:26)                                                     
    at Glob.emit (events.js:209:13)                                                              
    at Glob.EventEmitter.emit (domain.js:476:20)                                                 
    at Glob._finish (C:\Users\jeanp\repos\OrchardCore\node_modules\glob\glob.js:197:8)           
    at done (C:\Users\jeanp\repos\OrchardCore\node_modules\glob\glob.js:182:14)                  
    at Glob._processSimple2 (C:\Users\jeanp\repos\OrchardCore\node_modules\glob\glob.js:688:12)  
    at C:\Users\jeanp\repos\OrchardCore\node_modules\glob\glob.js:676:10                         
    at Glob._stat2 (C:\Users\jeanp\repos\OrchardCore\node_modules\glob\glob.js:772:12)           
    at lstatcb_ (C:\Users\jeanp\repos\OrchardCore\node_modules\glob\glob.js:764:12)              
npm ERR! code ELIFECYCLE                                                                         
npm ERR! errno 1                                                                                 
npm ERR! @ rebuild: `gulp rebuild`                                                               
npm ERR! Exit status 1                                                                           
npm ERR!                                                                                         
npm ERR! Failed at the @ rebuild script.                                                         
npm ERR! This is probably not a problem with npm. There is likely additional logging output above
.                                                                                                
                                                                                                 
npm ERR! A complete log of this run can be found in:                                             
npm ERR!     C:\Users\jeanp\AppData\Roaming\npm-cache\_logs\2019-10-06T18_50_10_420Z-debug.log   
```

**Comment by jptissot** [comment]
@agriffard can you try to delete all node_modules in the solution, npm install and gulp rebuild and see if you get the same error ?

We should not get different results on different machines this will cause issues.

**Comment by agriffard** [comment]
I also have this problem. 
Since we moved some dependencies in other sub modules (Resources, Graphql, Workflows, ...), some packages (like bootstrap-slider) are installed in the node_modules of these subfolders on my machine, while the assets are referencing the packages as if they were located in the root node_modules folder.
So I have to copy manually the missing packages in order to make the gulp rebuild work.

@sebastienros told me the packages were supposed to be all installed in the root so I thought it was a problem on my machine.

**Comment by deanmarcussen** [comment]
@jptissot @agriffard It's not this particular branch that has problems, but dev itself.

Same one you reported https://github.com/OrchardCMS/OrchardCore/issues/4338

Currently if I do an npm install of dev, most of the assets from `OrchardCore.Resources` like bootstrap-slider etc don't install

**Comment by jptissot** [comment]
Yarn worked tho :p just produced different minified files.

I'll try to improve it after 1.0.

**Comment by sebastienros** [comment]
Status on this one? Are we waiting for more, do you all agree with the changes? Is there still an issue to fix?

**Comment by jptissot** [comment]
I think this is fine. Just underlying issues we will tackle after 1.0

**Pull request merged**
