### PR TITLE
Fix prop-* type in BaseShapeTagHelper

### LINKED ISSUE #5090: Setting prop-* for shape tag helper throws an error
While experimenting with shape tag helper for #4955, I am trying to set kind property to have value "form", when I used prop-* as below, 

`<shape Type="SubLayout" prop-kind="form"> `

throws an error, Am I using it incorrectly?

```
The name 'form' does not exist in the current context
+ <shape type="SubLayout" prop-kind="form" >

```

### PR DESCRIPTION
**Pull request by hishamco**
Fixes #5090

### CODE REVIEW

**Comment by hishamco** [comment]
@agriffard this is a straightforward fix, hope you merge ASAP

**Comment by sebastienros** [comment]
Please don't merge, I'll explain later

**Comment by giannik** [comment]
explanation here :
https://www.youtube.com/watch?v=G5qPmYmLaGY&t=1392s

**Comment by hishamco** [comment]
> Please don't merge, I'll explain later

I label the PR with `dontmerge`, waiting for your explanation

**Comment by jtkech** [comment]
Hmm, this let me think that in Liquid i think we don't support yet `DictionaryAttributePrefix`.

For infos here `_properties` was never used, in one of my PR i just removed it.

**Comment by hishamco** [comment]
> Hmm, this let me think that in Liquid i think we don't support yet DictionaryAttributePrefix.

I see, I don't know about this one

**Comment by sebastienros** [comment]
If _properties is not used, and removing it doesn't break `prop-foo` then remove it.
If you think you change is fixing something, I'd like to know what you have tested and how it fixed the issue.

**Comment by jtkech** [comment]
Yes, i tested it `_properties` is useless

And i have to look if `DictionaryAttributePrefix` is implemented in Liquid

**Comment by hishamco** [comment]
> Yes, i tested it _properties is useless

It's useless before the PR

> If you think you change is fixing something, I'd like to know what you have tested and how it fixed the issue.

I'm just asking why the dictionary accepts `Object` before? I think the pattern similar to what ASP.NET Core has 'asp-route-*`

**Comment by ns8482e** [comment]
> i think we don't support yet `DictionaryAttributePrefix`.

@jtkech  for info, I managed to add support for it while working on #4955 (still WIP), so that I could write `asp-route-returnUrl` in admin liquid template.

**Comment by jtkech** [comment]
@ns8482e cool 👍 you will have to share the code ;)

**Comment by ns8482e** [comment]
> you will have to share the code ;)

Sure! Let me create separate PR for that so that it can be independently merged and don't have to wait for #4955

**Pull request closed without merging**
