### PR TITLE
Add custom Widget styles and classes with Flow

### PR DESCRIPTION
**Pull request by j42house**
#2742 Provide Classes and Styles fields in the FlowMetadata on a Widget for users to add custom classes and styles to the widget container.
widget-classes-styles

### CODE REVIEW

**Comment by agriffard** [comment]
I'd love to have this feature merged in dev.

**Comment by sebastienros** [comment]
What about just limiting it to classes to prevent from have to handle attributes this way. This might get more complex in liquid templates. And might also force to make cleaner changes.

**Comment by douwinga** [comment]
If it is just limited to classes, it would be nice if there was a way to add classes in the admin. Something like a global stylesheet that is stored in the database.

**Comment by sebastienros** [comment]
@douwinga I was thinking about that, by using settings on the part definition (widget or flow?). And then we could use the vue multi-select editor to display them, but also accept custom entries (optionally)

**Comment by sebastienros** [comment]
I assume right now we could just store it as a `string[]` and later improve the editor. Small steps ...

**Comment by jrestall** [comment]
This approach assumes FlowPart is generating HTML. But I use Orchard as a Headless CMS for native mobile apps and websites, so returning structured data with no bias towards how it might be rendered is important. There's no css when rendering native mobile widgets for example.

**Comment by arkadiuszwojcik** [comment]
@jrestall First of all those settings are saved as metadata so there might be plenty of rendering engines configuration as you wish so there is no bias. It would be bias if such config would land in Model settings. Second, HTML/CSS will be the case in > 90% of cases so justification for extra tools towars HTML/CSS is valid. What I would do is to create HTML/CSS section in Widget configuration bar and put all extra stuff there and all of them would be store in metadata section "html" or something like that.

**Comment by sebastienros** [comment]
@jrestall  If this is optional in the type part settings then that's fine. Also if in these settings we can limit the list of values that can be used. And then the toolbar can decide to render the dropdown or not.

**Comment by arkadiuszwojcik** [comment]
@sebastienros taking into consideration @jrestall comment if someone will start implementing this according to above discusion should name Classes be used in implemenation (which imply CSS connotation) or Attributes as more generic term that will be tanslated to CSS classes during HTML rendering?

**Comment by agriffard** [comment]
Do we close this, now that there have been other changes on the Widgets and Flow editor?

**Pull request closed without merging**
