### PR TITLE
Fix Publish Content Task

### PR DESCRIPTION
**Pull request by AmyBlaine**
Fixes https://github.com/OrchardCMS/OrchardCore/issues/16939

Updated the condition in the Publish Content Task. The condition for the Noop behavior is related to the properties of the content item, not the workflow. The workflow should publish content when the workflow is scheduled, restarted or triggered by a user event. To publish a content item, it must have a draft

Updated the default properties for a content item when it is created. When a content item is created, it is the latest version of the content item by default.

### CODE REVIEW

**Comment by AmyBlaine** [comment]
Results of manual testing are documented here - https://github.com/OrchardCMS/OrchardCore/issues/16939#issuecomment-2455457498

I will work on submitting a functional test as I have time.

**Comment by MikeAlhayek** [comment]
@AmyBlaine please accept the Contributor License Agreement

**Comment by AmyBlaine** [comment]
> @AmyBlaine please accept the Contributor License Agreement

I'm waiting on permission from my employer

**Review by sebastienros — APPROVED** [review]

**Comment by MikeAlhayek** [comment]
@AmyBlaine i hope this will be ready soon as we are getting ready to release 2.1.

This is a personal contribution and not company, maybe you don't need to use your company's name here and just use your own name instead.

**Comment by sebastienros** [comment]
If that's blocking then we should create a different PR. There is not much IP in here, including the fact we came up with the solution during a joint meeting.

**Comment by AmyBlaine** [comment]
@coderabbitai review

**Comment by AmyBlaine** [comment]
> @AmyBlaine i hope this will be ready soon as we are getting ready to release 2.1.
> 
> This is a personal contribution and not company, maybe you don't need to use your company's name here and just use your own name instead.

> If that's blocking then we should create a different PR. There is not much IP in here, including the fact we came up with the solution during a joint meeting.

That's fine with me.  

I escalated this to my manager because I did this work on company time with company resources in the course of my work for my employer. There are active conversations but the resolution may not occur within your desired timeframe.

**Comment by MikeAlhayek** [comment]
This PR was replaced by #17033

**Pull request closed without merging**
