### PR TITLE
Remove npm assets from dependabot

### LINKED ISSUE #15694: Have a better way to auto-update dependencies
### Is your feature request related to a problem? Please describe.
Dependabot is currently enabled and it updates some dependencies automatically. However, this is not ideal, see [from here](https://github.com/OrchardCMS/OrchardCore/pull/15641#issuecomment-2043231255).

### Describe the solution you'd like
Perhaps we should disable Dependabot, or use [Renovate](https://github.com/renovatebot/renovate).

See this issue with some ideas: https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/issues/703

### Describe alternatives you've considered
Just disabling Dependabot.

### PR DESCRIPTION
**Pull request by sebastienros**
Based on the following query we close all the PRs it's creating for npm: https://github.com/OrchardCMS/OrchardCore/pulls?q=is%3Apr+author%3Aapp%2Fdependabot+is%3Aclosed

I think it could work out but we should add some functional test of the groups it's updating. And maybe group the dependencies for each feature we test. e.g., graphiql

Fixes #15694.

### CODE REVIEW

**Comment by Piedone** [comment]
Is this fixing https://github.com/OrchardCMS/OrchardCore/issues/15694?

**Comment by sebastienros** [comment]
It fixes the issue I think, as this is a suggested solution in the description.

**Comment by Piedone** [comment]
OK then!

**Review by Piedone — APPROVED** [review]

**Comment by Piedone** [comment]
And opened https://github.com/OrchardCMS/OrchardCore/issues/16318 to re-add this later.

**Comment by Piedone** [comment]
For some reason, we got still this: https://github.com/OrchardCMS/OrchardCore/pull/16343

**Pull request merged**
