### PR TITLE
Liquid TryIt Editor module

### PR DESCRIPTION
**Pull request by DotCat1985**
Related to the discussion [#16338](https://github.com/OrchardCMS/OrchardCore/discussions/16338).

### CODE REVIEW

**Comment by Piedone** [comment]
While at a first glance this looks cool, I think it would be better suited as a community module, i.e. you can publish it under your own name.

We should discuss it during the triage meeting whether we'd like to have such a module in the source, before going any further.

**Comment by DotCat1985** [comment]
> While at a first glance this looks cool, I think it would be better suited as a community module, i.e. you can publish it under your own name.
> 
> We should discuss it during the triage meeting whether we'd like to have such a module in the source, before going any further.

Alright. I've just shared my module source code on [this public repository](https://github.com/DotCat1985/OrchardCore-Extensions/tree/main).

**Comment by sebastienros** [comment]
Let's not do it so we don't have to maintain it while there are online alternatives which are much better: https://github.com/OrchardCMS/OrchardCore/discussions/16338#discussioncomment-10023969

**Comment by hishamco** [comment]
@DotCat1985 are you interested to add this into OCC https://github.com/OrchardCMS/OrchardCore/discussions/16338#discussioncomment-9803114

**Pull request closed without merging**
