### PR TITLE
Fix toggle password style in site login

### LINKED ISSUE #7408: Login page with Blog Theme
If you check 'Use site theme for login page' in the settings of a site using theBlogTheme, the login page looks like this:

image

The button to show the password is not looking good.

### PR DESCRIPTION
**Pull request by hishamco**
Fixes #7408

Login

### CODE REVIEW

**Comment by hishamco** [comment]
I just inline the style to ensure that will work across all site themes

**Review by deanmarcussen — COMMENTED** [review]
Anything like this should be at theme level, rather than in the view.

Unfortunately here you are adding a style which is theme dependant, and while it may provide a fix for the samples themes, does not fit well with the concept of theming in general

**Comment by Skrypt** [comment]
I will take a look.

**Comment by hishamco** [comment]
> Anything like this should be at theme level, rather than in the view.

That means we should add it in all the site themes

**Comment by agriffard** [comment]
Add it to bootstrap-oc.scss may be.

**Comment by hishamco** [comment]
Seems `bootstrap-oc.scss` available in all the themes

Thanks

**Comment by hishamco** [comment]
@agriffard it works!! so it's one from my side and ready to merge

**Pull request merged**
