### PR TITLE
Replace NullLogger with FakeLogger

### PR DESCRIPTION
**Pull request by hishamco**

### CODE REVIEW

**Review by Piedone — CHANGES_REQUESTED** [review]
`FakeLogger` collects the log messages so you can later retrieve them, in a test. `NullLogger` does nothing, nor the mocked loggers. In all of the changed instances, we don't need logging, so `NullLogger` or a mock was appropriate, while `FakeLogger` is unnecessary and potentially an impact on performance too.

So, I don't agree with any of the changes here. However, you can check whether `NullLogger` would be better instead of mock, especially `NullLogger<T>.Instance`, since it might be cheaper to construct and use then a mock.

**Comment by hishamco** [comment]
> FakeLogger collects the log messages so you can later retrieve them, in a test.

I knew that collecting logs was handy especially in testing, maybe you will notice there's no much value on this PR, but I'm sure `FakeLogger` is much better than `NullLogger` because it give us the ability to collect the logs, that's why ASP.NET Core bring it in the latest version

> while FakeLogger is unnecessary and potentially an impact on performance too

This is true if we use it in the code-base, but I used for testing ONLY

**Comment by Piedone** [comment]
But we don't do anything with the logs. If we were, then `FakeLogger` would be useful. However, for the instances you changed, no logging is required, the mocks and `NullLogger` were only injected to not have the code break due to null references. So, using `FakeLogger` causes unnecessary overhead but brings no value.

I understand this is only about testing, but test execution performance matters too.

**Comment by hishamco** [comment]
I will close this for now, but once when need the logs records on the testing `FakeLogger` is our choice :)

**Comment by Piedone** [comment]
Then absolutely, just these are not such cases.

**Pull request closed without merging**
