### PR TITLE
Update StackExchange.Redis 2.6.116

### PR DESCRIPTION
**Pull request by hishamco**
https://github.com/StackExchange/StackExchange.Redis/releases/tag/2.6.116

https://www.nuget.org/packages/StackExchange.Redis/2.6.116

### CODE REVIEW

**Review by agriffard — APPROVED** [review]
Can you please add some links to the Nuget package version and GitHub release in your description when you update packages? ty.

**Comment by jtkech** [comment]
Can you describe the changes we could benefit from this correctif.

**Comment by hishamco** [comment]
I will check if there's a required change but I remembered it's a patch release

**Comment by agriffard** [comment]
I let you merge @jtkech or keep the status quo, as you are more aware of the Redis feature.

**Comment by hishamco** [comment]
@jtkech can we merge this while nothing special here :)

**Pull request merged**
