### PR TITLE
Make OrchardCore.Cms.Web the startup project by default (Lombiq Technologies: OCORE-36)

### PR DESCRIPTION
**Pull request by Piedone**
...by moving OrchardCore.Cms.Web to the top of the sln.

### CODE REVIEW

**Comment by hishamco** [comment]
I thought when you save a project as Startup, it will be forever, furthermore there's a new feature in VS whenever you select a project it will be a default one

**Comment by Piedone** [comment]
The startup project is stored in the .vs folder. If you clean the clone, or re-clone it (or somebody else clones the repo for the first time) then it needs to be set again.

**Comment by hishamco** [comment]
But .vs is per machine if I am not wrong, anyhow the change LGTM

**Comment by Piedone** [comment]
There might be one but there is also one in the solution folder. But just check it out, run `git clean -fxd` on your clone and you'll see that the startup project is back to OrchardCore.DisplayManagement (the topmost project) :).

Thanks for checking!

**Pull request merged**
