### PR TITLE
Remove SetBaseUrl() in the background

### PR DESCRIPTION
**Pull request by jtkech**
While working on #14105 I saw other tweaks to do that are not directly related.

@Piedone we added this at some point

But for me the `BaseUrl` setting is an info about the public url, it is used for `Sitemaps` and while editing an `Autoroute`, in the background we can retrieve it from the site settings but not sure it is a good idea to use it to mutate the `HttpContext`.

in #14105 I am trying a better way to init the `HttpContext` by using the server feature addresses on which it is listening, e.g. in case of a virtual folder, I will comment it more.

Yes because it is important to have the right data when we build a shell container in the background (there is an option) and also a shell pipeline as we plan to do (with a new option). For example in case of a virtual folder, the media file store is not correctly configured if done in the background.

I first thought that using `SetBaseUrl()` could be a problem but it happens after the shell container and possibly the shell pipeline have been built, so for now that's okay but as mentioned not sure it's good.

So here we remove the usage of `SetBaseUrl()` in the background to not mutate the `HttpContext`.

@Piedone let me know if you still need this for some reasons I'm not aware.

### CODE REVIEW

**Comment by Piedone** [comment]
Hmm, I can't really recall me doing anything related to this. But having a dummy HTTP request in a background task is useful; I believe the code this PR removes makes that possible. What we do in background tasks is generating URLs to the app (like sending out notifications that you can open). https://github.com/OrchardCMS/OrchardCore/issues/14086 seems to cover this use case, right?

**Comment by jtkech** [comment]
Okay I understand, to provide public urls, but that's the same even if not in the background, the HttpContext of a given running instance may not hold the same data as in the BaseUrl, for example if behind a proxy / load balencer.

In both case, to provide public urls you may need to use the `BaseUrl` to retrieve for example a public host, but not to mutate the current HttpContext even if it was created in the background.

Yes, we were already able to generate simple urls but not those based on route values, for this we need the shell pipeline (not only the container) to be built (which calls all module startup Configure()) and then execute it (in a light way). This is the goal of #14105 where it is done but only if a background task has the related setting to true.

**Comment by Piedone** [comment]
Behind a proxy the HTTP host is forwarded (see [here](https://github.com/Lombiq/Helpful-Libraries/blob/66138db31d1b9fe05c90abcf7d2410c77f307099/Lombiq.HelpfulLibraries.AspNetCore/Extensions/ForwardedHeadersApplicationBuilderExtensions.cs#L25) or the Reverse Proxy module, of course), so generating URLs with `UrlHelper` or checking the URL from the `HttpContext` is no different than without a proxy.

I think in the broader sense, the idea with this dummy `HttpContext` was that any code will run in a background task, without it knowing anything about background tasks, because everything works there the same as in the context of a request. Without a base URL, is the HTTP context any good, actually?

**Comment by jtkech** [comment]
Hmm yes in the background you more often need to generate full uris, while in a real http request we more often need to generate absolute / relative url paths.

So if it helps you to generate full uris by directly using helpers that use HttpContext data, but normally using the BaseUrl on which we append an absolute url path would do the same.

**Comment by jtkech** [comment]
> Behind a proxy the HTTP host is forwarded

You're right, I was too much thinking about `IServerAddressesFeature` which then not provide the same data. Hmm, finally maybe this is the `BaseUrl` which is better ;) The problem is that to get it we need the shell to be built, so when we build the shell in the background we can't use this `BaseUrl`.

Also the `BaseUrl` is not always defined.

Currently we use `ShellSettings.RequestUrlHost` and `RequestUrlPrefix` and in the case of under a virtual folder I saw that we could use `IServerAddressesFeature` whose addresses include it in their base path.

Currently if under a virtual folder and use the `ShellWarmup` option, the media file store is not correctly configured, that's why I am trying to use `IServerAddressesFeature`.

**Comment by jtkech** [comment]
@Piedone 

Okay I'm closing this one, thanks for the discussion.

I was too focused on how to build correctly the shell pipeline where in fact we don't need the `BaseUrl` but only the right `Path` and `PathBase` that may include a virtual folder.

But yes using the `BaseUrl` before executing a background task is still helpful to generate public urls.

**Comment by Piedone** [comment]
As always, thank you for elaborating to such detail!

**Pull request closed without merging**
