### PR TITLE
Fix Facebook widgets recipe migration (Lombiq Technologies: OCORE-188)

### LINKED ISSUE #16346: Database breaks when multiple features are enabled in a single recipe
### Describe the bug

Recipe with certain features will crash the database both in SQLite and MS SQL. Happens both with setup and recipe execution. It's not clear yet if the problem is caused by a single recipe's migrations or if enabling multiple recipes in the same step causes a race condition. I will investigate further, but any suggestions are welcome.

### Orchard Core version

The current latest preview at the time of writing this (2.0.0-preview-18246), also [the current `main`](https://github.com/OrchardCMS/OrchardCore/tree/22fbbb491068316a71b2feff7014dd828a73a654) as-is.

### To Reproduce

0. Clone the latest `main`.
1. Set up a new site (any recipe, but make sure deployments feature is enabled)
2. Go to Admin > Configuration > Import/Export > JSON Import.
3. Paste the JSON below and submit.
4. Import succeeds.
5. Reload the page or navigate to anywhere on the site.
6. Observe that every page load turns into the error on the screenshot. Restarting the server does not fix the issue.

Recipe JSON to import (these are the features step of the setup recipe of the UI test where I first encountered the problem. I will update this if I can simplify the reproducing recipe):
```json
{
  "steps": [
    {
      "name": "Feature",
      "enable": [
        "OrchardCore.ContentFields",
        "OrchardCore.ContentFields.Indexing.SQL",
        "OrchardCore.ContentFields.Indexing.SQL.UserPicker",
        "OrchardCore.ContentLocalization",
        "OrchardCore.ContentLocalization.ContentCulturePicker",
        "OrchardCore.ContentLocalization.Sitemaps",
        "OrchardCore.ContentPreview",
        "OrchardCore.ContentTypes",
        "OrchardCore.Contents",
        "OrchardCore.Contents.Deployment.AddToDeploymentPlan",
        "OrchardCore.Contents.Deployment.Download",
        "OrchardCore.Contents.Deployment.ExportContentToDeploymentTarget",
        "OrchardCore.Cors",
        "OrchardCore.CustomSettings",
        "OrchardCore.Deployment.Remote",
        "OrchardCore.Email",
        "OrchardCore.Facebook",
        "OrchardCore.Facebook.Widgets",
        "OrchardCore.Feeds",
        "OrchardCore.Flows",
        "OrchardCore.Forms",
        "OrchardCore.Google.Analytics",
        "OrchardCore.Google.TagManager",
        "OrchardCore.HealthChecks",
        "OrchardCore.Html",
        "OrchardCore.Https",
        "OrchardCore.Indexing",
        "OrchardCore.Layers",
        "OrchardCore.Liquid",
        "OrchardCore.Lists",
        "OrchardCore.Localization.ContentLanguageHeader",
        "OrchardCore.Markdown",
        "OrchardCore.Media",
        "OrchardCore.Media.Cache",
        "OrchardCore.Menu",
        "OrchardCore.OpenId",
        "OrchardCore.OpenId.Client",
        "OrchardCore.OpenId.Management",
        "OrchardCore.OpenId.Server",
        "OrchardCore.OpenId.Validation"
      ]
    }
  ]
}
```

Note: Also tested this with SQL Server on our own repo

### Expected behavior

Site should not break.

### Logs and screenshots

After import:
image

After restarting the server:
image

The App_Data log:
[orchard-log-2024-06-19.log](https://github.com/user-attachments/files/15901051/orchard-log-2024-06-19.log)

Error in SQL Server (UI test in a different repo):
image

### PR DESCRIPTION
**Pull request by sarahelsaig**
Fixes #16346

### CODE REVIEW

**Comment by Piedone** [comment]
Please try to repro the issue with `YesSqlOptions.EnableThreadSafetyChecks` set, what happens then? Still successful?

**Comment by sarahelsaig** [comment]
Ok, I will check that too.

**Comment by sarahelsaig** [comment]
[I have enabled](https://github.com/OrchardCMS/OrchardCore/pull/16347/commits/9af341013181f4412012ea2d8078e90327d0a900) it and tested the scenario using both SQLite and SQL Server. The logs show no problem now that the migration recipe has been fixed:
```
2024-06-19 19:06:44.9190|||8|Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer|WARN|The ASP.NET Core developer certificate is not trusted. For information about trusting the ASP.NET Core developer certificate, see https://aka.ms/aspnet/https-trust-dev-cert. 
2024-06-19 19:06:45.1228|||14|Microsoft.Hosting.Lifetime|INFO|Now listening on: https://localhost:5001 
2024-06-19 19:06:45.1284|||14|Microsoft.Hosting.Lifetime|INFO|Now listening on: http://localhost:5000 
2024-06-19 19:06:45.1344||||Microsoft.Hosting.Lifetime|INFO|Application started. Press Ctrl+C to shut down. 
2024-06-19 19:06:45.1344||||Microsoft.Hosting.Lifetime|INFO|Hosting environment: Development 
2024-06-19 19:06:45.1374||||Microsoft.Hosting.Lifetime|INFO|Content root path: /home/sarah/Projects/OrchardCore/src/OrchardCore.Cms.Web 
2024-06-19 19:11:50.9110|Default|00-c5b08a3d9d20dca367b8561beba9f902-aff1855bc4b9fed6-00||OrchardCore.OpenId.Configuration.OpenIdClientConfiguration|WARN|The OpenID client settings are invalid: The authority cannot be null or empty.
The response type cannot be null or empty.
The response mode cannot be null or empty. 
2024-06-19 19:11:50.9364|Default|00-c5b08a3d9d20dca367b8561beba9f902-aff1855bc4b9fed6-00||OrchardCore.Twitter.Signin.Configuration.TwitterOptionsConfiguration|WARN|Integration with Twitter is not correctly configured. 
2024-06-19 19:12:19.7184|Default|00-ada19df463dd6dab8ab2a4a39786ab30-9f3606700275785a-00||OrchardCore.Twitter.Services.TwitterSettingsConfiguration|WARN|Twitter is not correctly configured. 
```

**Comment by sarahelsaig** [comment]
While doing the same on the `main` branch results no additional information as far as I can see.
[orchard-log-2024-06-19.log](https://github.com/user-attachments/files/15904172/orchard-log-2024-06-19.log)

**Review by Piedone — APPROVED** [review]

**Pull request merged**
