### PR TITLE
Update private constant to PascalCase

### LINKED ISSUE #14198: Constants should be pascal cased
I believe this block should be removed:

```
# Define the 'private_const_fields_ignore_camel_case_leading_underscore' naming rule.
dotnet_naming_rule.private_const_fields_ignore_camel_case_leading_underscore.severity = none
dotnet_naming_rule.private_const_fields_ignore_camel_case_leading_underscore.symbols = private_const_fields
dotnet_naming_rule.private_const_fields_ignore_camel_case_leading_underscore.style = camel_case_leading_underscore
```

c.f. https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/identifier-names
And check aspnetcore and runtime soruce code.

### PR DESCRIPTION
**Pull request by hishamco**
Fixes #14198

### CODE REVIEW

**Comment by MikeAlhayek** [comment]
you need to apply the rule if you want to change the `.editorconfig` file.

**Comment by jtkech** [comment]
https://github.com/OrchardCMS/OrchardCore/issues/14198#issuecomment-1693847971

At some point we added a rule for all private fields, that's why some private const has been changed, but then I added a new rule precisely to not have this constraint for private const.

We already can use Pascal case for private const, and this is what we use for new fields, but without forcing it that's why there is no analyzer violations on private const fields not using Pascal Case.

Removing this rule as you do here will force again to use an underscore + camel case for private const.

If we want to force PascalCase for private const, first a new rule need to be defined, this on the already defined private const group. Then in that case, yes private const fields would need to be updated to fix the new analyzer rule violations.

**Comment by hishamco** [comment]
> If we want to force PascalCase for private const, first a new rule need to be defined, this on the already defined private const group. Then in that case, yes private const fields would need to be updated to fix the new analyzer rule violations.

Is there a guidance for that, coz when I open `.editor` via VS I didn't find the private constants :(

**Comment by jtkech** [comment]
@hishamco 

I opened `.editorconfig` in `Notepad`, I will show you how to define a new rule if we really need it. Maybe @sebastienros saw some private const in camel case and thought that we currently have this rule.

This was the case before when we added it for all private fields, but the rule you are removing is precisely to remove this constraint for private const, so maybe nothing to do, see https://github.com/OrchardCMS/OrchardCore/issues/14198#issuecomment-1696475396

In the meantime you can take a look at https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/overview?tabs=net-7

**Comment by hishamco** [comment]
I will revert the changes in `.editorconfig`, so we can merge the this PR because it fixes the private constants that me & Seb saw :)

**Comment by jtkech** [comment]
Okay but maybe nothing to do, see also at the end of https://github.com/OrchardCMS/OrchardCore/discussions/14199#discussioncomment-6847239.

Yes my reflex is to fix current rule violations, not to apply implicit recommendations in all files in one pass but progressively if there is no violation.

But I'm not against this one because there are not so much files to update ;)

I will add the rule myself if we really want to **enforce** PascalCase for private const

**Comment by sebastienros** [comment]
I don't know where the discussions and PRs are at, I'll let you merge anything related as long as you are in an agreement.

**Review by jtkech — APPROVED** [review]

**Pull request merged**
