### PR TITLE
URI components Liquid accessors

### PR DESCRIPTION
**Pull request by jtkech**
Related to #9617 and #9618

Provides correct escaping to reconstruct a request or redirect URI.

### CODE REVIEW

**Comment by sebastienros** [comment]
Can these replaces the existing ones?

**Comment by jtkech** [comment]
> Can these replaces the existing ones?

No, the existing ones are still useful to get the non escaped original values.

**Comment by deanmarcussen** [comment]
Needs adding to the docs as well @jtkech  :) otherwise looks fine

**Comment by jtkech** [comment]
@deanmarcussen done through #10179 ;)

**Pull request merged**
