### PR TITLE
Make ShapeProxyBenchmark methods static

### PR DESCRIPTION
**Pull request by Skrypt**
(Visual Studio) code analyzer suggestion.

### CODE REVIEW

**Review by hishamco — APPROVED** [review]

**Review by Piedone — CHANGES_REQUESTED** [review]
This breaks the benchmarks:

image

Suppress the analyzer for the whole project, together with a comment on why is it necessary, instead. See https://github.com/Lombiq/.NET-Analyzers/blob/dev/Lombiq.Analyzers/Docs/ConfiguringAnalyzers.md#suppressing-analyzers-from-code-for-a-whole-project

**Comment by Piedone** [comment]
It does, see my comment just above.

**Comment by hishamco** [comment]
Oops, seems I was confused between the benchmarks themselves and the methods utilized by them. So ignore my approval

**Comment by Skrypt** [comment]
@piedone Can you create an issue with your suggestion?

**Comment by Piedone** [comment]
The fix was quicker :) https://github.com/OrchardCMS/OrchardCore/pull/15707

**Pull request closed without merging**
