### PR TITLE
GraphQL 7

### PR DESCRIPTION
**Pull request by agriffard**
https://www.nuget.org/packages/GraphQL/7.2.1
https://github.com/graphql-dotnet/graphql-dotnet/releases/tag/7.2.1

### CODE REVIEW

**Comment by agriffard** [comment]
Some help would be appreciated to fix the errors in LockedAsyncFieldResolver.cs

**Comment by agriffard** [comment]
Many errors updating from 4.x to 7.x.

https://graphql-dotnet.github.io/docs/migrations/migration5
https://graphql-dotnet.github.io/docs/migrations/migration7

**Comment by agriffard** [comment]
Help is wanted.

**Comment by hishamco** [comment]
We can close this on favor of #13255

**Comment by Piedone** [comment]
Closing in favor of https://github.com/OrchardCMS/OrchardCore/pull/13255.

**Pull request closed without merging**
