### PR TITLE
Prevent Uninitialized tenants from accessing ISiteService since the ISession instance is not yet set

### LINKED ISSUE #11976: Object reference not set to an instance of an object exception in production environment
### Describe the bug
I added a new tenant using the Tenants UI. When I click "Setup" button I am redirected to `https://subdomain.domain.com/?token=CfDJ8KtwYcM66YVAqGUg9CLX......` which shows HTTP Error 500.

Looking at the log file I see the following

```
2022-07-08 22:24:07.6669|test123|00-e5f6a593a8645780dc209197a58c33df-99eff78a1a46d690-00||Microsoft.AspNetCore.Server.Kestrel|ERROR|Connection id "0HMJ1550K2I32", Request id "0HMJ1550K2I32:0000000A": An unhandled exception was thrown by the application. System.NullReferenceException: Object reference not set to an instance of an object.
   at YesSql.QueryExtensions.Query[T](ISession session, String collection)
   at OrchardCore.Data.Documents.DocumentStore.GetOrCreateImmutableAsync[T](Func`1 factoryAsync)
   at OrchardCore.Documents.DocumentManager`1.GetOrCreateImmutableAsync(Func`1 factoryAsync)
   at OrchardCore.Settings.Services.SiteService.GetSiteSettingsAsync()
   at OrchardCore.Media.Processing.MediaTokenSettingsUpdater.ActivatedAsync()
   at OrchardCore.Environment.Shell.Scope.ShellScope.<>c.<<ActivateShellInternalAsync>b__43_0>d.MoveNext()
--- End of stack trace from previous location ---
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell)
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell)
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell)
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell)
   at OrchardCore.Environment.Shell.Scope.ShellScope.ActivateShellInternalAsync()
   at OrchardCore.Environment.Shell.Scope.ShellScope.ActivateShellInternalAsync()
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell)
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell)
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell)
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell)
   at OrchardCore.Modules.ModularTenantContainerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)    at YesSql.QueryExtensions.Query[T](ISession session, String collection)
   at OrchardCore.Data.Documents.DocumentStore.GetOrCreateImmutableAsync[T](Func`1 factoryAsync)
   at OrchardCore.Documents.DocumentManager`1.GetOrCreateImmutableAsync(Func`1 factoryAsync)
   at OrchardCore.Settings.Services.SiteService.GetSiteSettingsAsync()
   at OrchardCore.Media.Processing.MediaTokenSettingsUpdater.ActivatedAsync()
   at OrchardCore.Environment.Shell.Scope.ShellScope.<>c.<<ActivateShellInternalAsync>b__43_0>d.MoveNext()
--- End of stack trace from previous location ---
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell)
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell)
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell)
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell)
   at OrchardCore.Environment.Shell.Scope.ShellScope.ActivateShellInternalAsync()
   at OrchardCore.Environment.Shell.Scope.ShellScope.ActivateShellInternalAsync()
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell)
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell)
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell)
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell)
   at OrchardCore.Modules.ModularTenantContainerMiddleware.Invoke(HttpContext httpContext)
```

I can't reproduce this issue locally and it is happening only in Production environment. The production environment is running on Azure Web App using docker container with the following features 

```
services.AddOrchardCms()
             .AddSetupFeatures("OrchardCore.Redis", "OrchardCore.Redis.Lock")
             .AddGlobalFeatures("OrchardCore.DataProtection.Azure", "OrchardCore.Media.Azure.Storage","OrchardCore.Redis", "OrchardCore.Redis.Cache", "OrchardCore.Redis.DataProtection", "OrchardCore.Redis.Lock")
```

The app is running in production with no issues. However, I can't seems to be able to setup new tenants.

Is this a bug? Any idea how I can trace this issue or go about fixing it?

### PR DESCRIPTION
**Pull request by CrestApps**
Fix #11976

### CODE REVIEW

**Comment by jtkech** [comment]
Can't right now but need to think about it as we never had issue in the action filter, and maybe there are scenario where we still need site settings while initializing.

Idem about the media token updater, maybe we just need to do nothing only if the tenant is Uninitialized, and let it working if it is Initializing as it is checked in other places, would need to be tried.

**Comment by CrestApps** [comment]
I just changed the [RazorViewActionFilter.cs](https://github.com/OrchardCMS/OrchardCore/pull/11988/files#diff-6cc9be708bdc435533024bb861a580207f2ccb1a7d83f4da7ea5db67012f07bf) as per your suggesting to `if (siteService != null && shellSettings.State != TenantState.Uninitialized)`.

I also tested it and it worked with no problems.

**Comment by jtkech** [comment]
Cool thanks.

Can you test it without changing at all the action filter.

Then with only testing Uninitialized in the media token updater.

**Comment by CrestApps** [comment]
@jtkech I already did prior the PR. When the tenant is uninitialized, we get an exception. Adding `&& shellSettings.State != TenantState.Uninitialized` fixed the issue and worked with no errors

**Comment by jtkech** [comment]
Okay sorry

So okay for the media updater, but would it fail if we don't change the action filter, if not already tested ;)

**Comment by CrestApps** [comment]
@jtkech If we remove the change to `MediaTokenSettingsUpdater` we get the error also. We can change the code to this and the code still would work. I just don't know if the logic should be `_shellSettings.State != TenantState.Running` or `_shellSettings.State == TenantState.Uninitialized` I think in both places, we just can't access the site settings if the settings document isn't created yet since that would mean that ISession will still be null. 

Either way, I confirmed that in order for this to work, it must be changed in both  `MediaTokenSettingsUpdater`  and `RazorViewActionFilter`

```
            if (_shellSettings.State == TenantState.Uninitialized)
            {
                // At this point the tenant is not running which mean the request is likely tp be coming from setup request
                // We can't activate this class since siteService will have no ISession instance available
                return;
            }
```

**Comment by jtkech** [comment]
Okay cool then

I wanted to be sure that we need the change in both places, so I think that's okay to only check Uninitialized, so, as we laready saw in some scenario, we can still make this kind of service available during the setup.

**Comment by CrestApps** [comment]
@jtkech thank you! both places are only checking for Uninitialized now.

**Review by jtkech — APPROVED** [review]

**Comment by jtkech** [comment]
@CrestApps Just updated a little the comments and then approved this PR.

**Comment by CrestApps** [comment]
@jtkech this is great! Thank you!

**Review by Skrypt — APPROVED** [review]

**Pull request merged**
