### PR TITLE
Use file scoped namespace

### LINKED ISSUE #12029: Use file scoped namespaces

### PR DESCRIPTION
**Pull request by hishamco**
Fixes #12029

### CODE REVIEW

**Comment by Skrypt** [comment]
This thing will break everyone PR's 😞 😭

**Comment by Skrypt** [comment]
Only 61 files, it probably did not run on every file.

**Comment by hishamco** [comment]
I did that manually, please hold on while I push the next commit

**Comment by Skrypt** [comment]
Good luck doing that on 3668 files.

**Comment by hishamco** [comment]
I was suffering at the beginning, after then I got this done by the help of VS Studio 2022 ;)

**Comment by jptissot** [comment]
I would suggest not to merge this, and do it when we go along and merge pr's. Too many open pr's that will be broken with this.

**Comment by jtkech** [comment]
Idem as commented here https://github.com/OrchardCMS/OrchardCore/pull/12032#issuecomment-1188318199

**Comment by Skrypt** [comment]
I prefer that we do it in one PR than in different separated PRs because else it will be a total mess for the repo history.

**Comment by hishamco** [comment]
Also I will open a new PR to allow VS suggests this using `.editorconfig`

**Comment by jptissot** [comment]
> I prefer that we do it in one PR than in different separated PRs because else it will be a total mess for the repo history. At least we will be able to track that the changes are coming from a single PR.
> 
> If we ever do this.

But you would be creating merge conflicts in most existing pr's no ?

**Comment by Skrypt** [comment]
> But you would be creating merge conflicts in most existing pr's no ?

Yes, that's why I'm saying: if we ever do this.

**Comment by Skrypt** [comment]
Ok, we decided to do this progressively else it breaks everything. Closing.

**Comment by hishamco** [comment]
Ok

**Pull request closed without merging**
