### PR TITLE
fix 2 projects could not be loaded

### PR DESCRIPTION
**Pull request by infofromca**
cannotload21

### CODE REVIEW

**Comment by infofromca** [comment]
#1614 can be closed now

**Comment by sebastienros** [comment]
Can you explain the changes and the relationship with the linked issue?

**Comment by jtkech** [comment]
`OrchardCore.Application.Nancy.Targets` is a library package so normally it should be `netstandard2.0`.

Idem for `DerivedThemeSample2` which is a testing module but it was already `netcoreapp2.0` which is wrong, idem for other testing modules.

Normally we only use `Microsoft.NET.Sdk.Razor` for themes and modules, and only if they have at least one razor view.

I will check this.

**Comment by jtkech** [comment]
This is what we do unless for modules which will never have any views. For these ones i opted to still use `Microsoft.NET.Sdk` to not include in this case the razor sdk msbuild scripts.

But there was a mistake for the testing modules that i'm currently fixing.

That said i could repro the message about `DerivedThemeSample2` which has the exact same csproj file as `DerivedThemeSample`. Hmm not sure it's a real error because all tests build and run without errors.

I will check this.

**Comment by jtkech** [comment]
I don't think it's a real error.

Through VS i just tried to unload the project, then reload it, then the package manager did a restore for this project without any error messages.

Then i re-did a git clean, then i got again the same messages **but it was related to 2 other libraries**. Doing it again i got only one message but now related to `BaseThemeSample2`.

Sound like a VS issue, i will investigate.

**Comment by jtkech** [comment]
Didn't find anything else, it's erratic, the message is not always related to the same projects. That said seems to be always related to a referenced project by the `OC.Tests` project. So, i will still investigate.

Meanwhile, there are some issues around this where i found this comment.

> Typically this error appears when the projects are still not loaded, in that case auto restore will try again when the project metadata is pushed, and everything will be restored correctly at that time.

**Comment by jtkech** [comment]
Related links.

[This one](https://github.com/NuGet/Home/issues/4307), and [this one](https://github.com/dotnet/project-system/issues/1600).

So, i think that right now for large solutions a first restore could fail on not yet nominated projects, then a delayed automatic restore is done ... as i understand in [this part of code](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/NuGet.SolutionRestoreManager/SolutionRestoreWorker.cs#L460).

Honestly, i think there is nothing to do here, unless the little updates i mentionned above and that i did here #1973.

**Pull request closed without merging**
