### PR TITLE
Adding Validate Pull Request GitHub Actions workflow to check PRs for merge conflicts (Lombiq Technologies: OCORE-141)

### LINKED ISSUE #15060: Automation to notify PR authors that their PR has a merge conflict
### Is your feature request related to a problem? Please describe.
When a PR has merge conflicts, the reviewer has to point that out if the author doesn't check back. Otherwise, the author wouldn't know that since they opened it, they PR got a merge conflict.

### Describe the solution you'd like
Automate this. Similar to what [Lombiq's `validate-pull-request`](https://github.com/Lombiq/GitHub-Actions/blob/dev/Docs/Workflows/Productivity/ValidatePullRequest.md) workflows does (but with `pull_request_target`), we could use [`eps1lon/actions-label-merge-conflict`](https://github.com/eps1lon/actions-label-merge-conflict) to label conflicting PRs, and add a comment under them. See [example](https://github.com/Lombiq/GitHub-Actions/blob/dev/.github/actions/check-merge-conflict/action.yml#L13).

### Describe alternatives you've considered
Perhaps there are other usable automation for this but the mentioned action works well.

### PR DESCRIPTION
**Pull request by Piedone**
Fixes #15060

### CODE REVIEW

**Comment by Piedone** [comment]
@hishamco (or anybody else interested) may I have a review, please?

**Review by hishamco — APPROVED** [review]

**Comment by Piedone** [comment]
Thanks!

**Comment by MikeAlhayek** [comment]
@Piedone I am not sure this is a good idea when we have so many open PRs. So many things are waiting to be processed because multiple PR have conflicts. Maybe it's fine for the most part or maybe something is wrong with it

**Comment by Piedone** [comment]
What's the issue you're seeing?

**Pull request merged**
