### PR TITLE
Update branding assets (Lombiq Technologies: OCORE-57)

### LINKED ISSUE #6279: Update branding
We don't really have concise branding guidelines or even proper branding assets, just what's left over from a long time ago: https://docs.orchardcore.net/projects/O1/en/latest/Documentation/Walkthroughs/#orchard-branding

What I'd imagine:

- Possibly retouch the existing design a bit: E.g. the current logo's outer circle is strangely uneven. 
- Maybe use a different branding color than the green there or just use those but then we should settle with the same main brand colors everywhere. Currently, there are these old greens and greys, then there's the other green on the [website](https://www.orchardcore.net/), a blue [on the docs site](https://docs.orchardcore.net/en/dev/) and another blue for the social preview: 
image
- Create new, high-resolution bitmaps.
- Possibly some branding guidelines on how to use the new assets.

We can potentially sponsor designers for this (the bottleneck is their capacity).

[Here're the old branding assets](https://docs.orchardcore.net/en/dev/docs/resources/branding/) in the docs.

### PR DESCRIPTION
**Pull request by Piedone**
Updated branding assets in the docs.

Remaining:

- ✔️ Logomarks (symbol logo versions)
- ✔️ (Done by Antoine) Update logos/favicons for the docs site and the app itself.

Fixes #6279

### CODE REVIEW

**Comment by deanmarcussen** [comment]
Can this go out of draft now @Piedone with @agriffard prs?

**Comment by Piedone** [comment]
I'm waiting for the logomarks (including AI source files and high-res PNGs) as well as high-res PNGs from Paris and co for this but Antoine's PR addresses the others.

**Comment by sebastienros** [comment]
Can we create the missing files if we have the vector files?

**Comment by Piedone** [comment]
In principle yes but I won't venture into that.

**Comment by Piedone** [comment]
Added the remaining files now.

**Pull request merged**
