### PR TITLE
Remove useless placeholder file

### PR DESCRIPTION
**Pull request by TFleury**

### CODE REVIEW

**Comment by Skrypt** [comment]
Hmm good one. I think at some point it was necessary to keep it, can't remember why. @jtkech

**Comment by TFleury** [comment]
I think it was necessary before having some code in the project. But since there is a Startup and controller in project, placeholder is useless.

**Comment by jtkech** [comment]
As I remember it is a concern about creating the directory when publishing the `wwwroot` of the web application, but normally not a problemwith embedded files of a module / theme.

But at least should be tried ;)

**Comment by MikeAlhayek** [comment]
@TFleury 

> As I remember it is a concern about creating the directory when publishing the wwwroot of the web application, but normally not a problem with the embedded files of a module / theme.

Did you try removing that file and then publishing to ensure the embedded files of modules and theme don't break?

**Comment by TFleury** [comment]
I tried removing the file and the published directory structure is strictly the same.
I tested the output and didn't encountered any problem creating a new site.

**Review by Skrypt — APPROVED** [review]

**Pull request merged**
