### PR TITLE
Update Fluid.Core, YesSQL, and Shortcodes

### PR DESCRIPTION
**Pull request by MikeAlhayek**

### CODE REVIEW

**Comment by MikeAlhayek** [comment]
This PR is going to have to wait for https://github.com/sebastienros/shortcodes/pull/34 then a new release of Shortcodes package.

**Comment by Piedone** [comment]
Converted to draft until then.

**Comment by MikeAlhayek** [comment]
@lahma can you please review this PR?

**Review by lahma — APPROVED** [review]
Seems legit, there might be some performance improvement opportunities later, but not related to this PR 👍🏻

**Pull request merged**
