### PR TITLE
Rename dynamic cache tag helper

### PR DESCRIPTION
**Pull request by deanmarcussen**
Fixes https://github.com/OrchardCMS/OrchardCore/issues/6548

### CODE REVIEW

**Comment by hishamco** [comment]
Still I see a value of using `oc` as TagHelper prefix that can be configured into `_ViewImports.cshtml` not as a part of TagHelper name, this will avoid the name conflict from Microsoft and other 3rd parties TagHelpers. But I will leave this open to the community to decide

**Comment by jtkech** [comment]
@deanmarcussen 

Here the singularity is that the mvc `cache` tag helper can be selected only by its tag name without any attribute.

**So i suggest `distributed-cache`** because the mvc one needs a `name` attribute, and our one a `cache-id` attribute.

And also because our tag helper uses `IDistributedCache`.

**Comment by deanmarcussen** [comment]
> **So i suggest `distributed-cache`** because the mvc one needs a `name` attribute, and our one a `cache-id` attribute.
> 
> And also because our tag helper uses `IDistributedCache`.

It's kinda wordy? But so is `<dynamic-cache>` But I'm not hearing any better offers from anyone...

@hishamco The idea is to not have to configure anything special in `_ViewImports` (because how will people know they have to - it's been three years of having this tag before we realised it conflicted). So I don't see how having to use a prefix fixes anything.

**Comment by hishamco** [comment]
Three years!! that's too long ;) the tag prefix will not change the name, we can keep the tag name as it was, so no breaking changes. It just a token that can differentiate our tag helpers from other 3rd-party once and avoid us from thinking about new names whenever create a tag helper and AspNetCore has similar one. It is something like old WebForms controls: `asp:Button`, `asp:Label`, IMHO the prefix will add a value nothing else

**Comment by deanmarcussen** [comment]
Maybe I am misunderstanding the prefix suggestion. 

It is something the user has to add to their `_ViewImports` file? so that taghelpers from a particular  assembly are prefixed?

So doesn't prevent the collision, just provides another way of managing them.

If I have misunderstood, show an example?

**Comment by hishamco** [comment]
> It is something the user has to add to their _ViewImports file?

Exactly!!

> So doesn't prevent the collision

Why?!! if we prefix our tag helpers in all assemblies, no collision will happen, because we should write `oc:` first, then the VS intellisense will recognize them

**Review by jtkech — APPROVED** [review]

**Pull request merged**
