### PR TITLE
Flow editor  CSS/UI improvements

### LINKED ISSUE #4685: Utilize more white-space for Content Card editor
As per comments in #4470,  For better usability of Content Card for smaller screens and nested content

- Reduce padding for card body.
-  Hide the field label/hint if the widget content type has only one field.

### PR DESCRIPTION
**Pull request by ns8482e**
Fixes #4685 
1. Reduced padding and margin space
2. Moved flow metadata to header
3. Changed "Add Widget" and Insert widget to icon button
4. Unify button color "Add" with primary and "Delete" with danger class to match other areas of orchard core.
5. CSS/UI improvements BagPart, WidgetListPart

flowpage

### CODE REVIEW

**Comment by deanmarcussen** [comment]
LGTM. 
Particularly moving the metadata to the header, and with a hover. nice

**Comment by ns8482e** [comment]
@deanmarcussen @jptissot  Can please review changes related Assets.json

Thank you.

**Comment by deanmarcussen** [comment]
> @deanmarcussen @jptissot Can you please review changes related Assets.json

Assets.json changes LGTM @ns8482e 

Please let us know when this is ready, or if you intend further changes.

**Comment by ns8482e** [comment]
@deanmarcussen  I am done with changes - no more changes.

**Pull request merged**
