### PR TITLE
Unused usings

### PR DESCRIPTION
**Pull request by jtkech**

### CODE REVIEW

**Comment by Skrypt** [comment]
LGTM

**Comment by hishamco** [comment]
I think there are many `using` need to be removed, unless someone already clean them ;)

**Comment by jtkech** [comment]
@agriffard already did a big cleanup, just because i just saw these 2 ones
@Skrypt thanks ;) i was just waiting for the CI before merging

**Comment by Skrypt** [comment]
I just saw some more in AliasPartDisplayDriver. Trying to clean code from Visual Studio to see if it works.

**Pull request merged**
