### PR TITLE
Add reference tokens support

### PR DESCRIPTION
**Pull request by timlunev**
@kevinchalet this PR duplicates all the changes from #5774 with the discussed review notes.

Changes for #1983

- Add Use Reference Token checkbox functionality to the OpenIdServerSettings View
UseReferenceTokens

- Remove typo on User Info endpoint description
- Add Reference setting validation to the OpenIdServerService

### CODE REVIEW

**Comment by hishamco** [comment]
Why you duplicate the PR?!!

**Comment by timlunev** [comment]
@hishamco I've tagged you in #5774 could you look at it

**Comment by hishamco** [comment]
I didn't see the commet ;)

**Comment by kevinchalet** [comment]
Merged, thanks for your contribution! 👏

**Pull request merged**
