### PR TITLE
Fix Content-Types and Content-Parts search UI

### PR DESCRIPTION
**Pull request by MikeAlhayek**
Before this, if you click enter in the text box you'll get a 404. Also, the `keyCode` property on the JavaScript is deprecated.

Also, now we no longer need jQuery for this to work. And the logic is reusable.

Here is a quick demo of the UI behavior for both content-types and content-parts UI.

content-types-list

### CODE REVIEW

**Comment by Piedone** [comment]
I see the Enter issue, but not the Esc one. On `main`, if I hit Esc when searching, then the search box will be cleared and the filtering removed:

https://github.com/OrchardCMS/OrchardCore/assets/1976647/d5300276-9deb-4140-bcdf-f70c29ff8514

This is exactly what I'd expect to happen. What behavior is this fixing for Esc?

**Comment by MikeAlhayek** [comment]
I don't think there was an issue with escape actually. There is a deprecated warning. But the enter is definitely a problem. 

Also, the resource is now reusable too. 

Let me know if you see an issue with the current PR.

**Comment by Piedone** [comment]
I'll review it soon.

**Comment by Piedone** [comment]
I still get a 404 on Enter:


https://github.com/OrchardCMS/OrchardCore/assets/1976647/90112f61-3c0d-4b7c-a7aa-a7a1cb7e7d54

**Comment by MikeAlhayek** [comment]
> I still get a 404 on Enter:

I am guessing you need to do a deep refresh CTRL + F5. It works with no issues for me (just tried it out again). Look at the video in the description to see how it works for me.

**Comment by Piedone** [comment]
I did that. With the DevTools open the cache is disabled anyway.

**Comment by MikeAlhayek** [comment]
Can you please check the generated HTML? ensure that the old script is removed and the `list-items-filter.js` is included

**Comment by Piedone** [comment]
Now it works, WTF. Anyway, I'll continue with the code review.

**Pull request merged**
