### PR TITLE
Prettify Features page

### LINKED ISSUE #4175: Prettify Features page
This include:

- Unify the look and feel for the search bar as content items and tenants pages
- Change Features to Modules
- Use Bulk actions drop down and remove the toggle option (optional)
- Use smaller font size for module's names

### PR DESCRIPTION
**Pull request by hishamco**
Fixes #4175

### CODE REVIEW

**Comment by hishamco** [comment]
The features page is now look like:

Features

@sebastienros can I change routes from Features to Modules, coz the page is for modules which are contains features

**Comment by sebastienros** [comment]
> Features to Modules, coz the page is for modules which are contains features

Please keep the Features name, unless more people would like to change this. We had `Modules` in O1 and we intentionally decided to use Features here, because this page is showing __features__.

**Comment by Skrypt** [comment]
Should we change the menu name accordingly then?

**Comment by sebastienros** [comment]
Sure, would make sense

**Pull request merged**
