### PR TITLE
Add ShapeDump

### PR DESCRIPTION
**Pull request by deanmarcussen**
Fixes https://github.com/OrchardCMS/OrchardCore/issues/1507

I was trying the tabs for widgets example from https://github.com/OrchardCMS/OrchardCore/pull/4470 and struggling to get the placement correct (found a minor issue, which is fixed in https://github.com/OrchardCMS/OrchardCore/pull/4484) but I quickly wrote a shape dumper, to try and see what was going on.

I've made `ShapeMetadata` serializable 

**Edited, removed old examples**

### CODE REVIEW

**Comment by jptissot** [comment]
This looks useful! Would need some docs to go along with it :)

**Comment by deanmarcussen** [comment]
to be refactored to use the new ConsoleLog extension helper

**Comment by deanmarcussen** [comment]
I've adapted this to use the ConsoleLog and added wrapper console log shapes to ondisplaying for items, so when you dump ZoneHolding, you see the holding zone, then another log with all the items in it, with their alternates (as they are calculated at execution time)

Here's an example dumping the Model from the Blog Content template

shape-log

Documentation to follow @jptissot :) if approved.

Also noting, I've removed the liquid filter. 
I don't know which project a `ConsoleLog` Liquid filter should go in? 
There is no `ContentManagement.Liquid` related project.
And probably the console log is useful for liquid as well.

**Comment by sebastienros** [comment]
Why a `ShapeConsoleLogWrapper` ? Can't we just use the helper?
The liquid filter should be in the same project as the helper.

**Comment by deanmarcussen** [comment]
It inserts the `ShapeConsoleLogWrapper` on any item or property that is a shape. Otherwise the `AlternatesCollection` isn't populated, as that's built on shape execution.

Inserting the wrapper means when you dump a shape from a `Content` template that has items, you get the list of items in the console, then each item is dumped afterwards (as the wrapper executes) and the alternates collection is populated.

Same applies with `ZoneHolding` which has the shapes in it's properties, rather than items collection

**Comment by Skrypt** [comment]
This works but misses the Liquid Filter for calling this method from a Liquid template.

**Comment by deanmarcussen** [comment]
@Skrypt yeah see #5045 I'll rustle up the liquid version this week

**Comment by Skrypt** [comment]
And why not adding Orchard.ConsoleLog((object)Model.Content) in the Content.cshtml template? I'm looking at the method and it should only display in dev mode which seems fine enough to simply add it by default.

**Comment by urbanit** [comment]
What about Content.liquid? What is the equivalent?

**Comment by urbanit** [comment]
I should wait for #5045  I assume :-)

**Pull request merged**
