### PR TITLE
List query helpers

### LINKED ISSUE #4848: Create helper to load ListPart items
Hello,
I am trying to get the list of questions based on the culture in a decoupled way.I used same approach as the Blog theme:
image
here you can see that i have both languages
image
and for each list i have one Item 
image

But
in razor i always end up with the right set but an empty list
image

### PR DESCRIPTION
**Pull request by arkadiuszwojcik**
List module query code was moved to dedicated class. Also two helpers methods were exposed: `QueryListItemsCountAsync `and `QueryListItemsAsync`

I think it fixes #4848

### CODE REVIEW

**Comment by arkadiuszwojcik** [comment]
Shoud I add liquid filters aswell?

**Comment by deanmarcussen** [comment]
Looks good @arkadiuszwojcik 

I have a few suggestions though.

Could you make it an extension on the IOrchardHelper? Then it is accesable in Razor through `Orchard.QueryListItemsCountAsync` etc. You can also resolve `ISession` from the `IOrchardDisplayHelper`

The MarkdownHelperExtensions have a good example of how it's generally done through the code base.
https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.Markdown/Razor/MarkdownHelperExtensions.cs

You can change the namespace as per the MarkdownHelperExtensions as well which makes it easier to access.

Also I'm not sure I agree with moving the query out of the driver? 
Am I wrong but I don't see the benefit?
Possibly I am prejudiced because I moved it to a service on a PR that is still waiting for review https://github.com/OrchardCMS/OrchardCore/pull/3711/files to get ordering achieved. The reason for moving it on that PR is that it is reused. 
I don't see the reuse in this PR? and if it is `internal` then nothing else can reuse it?

**Comment by arkadiuszwojcik** [comment]
Thanks @deanmarcussen for feedback.

List of changes:

I added `ListOrchardHelperExtensions `(I was actually basing on `TaxonomyOrchardHelperExtensions ` example)

I moved old query code back do driver class. Initialy I thought it is worth to have all query logic in one class, but after your comment I think it was bad idea.

`ListQueryHelpers` class is now internal. It is used by Filters and `ListOrchardHelperExtensions `. I don't want to expose it to avoid duplicate logic already exposed in `ListOrchardHelperExtensions `

**Comment by deanmarcussen** [comment]
LGTM

**Comment by Skrypt** [comment]
I'm thinking about that one and I'm not sure of the implementation as I introduced lately a IQueryResult interface which returns the count of records possible for Lucene Queries. Though a SQL Query can be using paging with `LIMIT 10 OFFSET 10`

**Comment by sebastienros** [comment]
@Skrypt I think your concern is not an issue. The intent of Count is correct, it's just that you would not put the take/skip in the predicate.

**Comment by Skrypt** [comment]
More ways to do the same thing is fine, I was just having self thoughts on that one I guess 😄

**Pull request merged**
