### PR TITLE
Update YesSQL 3.4.0

### LINKED ISSUE #14036: Multi-tenancy with different schema write in wrong schema for indexes
### Describe the bug
We discovered a bug when using a multi-tenant version of OrchardCore with the same database for each tenant but different schema.  For now, I don't know if the issue is only on postgresql or on other kind of database too.

### To Reproduce
1. Create a SaaS tenant (so it will fall on default schema, public for us because we used a postgresql database)
2. Create a second tenant, let's say tenant1, on the same database but in the schema "tenant1"
3. Create a third tenant, let's say tenant2, on the same database but in the schema "tenant2"
4. Try to create a content item on tenant1 and on tenant2. Depend on the last launched tenant, one of them will not act as wanted. 
5. The content item will be successfully created on one of the tenant (let's say tenant1).
6. On the other one (let's say tenant2), an error will occurs as the content item will be created in tenant2.Document but the index will fail as it try to insert it in tenant1's indexes. For example, one of the error we got : `PostgresException: 23503: insert or update on table "ContentItemIndex" violates foreign key constraint "fk_contentitemindex" DETAIL: Detail redacted as it may contain sensitive data. Specify 'Include Error Detail' in the connection string to include this information.`
7. We discovered that, if we force the tenant that failed to create the content item to reload (by activating a new feature for exemple), we will not face the issue anymore on this tenant but now, the issue will be it on the other tenant.

We think that, somewhere, there is a mismatch between the schema, maybe with "OrchardCore.Data.IndexServiceCollectionExtensions.AddIndexProvider" but we're not sure that's the rootcause for now.

### Expected behavior
Each tenant successfully save the Content Item in Document and in Indexes in the correct schema.

### Screenshots

image

### PR DESCRIPTION
**Pull request by hishamco**
https://github.com/sebastienros/yessql/releases/tag/v3.4.0

Fix #14036

### CODE REVIEW

**Comment by hishamco** [comment]
Should fix #14338 right?

/cc @MikeAlhayek

**Comment by hishamco** [comment]
Seems the build complaining about using unicode, I will fix it ASAP

**Comment by sebastienros** [comment]
I'd rather see a PR that updates YesSql and fixes the index issues in migrations, targeting release/1.7.
Then the fixes will flow back to main. Otherwise we need to do the changes in both branches and fix merge conflicts.

**Comment by sebastienros** [comment]
@hishamco this should also fix the issue where we had problem with unicode chars in the query editor.

**Comment by sebastienros** [comment]
But we need to ensure it has fixed it, it would be bad to ship a patch release that has more bugs :/

**Comment by sebastienros** [comment]
We need to check all indexes

**Comment by sebastienros** [comment]
> related to the issue https://github.com/OrchardCMS/OrchardCore/issues/13440 I think the issue needs to be fixed in the SQL Parser itself to support using N for nvarchar type

You already mentioned that multiple times, and I answered it already, and will repeat it, I don't think so, and I think I fixed it in YesSql. To prove me wrong you should be able to repro the issue even with the new YesSql version.

**Comment by sebastienros** [comment]
> @MikeAlhayek I prefer to fix the indexes in another PR to avoid mixing things.

Updating YesSql **IS** to fix the index issue. I don't think it add much value to do one without the other, but whatever works for everyone.

**Comment by jtkech** [comment]
> should fix the issue for MySQL without having to reduce the size of the column length.

As I can see there is no current issue for the `IDX_AliasPartIndex_DocumentId`.

What I meant is that we already reduced the size of the Alias column (see below). In your comment `DocumentId (26)` is wrong as it is at most a bigint (size = 8 bytes = `2 chars size`), the 2 booleans may not share the same bytes but `one char size` (4 bytes) is sufficient, anyway we kept a margin of 4 bytes.

https://github.com/OrchardCMS/OrchardCore/blob/f377a07462ea7843094c6872c12c43c74727f728/src/OrchardCore.Modules/OrchardCore.Alias/Models/AliasPart.cs#L7-L13

**Comment by sebastienros** [comment]
> should fix the issue for MySQL without having to reduce the size of the column length.

we don't need to restrict the size of the Alias column anymore, at least not for MySQL. We just need to update the index definition.

So this doesn't make sense anymore:

>  // Maximum length that MySql can support in an index under utf8mb4 collation is 768, 
 // minus 2 for the `DocumentId` integer (bigint size = 8 bytes = 2 character size), 
 // minus 26 for the `ContentItemId` and 1 for the 'Published' and 'Latest' bools. 
 // minus 4 to allow at least to add a new integer column. 
 public const int MaxAliasLength = 735; 

We should just have `public const int MaxAliasLength = 123455;` or whatever limit we want to apply here.

**Comment by jtkech** [comment]
Yes I understand, this is why I said

> Yes we could think about no longer reduce MaxAliasLength and apply what you suggested ...

So if we go this way we may want to revert back the size we reduced for Alias and also for other indexes for the same reason. Then use the new `Column(n)` syntax with the right values and comments.

**Comment by MikeAlhayek** [comment]
@sebastienros I am merging this one and starting a new PR to fix the actual issues. We'll chary pick this one and the new one into 1.7.1. Can't modify this one since it is a fork not a branch we can maintain

**Comment by sebastienros** [comment]
That was supposed to target release/1.7

The flow is that we release these fixes for 1.7 and then we'll merge release/1.7 to main. We can't do it the other way around, which means now we have to cherry pick every change and do it again.

**Comment by sebastienros** [comment]
Sorry, my bad, this one doesn't need to be in release/1.7

**Comment by sebastienros** [comment]
Or it does, if we want the indexes to be fixed in 1.7, because it has the index length support :/

**Pull request merged**
