### PR TITLE
Upgrade ImageSharp.Web to v1.0.0-beta9

### LINKED ISSUE #4073: Upgrade ImageSharp.Web
[The PR to reduce allocations](https://github.com/SixLabors/ImageSharp.Web/pull/69) was merged, need to wait for release.

### PR DESCRIPTION
**Pull request by lahma**
Fixes  #4073

### CODE REVIEW

**Comment by deanmarcussen** [comment]
@lahma Nice one. Be good to get this in.

However there are a few breaking changes in beta8 which is why the build failed.

If you don't mind I'd prefer to do after https://github.com/OrchardCMS/OrchardCore/pull/4025 as there are also breaking changes with how we interact with ImageSharp in that PR.

**Comment by lahma** [comment]
@deanmarcussen ah OK cool, seems that the build failed because `ImageMetaData` is now `ImageMetadata`, force pushed better commit.

**Comment by jptissot** [comment]
lgtm

**Comment by sebastienros** [comment]
Please create a new PR since #4025 is now merged. Or fix the conflicts, whichever is easier

**Comment by lahma** [comment]
Thanks for the heads up, I'll try to do a rebase when I get back to keyboard.

**Comment by lahma** [comment]
There's an unfortunate bug, tracked here https://github.com/SixLabors/ImageSharp.Web/pull/76 . Requires a new ImageSharp.Web release before this PR can fly.

**Comment by deanmarcussen** [comment]
Good spot. There are nightly builds on myget for imagesharp so if the pr is accepted but release delayed we can at least test it with the nightlies

**Comment by lahma** [comment]
Now using new beta9 lib with the fix, build is green now.

**Pull request merged**
