### PR TITLE
Fix localized datepicker for DateField

### PR DESCRIPTION
**Pull request by stoyandimov**
* Add the jQuery UI when date filed editor is displayed (+ i18n)
* Add jQuery UI image for the default template to ensure month arrows display correctly.

Fixes: https://github.com/OrchardCMS/OrchardCore/issues/12762

### CODE REVIEW

**Comment by hishamco** [comment]
Please screenshot

**Comment by stoyandimov** [comment]
Screenshot with Bulgarian localization
 image

**Comment by hishamco** [comment]
Do we have `jQuery-ui-i18n` in our resource before?!! If Yes I'm not sure why we didn't use this from awhile ;)

**Comment by hishamco** [comment]
Could you please try `ar` culture and share a screenshot

**Comment by stoyandimov** [comment]
Not perfect:
image

**Comment by hishamco** [comment]
I dislike the months names ;)

LGTM

**Comment by hishamco** [comment]
BTW do we need a variations for those attached colorized images

**Comment by stoyandimov** [comment]
I initially tried with only one image. However, the hover effect loads icons from a different image. Then I wasn't sure which ones are required so I added them all (as per the docs of jquery-ui).

**Comment by stoyandimov** [comment]
> Do we have `jQuery-ui-i18n` in our resource before?!! If Yes I'm not sure why we didn't use this from awhile ;)

I checked that. I believe ([here](https://github.com/OrchardCMS/OrchardCore/commit/050d766f0d980c20229095b59333e214b1464ab9#diff-0dbbec37c3f8b3e751ec99d345c69464351a552a508221b3bd47ea275e297fa2)) it was moved from the layout.cshtml to the editor of the DateFiled, but it somehow never made it in the localized editor.

**Comment by Skrypt** [comment]
I think the appropriate fix would be to use a different date picker that doesn't use JQuery UI. But for now, I guess that it can work. Though, we should really try to move away from JQueryUI.

**Comment by stoyandimov** [comment]
This PR is a bug fix for an issue scheduled for 1.6. Looking at the code and commit history, the bug is that `jQuery-ui` is being used but the library (though present in the Resource Manager) is not included.

@Skrypt please, feel free to close this PR if you really find this fix inappropriate or if it is decided that the calendar fix should be replacing jQuery-ui all together.

**Comment by Skrypt** [comment]
Nah, I guess we should merge it for now since it fixes the issue with the current implementation. Thanks.

**Comment by hishamco** [comment]
LGTM after remove the extra icons PNGs, I'm sure we aren't using other than black icons, right?

**Comment by hishamco** [comment]
@stoyandimov could you please react to the latest comment, then we could merge

**Comment by hishamco** [comment]
@stoyandimov if you are busy let us know, so I can start a new PR or update yours if it's possible. We need to merge this before realease `1.6`

**Comment by Skrypt** [comment]
@hishamco Use Gitextensions and pull the Pull Request fork locally. Then make the changes.

**Comment by hishamco** [comment]
I will try, coz I remembered that I did it in OC Extractor, but for unknown reason I become the only commiter

**Comment by sebastienros** [comment]
Note for later: the ui-icons_* files are defined in the jquery-ui.css file. These files need to be in a ./images subfolder of the css.

**Comment by hishamco** [comment]
I just checkout the PR into a local branch, seems Seb merge it quickly :)

I will add a new PR

**Comment by asemandeveloper** [comment]
Hello to all
As with Orchard CMS, it is better to display the calendar based on the selected culture. For example, if the Arabic culture is selected, the calendar will also show Hijri.
In your work, only the title of the months changes and not the dates and days of the calendar.

**Comment by hishamco** [comment]
> As with Orchard CMS, it is better to display the calendar based on the selected culture. For example, if the Arabic culture is selected, the calendar will also show Hijri.

This is valid for `ar-SA` coz not all the Arabian countries are using Hijri calendar

**Comment by asemandeveloper** [comment]
> 

But by choosing the Persian culture (fa), the calendar does not become Jalali calendar!

**Comment by hishamco** [comment]
There's another service that you choose use to manage the calendar(s) `ICalendarSelector` but I don't think it's align with the jQuery datapicker

**Pull request merged**
