### PR TITLE
Update Azure.Search.Documents 11.6.0-beta.3

### PR DESCRIPTION
**Pull request by hishamco**
https://www.nuget.org/packages/Azure.Search.Documents/11.6.0-beta.3

### CODE REVIEW

**Review by Piedone — CHANGES_REQUESTED** [review]
I don't think we should update to beta versions, unless they fix a bug that's important for us. NuGet analyzers also recommend not depending on non-release versions from a release package (that OC is).

**Comment by MikeAlhayek** [comment]
> I don't think we should update to beta versions, unless they fix a bug that's important for us. NuGet analyzers also recommend not depending on non-release versions from a release package (that OC is).

Agreed

**Comment by hishamco** [comment]
No problem we will wait for next stable release

**Comment by Piedone** [comment]
Also, I'm just stating the obvious, but please test these changes too. Even patch versions can bring breaking changes even if they shouldn't (we've seen this with .NET too).

**Pull request closed without merging**
