### PR TITLE
Update GraphQLFilter example

### PR DESCRIPTION
**Pull request by MikeKry**
Update GraphQLFilter example.

Related to #12797

### CODE REVIEW

**Comment by MikeAlhayek** [comment]
@MikeKry I think we need to do more here.

First of all, I think filters isn't needed in this case when we use IndexAlias. But we also have to add a warning to explain that the property names in the index should match the part. We should also explain when a filter is needed or not.

**Comment by MikeKry** [comment]
@MikeAlhayek 

I just fixed the example in docs as it was not working at all.

But I agree, that it should cover this topic more in depth. Apart from using WhereInputQueryObjectType or GraphQLFilter there are also other ways how to define query and filters when it comes to custom types.

**Comment by MikeAlhayek** [comment]
@MikeKry agreed! One question/suggestion was logged here https://github.com/OrchardCMS/OrchardCore/issues/12847

I'll look at the docs soon

**Comment by Piedone** [comment]
Could you please finish the review of this, @MikeAlhayek?

**Review by MikeAlhayek — COMMENTED** [review]
clean up comment

**Review by MikeAlhayek — APPROVED** [review]

**Pull request merged**
