### PR TITLE
Create a abstract service, UserPropertiesService,  for user

### PR DESCRIPTION
**Pull request by infofromca**

### CODE REVIEW

**Comment by infofromca** [comment]
fixed #3435

**Comment by deanmarcussen** [comment]
I'm not sure I understand how this is fixing the issue you mention?

The `Properties` update methods you have added are already available as extensions methods on `EntityExtensions`

It looks like the `UserManager` already does what is necessary to get a user, so I wonder why a wrapper service is helpful?

**Comment by infofromca** [comment]
it is still diff.
1-- mine deal with user, for exaple, null
2--update the use directly.

for get , just benefit from the injection of _userManager and make it clearly.  if not necessary, we can delete it.

**Comment by deanmarcussen** [comment]
From your issue here https://github.com/OrchardCMS/OrchardCore/issues/5916 I don't see how this service would work?

**Pull request closed without merging**
