### PR TITLE
Reusing compiled views across tenants

### LINKED ISSUE #998: Enabling/Disabling features perf investigation
Enabling and disabling a feature used to take something like 100ms from the features page. Today I noticed it would take multiple seconds. This is a huge regression that should be looked into.

### PR DESCRIPTION
**Pull request by sebastienros**
The move to 2.0.0 introduced a regression in the way we were sharing compiled views across tenants. The impact is that running through setup, or enabling/disabling a feature, would take significantly more time.

Fixes #998

### CODE REVIEW

**Comment by Jetski5822** [comment]
LGTM

**Comment by jtkech** [comment]
- We can grab **precompiled** view descriptors once, not for each tenant.

- Maybe simpler to use a wrapper class, but that's ok waiting for mvc to expose the compiler cache.

- The only problem i see is that in our static cache, the entries options rely on file providers which are tenant services.

**Just some thinkings**

- The composite razor file provider is a tenant service but it embeds e.g the `ContentRootFileProvider` which is at the app level. But it also embeds some of our file providers which are registered at the tenant level.

- So, maybe good to move some of our file providers at the app level, and maybe also the razor file provider, as the `ContentRootFileProvider` is, but not sure.

**Comment by sebastienros** [comment]
@jtkech I think what we do it totally fine. We can share higher level components across tenants. And when we create an entry from a tenant, it will be available to all others, even if this tenants is recycled, as nothing but tokens is kept.

**Comment by jtkech** [comment]
Okay.

But what you think about expiration tokens which are kept and could hold reference on tenant file providers?

**Comment by jtkech** [comment]
About grabbing precompiled views, just tried, it only take 4ms the 1st time, then for another tenant only 1ms. So that's fine.

So, if you think it's ok about my above concern on file providers references, LGTM.

**Comment by jtkech** [comment]
> We can share higher level components across tenants ... as nothing but tokens is kept.

But, when i see the following line, as i understand these token as a reference on the razor file provider.

    cacheEntryOptions.ExpirationTokens.Add(_fileProvider.Watch(normalizedPath));

**Comment by jtkech** [comment]
Oh yes, they only keep reference on the returned `IChangeToken`. Right?

**Comment by jtkech** [comment]
As a side note.

Not sure but maybe this also explains part of #992. `TheBlogTheme` is only composed of liquid views, even the `Layout.liquid`, which are triggered by custom `LiquidPage` razor views but they are all **precompiled** views.

`TheAgencyTheme` uses a main liquid template but it still uses a `Layout.cshtml` which i assume (without this fix) was re-compiled for each tenant.

**Comment by sebastienros** [comment]
992 can't be explained by it, it's raw throughput so everything is already warmed up, cache is filled and views are compiled.

**Comment by jtkech** [comment]
Oh yes sorry, so only checking rps on the same tenant, i was thinking about the test which starts many tenants.

**Pull request merged**
