### PR TITLE
Build SqlGrammer on top of Parlot

### LINKED ISSUE #8214: Build SQL Grammer on top of Parlot

### PR DESCRIPTION
**Pull request by hishamco**
Fixed #8214

### CODE REVIEW

**Comment by hishamco** [comment]
@sebastienros could you please push a NuGet package with the latest modifications that you made, coz I'm unable to use the identifier in the fluent APIs

**Comment by sebastienros** [comment]
https://github.com/sebastienros/parlot/releases/tag/v0.0.2

**Comment by sebastienros** [comment]
Take a look at this file for more examples: https://github.com/sebastienros/fluid/blob/sebros/parlot/Fluid/Parlot/ParlotParser.cs
It is the equivalent of the FluidGrammar file, the same way there is a SqlGrammar in OC.

**Comment by hishamco** [comment]
I already started to covert the parser to fluent APIs, I will push the updates now ...

Thanks for updating the NuGet package

**Comment by hishamco** [comment]
One more thing I forgot to mention `static` lamda is not supported in OC, the project shoud use C# 9.0

**Comment by Piedone** [comment]
Is this something you'd like to revisit any time soon @hishamco (given that this is a draft PR) or should we close?

**Comment by hishamco** [comment]
I added a new OSS a long time ago to parse SQL using Parlot, that is it took time to build AST. While Parlot doesn't have the primitives I just built them myself

So what do you suggest Seb?

**Comment by sebastienros** [comment]
Now I understand, I found your project. I think the AST is too abstract, it's just a tree on "Nodes" which need to be visited the same way as Irony, by checking strings. It should result in a syntax tree made of concrete nodes that can be visited, not with a set of switch/case. Looking at the source code it creates `SyntaxNode` for everything, it's very practical and performant. I may come back to you with a simple prototype that you can work on. I still think we can close the PR but keep the issue open.

**Comment by lampersky** [comment]
> Now I understand, I found your project. I think the AST is too abstract, it's just a tree on "Nodes" which need to be visited the same way as Irony, by checking strings. It should result in a syntax tree made of concrete nodes that can be visited, not with a set of switch/case. Looking at the source code it creates `SyntaxNode` for everything, it's very practical and performant. I may come back to you with a simple prototype that you can work on. I still think we can close the PR but keep the issue open.

I've implemented own SQLParser using Parlot and I used simpler approach than AST.
It is still a work in progress, because I've decided to extract some usefull parsers, they can be used to build parsers for other languages.

Those parsers are:
- **QuotedIdentifierParser** - which parses identifiers between given start and end symbols, it also handles escaped character, example identifiers which are parsed properly: ```[abcd], "hello\nworld", "this includes"" escaped", `backticks`, 'qwe rty'```,
- **ExtendedWhiteSpaceParser** - it is fully configurable white space and comments parser, you can define single or multi line comments, also it can detect not properly ended comments and allows comment nesting,
- **RegexParser** - this is built on top of `System.Text.RegularExpressions`,
- **CustomIdentifierParser** - this is a more generic version of builtin Identifier Parser, you can define allowed characters, I found that this builtin has some limitations.

All above implements ICompilable.

@sebastienros do you think those parsers could be a good candidates to extend Parlot? Or maybe better to create a dedicated project: "UsefulParlotParsers"? I'm curious about your thoughts.

Some screenshots:

image
image

**Comment by hishamco** [comment]
Seb, we might discuss that at the upcoming meeting if there's a possibility, I will close the PR then revisit it again

**Pull request closed without merging**
