### PR TITLE
Run preview_ci once a day

### LINKED ISSUE #15548: Daily preview package publish instead of on every commit to main
### Is your feature request related to a problem? Please describe.

On every commit to `main` (except for some ignored files) the [Preview - CI action](https://github.com/OrchardCMS/OrchardCore/actions/workflows/preview_ci.yml) will, among others, publish NuGet packages to the preview feed.

We store the preview package feed on [Cloudsmith](https://cloudsmith.io/~orchardcore/repos/preview/packages/). For this, Cloudsmith provides free hosting.

Previously, we could store GBs of packages (maybe up to 100 GB?) for 180 days. Cloudsmith will restrict this to 10k packages soon and we need to figure out how to adapt to this.

### Describe the solution you'd like
Instead of a publish on every push, we could have a single publish every day if there were new commits (i.e. a "nightly"). This is only for the package publish; we'd still have a CI build for every commit as of today.

Ideally, we could say to our users that the preview packages are guaranteed to be available for x days (while still recommending not to use them in production). While we won't be able to say exactly that, we could approximate: We publish 186 packages currently, so that's ~53 days of packages if we publish every day.

### Describe alternatives you've considered
We could clean up the oldest packages without downloads too. The [Cloudsmith CLI](https://pypi.org/project/cloudsmith-cli/) can be used to fetch this data (I guess its `metrics packages` command) and to delete packages (`delete`). However, this looks a bit too complex for this use case.

### PR DESCRIPTION
**Pull request by MikeAlhayek**
Fix #15548

### CODE REVIEW

**Comment by Piedone** [comment]
I started to work on this with a more complete solution: https://github.com/OrchardCMS/OrchardCore/compare/main...Lombiq:OrchardCore:issue/OCORE-151

**Comment by Piedone** [comment]
And now done: https://github.com/OrchardCMS/OrchardCore/pull/15552

**Comment by Piedone** [comment]
The dependent job instead of per-step checks is a good idea for less code, but it starts a separate VM just for that script. That seems wasteful for me.

Otherwise, I'd have loads of change requests to do things (in a way) that I've done. So if you're OK with it, I'd continue with that.

**Comment by MikeAlhayek** [comment]
I'll close this PR and let you finish it :)

**Comment by Piedone** [comment]
Thanks! I'm done there, actually.

Sorry about the wasted effort. Usually, I'm attentive enough to assign the issue, what I forgot this time, and you were too quick :).

**Comment by MikeAlhayek** [comment]
> Sorry about the wasted effort. 

Never waste. Always learn something while trying something new.

**Pull request closed without merging**
