### PR TITLE
Update ContentItemVersionId nullable in graphql

### PR DESCRIPTION
**Pull request by hyzx86**
In the me field, the user may check contentItemVersionId, but we don't assign a value to it.

```json
{
  "errors": [
    {
      "message": "Error trying to resolve field 'contentItemVersionId'.",
      "locations": [
        {
          "line": 4,
          "column": 7
        }
      ],
      "path": [
        "me",
        "testProfile2",
        "contentItemVersionId"
      ],
      "extensions": {
        "code": "INVALID_OPERATION",
        "codes": [
          "INVALID_OPERATION"
        ],
        "details": "GraphQL.Execution.UnhandledError: Error trying to resolve field 'contentItemVersionId'.\r\n ---> System.InvalidOperationException: Cannot return null for a non-null type. Field: contentItemVersionId, Type: String!.\r\n   at GraphQL.Execution.ExecutionStrategy.ValidateNodeResult(ExecutionContext context, ExecutionNode node) in /_/src/GraphQL/Execution/ExecutionStrategy.cs:line 635\r\n   at GraphQL.Execution.ExecutionStrategy.CompleteNodeAsync(ExecutionContext context, ExecutionNode node) in /_/src/GraphQL/Execution/ExecutionStrategy.cs:line 551\r\n   --- End of inner exception stack trace ---"
      }
    },
    {
      "message": "Error trying to resolve field 'contentItemVersionId'.",
      "locations": [
        {
          "line": 9,
          "column": 7
        }
      ],
      "path": [
        "me",
        "testUserProfile",
        "contentItemVersionId"
      ],
      "extensions": {
        "code": "INVALID_OPERATION",
        "codes": [
          "INVALID_OPERATION"
        ],
        "details": "GraphQL.Execution.UnhandledError: Error trying to resolve field 'contentItemVersionId'.\r\n ---> System.InvalidOperationException: Cannot return null for a non-null type. Field: contentItemVersionId, Type: String!.\r\n   at GraphQL.Execution.ExecutionStrategy.ValidateNodeResult(ExecutionContext context, ExecutionNode node) in /_/src/GraphQL/Execution/ExecutionStrategy.cs:line 635\r\n   at GraphQL.Execution.ExecutionStrategy.CompleteNodeAsync(ExecutionContext context, ExecutionNode node) in /_/src/GraphQL/Execution/ExecutionStrategy.cs:line 551\r\n   --- End of inner exception stack trace ---"
      }
    },
    {
      "message": "Error trying to resolve field 'render'.",
      "locations": [
        {
          "line": 11,
          "column": 7
        }
      ],
      "path": [
        "me",
        "testUserProfile",
        "render"
      ],
      "extensions": {
        "code": "INVALID_OPERATION",
        "codes": [
          "INVALID_OPERATION"
        ],
        "details": "GraphQL.Execution.UnhandledError: Error trying to resolve field 'render'.\r\n ---> System.InvalidOperationException: The model item passed into the ViewDataDictionary is of type 'OrchardCore.DisplayManagement.Zones.ZoneHolding', but this ViewDataDictionary instance requires a model item of type 'OrchardCore.Users.ViewModels.CustomUserSettingsEditViewModel'.\r\n   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary..ctor(ViewDataDictionary source, Object model, Type declaredModelType)\r\n   at lambda_method702(Closure, ViewDataDictionary)\r\n   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)\r\n   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)\r\n   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)\r\n   at OrchardCore.DisplayManagement.Razor.RazorShapeTemplateViewEngine.RenderViewToStringAsync(String viewName, Object model, IViewEngine viewEngine) in D:\\SourceCodes\\JZSoft\\EasyOC.OrchardCore\\OrchardCore\\src\\OrchardCore\\OrchardCore.DisplayManagement\\Razor\\RazorShapeTemplateViewEngine.cs:line 123\r\n   at OrchardCore.DisplayManagement.Razor.RazorShapeTemplateViewEngine.RenderRazorViewAsync(String viewName, DisplayContext displayContext) in D:\\SourceCodes\\JZSoft\\EasyOC.OrchardCore\\OrchardCore\\src\\OrchardCore\\OrchardCore.DisplayManagement\\Razor\\RazorShapeTemplateViewEngine.cs:line 97\r\n   at OrchardCore.DisplayManagement.Implementation.DefaultHtmlDisplay.<ProcessAsync>g__Awaited|13_0(Task`1 task) in D:\\SourceCodes\\JZSoft\\EasyOC.OrchardCore\\OrchardCore\\src\\OrchardCore\\OrchardCore.DisplayManagement\\Implementation\\DefaultHtmlDisplay.cs:line 300\r\n   at OrchardCore.DisplayManagement.Implementation.DefaultHtmlDisplay.ExecuteAsync(DisplayContext context) in D:\\SourceCodes\\JZSoft\\EasyOC.OrchardCore\\OrchardCore\\src\\OrchardCore\\OrchardCore.DisplayManagement\\Implementation\\DefaultHtmlDisplay.cs:line 135\r\n   at OrchardCore.DisplayManagement.Implementation.DefaultHtmlDisplay.ExecuteAsync(DisplayContext context) in D:\\SourceCodes\\JZSoft\\EasyOC.OrchardCore\\OrchardCore\\src\\OrchardCore\\OrchardCore.DisplayManagement\\Implementation\\DefaultHtmlDisplay.cs:line 189\r\n   at OrchardCore.ContentManagement.GraphQL.Queries.Types.ContentItemType.RenderShapeAsync(IResolveFieldContext`1 context) in D:\\SourceCodes\\JZSoft\\EasyOC.OrchardCore\\OrchardCore\\src\\OrchardCore\\OrchardCore.ContentManagement.GraphQL\\Queries\\Types\\ContentItemType.cs:line 74\r\n   at GraphQL.Resolvers.FuncFieldResolver`2.<>c__DisplayClass3_0.<<-ctor>b__1>d.MoveNext() in /_/src/GraphQL/Resolvers/FuncFieldResolver.cs:line 70\r\n--- End of stack trace from previous location ---\r\n   at GraphQL.Execution.ExecutionStrategy.ExecuteNodeAsync(ExecutionContext context, ExecutionNode node) in /_/src/GraphQL/Execution/ExecutionStrategy.cs:line 472\r\n   --- End of inner exception stack trace ---"
      }
    }
  ],
  "data": {
    "me": {
      "testProfile2": null,
      "testUserProfile": null
    }
  }
}
```

### CODE REVIEW

**Comment by hyzx86** [comment]
image

**Comment by Piedone** [comment]
How do you get to this point, what's `testProfile2`?

**Comment by hyzx86** [comment]
> How do you get to this point, what's `testProfile2`?

Ha, in case you haven't noticed, OC's graphql Api already supports `me` fields https://github.com/OrchardCMS/OrchardCore/pull/15215, 
and me fields also support linking types with a Stereotype of `CustomUserSettings` here

**Comment by Piedone** [comment]
Yeah, but what exactly is `testProfile2`? A `CustomSettings` content item? Please share an export file or reproduction steps.

**Comment by Piedone** [comment]
Thanks! I did this, but BTW since there's nothing from these content types in the user editor, nothing was saved to them:

image

And, expectedly `userProfile` and `userProfile2` are `null`:

image

How exactly did you save content to them?

**Comment by hyzx86** [comment]
> How exactly did you save content to them?
Have you enable the `Custom User Settings` featrue?

**Comment by hyzx86** [comment]
Because you haven't enabled the "Custom User Settings" feature, the user information page doesn't display these panels, but when you do enable it, you'll be able to see these panels, and the display driver will automatically handle the save logic, 
but it won't assign a value to the `ContentItemVersinId` property of the `ContentItem`.

**Review by Piedone — APPROVED** [review]
Ah, of course, I see. Looks good, then!

**Comment by sebastienros** [comment]
Why not assign a new id to it then and let it non-nullable?

**Pull request merged**
