### PR TITLE
Fix invalid SRI hashes

### PR DESCRIPTION
**Pull request by hishamco**

### CODE REVIEW

**Comment by hishamco** [comment]
@agriffard can we merge this?

**Comment by sebastienros** [comment]
Any reason to change from sha512 to sha384?

**Comment by hishamco** [comment]
We always use sha384, @agriffard correct me if I'm wrong

**Comment by hishamco** [comment]
@agriffard your thought?

**Comment by MikeAlhayek** [comment]
@hishamco is this still needed? If not, please close it

**Comment by hishamco** [comment]
Ya, I need to revise some of my old PRs, the issue in this one is the PR takes so long during the execution in GitHub workflow, still need to find better way

**Comment by hishamco** [comment]
Seems I confused with other PR, let me check tomorrow from my laptop instead

**Comment by hishamco** [comment]
@agriffard I remembered that you are using SHA-384 for all the resources, except the one I fixed using https://www.srihash.org/

**Review by sebastienros — APPROVED** [review]

**Comment by sebastienros** [comment]
I changed the title of the commit

**Pull request merged**
