### PR TITLE
Fix localization accessors names

### PR DESCRIPTION
**Pull request by hishamco**
- Localization accessor conventions
- Remove unnecessary localizers
- Fix localizers generic types

@jtkech please merge if you don't have any comments

@agriffard is there a docs describing what are the conventions are used to get translations generated from `PoExtractor` in the docs? If not this a reminder for us

### CODE REVIEW

**Comment by jtkech** [comment]
@hishamco happy new year ;)

    Controllers/AdminController.cs(363,37): error CS0103: The name 'TH' does not exist in the current context [/Users/travis/build/OrchardCMS/OrchardCore/src/OrchardCore.Modules/OrchardCore.Users/OrchardCore.Users.csproj]
    Controllers/AdminController.cs(164,37): error CS0103: The name 'TH' does not exist in the current context [/Users/travis/build/OrchardCMS/OrchardCore/src/OrchardCore.Modules/OrchardCore.Roles/OrchardCore.Roles.csproj]
    0 Warning(s)
    2 Error(s)

**Comment by hishamco** [comment]
I just fixed them, don't blame me, I used VS Code, coz VS slow down my laptop :)

Just a sec

**Comment by hishamco** [comment]
Happy new year @jtkech 😄

**Comment by sebastienros** [comment]
The question is why do that?

We have always used `T` historically, as in "Translate". Since dotnet core there are two services, but when there is no ambiguity why not keep it?

**Comment by hishamco** [comment]
We are using `T` in the views, few months ago we agreed with @jktech to unify the names, before there was many `T`, `S`, `H`, `TS` and `TH` so to avoid the confusion we choose `S` for `IStringLocalizer` and `H` for `IHtmlLocalizer`

I will try to refer to the old pr if I find it

**Comment by hishamco** [comment]
https://github.com/OrchardCMS/OrchardCore/pull/4750

**Comment by sebastienros** [comment]
Ok, I am satisfied with the explanation, thanks

**Comment by hishamco** [comment]
FYI I did a PR in PoExtractor to reflect the changes, also I may to add some other PRs to support other cases that aren't covered by the tool now

**Pull request merged**
