### PR TITLE
Set listpart property in listpartviewmodel

### LINKED ISSUE #15558: ListPart DisplayDriver does not set ListPart property on ListPartViewModel
You cannot access list part from ListPart.liquid template

### PR DESCRIPTION
**Pull request by aliamiras**
Set list part when displaying the shape.
Extend console_log to support ContentPart.
closes #15558

### CODE REVIEW

**Comment by aliamiras** [comment]
@dotnet-policy-service agree

**Comment by hishamco** [comment]
@MichaelPetrinolis your review please

**Review by sebastienros — APPROVED** [review]

**Review by MichaelPetrinolis — APPROVED** [review]

**Review by MichaelPetrinolis — APPROVED** [review]

**Comment by hishamco** [comment]
@all-contributors please add @aliamiras for code.

**Comment by hishamco** [comment]
@Piedone why the bot create a new PR instead of adding an entry in the same PR?

**Comment by Piedone** [comment]
You have to ask their developers about the decision behind this, but that's the only way it can work. See https://allcontributors.org/docs/en/bot/configuration.

**Comment by hishamco** [comment]
Thank you for your contributions, and congrats on your first one!

**Pull request merged**
