### PR TITLE
Fix localizer type in tenants ApiController

### PR DESCRIPTION
**Pull request by hishamco**

### CODE REVIEW

**Comment by hishamco** [comment]
@Piedone I remember that you mentioned long time before that we need sort of analyzer, indeed this one of the common cases that we need such analyzer, if it will take long time here we can add it to Lombiq Analyzer

**Comment by Piedone** [comment]
Thank you, made a note of this here: https://github.com/Lombiq/.NET-Analyzers/issues/15 There's no such analyzer currently, unfortunately.

**Comment by hishamco** [comment]
I can contribute to this one

**Comment by Piedone** [comment]
Really? That would be awesome, actually!

**Comment by hishamco** [comment]
I will add your link in my list of this month, hope to have a look soon

**Pull request merged**
