### PR TITLE
Added missing transaction commit

### PR DESCRIPTION
**Pull request by mariojsnunes**
Try fix to #8466
Another possible option would be to remove the transaction as it's only a Query. But I'm not sure about it...

### CODE REVIEW

**Comment by jtkech** [comment]
> Another possible option would be to remove the transaction as it's only a Query. But I'm not sure about it...

We added it through #4698 to fix a db locking issue #4669

Not sure we need a transaction commit as we are only reading and the transaction is disposed at the end of the using block, but if we need it we could use `await transaction.CommitAsync()`

One thing i noticed in the trace of your original issue, is that `CommitTransactionAsync()` is called twice.

Need more thinkings, i will let you know

**Comment by mariojsnunes** [comment]
I've updated the PR if you think it will do no harm, I could test if it solves.
Please tell me if I can help in any way.

**Comment by jtkech** [comment]
@mariojsnunes 

> I've updated the PR if you think it will do no harm

Thanks for the async call, and also the `await using` ;)

> I could test if it solves.

Yes please

As commented in your issue, can you check if it was working with an older OrchardCore version, e.g. one month ago.

**Comment by mariojsnunes** [comment]
Since it was found not to be the cause of the issue, should I close this?

**Comment by jtkech** [comment]
@mariojsnunes Okay cool, so i close it

**Pull request closed without merging**
