### PR TITLE
Distributed services. Only kept to re-use some code

### PR DESCRIPTION
**Pull request by jtkech**
So, as a first step, i revisited in `SiteService` the usage of memory cache and its change token.

- Currently the change token is not used to invalidate the cache. It is used by `SiteService` to signal that it has updated the site settings. This is used by `HomePageRoute` which holds the token and checks it.

Then, thinking about some future distributed events, where an instance would have to not react on its own distributed events and so on, and which could be used to invalidate local caches.

- Here we also use the token as an expiration token when setting the cache.

- We still do `SignalToken()` but just before to not invalidate the cache immediately, and if a distributed event has already canceled the token, `SignalToken()` will just do nothing.

- Note: We could think about a distributed `SignalToken()` which also sends a distributed event if the token is still in the dictionary. This to work locally as before, and if already canceled and removed by a distributed event, meaning that the local instance is not the initiator, `SignalToken()` will do nothing.

- Beyond these changes i only kept the `SignalToken()` called when site settings are updated, the other ones seem to me useless. But need to be reviewed.

- I checked that it works locally as before, then i simulated a distributed event which cancels the token through a background task.

Note: now updating **site settings** reload the tenant, so local token cancellation is no more useful, and we will need to listen to a distributed tenant restart. That said i also did my tests without reloading the tenant.

So, if this pattern could be ok.

- I could update other places which use memory cache as `SiteService`, e.g `TemplatesManager` to cache templates. Right now i will also use this pattern for caching background task settings to not be blocked on #1572 related to the `hostedService` branch.

- There are places where we use `IDistributedCache` which, to be really distributed, rely on things as `Redis`. And maybe (but not sure), using distributed events to invalidate local caches will need the same things. But among this, is it okay to allow the 2 ways or do we want to recommend one of them?

Finally, i tried a quite simple distributed lock without using `Redis` or `Sql Server`, but not sure we can do the same with distributed events, unless we allow some latency for some broadcast events ...

### CODE REVIEW

**Comment by jtkech** [comment]
First summary of what i did and **needs to be reviewed**.

- Fixes #2432, here a copy of the end of my last comment in this issue.

    > There is still an issue when using known values variations. The context is also cached and used to compute the final key of the cached value, but in this case different contexts can have the same `CacheId` but not the same key returned by `GetCacheKey()`. So, to not mix them we need to use the actual context to compute the final key, not the one retrieved from the cache.

- Fixes #2433 related to lucene writer locking issues when running multiple instances.

    > `LuceneIndexManager` is a tenant singleton and hold a lock which can't be shared between instances. The `Write()` method has a `close` parameter which is set to false by default. So, a quick workaround was to use `Write(...., close: true)`.

- Then, as a first distributed service, i added a `Distributed cache implementation using Redis.` I used docker + redis + 2 instances of our web app, and added this for testing in `Content-Article.liquid`.

      {% assign cacheDependency = "contentitemid:" | append: Model.ContentItem.ContentItemId %}

      {% cache "article", dependencies: cacheDependency  %}
          <h3>Cache testing: {{ "now" | date: "%Y-%m-%d %H:%M:%S" }}</h3>
      {% endcache %}

    Then, i checked that, after publishing an item, both instances keep synchronized.

- To have this result, i also need to fix another issue. Here the related comments i added.

      // Even this instance has removed or never set the cached value, here we may get
      // a cached value from another instance and before this instance was able to set
      // or refresh the cache itself, and then before tagging the cache keys locally.

**Comment by jtkech** [comment]
@sebastienros 

- So, i opened some separate issues / PRs related to some points that need to be discussed.

- So, now i have a working beta version which use a **redis `IDistributedCache`** and also a redis implementation of a **distributed `ISignal`**.

- By using a database template using a cache tag, i checked that invalidating the cache or updating the template from one instance is propagated to another instance when rendering the shape.

- In fact, i started with `ServiceStack` but it is less flexible and doesn't use the same config objetcs. And there seems to be a problem of commercial license, **so now i only work with `StackExchange.Redis`**.

- `ServiceStack` was good for its distributed locking, but i think i can make a mix with `StackExchange` for connecting to redis while taking inspiration from `ServiceStack` for the locking logic.

Note: Oh yes, what i saw for redis pub sub is that for a given subscriber there is a kind of listener doing a kind of "pooling". It reminded me when i was trying to do the same but not on a memory database ;)

- Finally, i had a circular dependency issue. `Redis distributed ISignal` injects `ISiteService` to resolve redis settings, and `ISiteService` injects `ISignal`. I solved it by not injecting `ISiteService` and resolve it through an `IHttpContextAccessor` in a shell `Activated` event, not in the constructor.

---

**Little question**

- I have a base module `OC.Distributed` which have features implementing some services using redis. Do i need to create a separate redis module to reference `StackExchange.Redis`, or is it okay?

- Idem, is it okay that e.g `OC.Abstractions` references `StackExchange.Redis`? Or do i need to create a separate abstractions project?

**Comment by jtkech** [comment]
**Beta versions of**

- IDistributedCache using Redis.
- IMessageBus using Redis.
- Distributed ISignal.
- Distributed Shell.

**Todo**

- Distributed Lock.
- Make message bus Publish() and Subscribe() async. **<= Done**.
- Make SignalToken() async to fully use PublishAsync().
- Update other usages of MemoryCache / Tokens as done for SiteService & TemplateManager.

**Refactoring**

- See if okay to reference `Microsoft.Extensions.Caching.Redis` in a generic module or `OrchardCore` or `OC.Abstractions`. Or better to have a dedicated module and / or core library.

- Right now redis configuration is done through site settings which implies a reference on `OC.DisplayManagement`. Is it okay?

**Comment by jtkech** [comment]
@sebastienros i committed some first updates after your review.
I will comment them tomorrow, to be continued.

**Comment by jtkech** [comment]
@sebastienros 

- In some places to sync tenants we still need to load the last updated settings. So, i added and tried this method, in `IShellSettingsManager`, which loads settings **but only for a given tenant**.

      bool TryLoadSettings(string name, out ShellSettings settings)

    Let me know if it make sense and, if so, if better to do a separate PR.

**Comment by jtkech** [comment]
@sebastienros 

I made good progress.

- Distributed tag cache so that when a view is rendered by one instance, items are also tagged on another instance even it has not yet rendered the view.

- And other things, e.g while doing a setup / recipe, subsequent requests on this tenant and on the same instance are not served, this is now true also for requests on this tenant but on other instances.

- Distributed Data Protection: ATM i'm lost ;)

- Lucene locking issues: One 1st idea would be to check, per tenant, if the directory is already locked (easy to do), and then let the instance which own the lock doing things (e.g bg task). And then, when e.g publishing an item, if not the owner of the lock, use the message bus to inform the owner.

**Comment by sebastienros** [comment]
Open Skype

**Comment by jtkech** [comment]
Just for infos.

- I did some tests by mixing instances that share or not their shells container location. Seems to work well, even for tenant setups after having fixed some issues when `Setting.txt` is updated concurrently.

- The only issue i had, when using the blog setup / recipe, is related to the `ContentDefinition.json` file which is missing on the instances which don't share the same location. After the distributed command, to make it working we just have to copy paste this file in the other shells container locations.

- I understand the dev scenario which needs this and which implies to 1st dispatch this file, but it is not distributed as we would want in another scenario. So i will not try to fix any issue around this, just to say that maybe better to not add this as a default feature in our recipe.

**Comment by sebastienros** [comment]
The `ContentDefinition.json` is only for single instance systems. For distributed then users should use the Database one. So it's working as expected, by design.

**Comment by jtkech** [comment]
Okay cool. Do we keep it by default in our recipes?

**Comment by jtkech** [comment]
@sebastienros 

Here a summary of the features that can be used to discuss if we need or not a redis config per tenant, a connection per tenant and / or per service, if too many features and more services can be grouped ...

- `OC.Distributed.Redis.Redis`: `Allows to configure and connect to Redis.` Per tenant feature, per tenant redis client configuration used by a **per tenant redis client**.

- `OC.Distributed.Redis.Shell`: `Distributed Shell using a Message bus.` `DefaultTenantOnly` feature, uses the **default tenant redis client connection**.

- `OC.Distributed.Redis.Cache`: `Distributed cache using Redis.` Per tenant feature, also registers `RedisTagCache`, per tenant redis configuration **but uses its own connection**.

- `OC.Distributed.Redis.Signal`: `Distributed Signal using a Message bus.` Per tenant feature, uses the tenant client connection.

- `OC.Distributed.Redis.Lock`: `Distributed Lock using Redis.` Idem.

- `OC.Distributed.Redis.DataProtection`: `Distributed DataProtection key storage using Redis.`  Idem.

**Comment by carlwoodhouse** [comment]
Just a note on distributed stuff, correct me if im wrong or its fixed here (i cant see that it is)

Atm autoroute will not work well on distributed environments as IAutorouteEntries is onyl populated on startup and then modified as new routes are added/deleted by the instance, meaning other instances in a distributed enviornment wouldn't get the updates. Pretty fundamental part we need to implement imo. (I think o1 got round it by updating its aliasholder on a bg thread every 1 min if new aliases where added, dunno that i was ever a fan of that ;P)

**Comment by jtkech** [comment]
Okay, i think i missed this, thanks for the info, it is noted.

**Comment by jtkech** [comment]
I long for reworking on this.

- I thing i will review every feature based on the experience i had working on shell configurations, shell scope async values, the new endpoint routing system for 3.0 and so on.

- Not urgent for me but i prefer to wait for some of my other pending PRs that may be helpful and to not redo things.

 - The best would be to rework on it **after the migration to 3.0** because of the new routing system, to not redo things, but i don't know if 3.0 will be released soon.

**Comment by jtkech** [comment]
- Maybe it would have been good to do intermediate PRs e.g for the usage of a local `MemoryCache` so that it can be invalidated in a distributed env. So that, even this PR is not ready, new PRs will be aware of this and we will not have to update them.

- More globally, maybe we will be able to define a few rules so that new PRs are aware of multi tenancy, distributed env, working under a virtual folder and so on. For the virtual folder can be easily tested by using a `MapGet("virtualFolder", ...)`.

**Comment by Piedone** [comment]
Isn't https://github.com/OrchardCMS/OrchardCore/pull/5249 and https://github.com/OrchardCMS/OrchardCore/pull/5815 superseding this PR @jtkech ?

**Comment by jtkech** [comment]
Yes exactly ;) And I kept this branch to re-use some code that i need to update.

E.g with what has been done around shell configuration, and also because the caching pattern will change, currently we use the signal service (that could be distributed) to invalidate local caches, but we will use instead a pattern based on `IDistributedCache`.

**Comment by Piedone** [comment]
Ah OK then, thank you. Very important work BTW, thank you for doing it!

**Comment by jtkech** [comment]
Okay, it's time to close this one ;)

**Pull request closed without merging**
