### PR TITLE
Update OpenIddict to 4.0 preview1

### PR DESCRIPTION
**Pull request by hishamco**
https://kevinchalet.com/2022/06/22/openiddict-4-0-preview1-is-out/

### CODE REVIEW

**Comment by kevinchalet** [comment]
Thanks for your kind words, Hisham 😃

**Comment by hishamco** [comment]
BTW is there a section for breaking changes in OpenIddict?

**Comment by hishamco** [comment]
I though there is a section in the repo, thanks anyway

**Comment by kevinchalet** [comment]
Hey @hishamco,

As 4.0 RTM is approaching, I opened https://github.com/OrchardCMS/OrchardCore/pull/12804 to start testing it with Orchard. Don't hesitate if you have any suggestion/remark 😃 

Cheers.

**Pull request closed without merging**
