### PR TITLE
Use is operator for null check instead of ==

### PR DESCRIPTION
**Pull request by hishamco**
Enhance readability and reduces the chance of null-related bugs

### CODE REVIEW

**Review by Piedone — CHANGES_REQUESTED** [review]
Oh no. Why change 800 files for this? :) I had some discussion with somebody for a line changed somewhere under a PR, but that's one thing, changing every instance in the codebase is another ballpark.

What's the benefit, exactly? How does it enhances readability and reduces the change of null-related bugs? Is `dashboardFeature is null` _really_ more readable than `dashboardFeature == null` when we use `==` and `!=` for every other equality check, and have all C-type languages since the dawn of time? Can you provide some evidence of the benefit?

Pattern matching is great, but there is no "pattern" here to match. All these changes are just literal `==` -> `is` and `!=` -> `is not` changes (and FWIW, I've seen actual use cases for pattern matching missed in there where the expression was longer).

**Comment by hishamco** [comment]
>  I had some discussion with somebody for a line changed somewhere under a PR, but that's one thing, changing every instance in the codebase is another ballpark.

Go for it :)

**Comment by hishamco** [comment]
>  All these changes are just literal == -> is and != -> is not changes

is and is not much readable & cleaner for `null` equality nothing else

**Comment by Piedone** [comment]
Please reply to this:

> How does it enhances readability and reduces the change of null-related bugs? Is `dashboardFeature is null` _really_ more readable than `dashboardFeature == null` when we use `==` and `!=` for every other equality check, and have all C-type languages since the dawn of time? Can you provide some evidence of the benefit?

**Comment by hishamco** [comment]
To be honest, the JIT ASM for both are the same, but for the readers `is null` more readable than `==`, maybe I'm a VB guy :) there's no example in mind right now, but I might think about one

**Comment by Piedone** [comment]
Maybe you should be more of a C# guy ;).

**Comment by hishamco** [comment]
Have a look at the examples below:

```csharp
int i = 1;
if (i is null)
{
    Console.WriteLine("i is null");
}
```

this will not compile because `i` is non-nullable, while in the second example

```csharp
int i = 1;
if (i == null)
{
    Console.WriteLine("i is null");
}
```

it will compile and the condition is `false`

Think for this and you will know what I mean :)

**Comment by Piedone** [comment]
That's a good point, but since this PR compiles, it doesn't apply to any of the changes in it. The second example also emits this warning BTW, that in our case still breaks the build: https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs0472?f1url=%3FappId%3Droslyn%26k%3Dk(CS0472)

**Comment by hishamco** [comment]
> that in our case still breaks the build

I didn't understand which build had been broken.

**Comment by Piedone** [comment]
If you write the second example, it causes a build warning. This will fail the CI build.

**Comment by MikeAlhayek** [comment]
@hishamco I also agree that this isn't needed. 

Also today @sebastienros said this isn't needed. Maybe we should not then?

**Comment by hishamco** [comment]
No problem, we could close it then :)

**Pull request closed without merging**
