### PR TITLE
Remove closing tags from <input> self-closing element

### PR DESCRIPTION
**Pull request by MichaelPetrinolis**

### CODE REVIEW

**Comment by sebastienros** [comment]
Not self-closing either?

**Comment by MichaelPetrinolis** [comment]
oops...

**Comment by sebastienros** [comment]
Can I merge or should I wait for more changes?

**Comment by MichaelPetrinolis** [comment]
Yes merge please, just a small PR to remove HTML1512: Unmatched end tag warnings.

**Pull request merged**
