### PR TITLE
Trumbowyg 2.25.2 - added icons missing icons to OrchardCore.Resources and reworked some tasks

### LINKED ISSUE #11985: Trumbowyg missing icons
### Discussed in https://github.com/OrchardCMS/OrchardCore/discussions/11979

<div type='discussions-op-text'>

<sup>Originally posted by **kevinsmgov** July  9, 2022</sup>
When I add "indent" and "outdent" buttons to the Trumbowyg configuration, the buttons appear and function in the bar but there are no icons in them (they are blank). Does anyone know what additional configuration in necessary to make the icons show in the buttons?</div>

### PR DESCRIPTION
**Pull request by PiemP**
resolves #11985, #11979

- added single icons from Trumbowyg 2.25.2 sources
- added a task in the main gulpfile to biuld svg that allow to put lot of svg in one file and minify it
- renamed the main trumbowyg icons file to better understand the relationship between this svg file and trumbowyg
- added icon for shortcode plugin
- added trumbowyg language files

### CODE REVIEW

**Comment by PiemP** [comment]
I have noticed something...the Resources system load main trumbowyg javascript source file from the `node_module` folder, but the source files related to the plugins and the stylesheets are loaded from the `Assets` folder. Have I to fix that or is ok?

At this moment I can't use the `icons.svg` file generated when build the trumbowyg sources because the gulp script doesn't allow me to import it and I don't know why.

**Comment by agriffard** [comment]
Trumbowyg latest version is: https://www.npmjs.com/package/trumbowyg/v/2.25.2

Can you please attach some screenshots and some examples of using specific icons/language?

**Comment by PiemP** [comment]
icon fixed and added (shortcode, indent, outdent):
icon fixed

Language italian:
lang_italian

Language english: 
lang_eng

Tested by enable `Localization` and `Content Language Header` features.

I proceed to update trumbo src to the latest version.

**Comment by Piedone** [comment]
I sincerely apologize for us taking so much time here. I checked out the PR, going over old ones, and this would be quite useful, but is now quite outdated with the rest of the codebase.

Is this something you'd like to revisit any time soon @PiemP or should we close?

**Comment by PiemP** [comment]
I have to check if the issue related to this PR are already done by other updates... is a really old PR... the most one that interest me is about the translations of the trumbowyg commands... but at this moment I don't have time to check if in the last version of OC are all ok about this... close it please

**Comment by Piedone** [comment]
OK, sorry about that.

**Pull request closed without merging**
