### PR TITLE
Rename BodyPart to HtmlBodyPart

### LINKED ISSUE #365: Renaming BodyPart
Should we rename `BodyPart` to `HtmlBodyPart` as we will also have a `MarkdownBodyPart` and a layout oriented body part. Any body part is a part that provide a `BodyAspect` value. An `HtmlBodyPart` is a body part that stores its content in HTML and provides an HTML editor.

### PR DESCRIPTION
**Pull request by agriffard**
Fixes #365 

I only changed the name of the part and the corresponding files, documentation and alternates.
I didn't change the name of the module or the property called `Body`.

Breaking change: BodyPart is renamed HtmlBodyPart in recipes.
Previously created site with BodyPart could not be able to edit anymore a BodyPart, unless they change the content types that use it and the content part in the database.

### CODE REVIEW

**Comment by sebastienros** [comment]
I'd like that we find something consistent for Html and Markdown.
We have a Markdown part and an HtmlBody part now. I think we should either have
- Markdown and Html parts
- MarkdownBody and HtmlBody parts

Same consistency for the modules, and for this a different decision is possible too, like using MarkdownBody part in a module named Markdown.

Also consistency in the property name: Body vs Html/Markdown.

**Comment by agriffard** [comment]
Ok, changes taken into account:
Rename `OrchardCore.Body` to `OrchardCore.Html` and MarkdownPart to MarkdownBodyPart.

Will require many tests on all recipes, setup, ...

In an existing database, in the Document table, you need to :
- Rename `OrchardCore.Body` to `OrchardCore.Html` in OrchardCore.Environment.Shell.Descriptor.Models.ShellDescriptor, OrchardCore.Environment.Shell.Abstractions
- Rename `OrchardCore.Body` to `OrchardCore.Html` in OrchardCore.Environment.Shell.State.ShellState, OrchardCore.Environment.Shell.Abstractions
- Rename `OrchardCore.Body` to `OrchardCore.Html` in OrchardCore.Data.Migration.Records.DataMigrationRecord, OrchardCore.Data
- Rename `BodyPart` to `HtmlBodyPart` and `MarkdownPart` to `MarkdownBodyPart` in OrchardCore.ContentManagement.Metadata.Records.ContentDefinitionRecord, OrchardCore.ContentManagement.Abstractions

**Comment by agriffard** [comment]
Media-HtmlBody.Wrapper.cshtml and Media-MarkdownBody.Wrapper.cshtml are different:

```
@if (!Context.Items.ContainsKey("Media_Modal__HtmlBody"))
{
    Context.Items["Media_Modal__HtmlBody"] = new object();
    @await DisplayAsync(await New.Media_Modal__HtmlBody())
}
```

```
@if (!Context.Items.ContainsKey("Media_Wrapper__MarkdownBody"))
{
    Context.Items["Media_Wrapper__MarkdownBody"] = new object();
    @await DisplayAsync(await New.Media_Modal__MarkdownBody())
}
```

Which one is correct?

**Comment by sebastienros** [comment]
What is the issue with them being different?

**Comment by agriffard** [comment]
I was wondering why one checks
`ContainsKey("Media_Modal__`
and the other checks
`ContainsKey("Media_Wrapper__`

**Comment by sebastienros** [comment]
Yes you are right, it's not technically an issue but we should use the same keys, and have this:

```
@if (!Context.Items.ContainsKey("Media_Modal__MarkdownBody"))
{
    Context.Items["Media_Modal__MarkdownBody"] = new object();
    @await DisplayAsync(await New.Media_Modal__MarkdownBody())
}
```

**Comment by sebastienros** [comment]
The goal is that during a single request, only one call to this shape is done on a page. So we add an object to the global request items as a marker.

**Comment by Jetski5822** [comment]
this looks weird
```
@if (!Context.Items.ContainsKey("Media_Modal__MarkdownBody"))
{
    Context.Items["Media_Modal__MarkdownBody"] = new object();
    @await DisplayAsync(await New.Media_Modal__MarkdownBody())
}
```

Cant we have something that says... HasShape("name") and SetShape?

**Comment by sebastienros** [comment]
@Jetski5822 meh, it's very specific to this module. If we reuse this pattern maybe.

**Comment by Skrypt** [comment]
Here is a quick SQL migration

```SQL

--UPDATES Module definitions
UPDATE Document SET Content = REPLACE(content, 'OrchardCore.Body', 'OrchardCore.Html') 
WHERE Type = 'OrchardCore.Environment.Shell.Descriptor.Models.ShellDescriptor, OrchardCore.Environment.Shell.Abstractions';

UPDATE Document SET Content = REPLACE(content, 'OrchardCore.Body', 'OrchardCore.Html') 
WHERE Type = 'OrchardCore.Environment.Shell.State.ShellState, OrchardCore.Environment.Shell.Abstractions';


--UPDATES migrations
UPDATE Document SET Content = REPLACE(content, 'OrchardCore.Body.Migrations', 'OrchardCore.Html.Migrations') 
WHERE Type = 'OrchardCore.Data.Migration.Records.DataMigrationRecord, OrchardCore.Data';


--UPDATES Content Type definitions
UPDATE Document SET Content = REPLACE(content, 'BodyPart', 'HtmlBodyPart') 
WHERE Type = 'OrchardCore.ContentManagement.Metadata.Records.ContentDefinitionRecord, OrchardCore.ContentManagement.Abstractions';

UPDATE Document SET Content = REPLACE(content, 'MarkdownPart', 'MarkdownBodyPart') 
WHERE Type = 'OrchardCore.ContentManagement.Metadata.Records.ContentDefinitionRecord, OrchardCore.ContentManagement.Abstractions';


--UPDATES content items
UPDATE Document SET Content = REPLACE(content, 'BodyPart', 'HtmlBodyPart') 
WHERE Type = 'OrchardCore.ContentManagement.ContentItem, OrchardCore.ContentManagement.Abstractions';

UPDATE Document SET Content = REPLACE(content, 'MarkdownPart', 'MarkdownBodyPart') 
WHERE Type = 'OrchardCore.ContentManagement.ContentItem, OrchardCore.ContentManagement.Abstractions';

UPDATE Document SET Content = REPLACE(content, '{"Body"', '{"Html"') 
WHERE Type = 'OrchardCore.ContentManagement.ContentItem, OrchardCore.ContentManagement.Abstractions';

```

**Pull request merged**
