### PR TITLE
Replace ".Modules" to "Areas"

### LINKED ISSUE #1921: Can't find application start page
Hi,
It seems that the last changes have broken application pages localization. My home page located in App/Areas/Framework/Views/Home/Index.cshtml is not found anymore. This was working well Friday but breaks now with the following message :

```
An unhandled exception occurred while processing the request.
InvalidOperationException: The view 'Index' was not found. The following locations were searched:
/.Modules/InspiniaTheme/Views/Framework/Home/Index.cshtml
/.Modules/InspiniaTheme/Views/Framework/Shared/Index.cshtml
/.Modules/InspiniaTheme/Views/Shared/Index.cshtml
/.Modules/Framework/Views/Home/Index.cshtml
/.Modules/Framework/Views/Shared/Index.cshtml
/Areas/Framework/Views/Home/Index.en-US.cshtml
/Areas/Framework/Views/Home/Index.en.cshtml
/Areas/Framework/Views/Home/Index.cshtml
/Areas/Framework/Views/Shared/Index.en-US.cshtml
/Areas/Framework/Views/Shared/Index.en.cshtml
/Areas/Framework/Views/Shared/Index.cshtml
/Views/Shared/Index.en-US.cshtml
/Views/Shared/Index.en.cshtml
/Views/Shared/Index.cshtml
Microsoft.AspNetCore.Mvc.ViewEngines.ViewEngineResult.EnsureSuccessful(IEnumerable<string> originalLocations)

```
Regards,

### PR DESCRIPTION
**Pull request by jtkech**
Beautiful ;)

Fixes #1921, #2385 and replace #2386. Some of the benefits.

- We use automatically some standard view locations and those added by some mvc expanders..

- We re-use the default pages route directory equal to `/Pages` and then re-use the content root file provider which will not watch pages from the root. So, i think it also fixes the original issue of #1921.

- We get the default routes `{Module}/Foo`, and for an `Index` page `{Module}/Index` and `{Module}`.

- Modules pages routes now have an area route value as other controller actions.

- I was able to use absolute and relative `asp-page="/Foo"` and `asp-page="Foo"` attributes.

- I was able to use standard helpers as `AddAreaPageRoute()`.

**Todo**:

- Remove testing code.

- Filter application **home page** when running a setup. **Maybe in a separate PR** because it's idem for a controller with a home route attribute, even if defined by a not enabled module because of #2389.

### CODE REVIEW

**Comment by sebastienros** [comment]
It looks good ... once there is a new Web project in the Functional folder that will contain all these examples. You don't have to write test, at least move these test files in a specific, new, project.

**Comment by jtkech** [comment]
Okay, i will do it. And beyond functionnal tests, it will be useful also to debug issues without having to always re-create razor pages for testing in the cms web app.

**Comment by jtkech** [comment]
@sebastienros 

- I will do the testing application asap. Should we put it under `/test` or `/OC.Samples`?

- Should we create razor page(s) only in a module and / or a theme and / or at the application level?

- Should we consider any scenarios? Pages may have custom routes, there are many view locations ...

**First, i will see your last video to be sure i'm aware of all issues**.

**Comment by sebastienros** [comment]
In tests, this way it can have nonsensical examples. You don't have to create functional tests yet, just something where we can put whatever needs to work. We can do the functional tests in another PR.
The test can also have a module or a theme to test some scenarios. And the application would reference them.

**Comment by jtkech** [comment]
Okay cool.

**Comment by jtkech** [comment]
I saw the video.

- Setup issue is fixed.

- `_Layout` without file extension or a relative path in `viewStart` works. With the 1st option, the view is searched in `Pages/Shared`, `Views/Shared`, in the theme, the module, from the application root.

- Also works with `@page "{name}"` in a `Foo` page, and then from another page you can use.

      // The page name is still `/Foo` but you can add a route value.
      <a asp-page="/Foo" asp-route-name="TheName" class="navbar-brand">FooPage</a>
      <a href="/Foo/OtherName" class="navbar-brand">FooPage</a>

**Comment by jtkech** [comment]
So, for testing razor pages i created an application with on Module and on theme.

- Right now i only created pages in the module and different layout views in the module, the theme and under the application root.

- The module uses `AddAreaFolderRoute()` in its startup so that we can access its pages from the root. `/Foo`, `/Bar`, `/Baz`, `/FooBar`, `FooBaz` and `/Index` which also becomes the home page.

- All pages use `@page "{id?}"` or `@page "{name?}"` so that we can check e.g `/Foo/TheName`.

- The module index page (the home) contains these links that we can check.

      <p><a asp-page="/Foo">Foo without name</a></p>
      <p><a asp-page="/Foo" asp-route-name="Bill Gates">Foo with "Bill Gates"</a></p>

- The pages use the layout specified in `_ViewStart` or override it explicitly. Then, to locate the layout, `/Pages/Shared` has priority on `/Views/Shared`, the theme has priority on the module and then the application.

- So, the module pages use different layout and one layout is located everywhere, idem for another one but not under the theme `/Pages/Shared`, idem for another one but not at all under the theme, and so on. **So that we can check for each page that the right layout is used**.

- Finally, i copy pasted the index page under the module `/Pages/Subpages`, so we can access it through `/SubPages`. But in this folder there is a `_ViewStart` which explicitly specifies the layout located in the module `/Views/Shared`, this by using a **relative path**.

**Comment by jtkech** [comment]
@sebastienros 

I think this PR is ready, i added the test application.

I hope it will be merged before #2199 to not have to solve conflicts ;)

**Comment by psijkof** [comment]
We've checked out the areas branch and the demo seems to work fine!
The only thing that doesn't work in that demo is that since index.cshtml in the pages module handles the route, the admin is unreachable :)

We hope to see this merged soon. Thanks!

**Comment by sebastienros** [comment]
> I hope it will be merged before #2199 to not have to solve conflicts ;)
😢 

@jtkech Can you check what @psijkof is mentioning?

Also on the other branch that scares you, I have updated how the functional tests are written, and this is simpler now. So I hope I will be able to add a few tests once it's merged.

**Comment by jtkech** [comment]
@sebastienros okay cool.

@psijkof oh yes, i'm stupid, thanks.
The module index page is the home and it also contains `@page "{id?}"`, so ;)

**Pull request merged**
