### PR TITLE
Fix task.json for powershell

### PR DESCRIPTION
**Pull request by ns8482e**
Fixed following build error  encountered while using powershell in vscode.

image

### CODE REVIEW

**Comment by Skrypt** [comment]
Have you tried to see if it still works in Linux then?

**Comment by ns8482e** [comment]
@Skrypt  no I haven’t tried in Linux

**Comment by Skrypt** [comment]
Please try it, I'm pretty sure it will break the tasks. That's why we use the "Shell" type of command because it is universal across different OS's. Also, powershell is not necessary.

**Comment by ns8482e** [comment]
My vs code uses powershell For all task.json related task

**Comment by deanmarcussen** [comment]
I’ll try it on the Mac tomorrow and let you know

**Comment by deanmarcussen** [comment]
> Please try it, I'm pretty sure it will break the tasks. That's why we use the "Shell" type of command because it is universal across different OS's. Also, powershell is not necessary.

Pretty much what @Skrypt says, doesn't seem to be the right fix for the issue with powershell.

**Comment by ns8482e** [comment]
@deanmarcussen, @Skrypt I guess that's correct, But I don't understand why its taking powershell instead of cmd on windows?

**Comment by Skrypt** [comment]
Maybe because your default shell on Windows is set to Powershell.

**Comment by ns8482e** [comment]
@Skrypt  understood - I do have power shell as default in vscode that i  use in other repos. So I don't want to change it in global settings.

 What I don't understand is, Task.json has already defined following in OC repo 

```json
"windows": {
    "command": "cmd",
    "args": [
      "/C"
    ]
  },
```

Why it's not taking `cmd` and uses still `powershell`  for OC

**Comment by Skrypt** [comment]
image

I think that the description here explains what it does. It overrides any tasks.json settings to use what you defined globally in this "windows" settings.

**Comment by Skrypt** [comment]
I'm doing some reading and it would be possible to only use Powershell for any OS since you can install it on Linux and OSX. But the issue is that it requires to configure VS Code accordingly by adding this in the settings.json file of our project : 

```
{
    "terminal.integrated.automationShell.windows": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe"
}
```

**Comment by Skrypt** [comment]
Here some reading : https://code.visualstudio.com/docs/editor/integrated-terminal#_configuring-profiles

**Comment by ns8482e** [comment]
@Skrypt  @deanmarcussen  I am not sure why it's not working for me - I am using default installation of VS Code. All other .NET projects builds fine except orchard core.

Based your above suggestion, I updated the `task.json` as following for `windows` section and it works fine - update the PR

```json
"windows": {
    "options": {
      "shell": {
        "executable": "cmd.exe",
        "args": [
          "/C"
        ]
      }
    }
  }
```

**Comment by Skrypt** [comment]
I think this will work.

**Pull request merged**
