### PR TITLE
Minimal API

### LINKED ISSUE #15274: Migrate to Minimal APIs
Minimal APIs would provide better performance with minimal disruption since we are already organized as modules. I'd like to see someone trying to convert a simple module to it and see if it improves performance or find issues during the process.

### PR DESCRIPTION
**Pull request by MikeAlhayek**
Fix #15274

### CODE REVIEW

**Comment by MikeAlhayek** [comment]
@sebastienros I did bombarded by localhost using

```
bombardier -c 500 -n 1000000
```

Here is the output using mimimal API

image

Here is the output using controller

image

**Comment by sebastienros** [comment]
5xx means all the responses are 500, so it's void. If you ran this command line it's missing the url.

`bombardier -c 50 -d 15 -- insecure -l http://localhost:5000/{insertpathhere}`

**Comment by MikeAlhayek** [comment]
Oh see now that all of the are 5xx errr

bombardier -c 500 -n 1000000 https://localhost:44300/kb15/api/content/4efeywk0k48f1vbnewk0xwcpxd -H "Authorization: Bearer a token that was generated by postman"

let me try it again

**Comment by MikeAlhayek** [comment]
@sebastienros here are better outputs using `-c 125 -n 100000`

Minimal APIs

image

Using controller 

image

**Comment by Piedone** [comment]
This is not something ready for review, right? Because then please make it a draft.

**Comment by MikeAlhayek** [comment]
@Piedone yes. I cleaned it up and fixed the test. It is ready for review. It uses Minimal API for the content API.

**Comment by Piedone** [comment]
Is the primary goal of this performance?

**Comment by MikeAlhayek** [comment]
Yes. And less complexity since we are using Minimal APIs.

**Comment by Piedone** [comment]
I'm not sure about the complexity, since it's 25% more code than the controller was :).

Do we know though what makes it faster? Because if it's due to it not doing something that the MVC approach does, then we'll need to optimize that too, since we won't rewrite every OC API controller out there.

**Comment by MikeAlhayek** [comment]
You are saving the complexity of creating the controller and its objects.

Minimal API are executed directly like a middleware. We'll ensure that we only resolve services that are needed by the endpoint. If you see the Bombarier output I shared earlier, you'll see that it is able to handle slightly more requests that a controller does.

**Comment by Piedone** [comment]
I see, thanks. Yep, seen that, it's nice.

**Comment by MikeAlhayek** [comment]
> I see, thanks. Yep, seen that, it's nice.

Did you want to review this PR?

@sebastienros can you please review this?

**Review by Piedone — COMMENTED** [review]
Do I understand correctly that there are no logic changes within the endpoints (compared to the actions)? Except for `Delete` returning 404 instead of 204 if no item is found.

**Comment by MikeAlhayek** [comment]
Correct. At the end of the day, we took the code from a single controller and split it into multiple smaller endpoint level manageable files that get called quicker with less resources.

**Review by Piedone — APPROVED** [review]

**Pull request merged**
