### PR TITLE
Fix user migration

### PR DESCRIPTION
**Pull request by deanmarcussen**
Fixes https://github.com/OrchardCMS/OrchardCore/issues/8184

Has been made to rerun on anyone who has already run the migration from previous pr.

/cc @Skrypt

### CODE REVIEW

**Comment by Skrypt** [comment]
Ok, so for me it doesn'T seem to update the UserIndex table it might be an issue on my side with some handler failing. I will take a look, but the PR seems appropriate.

**Comment by deanmarcussen** [comment]
Another failing migration perhaps? What does your migration record say

**Comment by Skrypt** [comment]
```
    {
      "DataMigrationClass": "OrchardCore.Users.Migrations",
      "Version": 7
    },
```

**Comment by deanmarcussen** [comment]
Ok so if you have 7 this next migration which returns 8 hasn’t run.

The index is refreshed by the document save.

but previously as normalized user name wasn’t set, the index refresh produced same output.

**Comment by Skrypt** [comment]
Ok merge it. It's required ... we will see if it fixes my issues for the UserIndex from nuget packages afterward. I don't want to spend too much time testing it with full source code.

**Review by Skrypt — APPROVED** [review]

**Comment by Skrypt** [comment]
Ok, just saw that the UserIndex indexes NormalizedUserName. So this is the appropriate fix. Merged.

**Pull request merged**
