### PR TITLE
Fix media table valign

### LINKED ISSUE #4127: Asset layout trouble
image

image

### PR DESCRIPTION
**Pull request by matiasmolleja**
Fixes #4127

fixed-alignement

fix-treeview

### CODE REVIEW

**Comment by matiasmolleja** [comment]
I think that instead of an horizontal scroll bar it would be better if we could have an splitter, like the one in VSCode. My plan is to try to do that on a future PR.
For now the solution is good enough I think. Not very common having so deep paths. For these cases we have a solution now.

**Comment by hishamco** [comment]
How it looks in Mobile?

**Comment by matiasmolleja** [comment]
Nice IMO.

mobile

**Comment by hishamco** [comment]
Good job :shipit:

**Pull request merged**
