### PR TITLE
Create ManageMediaOptions Permission

### LINKED ISSUE #8141: Create new permission for Manage Media Options
Currently if you have the ManageMedia permission you can ~edit~ see the Media Options.
It should be a separate permission ~as it allows to change the base path of media folder~.

### PR DESCRIPTION
**Pull request by Skrypt**
And assign it to it's controller action.

Fixes #8141

### CODE REVIEW

**Comment by Skrypt** [comment]
Other option would be to use ManageAdminSettings.

**Comment by deanmarcussen** [comment]
Yes, I'm ok with separating this permission out.

Suggest it is named `ViewMediaOptions` as was done for the Azure module, as there is no Management involved. They're a read only view of the options.

https://github.com/OrchardCMS/OrchardCore/blob/894ab0c931a944ef9db1d56a5bbd903b450f94ee/src/OrchardCore.Modules/OrchardCore.Media.Azure/Permissions.cs#L10

**Comment by hishamco** [comment]
@Skrypt how this controls the media options in the UI?

**Comment by Skrypt** [comment]
Seems like there is no edit button so you can't edit them. But still, doesn't make sense to me to allow seeing these options when you are a content editor for example.

**Comment by hishamco** [comment]
> But still, doesn't make sense to me to allow seeing these options when you are a content editor for example.

I was expecting the PR solving this ;)

**Comment by Skrypt** [comment]
You expecting too much of me 😉

**Review by deanmarcussen — APPROVED** [review]

**Pull request merged**
