### PR TITLE
Case insensitive Shape parameters

### PR DESCRIPTION
**Pull request by jtkech**
My bad, in a previous PR thinking it was using `StringComparison.Ordinal` i changed it to just use the `==` operator. So, here i reverted this change to be case insensitive as before.

### CODE REVIEW

**Comment by Skrypt** [comment]
LGTM

**Comment by sebastienros** [comment]
Does it mean we don't need the parameters to be PascalCase either?

**Comment by jtkech** [comment]
Yes, as it was before

But if you prefer we can keep it as it is now (case sensitive), i was hesitating

**Comment by sebastienros** [comment]
I like the case insensitive change, but I am wondering if we can also revert the changes you made to the arguments in the same PR.

**Comment by jtkech** [comment]
Or if you want we could do

    if (parameter.Name == "DisplayAsync" || parameter.Name == "displayAsync")

>  ... if we can also revert the changes you made to the arguments in the same PR.

I don't remember, need to retrieve what i could did

**Comment by sebastienros** [comment]
No, these changes:
https://github.com/OrchardCMS/OrchardCore/pull/5470/files#diff-83238ac7c4ea3e60ee5c23f38fb0fc24R21

**Comment by jtkech** [comment]
Oh yes so we could re-use `shape` inplace of `Shape`

You see everything ;)

**Pull request merged**
