### PR TITLE
Fix for parsing plural entries in PO files with multi line strings.

### PR DESCRIPTION
**Pull request by rros**
This PR adds a test for the `PoParser`-class and fixes the bug in `PoParser` for plural entries with multi line strings.

Fixes: #13565

### CODE REVIEW

**Comment by rros** [comment]
@dotnet-policy-service agree [company="Blis Digital"]

**Comment by rros** [comment]
@dotnet-policy-service agree company="Blis Digital"

**Review by sebastienros — APPROVED** [review]

**Review by hishamco — APPROVED** [review]

**Comment by hishamco** [comment]
Thanks for your contribution @rros

**Comment by hishamco** [comment]
Thanks for your contribution @rros

**Pull request merged**
