### PR TITLE
Add missing contributors (Lombiq Technologies: OCORE-154)

### PR DESCRIPTION
**Pull request by Piedone**
Related: #15029.

### CODE REVIEW

**Comment by Piedone** [comment]
@agriffard can I get some reaction from you here, please? It's fine if you can't review, I just don't want to pointlessly wait.

**Comment by MikeAlhayek** [comment]
@agriffard seems to be too busy these days. @Piedone this LGTM.

**Review by agriffard — APPROVED** [review]
Sorry, didn't see you expected a review from me.
LGTM

**Comment by Piedone** [comment]
Thank you both!

**Pull request merged**
