### PR TITLE
Add display mode option to parts

### PR DESCRIPTION
**Pull request by deanmarcussen**
Fixes https://github.com/OrchardCMS/OrchardCore/issues/5220

Still need to update some part drivers to support both editors and display modes, and provide default option for editor and display

### CODE REVIEW

**Comment by deanmarcussen** [comment]
@agriffard your thoughts on this?

After reviewing the parts the only ones this makes any sense to apply a display mode to is
- Markdown
- Html
- Title (at a stretch)

The rest of the parts are too complicated (in the way their drivers work) to really want to apply a display mode to.

So this is a lot of change, for not a huge benefit, and will only be supported for a few parts.

I may close if no one particularly wants it

**Comment by agriffard** [comment]
For example, you could display a list with <ul><li> by default and want to make other display options like Table, Bootstrap Cards (with settings like the container and column css classes, horizontal or vertical, nb items per line, ...), Masonry.

In this case, you need to choose between the use of templates or the implementation of new display options.

For the other kind of parts, if you were also able to choose different rendering between Details and Summary, that could be interesting.

**Comment by deanmarcussen** [comment]
added a display mode option to Lists as well.

**Comment by sebastienros** [comment]
When we designed the feature, we didn't have a way to switch drivers per display mode. So we came with a way to use a different shape type based on a setting, hence `GetDisplayShapeType()`.

However we now have the possibility to create custom drivers and even complement existing ones for a custom display modes. We could assume that this method is then not needed anymore. However it's useful to just switch the existing template with another one if we don't intend to change anything in the way the driver creates the shape properties, or edits the values. And substituting the driver would be only necessary if the driver needs to be replaced. Be careful that in the case we want to add an extra driver, then it won't work as the initial driver will still find a display template is used, and change the initial shape type.

**Comment by deanmarcussen** [comment]
> However we now have the possibility to create custom drivers and even complement existing ones for a custom display modes. We could assume that this method is then not needed anymore. 

I think `GetDisplayShapeType()` still remains useful for parts that we do not want to support the concept of a display mode. As not all parts suit that - which is why I've only enabled the concept for a few of the suitable parts.

> However it's useful to just switch the existing template with another one if we don't intend to change anything in the way the driver creates the shape properties, or edits the values. 

This bit is where display modes are useful I think. That you can just add a new template (named correctly, with the setting view), and the shape system will pick just pick it up

> And substituting the driver would be only necessary if the driver needs to be replaced. Be careful that in the case we want to add an extra driver, then it won't work as the initial driver will still find a display template is used, and change the initial shape type.

I think as soon as you (an end user) is replacing the driver, then they are getting into territory where they need to understand that they would have to reconfigure the existing driver not to fire for the display mode they want to create. Which is how I have done the driver configuration options.

**Pull request merged**
