### PR TITLE
Allow registering named style and script resources with inline content

### LINKED ISSUE #5897: Feature : Allow registering style block from shapes
The intent is to have something similar to custom scripts feature :

Razor
```
<style>
    .my-class {
        /* some style */
    }
</style>
```

Liquid
```
{% styleblock %}
    .my-class {
        /* some style */
    }
{% endstyleblock %}
```

To do :
- [ ] Allow inline declaration with `StyleTagHelper`
- [ ] Add 'styleblock' Liquid `NamedHelperBlock`
- [ ] Document feature

### PR DESCRIPTION
**Pull request by TFleury**
Closes #5897 : Allow registering named style and script resources with inline content

### CODE REVIEW

**Comment by TFleury** [comment]
I think it could replace the existing [custom script feature](https://orchardcore.readthedocs.io/en/latest/docs/reference/modules/Resources/#custom-scripts). It just requires an additional name attribute.
So, we will be able to remove `RegisterHeadScript` and `RegisterFootScript` from `ResourceManager`.

#### Usage :
Razor
```razor
<script asp-name="Test" at="Head" depends-on="jQuery">
    console.log("Hello");
</script>

<style asp-name="custom-style" depends-on="thetheme-bootstrap-oc">
    .my-class {
        /* Some css rules */
    }
</style>
```
Liquid
```liquid
{% scriptblock name:"Test", at:"Head", depends-on:"jQuery" %}
    console.log("Hello");
{% endscriptblock %}

{% styleblock name:"custom-style", depends-on:"thetheme-bootstrap-oc" %}
    .my-class {
        /* Some css rules */
    }
{% endstyleblock %}
```

**Comment by deanmarcussen** [comment]
I like this option two @TFleury and I would be happy with both this, and your other pr.

For me it makes using an inline script easier, because you don't need to also specify the script you are depending on, earlier in the template.

I wouldn't think to remove the `RegisterHeadScript` and `RegisterFootScript` though, as that would be a breaking change, but over time possibly deprecate?

**Comment by TFleury** [comment]
Merged into #5903

**Comment by ns8482e** [comment]
@deanmarcussen @TFleury comments on general concept - not on PR. 

I didn't like the original implementation of inline script combined with resource but it works because normally `<script>` are placed at `Foot` (works with some bugs that I am trying to fix in PR #5507 ) , So I fear that having in-line style on similar implementation would add similar issues. 

In my opinion inline scripts and inline styles are `content` and not `resources`  hence it should be kept outside resource manager, `zones` are perfect for inline script/style and you can manage order using placement order.

For naming in liquid, it's prefer to use `javascript` instead of `scriptblock` and `stylesheet` instead of `styleblock` as those are known to liquid developers. or add both names.

**Comment by ns8482e** [comment]
FYI with PR #5413 for `@section` It would be even easier for asp.net developer to define scripts with known method, without needing to know orchard core provided implementations of script/style tag helper

```
@section styles {
.my-class {
        /* Some css rules */
    }
}
@section scripts {
    <script>
      alert('foo');
    </script>
}
```

**Comment by TFleury** [comment]
Yes, this is what I used so far.

But, assume you have a shape that injects a custom script/style, and you have n instance of your shape on your page. Unless you use a trick with `HttpContext.Items`, you will end up with n instances of your script/style.

That's what I wanted to solve with this PR.

**Pull request merged**
