### PR TITLE
Update ContentTypes README.md

### PR DESCRIPTION
**Pull request by microposmp**
The WithField is not available on ContentTypePartDefinitionBuilder. Updated the sample to call AlterPartDefinition separately.

### CODE REVIEW

**Comment by sebastienros** [comment]
That's a different kind of field IMO. We need to check where this extension method is, or where the code it's supposed to call is. Because your new example adds fields to the PartDefinition, not the TypePartDefinition.

**Comment by microposmp** [comment]
I think the end result should be exactly the same and I like the coding pattern in the original sample. It makes it very easy to read.

**The text above the sample is as follows**:
Fields can not be attached directly to a Content Type. To add fields to a content type, create a part with the same name as the type, and add fields to this part.

The suggested documentation change works as it is today.

AlterTypeDefinition.WithPart returns a ContentTypeDefinitionBuilder and not ContentTypePartDefinitionBuilder as I wrote in the original description.

**Comment by microposmp** [comment]
I made some experiments (mostly to learn about OrchardCore development) and tried to implement WithField on ContentTypePartDefinitionBuilder. It will have to create the PartDefinition behind the scenes and I think it can be confusing.

The suggested change of the sample code I believe describes the correct way to add fields to a content type.

**Comment by microposmp** [comment]
I made a mistake when I created this pull request off the dev branch of my fork. I would like to close it and open a new pull request from a separate branch or open it as an issue instead.

Every time I bring the dev branch up to date it triggers an unnecessary rebuild in this pull request.

Which is the preferred way of doing it?

- Close this pull request and open a new one.
- Close this pull request and open an issue.

**Comment by hishamco** [comment]
What's the action needed here?

**Comment by microposmp** [comment]
The original update to the README file in this pull request was a suggestion to update the documentation. It's only the README that should be in this issue. The rest was pushed by mistake.

**The description in the documentation is written as follows**:
Fields can not be attached directly to a Content Type. To add fields to a content type, create a part with the same name as the type, and add fields to this part.

The existing code sample following the description don't work. The updated code sample works.

**Comment by sebastienros** [comment]
Please recreate a PR with only the intended changes

**Pull request closed without merging**
