### PR TITLE
Fix steporder.js

### PR DESCRIPTION
**Pull request by MikeAlhayek**

### CODE REVIEW

**Comment by sebastienros** [comment]
Have you tried it? It's possible that the correct fix was done in the wwwroot manually, I just want to be sure that's what it was supposed to do.

**Comment by MikeAlhayek** [comment]
that condition was added to avoid a js exception when trying to sort objects that does not exists in the DOM.

**Comment by MikeAlhayek** [comment]
this is the correct logic "already in main"

https://github.com/OrchardCMS/OrchardCore/blob/fe2ba6ed5ac8a7ef7e29b73bdc2c46d067674958/src/OrchardCore.Modules/OrchardCore.Deployment/wwwroot/Scripts/steporder.js#L25

**Comment by sebastienros** [comment]
I'll let you merge Bootstrap and this one yourself then because there will be conflicts: the 3 files impacted need to match. Might be easier to reapply gulp here once BS is merged

**Review by sebastienros — APPROVED** [review]

**Pull request merged**
