### PR TITLE
Upgrade Fluid

### PR DESCRIPTION
**Pull request by sebastienros**
/cc @lahma 

Is that how I need to change the code?

### CODE REVIEW

**Comment by lahma** [comment]
Yep sorry I was already at sleep. Looks about right, I think I'll make a separate PR to reduce state machines like in Liquid.

**Comment by jtkech** [comment]
@lahma i just began to take a look on your merged pr in fluid (will continue maybe tomorrow). So as i understood, you use as possible `Task` object without using async / await, and in some place when an await would be needed you wraps thing in an `Awaited` method that does the await so that the caller is still able to not use async / await.

That said, here i don't understand what @sebastienros did, he adds some await in place of returning a task directly. Seems to me contradictory ???

**Comment by lahma** [comment]
Well this adds one state machine, but the Fluid update removes many. Your analysis is correct, the implementation could be a bit more efficient. I'm working on a separate PR for this, but the pattern without state machine creation would be this:

```
public static ValueTask RenderAsync(
    this LiquidViewTemplate template,
    LiquidOptions options,
    IServiceProvider services,
    TextWriter writer,
    TextEncoder encoder,
    TemplateContext templateContext)
{
    async ValueTask Awaited(Task task)
    {
        await task;
    }

    templateContext.AddAsyncFilters(options, services);

    // Check if a 'ViewContext' has been cached for rendering.
    var viewContext = templateContext.GetAmbientViewContext(encoder, template);

    if (viewContext != null)
    {
        viewContext.Writer = writer;

        // Use the view engine to render the liquid page.
        var task = viewContext.View.RenderAsync(viewContext);
        if (task.IsCompletedSuccessfully)
        {
            return new ValueTask();
        }
        return Awaited(task);
    }

    // Otherwise, we don't need the view engine for rendering.
    return template.RenderAsync(writer, encoder, templateContext);
}
```

**Comment by jtkech** [comment]
@lahma thanks for the infos, yes i saw this kind of code in the aspnetcore repo, but i said to me that if i begin to write some code like this sebastien will never merge my PRs ;)

Okay, i now see why @sebastienros added these await (what i didn't understand). With the fluid upgrade `template.RenderAsync()` now returns a `ValueTask` and here is used in a method that still returns a `Task`.

**Comment by lahma** [comment]
Yes, I stand on the shoulders of giants 🙂  coreclr/aspnet repos have the big guns working and it's a great learning resource, I've adressed state machines in this PR https://github.com/OrchardCMS/OrchardCore/pull/4352

**Pull request merged**
