### PR TITLE
DateField implementation

### PR DESCRIPTION
**Pull request by agriffard**
DateField with basic `<input type="date"/>` editor.

### CODE REVIEW

**Comment by Skrypt** [comment]
We should maybe add some comment about the fact that this field has no time zone.

**Comment by sebastienros** [comment]
I would personally force to UtcKind when it's stored and read, to be sure the database is not converting it from Local to Utc or the opposite. We just don't convert the timezone when displaying it.

**Comment by Skrypt** [comment]
Store it as Utc but yes make sure it's never converted. Which means that if someone enters 12/12/2018 12:00 am then it's always stored or read as is. We force the UtcKind only for reusability with NodaTime. So it's a "fake" UtcKind 😉

**Comment by sebastienros** [comment]
Yes we never convert it. And it's not just about NodaTime, which in this case would not make sense. It's more about the database drivers.

**Comment by Skrypt** [comment]
I think NodaTime LocalDate should works with PostgreSQL and SQL Server but I'm not sure with SQLite. I agree that we're probably better keep using BCL types for now.

**Comment by sebastienros** [comment]
Merging, let's test it on different databases later.

**Pull request merged**
