### PR TITLE
Some general CSS fixes

### PR DESCRIPTION
**Pull request by Skrypt**
I made some CSS fixes. 
- The NanoScroller was displaying on top of the > icons
- Added cursor: pointer on nav items
- Added style for current active "category"
- Added some padding 1em on tb-content bottom so that we see the bottom border of content lists. "Natural page bottom padding".
- Changed top nav background-color to make a distinction between left sidebar and top nav zones.

image

### CODE REVIEW

**Comment by Jetski5822** [comment]
Nice!!! The log off button looks outta place :(

**Comment by agriffard** [comment]
I have done a similar fix for nano-scroller in my Bootstrap beta 2 PR #913 but yours seems ok.

Please read my suggestion in #1150 about using Bootswatch and tells me if it is a good solution to customize the header.

**Comment by agriffard** [comment]
May be could separate the sidebar variables and sass in another .scss file.

**Comment by Skrypt** [comment]
I'm not sure if Bootswatch is enough for having a great looking admin theme. If I remember when we used the Amaretti theme on 01 it was removing total compatability with Bootswatch. The decision depends on what we want to achieve as an end goal. We could easily set a short term goal for having Bootswatch compatibility but I'd say that looking at something like : http://coreui.io/index.html right now could be also a good. I just found that admin theme by looking quick. I'd say, if we take lessons from the previous implementation(s) we should try to find an open source theme that we can either fork or contribute on. That way, we could separate logic from theming concerns and having a separate repository for that seems like the way to go now. We also want to leave the choice of which JS framework people will want to integrate with. That CoreUI theme seems like proposing integrations for most of the popular ones.

**Comment by Skrypt** [comment]
@Jetski5822 I'm sure it needs more work ! 😄

**Comment by sebastienros** [comment]
I like everything but the colors. This muddy green, and the super dark active category. Am I the only one?

**Comment by agriffard** [comment]
I don't like the header color either. That is why I suggested to use Bootswatch, to give a way to the user to choose.
At least, it opened the discussion: I found interesting Jasmin's answer about CoreUI, I'll continue to comment on this thread: #1150.

If you don't mind, I would wait until the Bootstrap Beta PR is merged.

@Skrypt : If you intend to make other contributions, I suggest we add you on the OrchardCore dev team so you can push your branches and PRs on the repo.

**Comment by sebastienros** [comment]
We'll ask you to update the PR when @agriffard 's PR is merged

**Comment by sebastienros** [comment]
Can you update this one since we have merged @agriffard 's ? Thanks

**Comment by paynecrl97** [comment]
@agriffard's new documentation theme got a positive reception at a recent meeting. Maybe use that design as a basis? https://orchardcoredoc.azurewebsites.net/

**Comment by agriffard** [comment]
@paynecrl97 : the theme used for the documentation is only a MkDocs one : http://squidfunk.github.io/mkdocs-material/

**Comment by Skrypt** [comment]
Not needed anymore

**Pull request closed without merging**
