### PR TITLE
Prettify the localization part

### PR DESCRIPTION
**Pull request by hishamco**

### CODE REVIEW

**Comment by hishamco** [comment]
Content Localization

**Comment by hishamco** [comment]
I might share a screenshot of how it was before, the UX after this PR got improved, may be I can demo on it next week

**Comment by Piedone** [comment]
This is the before-after:

image

Now, I'm really not authoritative on design questions, but the new one doesn't seem to be better for me. I don't think it looks nicer, but more importantly, with an overlay it's harder to use than the collapsible area, and displays less information about the culture settings.

So, I don't think changing to this would be useful.

**Comment by hishamco** [comment]
Thanks for the before and after pic :)

Your feedback is welcome, but this is not the right way to use the accordion anymore, the idea is to select the culture so the content type will be localized concerning that culture and nothing more

That's why I complained from the early days in OC that all are developers and there is no one specialist. I'm practicing some of the knowledge that I have in the UI but I can talk with my colleague who is the UI/UX specialist

Again UI refreshment is something that we might consider for OC 2.0

**Comment by Piedone** [comment]
Why is it not the "right" way?

**Comment by sebastienros** [comment]
I think we can do better than the accordion, but I'd like to see a hint in some sort for the user to understand that clicking this button will open a new editor for the culture. In your demo it's obvious that even you didn't expect the "Demo (IT)" change to be lost by selecting IT in the drop down. This should be two step: Select culture + Action to go to the new editor (and potentially a warning that changes are pending and will be lost). Or a way to know that selecting a culture will refresh the page.

Something like:

Culture: English (en-us) [Switch Cultures]

Where `[Switch Cultures]` is a button drop-down. And a message box in case there are pending changes (the preview events should be able to help with that if).

**Comment by hishamco** [comment]
Screenshot 2024-03-26 052300

**Comment by hishamco** [comment]
@sebastienros are you happy with the change, so I can merge this? As you know I have many PRs on my list :)

**Comment by Piedone** [comment]
You didn't really elaborated why it's better; I don't think it is. And I didn't really get an answer on https://github.com/OrchardCMS/OrchardCore/pull/13354#issuecomment-2008375318 either.

**Comment by hishamco** [comment]
Sorry, Zoltan maybe I missed this due to many issues & PRs I have :)

Regarding your question:

- An accordion is used when you have many items that contain headers & bodies something like FAQ, in our case we used it as a dropdown list
- The current UI is taking much unnecessary space horizontally
- Some UI issues (duplicate arrow)

IMHO the new design is much clearer & cleaner, the only thing it missed as Seb pointed is a warning to tell the user that changing the culture either will create or display a localized version

**Comment by Piedone** [comment]
> An accordion is used when you have many items that contain headers & bodies something like FAQ, in our case we used it as a dropdown list

I don't think there is only one way to use an accordion, but sure, we could display it permanently.

> The current UI is taking much unnecessary space horizontally

I don't think that's a concern since there's nothing else that would use that UI, nor does it make the UI harder to use. But, you can just make it narrower.

> Some UI issues (duplicate arrow)

I don't know what you're referring to, could you elaborate?

I'm also awaiting your reflection on the other concerns I voiced:

- An overlay is harder to use. You can easily misclick on one of the buttons. This is a [known accessibility issue](https://www.w3.org/WAI/tutorials/menus/flyout/).
- The new UI displays less information about the culture settings, since it misses the culture code. Among the myriad of cultures, why would we make the UI less specific? Like it displays "Breton"; what's that actual culture? Is it `br`? Or `br-FR`? If it's "Arabic", do we indeed mean just `ar`, or `ar-001`, or any of the other Arabic locales? Unless you have .NET's culture table in your head (because the human-readable names are not standard and are not the same among all platforms/OS), you won't know without the culture code. I don't see why we'd remove this.

**Comment by hishamco** [comment]
> I don't think that's a concern since there's nothing else that would use that UI, nor does it make the UI harder to use. But, you can just make it narrower.

We can make it smaller but I don't think the accordion is suitable for such case

> I don't know what you're referring to, could you elaborate?

There's a UI issue, there are two arrows one on the right and one after the culture code, up and down for unknown reasons :)

> An overlay is harder to use. You can easily misclick on one of the buttons.

We already use culture pickers in many places. BTW I remember I suggested another design in the past hope to find it

> The new UI displays less information about the culture settings, since it misses the culture code. Among the myriad of cultures, why would we make the UI less specific? Like it displays "Breton"; what's that actual culture? Is it br? Or br-FR? If it's "Arabic", do we indeed mean just ar, or ar-001, or any of the other Arabic locales? Unless you have .NET's culture table in your head (because the human-readable names are not standard and are not the same among all platforms/OS), you won't know without the culture code. I don't see why we'd remove this.

I just displayed the language (Country), and I can bring the code back. While you mention this I remember almost all the CMSs use the term language instead, regardless of the country. It's Arabic for instance regardless you are from Yemen, KSA, UAE .. etc

**Comment by hishamco** [comment]
> We already use culture pickers in many places. BTW I remember I suggested another design in the past hope to find it

#3597

**Comment by Piedone** [comment]
Perhaps you can find a way to fix those issues, or come up with a different UI altogether. What's in this PR I don't think is better, and that we have other pieces of UI that have the same issues is not an argument in favor of it.

I'll leave the rest up to those interested, but this PR, in its current form, is not something I agree with merging.

**Comment by hishamco** [comment]
> What's in this PR I don't think is better, and that we have other pieces of UI that have the same issues is not an argument in favor of it

For me, it's much better :), I know there're many UI issues, that's why I'm trying to fixed them one by one

**Comment by hishamco** [comment]
@sebastienros is this something we can agree with or shall I close this PR, then probably move the change into Orchard Core Contrib (OCC)

**Comment by sebastienros** [comment]
Currently trying the merge steps to get the PR uptodate, please don't do anything here in the meantime

**Comment by sebastienros** [comment]
We are closing the PR because this won't be a better solution. You can create another one after we agree on what solution to apply (if any).

**Comment by hishamco** [comment]
I will move this into Orchard Core Contrib (OCC) while the current UI for the localization part is inappropriate in terms of UI/UX :)

**Pull request closed without merging**
