### PR TITLE
Fixes #9512 Cancel session on exception

### LINKED ISSUE #9512: Documents are still persisted after an unhandled exception is thrown
### To Reproduce

- enlist an entity for save with `_session.Save(entity)`
- throw an unhandled exception
- entity is still commited by the `RegisterBeforeDispose` in the shell scope

### Expected behavior

We've resolved this ourselves with some exception handling middleware, which specifically calls `await _session.CancelAsync()`

Should we put this, or a similar solution, into the shellscope, so that `RegisterBeforeDispose` can potentially have an option to execute operations, like `SaveChangesAsync()` only if there are no exceptions.

/cc @jtkech have we talked about this before, I thought we had?

### PR DESCRIPTION
**Pull request by jtkech**
Fixes #9512 

@deanmarcussen if you have time, can you check if it fixes your issue?

### CODE REVIEW

**Comment by deanmarcussen** [comment]
@jtkech looks like it will be ideal - particularly with the `IExceptionHandlerFeature`

I will test on Monday

**Comment by jtkech** [comment]
Okay cool, i may have some last tweaks to do

**Comment by jtkech** [comment]
Any feedback?

But only if you have time

Just because i need it for #9509 ;)

**Review by deanmarcussen — APPROVED** [review]
@jtkech tested, fixes the issue thank you

**Pull request merged**
