### PR TITLE
Fixes building the GraphQL schema.

### LINKED ISSUE #16182: GraphQL schema building fails and is inefficient
### Describe the bug
After merging #16143, building the GraphQL schema may fail if a field is resolved through DI multiple times.
E.g. if we have a content type with a media field and also a `CustomUserSetting` with another media field as well, it fails with: 

```
System.InvalidOperationException: A different instance of the GraphType 'MediaFieldQueryObjectType' with the name 
'MediaField' has already been registered within the schema. Please use the same instance for all references 
within the schema, or use GraphQLTypeReference to reference a type instantiated elsewhere.
To view additional trace enable GlobalSwitches.TrackGraphTypeInitialization switch.
   at GraphQL.Types.SchemaTypes.EnsureTypeEquality(IGraphType existingType, IGraphType newType, TypeCollectionContext context) in /_/src/GraphQL/Types/Collections/SchemaTypes.cs:line 803
   at GraphQL.Types.SchemaTypes.AddTypeIfNotRegistered(IGraphType type, TypeCollectionContext context) in /_/src/GraphQL/Types/Collections/SchemaTypes.cs:line 780
   at GraphQL.Types.SchemaTypes.Initialize(ISchema schema, IServiceProvider serviceProvider, IEnumerable`1 graphTypeMappings) in /_/src/GraphQL/Types/Collections/SchemaTypes.cs:line 277
   at GraphQL.Types.SchemaTypes..ctor(ISchema schema, IServiceProvider serviceProvider, IEnumerable`1 graphTypeMappings) in /_/src/GraphQL/Types/Collections/SchemaTypes.cs:line 190
   at GraphQL.Types.SchemaTypes..ctor(ISchema schema, IServiceProvider serviceProvider) in /_/src/GraphQL/Types/Collections/SchemaTypes.cs:line 175
   at GraphQL.Types.Schema.CreateSchemaTypes() in /_/src/GraphQL/Types/Schema.cs:line 477
   at GraphQL.Types.Schema.CreateAndInitializeSchemaTypes() in /_/src/GraphQL/Types/Schema.cs:line 448
   at GraphQL.Types.Schema.Initialize() in /_/src/GraphQL/Types/Schema.cs:line 196
   at OrchardCore.Apis.GraphQL.Services.SchemaService.GetSchemaAsync() 

[...]
```
This comes from the fact that `ObjectGraphType<T>`s are now resolved multiple times as @tropcicstefan pointed out. The types are added manually to the schema and are also resolved by initializing the schema. This causes conflicting instances being used.

As we cannot register the GraphQL types as neither `Scoped` nor `Singleton`, we must ensure that building the schema will always use the correct instances. This may require some rework how we build the schema.

### PR DESCRIPTION
**Pull request by gvkries**
Fixes building the GraphQL schema that fails because the types must be registered as transient and are resolved multiple times.

Also this makes the schema building a little bit more efficient by mostly reusing already registered types.

Fixes #16182

/cc @MikeAlhayek @tropcicstefan

### CODE REVIEW

**Comment by Piedone** [comment]
@hyzx86 could you please check this out too?

**Comment by hyzx86** [comment]
Hi @mdameer , It looks like this PR will have some relevance to your PR #16092 , can you take a look?

**Comment by gvkries** [comment]
#16092 would have to change a little bit, but it doesn't look like too conflicting. I would suggest to merge this PR first, because it fixes a bug and #16092 is about new features 🤷‍♂️

**Review by hyzx86 — APPROVED** [review]
LGTM

**Review by sebastienros — APPROVED** [review]

**Comment by hishamco** [comment]
@gvkries anything else to add here or shall I merge?

**Comment by hishamco** [comment]
I will update to master then merge

**Pull request merged**
