### PR TITLE
Fix user menu text alignment

### LINKED ISSUE #16595: Slightly misaligned icons in user menu
### Describe the bug

Most of the standard user menu items include icons that are tagged with the "fixed width" (fa-fw) font awesome class which allows them to align nicely in the drop-down menu. However, a few are missing the fa-fw class so they appear a bit askew.
 
### Orchard Core version

1.8.3

### To Reproduce
1. Sign in to the admin dashboard
2. Enable the "Users Change Email" feature and then under Security > Settings > User Change email, check "Allow the users to change their email" setting and press Save. (This just makes the problem a bit more obvious.)
3. Click on the user icon and notice that the drop-down menu text is not aligned quite right.

### Expected behavior
The menu should have nicely aligned icons and text. The problem is a bit subtle but it's enough that it gives just a bit of a sloppy appearance that some users (and our UX team) have noted.

### Logs and screenshots

Here's a screenshot showing the menu with a straight red line added to help clarify that the text is not properly aligned.

image

Notice that most of the UserMenuItem-*.cshml templates use the fa-fw (fontawesome fixed width class) to ensure that the text after the icon will be aligned correctly. For example, the Change Email shape:

```
<li>
    <a class="dropdown-item" asp-route-area="@UserConstants.Features.Users" asp-controller="ChangeEmail" asp-action="Index">
        <i class="fa-solid fa-envelope fa-fw" aria-hidden="true"></i> @T["Change Email"]
    </a>
</li>

```

However, some of them are missing the fa-fw class. For example, the Sign Out shape:

```
<li>
    <a class="dropdown-item" asp-area="@UserConstants.Features.Users" asp-controller="Account" asp-action="ChangePassword" asp-route-returnUrl="@FullRequestPath">
        <i class="fa-solid fa-key" aria-hidden="true"></i> @T["Change password"]
    </a>
</li>
<li>
    <form asp-route-area="@UserConstants.Features.Users" asp-controller="Account" asp-action="LogOff" method="post" class="no-multisubmit">
        <button type="submit" class="dropdown-item">
            <i class="fa-solid fa-sign-out-alt" aria-hidden="true"></i> @T["Log off"]
        </button>
    </form>
</li>
```

If I add the missing fa-fw classes, then the problem is resolved.

image

### PR DESCRIPTION
**Pull request by mvarblow**
Fixes #16595

### CODE REVIEW

**Comment by hyzx86** [comment]
Can you provide screenshots before and after the fix? Thanks!

**Comment by hishamco** [comment]
As @hyzx86 said please share before and after screenshoot

**Comment by mvarblow** [comment]
Hi @hishamco, @hyzx86. Thanks for taking a look. I included screen shots on the associated issue. #16595

**Comment by mvarblow** [comment]
It had merge conflicts with my other pull request from today. Those conflicts are resolved now. :)

**Comment by mvarblow** [comment]
The screenshots are included on #16595. But there's a bit more information I can provide...

The documentation on the (sometimes) missing fa-fw style is here:

https://docs.fontawesome.com/v5/web/style/fixed-width

Here are examples in Orchard Core user menu items where it was correctly included:

* https://github.com/OrchardCMS/OrchardCore/blob/main/src/OrchardCore.Modules/OrchardCore.Users/Views/UserMenuItems-Title.cshtml
* https://github.com/OrchardCMS/OrchardCore/blob/main/src/OrchardCore.Modules/OrchardCore.Users/Views/UserMenuItems-TwoFactor.cshtml
* https://github.com/OrchardCMS/OrchardCore/blob/main/src/OrchardCore.Modules/OrchardCore.Users/Views/UserMenuItems-Dashboard.cshtml
* https://github.com/OrchardCMS/OrchardCore/blob/main/src/OrchardCore.Modules/OrchardCore.Users/Views/UserMenuItems-ChangeEmail.cshtml
* https://github.com/OrchardCMS/OrchardCore/blob/main/src/OrchardCore.Modules/OrchardCore.Users/Views/UserMenuItems-ExternalLogins.cshtml
* https://github.com/OrchardCMS/OrchardCore/blob/main/src/OrchardCore.Modules/OrchardCore.Users/Views/UserMenuItems-Title.DetailAdmin.cshtml

Of course there are the two files (see "Files changed" tab) where it was missing.

**Review by gvkries — APPROVED** [review]

**Comment by Piedone** [comment]
@gvkries when you approve a PR, and especially for someone who doesn't have merge permissions, please also merge right away after waiting for the functional tests to pass. Or, if you're waiting for a second opinion, make it explicit with a comment (and then merge after like 1-2 days if nobody else chimes in, so we don't have PRs lingering indefinitely).

**Pull request merged**
