### PR TITLE
Setup : cleanup code

### PR DESCRIPTION
**Pull request by Skrypt**
The ConnnectionString now uses the same javascript method than the password to show/hide it's fa-eye icon. There was a duplication of methods for doing the same thing in the code (because of my last PR).
Also, fixing the icon for the connectionstring that was reversed ; it was showing fa-eye-slash when the password was displayed.

### CODE REVIEW

**Comment by hishamco** [comment]
Hope it doesn't conflict with eye icon in Microsoft Edge

**Comment by Skrypt** [comment]
lol, this should be covered by the previous CSS I added right?

**Comment by hishamco** [comment]
I though setup has a different style file ;)

**Comment by Skrypt** [comment]
Yeah, we are never too sure to be sure on anything 🙈 
But yeah you are right, good catch 👍

**Review by hishamco — APPROVED** [review]
LGTM

**Pull request merged**
