### PR TITLE
MetaTags module

### PR DESCRIPTION
**Pull request by agriffard**
Provides a way to specify Description and Keywords meta tags:

image

Related to #2148

### CODE REVIEW

**Comment by hishamco** [comment]
This could be SEO related, it could be a feature of SEO, then we could add plenty of SEO services

**Comment by agriffard** [comment]
Should the part be included by default on some content types in the recipes?

**Comment by jptissot** [comment]
@agriffard What about localized Meta tags ? Is this going to be handled by dynamic localization ?

**Comment by Skrypt** [comment]
I think that if you will localize a content item then it will have it's own Meta tab. Then the localized content item will contains it's own meta tag data.

**Comment by hishamco** [comment]
>  Is this going to be handled by dynamic localization ?

I think this should be handled by dynamic localization, while it's changeable

**Comment by agriffard** [comment]
Closing. A bit too simple compared to Seth and EtchUK SEO modules.

**Comment by hishamco** [comment]
@agriffard if you don't mind we can add this to OCC.Modules repo

**Pull request closed without merging**
