### PR TITLE
Update editorconfig file

### PR DESCRIPTION
**Pull request by MikeAlhayek**
Adding suggestion to use file_scoped namespaces.

also disabling @sebastienros 2 favorite feature in C#12.
- [Use primary constructor (IDE0290)](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0290)
- [Use collection expression for fluent (IDE0305)](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0305) so we don't replace readable`.ToArray()` syntax with a crazy syntax `[..item]`

### CODE REVIEW

**Review by Skrypt — APPROVED** [review]

**Comment by hishamco** [comment]
> also disabling @sebastienros 2 favorite feature in C#12.

Why?

**Comment by Skrypt** [comment]
@hishamco I think it was sarcasm.

**Comment by MikeAlhayek** [comment]
@hishamco 

[Use collection expression for fluent (IDE0305)](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0305) will make the code hard to read since it is not natural. Also, the fact that it is a new syntax and not many people are using it or familiar with it will make them guess what it does and could cause issues.

Primary constructors are okay when you know don't need to add any kinds of checks in the constructor, but then what happen if we need to add a check? Do we keep altering between the two styles?

**Comment by Skrypt** [comment]
Primary constructor is just a different simplified syntax but personnally what I find annoying is the suggestion to change all classes to Primary constructors when working with VS Code.

**Pull request merged**
