### PR TITLE
Update YesSql.Core to 2.0.0-beta-1541

### PR DESCRIPTION
**Pull request by hishamco**

### CODE REVIEW

**Comment by agriffard** [comment]
Build error: 
```
C:\projects\orchardcore\src\OrchardCore.Modules\OrchardCore.PublishLater\bin\Release\netcoreapp3.1\OrchardCore.PublishLater.Views.dll
Sql\SqlParser.cs(143,28): error CS1061: 'ISqlBuilder' does not contain a definition for 'WhereAlso' and no accessible extension method 'WhereAlso' accepting a first argument of type 'ISqlBuilder' could be found (are you missing a using directive or an assembly reference?) [C:\projects\orchardcore\src\OrchardCore.Modules\OrchardCore.Queries\OrchardCore.Queries.csproj]
```

**Comment by hishamco** [comment]
I just saw the error, but the test is passed on YesSql repo

**Comment by hishamco** [comment]
Seems @sebastienros removed `WhereAlso` in https://github.com/sebastienros/yessql/commit/68972b2325c0594f98491fd40e2c77bd75dd3b59#diff-437fac8b343ae4d5d77f4c992da01af0L37

I will update `OrchardCore.PublishLater` to react to the changes, but this kind of change is a breaking change in YesSql, unless you set the version to `2.0.0`

**Comment by hishamco** [comment]
I just found it had been used in

- `OrchardCore.Indexing`

https://github.com/OrchardCMS/OrchardCore/blob/1879619df4418ff175a59ba70dcb36bab89fcbb5/src/OrchardCore.Modules/OrchardCore.Indexing/IndexingTaskManager.cs#L185-L207

here I think `Where` clause is enough

- `OrchardCore.Quieries`

https://github.com/OrchardCMS/OrchardCore/blob/1879619df4418ff175a59ba70dcb36bab89fcbb5/src/OrchardCore.Modules/OrchardCore.Queries/Sql/SqlParser.cs#L110-L188

@Skrypt I may need your help in this one

**Comment by sebastienros** [comment]
WhereAlso just became WhereAnd.

**Comment by hishamco** [comment]
> WhereAlso just became WhereAnd.

I notice a `WhereOr` too ;)

**Comment by sebastienros** [comment]
Yeah, maybe I made a mistake, there is another AndAlso ... I might fix it at some point.

**Comment by hishamco** [comment]
I got some unit tests errors that I'm trying to know why they are failing. @sebastienros `WhereAnd` and `WhereOr` are different, that's why I asked before, because they will lead to different result

**Comment by nakamura2000** [comment]
Unit test error is cause by yessql new sql table name alias feature.Graphql module uses original table name when generating sql where clause. so sql error occurs in this test case and graphql query fails. I tried to fix this error in #7468.

**Comment by hishamco** [comment]
@nakamura2000 the error that show up occurs on `OrchardCore.Indexing` when I tested last time

**Comment by sebastienros** [comment]
We looked at it this morning and the issue is that dynamically generated SQL needs to know the alias tables. So GraphQL tests don't work. I will try to understand why graphql is not using the predicates to do it instead of relying on its own mix of SQL generation + predicates. And maybe also provide some public helpers to the yessql aliases tables if they are required.

**Comment by sebastienros** [comment]
Fixed in another PR

**Pull request closed without merging**
