### PR TITLE
Update OpenIddict.Core 4.1.0

### PR DESCRIPTION
**Pull request by hishamco**

### CODE REVIEW

**Review by kevinchalet — APPROVED** [review]
Thanks @hishamco!

Do we have a rough idea of when 1.6 will ship? Folks are starting to complain they can't use OpenIddict 4 with OC: https://github.com/kevinchalet/kevinchalet.github.io/discussions/4#discussioncomment-5070048

**Comment by kevinchalet** [comment]
Awesome, thanks @hishamco! 👍🏻

**Comment by runxc1** [comment]
> Thanks @hishamco!
> 
> Do we have a rough idea of when 1.6 will ship? Folks are starting to complain they can't use OpenIddict 4 with OC: [kevinchalet/kevinchalet.github.io#4 (comment)](https://github.com/kevinchalet/kevinchalet.github.io/discussions/4#discussioncomment-5070048)

I'm also waiting on the OpenIddict upgrade to 4.0 to try using Orchard as a centralized authentication handler.

**Comment by hishamco** [comment]
I presume Seb will merge the PR https://github.com/OrchardCMS/OrchardCore/pull/13416 if all goes well, may be he can do it tomorrow. Yesterday he mentioned that we need to do some testing before release

It's matter of few days :)

**Pull request merged**
