### PR TITLE
Updating to ASP.NET Core 2.1.1

### PR DESCRIPTION
**Pull request by sebastienros**

### CODE REVIEW

**Comment by jtkech** [comment]
It never ends ;)

**Comment by sebastienros** [comment]
Right now it doesn't work because the CI doesn't have the 2.1.1 SDK and hence the 2.1.1 `.All` meta package. I suggest we ship with 2.10, and once 2.1.1 SDK is installed on appveyor and travis we do another release with it.

The other solution is to deploy the 2.1.1 sdk ourselves on the CI scripts, and this will be required for the dev boxes that use Orchard (like 2.1.0 is required) today.

**Comment by jtkech** [comment]
👏 👏

**Comment by jtkech** [comment]
I'm installing 2.1.301 to try it

**Comment by jtkech** [comment]
For infos, just tried, at least i could run a setup, go to the admin, in debug mode, and create an article.

**Pull request merged**
