### PR TITLE
Update Microsoft.AspNetCore.All 2.0.6 dependencies

### PR DESCRIPTION
**Pull request by agriffard**
Update dependencies for
https://www.nuget.org/packages/Microsoft.AspNetCore.All/2.0.6

### CODE REVIEW

**Comment by sebastienros** [comment]
Did you take the file from somewhere specific?
I think we added custom lines to it

**Comment by agriffard** [comment]
No, I updated the versions manually.

**Comment by agriffard** [comment]
I did it because my App using OC.Targets doesn't work anymore. 
Since I ugraded to .NET Core SDK 2.1.101, the Packages folder is not generated anymore.
And I don't know if I have to upgrade Microsoft.AspNetCore.All to version 2.0.6 .

**Comment by agriffard** [comment]
When I launch my application, there are errors like this:
`The type 'Attribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.`

**Comment by agriffard** [comment]
In src\OrchardCore.Build\Dependencies.props , there is still:

```
<!-- This value is deprecated and will be deleted in beta2 -->
    <AspNetCoreVersion>2.0.1</AspNetCoreVersion>
```

but I don't know if I have to change it or remove it.

**Comment by agriffard** [comment]
On another computer, I managed to update the OrchardCore and the Microsoft.AspNetCore.All packages.

On the one that doesn't work, the 2.1.300-preview2-008315 is installed. Is it related?

**Pull request merged**
