### PR TITLE
Inline tenant status

### PR DESCRIPTION
**Pull request by hishamco**

### CODE REVIEW

**Comment by agriffard** [comment]
Nice, I like it.

Can you add a `title="@T[...]"` with the state and use `fa-xs`?

**Comment by hishamco** [comment]
I forgot the title, also I was looking for something like `fa-xs` ;)

Thanks

**Comment by hishamco** [comment]
Seems localization will enforce me to return the switch back :(

**Comment by agriffard** [comment]
May be init the variable cssClass and state in one switch and then use them in the html.

**Comment by hishamco** [comment]
> May be init the variable cssClass and state in one switch and then use them in the html.

It will nothing the localization extractor will unable to find them, while they are dynamic

**Pull request merged**
