### PR TITLE
Remove duplicate ResourceCdnHelperExtensions

### PR DESCRIPTION
**Pull request by TFleury**
Was moved to OrchardCore.ResourceManagement.Core but still present in OrchardCore.ResourceManagement.
OrchardCore.ResourceManagement depends on OrchardCore.ResourceManagement.Core

### CODE REVIEW

**Comment by Skrypt** [comment]
Then it needs to be set as [obsolete] with a message describing what should be done.

**Comment by TFleury** [comment]
I don't think it needs to be marked as obsolete because the 2 versions were in conflict.
If you add reference to both OrchardCore.ResourceManagement and OrchardCore.ResourceManagement.Core to your project, you can't use ResourceUrl helper because the call is ambiguous. That's how I found the issue.

**Comment by Skrypt** [comment]
That's what we generally do all the time. Mark the old class or method with an [obsolete] attribute so that when you try to compile it will either fail or warn you.

**Comment by Skrypt** [comment]
It has been moved by @MikeAlhayek 3 months ago so I think my suggestion is to add an [obsolete] attribute here.

**Comment by TFleury** [comment]
As it is actually, the `ResourceUrl` extension method is unusable if you import OrchardCore.ResourceManagement in your project because there are 2 implementations. It raises a CS0121 ambiguous call.
So no code can rely on OrchardCore.ResourceManagement's implementation.

**Comment by MikeAlhayek** [comment]
Oops! Yeah that should have been removed already. I think you should safly be able to remove it since it has the same namespace and also `OrchardCore.ResourceManagement` depends on `OrchardCore.ResourceManagement.Core`

**Review by Skrypt — APPROVED** [review]
I have not experienced the issue of the ambiguous call yet but I'm approving this one because of it.

**Review by MikeAlhayek — APPROVED** [review]

**Pull request merged**
