### PR TITLE
Regression fix : ContentPickerField

### PR DESCRIPTION
**Pull request by Skrypt**
Fix regression as we can't pick a specific field easily in an eventListener without these data attributes.

### CODE REVIEW

**Comment by jptissot** [comment]
Maybe add it to the localization set content picker as well

**Comment by jptissot** [comment]
And should you pass these values via the event ?

**Comment by Skrypt** [comment]
Good question. It's one or the other. It's quite equivalent.

**Comment by jptissot** [comment]
LGTM

**Comment by Skrypt** [comment]
@sebastienros You ok with that one or you want documentation?

**Pull request merged**
