### PR TITLE
Working on a possible "Versionable" option.

### PR DESCRIPTION
**Pull request by jtkech**
Just a suggestion to have an `Updatable` option.

- Then, when editing a published item of an `Updatable` content type an `Update` button is added.

- This button allows to update the published item without creating a new version.

E.g, with an `Updatable` and `Not Draftable` content type, you have the following.

updateoption

Best.

### CODE REVIEW

**Comment by DanielStolt** [comment]
This would circumvent audit trail.

**Comment by jtkech** [comment]
Oh, yes if you select this option in the admin for a given content type.

**Comment by jtkech** [comment]
So, as a last attempt i propose the simplest solution i found.

- Same UI, same controller actions, no change in content manager ...

- `Draftable`, as before, determines if a content type supports draft versions.

- Then `Updatable` means it doesn't use versioning on publishing (a new draft version is not created).

The implementation is very simple, when publishing an `Updatable` item, it is 1st unpublished then `EditPOST()` update and re-publish it so without creating a new draft version.

Best.

**Comment by jtkech** [comment]
So, in the last suggestion no change in the UI and the main implementation only takes 3 lines.

            // in EditAndPublishPOST().

            if (content.IsPublished() &&
                typeDefinition.Settings.ToObject<ContentTypeSettings>().Updatable)
            {
                await _contentManager.UnpublishAsync(content);
            }

            // then if the update fails the session is cancelled so the item is not unpublished.
            // if ok the item (now a draft) is published but without creating a new draft version.

            return await EditPOST(contentItemId, returnUrl, async contentItem =>
            ...

Maybe not the right place to use `ContentTypeSettings`, but can be changed.

Best.

**Comment by jtkech** [comment]
Conflicts solved.

So here, as a reminder, we give the ability to update an already published item without creating a new draft version (which is then published). This through an `Updatable` option in the admin.

In `EditAndPublishPOST()` if an item is already published and `Updatable`, we just `Unpublish` it before. So, it becomes a draft which is then published without creating any new version.

So, only 3 lines of code using the regular content manager api, no new button ...

**Comment by jtkech** [comment]
**Full Versionable option**

`Updatable` is not a good name, so i've done a full `Versionable` option in a more global but also in a simpler way as i did before. And more consistent when we change options.

- I've only updated `BuildNewVersionAsync()` where, in place of creating a new version, we use the record of the previous one if it exists. And, to be consistent with the current versioning implementation, we swap version numbers so that the latest item always have the highest version number.

---

**Note**

Because we update version numbers, here i'm thinking again about the ability we have to recall an item in the same session and based on some of its states. So, maybe good to check item states consistency in the recall methods. But, if so, notice that it's already related to other states as the published state.

---

**Unrelated to this PR**

There is a scenario which generates duplicated version numbers.

- Save as draft
- Discard the draft
- Save as draft again
- Then you get a duplicate version number

Seems not to be a problem as long as there is only one latest item. But i'm thinking about a versioning tool. So, when we discard a draft, i suggest that we could also set the version number to 0.

Best

**Comment by jtkech** [comment]
Merge last master and solve conflicts.

**Comment by jtkech** [comment]
I needed to merge last master again to solve new conflicts.

**Comment by jtkech** [comment]
Replaced by #1013.

**Pull request closed without merging**
