### PR TITLE
Drive the OpenId ".well-known" URI from the Authority when a value is provided

### LINKED ISSUE #13671: Setting Authority value in OpenId server does not reflect server endpoints in the well-known info
### Describe the bug
When using OpenId Server feature, one of the available settings is **Authority** or **Issuer**. When providing a specific value, the values the URI's showing for `authorization_endpoint`, `token_endpoint`, `introspection_endpoint`, `end_session_endpoint`, `revocation_endpoint`, `userinfo_endpoint`, and `jwks_uri` will still reflect the current site URL. For example, my OC app is running locally using `https://custom-domain.NET` this domain is accessible only when users on the internal network access my app. However, external apps must use `https://custom-domain.COM` in order to get to the same website. To allow external apps to connect to my app, I set the `Issuer` to `https://custom-domain.com/` which is the domain anyone can use to connect to my server. However, the value for the other endpoints still reflect the `.NET` domain not the `.COM` as I would expect. Here is the output of the `https://custom-domain.com/.well-known/openid-configuration`

```
{
  "issuer": "https://custom-domain.com/",
  "authorization_endpoint": "https://custom-domain.NET/connect/authorize",
  "token_endpoint": "https://custom-domain.NET/connect/token",
  "introspection_endpoint": "https://custom-domain.NET/connect/introspect",
  "end_session_endpoint": "https://custom-domain.NET/connect/logout",
  "revocation_endpoint": "https://custom-domain.NET/connect/revoke",
  "userinfo_endpoint": "https://custom-domain.NET/connect/userinfo",
  "jwks_uri": "https://custom-domain.NET/.well-known/jwks",
  "grant_types_supported": [
    "authorization_code",
    "refresh_token"
  ],
  "response_types_supported": [
    "code"
  ],
  "response_modes_supported": [
    "form_post",
    "fragment",
    "query"
  ],
  "scopes_supported": [
    "openid",
    "offline_access",
    "email",
    "phone",
    "profile",
    "roles"
  ],
  "claims_supported": [
    "aud",
    "exp",
    "iat",
    "iss",
    "sub"
  ],
  "id_token_signing_alg_values_supported": [
    "RS256"
  ],
  "code_challenge_methods_supported": [
    "S256"
  ],
  "subject_types_supported": [
    "public"
  ],
  "token_endpoint_auth_methods_supported": [
    "client_secret_basic",
    "client_secret_post"
  ],
  "introspection_endpoint_auth_methods_supported": [
    "client_secret_basic",
    "client_secret_post"
  ],
  "revocation_endpoint_auth_methods_supported": [
    "client_secret_basic",
    "client_secret_post"
  ],
  "claims_parameter_supported": false,
  "request_parameter_supported": false,
  "request_uri_parameter_supported": false,
  "authorization_response_iss_parameter_supported": true
}
```
### Expected behavior
I think anytime an `Authority` settings is different than the current host, the value for  `authorization_endpoint`, `token_endpoint`, `introspection_endpoint`, `end_session_endpoint`, `revocation_endpoint`, `userinfo_endpoint`, and `jwks_uri` should be based on the Issue not the current site.

### PR DESCRIPTION
**Pull request by MikeAlhayek**
Fix #13671

### CODE REVIEW

**Comment by MikeAlhayek** [comment]
@kevinchalet unfortunately, the URL with this PR all return HTTP 404. Is there a way to change the display value of these URLs on `.well-known/openid-configuration` with out returning 404?

**Comment by MikeAlhayek** [comment]
@kevinchalet thanks for your feedback.

I have 2 domains that are pointing to the same app/server. The .net domain is used internally and is bounded to the site in IIS. It is the true domain for the app. However, the .net domain is not exposed externally, instead we use a .com domain that is exposed externally and points to a reverse proxy. So anytime you visit the .com you are routed to the .net via the reverse proxy server. The reverse proxy does not expose all the routes that are available internally. So the problem here is that the openid client is seeing the .net domains which can't connect to them unless the client is hosted internally as well. The client need to see the .com link so it is able to fetch them.

Can you advise of a better watch to expose the .com url while the app is hosted on the .net domain?

Thank you

**Comment by kevinchalet** [comment]
> Can you advise of a better watch to expose the .com url while the app is hosted on the .net domain?

I would strongly advise against using different domains to represent the same server.

The scenario you describe is generally better implementing using a single domain and:
  - 1) Configuring the internal DNS servers to return the internal address of the server when it's accessed by a machine located in the corp network.
  - 2) Configuring the reserve proxies to preserve the original host so that the server that effectively handles the request can set `HttpRequest.Host` to the correct (see `X-Forwarded-Host` & the built-in stuff in ASP.NET Core for more information).

**Comment by MikeAlhayek** [comment]
@kevinchalet I made some more changes but still not able to get it to work. 

I actually ended up disabling the `Reverse Proxy feature` feature as I don't believe it is needed here since the OC app itself isn't the reverse proxy.

When connected internally, any user that targets the `.com` domain is auto directed through the internal network using DNS. Any external traffic that comes from the `.com` reaches the revere proxy server hosted on IIS. This reverse proxy server sets the `X-Forwarded-Host` header to `internal-domain.net` and rewrite all the `https://external-domain.com` urls to `https://internal-domain.net` so they are forwarded correctly.

I believe this setup is working as expected since all the following links work

The link `https://external-domain.com/connect/authorize` behaves identical to `https://internal-domain.net/connect/authorize` 
The link `https://external-domain.com/connect/userinfo` behaves identical to `https://internal-domain.net/connect/userinfo`
...
...
...
The link `https://external-domain.com/.well-known/jwks` behaves identical to `https://internal-domain.net/.well-known/jwks` 

### Problem

However, the `https://external-domain.com/.well-known/openid-configuration` displays internal links not external link. So when the OpenId Client app tried to connect to the server, it sees internal links that it is NOT able to fetch. This is why I though I would somehow need to change all the displayed links listed on the `https://external-domain.com/.well-known/openid-configuration` so that the connecting clients are able to see the accessible external endpoint instead.

Any idea how I can fix this problem?

**Comment by kevinchalet** [comment]
> I actually ended up disabling the `Reverse Proxy feature` feature as I don't believe it is needed here since the OC app itself isn't the reverse proxy.

It's a misnomer: this module doesn't proxy anything, it just restores the original HTTP host and scheme from the `X-Forwarded-*` headers (using ASP.NET Core's built-in forwarded headers middleware). If you host your app behind a reverse proxy, you want to enable this module.

> Any idea how I can fix this problem?

By ensuring the forwarded headers are correct and correctly restored in your OC app: ASP.NET Core's `HttpRequest.Host` property must return the "public" domain, otherwise everything that generates URIs using the HTTP request details - OpenIddict or tons of things in ASP.NET Core itself - won't return the appropriate values.

> This reverse proxy server sets the X-Forwarded-Host header to internal-domain.net and rewrite all the https://external-domain.com urls to https://internal-domain.net so they are forwarded correctly.

It's likely you configured things (very) incorrectly. The `X-Forwarded-Host` is supposed to contain the "address typed by the user"/"seen in the browser tab", not the internal address of the final server that will handle the request. Having to rewrite URLs is the strong sign you're not using the proper approach.

**Comment by kevinchalet** [comment]
(BTW, this stuff isn't specific to OpenID/OpenIddict at all: every app hidden behind a reverse proxy must follow the same rules for things to work correctly)

**Pull request closed without merging**
