### PR TITLE
Optimize some Fluid access patterns

### PR DESCRIPTION
**Pull request by lahma**
* instead of looping 8 converters, use 3 that handle required cases
* directly convert `ViewLocalizer` to `ObjectValue` instead of looping converters
* create fast case for `ZoneTag` evaluating literals

### CODE REVIEW

**Comment by agriffard** [comment]
blog-test.js failed on Linux:
```
 1) Blog Tests
       Displays the home page of the blog recipe:
     AssertionError: Timed out retrying after 4000ms: Expected to find element: `.subheading`, but never found it.
```

Relaunching build to see if it is still happening.

**Comment by lahma** [comment]
This is pretty scary, why only on linux...

**Comment by agriffard** [comment]
> This is pretty scary, why only on linux...

It is just that Functional Tests are only run on Linux.

**Comment by deanmarcussen** [comment]
I had to revert langversion latest recently because when I did it project wide we ran into razor compilation errors on net core 3.

probably ok here, but it’s just static that you used it for I think? So not really necessary and maybe better not to bump just one project, or it gets confusing as to which ones can n can’t have it

**Comment by lahma** [comment]
I like to use the `static` modifier for lambdas for documentation purposes, it shows that it's "being used right", otherwise there could be context capturing which can cause closure instances to be instantiated to hold the state. But I'm fine changing it too, just checked that the project wasn't using Razor targets which seemed to be the reason to disallow usage of latest features.

**Comment by lahma** [comment]
Reverted back to c# 8 and found the probable cause, `LiteralValue.ToString()` is different from `LiteralValue.ToStringValue()` ... Wasn't the first time for me..

**Pull request merged**
