### PR TITLE
Change font-awesome CDN , Fix Error WoklowExecutionContext missing while invoking 'signal_url'

### PR DESCRIPTION
**Pull request by hyzx86**
To fix this problem : https://github.com/OrchardCMS/OrchardCore/issues/3330

### CODE REVIEW

**Comment by sebastienros** [comment]
I don't want to ship font-awesome in its entirety as part of this module.
Discussion on the issue thread.

**Comment by hyzx86** [comment]
Ok, I see

**Comment by hyzx86** [comment]
Fix WorkflowExecutionContext missing while invoking 'signal_url'  #3318

**Comment by jtkech** [comment]
Hi @hyzx86 good catch for the `WoklowExecutionContext` in the `TemplateContext` 👍

**Pull request merged**
