### PR TITLE
Adding OrchardCore.IdGeneration and updating usages

### PR DESCRIPTION
**Pull request by sfmskywalker**
This PR moves `IdGenerator` out of `OrchardCore.ContentManagement` to its own package so it can be reused by other packages (Workflows) without having to take a dependency on `OrchardCore.ContentManagement`.

See issue #1473

### CODE REVIEW

**Comment by sebastienros** [comment]
Isn't there a common OrchardCore project that all modules already use?

**Comment by sfmskywalker** [comment]
There is Shell, Data and Entities (and others that are worse fitting projects). I considered Data, but didn’t seem good either because that thing has more to do with actual data access. Entities then?

**Comment by sebastienros** [comment]
Yeah seems fine. And there is already an abstractions one too. Thanks.

**Comment by sfmskywalker** [comment]
OK. Do you think it's fine to also add a dependency to the Scripting abstraction project? We need it for the `"uuid"` global method.

**Comment by sfmskywalker** [comment]
> And there is already an abstractions one too.
I couldn't find an Entities and Entities Abstractions project, so I just added it to OrchardCore.Entities. Perhaps you intended for me to move things to a different project. If so, let me know.

**Comment by sebastienros** [comment]
Good, can you fix the merge conflict? Then merge without waiting for me or to be blocked by yet another merge PR.

**Pull request merged**
