### PR TITLE
Fixes select culture on setup screen

### LINKED ISSUE #8224: Changing language in setup causes redirect to /undefined
On the initial setup screen change the language results in a redirect to https://localhost:5001/undefined and nothing is displayed.

### PR DESCRIPTION
**Pull request by jtkech**
Fixes #8224

### CODE REVIEW

**Comment by hishamco** [comment]
I'm just waiting for @scleaver to confirm, good to see the quick fix

**Comment by Skrypt** [comment]
Really weird one because I don't see any diff on last @deanmarcussen PR.

**Comment by jtkech** [comment]
It is used in the setup.js

    function setLocalizationUrl() {
        var culturesList = document.getElementById('culturesList');
        window.location = culturesList.options[culturesList.selectedIndex].dataset.url;
    }

Was changed through this commit

https://github.com/OrchardCMS/OrchardCore/commit/87b5619a8a4e1a1a1e5e854d323b9191a4c052f8#diff-8f82e7049a3b0c76198aebcf77e1fa9eb85db07ff4b0325a39e81d370f5444b0

**Comment by Skrypt** [comment]
Ahhh, I see, I replaced it while I should'nt have.

**Comment by scleaver** [comment]
> I'm just waiting for @scleaver to confirm, good to see the quick fix

Sorry @hishamco was at the beach!

**Comment by hishamco** [comment]
No problem, while the issue was resolved ;)

**Pull request merged**
