### PR TITLE
Pool StringBuilder instances used by LiquidTemplateManagerExtensions

### PR DESCRIPTION
**Pull request by lahma**
* adding same implementation (internal) that Liquid uses for StringBuilderPool, could be referenced in multiple projects later if needed
* I'll leave performance benchmarks to more able people 🙂

### CODE REVIEW

**Comment by sebastienros** [comment]
You actually already implemented it in Fluid, but in an extension method on `IFluidTemplate`, I need to see why it's not on a `string` though.

**Comment by sebastienros** [comment]
https://github.com/sebastienros/fluid/commit/c6854a63999d4d8be487fba36f52434e58b96e4b#diff-4ae67e91aced0f7f4c7533ce74444fec

**Comment by sebastienros** [comment]
I see why we can't use this from Fluid, because the ILiquidManager interface doesn't provide an easy access to it, just the `TextWriter` one. The implementation of this interface is good, but the extension method needs to use the method from the interface, so that makes sense here.

Note that in liquid I optimized the pool with a default buffer size that worked best in my tests.
Maybe I should expose an overload with a `string` result instead of the `TextWriter` to allow for two optimized implementations instead. This way the method could reuse the logic in Fluid, and we wouldn't have two StringBuilder pools.

**Comment by sebastienros** [comment]
I am writing the fix I am suggesting.

**Comment by lahma** [comment]
I can see that `FluidView` would benefit from writing directly to stream without materializing string at least. Feel free to create a more refined version of the improvement and close this, This was the easy route 🙂

**Comment by sebastienros** [comment]
Yes, I am sure there are places we shouldn't use strings. But this one is in Fluid directly, right?

**Comment by lahma** [comment]
Indeed, seems that Orchard's side is using the materialized string.

**Pull request closed without merging**
