### PR TITLE
Fix TheAdminTheme layout margin and padding

### PR DESCRIPTION
**Pull request by MikeAlhayek**

### CODE REVIEW

**Comment by hishamco** [comment]
Please screenshot before & after

**Comment by MikeAlhayek** [comment]
There isn't visual difference. Just better layout since this uses padding not margin. So the scroll bar shows only when the screen in full. 

Also, instead of using 15px padding, we use 1rem just like bootstrap for consistency.

Feel free to checkout the PR.

**Review by hishamco — APPROVED** [review]
> Feel free to checkout the PR.

I TRUST you, I have many many PRs to complete :)

**Comment by hishamco** [comment]
@MikeAlhayek I just noticed UI issue

Screenshot 2024-01-23 095459

**Comment by MikeAlhayek** [comment]
What is the issue?

**Comment by hishamco** [comment]
Look to the button underneath, seems the padding or margin almost 0

**Pull request merged**
