### PR TITLE
Author field perhaps is null

### PR DESCRIPTION
**Pull request by hyzx86**

### CODE REVIEW

**Review by MikeAlhayek — COMMENTED** [review]
I think even `Owner` can be nullable if the user provider no id during a recipe import.

**Review by MikeAlhayek — APPROVED** [review]

**Comment by hyzx86** [comment]
Hi @Skrypt , what do you think ? I remember you seem to have related PR, about index table fields.

**Review by sebastienros — APPROVED** [review]

**Comment by hyzx86** [comment]
> I think even `Owner` can be nullable if the user provider no id during a recipe import.

Yes  Indeed  ，There are some situations in my content items where the owner is empty, such as content items created by workflow or background threads. In order to prevent graphql from making errors, I can only exclude this field. In fact, rendering this field in graphql has no practical meaning. Unless the user wishes to send further requests through graphql's request results

**Comment by hyzx86** [comment]
@MikeAlhayek  , I  pushed a new PR https://github.com/OrchardCMS/OrchardCore/pull/15477

**Pull request merged**
