### PR TITLE
Bootstrap 5.0.2

### PR DESCRIPTION
**Pull request by agriffard**
https://www.npmjs.com/package/bootstrap/v/5.0.2
https://github.com/twbs/bootstrap/releases/tag/v5.0.2

Changed in Resources and TheTheme.

### CODE REVIEW

**Comment by agriffard** [comment]
I tried to use bootstrap 5.0.2 in the setup too but I don't know why, there is an error in setup.js related to popperjs so the recipes dropdown does not work for the moment.

Some help would be appreciated to fix it.

**Comment by agriffard** [comment]
image

**Comment by agriffard** [comment]
I am not sure why `bootstrap-scss` i still used.

**Comment by agriffard** [comment]
@Skrypt Can you please review this PR when you have time?

**Review by Skrypt — APPROVED** [review]

**Pull request merged**
