### PR TITLE
Upgrade to GraphQL 7.2.2

### LINKED ISSUE #15104: Update GraphQL for .NET to latest
### Is your feature request related to a problem? Please describe.
[GraphQL for .NET](https://github.com/graphql-dotnet/graphql-dotnet) is currently on v7.7.2 while we use 4.8.0. While this is not hugely old (it [was released in March 2022](https://github.com/graphql-dotnet/graphql-dotnet/releases/tag/4.8.0)) but it still is, and we're too much behind.

### Describe the solution you'd like
Upgrade to the latest version. This will be a pain I'd guess. Perhaps we could ask somebody from the GraphQL for .NET team to help?

### Describe alternatives you've considered
I really don't know of any.

### PR DESCRIPTION
**Pull request by hishamco**
Fixes #15104.

### CODE REVIEW

**Comment by hishamco** [comment]
@agriffard this might need some review and fixing the broken unit tests

**Comment by hishamco** [comment]
@agriffard I might create incremental PRs to make the update easier, seems there are a lot of changes to move into `7.2.2`

**Comment by agriffard** [comment]
Ok, we haven't updated the dependencies for a long time, this is not gonna be easy.

The latest versions are:
https://www.nuget.org/packages/GraphQL/7.6.1
https://www.npmjs.com/package/graphql/v/16.8.0
https://www.npmjs.com/package/graphiql/v/3.0.5

**Comment by hishamco** [comment]
> Ok, we haven't updated the dependencies for a long time, this is not gonna be easy.

I'm struggling to update into `5.0.0`, there are many errors and breaking-changes, hope to fix them all

**Comment by Piedone** [comment]
Do you intend to address https://github.com/OrchardCMS/OrchardCore/issues/12295 here too?

**Comment by hyzx86** [comment]
@hishamco 
It is temporarily found that the duplicate registration is checked in this PR
https://github.com/graphql-dotnet/graphql-dotnet/pull/3248

I merged the main branch from your branch here
https://github.com/hyzx86/OrchardCore/tree/hishamco/upgrade-graphQL

**Comment by hishamco** [comment]
@Piedone is there a way that @hyzx86 can commit to my PR or is it required to be a member of OC?

**Comment by Piedone** [comment]
They need to be a member. However, you can create a fork under your GH profile and invite Tony to collaborate there.

**Comment by hishamco** [comment]
@hyzx86 if there are changes you want to add to my PR you could suggest them so I can accept the commits from you to get credits for your contributions :)

**Comment by hyzx86** [comment]
> @hyzx86 if there are changes you want to add to my PR you could suggest them so I can accept the commits from you to get credits for your contributions :)

OK,

Can I apply to be an OC project member?

**Comment by hishamco** [comment]
> Can I apply to be an OC project member?

This is not to apply, we usually recognize extraordinary contributors who have an impact on the project

**Comment by hyzx86** [comment]
> > Can I apply to be an OC project member?
> 
> This is not to apply, we usually recognize extraordinary contributors who have an impact on the project

All right. Got it.

**Comment by hishamco** [comment]
Anyhow if you keep active on GraphQL I will give you my vote 👍🏼

**Comment by hyzx86** [comment]
> Anyhow if you keep active on GraphQL I will give you my vote 👍🏼

No problem ，I have been busy at work these days.

**Comment by hyzx86** [comment]
@hishamco  here https://github.com/OrchardCMS/OrchardCore/pull/15127

**Comment by hyzx86** [comment]
@hishamco Why not just upgrade to the latest version, instead of just upgrading to 7.2? Is it because the change is too big?

**Comment by hishamco** [comment]
Too BiG and many breaking changes

**Pull request closed without merging**
