### PR TITLE
Fix html in autoroute  views to remove improper use of fieldset.

### PR DESCRIPTION
**Pull request by scleaver**
Fixes use of fieldset in autoroutepart. Part of #2809. Will move through other modules.

### CODE REVIEW

**Comment by sebastienros** [comment]
Everything looks the same before and after?

**Comment by scleaver** [comment]
@sebastienros only two files have changed in this PR cause I am working module by module as suggested (although I think I might do a couple of  modules at a time).

I removed the fieldset in 2 files and replaced with div - see below.

image

**Comment by scleaver** [comment]
Yes I made sure that this didn't affect how it looked before and after - it was purely a semantic. So all good.

Do you want me to use this PR to apply the rest of the html changes rather than individual PRs?

**Comment by sebastienros** [comment]
I merged the other PR so you can deal with a single one now.

**Pull request closed without merging**
