### PR TITLE
Add thanks issue template, and improve the bug and feature request templates (Lombiq Technologies: OCORE-205)

### LINKED ISSUE #16894: "Thanks" issue type to let people express their thanks
### Is your feature request related to a problem? Please describe.
As a maintainer, it's good to feel appreciated, and it's also great to see people using Orchard Core. The activity around the project shows that, as well as stars, but there's another cool way.

### Describe the solution you'd like
I've seen this at the [Twitter, together!](https://github.com/twitter-together/action) project. Their [thanks issue template](https://github.com/twitter-together/action/blob/main/.github/ISSUE_TEMPLATE/04_thanks.md) lets people express their thanks, while also gathering some information about how people use the project.

Such issues are then [listed with the same label](https://github.com/twitter-together/action/issues?q=label%3Athanks+).

### Describe alternatives you've considered
Just a quick idea, haven't put much more thought into it.

### PR DESCRIPTION
**Pull request by Piedone**
Fix #16894

### CODE REVIEW

**Comment by MikeAlhayek** [comment]
Are we seeing an increase in "Thank you" issues that we need to dedicate a template for it?

**Comment by Piedone** [comment]
We have no thank you issues since we don't allow thank you issues now. This is to inspire people to express them liking OC.

**Comment by MikeAlhayek** [comment]
I doubt this is useful at all. but feel free to merge it and see how many thank you we'll see. and why would we even need that? we'll just start managing thank you notes

**Comment by Piedone** [comment]
I elaborated the rationale under the issue and also yesterday at the meeting: it's about gathering positive feedback (which will help us keep contributing) and data about how people use OC.

But OK then. We'll see if people will submit such issues, and if it's useful, but there's really no cost to try it.

**Pull request merged**
