### PR TITLE
Add [Feature] attribute to the permission providers that are associated with a feature in a module

### PR DESCRIPTION
**Pull request by MikeAlhayek**
Based on the findings in #15782 the `ShellContainerFactory` associate types based on the `Feature` attribute.

https://github.com/OrchardCMS/OrchardCore/blob/dc6729bfe9c06c4423e0a6e2af92625dda6d1108/src/OrchardCore/OrchardCore/Shell/Builders/ShellContainerFactory.cs#L150-L158

Applying `[Feature]` attribute to the permissions that are registered with a feature is important since `RoleUpdater` service used `ITypeFeatureProvider` to check if the permission provider is associated with a given feature ID.

https://github.com/OrchardCMS/OrchardCore/blob/9688beb1c7d2f950971293244f92296627c09fdd/src/OrchardCore.Modules/OrchardCore.Roles/Services/RoleUpdater.cs#L57

## Summary by CodeRabbit

- **New Features**
	- Added feature attributes to enhance module-specific permissions across various OrchardCore modules including Facebook Pixel, Google Analytics, Google Authentication, Google Tag Manager, Azure Media Storage, Media Cache, SQL Queries, and Shortcodes Templates.
- **Bug Fixes**
	- Corrected a typo in a comment within the OrchardCore.Seo module.
- **Chores**
	- Removed unnecessary empty lines in the OrchardCore.ArchiveLater and OrchardCore.PublishLater modules.
- **Revert**
	- Removed the ReCaptcha feature attribute from the Startup and DeploymentStartup classes in the OrchardCore.ReCaptcha module.

### CODE REVIEW

**Review by gvkries — APPROVED** [review]
LGTM 👍

**Comment by gvkries** [comment]
We may still have a problem with types that are used by more than one feature, e.g. `OrchardCore.Microsoft.Authentication.Permissions`.

**Comment by Piedone** [comment]
Let's wait with https://github.com/OrchardCMS/OrchardCore/pull/15793 for this, because if we have that then no attributes are necessary.

**Comment by MikeAlhayek** [comment]
@Piedone this should be merged. I don't think https://github.com/OrchardCMS/OrchardCore/pull/15793 will be ready anytime soon. When that PR is ready, we'll be able to remove the new [Feature()] attribute from all classes except from controller and startup. But this also mean existing attributes. So this is a good fix that we should take.

**Comment by Piedone** [comment]
I'll try to wrap my head around https://github.com/OrchardCMS/OrchardCore/issues/15782 and get back here.

**Pull request closed without merging**
