### PR TITLE
Adjust the crosshair for better visibility across backgrounds

### LINKED ISSUE #7514: Slightly punchier crosshairs for crop center
Can I offer up a slightly easier to see crosshairs for the crop center UI?

Original version (i'm slightly red green colour blind and can hardly see this - it is over the spaceman's helmet visor for those like me):
Screen Shot 2020-11-05 at 7 28 39 am

My suggestion - 80x80px custom SVG in white with ever so slight shadow to give it more punch on light backgrounds:
Screen Shot 2020-11-05 at 8 06 44 am
Screen Shot 2020-11-05 at 8 06 53 am
Screen Shot 2020-11-05 at 8 07 00 am

Modifying the CSS a little I can center it right on the pointer when placed.

@deanmarcussen (I know this is your baby) and @Skrypt

### PR DESCRIPTION
**Pull request by scleaver**
Fixes #7514 

Changed colour to white, increased the size to 1.875rem (30px) and added black border to SVG via CSS with good browser support: https://css-tricks.com/almanac/properties/s/stroke/#browser-support

Used CSS translate to modify the centre location so it matched the cursor click.

Screen Shot 2020-11-13 at 12 59 18 pm

### CODE REVIEW

**Comment by deanmarcussen** [comment]
What does it look like when the anchor is dragged to the bottom / top (or sides)?
There is some js which moves it by a few pixels so it always appears inside the box. (because it didn't work with against white backgrounds when it came outside the box. )

But with the bigger icon it probably doesn't need that adjustment - so it can probably be remove, and could display half outside the box.

Because often you will want to make the anchor as low on an image as possible.

**Comment by scleaver** [comment]
@deanmarcussen  adjusted the js as discussed. Should be good to go.

anchors2

**Comment by netwavebe** [comment]
Looks good 👍 

The current pink(ish) anchor is hard to see on red, this should be better!

**Review by deanmarcussen — APPROVED** [review]
nice :)

**Pull request merged**
