### PR TITLE
Make contentpicker vue.js component reusable

### PR DESCRIPTION
**Pull request by Skrypt**
This allow to reuse the content picker vue.js component to be reused later on to pre-select values based on conditions that someone could require.

Example of usage (custom create.cshtml file in a custom dashboard module) : 

```C#
@using OrchardCore.ContentManagement
@using OrchardCore.ContentManagement.Metadata
@using OrchardCore.Mvc.Utilities
@using System.Security.Claims;

@inject IContentDefinitionManager ContentDefinitionManager

@{
    ContentItem contentItem = Model.ContentItem;
    var contentTypeDefinition = ContentDefinitionManager.GetTypeDefinition(contentItem.ContentType);
    var typeDisplayName = contentTypeDefinition?.DisplayName ?? contentItem.ContentType.CamelFriendly();

    // We use the current user account and determine if it has an Advertiser profile
    Dictionary<string, object> parameters = null;
    string owner = "*";
    ContentItem advertiser = null;

    if (User.FindFirst(ClaimTypes.Role).Value == "Advertiser")
    {
        owner = Context.User.Identity.Name;
        parameters = new Dictionary<string, object>() {
                    { "email", owner }
            };

        //An advertiser is an extended User profile.
        var results = await Orchard.ContentQueryAsync("AdvertiserQuery", parameters);
        if (results.Count() > 0)
        {
            advertiser = results.First();
        }
    }

}
<style asp-src="~/OrchardCore.Contents/Styles/Contents.min.css" debug-src="~/OrchardCore.Contents/Styles/Contents.css"></style>
<script asp-name="jquery-ui" at="Foot"></script>

<section>
    <h1>@RenderTitleSegments(T["New {0}", Html.Raw(T[typeDisplayName].Value)])</h1>
    <form asp-action="Create" asp-route-returnUrl="@Context.Request.Query["ReturnUrl"]" method="post" enctype="multipart/form-data">
        @Html.ValidationSummary()
        @await DisplayAsync(Model)
        <input type="hidden" name="id" value="@contentItem.ContentType">

        @await Html.PartialAsync("_MediaApplication")
    </form>
    @if (advertiser != null)
    {
        <script at="Foot">

            // THIS IS THE INTERESTING PART
            // I'M CALLING A Vue.js component from a JQuery document ready call
            $(function () {

                //We find here the proper contentPicker in the javascript array that contains all our vue 
                //component instances. We find it by "id". We could also use obj.$ref.includes("Advertiser") if 
                //we mark the component with a ref="someid".
                var advertiserContentPicker = contentPickers.find(obj => {
                    return obj.$el.dataset.field.includes('Advertiser');
                })

                // We create an object that can be used by the ContentPicker component.
                var selectedAdvertiser = { contentItemId: '@advertiser.ContentItemId', displayText: '@Html.Raw(advertiser)', hasPublished: @advertiser.IsPublished().ToString().ToLower() };

                //We call the onSelect of the content picker and pass our object as the selected item.
                advertiserContentPicker.onSelect(selectedAdvertiser, null);
            });

        </script>
    }
</section>
```

Here the only thing that would make this less prone to errors is if we could have found the content picker instances by their ref="someid" that would have been the same id as :  

https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.ContentFields/Views/ContentPickerField.Edit.cshtml#L30
```Razor
<div id="@vueElementId" ref="@vueElementId" class="content-picker-default">
```

The id of the content picker component here changes on every refresh of that page.

The same concept could be used for any other Vue.js components that we have so that we can reuse them, extend them too also.

@matiasmolleja @sebastienros @agriffard @jptissot

### CODE REVIEW

**Comment by Skrypt** [comment]
Fixes #3547

**Comment by sebastienros** [comment]
add more data attributes and merge

**Comment by matiasmolleja** [comment]
If this is ready I would like to see this merged. 
I'm working on a new admin menu type, "content item" admin menu. To let the user choose a content item instead of writing its url. I'm planning to reuse the content picker as part of the editor.
Having this PR merged will prevent conflicts later.

@Skrypt  @sebastienros  what do you think?

**Comment by sebastienros** [comment]
But we said we would add some `data-`

**Comment by Skrypt** [comment]
Yes sorry I've been busy doing things on the house. Will work on it tonight and merge it. Should be quite simple change.

**Comment by Skrypt** [comment]
I changed the example.
Adding data-properties to a Vue.js component will make those values available on the component by doing component.dataset.field or component.dataset.part

Here is what I did for searching by field name in the components. Using a standard jquery selector will not work to retrieve a component instance. You need to find it in that array of instances.


```js
                var advertiserContentPicker = contentPickers.find(obj => {
                    return obj.$el.dataset.field.includes('Advertiser');
                })
```

**Pull request merged**
