### PR TITLE
Add role description

### LINKED ISSUE #926: Add hints with roles' descriptions to the screen of user editing, and creating
There are 5 roles now, but what each role means user can only guess
Could you give me descriptions (I guess they exist in Orchard 1) and how to correctly put them (localization) so I will add them?

### PR DESCRIPTION
**Pull request by hishamco**
Fix #926

### CODE REVIEW

**Comment by hishamco** [comment]
@agriffard where the predefined roles have been created? So I can add its description

**Comment by sebastienros** [comment]
Can you add this in the deployment steps (import and export).

**Comment by hishamco** [comment]
Sure

**Comment by hishamco** [comment]
:shipit:

**Pull request merged**
