### PR TITLE
Lucene random sort order

### LINKED ISSUE #6916: Support random sort order for Lucene queries
Add support for random sort order results of Lucene queries. I have a PR that enables this behavior.
I was wondering how to add this support to the documentation.

### PR DESCRIPTION
**Pull request by ArieGato**
fixes #6916 

Add support for random sort order to Lucene queries.

example:
```
{
  "query": {
    "term": { "Content.ContentItem.ContentType": "BlogPost" }
  },
  "sort": [
    { "Content.ContentItem.CreatedUtc": { "order": "random" } }
  ],
  "size": 10
}
```

### CODE REVIEW

**Comment by deanmarcussen** [comment]
@Skrypt are you taking a look?

In principle looks fine to me, the `random` sort operator is what we had in O1 for SQL, so when someone implements the SQL version it would match up.

**Comment by ArieGato** [comment]
I'm currently looking at YesSql because I think that's the place for the Sql random sort order.

**Review by Skrypt — DISMISSED** [review]
LGTM. I don't think there is any issue merging this PR if it works as intended. Though, if we merge it we need to document it since it is a different way than what ElasticSearch themselves do. Please, let's also implement the proper ES cloned method while we are at it. If it works as good as the `script_score` method then we will be able to evaluate it and have both method.

**Comment by sebastienros** [comment]
Do you think that having this syntax would be better:

```
{
  "query": {
    "term": { "Content.ContentItem.ContentType": "BlogPost" }
  },
  "sort": [
    { "Content.ContentItem.DisplayText": { "order": "desc" } },
   "random"
  ],
  "size": 10
}
```

Which is just using the __string__ `"random"` as a "SortField". As long as there are no other field named "random". Or we could use something like "$random" to prevent any conflict.

**Comment by agriffard** [comment]
Please solve the conflicts.

**Comment by ArieGato** [comment]
something went wrong with my merge :-(
How can I undo the commit?

**Comment by hishamco** [comment]
> How can I undo the commit?

`git reset --soft HEAD~1`

Then you can enforce push

`git push -f`

**Comment by aminmohammadi05** [comment]
> 

Hello dear [sebastienros](https://github.com/sebastienros)
About this problem I have asked many questions in mane places such as Stackoverflow and Discussion section of this github repository, But no one helped me. I don't know whether this problem has been solved by now or not. Would you please provide a clear example?

**Comment by Piedone** [comment]
I sincerely apologize for us taking so much time here. I checked out the PR, going over old ones, and this would be quite useful. However, it needs to be updated to the latest `main`, documented, and perhaps also implemented in Elasticsearch (we have Elastic support too since then).

Is this something you'd like to revisit @ArieGato or should we close?

**Comment by ArieGato** [comment]
Afaik @Skrypt rejected this PR. Something to do with not complying with OpenSearch. Maybe he can give some clarity ont this. And it has been quite a long time since I made this PR.

I can always have a go at it, but only if you are absolutely sure that it is needed. Otherwise the PR can be closed.

**Comment by Piedone** [comment]
Thanks for your quick reply! Yes, his would definitely need substantial updates along the lines of what I've written, which is in line what Jasmin told (also see https://github.com/OrchardCMS/OrchardCore/issues/6916#issuecomment-692275442).

While I think this would be useful, I wouldn't say absolutely sure, it's not a critical feature (and apparently not many people are looking for it).

**Comment by ArieGato** [comment]
I’ll have a look if I can find some time to fix this correctly. I’ll have to dive into it again.

**Comment by Piedone** [comment]
Thank you, let us know here if you need some pointers.

**Comment by ArieGato** [comment]
I’ve had a look at the script score logic. I’m not sure how I can port this to Lucene. Also I don’t have the time it would take to achieve this. From my part this PR can be abandoned.

**Comment by Piedone** [comment]
I see, thanks, OK then.

**Pull request closed without merging**
