### PR TITLE
Updating Trumbowyg semantic defaults

### LINKED ISSUE #3817: Wysiwyg editor converts div to p tag
@sebastienros How to prevent the conversion of div to p tag automatically  in wysiwyg editor ?

### PR DESCRIPTION
**Pull request by jonvee**
Fixes #3817
I didn't delete or comment out this line as that is how it's described in the trumbowyg docs, and it may prevent other plugins like clean paste from potentially doing there own conversions.

### CODE REVIEW

**Comment by jrestall** [comment]
Hey @jonvee, it looks like you've checked in a bunch of obj build files with this pull request.

I would expect this change to only modify,

-  src/OrchardCore.Modules/OrchardCore.Resources/Assets/trumbowyg/js/trumbowyg.js 
- src/OrchardCore.Modules/OrchardCore.Resources/wwwroot/Scripts/trumbowyg.js 
- src/OrchardCore.Modules/OrchardCore.Resources/wwwroot/Scripts/trumbowyg.min.js

Probably best to create a new pull request that only modifies those 3 files.

**Comment by jonvee** [comment]
Sorry, first time submitting a PR like this... still trying to figure it out ;P

**Comment by jonvee** [comment]
No idea how to remove the extra files from my fork/commit/pull request...

**Comment by jrestall** [comment]
I'm no git expert but this is what I would do. Since you've committed directly to your dev branch it makes this a little trickier, normally you should work off a feature branch and keep dev clean so you can pull updates from the OrchardCore source or create clean new branches.

1. Assuming you have checked out the dev branch still, create a feature branch from the previous commit on dev by running this command then checkout:
git branch jonvee/trumbowyg HEAD~1
git checkout -b  jonvee/trumbowyg
2. Make the change to Assets/trumbowyg/js/trumbowyg.js and then run the gulp pipeline.
3. Commit the 3 changed files (You can do this from Visual Studio, just make sure you select just those 3 files and stage them, then commit).
4. Push the commit to your repo.
5. Open the PR via GitHub.

**Comment by jonvee** [comment]
@jrestall thanks for the tips! Hopefully my latest PR works.
Funny how the process in this case is exponentially more complicated than the actual fix ;p

**Comment by jrestall** [comment]
@jonvee Glad you figured it out! Now that you've learnt the process future PRs will be a lot easier :)

**Pull request closed without merging**
