### PR TITLE
Use readonly properties in file store entries

### PR DESCRIPTION
**Pull request by hishamco**

### CODE REVIEW

**Comment by deanmarcussen** [comment]
Why? was there a bug and it wasn't working?

Has it been tested?

**Comment by hishamco** [comment]
Actually there's no bug, but there's no need for the baking fields here nothing more

**Comment by deanmarcussen** [comment]
> Has it been tested?

So not tested then?

**Comment by hishamco** [comment]
> Has it been tested?

I can make unit tests to test them, but I find that there's no need while the change is not too much, I will write the unit tests then ...

**Comment by deanmarcussen** [comment]
> I can make unit tests to test them, but I find that there's no need while the change is not too much, I will write the unit tests then ...

I wasn't asking for unit tests, just to know whether you connected to blob storage (or blob development storage) and it still works?

There has been so many issues with prefixing and semantics with blob storage that I'm reluctant to approve a change if it hasn't been tried. (Knowing that if it breaks something I'll have to come along and figure out why)

**Comment by hishamco** [comment]
Got your point Dean, I will try to use blob development storage if there's a change, coz I didn't work with with yet

Thanks

**Comment by agriffard** [comment]
Can you please finalize it or close it if it is not meant to be merged?

**Comment by hishamco** [comment]
I'm not able to connect to blob storage since then, that's why I didn't update the status, but the changes that I made doesn't affect nything it's just refactoring

**Comment by agriffard** [comment]
Closing while it is not tested. Reopen if needed.

**Pull request closed without merging**
