### PR TITLE
AddModularFolderRoute() convention for razor pages.

### LINKED ISSUE #1434: Not possible to configure module's root path for Razor Pages?
We're using OrchardCore Modules in a custom ASP.NET Core app. It's working nicely but from what we have gathered, there doesn't seem to be a way to set a custom root path for a module?

What I mean that if we have a module:
ProjectName.Modules.Account

And the ProjectName.Modules.Account contains ~15 Razor pages, we can access these using:

http://localhost/ProjectName.Modules.Account/MyTestPage
http://localhost/ProjectName.Modules.Account/AnotherTestPage
etc.

What we would like to have is that each Razor page inside the module is available from the following url:

http://localhost/Account/*

So for example:

http://localhost/Account/MyTestPage
http://localhost/Account/AnotherTestPage

The AddModularPageRoute -functionality seems to be only for single pages. So we could write something like the following for each page but it seems little tedious:

options.Conventions.AddModularPageRoute("/ProjectName.Modules.Account/Pages/TestPage", "Account/TestPage");

Any way to do this? Thanks in advance.

### PR DESCRIPTION
**Pull request by jtkech**
Fixes #1434 

- So, now we have the following default urls

      /.Modules/OrchardCore.Demo/Pages/Hello
      /OrchardCore.Demo/Pages/Hello
      /OrchardCore.Demo/Hello

- **Now we have a new `RazorPagesOptions` configuration helper**, so if we use e.g

      options.Conventions.AddModularFolderRoute("/OrchardCore.Demo/Pages", "Demo");

    We have these new urls.

      /Demo/Hello
      /Demo/OtherPage
      ...

- And we can still use e.g

      options.Conventions.AddModularPageRoute("/OrchardCore.Demo/Pages/Hello", "Hello");

    To have this url

      /Hello

**Update**

- And now if you use the following by passing an empty folder route or just `/`

      options.Conventions.AddModularFolderRoute("/OrchardCore.Demo/Pages", "");

    We have these new urls.

      /Hello
      /OtherPage
      ...

- Finally, by doing the following you define a new home page.

      options.Conventions.AddModularPageRoute("/OrchardCore.Demo/Pages/Hello", "");

### CODE REVIEW

**Comment by sebastienros** [comment]
Needs documentation somewhere.

**Comment by sebastienros** [comment]
We should use the name of the feature/module if specified instead of the module id, like it's done in O1.

**Comment by jtkech** [comment]
@sebastienros 

> We should use the name of the feature/module if specified instead of the module id

Okay, so i will use the name because it is equal to the id when not specified.

I think you're talking about default routes, so assuming the name is `Demo`.

      /.Modules/OrchardCore.Demo/Pages/Hello  // i think better to keep this one as it is
      /OrchardCore.Demo/Pages/Hello           // maybe also this one, let me know
      /Demo/Hello                             // then use the name for this one

Then, maybe better to use the original route when defining new mapping routes.

      options.Conventions.AddModularFolderRoute("/OrchardCore.Demo/Pages", "FolderPath");
      options.Conventions.AddModularPageRoute("/OrchardCore.Demo/Pages/Hello", "SomeRoute");

**Comment by jtkech** [comment]
@sebastienros 

- So, now we still have the following underlying default routes

      /.Modules/OrchardCore.Demo/Pages/Hello
      /OrchardCore.Demo/Pages/Hello

And we also have a default route based on the module **name** specified in the manifest.

      /Orchard Demo/Hello

And if the name is not specified

      /OrchardCore.Demo/Hello

**Pull request merged**
