### PR TITLE
Use file-scoped namespace (IDE0161)

### PR DESCRIPTION
**Pull request by MikeAlhayek**
This will break every PR we have.

To fix the PR, open command line and execute the following code 

```
dotnet format --diagnostics IDE0161 --severity info
```

This should fix the PR.

### CODE REVIEW

**Comment by hishamco** [comment]
I already did something similar in the past, and then @sebastienros or someone else told me that such this would break almost all the PRs

I prefer to do this incrementally to avoid break others PRs

**Comment by MikeAlhayek** [comment]
yes I agree with you. it'll break every PR. That's why I added the command that every PR will have to apply to fix the conflicts all at once. 

It's something we discussed during the meet today. Also, check out the 2 submitted PRs around formatting which will cause the same affect for all PRs.

**Comment by Skrypt** [comment]
We should probably have all of these figured out in a single PR instead. CI steps included if any.

**Comment by Piedone** [comment]
Yeah, it would be nice to apply all such formatting changes at once, because then at least we break all PRs just once. And CI is definitely needed, so we don't re-introduce the same issues. See https://github.com/OrchardCMS/OrchardCore/issues/7950.

**Comment by MikeAlhayek** [comment]
Yes. I think @Skrypt is going to create an action to apply the same fix across PR. I also think he wants to merge this with his PR. I am closing this one for now.

**Pull request closed without merging**
