### PR TITLE
Move Title to Navbar header

### LINKED ISSUE #3688: Organize headers in the admin site pages
The headers in the admin site pages should be organized from h1 to h6

### PR DESCRIPTION
**Pull request by agriffard**
Fix #3688

Zone NavbarTitle in admin layout.

To do it everywhere we will need to update all the h1s in every admin views like this:
`<zone name="NavbarTitle"><h1>@RenderTitleSegments(T["Page title"])</h1></zone>`

### CODE REVIEW

**Comment by agriffard** [comment]
image

**Comment by hishamco** [comment]
How it look like in the mobile? Also we think we need to apply it everywhere if the team agree

**Comment by agriffard** [comment]
image
It looks fine on mobile too.

**Comment by agriffard** [comment]
Done. h1 wrapped by `<zone name="Title"></zone>` in 85 admin views.

**Comment by agriffard** [comment]
Merge it and then we will wrap the breadcrumbs the same way to render them in a specified zone and then decide where we display this zone in the admin.

**Comment by Skrypt** [comment]
I think the idea was to remove the header top nav at some point just to make the title move up.

**Comment by agriffard** [comment]
We might still want a navbarTop zone de to inject some shapes, like an admin culture picker for example.

**Comment by Skrypt** [comment]
I don't think we require to have a navbar for that. My point is that it's a waste of space right now it just adds an empty white space on top of the admin layout.

**Pull request merged**
