### PR TITLE
Liquid themes shouldn't need Razor support for MVC

### PR DESCRIPTION
**Pull request by hishamco**

### CODE REVIEW

**Comment by jtkech** [comment]
We can mix razor and liquid files, originally the blog theme was only composed of razor files that we migrated step by step to liquid. So maybe they are not Liquid themes but themes that currently only use Liquid files.

**Comment by hishamco** [comment]
As I can see the current themes are using Liquid, that's why I did the requested changes. That's why we suggested to create an apps using Full CMS, Decoupled & Headless with both Razor & Liquid

**Comment by sebastienros** [comment]
@jtkech Maybe in "this" case we can remove the tags?

**Comment by jtkech** [comment]
> @jtkech Maybe in "this" case we can remove the tags?

No problem, I have no closed opinion so as you want, was just to be aware of what it allows.

**Review by jtkech — APPROVED** [review]

**Pull request merged**
