### PR TITLE
Fix Liquid QueryCollection access

### LINKED ISSUE #10737: Liquid : Request.Query.value not working
### Describe the bug

{{ Request.Query.something }} should return the QueryString element value and it doesn't as of now from the latest main branch.

### Screenshot

https://user-images.githubusercontent.com/3228637/142957299-c48141ca-078f-4f22-93a4-6e4365e6e435.mp4

### PR DESCRIPTION
**Pull request by jtkech**
Fixes #10737 

The underlying type being a QueryCollectionInternal on which we don't have access

Fixed by creating a QueryCollection

### CODE REVIEW

**Comment by Skrypt** [comment]
Should it not be the same for the Request.Form then?

**Comment by jtkech** [comment]
Only checked for header collection that was not an internal class

Forgot to check all, just need to put a breakpoint and see what types the Request holds

**Comment by Skrypt** [comment]
I'm testing it right now.
It returns nothing.

image

**Comment by jtkech** [comment]
I tested it under the Blog recipe in the Article page, it was working

Yes it still says `QueryCollectionInternal`, did you applied my change?

**Comment by Skrypt** [comment]
I mean I'm testing the Request.Form now and it's returning nothing. I assume that your fix does work for the Request.Query.

**Comment by jtkech** [comment]
Ah okay, yes maybe the same issue with Request.Form

I'm on other things, I will check it asap

**Comment by Skrypt** [comment]
Alright never mind, it works. I forgot while testing to add the antiforgery token when using a form post.

image

**Review by Skrypt — APPROVED** [review]

**Comment by jtkech** [comment]
> Alright never mind, it works. I forgot while testing to add the antiforgery token when using a form post.

Cool cool ;)

**Pull request merged**
