### PR TITLE
Markdig 0.37.0

### PR DESCRIPTION
**Pull request by agriffard**
https://www.nuget.org/packages/Markdig/0.37.0
https://github.com/xoofx/markdig/releases/tag/0.37.0

### CODE REVIEW

**Comment by Piedone** [comment]
How's best to test this?

**Comment by agriffard** [comment]
Adding a Markdown Field to a content type and testing this example : 

```
> [!CAUTION] 
> This is the newly generated CAUTION block 
>  
> And this is the second paragraph
```

According to https://github.com/xoofx/markdig/pull/782 (PR included in https://github.com/xoofx/markdig/releases/tag/0.37.0), it should render this: 

```
<div class="markdown-alert markdown-alert-caution alert alert-danger" role="alert">
<p>This is the newly generated CAUTION block</p>
<p style="margin-bottom: 0">And this is the second paragraph</p>
</div>
```

but it is as if the change was not taken into account and the example output is still:

```
<div class="markdown-alert markdown-alert-caution">
<p class="markdown-alert-title">Caution</p>
<p>This is the newly generated CAUTION block</p>
<p>And this is the second paragraph</p>
</div>
```

**Comment by Piedone** [comment]
That's not what I see happening:

image

**Comment by MikeAlhayek** [comment]
@agriffard is this something ready to merge?

**Comment by Piedone** [comment]
No, see above.

**Comment by hishamco** [comment]
Could you please fix the conflict?

**Comment by hishamco** [comment]
Any updated on this?

**Comment by Piedone** [comment]
BTW Hisham there's not much point in fixing merge conflicts for PRs that otherwise need changes too, like this one, since the author will need to come back here anyway.

**Comment by hishamco** [comment]
I just fixed the conflict to help @agriffard to complete this PR :)

**Comment by sebastienros** [comment]
Superceded

**Pull request closed without merging**
