### PR TITLE
Add footer in admin and display version

### LINKED ISSUE #432: Admin: add version in footer
Display the current version of Orchard on the bottom right in the footer on admin layout.

### PR DESCRIPTION
**Pull request by agriffard**
Fixes #432

### CODE REVIEW

**Comment by sebastienros** [comment]
Fix the conflicts and merge

**Comment by agriffard** [comment]
Ok. Conflicts fixed.
I updated TheAdmin.scss with the latest changes.
I added the styles needed for the footer.

FYI @matiasmolleja, I didn't like the border between the left menu and the collapse button so I commented the border-top on left-nav. 
In fact, I'd prefer to see the collapse button on the right of the title in the top, rather than in the left menu, like this one: https://pratikborsadiya.in/vali-admin/

**Comment by matiasmolleja** [comment]
Yes. In fact that was my first intention. It is what CoreUI and other themes do too.
But after some conversations on gitter we thought that, when the menu was collapsed, the button seemed strange, hanging around in the middle of the top bar. So we used something similar to what the windows 10 mail app does (not exactly the same).

**Comment by agriffard** [comment]
Thank you @matiasmolleja 
The position is now fixed ;-)

**Pull request merged**
