### PR TITLE
Allow content item to be copied

### LINKED ISSUE #2773: Copying of content items?
Is there no facility for creating a new content item by copying an existing content item?  We can add/delete, but there's no copy feature that I can see.  This seems like a pretty fundamental feature that would be expected from any CMS.

### PR DESCRIPTION
**Pull request by hishamco**
Fixes #2773

### CODE REVIEW

**Comment by hishamco** [comment]
Your thoughts @sebastienros

**Comment by sebastienros** [comment]
We already have a Clone operation, and UI integration, in the localization branch. Do you think it's doing the same thing?

**Comment by hishamco** [comment]
This is the first time I heard that, coz I didn't see and link to the original issue

**Comment by sebastienros** [comment]
image

**Comment by sebastienros** [comment]
Please take a look then, and I think you will agree this is already very good

**Comment by hishamco** [comment]
Yep I saw @Skrypt comment, but I didn't know that this feature is implemented in localization branch, so I think I need to close this

**Pull request closed without merging**
