### PR TITLE
Move ContentRazorHelperExtensions to OC.ContentManagement

### PR DESCRIPTION
**Pull request by hishamco**
No need to rely on the `OC.Contents` module to access `IOrchardHelper` extensions

### CODE REVIEW

**Review by Piedone — CHANGES_REQUESTED** [review]
I really don't see the value in introducing such a breaking change (it's breaking because the package changes). If people complain, then we can revisit, but until then, let's not break code out there.

**Comment by hishamco** [comment]
Don't forget that the original APIs reside in the module, not the framework itself and the second problem is no need to rely on `OC.Contents` module to access `IOrchardHelper` extensions because this introduces module to module reference which @sebastienros disallows it from the beginning

**Comment by Piedone** [comment]
I stand by my previous opinion, just as for similar such small housekeeping changes that are still breaking.

**Comment by hishamco** [comment]
I don't think you should blame me for this Zoltan most of my PRs were too old :)

I will close this and probably have a good time before `2.0.0` to do our best to make our APIs consistent

**Comment by Piedone** [comment]
I'm not blaming you for anything, don't take me wrong :). It' just that this PR is not something I thought we should merge in the foreseeable future, so keeping it open is of no use.

**Pull request closed without merging**
