### PR TITLE
Branding favicons and logo

### PR DESCRIPTION
**Pull request by agriffard**
Update favicons and admin logo in themes based on new branding #9635

logo

### CODE REVIEW

**Comment by Piedone** [comment]
The favicons aren't multi-size ones, right?

**Comment by Piedone** [comment]
A couple of remarks:

1. OrchardCore.Admin also has a favicon and a logo in wwwroot and this is what's actually loaded on the admin.
2. The admin also has a logo in the upper-right corner.
3. There are a couple of other files in the solution named "favicon" too that contain the old logo.

**Comment by agriffard** [comment]
> The admin also has a logo in the upper-right corner.

I don't understand what you are referring to.

**Comment by Piedone** [comment]
Sorry, upper-left.

**Comment by agriffard** [comment]
> Sorry, upper-left.

Ok, I just updated it.

**Comment by Piedone** [comment]
Great! The Setup favicon is still needed.

**Comment by agriffard** [comment]
> Great! The Setup favicon is still needed.

Ok, done.

**Pull request merged**
