### PR TITLE
New Users UI

### PR DESCRIPTION
**Pull request by agriffard**
Related to #4747

### CODE REVIEW

**Comment by agriffard** [comment]
media

**Comment by agriffard** [comment]
I don't know how to filter only the approved users or sort them by creation date because it is not in the Index.
Is there a way to 'disable' a user?

**Comment by Skrypt** [comment]
Currently there is no options for these. I remember that in 01 we had a separated table that was used for storing creation / modification dates which was related with the audit trail module.

**Comment by Skrypt** [comment]
By the way I just did this for myself. And I added a IsDisabled bool param on the User and it works fine. I will submit a PR it's quite easy.

**Pull request merged**
