### PR TITLE
Update JOptions configuration (Lombiq Technologies: OCORE-149)

### LINKED ISSUE #15533: Content parts with get-only collections can't retain their values (JOptions configuration)
### Describe the bug

Right now if your content elements contain any get-only collections, those don't get populated by System.Text.Json. they are just left empty. This is an unintended breaking change compared to Newtonsoft.

Why have get-only collection props in the first place? See the explanation in the static code analysis warning [CA2227: Collection properties should be read only](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2227).

### To Reproduce

1. Have a model that contains a get-only collection property, such as [this one](https://github.com/Lombiq/Orchard-Content-Editors/blob/6a34914d01a82401ad77b0a39145601a704ef092/Lombiq.ContentEditors/Models/AsyncEditorPart.cs#L6).
2. Add it to a content type, create and save a content item with some strings in the collection property.
3. Load it back from the DB.
4. Observe that the collection is now empty

### Expected behavior

In Newtonsoft get-only collections (lists, dictionaries, etc) are automatically populated (see mode on the comparison [here](https://github.com/dotnet/runtime/issues/78556#:~:text=Suggestion%20for%20System.Text.Json%20with%20comparison%20with%20Newtonsoft.JSON)).

### Solution

[`JOptions.Base`](https://github.com/OrchardCMS/OrchardCore/blob/a2d529ec5309ad9478222c75182d265ee4c57e69/src/OrchardCore/OrchardCore.Abstractions/Json/JOptions.cs#L13) should contain the configurations:
- `PreferredObjectCreationHandling = JsonObjectCreationHandling.Populate`
- `ReferenceHandler = null`

Note: I'm not entirely sure what the second one means, but it's necessary otherwise the site crashes with the message "System.InvalidOperationException: JsonObjectCreationHandling.Populate is incompatible with reference handling." ([see](https://github.com/dotnet/runtime/blob/0935105e91450a1bad02b5b2f83be52bea2bcf59/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonPropertyInfo.cs#L560)). I suspect it's about handling circular references, but I'm not sure. If anyone has some insight, please chime in.

### Screenshots
image
A minimal sample (not using OC) to show the problem (the "B.Items") and solution (the "B.Items (with options)").

image
A real life example in [Lombiq Content Editors for Orchard Core](https://github.com/Lombiq/Orchard-Content-Editors).

### PR DESCRIPTION
**Pull request by sarahelsaig**
Fixes #15533

### CODE REVIEW

**Comment by MikeAlhayek** [comment]
This fix is good and will provide one less breaking change. I am not sure if there is a negative impact from this change. @sebastienros any thoughts if there is a downside from taking this change?

**Comment by MikeAlhayek** [comment]
@sarahelsaig on a second note, I think this change should not be part of Base (maybe we do, but probably not). It should only be part of the ContentSerializerOptions

https://github.com/OrchardCMS/OrchardCore/blob/main/src/OrchardCore/OrchardCore.Abstractions/Extensions/ContentSerializerJsonOptionsConfiguration.cs

**Comment by sarahelsaig** [comment]
> @sarahelsaig on a second note, I think this change should not be part of Base (maybe we do, but probably not). It should only be part of the ContentSerializerOptions
> 
> https://github.com/OrchardCMS/OrchardCore/blob/main/src/OrchardCore/OrchardCore.Abstractions/Extensions/ContentSerializerJsonOptionsConfiguration.cs
> 
> Not that ContentSerializerOptions is the only options that impact serializing and deserializing object in YesSql.

Won't it be bad if Base has a different ReferenceHandler than ContentSerializerOptions?

**Comment by MikeAlhayek** [comment]
> Won't it be bad if Base has a different ReferenceHandler than ContentSerializerOptions?

I don't think so. YesSQL can has different options. for example, in the YesSQL we add converters for different types.

**Comment by sarahelsaig** [comment]
@MikeAlhayek I've made the change you suggested and unfortunately it won't work. I don't think the problem is only related to YesSQL.

I guess your approach works as long as the original structure (i.e. the `ContentElement.Elements`) is maintained, but it breaks if you use methods which clear that element list such as `ContentElement.Apply()`, `ContentElement.Apply<TPart>()` or `ContentItem.Merge()`. At that point trying to access a child item (e.g. using the `ContentItem.As<TPart>()`) causes a de-serialization [which now only uses the `JOptions.Default`](https://github.com/OrchardCMS/OrchardCore/blob/65a131bd9518383352df0ff1704c0db7b30c6600/src/OrchardCore/OrchardCore.ContentManagement.Abstractions/ContentExtensions.cs#L77). This is too fragile, I'm not sure if anything besides read-only access is safe.

So I think this config won't be usable unless we put it into `JOptions.Base` after all.

**Review by sebastienros — APPROVED** [review]

**Pull request merged**
