### PR TITLE
Add security hash to url in [image] shortcode to allow custom sizes

### LINKED ISSUE #10406: Add security hash to url in [image] shortcode to allow custom sizes
If you specify a custom width or height for an image when using the [image] shortcode it will not work. This is because a security hash token needs to be added to the generated URL.

Helpers exist in OrchardCode.Media/Razor/OrchardRazorHelperExtensions.cs that should make this easy to add.

### PR DESCRIPTION
**Pull request by nogginbox**
Use media razor helper so that security token is added to generated URL. This fixes #10406

### CODE REVIEW

**Comment by hishamco** [comment]
Please fix the build, seems you are using C# 9.0 features

**Comment by NogginBox** [comment]
@hishamco I forgot to run the tests locally and one needs fixing. No C#9 here.

**Comment by NogginBox** [comment]
I'm having trouble setting up the test as the shortcode now uses ```OrchardRazorHelperExtensions``` which needs ```IOrchardHelper``` to get media options:
```
orchardHelper.HttpContext.RequestServices.GetService<IOptions<MediaOptions>>()
```
I'm setting the orchard helper up in the test like so:
```
var defaultHttpContext = new DefaultHttpContext();
defaultHttpContext.Request.PathBase = new PathString("/tenant");
var httpContextAccessor = Mock.Of<IHttpContextAccessor>(hca => hca.HttpContext == defaultHttpContext);
var orchardHelper = new DefaultOrchardHelper(httpContextAccessor);
```
But I can't figure out how to register IOptions<MediaOptions> to be returned by GetService. **Can anyone help or point me towards a test that does this?**

**Comment by deanmarcussen** [comment]
> But I can't figure out how to register IOptions to be returned by GetService. **Can anyone help or point me towards a test that does this?**

You can create your own serviceprovider, and load everything you need to resolve in it. Then resolve the shortcode provider from the test service provider.
For an example in the tests see here
https://github.com/OrchardCMS/OrchardCore/blob/162a62a10aa3f7829852148ff760e2b0ee052ea6/test/OrchardCore.Tests/Modules/OrchardCore.Rules/RuleTests.cs#L197

**Comment by NogginBox** [comment]
@hishamco there was a c# 9 'feature' in there. More of compiler improvement: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/target-typed-conditional-expression

Used it without realizing. Now removed.

**Comment by NogginBox** [comment]
@deanmarcussen this adds the hash now. How does it look?

**Comment by Piedone** [comment]
Is this something you'd like to revisit @nogginbox any time soon or should we close?

**Comment by nogginbox** [comment]
> Is this something you'd like to revisit @nogginbox any time soon or should we close?

@Piedone I'd completely forgotten about this PR, and I can hardly remember what it was about or why I needed it. I think I was busy at the time and didn't have time to resolve the comments in a good way particularly the one from @sebastienros about the orchard helper.

I suspect Orchard has moved under me a bit. Is the enhancement provided by this PR still something that is not possible?

**Comment by Piedone** [comment]
Thank you for your quick reply! The current behavior is that you can use one of the preset sizes in `[image]` (see https://docs.orchardcore.net/en/latest/docs/reference/modules/Shortcodes/#image). This [is configurable](https://docs.orchardcore.net/en/latest/docs/reference/modules/Media/#configuration). Furthermore, you can also use arbitrary sizes but for that, you still need a token.

If I understand correctly, the goal of this PR is to let users of the shortcode use custom sizes by making the shortcode generate this token. This can still be a valid use case, though I'd like to know more about where exactly this comes up (since shortcodes are about providing some simple and safe way for users to add dynamism to their texts, not about much customization; you have HTML and Liquid for that). If it is, then the implementation should be optional, with the current behavior being the default, so you only let users generate arbitrary sizes if you really want o allow them.

**Comment by Piedone** [comment]
Closing due to inactivity.

**Pull request closed without merging**
