### PR TITLE
Enable Graphql queries to support total when using Lucene queries

### PR DESCRIPTION
**Pull request by hyzx86**
Change the query schema to the following: add 'hasTotal' :true

```
{
  "type":"contentItem/TableProducts",
 "hasTotal":true
}
```

image

https://github.com/OrchardCMS/OrchardCore/issues/6939

### CODE REVIEW

**Comment by hyzx86** [comment]
Regarding the `"hasTotal":true`  option, I want it to be the default
I notice this PR is in the works, maybe it can be released with this feature?
https://github.com/OrchardCMS/OrchardCore/pull/11052

**Comment by aminmohammadi05** [comment]
What if when there are multiple content types? 
```
[{
  "type":"contentItem/TableProducts",
 "hasTotal":true
},
{
  "type":"contentItem/Type2",
 "hasTotal":true
}]
```

**Comment by hyzx86** [comment]
@aminmohammadi05  have you try  graphql ?

**Review by hishamco — CHANGES_REQUESTED** [review]
This is a quick review, please check the format in all the places

**Comment by aminmohammadi05** [comment]
> @aminmohammadi05 have you try graphql ?
Yes but it does not shown in the graphql

**Comment by hyzx86** [comment]
> > @aminmohammadi05 have you try graphql ?
> > Yes but it does not shown in the graphql

cuz , you haven't  input the schema field

**Comment by aminmohammadi05** [comment]
> > > @aminmohammadi05 have you try graphql ?
> > > Yes but it does not shown in the graphql
> 
> cuz , you haven't input the schema field

How to do that?

**Comment by hyzx86** [comment]
> > > > @aminmohammadi05 have you try graphql ?
> > > > Yes but it does not shown in the graphql
> > 
> > 
> > cuz , you haven't input the schema field
> 
> How to do that?

image

**Comment by aminmohammadi05** [comment]
> > > > > @aminmohammadi05 have you try graphql ?
> > > > > Yes but it does not shown in the graphql
> > > 
> > > 
> > > cuz , you haven't input the schema field
> > 
> > 
> > How to do that?
> 
> image
I mean when I put type Product in type field it shows just Product type field in Graphiql but I need it to show Blog type field also
image
image

**Comment by hyzx86** [comment]
image

**Comment by aminmohammadi05** [comment]
> image

This is a Lucene search query which I need to provide parameters for it to search the parameters in all the selected types: Product, Blog

**Comment by hyzx86** [comment]
image

**Comment by aminmohammadi05** [comment]
> image

I know, I want to set the schema field of the Lucene query in a way that the "searchAll" query shows fields of the both Product and Blog types

**Comment by hyzx86** [comment]
https://github.com/OrchardCMS/OrchardCore/pull/11052

I noticed that this function was merged into the main branch yesterday

**Comment by hyzx86** [comment]
> I know, I want to set the schema field of the Lucene query in a way that the "searchAll" query shows fields of the both Product and Blog types

Lucene query should not do what you said. It stores some types in a table containing many fields
If you want to query two types at the same time, you may need to perform secondary filtering on the client

**Comment by aminmohammadi05** [comment]
> > I know, I want to set the schema field of the Lucene query in a way that the "searchAll" query shows fields of the both Product and Blog types
> 
> Lucene query should not do what you said. It stores some types in a table containing many fields If you want to query two types at the same time, you may need to perform secondary filtering on the client

No problem how can I query two types at the same time. As you said I can handle separating the result based on its type.

**Comment by hyzx86** [comment]
> No problem, how can I query two types at the same time. As you said I can handle separating the result based on its type.


have you try  object type?

https://docs.orchardcore.net/en/latest/docs/reference/modules/Queries/#graphql

image

**Comment by aminmohammadi05** [comment]
> > No problem, how can I query two types at the same time. As you said I can handle separating the result based on its type.
> 
> have you try object type?
> 
> https://docs.orchardcore.net/en/latest/docs/reference/modules/Queries/#graphql
> 
> image

Yeah I saw that, I wonder how to query two types at the same time. As you see the document only shows one type: "BlogPost"

**Comment by hyzx86** [comment]
Not ready , I'm trying to implement more flexible schema configuration, such as

``` json
{
 {"type":"Array","ofType":"Blog","name":"items"},
 {"type":"Integer","name":"total"},
}
```

**Comment by aminmohammadi05** [comment]
> Change the query schema to the following: add 'hasTotal' :true
> 
> ```
> {
>   "type":"contentItem/TableProducts",
>  "hasTotal":true
> }
> ```
> 
> image
> 
> #6939

I tried this one to return total records but it did not work. What else should I do to get the result?

**Comment by hyzx86** [comment]
@aminmohammadi05 
> I tried this one to return total records but it did not work. What else should I do to get the result?

I have updated the code. Would you like to try again?

image

Schema:

```
{
    "type":"contentitem/AmisSchema",
    "hasTotal":true
}
```
Query
``` Liquid
{
    "query": {
        "bool": {
            "must": [
                { "term": { "Content.ContentItem.ContentType": "AmisSchema" } },
                { "term": { "Content.ContentItem.Published": 'true' } },
                { "term": { "Content.ContentItem.Latest": "true" } }
            ],
            {% if filters %}
            "filter":[
                  {% for filter in filters %} 
              		{%if filter.key %}
      					{"{{filter.method}}": { "{{filter.key}}": "{{filter.value}}" }},
                    {%else%}
                    	{"{{filter.method}}":"{{filter.value}}"}},
                    {%endif%}
				  {% endfor %} 
            	]
            {% endif %}
        }
    }
  {% if from %}
    ,"from":{{from}}
  {% endif %}
  {%if size %}
   ,"size":{{size}}
  {%endif%}  	
}
```

graphql
``` graphql
query MyQuery {
  defaultPagingQuery(parameters: "{'from':0,'size':2}") {
    items {
      displayText
      modifiedUtc
      publishedUtc
      createdUtc
      render
    }
    total
  }
}

```

**Comment by jtkech** [comment]
@hyzx86 There is the following warning to fix in the GitHub Actions / Build & Test ;)

'LuceneQueryResults' is obsolete: 'This class has been deprecated and will be removed in the next major release, please use OrchardCore.Search.Lucene.Abstractions instead.'

**Comment by hyzx86** [comment]
@hyzx86  Yes , I noticed that ,And I haven‘t received such a message  since I update the code

**Comment by aminmohammadi05** [comment]
What if I don't want to update my orchard package? I mean what approach did you use before this modification to return total number of records?

**Comment by hyzx86** [comment]
> What if I don't want to update my orchard package? I mean what approach did you use before this modification to return total number of records?

same as above ， Have you pull my PR before yesterday？

**Comment by aminmohammadi05** [comment]
> > What if I don't want to update my orchard package? I mean what approach did you use before this modification to return total number of records?
> 
> same as above ， Have you pull my PR before yesterday？

I am using version 1.4 of OrchardCore.Application.Cms.Core.Targets in .NET 6 project but this approach didn't work

**Comment by hyzx86** [comment]
> > > What if I don't want to update my orchard package? I mean what approach did you use before this modification to return total number of records?
> > 
> > 
> > same as above ， Have you pull my PR before yesterday？
> 
> I am using version 1.4 of OrchardCore.Application.Cms.Core.Targets in .NET 6 project but this approach didn't work

Please provide more information, such as error logs, Schema and Query

**Comment by aminmohammadi05** [comment]
image
 this is the schema

**Comment by aminmohammadi05** [comment]
image
 And the GraphQl output

**Comment by hyzx86** [comment]
Looks like the code is not work ,Do you use my branch directly?

**Comment by aminmohammadi05** [comment]
No I downloaded it via Nuget package manager in Visual Studio 2022 3 months ago

**Comment by hyzx86** [comment]
> No I downloaded it via Nuget package manager in Visual Studio 2022 3 months ago

This feature only work on my branch...

**Comment by aminmohammadi05** [comment]
So how can I get total records without using you branch? cuz I am in the middle of development and feel it risky to change the Orchard

**Comment by hyzx86** [comment]
> So how can I get total records without using you branch? cuz I am in the middle of development and feel it risky to change the Orchard


You can directly use the WebAPI : `api/queries/{name}`

https://docs.orchardcore.net/en/latest/docs/reference/modules/Queries/#breaking-changes

**Comment by aminmohammadi05** [comment]
Thanks a lot.

**Comment by aminmohammadi05** [comment]
Would you please tell me except bearer token which I provide in postman where should I put the query parameter which in my case is 
```
{
    "from" : 0,
    "size" : 6,
    "fulltext" : "'sf6'"
}
```

**Comment by hyzx86** [comment]
@hishamco 

I thought, is it possible to change the UI of LuceneQuery to add a checkbox, which can togdle the total field 

What do you think?

**Comment by Piedone** [comment]
I think this would be useful, but only if you implement parity with the Elasticsearch queries too. @Skrypt could you please chime in here?

**Comment by sebastienros** [comment]
Why not always have a `count` property and if the provider supports it return the value or `-1` if it's not available. `0` would mean no items when the query supports it.

**Comment by hyzx86** [comment]
Of course that would be best, but that would introduce a disruptive change. 
Because the current query api returns a collection type

**Comment by hyzx86** [comment]
In addition, we have discussed quantity statistics implemented on SQL at this level
https://github.com/OrchardCMS/OrchardCore/issues/6939

**Pull request closed without merging**
