### PR TITLE
Update Localization documentation for the extractor tool

### PR DESCRIPTION
**Pull request by rjpowers10**
@hishamco released version 1.0.0-preview of the extractor tool.

Once 1.0.0 is released this PR can be merged to update the docs.

### CODE REVIEW

**Comment by hishamco** [comment]
Thanks for a quick react to PO Extractor changes ;) I'm glad that we resolve all the logged issues, one more thing I didn't hear your feedback about the preview release

I need to do some tests next weeks if everything is fine I will bump the version

**Comment by rjpowers10** [comment]
> Thanks for a quick react to PO Extractor changes ;) I'm glad that we resolve all the logged issues, one more thing I didn't hear your feedback about the preview release
> 
> I need to do some tests next weeks if everything is fine I will bump the version

I gave it a quick test today and it seems to be working correctly, but I haven't looked too deeply at the results yet.

**Comment by hishamco** [comment]
@rjpowers10 thanks for your feedback, hope to release the `1.0.0` in this week, hope everything goes fine coz I'm still suffering from issue happens with my laptop

I will let you know once I publish a NuGet package

**Comment by hishamco** [comment]
FYI

https://github.com/OrchardCoreContrib/OrchardCoreContrib.PoExtractor/releases/tag/v1.0.0
https://www.nuget.org/packages/OrchardCoreContrib.PoExtractor/1.0.0

**Comment by hishamco** [comment]
@agriffard I think it's fine to merge this now

**Comment by hishamco** [comment]
Thanks again @rjpowers10

**Pull request merged**
