### PR TITLE
Update Microsoft.IdentityModel.Protocols.OpenIdConnect 8.1.1

### PR DESCRIPTION
**Pull request by hishamco**

### CODE REVIEW

**Comment by MikeAlhayek** [comment]
Did you miss this?

https://github.com/OrchardCMS/OrchardCore/pull/16850/files#diff-5baf5f9e448ad54ab25a091adee0da05d4d228481c9200518fcb1b53a65d4156R44-R50

**Comment by hishamco** [comment]
I will leave this to @kevinchalet to close this or update it when it's possible

**Comment by Piedone** [comment]
Please either do this fully or close it.

**Comment by hishamco** [comment]
No need for this why the rest are closed, let the bot handle them

**Pull request closed without merging**
