### PR TITLE
Convert anchors to strings using InvariantCulture

### PR DESCRIPTION
**Pull request by netwavebe**
When converting anchors to strings the InvariantCulture should be used.

On my machine (Belgium) I was getting
`?width=100&height=150&rmode=crop&rxy=0,37297297,0,10037175`
but it should be
`?width=100&height=150&rmode=crop&rxy=0.37297297,0.10037175`.

### CODE REVIEW

**Comment by deanmarcussen** [comment]
Yes makes sense.

Probably needs to be done here to https://github.com/OrchardCMS/OrchardCore/blob/313c21c9ab7b4008d9d8ec626eb9a4f80ec2b211/src/OrchardCore.Modules/OrchardCore.Media/Filters/MediaFilters.cs#L154

**Comment by netwavebe** [comment]
You're right, I added a commit for this.

**Comment by deanmarcussen** [comment]
Thanks, I need to check to understand if this is / was a serialization issue, which may cause problems when editing the anchor in a different culture to what it was originally created in.

If you have the json for the content item in it, can you post it? Thanks

**Comment by netwavebe** [comment]
Sure. The media field is called "Images" and this is the relevant JSON:

```
"Images": {
	"Paths": [
		"Products/B&C/Polo/CGPW440 - CGPM430/CGPM430_2020.jpg",
		"Products/B&C/Polo/CGPW440 - CGPM430/CGPM430-2_2020.jpg",
		"Products/B&C/Polo/CGPW440 - CGPM430/CGPM430-3_2020.jpg",
		"Products/B&C/Polo/CGPW440 - CGPM430/CGPM430_BOTTLEGREEN.jpg"
	],
	"MediaTexts": [
		"",
		"",
		"",
		""
	],
	"Anchors": [
		{
			"X": 0.4318182,
			"Y": 0.30708662
		},
		{
			"X": 0.5,
			"Y": 0.5
		},
		{
			"X": 0.5,
			"Y": 0.5
		},
		{
			"X": 0.5,
			"Y": 0.5
		}
	]
},
```

**Review by deanmarcussen — APPROVED** [review]
Great thanks, so it was only about the conversion on the output.

**Pull request merged**
