### PR TITLE
Expose ContentField/ContentPart as input fields

### LINKED ISSUE #12781: Expose Content Fields Indexing via GraphQL for content field filtering
### Is your feature request related to a problem? Please describe.
If you want to filter (with `where`) on the value of content fields, you have to implement a `WhereInputObjectGraphType` for it. There's no built-in way to filter on content field values from GraphQL.

This came up in [this discussion](https://github.com/OrchardCMS/OrchardCore/discussions/12630) too.

### Describe the solution you'd like
We already have [Content Fields Indexing](https://docs.orchardcore.net/en/latest/docs/reference/modules/SQLIndexing/#content-fields-indexing) to be able to run SQL queries for field values. Let's build on that, and expose such SQL indices in GraphQL too.

### Describe alternatives you've considered
An alternative would be to manually create indices for each field, and a `WhereInputObjectGraphType` for each of them.

Also, we could expose SQL Queries too: https://github.com/OrchardCMS/OrchardCore/issues/16008.

### PR DESCRIPTION
**Pull request by MikeAlhayek**
Fix #12781

### CODE REVIEW

**Comment by MikeKry** [comment]
@MikeAlhayek 
That is interesing PR :) 
I looked shortly into that. I do not know the solution, but I may know the problem.

Schema gets broken when fields here https://github.com/OrchardCMS/OrchardCore/pull/12946/files#diff-6134a028c0f30220fca9bd7cbaf61ae4257e53ac8e811f8e49081567f0ed3efeR64 
come from "BagPart" -> that means, at least in my case (as I have some testing content types only), when dynamic fields are nested in another part, it may be the problem.  

For example, after activating SQL indexing:

``{
                            "name": "xtest",
                            "description": "Text field",
                            "type": {
                                "kind": "SCALAR",
                                "name": "String",
                                "ofType": null
                            },
                            "defaultValue": null
 }``

This field is part of ContentType and is added as SCALAR field - no problem here, everything seems ok. 

But then there is field "test" that is contained in my bagpart definition. You can see it does not even include the field test:

``{
                            "name": "bag",
                            "description": "Represents a BagPart.",
                            "type": {
                                "kind": "INPUT_OBJECT",
                                "name": "BagPart",
                                "ofType": null
                            },
                            "defaultValue": null
 }``

This throws error that can be seen in JS console. 


I do not know what exactly you would like to achieve, but I can think of two possible solutions:
A/ include only scalar fields from given content type - that would eliminate those problems, but users would still need to create custom filter object for content parts (but not for fields).

B/ add fields from nested parts as scalar fields, something like here

``{
                    "kind": "OBJECT",
                    "name": "BagPart",
                    "description": "A BagPart allows to add content items directly within another content item",
                    "fields": [
                        {
                            "name": "contentItems",
                            "description": "the content items",
                            "args": [
                                {
                                    "name": "first",
                                    "description": "the first n elements",
                                    "type": {
                                        "kind": "SCALAR",
                                        "name": "Int",
                                        "ofType": null
                                    },
                                    "defaultValue": "0"
                                },....
                            ],
                            "type": {
                                "kind": "LIST",
                                "name": null,
                                "ofType": {
                                    "kind": "INTERFACE",
                                    "name": "ContentItem",
                                    "ofType": null
                                }
                            },
                            "isDeprecated": false,
                            "deprecationReason": null
                        }
                    ],
                   ...
 },``

If you have another problems, maybe share content type definitions that you are testing it with.

ps. is there a way to get notified in github notification center when I am mentioned?

**Comment by MikeAlhayek** [comment]
@MikeKry your notification preference in Github can be set by going https://github.com/settings/notifications maybe this is the settings you want to change.

image

**Comment by MikeAlhayek** [comment]
@MikeKry I am not sure my error is related to the BagPart. Here is a summary of what I am trying to do in `DynamicContentFieldBuilder`
Loop over content type definitions, For each part in the definition, loop over the fields if any exists. If the field is a scaler, we want to expose it under the `where` input variable to allow the user to filter by it.


Here is the recipe that you can use to use the same content definition that I am using.

```
{
  "name": "",
  "displayName": "",
  "description": "",
  "author": "",
  "website": "",
  "version": "",
  "issetuprecipe": false,
  "categories": [],
  "tags": [],
  "steps": [
    {
      "name": "ContentDefinition",
      "ContentTypes": [
        {
          "Name": "Product",
          "DisplayName": "Product",
          "Settings": {
            "ContentTypeSettings": {
              "Creatable": true,
              "Listable": true,
              "Draftable": true,
              "Versionable": true,
              "Securable": true
            },
            "FullTextAspectSettings": {}
          },
          "ContentTypePartDefinitionRecords": [
            {
              "PartName": "Product",
              "Name": "Product",
              "Settings": {
                "ContentTypePartSettings": {
                  "Position": "1"
                }
              }
            },
            {
              "PartName": "TitlePart",
              "Name": "TitlePart",
              "Settings": {
                "ContentTypePartSettings": {
                  "Position": "0"
                }
              }
            },
            {
              "PartName": "ProductInfoPart",
              "Name": "ProductInfoPart",
              "Settings": {
                "ContentTypePartSettings": {
                  "Position": "2"
                }
              }
            },
            {
              "PartName": "QuantityPart",
              "Name": "QuantityPart",
              "Settings": {
                "ContentTypePartSettings": {
                  "Position": "3"
                }
              }
            }
          ]
        }
      ],
      "ContentParts": [
        {
          "Name": "ProductInfoPart",
          "Settings": {
            "ContentPartSettings": {
              "Attachable": true
            }
          },
          "ContentPartFieldDefinitionRecords": [
            {
              "FieldName": "DateField",
              "Name": "AvailableDate",
              "Settings": {
                "ContentPartFieldSettings": {
                  "DisplayName": "AvailableDate"
                }
              }
            },
            {
              "FieldName": "NumericField",
              "Name": "Price",
              "Settings": {
                "ContentPartFieldSettings": {
                  "DisplayName": "Price"
                },
                "NumericFieldSettings": {
                  "Required": true,
                  "Scale": 2
                }
              }
            }
          ]
        },
        {
          "Name": "QuantityPart",
          "Settings": {
            "ContentPartSettings": {
              "Attachable": true
            }
          },
          "ContentPartFieldDefinitionRecords": [
            {
              "FieldName": "NumericField",
              "Name": "Quantity",
              "Settings": {
                "ContentPartFieldSettings": {
                  "DisplayName": "Quantity"
                }
              }
            },
            {
              "FieldName": "NumericField",
              "Name": "QuantityThreshold",
              "Settings": {
                "ContentPartFieldSettings": {
                  "DisplayName": "Quantity Threshold"
                }
              }
            }
          ]
        }
      ]
    }
  ]
}
```

When I render GraphiQL, I see the following error in the console.

> Uncaught (in promise) Error: Introspection must provide output type for fields, but received: ProductInfoPart.

**Comment by MikeAlhayek** [comment]
@MikeKry I figure out the issue and fixed it. Now the fields are being adding to the where input as expected. Next, I have to find a way to apply that logic to the query.

**Comment by hyzx86** [comment]
@MikeKry 
I have a similar implementation

But it is not the latest. I will update the code when I have time
https://github.com/EasyOC/EasyOC/blob/main/src/Modules/EasyOC.Scripting/Graphql/ScriptQueryFiledTypeProvider.cs

image


Our schema definitions are very similar, I also used `type` and `ofType`, 
and later I simplified the schema description

``` json
{
    "items": {
        "name": "string",
        "sex": "boolean",
        "age": "int",
        "weight": "float",
        "weight1": {
            "type": "float","description":"test description of weight1"
        },
        "customer": "Department"
    },
    "data": {
        "type": {
            "name": "string",
            "sex": "boolean",
            "age": "int",
            "weight": "float",
            "customer": "Department"
        }
    },
    "message": "string"
}
```


image


This is a deployed query
image

**Comment by hyzx86** [comment]
Can we change it like this?
 
image

The current 'field+logical name' method is too redundant...


image

**Comment by Piedone** [comment]
Is this something you'd like to revisit any time soon @MikeAlhayek or should we close?

**Pull request closed without merging**
