### PR TITLE
Avoid NRE in PartDefinition in ContentPartHandlerCoordinator

### PR DESCRIPTION
**Pull request by hishamco**

### CODE REVIEW

**Review by MikeAlhayek — APPROVED** [review]
@hishamco what trigger such a PR? Is there an analyzer that is suggesting that you do this? Such a PR does not add a a much value. I am just wondering what is triggering them as I notices multiple similar PR that you merged lately,

**Comment by hishamco** [comment]
I'm using a static analyzer, also I can reproduce such issues from within unit tests, we need to make sure nothing should break the code in case we leave the objects null

This should improve the quality

**Comment by MikeAlhayek** [comment]
@hishamco if there is an analyzer that should be added to your he project I suggest you add it and apply its suggestion using one PR.

Also, in this PR there was no added value because we already are doing null check. You reduced the null check by 1 on every line. But the end result will always be identical. So it's not like we would have gotten a null exception before and now we won't get this check. 

If you have a unit test that would throw exception, please keep such a unit test in OC.

**Comment by hishamco** [comment]
Ok, I will struggle to add more unit tests of the time

**Pull request merged**
