### PR TITLE
Add Authors in docs

### PR DESCRIPTION
**Pull request by agriffard**
Display authors at the bottom of docs pages.
Example with Readme:

image

Use https://pypi.org/project/mkdocs-git-authors-plugin/ with custom template.

### CODE REVIEW

**Comment by hishamco** [comment]
Lovely

**Comment by MichaelPetrinolis** [comment]
@agriffard unfortunately with the new structure in the documentation some info was lost :)

**Comment by agriffard** [comment]
> unfortunately with the new structure in the documentation some info was lost :)
What kind of information has been lost?

**Comment by MichaelPetrinolis** [comment]
The initial commits of readme files are lost, so after the move the authors list is inaccurate

**Pull request merged**
