### PR TITLE
Remove extra closed div in TheAdmin theme

### PR DESCRIPTION
**Pull request by hishamco**

### CODE REVIEW

**Comment by Skrypt** [comment]
Can you fix the indentation too?

**Comment by hishamco** [comment]
It's already fixed if I'm not wrong, let me double check ...

**Comment by hishamco** [comment]
It's OK Jasmin unless you see something I didn't see ;)

**Comment by hishamco** [comment]
Seems I was on another branch ;)

Thanks

**Review by Skrypt — APPROVED** [review]

**Pull request merged**
