### PR TITLE
Tenant names checking tweaks

### PR DESCRIPTION
**Pull request by jtkech**
@Piedone @hishamco 

I re-opened a PR on this branch just to show what I just did because I wanted to update it before forgetting the details around this, and also because I didn't see any update on the related PR #11435.

So here what I did

- Re-introduce `IsDefaultShell()` but make it case sensitive and then use it where it can be.

And what this branch was already doing as a reminder.

- Take into account that the shellHost dicos now are case insensitive.

- Fix a little validation issue in TenantValidator (which now also uses `IsDefaultShell()`).

All of the above being related to tenant names checking.

### CODE REVIEW

**Comment by hishamco** [comment]
Hi @jtkech I will update some of my PRs in the upcoming days, I was too busy because I am moving to a new house. I struggle to check the issues and comments as much as I can.

Hope to check your changes in the upcoming hours

**Comment by jtkech** [comment]
@hishamco nothing urgent, just wanted to finalize this branch before forgetting the details.

**Comment by jtkech** [comment]
@Piedone @hishamco 

I will merge this one, it has been indirectly reviewed through related PRs, it includes some new things as the new case insensitive shellHost dicos, and there are other pending PRs mixing with the same files since a too long time. So we will have the same base on which we will be able to add new things, even if it creates some little PR conflicts ;)

**Comment by hishamco** [comment]
No problem, I need to close mine then

**Pull request merged**
