### PR TITLE
Add Azure Blob Storage based TenantFileProvider

### PR DESCRIPTION
**Pull request by TFleury**
For discussion.

It may have performance impact, however it's an opt-in feature and it acts lately in the pipeline.

### CODE REVIEW

**Comment by sebastienros** [comment]
Scenario?
No way to be able to plug with the local azure media cache?

**Comment by TFleury** [comment]
> Scenario ?

#1221 and some assets (theme, css, js)
Maybe we can extend its usage to have Views and tenant config (Lucene, appSettings.json, ContentDefinition.json, …) in this storage.

> No way to be able to plug with the local azure media cache ?

Of course, if we make a more generic file cache which covers media files, ImageSharp and tenant files, with #4950 in mind.

**Comment by deanmarcussen** [comment]
The problem here is performance.

Wrapping azure blob into a non async `IFileProvider` interface is draining. All the calls, like `Exists`, `ListBlobs`, `OpenRead` are underlying in the azure blob implementation just calls to `ExistsAsync.GetAwaiter().GetResult()` etc. So not performant, and would be called a lot.

Reusing what we do for media as mentioned here might be better https://github.com/OrchardCMS/OrchardCore/issues/3012 because we would then have a ui to allow uploads to the storage.

A more generic file cache is also an option, but then there is no UI to drive it.

I guess it depends on whether a UI is important.

Also worth noting that you can point `App_Data` at blob storage or other shared folders already

**Comment by TFleury** [comment]
@deanmarcussen Thank you for you feedbacks

> Wrapping azure blob into a non async IFileProvider interface is draining. All the calls, like Exists, ListBlobs, OpenRead are underlying in the azure blob implementation just calls to ExistsAsync.GetAwaiter().GetResult() etc. So not performant, and would be called a lot.

Do you think we would have better performance with async IFileProvider and StaticFileMiddleware implementations ?

File cache would be the best option to improve performance, but we still have async calls.

> I guess it depends on whether a UI is important.

I think it's not important, and if there would be one, it should be distinct from Media, with some text editing features.

> Also worth noting that you can point App_Data at blob storage or other shared folders already

Interesting, can you tell me how ? Can I point each tenant folder to a distinct blob storage ?

**Comment by deanmarcussen** [comment]
> Do you think we would have better performance with async IFileProvider and StaticFileMiddleware implementations ?

Possibly, but I initially wrote some for the media blob implementation using `IFileStore` with async, but Seb had the much better idea of caching the files, and ultimately it meant the implementation became a lot simpler, with a lot less code to maintain.

> File cache would be the best option to improve performance, but we still have async calls.
Yes, cache is the fastest, and when using cache we can use async middleware.

> Interesting, can you tell me how ? Can I point each tenant folder to a distinct blob storage ?

You need to do something like this in azure, but the `ORCHARDCORE_APP_DATA` environment variable allows you to point at any mounted share. I don't have any experience implementing this though ;) I think @carlwoodhouse does with docker.

This might be interesting to take a look at too.
https://docs.microsoft.com/en-us/azure/app-service/overview-local-cache
> I think it's not important, and if there would be one, it should be distinct from Media, with some text editing features.

Cool, I don't have a clear sense of your use case, so the other question that comes to mind, is what files you are wanting to host?

If it's mostly just theme js/css files you could look at the cdn options for js and css in the resource manager. You could just use those to point direct at your tenant blob storage, or cdn front for blob storage, and OC wouldn't need to know more than that.

Content definition should go into database (as it can already). Tenants.json will probably go there as well, but that is with @jtkech as part of distributed. Views are also database hosted, so not sure the benefit of having them on a file system?
Lucene, well, Lucene's tricky. For performance it really has to be hosted locally (in my opinion), otherwise there would be the issue of locks, and risk of index corruption, so I would imagine that we go the elastic search route, or possibly/maybe cache refreshers as part of distributed.

**Comment by carlwoodhouse** [comment]
`ORCHARDCORE_APP_DATA` basically allows you to set any filesystem path for your AppData folder, if using docker you can then mount an external drive at the path you specify.

Be warned with azure though that the driver they use with docker to allow mounting a storage account account is not amazing, we suffered from dropped mounts and files wondering off A LOT when using it (mostly on container restart) ... (not specific to orchardcore)

**Comment by TFleury** [comment]
Thank you one more time for you answers.

What I've in mind is to be able to have simpler theme deployment.
I don't want to have to rebuild and redeploy my instance each time I have to change a line of css or js in a theme.
Templates feature is very flexible, but it implies to manualy update all changed templates.

My idea is to have something like a theme in a zip archive (liquid templates, css, js, fonts and probably some graphics) with a one click deployment.

**Comment by deanmarcussen** [comment]
> My idea is to have something like a theme in a zip archive (liquid templates, css, js, fonts and probably some graphics) with a one click deployment.

I think that could probably be handled by a combination of deployment steps (perhaps a custom deployment step that would deploy theme assets to a blob store of your choice) and using the cdn options for resources to point to the public blob store address.

Templates already have a deployment step

and this helper should prefix any kind of resource, js, css, image
https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore/OrchardCore.ResourceManagement/Razor/ResourceCdnHelperExtensions.cs

The only thing that wouldn't work with that is cache busting, but that is something that could be managed with file name versioning.

Maybe that would solve your issue?

**Comment by TFleury** [comment]
> You need to do something like this in azure, but the ORCHARDCORE_APP_DATA environment variable allows you to point at any mounted share.
> > Be warned with azure though that the driver they use with docker to allow mounting a storage account account is not amazing, we suffered from dropped mounts and files wondering off A LOT when using it (mostly on container restart)

So, probably not a reliable option.

> This might be interesting to take a look at too.
https://docs.microsoft.com/en-us/azure/app-service/overview-local-cache

Interesting feature, and it seems to make real performance improvements. Can we open an issue to track changes required to leverage it ?
- Need to point ORCHARDCORE_APP_DATA to 'D:\home\Data'
- Maybe others...

> Templates already have a deployment step

Yes, it seems to be the best option for templates. And it could also deploy content definitions and content items.

> and this helper should prefix any kind of resource, js, css, image

It's an option, but I would prefer to have everything served by OC.

Can we re-evaluate this after #4950 ?

**Comment by TFleury** [comment]
@agriffard I think this PR could be closed.
There is a perf issue accessing blob storage to serve static files.

**Pull request closed without merging**
