### PR TITLE
Remove duplicate LangVersion entry

### PR DESCRIPTION
**Pull request by hishamco**

### CODE REVIEW

**Comment by sebastienros** [comment]
Where is the other one?

**Comment by hishamco** [comment]
Here is a better look

https://github.com/OrchardCMS/OrchardCore/blob/e93de03087aa9e2919fcc52d3aa38a48e2120647/src/OrchardCore.Build/OrchardCore.Commons.props#L6-L17

**Comment by agriffard** [comment]
Do we keep it explicit or with a version number?

In the 5.0 branch, we upgraded to C# 9.

**Comment by hishamco** [comment]
I think the implicit version will get the latest version without any modifications everytime

**Comment by deanmarcussen** [comment]
I would suggest keeping it explicit. 

If we're doing a 3.1 LTS release we don't want v9 code sneaking in accidentally if people are running betas.

**Comment by hishamco** [comment]
OK Dean

**Review by deanmarcussen — APPROVED** [review]

**Pull request merged**
